define APP_SCHEMA=APP_SCHEMA
grant select on RLE_RISK_LIMIT_EXPOSURE to &APP_SCHEMA;
grant select on RLT_RISK_LIMIT_TYPE to &APP_SCHEMA;
grant select on BLE_BROKER_LIMIT_EXPOSURE to &APP_SCHEMA;
grant select on CLE_CP_LIMIT_EXPOSURE to &APP_SCHEMA;