CREATE TABLE PFRD_PRICE_FIX_REPORT_DETAIL(
PROCESS_ID                         VARCHAR2(15),
EOD_TRADE_DATE                     DATE,
CORPORATE_ID                       VARCHAR2(15),
CORPORATE_NAME                     VARCHAR2(100),
PRODUCT_ID						   VARCHAR2(15),
PRODUCT_NAME                       VARCHAR2(200),
CP_ID                              VARCHAR2(15),
CP_NAME                            VARCHAR2(100),
INTERNAL_CONTRACT_REF_NO           VARCHAR2(15),
DELIVERY_ITEM_NO                   VARCHAR2(20),
CONTRACT_REF_NO_DEL_ITEM_NO        VARCHAR2(50),
PRICE_FIXED_DATE                   DATE,    
PF_REF_NO                          VARCHAR2(100),
FIXED_QTY                          NUMBER(25,10),
PRICE                              NUMBER(25,10),
PRICE_UNIT_ID                      VARCHAR2(15),
PRICE_UNIT_CUR_ID                  VARCHAR2(15),    
PRICE_UNIT_CUR_CODE                VARCHAR2(15),    
PRICE_UNIT_WEIGHT_UNIT_ID          VARCHAR2(15),    
PRICE_UNIT_WEIGHT_UNIT             VARCHAR2(15),    
PRICE_UNIT_WEIGHT                  NUMBER(7,2),
PRICE_UNIT_NAME                    VARCHAR2(50),
FX_PRICE_TO_BASE_CUR               NUMBER(25,10),
PRICE_IN_BASE_CUR                  NUMBER(25,10),
CONSUMED_QTY                       NUMBER(25,10));

CREATE TABLE TIP_TEMP_INSTRUMENT_PRICE(
CORPORATE_ID            VARCHAR2(15),
INSTRUMENT_ID           VARCHAR2(15),
PRICE                    NUMBER(25,5),
PRICE_UNIT_ID            VARCHAR2(15),
DATA_MISSING_FOR        VARCHAR2(500));