DELETE FROM CGAR_CORPORATE_GMR_ACTION_RULE WHERE PARENT_ACTION_ID ='airDetail' AND ACTION_ID = 'transshipDetail';
DELETE FROM CGAR_CORPORATE_GMR_ACTION_RULE WHERE PARENT_ACTION_ID ='railDetail' AND ACTION_ID = 'transshipDetail';
DELETE FROM CGAR_CORPORATE_GMR_ACTION_RULE WHERE PARENT_ACTION_ID ='truckDetail' AND ACTION_ID = 'transshipDetail';