update POFH_PRICE_OPT_FIXATION_HEADER pofh 
set POFH.QP_START_QTY = POFH.QTY_TO_BE_FIXED
where POFH.QP_START_QTY is null;

update POCH_PRICE_OPT_CALL_OFF_HEADER poch
set POCH.IS_BALANCE_PRICING='N'
where POCH.IS_BALANCE_PRICING is null;

update POFH_PRICE_OPT_FIXATION_HEADER pofh
set POFH.IS_PROVESIONAL_ASSAY_EXIST='N'
where POFH.IS_PROVESIONAL_ASSAY_EXIST is null;

update PFD_PRICE_FIXATION_DETAILS pfd
set PFD.HEDGE_CORRECTION_DATE = PFD.AS_OF_DATE;

update PFD_PRICE_FIXATION_DETAILS pfd
set PFD.FX_FIXATION_DATE = PFD.AS_OF_DATE
,PFD.FX_CORRECTION_DATE=PFD.AS_OF_DATE
where PFD.FX_RATE is not null;
