--- GMR-2380-BLD --

-- Pd
Insert into PQCA_PQ_CHEMICAL_ATTRIBUTES
   (PQCA_ID, ASM_ID, ELEMENT_ID, MIN_VALUE, MAX_VALUE, 
    UNIT_OF_MEASURE, IS_ELEM_FOR_PRICING, TYPICAL, REJECTION, VERSION, 
    IS_ACTIVE, FINALIZATION_METHOD, IS_ASSAY_EXCHANGE, IS_DEDUCTIBLE, PAYABLE_PERCENTAGE, 
    ORDERING, IS_RETURNABLE, ASSAY_WINNER, IS_FINAL_ASSAY, IS_PURE_FREE_METAL_ELEMENT, 
    IS_ELMNT_PART_OF_CTRCT_ASSAY, SPLIT_LIMIT, UMPIRE_ID, UMPIRE_NAME, UMPIRE_REF_NO)
 Values
   ('0000002', '101363', 'AML-365', 10, 70, 
    'RM-2', 'Y', 83, NULL, 0, 
    'Y', NULL, 'N', 'N', NULL, 
    NULL, NULL, NULL, 'N', NULL, 
    NULL, 2, NULL, NULL, NULL);

-- Pt
Insert into PQCA_PQ_CHEMICAL_ATTRIBUTES
   (PQCA_ID, ASM_ID, ELEMENT_ID, MIN_VALUE, MAX_VALUE, 
    UNIT_OF_MEASURE, IS_ELEM_FOR_PRICING, TYPICAL, REJECTION, VERSION, 
    IS_ACTIVE, FINALIZATION_METHOD, IS_ASSAY_EXCHANGE, IS_DEDUCTIBLE, PAYABLE_PERCENTAGE, 
    ORDERING, IS_RETURNABLE, ASSAY_WINNER, IS_FINAL_ASSAY, IS_PURE_FREE_METAL_ELEMENT, 
    IS_ELMNT_PART_OF_CTRCT_ASSAY, SPLIT_LIMIT, UMPIRE_ID, UMPIRE_NAME, UMPIRE_REF_NO)
 Values
   ('0000003', '101363', 'AML-366', 1, 5, 
    'RM-2', 'Y', 0, NULL, 0, 
    'Y', NULL, 'N', 'N', NULL, 
    NULL, NULL, NULL, 'N', NULL, 
    NULL, 1, NULL, NULL, NULL);

---- GMR-10608-BLD ---

-- Pt
update PQCA_PQ_CHEMICAL_ATTRIBUTES pqca set PQCA.TYPICAL=0 where PQCA.PQCA_ID='5594770';
update PQCA_PQ_CHEMICAL_ATTRIBUTES pqca set PQCA.TYPICAL=0 where PQCA.PQCA_ID='5594690';

-- Pd
update PQCA_PQ_CHEMICAL_ATTRIBUTES pqca set PQCA.TYPICAL=0 where PQCA.PQCA_ID='5594780';
update PQCA_PQ_CHEMICAL_ATTRIBUTES pqca set PQCA.TYPICAL=0 where PQCA.PQCA_ID='5594692';