create or replace view v_invoice_doc as
select 'Invoice' section_name,
       rownum record_no,
       isd.corporate_id,
       isd.corporate_name,
       isd.address1,
       isd.address2,
       isd.city,
       isd.state,
       isd.country,
       isd.logo_path,
       isd.phone_no,
       isd.fax_no,
       isd.internal_doc_ref_no,
       isd.due_date,
       isd.sales_purchase,
       isd.cp_name,
       isd.cp_item_stock_ref_no,
       isd.business_unit,
       isd.self_item_stock_ref_no,
       isd.inco_term_location,
       isd.self_contract_item_no,
       isd.contract_date,
       isd.notify_party,
       isd.org_name,
       isd.cp_contract_ref_no,
       isd.productandquality_name,
       isd.contract_tolerance,
       isd.contract_quantity,
       isd.contract_qty_unit,
       isd.provisional_invoice_no,
       isd.internal_invoice_ref_no,
       isd.product,
       isd.quality,
       isd.amount,
       isd.invoice_amount_unit,
       isd.payment_term,
       isd.invoice_creation_date,
       null    invoice_issue_date,
       isd.invoice_quantity,
       isd.invoice_dry_quantity,
       isd.invoice_wet_quantity,
       isd.invoiced_qty_unit,
       isd.moisture,
       isd.invoice_type,
       isd.stock_size,
       isd.packing,
       isd.provisional_price,
       isd.origin,
       isd.tarriff,
       isd.final_qty,
       isd.final_amount,
       isd.pi_number,
       isd.provisional_amount,
       null amount_due,
       isd.addditional_charges,
       isd.taxes,
       isd.product_type,
       isd.Invoice_Status,
        isd.gmr_ref_no pledge_gmr_ref_no,
       isd.gmr_quality pledge_gmr_qty,
       isd.stock_ref_no pledge_stock_ref_no,
       isd.stock_quantity pledge_stock_qty,
       isc.internal_doc_ref_no internal_doc_ref_no0,
       isc.stock_ref_no,
       isc.stock_qty,
       isc.gmr_ref_no,
       isc.gmr_quality,
       isc.gmr_quantity,
       isc.price_as_per_defind_uom,
       isc.item_amount_in_inv_cur,
       isc.invoiced_price_unit,
       null element_price_unit,
       isc.total_quantity,
       isc.gmr_qty_unit,
       isp_c1.internal_doc_ref_no internal_doc_ref_no1,
       isp_c1.benificiary_name_c1,
       isp_c1.bank_name_c1,
       isp_c1.account_no_c1,
       isp_c1.aba_rtn_c1,
       isp_c1.instruction_c1,
       isp_c2.internal_doc_ref_no internal_doc_ref_no2,
       isp_c2.benificiary_name_c2,
       isp_c2.bank_name_c2,
       isp_c2.account_no_c2,
       isp_c2.aba_rtn_c2,
       isp_c2.instruction_c2,
       is_cp.internal_doc_ref_no internal_doc_ref_no3,
       is_cp.stock_ref_no stock_ref_no1,
       is_cp.stock_qty stock_qty1,
       is_cp.gmr_qty_unit gmr_qty_unit1,
       is_cp.payable_element_id,
       is_cp.payable_element,
       is_cp.analysis,
       is_cp.analysis_unit,
       is_cp.element_price,
       is_cp.invoiced_price_unit invoiced_price_unit1,
       is_cp.element_price_unit element_price_unit1,
       is_cp.sub_lot_no,
       is_cp.element_inv_amount,
       is_cp.element_invoiced_qty,
       is_cp.element_invoiced_qty_unit,
       istc.internal_doc_ref_no internal_doc_ref_no4,
       istc.tc_element_id,
       istc.element_name,
       istc.tc_amount,
       istc.tc_amount_unit,
       isrc.internal_doc_ref_no internal_doc_ref_no5,
       isrc.rc_element_id,
       isrc.element_name element_name1,
       isrc.rc_amount,
       isrc.rc_amount_unit,
       null internal_doc_ref_no6,
       null pen_element_id,
       null element_name2,
       null pen_amount,
       null pen_amount_unit,
       vat.vat_no,
       vat.cp_vat_no,
       vat.vat_code,
       vat.vat_rate,
       vat.vat_rate_unit,
       vat.vat_amount,
       isd.invoice_amount_unit vat_amount_cur,
       isd.is_inv_draft,
       null cost_name,
       null charge_type,
       null charge_amount_rate,
       null fx_rate,
       null charges_quantity,
       null charges_amount,
       null charges_invoice_amount,
       null charges_invoice_cur_name,
       null tax_code,
       null tax_rate,
       null tax_currency,
       null taxes_fx_rate,
       null Applicable_on,
       null taxes_amount,
       null taxes_invoice_amount,
       null taxes_invoice_amount_cur,
       isd.is_free_metal,
       isd. is_pledge,
       isd.internal_comments,
       (case when  isd.sales_purchase='P' then
                isp_c1.remarks1
                when isd.sales_purchase='S' then
                isp_c2.remarks2 end) remarks,
        isc.yield
  from (select akc.corporate_id,
               akc.corporate_name,
               akc.address1,
               akc.address2,
               akc.city,
               akc.state,
               akc.country,
               akc.logo_path,
               akc.phone_no,
               akc.fax_no,
               isd.internal_doc_ref_no,
               isd.due_date,
               isd.sales_purchase,
               isd.cp_name,
               isd.supplire_invoice_no cp_item_stock_ref_no,
               '' business_unit,
               isd.self_item_stock_ref_no,
               isd.inco_term_location,
               isd.contract_ref_no self_contract_item_no,
               isd.contract_date,
               isd.notify_party,
               isd.org_name,
               isd.cp_contract_ref_no,
               isd.productandquality_name,
               isd.contract_tolerance,
               isd.contract_quantity,
               isd.contract_qty_unit,
               isd.invoice_ref_no provisional_invoice_no,
               isd.internal_invoice_ref_no,
               isd.product,
               isd.quality,
               isd.invoice_amount amount,
               isd.invoice_amount_unit,
               isd.payment_term,
               isd.invoice_creation_date,
               null invoice_issue_date,
               isd.invoice_quantity,
               isd.invoice_dry_quantity,
               isd.invoice_wet_quantity,
               isd.invoiced_qty_unit,
               isd.moisture,
               isd.invoice_type_name invoice_type,
               isd.stock_size,
               isd.packing,
               isd.provisional_price,
               isd.origin,
               isd.tarriff,
               '' final_qty,
               isd.material_cost final_amount,
               '' pi_number,
               '' provisional_amount,
               '' amount_due,
               isd.addditional_charges,
               isd.taxes,
               isd.contract_type product_type,
               isd.Invoice_Status,
               isd.is_inv_draft,
               isd. is_free_metal,
               isd. is_pledge,
               isd. internal_comments,
               isd.stock_quantity,
               isd.stock_ref_no,
               isd.gmr_quality,
               isd.gmr_ref_no
          from is_d isd,
               ds_document_summary ds,
               v_ak_corporate akc
         where isd.internal_doc_ref_no = ds.internal_doc_ref_no(+)
           and ds.corporate_id = akc.corporate_id(+)
          /* and akc.corporate_id = '{?CorporateID}'
           and isd.internal_doc_ref_no = '{?DocRefNo}'*/) isd,
       (select internal_doc_ref_no,
               stock_ref_no,
               stock_qty || '' || invoiced_qty_unit stock_qty,
               gmr_ref_no,
               gmr_quality,
               gmr_quantity,
               price_as_per_defind_uom,
               item_amount_in_inv_cur,
               invoiced_price_unit,
               total_price_qty total_quantity,
               gmr_qty_unit,
               yield
          from is_child_d) isc,
       (select isp_c1.internal_doc_ref_no,
               isp_c1.beneficiary_name benificiary_name_c1,
               isp_c1.bank_name bank_name_c1,
               isp_c1.account_no account_no_c1,
               isp_c1.aba_rtn aba_rtn_c1,
               isp_c1.instruction instruction_c1,
               isp_c1.remarks remarks1
          from is_bdp_child_d isp_c1) isp_c1,
       (select isp_c2.internal_doc_ref_no,
               isp_c2.beneficiary_name benificiary_name_c2,
               isp_c2.bank_name bank_name_c2,
               isp_c2.account_no account_no_c2,
               isp_c2.aba_rtn aba_rtn_c2,
               isp_c2.instruction instruction_c2,
                isp_c2.remarks remarks2
          from is_bds_child_d isp_c2) isp_c2,
       (select is_cp.internal_doc_ref_no,
               is_cp.stock_ref_no,
               is_cp.stock_qty,
               is_cp.gmr_qty_unit,
               is_cp.element_id payable_element_id,
               is_cp.element_name payable_element,
               is_cp.assay_content analysis,
               is_cp.assay_content_unit analysis_unit,
               is_cp.invoice_price element_price,
               is_cp.invoiced_price_unit,
               is_cp.element_price_unit,
               is_cp.sub_lot_no,
               is_cp.element_inv_amount,
               is_cp.element_invoiced_qty,
               is_cp.element_invoiced_qty_unit
          from is_conc_payable_child is_cp) is_cp,
       (select istc.internal_doc_ref_no,
               istc.element_id tc_element_id,
               istc.element_name,
               istc.sub_lot_no,
               sum(istc.tc_amount) tc_amount,
               istc.amount_unit tc_amount_unit
          from is_conc_tc_child istc
         group by istc.internal_doc_ref_no,
                  istc.element_id,istc.sub_lot_no,
                  istc.element_name,
                  istc.amount_unit) istc,
       (select isrc.internal_doc_ref_no,
               isrc.element_id rc_element_id,
               isrc.element_name,
               isrc.sub_lot_no,
               sum(isrc.rc_amount) rc_amount,
               isrc.amount_unit rc_amount_unit
          from is_conc_rc_child isrc
         group by isrc.internal_doc_ref_no,isrc.sub_lot_no,
                  isrc.element_id,
                  isrc.element_name,
                  isrc.amount_unit) isrc,
     (select vat.internal_invoice_ref_no,
                       vat.our_vat_no vat_no,
                       vat.cp_vat_no,
                       vat.vat_code,
                       vat.vat_rate,
                       vat.vat_rate_unit,
                       vat.vat_amount_in_inv_cur vat_amount
                  from ivd_invoice_vat_details vat
                 where vat.is_separate_invoice = 'N')vat
 where isd.internal_doc_ref_no = isp_c2.internal_doc_ref_no(+)
   and isd.internal_doc_ref_no = isc.internal_doc_ref_no(+)
   and isd.internal_doc_ref_no = isp_c1.internal_doc_ref_no(+)
   and isd.internal_doc_ref_no = is_cp.internal_doc_ref_no(+)
   and is_cp.internal_doc_ref_no = istc.internal_doc_ref_no(+)
   and is_cp.payable_element_id = istc.tc_element_id(+)
   and is_cp.sub_lot_no = istc.sub_lot_no(+)
   and is_cp.internal_doc_ref_no = isrc.internal_doc_ref_no(+)
   and is_cp.payable_element_id = isrc.rc_element_id(+)
   and is_cp.sub_lot_no = isrc.sub_lot_no(+)
   and isd.internal_invoice_ref_no = vat.internal_invoice_ref_no(+)
union all
select 'Penality' section_name,
       rownum record_no,
       akc.corporate_id,
       akc.corporate_name,
       akc.address1,
       akc.address2,
       akc.city,
       akc.state,
       akc.country,
       akc.logo_path,
       akc.phone_no,
       akc.fax_no,
       isd.internal_doc_ref_no,
       isd.due_date,
       isd.sales_purchase,
       isd.cp_name,
       isd.supplire_invoice_no cp_item_stock_ref_no,
       '' business_unit,
       isd.self_item_stock_ref_no,
       isd.inco_term_location,
       isd.contract_ref_no self_contract_item_no,
       isd.contract_date,
       isd.notify_party,
       isd.org_name,
       isd.cp_contract_ref_no,
       isd.productandquality_name,
       isd.contract_tolerance,
       isd.contract_quantity,
       isd.contract_qty_unit,
       isd.invoice_ref_no provisional_invoice_no,
       isd.internal_invoice_ref_no,
       isd.product,
       isd.quality,
       isd.invoice_amount amount,
       isd.invoice_amount_unit,
       isd.payment_term,
       isd.invoice_creation_date,
       null invoice_issue_date,
       isd.invoice_quantity,
       isd.invoice_dry_quantity,
       isd.invoice_wet_quantity,
       isd.invoiced_qty_unit,
       isd.moisture,
       isd.invoice_type_name invoice_type,
       isd.stock_size,
       isd.packing,
       isd.provisional_price,
       isd.origin,
       isd.tarriff,
       isd.material_cost final_qty,
       '' final_amount,
       '' pi_number,
       '' provisional_amount,
       null amount_due,
       isd.addditional_charges,
       isd.taxes,
       isd.contract_type product_type,
       isd.Invoice_Status,
       null pledge_gmr_ref_no,
       null  pledge_gmr_qty,
       null  pledge_stock_ref_no,
       null  pledge_stock_qty,
       null internal_doc_ref_no0,
       null stock_ref_no,
       null stock_qty,
       null gmr_ref_no,
       null gmr_quality,
       null gmr_quantity,
       null price_as_per_defind_uom,
       null item_amount_in_inv_cur,
       null invoiced_price_unit,
       null element_price_unit,
       null total_quantity,
       null gmr_qty_unit,
       null internal_doc_ref_no1,
       null benificiary_name_c1,
       null bank_name_c1,
       null account_no_c1,
       null aba_rtn_c1,
       null instruction_c1,
       null internal_doc_ref_no2,
       null benificiary_name_c2,
       null bank_name_c2,
       null account_no_c2,
       null aba_rtn_c2,
       null instruction_c2,
       null internal_doc_ref_no3,
       null stock_ref_no1,
       null stock_qty1,
       null gmr_qty_unit1,
       null payable_element_id,
       null payable_element,
       null analysis,
       null analysis_unit,
       null element_price,
       null invoiced_price_unit1,
       null element_price_unit1,
       null sub_lot_no,
       null element_inv_amount,
       null element_invoiced_qty,
       null element_invoiced_qty_unit,
       null internal_doc_ref_no4,
       null tc_element_id,
       null element_name,
       null tc_amount,
       null tc_amount_unit,
       null internal_doc_ref_no5,
       null rc_element_id,
       null element_name1,
       null rc_amount,
       null rc_amount_unit,
       isp.internal_doc_ref_no internal_doc_ref_no6,
       isp.pen_element_id,
       isp.element_name element_name2,
       isp.pen_amount,
       isp.pen_amount_unit,
       null vat_no,
       null cp_vat_no,
       null vat_code,
       null vat_rate,
       null vat_rate_unit,
       null vat_amount,
       null vat_amount_cur,
       isd.is_inv_draft,
       null cost_name,
       null charge_type,
       null charge_amount_rate,
       null fx_rate,
       null charges_quantity,
       null charges_amount,
       null charges_invoice_amount,
       null charges_invoice_cur_name,
       null tax_code,
       null tax_rate,
       null tax_currency,
       null taxes_fx_rate,
       null Applicable_on,
       null taxes_amount,
       null taxes_invoice_amount,
       null taxes_invoice_amount_cur,
       isd. is_free_metal,
       isd. is_pledge,
       isd. internal_comments,
       null remarks,
       null yield
  from is_d isd,
       ds_document_summary ds,
       v_ak_corporate akc,
       (select isp.internal_doc_ref_no,
               isp.element_id pen_element_id,
               isp.element_name,
               sum(isp.penalty_amount) pen_amount,
               isp.amount_unit pen_amount_unit
          from is_conc_penalty_child isp
         group by isp.internal_doc_ref_no,
                  isp.element_id,
                  isp.element_name,
                  isp.amount_unit) isp
 where isd.internal_doc_ref_no = ds.internal_doc_ref_no
   and ds.corporate_id = akc.corporate_id(+)
   /*and akc.corporate_id = '{?CorporateID}'
   and isp.internal_doc_ref_no = '{?DocRefNo}'*/
   and isd.internal_doc_ref_no = isp.internal_doc_ref_no
union all
select 'Provisional' section_name,
       rownum record_no,
       akc.corporate_id,
       akc.corporate_name,
       akc.address1,
       akc.address2,
       akc.city,
       akc.state,
       akc.country,
       akc.logo_path,
       akc.phone_no,
       akc.fax_no,
       isd.internal_doc_ref_no,
       isd.due_date,
       isd.sales_purchase,
       isd.cp_name,
       isd.supplire_invoice_no cp_item_stock_ref_no,
       '' business_unit,
       isd.self_item_stock_ref_no,
       isd.inco_term_location,
       isd.contract_ref_no self_contract_item_no,
       isd.contract_date,
       isd.notify_party,
       isd.org_name,
       isd.cp_contract_ref_no,
       isd.productandquality_name,
       isd.contract_tolerance,
       isd.contract_quantity,
       isd.contract_qty_unit,
       isd.invoice_ref_no provisional_invoice_no,
       isd.internal_invoice_ref_no,
       isd.product,
       isd.quality,
       isd.invoice_amount amount,
       isd.invoice_amount_unit,
       isd.payment_term,
       isd.invoice_creation_date,
       null invoice_issue_date,
       isd.invoice_quantity,
       isd.invoice_dry_quantity,
       isd.invoice_wet_quantity,
       isd.invoiced_qty_unit,
       isd.moisture,
       isd.invoice_type_name invoice_type,
       isd.stock_size,
       isd.packing,
       isd.provisional_price,
       isd.origin,
       isd.tarriff,
       isd.invoice_quantity final_qty,
       isd.material_cost final_amount,
       ispcd.invoice_ref_no pi_number,
       ispcd.invoice_amount provisional_amount,
       isd.invoice_amount amount_due,
       isd.addditional_charges,
       isd.taxes,
       isd.contract_type product_type,
       isd.Invoice_Status,
       null pledge_gmr_ref_no,
       null  pledge_gmr_qty,
       null  pledge_stock_ref_no,
       null  pledge_stock_qty,
       null internal_doc_ref_no0,
       null stock_ref_no,
       null stock_qty,
       null gmr_ref_no,
       null gmr_quality,
       null gmr_quantity,
       null price_as_per_defind_uom,
       null item_amount_in_inv_cur,
       null invoiced_price_unit,
       null element_price_unit,
       null total_quantity,
       null gmr_qty_unit,
       null internal_doc_ref_no1,
       isp_c1.benificiary_name_c1,
       isp_c1.bank_name_c1,
       isp_c1.account_no_c1,
       isp_c1.aba_rtn_c1,
       isp_c1.instruction_c1,
       null internal_doc_ref_no2,
       isp_c2.benificiary_name_c2,
       isp_c2.bank_name_c2,
       isp_c2.account_no_c2,
       isp_c2.aba_rtn_c2,
       isp_c2.instruction_c2,
       null internal_doc_ref_no,
       null stock_ref_no1,
       null stock_qty1,
       null gmr_qty_unit1,
       null payable_element_id,
       null payable_element,
       null analysis,
       null analysis_unit,
       null element_price,
       null element_price_unit1,
       null invoiced_price_unit1,
       null sub_lot_no,
       null element_inv_amount,
       null element_invoiced_qty,
       null element_invoiced_qty_unit,
       null internal_doc_ref_no4,
       null tc_element_id,
       null element_name,
       null tc_amount,
       null tc_amount_unit,
       null internal_doc_ref_no5,
       null rc_element_id,
       null element_name1,
       null rc_amount,
       null rc_amount_unit,
       null internal_doc_ref_no6,
       null pen_element_id,
       null element_name2,
       null pen_amount,
       null pen_amount_unit,
       vat.vat_no,
       vat.cp_vat_no,
       vat.vat_code,
       vat.vat_rate,
       vat.vat_rate_unit,
       vat.vat_amount,
       isd.invoice_amount_unit vat_amount_cur,
       isd.is_inv_draft,
       null cost_name,
       null charge_type,
       null charge_amount_rate,
       null fx_rate,
       null charges_quantity,
       null charges_amount,
       null charges_invoice_amount,
       null charges_invoice_cur_name,
       null tax_code,
       null tax_rate,
       null tax_currency,
       null taxes_fx_rate,
       null Applicable_on,
       null taxes_amount,
       null taxes_invoice_amount,
       null taxes_invoice_amount_cur,
        isd. is_free_metal,
        isd. is_pledge,
        isd. internal_comments,
        (case when  isd.sales_purchase='P' then
                isp_c1.remarks1
                when isd.sales_purchase='S' then
                isp_c2.remarks2 end) remarks,
        null yield
  from is_d isd,
       ds_document_summary ds,
       v_ak_corporate akc,
       (select ispcd.internal_doc_ref_no,
               ispcd.invoice_ref_no,
               ispcd.invoice_amount,
               ispcd.invoice_currency
          from is_parent_child_d ispcd) ispcd,
          (select isp_c1.internal_doc_ref_no,
               isp_c1.beneficiary_name benificiary_name_c1,
               isp_c1.bank_name bank_name_c1,
               isp_c1.account_no account_no_c1,
               isp_c1.aba_rtn aba_rtn_c1,
               isp_c1.instruction instruction_c1,
               isp_c1.remarks remarks1
          from is_bdp_child_d isp_c1) isp_c1,
       (select isp_c2.internal_doc_ref_no,
               isp_c2.beneficiary_name benificiary_name_c2,
               isp_c2.bank_name bank_name_c2,
               isp_c2.account_no account_no_c2,
               isp_c2.aba_rtn aba_rtn_c2,
               isp_c2.instruction instruction_c2,
               isp_c2.remarks remarks2
          from is_bds_child_d isp_c2) isp_c2,
         (select vat.internal_invoice_ref_no,
                   vat.our_vat_no vat_no,
                   vat.cp_vat_no,
                   vat.vat_code,
                   vat.vat_rate,
                   vat.vat_rate_unit,
                   vat.vat_amount_in_inv_cur vat_amount
              from ivd_invoice_vat_details vat
             where vat.is_separate_invoice = 'N')vat
 where isd.internal_doc_ref_no = ds.internal_doc_ref_no
   and ds.corporate_id = akc.corporate_id(+)
   /*and akc.corporate_id = '{?CorporateID}'
   and isd.internal_doc_ref_no = '{?DocRefNo}'*/
   and isd.internal_doc_ref_no = ispcd.internal_doc_ref_no
   and isd.internal_invoice_ref_no = vat.internal_invoice_ref_no(+)
   and isd.internal_doc_ref_no = isp_c1.internal_doc_ref_no(+)
   and isd.internal_doc_ref_no = isp_c2.internal_doc_ref_no(+)
union all
select 'Other Charges' section_name,
       rownum record_no,
       ioc.corporate_id,
       ioc.corporate_name,
       ioc.address1,
       ioc.address2,
       ioc.city,
       ioc.state,
       ioc.country,
       ioc.logo_path,
       ioc.phone_no,
       ioc.fax_no,
       ioc.internal_doc_ref_no,
       ioc.due_date,
       ioc.sales_purchase,
       ioc.cp_name,
       ioc.cp_item_stock_ref_no,
       ioc.business_unit,
       ioc.self_item_stock_ref_no,
       ioc.inco_term_location,
       ioc.self_contract_item_no,
       ioc.contract_date,
       ioc.notify_party,
       ioc.org_name,
       ioc.cp_contract_ref_no,
       ioc.productandquality_name,
       ioc.contract_tolerance,
       ioc.contract_quantity,
       ioc.contract_qty_unit,
       ioc.provisional_invoice_no,
       ioc.internal_invoice_ref_no,
       ioc.product,
       ioc.quality,
       ioc.amount,
       ioc.invoice_amount_unit,
       ioc.payment_term,
       ioc.invoice_creation_date,
       null invoice_issue_date,
       ioc.invoice_quantity,
       ioc.invoice_dry_quantity,
       ioc.invoice_wet_quantity,
       ioc.invoiced_qty_unit,
       ioc.moisture,
       ioc.invoice_type,
       ioc.stock_size,
       ioc.packing,
       ioc.provisional_price,
       ioc.origin,
       ioc.tarriff,
       ioc.final_qty,
       ioc.final_amount,
       ioc.pi_number,
       ioc.provisional_amount,
       ioc.amount_due,
       ioc.addditional_charges,
       ioc.taxes,
       ioc.product_type,
       ioc.Invoice_Status,
       null pledge_gmr_ref_no,
       null  pledge_gmr_qty,
       null  pledge_stock_ref_no,
       null  pledge_stock_qty,
       null internal_doc_ref_no0,
       null stock_ref_no,
       null stock_qty,
       null gmr_ref_no,
       null gmr_quality,
       null gmr_quantity,
       null price_as_per_defind_uom,
       null item_amount_in_inv_cur,
       null invoiced_price_unit,
       null element_price_unit,
       null total_quantity,
       null gmr_qty_unit,
       null internal_doc_ref_no1,
       null benificiary_name_c1,
       null bank_name_c1,
       null account_no_c1,
       null aba_rtn_c1,
       null instruction_c1,
       null internal_doc_ref_no2,
       null benificiary_name_c2,
       null bank_name_c2,
       null account_no_c2,
       null aba_rtn_c2,
       null instruction_c2,
       null internal_doc_ref_no3,
       null stock_ref_no1,
       null stock_qty1,
       null gmr_qty_unit1,
       null payable_element_id,
       null payable_element,
       null analysis,
       null analysis_unit,
       null element_price,
       null invoiced_price_unit1,
       null element_price_unit1,
       null sub_lot_no,
       null element_inv_amount,
       null element_invoiced_qty,
       null element_invoiced_qty_unit,
       null internal_doc_ref_no4,
       null tc_element_id,
       null element_name,
       null tc_amount,
       null tc_amount_unit,
       null internal_doc_ref_no5,
       null rc_element_id,
       null element_name1,
       null rc_amount,
       null rc_amount_unit,
       null internal_doc_ref_no6,
       null pen_element_id,
       null element_name2,
       null pen_amount,
       null pen_amount_unit,
       null vat_no,
       null cp_vat_no,
       null vat_code,
       null vat_rate,
       null vat_rate_unit,
       null vat_amount,
       null vat_amount_cur,
       ioc.is_inv_draft,
       ioc.cost_name,
       ioc.charge_type,
       ioc.charge_amount_rate,
       ioc.fx_rate,
       ioc.charges_quantity,
       ioc.charges_amount,
       ioc.charges_invoice_amount,
       ioc.charges_invoice_cur_name,
       null tax_code,
       null tax_rate,
       null tax_currency,
       null taxes_fx_rate,
       null Applicable_on,
       null taxes_amount,
       null taxes_invoice_amount,
       null taxes_invoice_amount_cur,
       ioc. is_free_metal,
       ioc. is_pledge,
       ioc. internal_comments,
       null remarks,
      null yield
  from (select
               akc.corporate_id,
               akc.corporate_name,
               akc.address1,
               akc.address2,
               akc.city,
               akc.state,
               akc.country,
               akc.logo_path,
               akc.phone_no,
               akc.fax_no,
               isd.internal_doc_ref_no,
               isd.due_date,
               isd.sales_purchase,
               isd.cp_name,
               isd.supplire_invoice_no cp_item_stock_ref_no,
               '' business_unit,
               isd.self_item_stock_ref_no,
               isd.inco_term_location,
               isd.contract_ref_no self_contract_item_no,
               isd.contract_date,
               isd.notify_party,
               isd.org_name,
               isd.cp_contract_ref_no,
               isd.productandquality_name,
               isd.contract_tolerance,
               isd.contract_quantity,
               isd.contract_qty_unit,
               isd.invoice_ref_no provisional_invoice_no,
               isd.internal_invoice_ref_no,
               isd.product,
               isd.quality,
               isd.invoice_amount amount,
               isd.invoice_amount_unit,
               isd.payment_term,
               isd.invoice_creation_date,
               isd.invoice_quantity,
               isd.invoice_dry_quantity,
               isd.invoice_wet_quantity,
               isd.invoiced_qty_unit,
               isd.moisture,
               isd.invoice_type_name invoice_type,
               isd.stock_size,
               isd.packing,
               isd.provisional_price,
               isd.origin,
               isd.tarriff,
               '' final_qty,
               isd.material_cost final_amount,
               '' pi_number,
               '' provisional_amount,
               '' amount_due,
               isd.addditional_charges,
               isd.taxes,
               isd.contract_type product_type,
               isd.Invoice_Status,
               isd.is_inv_draft,
               ioc.other_charge_cost_name cost_name,
               ioc.charge_type,
               '' charge_amount_rate,
               ioc.fx_rate,
               ioc.quantity charges_quantity,
               ioc.amount charges_amount,
               ioc.invoice_amount charges_invoice_amount,
               ioc.invoice_cur_name charges_invoice_cur_name,
               isd. is_free_metal,
               isd. is_pledge,
               isd. internal_comments,
               null remarks
              from ioc_d ioc,
                   is_d isd,
                   ds_document_summary ds,
                   v_ak_corporate akc
             where ioc.internal_doc_ref_no = ds.internal_doc_ref_no
                and isd.internal_doc_ref_no = ioc.internal_doc_ref_no
              and ds.corporate_id = akc.corporate_id(+))ioc
union all
select 'Other Taxes' section_name,
       rownum record_no,
       ioc.corporate_id,
       ioc.corporate_name,
       ioc.address1,
       ioc.address2,
       ioc.city,
       ioc.state,
       ioc.country,
       ioc.logo_path,
       ioc.phone_no,
       ioc.fax_no,
       ioc.internal_doc_ref_no,
       ioc.due_date,
       ioc.sales_purchase,
       ioc.cp_name,
       ioc.cp_item_stock_ref_no,
       ioc.business_unit,
       ioc.self_item_stock_ref_no,
       ioc.inco_term_location,
       ioc.self_contract_item_no,
       ioc.contract_date,
       ioc.notify_party,
       ioc.org_name,
       ioc.cp_contract_ref_no,
       ioc.productandquality_name,
       ioc.contract_tolerance,
       ioc.contract_quantity,
       ioc.contract_qty_unit,
       ioc.provisional_invoice_no,
       ioc.internal_invoice_ref_no,
       ioc.product,
       ioc.quality,
       ioc.amount,
       ioc.invoice_amount_unit,
       ioc.payment_term,
       ioc.invoice_creation_date,
       null invoice_issue_date,
       ioc.invoice_quantity,
       ioc.invoice_dry_quantity,
       ioc.invoice_wet_quantity,
       ioc.invoiced_qty_unit,
       ioc.moisture,
       ioc.invoice_type,
       ioc.stock_size,
       ioc.packing,
       ioc.provisional_price,
       ioc.origin,
       ioc.tarriff,
       ioc.final_qty,
       ioc.final_amount,
       ioc.pi_number,
       ioc.provisional_amount,
       ioc.amount_due,
       ioc.addditional_charges,
       ioc.taxes,
       ioc.product_type,
       ioc.Invoice_Status,
       null pledge_gmr_ref_no,
       null  pledge_gmr_qty,
       null  pledge_stock_ref_no,
       null  pledge_stock_qty,
       null internal_doc_ref_no0,
       null stock_ref_no,
       null stock_qty,
       null gmr_ref_no,
       null gmr_quality,
       null gmr_quantity,
       null price_as_per_defind_uom,
       null item_amount_in_inv_cur,
       null invoiced_price_unit,
       null element_price_unit,
       null total_quantity,
       null gmr_qty_unit,
       null internal_doc_ref_no1,
       null benificiary_name_c1,
       null bank_name_c1,
       null account_no_c1,
       null aba_rtn_c1,
       null instruction_c1,
       null internal_doc_ref_no2,
       null benificiary_name_c2,
       null bank_name_c2,
       null account_no_c2,
       null aba_rtn_c2,
       null instruction_c2,
       null internal_doc_ref_no3,
       null stock_ref_no1,
       null stock_qty1,
       null gmr_qty_unit1,
       null payable_element_id,
       null payable_element,
       null analysis,
       null analysis_unit,
       null element_price,
       null invoiced_price_unit1,
       null element_price_unit1,
       null sub_lot_no,
       null element_inv_amount,
       null element_invoiced_qty,
       null element_invoiced_qty_unit,
       null internal_doc_ref_no4,
       null tc_element_id,
       null element_name,
       null tc_amount,
       null tc_amount_unit,
       null internal_doc_ref_no5,
       null rc_element_id,
       null element_name1,
       null rc_amount,
       null rc_amount_unit,
       null internal_doc_ref_no6,
       null pen_element_id,
       null element_name2,
       null pen_amount,
       null pen_amount_unit,
       null vat_no,
       null cp_vat_no,
       null vat_code,
       null vat_rate,
       null vat_rate_unit,
       null vat_amount,
       null vat_amount_cur,
       ioc.is_inv_draft,
       null cost_name,
       null charge_type,
       null charge_amount_rate,
       null fx_rate,
       null charges_quantity,
       null charges_amount,
       null charges_invoice_amount,
       null charges_invoice_cur_name,
       ioc.tax_code,
       ioc.tax_rate,
       ioc.tax_currency,
       ioc.taxes_fx_rate,
       ioc.Applicable_on,
       ioc.taxes_amount,
       ioc.taxes_invoice_amount,
       ioc.taxes_invoice_amount_cur,
        ioc. is_free_metal,
        ioc. is_pledge,
        ioc. internal_comments,
       null remarks,
       null yield
  from (select
               akc.corporate_id,
               akc.corporate_name,
               akc.address1,
               akc.address2,
               akc.city,
               akc.state,
               akc.country,
               akc.logo_path,
               akc.phone_no,
               akc.fax_no,
               isd.internal_doc_ref_no,
               isd.due_date,
               isd.sales_purchase,
               isd.cp_name,
               isd.supplire_invoice_no cp_item_stock_ref_no,
               '' business_unit,
               isd.self_item_stock_ref_no,
               isd.inco_term_location,
               isd.contract_ref_no self_contract_item_no,
               isd.contract_date,
               isd.notify_party,
               isd.org_name,
               isd.cp_contract_ref_no,
               isd.productandquality_name,
               isd.contract_tolerance,
               isd.contract_quantity,
               isd.contract_qty_unit,
               isd.invoice_ref_no provisional_invoice_no,
               isd.internal_invoice_ref_no,
               isd.product,
               isd.quality,
               isd.invoice_amount amount,
               isd.invoice_amount_unit,
               isd.payment_term,
               isd.invoice_creation_date,
               isd.invoice_quantity,
               isd.invoice_dry_quantity,
               isd.invoice_wet_quantity,
               isd.invoiced_qty_unit,
               isd.moisture,
               isd.invoice_type_name invoice_type,
               isd.stock_size,
               isd.packing,
               isd.provisional_price,
               isd.origin,
               isd.tarriff,
               '' final_qty,
               isd.material_cost final_amount,
               '' pi_number,
               '' provisional_amount,
               '' amount_due,
               isd.addditional_charges,
               isd.taxes,
               isd.contract_type product_type,
               isd.Invoice_Status,
               isd.is_inv_draft,
               itd.tax_code,
               itd.tax_rate,
               itd.tax_currency,
               itd.fx_rate taxes_fx_rate,
               '' Applicable_on,
               itd.amount taxes_amount,
               itd.invoice_amount taxes_invoice_amount,
               itd.invoice_currency taxes_invoice_amount_cur,
               isd. is_free_metal,
               isd. is_pledge,
               isd. internal_comments,
               null remarks
              from itd_d itd,
                   is_d isd,
                   ds_document_summary ds,
                   v_ak_corporate akc
             where itd.internal_doc_ref_no = ds.internal_doc_ref_no
                and isd.internal_doc_ref_no = itd.internal_doc_ref_no
              and ds.corporate_id = akc.corporate_id(+))ioc

