DROP MATERIALIZED VIEW MV_BI_HEDGED_UNHEDGED_POSITION;
CREATE MATERIALIZED VIEW MV_BI_HEDGED_UNHEDGED_POSITION
REFRESH FORCE ON DEMAND
START WITH TO_DATE('05-03-2012 21:02:24', 'DD-MM-YYYY HH24:MI:SS') NEXT SYSDATE+5/1440 
AS
SELECT * FROM V_BI_HEDGED_UNHEDGED_POSITION
