drop materialized view mv_bi_cpd_currency_pnl_daily;
create materialized view mv_bi_cpd_currency_pnl_daily
refresh force on demand
as
select 
cpd.ct_internal_ref_no,
tdc.corporate_id,
cpd.corporate_name,
cpd.eod_trade_date,
tdc.trade_date,
cpd.ct_ref_no,
cpd.profit_center_id,
cpd.profit_center_name,
cpd.strategy_id,
cpd.strategy_name,
cpd.ct_id,
cpd.cfq_id,
cpd.instrument_id,
cpd.instrument_name,
cpd.instrument_type,
cpd.currency_def_id,
cpd.derivative_name,
cpd.product_name,
cpd.prompt_date,
cpd.expiry_date,
cpd.pnl_type,
cpd.home_currency_amount,
cpd.home_cur_buy_sell,
cpd.home_currency,
cpd.home_cur_id,
cpd.market_exchange_rate,
cpd.original_exchange_rate,
cpd.fx_cur_id,
cpd.fx_currency,
cpd.fx_currency_amount,
cpd.fx_cur_buy_sell,
cpd.bank_name,
cpd.bank_account,
cpd.account_no,
cpd.account_name,
cpd.bank_charges,
cpd.bank_charges_currency,
cpd.bank_charges_type,
cpd.bank_charges_cur_id,
cpd.bank_charges_percent,
cpd.ex_rate_from_bank_to_home_cur,
cpd.market_value_in_home_currency,
cpd.original_value_in_home_curr,
cpd.pnl_value_in_home_currency,
cpd.bank_charges_in_home_currency,
cpd.net_pnl_in_home_currency,
cpd.dbd_id,
cpd.process_id,
cpd.user_entered_fx,
cpd.profit_center_short_name,
cpd.corp_fx_rate,
cpd.net_pnl_in_corp_currency,
cpd.corp_cur_id,
cpd.corp_currency,
cpd.pnl_in_corp_currency,
cpd.payment_terms_id
from cpd_currency_pnl_daily@eka_eoddb cpd,
       tdc_trade_date_closure@eka_eoddb tdc
where cpd.corporate_id = tdc.corporate_id
   AND cpd.process_id = tdc.process_id
   and tdc.process = 'EOD';
