CREATE MATERIALIZED VIEW MV_BI_LOGISTICS_INVENTORY
REFRESH FORCE ON DEMAND
START WITH TO_DATE('17-02-2012 20:11:08', 'DD-MM-YYYY HH24:MI:SS') NEXT SYSDATE+5/1440 
AS
SELECT * FROM V_BI_LOGISTICS_INVENTORY
