create or replace view v_invoice_doc as
select        'Invoice' section_name,
              'Invoice' sub_section,
               rownum record_no,
               akc.corporate_id,
               akc.corporate_name,
               akc.address1,
               akc.address2,
               akc.city,
               akc.state,
               akc.country,
               akc.logo_path,
               akc.phone_no,
               akc.fax_no,
               isd.internal_doc_ref_no,
               isd.due_date,
               isd.sales_purchase,
               isd.cp_name,
               isd.supplire_invoice_no cp_item_stock_ref_no,
               '' business_unit,
               isd.self_item_stock_ref_no,
               isd.inco_term_location,
               isd.contract_ref_no self_contract_item_no,
               isd.contract_date,
               isd.notify_party,
               isd.org_name,
               isd.cp_contract_ref_no,
               isd.productandquality_name,
               isd.contract_tolerance,
               isd.contract_quantity,
               isd.contract_qty_unit,
               isd.invoice_ref_no provisional_invoice_no,
               isd.internal_invoice_ref_no,
               isd.product,
               isd.quality,
               isd.invoice_amount amount,
               isd.invoice_amount_unit,
               isd.payment_term,
               isd.invoice_creation_date,
               null invoice_issue_date,
               isd.invoice_quantity,
               isd.invoice_dry_quantity,
               isd.invoice_wet_quantity,
               isd.invoiced_qty_unit,
               isd.moisture,
               isd.invoice_type_name invoice_type,
               isd.stock_size,
               isd.packing,
               isd.provisional_price,
               isd.origin,
               isd.tarriff,
               '' final_qty,
               isd.material_cost final_amount,
               ispcd.invoice_ref_no pi_number,
               ispcd.invoice_amount provisional_amount,
               '' amount_due,
               isd.addditional_charges,
               isd.taxes,
               isd.contract_type product_type,
               isd.Invoice_Status,
               isd.gmr_ref_no pledge_gmr_ref_no,
               isd.gmr_quality pledge_gmr_qty,
               isd.stock_ref_no pledge_stock_ref_no,
               isd.stock_quantity pledge_stock_qty,
               isc.internal_doc_ref_no internal_doc_ref_no0,
               isc.stock_ref_no,
               isc.stock_qty || '' || isc.invoiced_qty_unit stock_qty,
               isc.gmr_ref_no,
               isc.gmr_quality,
               isc.gmr_quantity,
               isc.price_as_per_defind_uom,
               isc.item_amount_in_inv_cur,
               isc.invoiced_price_unit,
               null element_price_unit,
               isc.total_price_qty total_quantity,
               isc.gmr_qty_unit,
               isp_c1.internal_doc_ref_no internal_doc_ref_no1,
               isp_c1.beneficiary_name benificiary_name_c1,
               isp_c1.bank_name bank_name_c1,
               isp_c1.account_no account_no_c1,
               isp_c1.iban iban_c1,
               isp_c1.aba_rtn aba_rtn_c1,
               isp_c1.instruction instruction_c1,
               isp_c2.internal_doc_ref_no internal_doc_ref_no2,
               isp_c2.beneficiary_name benificiary_name_c2,
               isp_c2.bank_name bank_name_c2,
               isp_c2.account_no account_no_c2,
               isp_c2.iban iban_c2,
               isp_c2.aba_rtn aba_rtn_c2,
               isp_c2.instruction instruction_c2,
               is_cp.internal_doc_ref_no internal_doc_ref_no3,
               is_cp.stock_ref_no stock_ref_no1,
               is_cp.gmr_ref_no stock_gmr_ref_no,
               is_cp.gmr_quantity cp_gmr_quantity,
               is_cp.stock_qty stock_qty1,
               is_cp.gmr_qty_unit gmr_qty_unit1,
               is_cp.element_id payable_element_id,
               is_cp.element_name payable_element,
               is_cp.assay_content analysis,
               is_cp.assay_content_unit analysis_unit,
               is_cp.invoice_price element_price,
               is_cp.invoiced_price_unit invoiced_price_unit1,
               is_cp.element_price_unit element_price_unit1,
               is_cp.sub_lot_no,
               is_cp.element_inv_amount,
               is_cp.element_invoiced_qty,
               is_cp.element_invoiced_qty_unit,
               null internal_doc_ref_no4,
               null tc_element_id,
               null element_name,
               null tc_rc_sub_lot_no,
               null tc_amount,
               null tc_amount_unit,
               null internal_doc_ref_no5,
               null rc_element_id,
               null element_name1,
               null rc_amount,
               null rc_amount_unit,
               null internal_doc_ref_no6,
               null pen_element_id,
               null element_name2,
               null pen_amount,
               null pen_amount_unit,
               vat.vat_no,
               vat.cp_vat_no,
               vat.vat_code,
               vat.vat_rate,
               vat.vat_rate_unit,
               vat.vat_amount,
               isd.invoice_amount_unit vat_amount_cur,
               isd.is_inv_draft,
               null cost_name,
               null charge_type,
               null charge_amount_rate,
               null charge_amount_rate_unit,
               null fx_rate,
               null charges_quantity,
               null charges_qty_unit,
               null charges_amount,
               null charge_amount_unit,
               null charges_invoice_amount,
               null charges_invoice_cur_name,
               null tax_code,
               null tax_rate,
               null tax_currency,
               null taxes_fx_rate,
               null Applicable_on,
               null taxes_amount,
               null taxes_amount_unit,
               null taxes_invoice_amount,
               null taxes_invoice_amount_cur,
               isd.is_free_metal,
               isd.is_pledge,
               isd.internal_comments,
               (case when  isd.sales_purchase='P' then
                        isp_c1.remarks
                        when isd.sales_purchase='S' then
                        isp_c2.remarks end) remarks,
                isc.yield,
                isc.product gmr_product,
                isc.invoiced_qty_unit child_qty_unit,
                isd.iban
  from is_d isd,
       is_child_d isc,
       is_bdp_child_d isp_c1,
       is_bds_child_d isp_c2,
       is_conc_payable_child is_cp,
       is_parent_child_d ispcd,
       ds_document_summary ds,
       v_ak_corporate akc,
        (select vat.internal_invoice_ref_no,
                       vat.our_vat_no vat_no,
                       vat.cp_vat_no,
                       vat.vat_code,
                       vat.vat_rate,
                       vat.vat_rate_unit,
                       vat.vat_amount_in_inv_cur vat_amount
                  from ivd_invoice_vat_details vat
                 where vat.is_separate_invoice = 'N')vat
         where isd.internal_doc_ref_no = ds.internal_doc_ref_no(+)
           and ds.corporate_id = akc.corporate_id(+)
           and isd.internal_doc_ref_no = isc.internal_doc_ref_no(+)
           and isd.internal_doc_ref_no = ispcd.internal_doc_ref_no(+)
           and isd.internal_doc_ref_no = isp_c1.internal_doc_ref_no(+)
           and isd.internal_doc_ref_no = isp_c2.internal_doc_ref_no(+)
           and isd.internal_doc_ref_no = is_cp.internal_doc_ref_no(+)
           and isd.internal_invoice_ref_no = vat.internal_invoice_ref_no(+)
union all
select        'Invoice' section_name,
              'Treatment Charge' sub_section,
               rownum record_no,
               akc.corporate_id,
               akc.corporate_name,
               akc.address1,
               akc.address2,
               akc.city,
               akc.state,
               akc.country,
               akc.logo_path,
               akc.phone_no,
               akc.fax_no,
               isd.internal_doc_ref_no,
               isd.due_date,
               isd.sales_purchase,
               isd.cp_name,
               isd.supplire_invoice_no cp_item_stock_ref_no,
               '' business_unit,
               isd.self_item_stock_ref_no,
               isd.inco_term_location,
               isd.contract_ref_no self_contract_item_no,
               isd.contract_date,
               isd.notify_party,
               isd.org_name,
               isd.cp_contract_ref_no,
               isd.productandquality_name,
               isd.contract_tolerance,
               isd.contract_quantity,
               isd.contract_qty_unit,
               isd.invoice_ref_no provisional_invoice_no,
               isd.internal_invoice_ref_no,
               isd.product,
               isd.quality,
               isd.invoice_amount amount,
               isd.invoice_amount_unit,
               isd.payment_term,
               isd.invoice_creation_date,
               null invoice_issue_date,
               isd.invoice_quantity,
               isd.invoice_dry_quantity,
               isd.invoice_wet_quantity,
               isd.invoiced_qty_unit,
               isd.moisture,
               isd.invoice_type_name invoice_type,
               isd.stock_size,
               isd.packing,
               isd.provisional_price,
               isd.origin,
               isd.tarriff,
               '' final_qty,
               isd.material_cost final_amount,
               '' pi_number,
               '' provisional_amount,
               '' amount_due,
               isd.addditional_charges,
               isd.taxes,
               isd.contract_type product_type,
               isd.Invoice_Status,
               isd.gmr_ref_no pledge_gmr_ref_no,
               isd.gmr_quality pledge_gmr_qty,
               isd.stock_ref_no pledge_stock_ref_no,
               isd.stock_quantity pledge_stock_qty,
               null internal_doc_ref_no0,
               null stock_ref_no1,
               null stock_qty,
               null gmr_ref_no,
               null gmr_quality,
               null gmr_quantity,
               null price_as_per_defind_uom,
               null item_amount_in_inv_cur,
               null invoiced_price_unit,
               null element_price_unit,
               null total_quantity,
               null gmr_qty_unit,
               isp_c1.internal_doc_ref_no internal_doc_ref_no1,
               isp_c1.beneficiary_name benificiary_name_c1,
               isp_c1.bank_name bank_name_c1,
               isp_c1.account_no account_no_c1,
               isp_c1.iban iban_c1,
               isp_c1.aba_rtn aba_rtn_c1,
               isp_c1.instruction instruction_c1,
               isp_c2.internal_doc_ref_no internal_doc_ref_no2,
               isp_c2.beneficiary_name benificiary_name_c2,
               isp_c2.bank_name bank_name_c2,
               isp_c2.account_no account_no_c2,
               isp_c2.iban iban_c2,
               isp_c2.aba_rtn aba_rtn_c2,
               isp_c2.instruction instruction_c2,
               null internal_doc_ref_no3,
               null stock_ref_no1,
               null stock_gmr_ref_no,
               null cp_gmr_quantity,
               null stock_qty1,
               null gmr_qty_unit1,
               null payable_element_id,
               null payable_element,
               null analysis,
               null analysis_unit,
               null element_price,
               null invoiced_price_unit1,
               null element_price_unit1,
               null sub_lot_no,
               null element_inv_amount,
               null element_invoiced_qty,
               null element_invoiced_qty_unit,
               istc.internal_doc_ref_no internal_doc_ref_no4,
               istc.tc_element_id,
               istc.element_name,
               istc.sub_lot_no tc_rc_sub_lot_no,
               istc.tc_amount,
               istc.tc_amount_unit,
               null internal_doc_ref_no5,
               null rc_element_id,
               null element_name1,
               null rc_amount,
               null rc_amount_unit,
               null internal_doc_ref_no6,
               null pen_element_id,
               null element_name2,
               null pen_amount,
               null pen_amount_unit,
               vat.vat_no,
               vat.cp_vat_no,
               vat.vat_code,
               vat.vat_rate,
               vat.vat_rate_unit,
               vat.vat_amount,
               isd.invoice_amount_unit vat_amount_cur,
               isd.is_inv_draft,
               null cost_name,
               null charge_type,
               null charge_amount_rate,
               null charge_amount_rate_unit,
               null fx_rate,
               null charges_quantity,
               null charges_qty_unit,
               null charges_amount,
               null charge_amount_unit,
               null charges_invoice_amount,
               null charges_invoice_cur_name,
               null tax_code,
               null tax_rate,
               null tax_currency,
               null taxes_fx_rate,
               null Applicable_on,
               null taxes_amount,
               null taxes_amount_unit,
               null taxes_invoice_amount,
               null taxes_invoice_amount_cur,
               isd.is_free_metal,
               isd.is_pledge,
               isd.internal_comments,
               (case when  isd.sales_purchase='P' then
                        isp_c1.remarks
                        when isd.sales_purchase='S' then
                        isp_c2.remarks end) remarks,
                null yield,
                null gmr_product,
                null child_qty_unit,
                isd.iban
  from is_d isd,
       is_bdp_child_d isp_c1,
       is_bds_child_d isp_c2,
       ds_document_summary ds,
       v_ak_corporate akc,
       (select istc.internal_doc_ref_no,
               istc.element_id tc_element_id,
               istc.element_name,
               istc.sub_lot_no ||(case when istc.assay_detail is null then ''
                                      else ' : '|| istc.assay_detail end) sub_lot_no,
              istc.tc_amount,
               istc.amount_unit tc_amount_unit
          from is_conc_tc_child istc) istc,
        (select vat.internal_invoice_ref_no,
                       vat.our_vat_no vat_no,
                       vat.cp_vat_no,
                       vat.vat_code,
                       vat.vat_rate,
                       vat.vat_rate_unit,
                       vat.vat_amount_in_inv_cur vat_amount
                  from ivd_invoice_vat_details vat
                 where vat.is_separate_invoice = 'N')vat
         where isd.internal_doc_ref_no = ds.internal_doc_ref_no(+)
           and ds.corporate_id = akc.corporate_id(+)
           and isd.internal_doc_ref_no = isp_c1.internal_doc_ref_no(+)
           and isd.internal_doc_ref_no = isp_c2.internal_doc_ref_no(+)
           and isd.internal_doc_ref_no = istc.internal_doc_ref_no(+)
           and isd.internal_invoice_ref_no = vat.internal_invoice_ref_no(+)
Union all
select        'Invoice' section_name,
              'Refining Charge' sub_section,
               rownum record_no,
               akc.corporate_id,
               akc.corporate_name,
               akc.address1,
               akc.address2,
               akc.city,
               akc.state,
               akc.country,
               akc.logo_path,
               akc.phone_no,
               akc.fax_no,
               isd.internal_doc_ref_no,
               isd.due_date,
               isd.sales_purchase,
               isd.cp_name,
               isd.supplire_invoice_no cp_item_stock_ref_no,
               '' business_unit,
               isd.self_item_stock_ref_no,
               isd.inco_term_location,
               isd.contract_ref_no self_contract_item_no,
               isd.contract_date,
               isd.notify_party,
               isd.org_name,
               isd.cp_contract_ref_no,
               isd.productandquality_name,
               isd.contract_tolerance,
               isd.contract_quantity,
               isd.contract_qty_unit,
               isd.invoice_ref_no provisional_invoice_no,
               isd.internal_invoice_ref_no,
               isd.product,
               isd.quality,
               isd.invoice_amount amount,
               isd.invoice_amount_unit,
               isd.payment_term,
               isd.invoice_creation_date,
               null invoice_issue_date,
               isd.invoice_quantity,
               isd.invoice_dry_quantity,
               isd.invoice_wet_quantity,
               isd.invoiced_qty_unit,
               isd.moisture,
               isd.invoice_type_name invoice_type,
               isd.stock_size,
               isd.packing,
               isd.provisional_price,
               isd.origin,
               isd.tarriff,
               '' final_qty,
               isd.material_cost final_amount,
               '' pi_number,
               '' provisional_amount,
               '' amount_due,
               isd.addditional_charges,
               isd.taxes,
               isd.contract_type product_type,
               isd.Invoice_Status,
               isd.gmr_ref_no pledge_gmr_ref_no,
               isd.gmr_quality pledge_gmr_qty,
               isd.stock_ref_no pledge_stock_ref_no,
               isd.stock_quantity pledge_stock_qty,
               null internal_doc_ref_no0,
               null stock_ref_no,
               null stock_qty,
               null gmr_ref_no,
               null gmr_quality,
               null gmr_quantity,
               null price_as_per_defind_uom,
               null item_amount_in_inv_cur,
               null invoiced_price_unit,
               null element_price_unit,
               null total_quantity,
               null gmr_qty_unit,
               isp_c1.internal_doc_ref_no internal_doc_ref_no1,
               isp_c1.beneficiary_name benificiary_name_c1,
               isp_c1.bank_name bank_name_c1,
               isp_c1.account_no account_no_c1,
               isp_c1.iban iban_c1,
               isp_c1.aba_rtn aba_rtn_c1,
               isp_c1.instruction instruction_c1,
               isp_c2.internal_doc_ref_no internal_doc_ref_no2,
               isp_c2.beneficiary_name benificiary_name_c2,
               isp_c2.bank_name bank_name_c2,
               isp_c2.account_no account_no_c2,
               isp_c2.iban iban_c2,
               isp_c2.aba_rtn aba_rtn_c2,
               isp_c2.instruction instruction_c2,
               null internal_doc_ref_no3,
               null stock_ref_no1,
               null stock_gmr_ref_no,
               null cp_gmr_quantity,
               null stock_qty1,
               null gmr_qty_unit1,
               null payable_element_id,
               null payable_element,
               null analysis,
               null analysis_unit,
               null element_price,
               null invoiced_price_unit1,
               null element_price_unit1,
               null sub_lot_no,
               null element_inv_amount,
               null element_invoiced_qty,
               null element_invoiced_qty_unit,
               null internal_doc_ref_no4,
               null tc_element_id,
               null element_name,
               isrc.sub_lot_no tc_rc_sub_lot_no,
               null tc_amount,
               null tc_amount_unit,
               isrc.internal_doc_ref_no internal_doc_ref_no5,
               isrc.rc_element_id,
               isrc.element_name element_name1,
               isrc.rc_amount,
               isrc.rc_amount_unit,
               null internal_doc_ref_no6,
               null pen_element_id,
               null element_name2,
               null pen_amount,
               null pen_amount_unit,
               vat.vat_no,
               vat.cp_vat_no,
               vat.vat_code,
               vat.vat_rate,
               vat.vat_rate_unit,
               vat.vat_amount,
               isd.invoice_amount_unit vat_amount_cur,
               isd.is_inv_draft,
               null cost_name,
               null charge_type,
               null charge_amount_rate,
               null charge_amount_rate_unit,
               null fx_rate,
               null charges_quantity,
               null charges_qty_unit,
               null charges_amount,
               null charge_amount_unit,
               null charges_invoice_amount,
               null charges_invoice_cur_name,
               null tax_code,
               null tax_rate,
               null tax_currency,
               null taxes_fx_rate,
               null Applicable_on,
               null taxes_amount,
               null taxes_amount_unit,
               null taxes_invoice_amount,
               null taxes_invoice_amount_cur,
               isd.is_free_metal,
               isd.is_pledge,
               isd.internal_comments,
               (case when  isd.sales_purchase='P' then
                        isp_c1.remarks
                        when isd.sales_purchase='S' then
                        isp_c2.remarks end) remarks,
                null yield,
                null  gmr_product,
                null child_qty_unit,
                isd.iban
  from is_d isd,
       is_bdp_child_d isp_c1,
       is_bds_child_d isp_c2,
       ds_document_summary ds,
       v_ak_corporate akc,
       (select isrc.internal_doc_ref_no,
               isrc.element_id rc_element_id,
               isrc.element_name,
               isrc.sub_lot_no ||(case when isrc.assay_content is null then ''
                                      else ' : '|| isrc.assay_content end) sub_lot_no,
               isrc.rc_amount,
               isrc.amount_unit rc_amount_unit
          from is_conc_rc_child isrc) isrc,
        (select vat.internal_invoice_ref_no,
                       vat.our_vat_no vat_no,
                       vat.cp_vat_no,
                       vat.vat_code,
                       vat.vat_rate,
                       vat.vat_rate_unit,
                       vat.vat_amount_in_inv_cur vat_amount
                  from ivd_invoice_vat_details vat
                 where vat.is_separate_invoice = 'N')vat
         where isd.internal_doc_ref_no = ds.internal_doc_ref_no(+)
           and ds.corporate_id = akc.corporate_id(+)
           and isd.internal_doc_ref_no = isp_c1.internal_doc_ref_no(+)
           and isd.internal_doc_ref_no = isp_c2.internal_doc_ref_no(+)
           and isd.internal_doc_ref_no = isrc.internal_doc_ref_no(+)
           and isd.internal_invoice_ref_no = vat.internal_invoice_ref_no(+)
union all
select 'Invoice' section_name,
       'Penality' sub_section,
       rownum record_no,
       akc.corporate_id,
       akc.corporate_name,
       akc.address1,
       akc.address2,
       akc.city,
       akc.state,
       akc.country,
       akc.logo_path,
       akc.phone_no,
       akc.fax_no,
       isd.internal_doc_ref_no,
       isd.due_date,
       isd.sales_purchase,
       isd.cp_name,
       isd.supplire_invoice_no cp_item_stock_ref_no,
       '' business_unit,
       isd.self_item_stock_ref_no,
       isd.inco_term_location,
       isd.contract_ref_no self_contract_item_no,
       isd.contract_date,
       isd.notify_party,
       isd.org_name,
       isd.cp_contract_ref_no,
       isd.productandquality_name,
       isd.contract_tolerance,
       isd.contract_quantity,
       isd.contract_qty_unit,
       isd.invoice_ref_no provisional_invoice_no,
       isd.internal_invoice_ref_no,
       isd.product,
       isd.quality,
       isd.invoice_amount amount,
       isd.invoice_amount_unit,
       isd.payment_term,
       isd.invoice_creation_date,
       null invoice_issue_date,
       isd.invoice_quantity,
       isd.invoice_dry_quantity,
       isd.invoice_wet_quantity,
       isd.invoiced_qty_unit,
       isd.moisture,
       isd.invoice_type_name invoice_type,
       isd.stock_size,
       isd.packing,
       isd.provisional_price,
       isd.origin,
       isd.tarriff,
       isd.material_cost final_qty,
       '' final_amount,
       '' pi_number,
       '' provisional_amount,
       null amount_due,
       isd.addditional_charges,
       isd.taxes,
       isd.contract_type product_type,
       isd.Invoice_Status,
       null pledge_gmr_ref_no,
       null  pledge_gmr_qty,
       null  pledge_stock_ref_no,
       null  pledge_stock_qty,
       null internal_doc_ref_no0,
       null stock_ref_no,
       null stock_qty,
       null gmr_ref_no,
       null gmr_quality,
       null gmr_quantity,
       null price_as_per_defind_uom,
       null item_amount_in_inv_cur,
       null invoiced_price_unit,
       null element_price_unit,
       null total_quantity,
       null gmr_qty_unit,
       null internal_doc_ref_no1,
       null benificiary_name_c1,
       null bank_name_c1,
       null account_no_c1,
       null iban_c1,
       null aba_rtn_c1,
       null instruction_c1,
       null internal_doc_ref_no2,
       null benificiary_name_c2,
       null bank_name_c2,
       null account_no_c2,
       null iban_c2,
       null aba_rtn_c2,
       null instruction_c2,
       null internal_doc_ref_no3,
       null stock_ref_no1,
       null stock_gmr_ref_no,
       null cp_gmr_quantity,
       null stock_qty1,
       null gmr_qty_unit1,
       null payable_element_id,
       null payable_element,
       null analysis,
       null analysis_unit,
       null element_price,
       null invoiced_price_unit1,
       null element_price_unit1,
       null sub_lot_no,
       null element_inv_amount,
       null element_invoiced_qty,
       null element_invoiced_qty_unit,
       null internal_doc_ref_no4,
       null tc_element_id,
       null element_name,
       null tc_rc_sub_lot_no,
       null tc_amount,
       null tc_amount_unit,
       null internal_doc_ref_no5,
       null rc_element_id,
       null element_name1,
       null rc_amount,
       null rc_amount_unit,
       isp.internal_doc_ref_no internal_doc_ref_no6,
       isp.pen_element_id,
       isp.element_name element_name2,
       isp.pen_amount,
       isp.pen_amount_unit,
       vat.vat_no,
       vat.cp_vat_no,
       vat.vat_code,
       vat.vat_rate,
       vat.vat_rate_unit,
       vat.vat_amount,
       isd.invoice_amount_unit vat_amount_cur,
       isd.is_inv_draft,
       null cost_name,
       null charge_type,
       null charge_amount_rate,
       null charge_amount_rate_unit,
       null fx_rate,
       null charges_quantity,
       null charges_qty_unit,
       null charges_amount,
       null charge_amount_unit,
       null charges_invoice_amount,
       null charges_invoice_cur_name,
       null tax_code,
       null tax_rate,
       null tax_currency,
       null taxes_fx_rate,
       null Applicable_on,
       null taxes_amount,
       null taxes_amount_unit,
       null taxes_invoice_amount,
       null taxes_invoice_amount_cur,
       isd. is_free_metal,
       isd. is_pledge,
       isd. internal_comments,
       null remarks,
       null yield,
       null gmr_product,
       null child_qty_unit,
       null iban
  from is_d isd,
       ds_document_summary ds,
       v_ak_corporate akc,
       (select isp.internal_doc_ref_no,
               isp.element_id pen_element_id,
               isp.element_name,
               sum(isp.penalty_amount) pen_amount,
               isp.amount_unit pen_amount_unit
          from is_conc_penalty_child isp
         group by isp.internal_doc_ref_no,
                  isp.element_id,
                  isp.element_name,
                  isp.amount_unit) isp,
        (select vat.internal_invoice_ref_no,
                       vat.our_vat_no vat_no,
                       vat.cp_vat_no,
                       vat.vat_code,
                       vat.vat_rate,
                       vat.vat_rate_unit,
                       vat.vat_amount_in_inv_cur vat_amount
                  from ivd_invoice_vat_details vat
                 where vat.is_separate_invoice = 'N')vat
 where isd.internal_doc_ref_no = ds.internal_doc_ref_no(+)
   and ds.corporate_id = akc.corporate_id(+)
   and isd.internal_doc_ref_no = isp.internal_doc_ref_no(+)
   and isd.internal_invoice_ref_no = vat.internal_invoice_ref_no(+)
union all
select         'Other Charges' section_name,
               'Other Charges' sub_section,
               rownum record_no,
               akc.corporate_id,
               akc.corporate_name,
               akc.address1,
               akc.address2,
               akc.city,
               akc.state,
               akc.country,
               akc.logo_path,
               akc.phone_no,
               akc.fax_no,
               isd.internal_doc_ref_no,
               isd.due_date,
               isd.sales_purchase,
               isd.cp_name,
               isd.supplire_invoice_no cp_item_stock_ref_no,
               '' business_unit,
               isd.self_item_stock_ref_no,
               isd.inco_term_location,
               isd.contract_ref_no self_contract_item_no,
               isd.contract_date,
               isd.notify_party,
               isd.org_name,
               isd.cp_contract_ref_no,
               isd.productandquality_name,
               isd.contract_tolerance,
               isd.contract_quantity,
               isd.contract_qty_unit,
               isd.invoice_ref_no provisional_invoice_no,
               isd.internal_invoice_ref_no,
               isd.product,
               isd.quality,
               isd.invoice_amount amount,
               isd.invoice_amount_unit,
               isd.payment_term,
               isd.invoice_creation_date,
               null invoice_issue_date,
               isd.invoice_quantity,
               isd.invoice_dry_quantity,
               isd.invoice_wet_quantity,
               isd.invoiced_qty_unit,
               isd.moisture,
               isd.invoice_type_name invoice_type,
               isd.stock_size,
               isd.packing,
               isd.provisional_price,
               isd.origin,
               isd.tarriff,
               '' final_qty,
               isd.material_cost final_amount,
               '' pi_number,
               '' provisional_amount,
               '' amount_due,
               isd.addditional_charges,
               isd.taxes,
               isd.contract_type product_type,
               isd.Invoice_Status,
               null pledge_gmr_ref_no,
               null  pledge_gmr_qty,
               null  pledge_stock_ref_no,
               null  pledge_stock_qty,
               null internal_doc_ref_no0,
               null stock_ref_no,
               null stock_qty,
               null gmr_ref_no,
               null gmr_quality,
               null gmr_quantity,
               null price_as_per_defind_uom,
               null item_amount_in_inv_cur,
               null invoiced_price_unit,
               null element_price_unit,
               null total_quantity,
               null gmr_qty_unit,
               null internal_doc_ref_no1,
               null benificiary_name_c1,
               null bank_name_c1,
               null account_no_c1,
               null iban_c1,
               null aba_rtn_c1,
               null instruction_c1,
               null internal_doc_ref_no2,
               null benificiary_name_c2,
               null bank_name_c2,
               null account_no_c2,
               null iban_c2,
               null aba_rtn_c2,
               null instruction_c2,
               null internal_doc_ref_no3,
               null stock_ref_no1,
               null stock_gmr_ref_no,
               null cp_gmr_quantity,
               null stock_qty1,
               null gmr_qty_unit1,
               null payable_element_id,
               null payable_element,
               null analysis,
               null analysis_unit,
               null element_price,
               null invoiced_price_unit1,
               null element_price_unit1,
               null sub_lot_no,
               null element_inv_amount,
               null element_invoiced_qty,
               null element_invoiced_qty_unit,
               null internal_doc_ref_no4,
               null tc_element_id,
               null element_name,
               null tc_rc_sub_lot_no,
               null tc_amount,
               null tc_amount_unit,
               null internal_doc_ref_no5,
               null rc_element_id,
               null element_name1,
               null rc_amount,
               null rc_amount_unit,
               null internal_doc_ref_no6,
               null pen_element_id,
               null element_name2,
               null pen_amount,
               null pen_amount_unit,
               null vat_no,
               null cp_vat_no,
               null vat_code,
               null vat_rate,
               null vat_rate_unit,
               null vat_amount,
               null vat_amount_cur,
               isd.is_inv_draft,
               ioc.other_charge_cost_name cost_name,
               ioc.charge_type,
               ioc.charge_amount_rate,
               ioc.rate_price_unit_name charge_amount_rate_unit,
               ioc.fx_rate,
               ioc.quantity charges_quantity,
               ioc.quantity_unit charges_qty_unit,
               ioc.amount charges_amount,
               ioc.amount_unit charge_amount_unit,
               ioc.invoice_amount charges_invoice_amount,
               ioc.invoice_cur_name charges_invoice_cur_name,
               null tax_code,
               null tax_rate,
               null tax_currency,
               null taxes_fx_rate,
               null Applicable_on,
               null taxes_amount,
               null taxes_amount_unit,
               null taxes_invoice_amount,
               null taxes_invoice_amount_cur,
               isd. is_free_metal,
               isd. is_pledge,
               isd. internal_comments,
               null remarks,
               null yield,
               null gmr_product,
               null child_qty_unit,
               null iban
       from ioc_d ioc,
            is_d isd,
            ds_document_summary ds,
            v_ak_corporate akc
     where ioc.internal_doc_ref_no = ds.internal_doc_ref_no
              and isd.internal_doc_ref_no = ioc.internal_doc_ref_no
              and ds.corporate_id = akc.corporate_id(+)
union all
select 'Other Taxes' section_name,
       'Other Taxes' sub_section,
       rownum record_no,
       akc.corporate_id,
       akc.corporate_name,
       akc.address1,
       akc.address2,
       akc.city,
       akc.state,
       akc.country,
       akc.logo_path,
       akc.phone_no,
       akc.fax_no,
       isd.internal_doc_ref_no,
       isd.due_date,
       isd.sales_purchase,
       isd.cp_name,
       isd.supplire_invoice_no cp_item_stock_ref_no,
       '' business_unit,
       isd.self_item_stock_ref_no,
       isd.inco_term_location,
       isd.contract_ref_no self_contract_item_no,
       isd.contract_date,
       isd.notify_party,
       isd.org_name,
       isd.cp_contract_ref_no,
       isd.productandquality_name,
       isd.contract_tolerance,
       isd.contract_quantity,
       isd.contract_qty_unit,
       isd.invoice_ref_no provisional_invoice_no,
       isd.internal_invoice_ref_no,
       isd.product,
       isd.quality,
       isd.invoice_amount amount,
       isd.invoice_amount_unit,
       isd.payment_term,
       isd.invoice_creation_date,
       null invoice_issue_date,
       isd.invoice_quantity,
       isd.invoice_dry_quantity,
       isd.invoice_wet_quantity,
       isd.invoiced_qty_unit,
       isd.moisture,
       isd.invoice_type_name invoice_type,
       isd.stock_size,
       isd.packing,
       isd.provisional_price,
       isd.origin,
       isd.tarriff,
       '' final_qty,
       isd.material_cost final_amount,
       '' pi_number,
       '' provisional_amount,
       '' amount_due,
       isd.addditional_charges,
       isd.taxes,
       isd.contract_type product_type,
       isd.Invoice_Status,
       null pledge_gmr_ref_no,
       null  pledge_gmr_qty,
       null  pledge_stock_ref_no,
       null  pledge_stock_qty,
       null internal_doc_ref_no0,
       null stock_ref_no,
       null stock_qty,
       null gmr_ref_no,
       null gmr_quality,
       null gmr_quantity,
       null price_as_per_defind_uom,
       null item_amount_in_inv_cur,
       null invoiced_price_unit,
       null element_price_unit,
       null total_quantity,
       null gmr_qty_unit,
       null internal_doc_ref_no1,
       null benificiary_name_c1,
       null bank_name_c1,
       null account_no_c1,
       null iban_c1,
       null aba_rtn_c1,
       null instruction_c1,
       null internal_doc_ref_no2,
       null benificiary_name_c2,
       null bank_name_c2,
       null account_no_c2,
       null iban_c2,
       null aba_rtn_c2,
       null instruction_c2,
       null internal_doc_ref_no3,
       null stock_ref_no1,
       null stock_gmr_ref_no,
       null cp_gmr_quantity,
       null stock_qty1,
       null gmr_qty_unit1,
       null payable_element_id,
       null payable_element,
       null analysis,
       null analysis_unit,
       null element_price,
       null invoiced_price_unit1,
       null element_price_unit1,
       null sub_lot_no,
       null element_inv_amount,
       null element_invoiced_qty,
       null element_invoiced_qty_unit,
       null internal_doc_ref_no4,
       null tc_element_id,
       null element_name,
       null tc_rc_sub_lot_no,
       null tc_amount,
       null tc_amount_unit,
       null internal_doc_ref_no5,
       null rc_element_id,
       null element_name1,
       null rc_amount,
       null rc_amount_unit,
       null internal_doc_ref_no6,
       null pen_element_id,
       null element_name2,
       null pen_amount,
       null pen_amount_unit,
       null vat_no,
       null cp_vat_no,
       null vat_code,
       null vat_rate,
       null vat_rate_unit,
       null vat_amount,
       null vat_amount_cur,
       isd.is_inv_draft,
       null cost_name,
       null charge_type,
       null charge_amount_rate,
       null charge_amount_rate_unit,
       null fx_rate,
       null charges_quantity,
       null charges_qty_unit,
       null charges_amount,
       null charge_amount_unit,
       null charges_invoice_amount,
       null charges_invoice_cur_name,
       itd.tax_code,
       itd.tax_rate,
       itd.tax_currency,
       itd.fx_rate taxes_fx_rate,
       '' Applicable_on,
       itd.amount taxes_amount,
       itd.tax_currency taxes_amount_unit,
       itd.invoice_amount taxes_invoice_amount,
       itd.invoice_currency taxes_invoice_amount_cur,
       isd.is_free_metal,
       isd.is_pledge,
       isd.internal_comments,
       null remarks,
       null yield,
       null gmr_product,
       null child_qty_unit,
       null iban
     from itd_d itd,
         is_d isd,
         ds_document_summary ds,
         v_ak_corporate akc
        where itd.internal_doc_ref_no = ds.internal_doc_ref_no
          and isd.internal_doc_ref_no = itd.internal_doc_ref_no
          and ds.corporate_id = akc.corporate_id(+)

