DROP MATERIALIZED VIEW MV_BI_TCRC_DISTRIBUTION_REPORT;
CREATE MATERIALIZED VIEW MV_BI_TCRC_DISTRIBUTION_REPORT
REFRESH FORCE ON DEMAND
START WITH TO_DATE('14-03-2012 20:14:53', 'DD-MM-YYYY HH24:MI:SS') NEXT SYSDATE+5/1440  
AS
SELECT * FROM V_BI_TC_RC_DISTRIBUTION_REPORT;