DROP materialized view MV_BI_DER_PHY_PFC_JOURNAL_EOD;
create materialized view MV_BI_DER_PHY_PFC_JOURNAL_EOD
refresh force on demand
as
select efj.journal_type,
       efj.book_type,
       efj.process_id,
       efj.process,
       efj.eod_trade_date,
       efj.corporate_id,
       efj.corporate_name,
       efj.product_id,
       efj.product_name,
       efj.profit_center_id,
       efj.profit_center_name,
       efj.profit_center_short_name,
       efj.price_fixation_refno,
       efj.internal_derivative_ref_no,
       efj.delivery_item_ref_no,
       efj.delivery_item_qty,
       efj.delivery_item_qty_unit,
       efj.contract_ref_no,
       efj.clearer_profile_id,
       efj.clearer_name,
       efj.trader_name,
       efj.price_fixation_date,
       efj.fixed_quantity,
       efj.quantity_unit,
       efj.trade_price,
       efj.price_unit,
       efj.adjustment,
       efj.fx_rate,
       efj.contract_premium,
       efj.contract_premium_unit,
       efj.total_price,
       efj.total_price_unit,
       efj.contract_issue_date,
       efj.average_from_date,
       efj.average_to_date,
       efj.settlement_price,
       efj.settlement_date,
       efj.strategy_id,
       efj.strategy_name,
       efj.attribute_1,
       efj.attribute_2,
       efj.attribute_3,
       efj.attribute_4,
       efj.attribute_5,
       efj.base_cur_id,
       efj.base_cur_code,
       efj.price_to_base_conv_rate,
       efj.prem_to_base_conv_rate,
       efj.price_in_base_unit,
       efj.premium_in_base_unit,
       efj.base_price_unit,
       efj.base_price_unit_id,
       efj.trade_price_unit_id,
       efj.prem_price_unit_id,
       efj.base_qty_unit,
       efj.base_qty_unit_id,
       efj.attribute_id element_id,
       efj.attribute_name element_name,
       tdc.created_date eod_eom_run_date,
       tdc.process_run_count eod_eom_run_count
  from eod_eom_fixation_journal@eka_eoddb efj,
       tdc_trade_date_closure@eka_eoddb   tdc
 where efj.corporate_id = tdc.corporate_id
   and efj.process_id = tdc.process_id
   and efj.process = 'EOD';
