DROP materialized view MV_BI_DER_BOOK_JOURNAL_EOM;
DROP TABLE MV_BI_DER_BOOK_JOURNAL_EOM;
create materialized view MV_BI_DER_BOOK_JOURNAL_EOM
refresh force on demand
as
select bkj.internal_close_out_ref_no,
       bkj.journal_type,
       bkj.book_type,
       bkj.corporate_id,
       bkj.corporate_name,
       bkj.profit_center_id,
       bkj.profit_center_name,
       bkj.profit_center_short_name,
       bkj.close_out_ref_no,
       bkj.close_out_date,
       bkj.internal_derivative_ref_no,
       bkj.derivative_ref_no,
       bkj.external_ref_no,
       bkj.trade_type,
       bkj.clearer,
       bkj.created_by,
       bkj.quantity,
       bkj.quantity_unit_id,
       bkj.quantity_unit,
       bkj.clearer_comm_amt,
       bkj.clearer_comm_cur_id,
       bkj.clearer_comm_cur_code,
       bkj.trade_amount,
       bkj.trade_currency,
       bkj.trade_to_corp_fx_rate,
       bkj.trade_amount_in_base_ccy,
       bkj.clearer_comm_in_base_ccy,
       bkj.base_cur_id,
       bkj.base_cur_code,
       bkj.product_id,
       bkj.product_desc,
       bkj.eod_eom_date,
       bkj.process,
       bkj.process_id,
       bkj.dbd_id,
       bkj.trade_price,
       bkj.trade_price_unit_id,
       bkj.trade_price_unit,
       bkj.price_cur_id,
       bkj.price_cur_code,
       bkj.price_weight,
       bkj.price_weight_unit_id,
       bkj.price_weight_unit,
       bkj.strategy_id,
       bkj.strategy_name,
       bkj.attribute_1,
       bkj.attribute_2,
       bkj.attribute_3,
       bkj.attribute_4,
       bkj.attribute_5,
       tdc.created_date eod_eom_run_date,
       tdc.process_run_count eod_eom_run_count
  from eod_eom_booking_journal@eka_eoddb bkj,
       tdc_trade_date_closure@eka_eoddb  tdc
 where bkj.corporate_id = tdc.corporate_id
   and bkj.process_id = tdc.process_id
   and bkj.process = 'EOM';
