DROP MATERIALIZED VIEW MV_CASH_FLOW_REPORT;
CREATE MATERIALIZED VIEW MV_CASH_FLOW_REPORT 
BUILD IMMEDIATE
REFRESH FORCE
START WITH TO_DATE('16-Dec-2011 11:23:07','dd-mon-yyyy hh24:mi:ss')
NEXT SYSDATE+3/1440 
WITH PRIMARY KEY
AS 
SELECT * FROM V_CASH_FLOW_REPORT;