--script modified,
ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD LATEST_INTERNAL_INVOICE_REF_NO VARCHAR2 (25 Char);
ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD LATEST_INVOICE_REF_NO VARCHAR2 (30 Char);
ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD SHIPMENT_DATE VARCHAR2 (21 Char);
ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD IS_FI_CREATED CHAR (1 Char);
ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD INVOICE_CUR_ID VARCHAR2 (15 Char);
ALTER TABLE GMRUL_GMR_UL ADD LATEST_INTERNAL_INVOICE_REF_NO VARCHAR2 (25 Char);
ALTER TABLE GMRUL_GMR_UL ADD LATEST_INVOICE_REF_NO VARCHAR2 (30 Char);
ALTER TABLE GMRUL_GMR_UL ADD SHIPMENT_DATE VARCHAR2 (21 Char);
ALTER TABLE GMRUL_GMR_UL ADD IS_FI_CREATED CHAR (15 Char);
ALTER TABLE GMRUL_GMR_UL ADD INVOICE_CUR_ID VARCHAR2 (15 Char);