CREATE TABLE PRRQS_PRR_QTY_STATUS
(
  PRRQS_ID                VARCHAR2(15)     NOT NULL,
  INTERNAL_GMR_REF_NO     VARCHAR2(15),
  INTERNAL_GRD_REF_NO     VARCHAR2(15),
  INTERNAL_DGRD_REF_NO    VARCHAR2(15),
  ACTIVITY_ACTION_ID      VARCHAR2(30)     NOT NULL,
  QTY_TYPE                VARCHAR2(10)     DEFAULT 'Payable'             NOT NULL,
  SUPPLIER_CP_ID          VARCHAR2(20),
  SMELTER_CP_ID           VARCHAR2(20),
  TO_SUPPLIER_CP_ID       VARCHAR2(20),
  TO_SMELTER_CP_ID        VARCHAR2(20),
  QTY_SIGN                NUMBER(2)             DEFAULT 1                     NOT NULL,
  PRODUCT_ID              VARCHAR2(15),
  ELEMENT_ID              VARCHAR2(15),
  QTY                     NUMBER(25,10)         NOT NULL,
  QTY_UNIT_ID             VARCHAR2(15)     NOT NULL,
  INTERNAL_ACTION_REF_NO  VARCHAR2(15)     NOT NULL,
  IS_ACTIVE               CHAR(1)          DEFAULT 'Y'                   NOT NULL,
  VERSION                 NUMBER(10)
);


ALTER TABLE PRRQS_PRR_QTY_STATUS ADD (
  CONSTRAINT CHK_PRRQS_QTY_TYPE
 CHECK (QTY_TYPE IN ('Payable','Returnable','Returned')),
  CONSTRAINT CHK_PRRQS_IS_ACTIVE
 CHECK ( IS_ACTIVE IN ('Y', 'N')),
 CONSTRAINT PK_PRRQS PRIMARY KEY (PRRQS_ID));

ALTER TABLE PRRQS_PRR_QTY_STATUS ADD (
  CONSTRAINT FK_PRRQS_GMR 
 FOREIGN KEY (INTERNAL_GMR_REF_NO) 
 REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO),
  CONSTRAINT FK_PRRQS_GRD 
 FOREIGN KEY (INTERNAL_GRD_REF_NO) 
 REFERENCES GRD_GOODS_RECORD_DETAIL (INTERNAL_GRD_REF_NO),
  CONSTRAINT FK_PRRQS_DGRD 
 FOREIGN KEY (INTERNAL_DGRD_REF_NO) 
 REFERENCES DGRD_DELIVERED_GRD (INTERNAL_DGRD_REF_NO),
  CONSTRAINT FK_PRRQS_ACTIVITY_ACTION_ID 
 FOREIGN KEY (ACTIVITY_ACTION_ID) 
 REFERENCES AXM_ACTION_MASTER (ACTION_ID),
  CONSTRAINT FK_PRRQS_SUPPLIER_CP_ID 
 FOREIGN KEY (SUPPLIER_CP_ID) 
 REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
  CONSTRAINT FK_PRRQS_SMELTER_CP_ID 
 FOREIGN KEY (SMELTER_CP_ID) 
 REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
  CONSTRAINT FK_PRRQS_TO_SUPPLIER_CP_ID 
 FOREIGN KEY (TO_SUPPLIER_CP_ID) 
 REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
  CONSTRAINT FK_PRRQS_TO_SMELTER_CP_ID 
 FOREIGN KEY (TO_SMELTER_CP_ID) 
 REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
  CONSTRAINT FK_PRRQS_PRODUCT_ID 
 FOREIGN KEY (PRODUCT_ID) 
 REFERENCES PDM_PRODUCTMASTER (PRODUCT_ID),
  CONSTRAINT FK_PRRQS_ELEMENT_ID 
 FOREIGN KEY (ELEMENT_ID) 
 REFERENCES AML_ATTRIBUTE_MASTER_LIST (ATTRIBUTE_ID),
  CONSTRAINT FK_PRRQS_QTY_UNIT_ID 
 FOREIGN KEY (QTY_UNIT_ID) 
 REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID),
  CONSTRAINT FK_PRRQS_INTERNAL_ACTION_NO 
 FOREIGN KEY (INTERNAL_ACTION_REF_NO) 
 REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO));

CREATE SEQUENCE SEQ_PRRQS
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


ALTER TABLE WRD_WAREHOUSE_RECEIPT_DETAIL ADD
(
SUPPLIER_CP_ID          VARCHAR2(20),
SMELTER_CP_ID           VARCHAR2(20),
PROFIT_CENTER_ID        VARCHAR2(15),
CONSTRAINT FK_WRD_SUPPLIER_CP_ID FOREIGN KEY (SUPPLIER_CP_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_WRD_SMELTER_CP_ID FOREIGN KEY (SMELTER_CP_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_WRD_PROFIT_CENTER_ID FOREIGN KEY (PROFIT_CENTER_ID) REFERENCES CPC_CORPORATE_PROFIT_CENTER (PROFIT_CENTER_ID)
);

ALTER TABLE WRDUL_WAREHOUSE_RECEIPT_UL ADD
(
SUPPLIER_CP_ID          VARCHAR2(20),
SMELTER_CP_ID           VARCHAR2(20),
PROFIT_CENTER_ID        VARCHAR2(15)
);


ALTER TABLE GRD_GOODS_RECORD_DETAIL ADD
(
PAYABLE_RETURNABLE_TYPE VARCHAR2(10),
CONSTRAINT CHK_GRD_PR_TYPE CHECK (PAYABLE_RETURNABLE_TYPE IN ('Payable','Returnable'))
);


ALTER TABLE AGRD_ACTION_GRD ADD
(
PAYABLE_RETURNABLE_TYPE VARCHAR2(10),
CONSTRAINT CHK_AGRD_PR_TYPE CHECK (PAYABLE_RETURNABLE_TYPE IN ('Payable','Returnable'))
);

ALTER TABLE GRDUL_GOODS_RECORD_DETAIL_UL ADD
(
PAYABLE_RETURNABLE_TYPE VARCHAR2(10)
);

ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD
(
PLEDGE_INPUT_GMR VARCHAR2(15),
CONSTRAINT FK_GMR_PLEDGE_INPUT_GMR FOREIGN KEY (PLEDGE_INPUT_GMR) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO)
);

ALTER TABLE GMRUL_GMR_UL ADD
(
PLEDGE_INPUT_GMR VARCHAR2(15)
);

ALTER TABLE SPQ_STOCK_PAYABLE_QTY DROP CONSTRAINT CHK_SPQ_QTY_TYPE;
ALTER TABLE SPQ_STOCK_PAYABLE_QTY ADD CONSTRAINT CHK_SPQ_QTY_TYPE CHECK (QTY_TYPE IN ('Payable','Returnable'));