CREATE TABLE AAD_ACTIVITY_APPROVAL_DETAILS
(
  ACTIVITY_APPROVAL_ID      VARCHAR2(15 ),
  ACTIVITY_REFNO            VARCHAR2(50 ),
  ENTITY_TYPE               VARCHAR2(50 ),
  ACTIVITY_APPROVAL_STATUS  VARCHAR2(50 ),
  IS_ACTIVE                 CHAR(1 )        DEFAULT 'Y'
);


ALTER TABLE AAD_ACTIVITY_APPROVAL_DETAILS ADD (
  CONSTRAINT AAD_APPROVAL_IS_ACTIVE
 CHECK (is_active IN ('Y', 'N')),
  PRIMARY KEY
 (ACTIVITY_APPROVAL_ID));


CREATE TABLE AD_APPROVAL_DETAILS
(
  APPROVAL_ID              VARCHAR2(15 ),
  ACTIVITY_APPROVAL_ID     VARCHAR2(15 ),
  APPROVAL_LEVEL_ID        VARCHAR2(15 ),
  NO_OF_APPROVAL_REQUIRED  NUMBER(2),
  APPROVAL_STATUS          VARCHAR2(50 )
);


ALTER TABLE AD_APPROVAL_DETAILS ADD (
  PRIMARY KEY
 (APPROVAL_ID));


CREATE TABLE ASD_APPROVAL_SUB_DETAILS
(
  SUB_APPROVAL_ID             VARCHAR2(15 ),
  SUB_APPROVAL_LEVEL_ID       VARCHAR2(15 ),
  APPROVAL_ID                 VARCHAR2(15 ),
  SUGGESTED_APPROVER_USER_ID  VARCHAR2(50 ),
  REMARKS                     VARCHAR2(200 ),
  SUB_APPROVAL_STATUS         VARCHAR2(15 ),
  APPROVED_BY                 VARCHAR2(15 ),
  APPROVED_DATE               TIMESTAMP(6)
);


ALTER TABLE ASD_APPROVAL_SUB_DETAILS ADD (
  PRIMARY KEY
 (SUB_APPROVAL_ID));

CREATE SEQUENCE SEQ_PK_AAD
  START WITH 161
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE SEQ_PK_AD
  START WITH 161
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE SEQ_PK_ASD
  START WITH 161
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

 alter table PCM_PHYSICAL_CONTRACT_MAIN add approval_status varchar2(60);