alter table IIED_INV_ITEM_ELEMENT_DETAILS drop constraint IIED_PK;

drop INDEX IIED_PK;

ALTER TABLE IIED_INV_ITEM_ELEMENT_DETAILS ADD (
  CONSTRAINT IIED_PK
 PRIMARY KEY
 (ELEMENT_ID, INTERNAL_INVOICE_REF_NO, GRD_ID, SUB_LOT_NO));