CREATE TABLE IS_CHILD_SI_D(
INTERNAL_INVOICE_REF_NO VARCHAR2(30),
GMR_REF_NO              VARCHAR2(30),
COST_COMPONENT_NAME     VARCHAR2(30),
INVOICE_AMOUNT          VARCHAR2(30),
INVOICE_AMOUNT_UNIT     VARCHAR2(30),
INTERNAL_DOC_REF_NO     VARCHAR2(30)
);