CREATE MATERIALIZED VIEW LOG ON  AGMR_ACTION_GMR;
CREATE MATERIALIZED VIEW LOG ON  REM_REGION_MASTER;
CREATE MATERIALIZED VIEW LOG ON  BVD_BP_VAT_DETAILS;
CREATE MATERIALIZED VIEW LOG ON  IOC_INVOICE_OTHER_CHARGE;
CREATE MATERIALIZED VIEW LOG ON  YPD_YIELD_PCT_DETAIL;