ALTER TABLE PCPDQD_PD_QUALITY_DETAILS
 ADD (QUALITY_NAME  VARCHAR2(30 BYTE));

ALTER TABLE PQD_PAYABLE_QUALITY_DETAILS
 ADD (QUALITY_NAME  VARCHAR2(30 BYTE));

ALTER TABLE TQD_TREATMENT_QUALITY_DETAILS
 ADD (QUALITY_NAME  VARCHAR2(30 BYTE));

ALTER TABLE RQD_REFINING_QUALITY_DETAILS
 ADD (QUALITY_NAME  VARCHAR2(30 BYTE));

ALTER TABLE PQD_PENALTY_QUALITY_DETAILS
 ADD (QUALITY_NAME  VARCHAR2(30 BYTE));

ALTER TABLE ARQD_ASSAY_QUALITY_DETAILS
 ADD (QUALITY_NAME  VARCHAR2(30 BYTE));


ALTER TABLE TED_TREATMENT_ELEMENT_DETAILS
 ADD (ELEMENT_NAME  VARCHAR2(30 BYTE));

ALTER TABLE RED_REFINING_ELEMENT_DETAILS
 ADD (ELEMENT_NAME  VARCHAR2(30 BYTE));

ALTER TABLE PAD_PENALTY_ATTRIBUTE_DETAILS
 ADD (ELEMENT_NAME  VARCHAR2(30 BYTE));

ALTER TABLE PCAR_PC_ASSAYING_RULES
 ADD (ELEMENT_NAME  VARCHAR2(30 BYTE));