CREATE TABLE VPCM_VAT_PARENT_CHILD_MAP
(
  INTERNAL_INVOICE_REF_NO          VARCHAR2(30 CHAR),
  VAT_INTERNAL_INVOICE_REF_NO      VARCHAR2(30 CHAR),
  VPCM_ID                          VARCHAR2(30 CHAR)
);

ALTER TABLE VPCM_VAT_PARENT_CHILD_MAP ADD (
  CONSTRAINT VPCM_PK
 PRIMARY KEY
 (VPCM_ID));

 CREATE SEQUENCE SEQ_VPCM
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;