alter table GMR_GOODS_MOVEMENT_RECORD drop CONSTRAINT CHK_GMR_TOLLING_GMR_TYPE;
ALTER TABLE GMR_GOODS_MOVEMENT_RECORD add (
  CONSTRAINT CHK_GMR_TOLLING_GMR_TYPE
 CHECK (TOLLING_GMR_TYPE IN ('Input Process','Output Process','Process Activity')));


 alter table GMR_GOODS_MOVEMENT_RECORD modify(TOLLING_GMR_TYPE VARCHAR2 (30 Char));
alter table GMRUL_GMR_UL modify (TOLLING_GMR_TYPE VARCHAR2 (30 Char));

alter table AGMR_ACTION_GMR modify (TOLLING_GMR_TYPE VARCHAR2 (30 Char));


ALTER TABLE AGMR_ACTION_GMR DROP CONSTRAINT CHK_AGMR_TOLLING_GMR_TYPE;

ALTER TABLE AGMR_ACTION_GMR add (
  CONSTRAINT CHK_AGMR_TOLLING_GMR_TYPE
 CHECK (TOLLING_GMR_TYPE IN ('Input Process','Output Process','Process Activity')));

alter table GRD_GOODS_RECORD_DETAIL modify (TOLLING_STOCK_TYPE VARCHAR2 (30 Char));

alter table GRDUL_GOODS_RECORD_DETAIL_UL modify (TOLLING_STOCK_TYPE VARCHAR2 (30 Char));

ALTER TABLE GRD_GOODS_RECORD_DETAIL
  DROP CONSTRAINT CHK_GRD_TOLLING_STOCK_TYPE;

ALTER TABLE GRD_GOODS_RECORD_DETAIL ADD (
  CONSTRAINT CHK_GRD_TOLLING_STOCK_TYPE
 CHECK (TOLLING_STOCK_TYPE IN ('None Tolling','Input Process','Output Process','Process Activity')));

alter table AGRD_ACTION_GRD modify (TOLLING_STOCK_TYPE VARCHAR2 (30 Char));

ALTER TABLE AGRD_ACTION_GRD
  DROP CONSTRAINT CHK_AGRD_TOLLING_STOCK_TYPE;

ALTER TABLE AGRD_ACTION_GRD ADD (
  CONSTRAINT CHK_AGRD_TOLLING_STOCK_TYPE
 CHECK (TOLLING_STOCK_TYPE IN ('None Tolling','Input Process','Output Process','Process Activity')));


 CREATE SEQUENCE SEQ_PA
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

 

alter table WRD_WAREHOUSE_RECEIPT_DETAIL add(PROCESS_ACTIVITY_TYPE VARCHAR2(30 CHAR));
alter table WRDUL_WAREHOUSE_RECEIPT_UL add(PROCESS_ACTIVITY_TYPE VARCHAR2(30 CHAR));