ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
 ADD (IUD_ID  VARCHAR2(15 CHAR));

ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
 ADD CONSTRAINT IUD_INVOICE_UTILITY_DETAIL_PK
 PRIMARY KEY
 (IUD_ID);

CREATE SEQUENCE SEQ_IUD
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 1000000000000000000000000
NOCACHE 
NOCYCLE 
NOORDER