

 --- TABLE to contain the input details required for creating scheduler. 
CREATE TABLE sid_schedule_input_dts
    (
     sid_id VARCHAR2 (15 CHAR)  NOT NULL ,
     start_time TIMESTAMP  NOT NULL ,
     end_type VARCHAR2 (15 CHAR)  NOT NULL ,
     end_time TIMESTAMP ,
     end_no_occu NUMBER (10) ,
     reoccurence_type VARCHAR2 (10 CHAR)  NOT NULL ,
     reoccur_pattern VARCHAR2 (15 CHAR)  NOT NULL ,
     reoccur_pattern_val NUMBER (10) ,
     created_by VARCHAR2 (15 CHAR)  NOT NULL ,
     created_date TIMESTAMP  NOT NULL ,
     is_active CHAR (1 CHAR)  NOT NULL
    );

ALTER TABLE sid_schedule_input_dts
    ADD CONSTRAINT sid_schedule_input_dts_pk PRIMARY KEY ( sid_id );
	
	
--- TABLE to contain the scheduler timer expressions and exec. summary details
CREATE TABLE SD_SCHEDULER_DTS 
    ( 
     SD_ID VARCHAR2 (15 CHAR)  NOT NULL , 
     SID_ID VARCHAR2 (15 CHAR)  NOT NULL , 
     CRON_EXP VARCHAR2 (50 CHAR)  NOT NULL , 
     EXECUTION_CNT NUMBER (15)  NOT NULL , 
     STATUS VARCHAR2 (15 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE SD_SCHEDULER_DTS 
    ADD CONSTRAINT SD_PK PRIMARY KEY ( SD_ID ) ;

ALTER TABLE SD_SCHEDULER_DTS 
    ADD CONSTRAINT SD_SID_FK FOREIGN KEY 
    ( 
     SID_ID
    ) 
    REFERENCES SID_SCHEDULE_INPUT_DTS 
    ( 
     SID_ID
    ) 
;

--- TABLE to hold the job details that need to be scheduled

CREATE TABLE JD_JOB_DETAILS 
    ( 
     JOB_ID VARCHAR2 (15 CHAR)  NOT NULL , 
     JOB_TYPE VARCHAR2 (50 CHAR)  NOT NULL , 
     JOB_CRITERIA VARCHAR2 (1000 CHAR)  NOT NULL ,
	 CORPORATE_ID  VARCHAR2(15 CHAR)  NOT NULL
    ) 
;

ALTER TABLE JD_JOB_DETAILS 
    ADD CONSTRAINT JD_PK PRIMARY KEY ( JOB_ID ) ;
	
--- TABLE to hold the scheduler and job mapping

CREATE TABLE SJD_SCHEDULER_JOB_DETAILS 
    ( 
     SJD_ID VARCHAR2 (15 CHAR)  NOT NULL , 
     SD_ID VARCHAR2 (15 CHAR)  NOT NULL , 
     JOB_ID VARCHAR2 (15 CHAR)  NOT NULL , 
     IS_ACTIVE CHAR (1 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE SJD_SCHEDULER_JOB_DETAILS 
    ADD CONSTRAINT SJD_SCHEDULER_JOB_DETAILS_PK PRIMARY KEY ( SJD_ID ) ;

ALTER TABLE SJD_SCHEDULER_JOB_DETAILS 
    ADD CONSTRAINT SJD_JD_FK FOREIGN KEY 
    ( 
     JOB_ID
    ) 
    REFERENCES JD_JOB_DETAILS 
    ( 
     JOB_ID
    ) 
;

ALTER TABLE SJD_SCHEDULER_JOB_DETAILS 
    ADD CONSTRAINT SJD_SD_FK FOREIGN KEY 
    ( 
     SD_ID
    ) 
    REFERENCES SD_SCHEDULER_DTS 
    ( 
     SD_ID
    ) 
;

-- TABLE to contain the scheduler execution details 
CREATE TABLE SED_SCHEDULER_EXECUTION_DTS 
    ( 
     SED_ID VARCHAR2 (15 CHAR)  NOT NULL , 
     SJD_ID VARCHAR2 (15 CHAR)  NOT NULL , 
     JOB_EXE_ID VARCHAR2 (15 CHAR) , 
     EXECUTION_START_TIME TIMESTAMP  NOT NULL , 
     EXECUTION_END_TIME TIMESTAMP  NOT NULL , 
     EXECUTION_STATUS VARCHAR2 (30 CHAR)  NOT NULL 
    ) 
;

ALTER TABLE SED_SCHEDULER_EXECUTION_DTS 
    ADD CONSTRAINT SED_PK PRIMARY KEY ( SED_ID ) ;

ALTER TABLE SED_SCHEDULER_EXECUTION_DTS 
    ADD CONSTRAINT SED_SJD_FK FOREIGN KEY 
    ( 
     SJD_ID
    ) 
    REFERENCES SJD_SCHEDULER_JOB_DETAILS 
    ( 
     SJD_ID
    ) 
;


-- Sequence for SID_SCHEDULE_INPUT_DTS
CREATE SEQUENCE seq_schid
  START WITH 100
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


-- Sequence for SD_SCHEDULER_DTS
CREATE SEQUENCE seq_sdid
  START WITH 100
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

  -- Sequence for JD_JOB_DETAILS

CREATE   SEQUENCE  seq_jdid
  START WITH 100
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
  -- Sequence for SJD_SCHEDULER_JOB_DETAILS
  CREATE   SEQUENCE  seq_sjdid
  START WITH 100
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

   -- Sequence for SED_SCHEDULER_EXECUTION_DTS

CREATE   SEQUENCE  seq_sed
  START WITH 100
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;