alter table PCDI_PC_DELIVERY_ITEM add QTY_DECLARATION_DATE DATE;
alter table PCDI_PC_DELIVERY_ITEM add QUALITY_DECLARATION_DATE DATE;
alter table PCDI_PC_DELIVERY_ITEM add INCO_LOCATION_DECLARATION_DATE DATE;