ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD
(
 FREE_MATERIAL_STATUS VARCHAR2(3),
 CONSTRAINT CHK_GMR_FREE_MATERIAL_STATUS CHECK (FREE_MATERIAL_STATUS IN ('Y','N','N/A'))
);

ALTER TABLE GMRUL_GMR_UL ADD
(
 FREE_MATERIAL_STATUS VARCHAR2(15)
);