alter table SSWH_SPE_SETTLE_WASHOUT_HEADER add (ACTIVITY_REF_NO varchar2(15), ACTIVITY_TYPE varchar2(15));

alter table SSWH_SPE_SETTLE_WASHOUT_HEADER add (CANCELLATION_DATE  TIMESTAMP(6));

alter table SSWD_SPE_SETTLE_WASHOUT_DETAIL add (PRICE_FIXED varchar2(15), PRICE_TYPE varchar2(15));

alter table SSWD_SPE_SETTLE_WASHOUT_DETAIL add (PRICE_DESC varchar2(4000));