
ALTER TABLE MTFS_MBT_FIN_SETTLEMENT ADD 
(
INTERNAL_GMR_REF_NO     VARCHAR2(15)     NULL,
CONSTRAINT FK_MTFS_INTERNAL_GMR_REF_NO FOREIGN KEY (INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO)
);

ALTER TABLE MTFS_MBT_FIN_SETTLEMENT MODIFY(TO_CP_ID  NULL);