CREATE TABLE IAD_INVOICE_AMOUNT_DETAILS
(
  IAD_ID             VARCHAR2(15 CHAR),
  UTIL_REF_NO        VARCHAR2(15 CHAR),
  INVOICE_REF_NO     VARCHAR2(15 CHAR),
  ELEMENT_NAME       VARCHAR2(15 CHAR),
  TC_AMOUNT          NUMBER(25,10),
  RC_AMOUNT          NUMBER(25,10),
  PENALTY_AMOUNT     NUMBER(25,10),
  FREE_METAL_AMOUNT  NUMBER(25,10)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE IAD_INVOICE_AMOUNT_DETAILS ADD (
  CONSTRAINT IAD_INVOICE_AMOUNT_DETAILS_PK
 PRIMARY KEY
 (IAD_ID));


CREATE SEQUENCE SEQ_IAD
START WITH 0
INCREMENT BY 1
MINVALUE 0
MAXVALUE 100000000000000000000000000
NOCACHE 
NOCYCLE 
NOORDER 

