CREATE TABLE IUS_INVOICE_UTILITY_SUMMARY
(
  IUS_ID                         VARCHAR2(15),
  INTERNAL_ACTION_REF_NO         VARCHAR2(15) NOT NULL,    
  SMELTER_ID                     VARCHAR2(15) NOT NULL,
  UTILITY_REF_NO                 VARCHAR2(15) NOT NULL,
  STATUS                         VARCHAR2(15),
  IS_ACTIVE                      CHAR(1)
);



ALTER TABLE IUS_INVOICE_UTILITY_SUMMARY ADD (
  CONSTRAINT PK_IUS PRIMARY KEY (IUS_ID)
);

ALTER TABLE IUS_INVOICE_UTILITY_SUMMARY ADD (
  CONSTRAINT FK_IUS_INTERNAL_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO),
  CONSTRAINT FK_IUS_SMELTER_ID FOREIGN KEY (SMELTER_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID)
);

CREATE SEQUENCE SEQ_IUS
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


alter table IS_INVOICE_SUMMARY add UTILITY_REF_NO varchar2(15);

