ALTER TABLE SPQ_STOCK_PAYABLE_QTY ADD
(
QTY_TYPE            VARCHAR2(10)    DEFAULT 'Payable',
ACTIVITY_ACTION_ID  VARCHAR2(30),
IS_STOCK_SPLIT      CHAR(1)         DEFAULT 'N',
SUPPLIER_ID         VARCHAR2(20),
SMELTER_ID          VARCHAR2(20),
IN_PROCESS_STOCK_ID VARCHAR2(20),
FREE_METAL_STOCK_ID VARCHAR2(20),
FREE_METAL_QTY      NUMBER (25,10),

CONSTRAINT CHK_SPQ_QTY_TYPE CHECK (QTY_TYPE IN ('Payable','Returnable','Returned')),
CONSTRAINT CHK_SPQ_IS_STOCK_SPLIT CHECK (IS_STOCK_SPLIT IN ('Y','N')),
CONSTRAINT FK_SPQ_ACTIVITY_ACTION_ID FOREIGN KEY (ACTIVITY_ACTION_ID) REFERENCES AXM_ACTION_MASTER (ACTION_ID),
CONSTRAINT FK_SPQ_SUPPLIER_ID FOREIGN KEY (SUPPLIER_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_SPQ_SMELTER_ID FOREIGN KEY (SMELTER_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_SPQ_IN_PROCESS_STOCK_ID FOREIGN KEY (IN_PROCESS_STOCK_ID) REFERENCES GRD_GOODS_RECORD_DETAIL (INTERNAL_GRD_REF_NO),
CONSTRAINT FK_SPQ_FREE_METAL_STOCK_ID FOREIGN KEY (FREE_METAL_STOCK_ID) REFERENCES GRD_GOODS_RECORD_DETAIL (INTERNAL_GRD_REF_NO)
);
