alter table ASM_ASSAY_SUBLOT_MAPPING add(ORDERING NUMBER(6));
alter table AS_ASSAY_CHILD_D add(SUBLOTORDERING NUMBER(6));
alter table AS_ASSAY_CHILD_D add(ELEMENTORDERING NUMBER(6));
alter table WNS_ASSAY_CHILD_D add(SUBLOTORDERING NUMBER(6));