alter table ASM_ASSAY_SUBLOT_MAPPING drop(UMPIRE_ID,UMPIRE_NAME,UMPIRE_REF_NO);

alter table PQCA_PQ_CHEMICAL_ATTRIBUTES add(UMPIRE_ID varchar2(50),UMPIRE_NAME varchar2(100),UMPIRE_REF_NO varchar2(100));