APP DB:

ALTER TABLE IID_INVOICABLE_ITEM_DETAILS
MODIFY(INVOICE_ITEM_AMOUNT NUMBER(35,10));

ALTER TABLE IID_INVOICABLE_ITEM_DETAILS
MODIFY(ITEM_AMOUNT NUMBER(35,10));

DROP SNAPSHOT LOG ON  IID_INVOICABLE_ITEM_DETAILS;
CREATE MATERIALIZED VIEW LOG ON  IID_INVOICABLE_ITEM_DETAILS;