ALTER TABLE GRDUL_GOODS_RECORD_DETAIL_UL
 ADD (PROFIT_CENTER_ID  VARCHAR2(15 BYTE));
 
 ALTER TABLE GRDUL_GOODS_RECORD_DETAIL_UL
 ADD (STRATEGY_ID  VARCHAR2(15 BYTE));


ALTER TABLE GRD_GOODS_RECORD_DETAIL
 ADD (PROFIT_CENTER_ID  VARCHAR2(15 BYTE));
 
 ALTER TABLE GRD_GOODS_RECORD_DETAIL
 ADD (STRATEGY_ID  VARCHAR2(15 BYTE));
 
ALTER TABLE AGRD_ACTION_GRD
 ADD (PROFIT_CENTER_ID  VARCHAR2(15 BYTE));
 
 ALTER TABLE AGRD_ACTION_GRD
 ADD (STRATEGY_ID  VARCHAR2(15 BYTE));