-- Add/modify columns for EOD_END_OF_DAY_DETAILS
alter table EOD_END_OF_DAY_DETAILS add PRECHCEK_END_TIME TIMESTAMP(6);
alter table EOD_END_OF_DAY_DETAILS add PROCESS_END_TIME TIMESTAMP(6);
alter table EOD_END_OF_DAY_DETAILS add PRECHECK_TIME VARCHAR2(20);
alter table EOD_END_OF_DAY_DETAILS add PROCESS_TIME VARCHAR2(20);
alter table EOD_END_OF_DAY_DETAILS add NET_TIME VARCHAR2(20);

alter table EOD_END_OF_DAY_DETAILS add PRECHECK_DURATION INTERVAL DAY(2) TO SECOND(6);
alter table EOD_END_OF_DAY_DETAILS add PROCESS_DURATION INTERVAL DAY(2) TO SECOND(6);
alter table EOD_END_OF_DAY_DETAILS add NET_DURATION INTERVAL DAY(2) TO SECOND(6);

-- Add/modify columns for EOM_END_OF_MONTH_DETAILS
alter table EOM_END_OF_MONTH_DETAILS add PRECHCEK_END_TIME TIMESTAMP(6);
alter table EOM_END_OF_MONTH_DETAILS add PROCESS_END_TIME TIMESTAMP(6);
alter table EOM_END_OF_MONTH_DETAILS add PRECHECK_TIME VARCHAR2(20);
alter table EOM_END_OF_MONTH_DETAILS add PROCESS_TIME VARCHAR2(20);
alter table EOM_END_OF_MONTH_DETAILS add NET_TIME VARCHAR2(20);

alter table EOM_END_OF_MONTH_DETAILS add PRECHECK_DURATION INTERVAL DAY(2) TO SECOND(6);
alter table EOM_END_OF_MONTH_DETAILS add PROCESS_DURATION INTERVAL DAY(2) TO SECOND(6);
alter table EOM_END_OF_MONTH_DETAILS add NET_DURATION INTERVAL DAY(2) TO SECOND(6);

CREATE INDEX IDX_GRDL_AXS ON GRDL_GOODS_RECORD_DETAIL_LOG(INTERNAL_ACTION_REF_NO)
/