ALTER TABLE AK_CORPORATE_LOGO ADD VISITING_ADDRESS VARCHAR2(1000);

ALTER TABLE AK_CORPORATE_LOGO ADD ORGANISATION_NO VARCHAR2(100);

ALTER TABLE AK_CORPORATE_LOGO ADD FOOT_NOTE VARCHAR2(1000);


UPDATE AK_CORPORATE_LOGO
SET 
VISITING_ADDRESS = 'Klarabergsviadukten 90',
ORGANISATION_NO = '5561582205',
FOOT_NOTE = 'The Board is situated in Stockholm';

UPDATE PAD_PROFILE_ADDRESSES
SET ADDRESS_NAME = 'Boliden Commercial AB',
      ADDRESS = 'Box 750, SE-101 35 Stockholm
Sweden'
WHERE ADDRESS_ID = 'PAD-247';