ALTER TABLE PSR_POOL_STOCK_REGISTER
 ADD (INTERNAL_ACTION_REF_NO  VARCHAR2(15));

ALTER TABLE PSR_POOL_STOCK_REGISTER
 ADD (RELEASED_STOCK_QTY  NUMBER(25,4));

ALTER TABLE PSR_POOL_STOCK_REGISTER
 ADD (INTERNAL_GMR_REF_NO  VARCHAR2(15));

ALTER TABLE PSR_POOL_STOCK_REGISTER
 ADD (CURRENT_STOCK_QTY  NUMBER(25,4));


 ALTER TABLE GMR_GOODS_MOVEMENT_RECORD
 ADD (POOL_ID  VARCHAR2(15 ));

 
 ALTER TABLE GMRUL_GMR_UL
 ADD (POOL_ID  VARCHAR2(15 ));
 


ALTER TABLE MOGRD_MOVED_OUT_GRD
drop CONSTRAINT FK_MOGRD_INTERNAL_GRD_REF_NO;


