--APP DB:

ALTER TABLE IID_INVOICABLE_ITEM_DETAILS
MODIFY(INVOICE_ITEM_AMOUNT NUMBER(35,10));

ALTER TABLE IID_INVOICABLE_ITEM_DETAILS
MODIFY(ITEM_AMOUNT NUMBER(35,10));

ALTER TABLE IS_INVOICE_SUMMARY
MODIFY(AMOUNT_PAID NUMBER(35,10));

ALTER TABLE IS_INVOICE_SUMMARY
MODIFY(AMOUNT_TO_PAY_BEFORE_ADJ NUMBER(35,10));

ALTER TABLE IS_INVOICE_SUMMARY
MODIFY(ACCRUED_PUR_AMT NUMBER(35,10));

ALTER TABLE IS_INVOICE_SUMMARY
MODIFY(API_ADJUSTED_AMOUNT NUMBER(35,10));

ALTER TABLE IS_INVOICE_SUMMARY
MODIFY(FREIGHT_ALLOWANCE_AMT NUMBER(35,10));

ALTER TABLE IS_INVOICE_SUMMARY
MODIFY(INVOICE_ADJUSTMENT_AMOUNT NUMBER(35,10));

ALTER TABLE IS_INVOICE_SUMMARY
MODIFY(PROV_PCTG_AMT NUMBER(35,10));

ALTER TABLE IS_INVOICE_SUMMARY
MODIFY(TOTAL_AMOUNT_TO_PAY NUMBER(35,10));

ALTER TABLE IS_INVOICE_SUMMARY
MODIFY(TOTAL_INVOICE_ITEM_AMOUNT NUMBER(35,10));

ALTER TABLE IS_INVOICE_SUMMARY
MODIFY(TOTAL_OTHER_CHARGE_AMOUNT NUMBER(35,10));

ALTER TABLE IS_INVOICE_SUMMARY
MODIFY(TOTAL_PREMIUM_AMOUNT NUMBER(35,10));

ALTER TABLE IS_INVOICE_SUMMARY
MODIFY(TOTAL_TAX_AMOUNT NUMBER(35,10));

DROP SNAPSHOT LOG ON  IID_INVOICABLE_ITEM_DETAILS;
CREATE MATERIALIZED VIEW LOG ON  IID_INVOICABLE_ITEM_DETAILS;