CREATE TABLE PCARUL_ASSAYING_RULES_UL
(
  PCARUL_ID                 VARCHAR2(15 BYTE)   NOT NULL,
  INTERNAL_ACTION_REF_NO    VARCHAR2(15 BYTE)   NOT NULL,
  ENTRY_TYPE                VARCHAR2(30 BYTE)   NOT NULL,
  PCAR_ID                   VARCHAR2(15 BYTE)   NOT NULL,
  INTERNAL_CONTRACT_REF_NO  VARCHAR2(15 BYTE)   NOT NULL,
  ELEMENT_ID                VARCHAR2(15 BYTE),
  FINAL_ASSAY_BASIS_ID      VARCHAR2(20 BYTE),
  COMPARISION               VARCHAR2(30 BYTE),
  SPLIT_LIMIT_BASIS         VARCHAR2(30 BYTE),
  SPLIT_LIMIT               VARCHAR2(15 BYTE),
  SPLIT_LIMIT_UNIT_ID       VARCHAR2(15 BYTE),
  VERSION                   NUMBER(10)          NOT NULL,
  IS_ACTIVE                 CHAR(1 BYTE)        NOT NULL
);


CREATE UNIQUE INDEX PK_PCARUL ON PCARUL_ASSAYING_RULES_UL
(PCARUL_ID);


ALTER TABLE PCARUL_ASSAYING_RULES_UL ADD (
  CONSTRAINT PK_PCARUL
 PRIMARY KEY
 (PCARUL_ID));



CREATE TABLE PCAESLUL_ASSAY_ELM_SPLT_LMT_UL
(
  PCAESLUL_ID            VARCHAR2(15 BYTE)        NOT NULL,
  INTERNAL_ACTION_REF_NO VARCHAR2(15 BYTE)        NOT NULL,
  ENTRY_TYPE             VARCHAR2(30 BYTE)        NOT NULL,
  PCAESL_ID              VARCHAR2(15 BYTE)        NOT NULL,
  PCAR_ID                VARCHAR2(15 BYTE)        NOT NULL,
  ASSAY_MIN_OP           VARCHAR2(2 BYTE),
  ASSAY_MIN_VALUE        VARCHAR2(15 BYTE),
  ASSAY_MAX_OP           VARCHAR2(2 BYTE)         NOT NULL,
  ASSAY_MAX_VALUE        VARCHAR2(15 BYTE),
  APPLICABLE_VALUE       VARCHAR2(15 BYTE),
  VERSION                NUMBER(10)               NOT NULL,
  IS_ACTIVE              CHAR(1 BYTE)             NOT NULL
);


CREATE UNIQUE INDEX PK_PCAESLUL ON PCAESLUL_ASSAY_ELM_SPLT_LMT_UL
(PCAESLUL_ID);


ALTER TABLE PCAESLUL_ASSAY_ELM_SPLT_LMT_UL ADD (
  CONSTRAINT PK_PCAESLUL
 PRIMARY KEY
 (PCAESLUL_ID));



CREATE TABLE ARQDUL_ASSAY_QUALITY_DTL_UL
(
  ARQDUL_ID              VARCHAR2(15 BYTE)                  NOT NULL,
  INTERNAL_ACTION_REF_NO VARCHAR2(15 BYTE)                  NOT NULL,
  ENTRY_TYPE             VARCHAR2(30 BYTE)                  NOT NULL,
  ARQD_ID                VARCHAR2(15 BYTE)                  NOT NULL,
  PCAR_ID                VARCHAR2(15 BYTE)                  NOT NULL,
  PCPQ_ID                VARCHAR2(15 BYTE)                  NOT NULL,
  VERSION                NUMBER(10)                         NOT NULL,
  IS_ACTIVE              CHAR(1 BYTE)                       NOT NULL
);


CREATE UNIQUE INDEX PK_ARQDUL ON ARQDUL_ASSAY_QUALITY_DTL_UL
(ARQDUL_ID);


ALTER TABLE ARQDUL_ASSAY_QUALITY_DTL_UL ADD (
  CONSTRAINT PK_ARQDUL
 PRIMARY KEY
 (ARQDUL_ID));



CREATE SEQUENCE SEQ_PCARUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE SEQ_PCAESLUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE SEQ_ARQDUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;