ALTER TABLE IS_INVOICE_SUMMARY
 ADD (PROV_PCTG_AMT  NUMBER(38,18));

ALTER TABLE IS_INVOICE_SUMMARY
 ADD (ACCRUED_PUR_AMT  NUMBER(38,18));


CREATE INDA_INVOICE_DELTA_AMOUNTS
(
  INDA_ID                       VARCHAR2(15 CHAR),
  INTERNAL_INVOICE_REF_NO       VARCHAR2(15 CHAR),
  INVOICE_CUR_ID                VARCHAR2(15 CHAR),
  VAT_AMOUNT_DEL                NUMBER(38,18),
  PRO_PCTG_AMT_DEL              NUMBER(38,18),
  AMT_TO_PAY_DEL                NUMBER(38,18),
  TOTAL_INV_AMT_BEFORE_ADJ_DEL  NUMBER(38,18),
  ACCRUED_PUR_AMT_DEL           NUMBER(38,18),
  API_ADJ_AMT_DEL               NUMBER(38,18)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE INDA_INVOICE_DELTA_AMOUNTS ADD (
  CONSTRAINT INDA_INVOICE_DELTA_AMOUNTS_PK
 PRIMARY KEY
 (INDA_ID));


CREATE SEQUENCE SEQ_INDA
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 10000000000000000000000000
CACHE 20
NOCYCLE 
NOORDER 


