CREATE TABLE PFI_D
(
  INTERNAL_INVOICE_REF_NO         VARCHAR2(30 BYTE),
  INTERNAL_DOC_REF_NO             VARCHAR2(30 BYTE),
  CP_NAME                         VARCHAR2(100 BYTE),
  CP_ITEM_STOCK_REF_NO            VARCHAR2(30 BYTE),
  SELF_ITEM_STOCK_REF_NO          VARCHAR2(30 BYTE),
  INCO_TERM_LOCATION              VARCHAR2(100 BYTE),
  PRODUCT                         VARCHAR2(30 BYTE),
  NOTIFY_PARTY                    VARCHAR2(30 BYTE),
  INVOICE_QUANTITY                VARCHAR2(30 BYTE),
  INVOICE_QUANTITY_UNIT           VARCHAR2(30 BYTE),
  QUALITY                         VARCHAR2(30 BYTE),
  PAYMENT_TERM                    VARCHAR2(30 BYTE),
  INVOICE_ISSUE_DATE              DATE,
  INVOICE_AMOUNT_UNIT             VARCHAR2(30 BYTE),
  INVOICE_AMOUNT                  VARCHAR2(30 BYTE),
  INVOICE_REF_NO                  VARCHAR2(30 BYTE),
  ORIGIN                          VARCHAR2(100 BYTE),
  INTERNAL_COMMENTS               VARCHAR2(100 BYTE),
  DOCUMENT_DATE                   DATE,
  DOC_REF_NO                      VARCHAR2(30 BYTE)
)


CREATE TABLE PFI_CHILD_D
(
  INTERNAL_INVOICE_REF_NO         VARCHAR2(30 BYTE),
  INTERNAL_DOC_REF_NO             VARCHAR2(30 BYTE),
  STOCK_REF_NO                    VARCHAR2(30 BYTE),
  CONTRACT_ITEM_REF_NO            VARCHAR2(30 BYTE),
  QUANTITY                        VARCHAR2(30 BYTE),
  QUANTITY_UNIT                   VARCHAR2(30 BYTE),
  PRICE                           VARCHAR2(30 BYTE),
  PRICE_UNIT                      VARCHAR2(30 BYTE),
  AMOUNT_UNIT                     VARCHAR2(30 BYTE),
  AMOUNT                          VARCHAR2(30 BYTE),
  IS_FROM                         VARCHAR2(50 BYTE)
)

ALTER TABLE PFI_D
 ADD (CONTRACT_TYPE  VARCHAR2(30 BYTE));

ALTER TABLE PFI_D
 ADD (INVOICE_STATUS  VARCHAR2(30 BYTE));

ALTER TABLE PFI_D
 ADD (SALES_PURCHASE  VARCHAR2(30 BYTE));
 
