alter table II_INVOICABLE_ITEM add(IS_FM_PRICING_UTILITY_APPL CHAR(1) default 'N');

alter table IUS_INVOICE_UTILITY_SUMMARY add(ACTIVITY_DATE DATE);

alter table IS_INVOICE_SUMMARY add(IS_FM_PRICING_UTILITY_APPL CHAR(1) default 'N');