ALTER TABLE GRD_GOODS_RECORD_DETAIL MODIFY(INTERNAL_STOCK_REF_NO VARCHAR2(30));

ALTER TABLE GRDUL_GOODS_RECORD_DETAIL_UL MODIFY(INTERNAL_STOCK_REF_NO VARCHAR2(30));

ALTER TABLE AGRD_ACTION_GRD MODIFY(INTERNAL_STOCK_REF_NO VARCHAR2(30));

ALTER TABLE DGRD_DELIVERED_GRD MODIFY(INTERNAL_STOCK_REF_NO VARCHAR2(30));

ALTER TABLE DGRDUL_DELIVERED_GRD_UL MODIFY(INTERNAL_STOCK_REF_NO VARCHAR2(30));

ALTER TABLE ADGRD_ACTION_DGRD MODIFY(INTERNAL_STOCK_REF_NO VARCHAR2(30));