
CREATE TABLE PQCAPDUL_PR_QLTY_CHEPAY_DTL_UL
(
  PQCAPDUL_ID             VARCHAR2(15)         NOT NULL,
  PQCAPD_ID               VARCHAR2(15)         NOT NULL,
  PQCA_ID                 VARCHAR2(15)         NOT NULL,
  PCDI_ID                 VARCHAR2(15),
  PAYABLE_RULE_ID         VARCHAR2(15)         NOT NULL,
  PAYABLE_PERCENTAGE      NUMBER(25,10),
  INTERNAL_ACTION_REF_NO  VARCHAR2(30)         NOT NULL,
  IS_ACTIVE               CHAR(1)              DEFAULT 'N'  NOT NULL,
  IS_RETURNABLE           CHAR(1)              DEFAULT 'N',
  VERSION                 NUMBER(10)           NOT NULL
)

CREATE SEQUENCE SEQ_PQCAPDUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;