
ALTER TABLE GRD_GOODS_RECORD_DETAIL ADD (IS_WARRANT  CHAR(1 CHAR) DEFAULT 'N');
ALTER TABLE AGRD_ACTION_GRD ADD (IS_WARRANT  CHAR(1 CHAR) DEFAULT 'N');
ALTER TABLE DGRD_DELIVERED_GRD ADD (IS_WARRANT  CHAR(1 CHAR) DEFAULT 'N');
ALTER TABLE ADGRD_ACTION_DGRD ADD (IS_WARRANT  CHAR(1 CHAR) DEFAULT 'N');
ALTER TABLE WRD_WAREHOUSE_RECEIPT_DETAIL ADD (IS_WARRANT  CHAR(1 CHAR) DEFAULT 'N');
ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD (IS_WARRANT  CHAR(1 CHAR) DEFAULT 'N');
ALTER TABLE AGMR_ACTION_GMR ADD (IS_WARRANT  CHAR(1 CHAR) DEFAULT 'N');


ALTER TABLE GRDUL_GOODS_RECORD_DETAIL_UL ADD (IS_WARRANT  CHAR(1 CHAR));
ALTER TABLE DGRDUL_DELIVERED_GRD_UL ADD (IS_WARRANT  CHAR(1 CHAR) );
ALTER TABLE WRDUL_WAREHOUSE_RECEIPT_UL ADD (IS_WARRANT  CHAR(1 CHAR));
ALTER TABLE GMRUL_GMR_UL ADD (IS_WARRANT  CHAR(1 CHAR) );


ALTER TABLE GRD_GOODS_RECORD_DETAIL ADD (WARRANT_NO  VARCHAR2(15 CHAR));
ALTER TABLE AGRD_ACTION_GRD ADD (WARRANT_NO  VARCHAR2(15 CHAR));
ALTER TABLE DGRD_DELIVERED_GRD ADD (WARRANT_NO  VARCHAR2(15 CHAR));
ALTER TABLE ADGRD_ACTION_DGRD ADD (WARRANT_NO  VARCHAR2(15 CHAR));


ALTER TABLE GRDUL_GOODS_RECORD_DETAIL_UL ADD (WARRANT_NO  VARCHAR2(15 CHAR));
ALTER TABLE DGRDUL_DELIVERED_GRD_UL ADD (WARRANT_NO  VARCHAR2(15 CHAR));