ALTER TABLE GRD_GOODS_RECORD_DETAIL ADD
(
SUPP_INTERNAL_GMR_REF_NO       VARCHAR2(15),
CONSTRAINT FK_GRD_SUPP_GMR_REF_NO FOREIGN KEY (SUPP_INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO)
);

ALTER TABLE GRDUL_GOODS_RECORD_DETAIL_UL ADD
(
SUPP_INTERNAL_GMR_REF_NO       VARCHAR2(15)
);

ALTER TABLE AGRD_ACTION_GRD ADD
(
SUPP_INTERNAL_GMR_REF_NO       VARCHAR2(15),
CONSTRAINT FK_AGRD_SUPP_GMR_REF_NO FOREIGN KEY (SUPP_INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO)
);
