ALTER TABLE PCDIUL_PC_DELIVERY_ITEM_UL ADD QTY_DECLARATION_DATE VARCHAR2(15 CHAR);
ALTER TABLE PCDIUL_PC_DELIVERY_ITEM_UL ADD QUALITY_DECLARATION_DATE VARCHAR2(15 CHAR) ;
ALTER TABLE PCDIUL_PC_DELIVERY_ITEM_UL ADD INCO_LOCATION_DECLARATION_DATE VARCHAR2(15 CHAR);
ALTER TABLE PCMUL_PHY_CONTRACT_MAIN_UL ADD CP_ADDRESS_ID VARCHAR2(15 CHAR);
ALTER TABLE PCMUL_PHY_CONTRACT_MAIN_UL ADD IS_LOT_LEVEL_INVOICE CHAR(1 CHAR) ;
ALTER TABLE PCPDQDUL_PD_QUALITY_DTL_UL ADD QUALITY_NAME  VARCHAR2(30 CHAR);
ALTER TABLE PFQPPUL_PHY_FORMULA_QP_PRC_UL ADD IS_SPOT_PRICING CHAR(1 CHAR);
ALTER TABLE PCPCHUL_PAYBLE_CONTNT_HEADR_UL ADD PAYABLE_TYPE VARCHAR2(15 CHAR);
ALTER TABLE  PQDUL_PAYABLE_QUALITY_DTL_UL ADD QUALITY_NAME  VARCHAR2(30 CHAR);
ALTER TABLE TEDUL_TREATMENT_ELEMENT_DTL_UL ADD ELEMENT_NAME  VARCHAR2(30 CHAR);
ALTER TABLE TQDUL_TREATMENT_QUALITY_DTL_UL ADD QUALITY_NAME  VARCHAR2(30 CHAR);
ALTER TABLE PCARUL_ASSAYING_RULES_UL ADD ELEMENT_NAME VARCHAR2(30 CHAR);
ALTER TABLE PCARUL_ASSAYING_RULES_UL ADD QUALITY_ID VARCHAR2(15 CHAR);
ALTER TABLE ARQDUL_ASSAY_QUALITY_DTL_UL ADD QUALITY_NAME  VARCHAR2(30 CHAR);
ALTER TABLE RQDUL_REFINING_QUALITY_DTL_UL ADD QUALITY_NAME  VARCHAR2(30 CHAR);
ALTER TABLE REDUL_REFINING_ELEMENT_DTL_UL ADD ELEMENT_NAME VARCHAR2(30 CHAR)