CREATE TABLE IS_CHILD_D
(
  INTERNAL_INVOICE_REF_NO         VARCHAR2(30 BYTE),
  GMR_REF_NO                      VARCHAR2(30 BYTE),
  GMR_QUANTITY                    VARCHAR2(30 BYTE),
  GMR_QUALITY                     VARCHAR2(30 BYTE),
  PRICE_AS_PER_DEFIND_UOM         VARCHAR2(30 BYTE),
  TOTAL_PRICE_QTY                 VARCHAR2(30 BYTE),
  INTERNAL_DOC_REF_NO             VARCHAR2(30 BYTE),
  GMR_QTY_UNIT                    VARCHAR2(30 BYTE),
  INVOICED_QTY_UNIT               VARCHAR2(30 BYTE),
  INVOICED_PRICE_UNIT             VARCHAR2(30 BYTE)
);