CREATE TABLE IEDA_INVOICE_ELE_DELTA_AMOUNT
(
  IEDA_ID                  VARCHAR2(15 CHAR),
  INTERNAL_INVOICE_REF_NO  VARCHAR2(15 CHAR),
  ELEMENT_ID               VARCHAR2(15 CHAR),
  DELTA_TC_AMOUNT          NUMBER(38,18),
  DELTA_RC_AMOUNT          NUMBER(38,18),
  DELTA_PEN_AMOUNT         NUMBER(38,18),
  DELTA_PAY_AMOUNT         NUMBER(38,18),
  INVOICE_CUR_ID           VARCHAR2(15 CHAR)
);

CREATE UNIQUE INDEX IEDA_PK ON IEDA_INVOICE_ELE_DELTA_AMOUNT
(IEDA_ID);


ALTER TABLE IEDA_INVOICE_ELE_DELTA_AMOUNT ADD (
  CONSTRAINT IEDA_PK
 PRIMARY KEY
 (IEDA_ID));

ALTER TABLE IEDA_INVOICE_ELE_DELTA_AMOUNT ADD (
  CONSTRAINT IEDA_IS_FK 
 FOREIGN KEY (INTERNAL_INVOICE_REF_NO) 
 REFERENCES IS_INVOICE_SUMMARY (INTERNAL_INVOICE_REF_NO));


CREATE SEQUENCE SEQ_IEDA
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
