


DELETE FROM DGM_DOCUMENT_GENERATION_MASTER DGM WHERE DGM.DGM_ID='DGM-API-1-1' AND DGM.IS_CONCENTRATE='N' AND DGM.SEQUENCE_ORDER=2;
DELETE FROM DGM_DOCUMENT_GENERATION_MASTER DGM WHERE DGM.DGM_ID='DGM-API-1-1' AND DGM.IS_CONCENTRATE='N' AND DGM.SEQUENCE_ORDER=3;
DELETE FROM DGM_DOCUMENT_GENERATION_MASTER DGM WHERE DGM.DGM_ID='DGM-API-1-1' AND DGM.IS_CONCENTRATE='N' AND DGM.SEQUENCE_ORDER=4;
DELETE FROM DGM_DOCUMENT_GENERATION_MASTER DGM WHERE DGM.DGM_ID='DGM-API-1-1' AND DGM.IS_CONCENTRATE='N' AND DGM.SEQUENCE_ORDER=5;
COMMIT;



UPDATE DGM_DOCUMENT_GENERATION_MASTER DGM SET DGM.SEQUENCE_ORDER=2 WHERE DGM.DGM_ID='DGM-API-1' AND DGM.DOC_ID='CREATE_API' AND DGM.IS_CONCENTRATE='N' AND DGM.SEQUENCE_ORDER=6;
UPDATE DGM_DOCUMENT_GENERATION_MASTER DGM SET DGM.SEQUENCE_ORDER=3 WHERE DGM.DGM_ID='DGM-API-2' AND DGM.DOC_ID='CREATE_API' AND DGM.IS_CONCENTRATE='N' AND DGM.SEQUENCE_ORDER=7;
UPDATE DGM_DOCUMENT_GENERATION_MASTER DGM SET DGM.SEQUENCE_ORDER=4 WHERE DGM.DGM_ID='DGM-API-3' AND DGM.DOC_ID='CREATE_API' AND DGM.IS_CONCENTRATE='N' AND DGM.SEQUENCE_ORDER=8;
UPDATE DGM_DOCUMENT_GENERATION_MASTER DGM SET DGM.SEQUENCE_ORDER=5 WHERE DGM.DGM_ID='DGM-API-4' AND DGM.DOC_ID='CREATE_API' AND DGM.IS_CONCENTRATE='N' AND DGM.SEQUENCE_ORDER=9;
UPDATE DGM_DOCUMENT_GENERATION_MASTER DGM SET DGM.SEQUENCE_ORDER=6 WHERE DGM.DGM_ID='DGM-API-5' AND DGM.DOC_ID='CREATE_API' AND DGM.IS_CONCENTRATE='N' AND DGM.SEQUENCE_ORDER=10;
COMMIT;


alter table VAT_D add OUR_PERSON_INCHARGE  VARCHAR2(100 CHAR);