ALTER TABLE IIED_INV_ITEM_ELEMENT_DETAILS
 ADD (NEW_INVOICED_QTY  NUMBER(38,18));

ALTER TABLE IIED_INV_ITEM_ELEMENT_DETAILS
 ADD (NEW_INVOICED_QTY_UNIT_ID  VARCHAR2(15 CHAR));

ALTER TABLE IIED_INV_ITEM_ELEMENT_DETAILS
 ADD (NEW_PRICE  NUMBER(38,18));

ALTER TABLE IIED_INV_ITEM_ELEMENT_DETAILS
 ADD (NEW_PRICE_UNIT_ID  VARCHAR2(15 CHAR));

ALTER TABLE IIED_INV_ITEM_ELEMENT_DETAILS
 ADD (NEW_PAYABLE_AMOUNT  NUMBER(38,18));

ALTER TABLE IIED_INV_ITEM_ELEMENT_DETAILS
 ADD (FX_RATE  NUMBER(38,18));

ALTER TABLE IIED_INV_ITEM_ELEMENT_DETAILS
 ADD (NEW_FX_RATE  NUMBER(38,18));
