ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(PAYABLE_QTY_DISPLAY VARCHAR2(1000 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(FREE_METAL_QTY_DISPLAY VARCHAR2(1000 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(TC_AMOUNT_DISPLAY VARCHAR2(1000 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(RC_AMOUNT_DISPLAY VARCHAR2(1000 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(PENALTY_AMOUNT_DISPLAY VARCHAR2(1000 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(FREE_METAL_AMOUNT_DISPLAY VARCHAR2(1000 CHAR));

