ALTER TABLE IUH_INVOICE_UTILITY_HEADER
 ADD (IUH_ID  VARCHAR2(15 CHAR)                     NOT NULL);

ALTER TABLE IUH_INVOICE_UTILITY_HEADER
 ADD CONSTRAINT IUH_INVOICE_UTILITY_HEADER_PK
 PRIMARY KEY
 (IUH_ID);

CREATE SEQUENCE SEQ_IUH
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 100000000000000000000000000
CACHE 20
NOCYCLE 
NOORDER 
