ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD 
(
 IS_APPLY_CONTAINER_CHARGE  CHAR(1)         DEFAULT 'N' NULL,
 MODE_OF_TRANSPORT          VARCHAR2(15)                NULL,
 ARRIVAL_DATE               DATE                        NULL,
 CONSTRAINT CHK_GMR_IS_CONTAINER_CHARGE CHECK (IS_APPLY_CONTAINER_CHARGE IN ('Y','N'))
); 

ALTER TABLE GMRUL_GMR_UL ADD
(
 IS_APPLY_CONTAINER_CHARGE  CHAR(1)         NULL,
 MODE_OF_TRANSPORT          VARCHAR2(15)    NULL,
 ARRIVAL_DATE               DATE            NULL
); 

ALTER TABLE AGMR_ACTION_GMR ADD 
(
 IS_APPLY_CONTAINER_CHARGE  CHAR(1)         DEFAULT 'N' NULL,
 MODE_OF_TRANSPORT          VARCHAR2(15)                NULL,
 ARRIVAL_DATE               DATE                        NULL,
 CONSTRAINT CHK_AGMR_IS_CONTAINER_CHARGE CHECK (IS_APPLY_CONTAINER_CHARGE IN ('Y','N'))
); 

ALTER TABLE GRD_GOODS_RECORD_DETAIL ADD DATE_OF_MOVEMENT DATE NULL;

ALTER TABLE GRDUL_GOODS_RECORD_DETAIL_UL ADD DATE_OF_MOVEMENT DATE NULL;

ALTER TABLE AGRD_ACTION_GRD ADD DATE_OF_MOVEMENT DATE NULL;

ALTER TABLE DGRD_DELIVERED_GRD ADD DATE_OF_MOVEMENT DATE  NULL;

ALTER TABLE DGRDUL_DELIVERED_GRD_UL ADD DATE_OF_MOVEMENT DATE NULL;

ALTER TABLE ADGRD_ACTION_DGRD ADD DATE_OF_MOVEMENT DATE NULL;