ALTER TABLE sid_stock_inventory_detail
 ADD (is_provisional_stock  CHAR(1));

ALTER TABLE sid_stock_inventory_detail
 ADD (parent_provsional_stock_id  VARCHAR2(15));

ALTER TABLE sid_stock_inventory_detail
 ADD (ratio_proportion  NUMBER(25,10));

ALTER TABLE sid_stock_inventory_detail
 ADD (level_no  NUMBER(5));

ALTER TABLE sid_stock_inventory_detail
 ADD (LEVELWISE_CREATED_DATE TIMESTAMP(6));

ALTER TABLE GRD_GOODS_RECORD_DETAIL ADD(PARENT_IM_STOCK_ID VARCHAR2(15));
ALTER TABLE GRDUL_GOODS_RECORD_DETAIL_UL ADD(PARENT_IM_STOCK_ID VARCHAR2(15));
ALTER TABLE AGRD_ACTION_GRD ADD(PARENT_IM_STOCK_ID VARCHAR2(15));

ALTER TABLE GRD_GOODS_RECORD_DETAIL ADD(PARENT_CLONE_STOCK_ID VARCHAR2(15));
ALTER TABLE GRDUL_GOODS_RECORD_DETAIL_UL ADD(PARENT_CLONE_STOCK_ID VARCHAR2(15));
ALTER TABLE AGRD_ACTION_GRD ADD(PARENT_CLONE_STOCK_ID VARCHAR2(15));


