alter table PFD_PRICE_FIXATION_DETAILS add PARENT_PFD_ID VARCHAR2 (15 Char);
alter table PFD_PRICE_FIXATION_DETAILS add IS_CANCEL Char (1 Char);
alter table PFD_PRICE_FIXATION_DETAILS add CANCEL_ACTION_REF_NO VARCHAR2 (15 Char);