 alter table FMPFD_PRICE_FIXATION_DETAILS add HEDGE_CORRECTION_DATE DATE;
 alter table FMPFH_PRICE_FIXATION_HEADER drop column HEDGE_CORRECTION_DATE;

 ALTER TABLE FMPFAM_PRICE_ACTION_MAPPING ADD (
  CONSTRAINT FMPFAM_FMPFD_ID 
 FOREIGN KEY (FMPFD_ID) 
 REFERENCES FMPFD_PRICE_FIXATION_DETAILS (FMPFD_ID));