ALTER TABLE PFI_D
 ADD (CP_ADDRESS  VARCHAR2(100 CHAR));

ALTER TABLE PFI_D
 ADD (CP_CITY  VARCHAR2(100 CHAR));

ALTER TABLE PFI_D
 ADD (CP_COUNTRY  VARCHAR2(100 CHAR));

ALTER TABLE PFI_D
 ADD (CP_ZIP  VARCHAR2(100 CHAR));

ALTER TABLE PFI_D
 ADD (CP_STATE  VARCHAR2(100 CHAR));

ALTER TABLE IS_D
MODIFY(PROVISIONAL_INVOICE_AMOUNT VARCHAR2(50 CHAR));