CREATE INDEX IDX_PQCAPD_PQCA_ID ON PQCAPD_PRD_QLTY_CATTR_PAY_DTLS(PQCA_ID);

DROP INDEX IDX_PQCA2;

CREATE INDEX IDX_PQCA2 ON PQCA_PQ_CHEMICAL_ATTRIBUTES(ASM_ID, IS_ACTIVE);

CREATE INDEX IDX_PQCA3 ON PQCA_PQ_CHEMICAL_ATTRIBUTES(IS_DEDUCTIBLE);

CREATE INDEX IDX_DIPQ_VERSION ON  DIPQ_DELIVERY_ITEM_PAYABLE_QTY(VERSION);

CREATE INDEX IDX_CIQS_VERSION ON CIQS_CONTRACT_ITEM_QTY_STATUS(VERSION);

CREATE INDEX IDX_PCI_VERSION ON PCI_PHYSICAL_CONTRACT_ITEM(VERSION);

CREATE INDEX IDX_PCIPF_VERSION ON PCIPF_PCI_PRICING_FORMULA(VERSION);

CREATE INDEX IDX_DIQS_VERSION ON DIQS_DELIVERY_ITEM_QTY_STATUS(VERSION);

CREATE INDEX IDX_CIPQ_VERSION ON CIPQ_CONTRACT_ITEM_PAYABLE_QTY(VERSION);

CREATE INDEX IDX_CQD_VERSION ON CQS_CONTRACT_QTY_STATUS(VERSION);