CREATE TABLE TBD_TRANSPORT_BOOKING_DETAIL
(
TBD_ID VARCHAR2(15) NOT NULL,
CORPORATE_ID varchar2(15) not null,
PRODUCT_ID VARCHAR2(15) NOT NULL,
ACTIVITY_DATE DATE NOT NULL,
BOOKING_REF_NO VARCHAR2(30) NOT NULL,
CP_BOOKING_REF_NO VARCHAR2(50) NOT NULL,
BOOKING_BASIS VARCHAR2(20) NOT NULL,
BOOKING_DATE DATE NOT NULL,
CAPACITY_BOOKED NUMBER(25,10) NOT NULL,
CAPACITY_UNIT_ID VARCHAR2(15) NOT NULL,
ETA DATE NOT NULL,
ETD DATE NOT NULL,
MODE_OF_TRANSPORT VARCHAR2(5) NOT NULL,
Shipper_ID varchar2(20) not null,
Shipper_Address varchar2(4000),
Shipping_Agent_id varchar2(20),
Vessel_Name varchar2(50),
Voyage_No varchar2(50),
LOADING_COUNTRY_ID VARCHAR2 (15) NOT NULL,
LOADING_STATE_ID VARCHAR2 (15)   ,
LOADING_CITY_ID VARCHAR2 (15) NOT NULL,
DISCHARGE_COUNTRY_ID VARCHAR2(15) NOT NULL,
DISCHARGE_STATE_ID VARCHAR2 (15) ,
DISCHARGE_CITY_ID VARCHAR2 (15) NOT NULL,
TRANS_SHIPMENT_COUNTRY_ID VARCHAR2 (15),
TRANS_SHIPMENT_STATE_ID VARCHAR2 (15),
TRANS_SHIPMENT_CITY_ID VARCHAR2 (15),
IS_DELETE CHAR(1) NOT NULL,
INTERNAL_ACTION_REF_NO varchar2(15) not null,
REMARKS VARCHAR2(4000),
CONSTRAINT PK_TBD PRIMARY KEY (TBD_ID),
CONSTRAINT FK_TBD_CORPORATE_ID FOREIGN KEY (CORPORATE_ID) REFERENCES AK_CORPORATE (CORPORATE_ID),
CONSTRAINT FK_TBD_INT_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO),
CONSTRAINT FK_TBD_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PDM_PRODUCTMASTER (PRODUCT_ID),
CONSTRAINT FK_TBD_CAPACITY_UNIT_ID FOREIGN KEY (CAPACITY_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID),
CONSTRAINT FK_TBD_Shipper_ID FOREIGN KEY (Shipper_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_TBD_Shipping_Agent_id FOREIGN KEY (Shipping_Agent_id) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_TBD_LOADING_COUNTRY_ID FOREIGN KEY (LOADING_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_TBD_LOADING_STATE_ID FOREIGN KEY (LOADING_STATE_ID) REFERENCES SM_STATE_MASTER (STATE_ID),
CONSTRAINT FK_TBD_LOADING_CITY_ID FOREIGN KEY (LOADING_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),
CONSTRAINT FK_TBD_DISCHARGE_COUNTRY_ID FOREIGN KEY (DISCHARGE_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_TBD_DISCHARGE_STATE_ID FOREIGN KEY (DISCHARGE_STATE_ID) REFERENCES SM_STATE_MASTER (STATE_ID),
CONSTRAINT FK_TBD_DISCHARGE_CITY_ID FOREIGN KEY (DISCHARGE_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),
CONSTRAINT FK_TBD_TRANS_SHIP_COUNTRY_ID FOREIGN KEY (TRANS_SHIPMENT_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_TBD_TRANS_SHIP_STATE_ID FOREIGN KEY (TRANS_SHIPMENT_STATE_ID) REFERENCES SM_STATE_MASTER (STATE_ID),
CONSTRAINT FK_TBD_TRANS_SHIP_CITY_ID FOREIGN KEY (TRANS_SHIPMENT_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),

CONSTRAINT CHK_TBD_BOOKING_BASIS CHECK (BOOKING_BASIS IN ('Purchase','Sales','Internal Movement')),
CONSTRAINT CHK_TBD_MODE_OF_TRANSPORT CHECK (MODE_OF_TRANSPORT IN ('Air','Rail','Ship','Truck')),
CONSTRAINT CHK_TBD_IS_DELETE CHECK (IS_DELETE IN ('Y','N'))
);

ALTER TABLE VD_VOYAGE_DETAIL ADD
(
TRANSPORT_BOOKING_ID VARCHAR2(15),
CONSTRAINT FK_VD_TRANSPORT_BOOKING_ID FOREIGN KEY (TRANSPORT_BOOKING_ID) REFERENCES TBD_TRANSPORT_BOOKING_DETAIL (TBD_ID)
);

ALTER TABLE VDUL_VOYAGE_DETAIL_UL ADD
(
TRANSPORT_BOOKING_ID VARCHAR2(15)
);