
CREATE TABLE ACS_AMEND_CONTRACT_SUMMARY
(
  DOC_ID                    VARCHAR2(15),
  DOC_TYPE                  VARCHAR2(15),
  TEMPLATE_TYPE             VARCHAR2(15),
  TEMPLATE_NAME             VARCHAR2(50),
  INTERNAL_DOC_REF_NO       VARCHAR2(15),
  VER_NO                    NUMBER(5),
  ISSUE_DATE                DATE,
  IS_AMENDMENT              CHAR(1),
  STATUS                    VARCHAR2(15),
  CREATED_BY                VARCHAR2(15),
  CREATED_DATE              TIMESTAMP(6),
  UPDATED_BY                VARCHAR2(15),
  UPDATED_DATE              TIMESTAMP(6),
  CANCELLED_BY              VARCHAR2(15),
  CANCELLED_DATE            TIMESTAMP(6),
  SEND_DATE                 DATE,
  RECEIVED_DATE             DATE,
  INTERNAL_CONTRACT_REF_NO  VARCHAR2(15),
  CONTRACT_REF_NO           VARCHAR2(30),
  CONTRACT_TYPE             CHAR(1),
  CORPORATE_ID              VARCHAR2(15),
  CONTRACT_SIGNING_DATE     DATE,
  APPROVAL_TYPE             VARCHAR2(30),
  AMENDMENT_NO              NUMBER(5),
  WATERMARK                 VARCHAR2(30),
  AMENDMENT_DATE            DATE,
  DOCUMENT_PRINT_TYPE       VARCHAR2(30)
);

ALTER TABLE ACS_AMEND_CONTRACT_SUMMARY ADD (
  CONSTRAINT PK_ACS
 PRIMARY KEY
 (DOC_ID));


ALTER TABLE ACS_AMEND_CONTRACT_SUMMARY ADD (
  CONSTRAINT FK_ACS_INT_CON_REF_NO 
 FOREIGN KEY (INTERNAL_CONTRACT_REF_NO) 
 REFERENCES PCM_PHYSICAL_CONTRACT_MAIN (INTERNAL_CONTRACT_REF_NO));

CREATE TABLE ACD_AMEND_CONTRACT_DETAILS
(
  DOC_ID                VARCHAR2(15),
  DISPLAY_ORDER         NUMBER(8,2),
  FIELD_LAYOUT_ID       VARCHAR2(15),
  SECTION_NAME          VARCHAR2(50),
  FIELD_NAME            VARCHAR2(50),
  IS_PRINT_REQD         CHAR(1),
  PRE_CONTENT_TEXT_ID   VARCHAR2(15),
  POST_CONTENT_TEXT_ID  VARCHAR2(15),
  CONTRACT_CONTENT      CLOB,
  PRE_CONTENT_TEXT      CLOB,
  POST_CONTENT_TEXT     CLOB,
  IS_CUSTOM_SECTION     CHAR(1),
  IS_FOOTER_SECTION     CHAR(1),
  IS_AMEND_SECTION      CHAR(1),
  PRINT_TYPE            VARCHAR2(15)       DEFAULT 'FULL',
  IS_CHANGED            CHAR(1)
);

ALTER TABLE ACD_AMEND_CONTRACT_DETAILS ADD (
  CONSTRAINT PK_ACD_AMEND
 PRIMARY KEY
 (DOC_ID, DISPLAY_ORDER));

ALTER TABLE ACD_AMEND_CONTRACT_DETAILS ADD (
  CONSTRAINT FK_ACD_DOC_ID 
 FOREIGN KEY (DOC_ID) 
 REFERENCES ACS_AMEND_CONTRACT_SUMMARY (DOC_ID));

CREATE SEQUENCE SEQ_AMEND_DOC
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

alter table COD_CONTRACT_OUTPUT_DETAIL modify DISPLAY_ORDER NUMBER(8,2);
alter table COD_CONTRACT_OUTPUT_DETAIL add  DOCUMENT_TYPE varchar2(15);