ALTER TABLE PE_METALS_BUILD3_DEV.IID_INVOICABLE_ITEM_DETAILS
 ADD (CONTRACT_TYPE  VARCHAR2(15 BYTE));

ALTER TABLE PE_METALS_BUILD3_DEV.ITD_INVOICE_TAX_DETAILS
 ADD (FX_RATE  NUMBER(38,18));

ALTER TABLE PE_METALS_BUILD3_DEV.IS_INVOICE_SUMMARY
 ADD (IS_PROV_CREATED  CHAR(1 BYTE) DEFAULT 'N');