CREATE TABLE DITHUL_DI_TREATMENT_HEADER_UL
(
  DITHUL_ID               VARCHAR2(15 BYTE)     NOT NULL,
  INTERNAL_ACTION_REF_NO  VARCHAR2(15 BYTE)     NOT NULL,
  ENTRY_TYPE              VARCHAR2(30 BYTE)     NOT NULL,
  DITH_ID                 VARCHAR2(15 BYTE)     NOT NULL,
  PCDI_ID                 VARCHAR2(15 BYTE)     NOT NULL,
  PCTH_ID                 VARCHAR2(15 BYTE)     NOT NULL,
  VERSION                 NUMBER(10)            NOT NULL,
  IS_ACTIVE               CHAR(1 BYTE)          DEFAULT 'Y'                   NOT NULL
);

ALTER TABLE DITHUL_DI_TREATMENT_HEADER_UL ADD (
  CONSTRAINT PK_DITHUL
 PRIMARY KEY
 (DITHUL_ID));



CREATE TABLE DIRHUL_DI_REFINING_HEADER_UL
(
  DIRHUL_ID               VARCHAR2(15 BYTE)     NOT NULL,
  INTERNAL_ACTION_REF_NO  VARCHAR2(15 BYTE)     NOT NULL,
  ENTRY_TYPE              VARCHAR2(30 BYTE)     NOT NULL,
  DIRH_ID                 VARCHAR2(15 BYTE)     NOT NULL,
  PCDI_ID                 VARCHAR2(15 BYTE)     NOT NULL,
  PCRH_ID                 VARCHAR2(15 BYTE)     NOT NULL,
  VERSION                 NUMBER(10)            NOT NULL,
  IS_ACTIVE               CHAR(1 BYTE)          DEFAULT 'Y'       

            NOT NULL
);

ALTER TABLE DIRHUL_DI_REFINING_HEADER_UL ADD (
  CONSTRAINT PK_DIRHUL
 PRIMARY KEY
 (DIRHUL_ID ));



CREATE TABLE DIPHUL_DI_PENALTY_HEADER_UL
(
  DIPHUL_ID               VARCHAR2(15 BYTE)     NOT NULL,
  INTERNAL_ACTION_REF_NO  VARCHAR2(15 BYTE)     NOT NULL,
  ENTRY_TYPE              VARCHAR2(30 BYTE)     NOT NULL,
  DIPH_ID                 VARCHAR2(15 BYTE)     NOT NULL,
  PCDI_ID                 VARCHAR2(15 BYTE)     NOT NULL,
  PCAPH_ID                VARCHAR2(15 BYTE)     NOT NULL,
  VERSION                 NUMBER(10)            NOT NULL,
  IS_ACTIVE               CHAR(1 BYTE)          DEFAULT 'Y'       

            NOT NULL
);

ALTER TABLE DIPHUL_DI_PENALTY_HEADER_UL ADD (
  CONSTRAINT PK_DIPHUL
 PRIMARY KEY
 (DIPHUL_ID ));


  CREATE SEQUENCE SEQ_DITHUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  CREATE SEQUENCE SEQ_DIRHUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  CREATE SEQUENCE SEQ_DIPHUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE TABLE CIPQL_CTRT_ITM_PAYABLE_QTY_LOG
(
  CIPQ_ID                        VARCHAR2(15 BYTE) NOT NULL,
  INTERNAL_ACTION_REF_NO         VARCHAR2(15 BYTE),
  ENTRY_TYPE                     VARCHAR2(30 BYTE) NOT NULL,
  INTERNAL_CONTRACT_ITEM_REF_NO  VARCHAR2(15 BYTE) NOT NULL,
  ELEMENT_ID                     VARCHAR2(15 BYTE),
  PAYABLE_QTY_DELTA              NUMBER(25,10),
  QTY_UNIT_ID                    VARCHAR2(15 BYTE),
  VERSION                        NUMBER(10)     NOT NULL,
  IS_ACTIVE                     CHAR(1 BYTE)    DEFAULT 'Y'                   NOT NULL
);


CREATE TABLE DIPQL_DEL_ITM_PAYBLE_QTY_LOG
(
  DIPQ_ID                       VARCHAR2(15 BYTE) NOT NULL,
  INTERNAL_ACTION_REF_NO        VARCHAR2(15 BYTE),
  ENTRY_TYPE                    VARCHAR2(30 BYTE) NOT NULL,
  PCDI_ID                       VARCHAR2(15 BYTE) NOT NULL,
  ELEMENT_ID                    VARCHAR2(15 BYTE),
  PAYABLE_QTY_DELTA             NUMBER(25,10),
  QTY_UNIT_ID                   VARCHAR2(15 BYTE),
  PRICE_OPTION_CALL_OFF_STATUS  VARCHAR2(30 BYTE) NOT NULL,
  VERSION                       NUMBER(10)      NOT NULL,
  IS_ACTIVE                     CHAR(1 BYTE)    DEFAULT 'Y'                   NOT NULL,
  IS_PRICE_OPTIONALITY_PRESENT  CHAR(1 BYTE)    DEFAULT 'Y'
);



CREATE TABLE SPQL_STOCK_PAYABLE_QTY_LOG
(
  SPQ_ID                VARCHAR2(15 BYTE)       NOT NULL,
  INTERNAL_ACTION_REF_NO VARCHAR2(15 BYTE),
  ENTRY_TYPE             VARCHAR2(30 BYTE) NOT NULL,
  INTERNAL_GMR_REF_NO   VARCHAR2(15 BYTE)       NOT NULL,
  ACTION_NO             NUMBER(2)               NOT NULL,
  STOCK_TYPE            CHAR(1 BYTE)            DEFAULT 'P'                   NOT NULL,
  INTERNAL_GRD_REF_NO   VARCHAR2(15 BYTE),
  INTERNAL_DGRD_REF_NO  VARCHAR2(15 BYTE),
  ELEMENT_ID            VARCHAR2(15 BYTE),
  PAYABLE_QTY_DELTA     NUMBER(25,10),
  QTY_UNIT_ID           VARCHAR2(15 BYTE),
  VERSION               NUMBER(10),
  IS_ACTIVE             CHAR(1 BYTE)            DEFAULT 'Y'                   NOT NULL
);


