ALTER TABLE YPD_YIELD_PCT_DETAIL
 ADD (IS_ACTIVE  CHAR(1)     DEFAULT 'Y');


ALTER TABLE YPD_YIELD_PCT_DETAIL
 ADD (INTERNAL_ACTION_REF_NO  VARCHAR2(15));
 

ALTER TABLE YPD_YIELD_PCT_DETAIL
 ADD (ACTION_NO  NUMBER);
 
 
 
 ALTER TABLE YPD_YIELD_PCT_DETAIL ADD (
  CONSTRAINT FK_YPD_INTERNAL_ACTION_REF_NO 
 FOREIGN KEY (INTERNAL_ACTION_REF_NO) 
 REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO));






ALTER TABLE GMR_GOODS_MOVEMENT_RECORD
DROP CONSTRAINT CHK_GMR_TOLLING_GMR_TYPE;


ALTER TABLE GMR_GOODS_MOVEMENT_RECORD
ADD CONSTRAINT CHK_GMR_TOLLING_GMR_TYPE  CHECK (TOLLING_GMR_TYPE IN ('Mark For Tolling','Received Materials','Output Process','Process Activity','Input Process','Pledge','Financial Settlement','Return Material'));



ALTER TABLE AGMR_ACTION_GMR
DROP CONSTRAINT CHK_AGMR_TOLLING_GMR_TYPE;


ALTER TABLE AGMR_ACTION_GMR
ADD CONSTRAINT CHK_AGMR_TOLLING_GMR_TYPE  CHECK (TOLLING_GMR_TYPE IN ('Mark For Tolling','Received Materials','Output Process','Process Activity','Input Process','Pledge','Financial Settlement','Return Material'));


 
