DROP TABLE ICC_INVOICE_CONTAINER_CHARGES CASCADE CONSTRAINTS;

CREATE TABLE ICC_INVOICE_CONTAINER_CHARGES
(
  ICC_ID                    VARCHAR2(15 CHAR)       NOT NULL,
  STOCK_ID                  VARCHAR2(15 CHAR)       NOT NULL,
  CP_ID                     VARCHAR2(20 CHAR)       NOT NULL,
  INTERNAL_INVOICE_REF_NO   VARCHAR2(15 CHAR)       NOT NULL,
  INTERNAL_CONTRACT_REF_NO  VARCHAR2(15 CHAR)       NOT NULL,
  DATE_OF_MOVEMENT          DATE                    NOT NULL,
  NO_OF_CONTAINERS          NUMBER(9)               NOT NULL,
  CONTAINER_SIZE            VARCHAR2(30 CHAR)       NOT NULL,
  CONTAINER_NO              VARCHAR2(30 CHAR)       NOT NULL,
  CHARGE_CUR_ID             VARCHAR2(15 CHAR)       NOT NULL,
  CHARGE_ID                 VARCHAR2(15 CHAR)       NOT NULL,
  CHARGE_NAME               VARCHAR2(50 CHAR)       NOT NULL,
  CHARGE_TYPE               VARCHAR2(30 CHAR)       NOT NULL,
  CHARGE                    NUMBER(38,18)           NOT NULL,
  CHARGE_AMOUNT             NUMBER(38,18),
  AMOUNT_IN_INV_CUR         NUMBER(38,18),
  IS_ACTIVE                 CHAR(1 CHAR)            DEFAULT 'Y',
  FX_RATE                   VARCHAR2(30 CHAR)
  
)

CREATE UNIQUE INDEX ICC_PK ON ICC_INVOICE_CONTAINER_CHARGES (ICC_ID);

ALTER TABLE ICC_INVOICE_CONTAINER_CHARGES ADD (
  CONSTRAINT FK_ICC_CHARGE_CUR_ID 
 FOREIGN KEY (CHARGE_CUR_ID) 
 REFERENCES CM_CURRENCY_MASTER (CUR_ID),
  CONSTRAINT FK_ICC_CP_ID 
 FOREIGN KEY (CP_ID) 
 REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
  CONSTRAINT FK_ICC_STOCK_ID
 FOREIGN KEY (STOCK_ID) 
 REFERENCES GRD_GOODS_RECORD_DETAIL (INTERNAL_GRD_REF_NO),
 CONSTRAINT FK_ICC_INT_INV_REF_NO
 FOREIGN KEY (INTERNAL_INVOICE_REF_NO) 
 REFERENCES IS_INVOICE_SUMMARY(INTERNAL_INVOICE_REF_NO),
  CONSTRAINT FK_ICC_INT_CONT_REF_NO
 FOREIGN KEY (INTERNAL_CONTRACT_REF_NO) 
 REFERENCES PCM_PHYSICAL_CONTRACT_MAIN (INTERNAL_CONTRACT_REF_NO));


DROP SEQUENCE SEQ_ICC

CREATE SEQUENCE SEQ_ICC
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


