ALTER TABLE GRD_GOODS_RECORD_DETAIL DROP CONSTRAINT CHK_GRD_TOLLING_STOCK_TYPE;
ALTER TABLE AGRD_ACTION_GRD DROP CONSTRAINT CHK_AGRD_TOLLING_STOCK_TYPE;
 
ALTER TABLE GRD_GOODS_RECORD_DETAIL ADD
(
ASSAY_CONTENT           NUMBER(25,10),
ASSAY_HEADER_ID         VARCHAR2(15),
CONSTRAINT FK_GRD_ASSAY_HEADER_ID FOREIGN KEY (ASSAY_HEADER_ID) REFERENCES ASH_ASSAY_HEADER (ASH_ID),
CONSTRAINT CHK_GRD_TOLLING_STOCK_TYPE CHECK (TOLLING_STOCK_TYPE IN ('None Tolling','MFT In Process Stock','Delta MFT IP Stock','RM In Process Stock','RM Out Process Stock','Process Activity','Clone Stock','Input Process','Output Process','Free Material Stock','Pledge Stock','Financial Settlement Stock'))
);

ALTER TABLE AGRD_ACTION_GRD ADD
(
ASSAY_CONTENT           NUMBER(25,10),
ASSAY_HEADER_ID         VARCHAR2(15),
CONSTRAINT FK_AGRD_ASSAY_HEADER_ID FOREIGN KEY (ASSAY_HEADER_ID) REFERENCES ASH_ASSAY_HEADER (ASH_ID),
CONSTRAINT CHK_AGRD_TOLLING_STOCK_TYPE CHECK (TOLLING_STOCK_TYPE IN ('None Tolling','MFT In Process Stock','Delta MFT IP Stock','RM In Process Stock','RM Out Process Stock','Process Activity','Clone Stock','Input Process','Output Process','Free Material Stock','Pledge Stock','Financial Settlement Stock'))
);

ALTER TABLE GRDUL_GOODS_RECORD_DETAIL_UL ADD
(
ASSAY_CONTENT           VARCHAR2 (25),
ASSAY_HEADER_ID         VARCHAR2(15)
);