ALTER TABLE EVD_ECONOMIC_VALUE_DETAILS ADD (CONTRACT_TYPE  VARCHAR2(15));


ALTER TABLE EVD_ECONOMIC_VALUE_DETAILS ADD (CONSTRAINT CHK_EVD_CONTRACT_TYPE CHECK (CONTRACT_TYPE IN ('Purchase','Sales','Sell Tolling','Buy Tolling')));
