DROP MATERIALIZED VIEW MV_BI_DER_PNL_EODEOM;
DROP TABLE MV_BI_DER_PNL_EODEOM;
create materialized view MV_BI_DER_PNL_EODEOM
refresh force on demand
as
select bdp.corporate_id,
       bdp.corporate_name,
       bdp.product_type,
       bdp.profit_center_id,
       bdp.profit_center,
       bdp.strategy_id,
       bdp.strategy_name,
       bdp.product_id,
       bdp.product_name,
       bdp.quality_id,
       bdp.quality_name,
       bdp.eod_date,
       bdp.eod_eom_flag,
       bdp.position_type,
       bdp.position_sub_type,
       bdp.contract_ref_no,
       bdp.external_ref_no,
       bdp.issue_trade_date,
       bdp.cp_id,
       bdp.cp_name,
       bdp.payment_term,
       bdp.derivative_purpose,
       bdp.option_type,
       bdp.allocated_phy_refno,
       bdp.group_cur_code,
       bdp.corporate_base_currency,
       bdp.contract_quantity,
       bdp.contract_quantity_uom,
       bdp.quantity_in_base_uom,
       bdp.quantity_in_lots,
       bdp.valuation_instrument_id,
       bdp.valuation_instrument,
       bdp.derivative_def_id,
       bdp.derivative_def_name,
       bdp.valuation_month,
       bdp.value_date,
       bdp.contract_price,
       bdp.trade_price_unit,
       bdp.strike_price,
       bdp.strike_price_unit,
       bdp.premium,
       bdp.premium_price_unit,
       bdp.m2m_settlement_price,
       bdp.net_settlement_price,
       bdp.settlement_price_unit,
       bdp.market_value_in_val_ccy,
       bdp.market_value_cur_id,
       bdp.market_value_cur_code,
       bdp.base_cur_id,
       bdp.base_cur_code,
       bdp.base_quantity_uom,
       bdp.average_period_from,
       bdp.average_period_to,
       bdp.commision_value,
       bdp.commission_value_currency,
       bdp.expiry_date,
       bdp.prompt_date,
       bdp.prompt_details,
       bdp.prompt_month_year,
       bdp.prompt_year,
       bdp.attribute_1,
       bdp.attribute_2,
       bdp.attribute_3,
       bdp.attribute_4,
       bdp.attribute_5,
       bdp.fixed_avg_price,
       bdp.unfixed_avg_price,
       bdp.clearer_comm_in_base,
       bdp.clearer_cur_to_base,
       bdp.trade_value_in_base,
       bdp.market_value_in_base,
       bdp.trade_type,
       bdp.instrument_type,
       bdp.instrument_sub_type,
       bdp.pnl_in_trade_cur,
       bdp.pnl_in_trade_cur_id,
       bdp.pnl_in_trade_cur_code,
       bdp.trade_cur_to_base_exch_rate,
       bdp.trade_cur_to_base_bank_fx_rate,
       bdp.prev_day_unr_pnl_in_base_cur,
       bdp.unrealized_pnl_in_base_cur,
       bdp.pnl_change_in_base_currency,
       bdp.clearer_cur_to_base_bk_fx_rate,
       bdp.trade_clearer_comm_amt
  from bdp_bi_dertivative_pnl@eka_eoddb bdp,
       tdc_trade_date_closure@eka_eoddb   tdc
 where bdp.process_id = tdc.process_id
   and bdp.corporate_id = tdc.corporate_id       
