CREATE TABLE IS_DC_CONC_CHILD_D
(
  INTERNAL_INV_REF_NO        VARCHAR2(15 CHAR),
  INTERNAL_DOC_REF_NO        VARCHAR2(15 CHAR),
  ELEMENT_ID                 VARCHAR2(15 CHAR),
  ELEMENT_NAME               VARCHAR2(15 CHAR),
  OLD_INVOICED_QTY           NUMBER(25,10),
  NEW_INVOICED_QTY           NUMBER(25,10),
  OLD_INVOICED_QTY_UNIT_ID   VARCHAR2(15 CHAR),
  NEW_INVOICED_QTY_UNIT_ID   VARCHAR2(15 CHAR),
  OLD_PAYABLE_PRICE          NUMBER(25,10),
  NEW_PAYABLE_PRICE          NUMBER(25,10),
  OLD_PAYABLE_PRICE_UNIT_ID  VARCHAR2(15 CHAR),
  NEW_PAYABLE_PRICE_UNIT_ID  VARCHAR2(15 CHAR),
  OLD_PAYABLE_AMOUNT         NUMBER(25,10),
  NEW_PAYABLE_AMOUNT         NUMBER(25,10),
  OLD_PAYABLE_AMOUNT_CUR_ID  VARCHAR2(15 CHAR),
  NEW_PAYABLE_AMOUNT_CUR_ID  VARCHAR2(15 CHAR),
  OLD_FX_RATE                NUMBER(25,10),
  NEW_FX_RATE                NUMBER(25,10),
  OLD_TC_AMOUNT              NUMBER(25,10),
  NEW_TC_AMOUNT              NUMBER(25,10),
  OLD_RC_AMOUNT              NUMBER(25,10),
  NEW_RC_AMOUNT              NUMBER(25,10),
  OLD_PENALTY_AMOUNT         NUMBER(25,10),
  NEW_PENALTY_AMOUNT         NUMBER(25,10),
  STOCK_REF_NO               VARCHAR2(50),
  AMOUNT_UNIT                VARCHAR2(15 CHAR),
  LOT_REF_NO                 VARCHAR2(50)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


