CREATE TABLE IVD_INVOICE_VAT_DETAILS
(
  INTERNAL_INVOICE_REF_NO  VARCHAR2(30 BYTE),
  IS_SEPARATE_INVOICE      CHAR(1 BYTE),
  VAT_CODE                 VARCHAR2(30 BYTE),
  DESCRIPTION              VARCHAR2(50 BYTE),
  VAT_RATE                 NUMBER(38,18),
  VAT_RATE_UNIT            VARCHAR2(15 BYTE),
  VAT_REMIT_CUR_ID         VARCHAR2(15 BYTE),
  FX_RATE_VC_IC            NUMBER(38,18),
  OUR_VAT_NO               VARCHAR2(30 BYTE),
  CP_VAT_NO                VARCHAR2(30 BYTE),
  VAT_AMOUNT_IN_VAT_CUR    NUMBER(38,18),
  VAT_AMOUNT_IN_INV_CUR    NUMBER(38,18),
  INVOICE_CUR_ID           VARCHAR2(15 BYTE),
  SPECIAL_INST             VARCHAR2(200 BYTE),
  NOTES                    VARCHAR2(200 BYTE),
  INTERNAL_COMMENTS        VARCHAR2(200 BYTE)
);

ALTER TABLE IVD_INVOICE_VAT_DETAILS ADD (
  CONSTRAINT IVD_PK
 PRIMARY KEY
 (INTERNAL_INVOICE_REF_NO, VAT_CODE));