
drop table PCAPAD_AP_ATTRIBUTE_DETAILS;
drop table PCAPQD_AP_QUALITY_DETAILS;


CREATE TABLE PQD_PENALTY_QUALITY_DETAILS
(
  PQD_ID  VARCHAR2(15 BYTE)                  NOT NULL,
  PCAPH_ID    VARCHAR2(15 BYTE)                  NOT NULL,
  PCPQ_ID    VARCHAR2(15 BYTE)                  NOT NULL,
  VERSION    NUMBER(10)                         NOT NULL,
  IS_ACTIVE  CHAR(1 BYTE)                       DEFAULT 'Y'                   NOT NULL
);


CREATE UNIQUE INDEX PK_PCAPQD ON PQD_PENALTY_QUALITY_DETAILS
(PQD_ID);

ALTER TABLE PQD_PENALTY_QUALITY_DETAILS ADD (
  CONSTRAINT PK_PCAPQD
 PRIMARY KEY
 (PQD_ID));
 
 
ALTER TABLE PQD_PENALTY_QUALITY_DETAILS ADD (
  CONSTRAINT FK_PCAPQD_PCPQ_ID 
 FOREIGN KEY (PCPQ_ID) 
 REFERENCES PCPQ_PC_PRODUCT_QUALITY
 (PCPQ_ID),
  CONSTRAINT FK_PCAPQD_PCAPH_ID 
 FOREIGN KEY (PCAPH_ID) 
 REFERENCES PCAPH_PC_ATTR_PENALTY_HEADER
 (PCAPH_ID));

CREATE TABLE PAD_PENALTY_ATTRIBUTE_DETAILS
(
  PAD_ID   VARCHAR2(15 BYTE)                 NOT NULL,
  PCAPH_ID   VARCHAR2(15 BYTE)                 NOT NULL,
  ELEMENT_ID  VARCHAR2(15 BYTE)                 NOT NULL,
  PQPA_ID     VARCHAR2(15 BYTE),
  VERSION     NUMBER(10)                        NOT NULL,
  IS_ACTIVE   CHAR(1 BYTE)                      DEFAULT 'Y'                   NOT NULL
);


CREATE UNIQUE INDEX PK_PCAPAD ON PAD_PENALTY_ATTRIBUTE_DETAILS
(PAD_ID);

ALTER TABLE PAD_PENALTY_ATTRIBUTE_DETAILS ADD (
  CONSTRAINT PK_PCAPAD
 PRIMARY KEY
 (PAD_ID));
 
 ALTER TABLE PAD_PENALTY_ATTRIBUTE_DETAILS ADD (
   CONSTRAINT FK_PCAPAD_PCAPH_ID 
 FOREIGN KEY (PCAPH_ID) 
 REFERENCES PCAPH_PC_ATTR_PENALTY_HEADER
 (PCAPH_ID));
 

 
CREATE TABLE PCTH_PC_TREATMENT_HEADER
(
  PCTH_ID                  VARCHAR2(15 BYTE)   NOT NULL,
  INTERNAL_CONTRACT_REF_NO  VARCHAR2(15 BYTE)   NOT NULL,
  RANGE_TYPE                VARCHAR2(20 BYTE)   NOT NULL,
  RANGE_UNIT_ID             VARCHAR2(15 BYTE)   NULL,
  PRICE_UNIT_ID             VARCHAR2(15 BYTE)   NULL,
  SLAB_TIER                 VARCHAR2(15 BYTE),
  VERSION                   NUMBER(10)          NOT NULL,
  IS_ACTIVE                 CHAR(1 BYTE)        DEFAULT 'Y'                   NOT NULL
);


CREATE UNIQUE INDEX PK_PCTH ON PCTH_PC_TREATMENT_HEADER
(PCTH_ID);

ALTER TABLE PCTH_PC_TREATMENT_HEADER ADD (
  CONSTRAINT PK_PCTH
 PRIMARY KEY
 (PCTH_ID));
 
 ALTER TABLE PCTH_PC_TREATMENT_HEADER ADD (
  CONSTRAINT FK_PCTH_PCM_ID 
 FOREIGN KEY (INTERNAL_CONTRACT_REF_NO) 
 REFERENCES PCM_PHYSICAL_CONTRACT_MAIN (INTERNAL_CONTRACT_REF_NO));
 

  
drop table PCETCQD_ETC_QUALITY_DETAILS;
  
CREATE TABLE TQD_TREATMENT_QUALITY_DETAILS
(
  TQD_ID  VARCHAR2(15 BYTE)                 NOT NULL,
  PCTH_ID    VARCHAR2(15 BYTE)                 NOT NULL,
  PCPQ_ID     VARCHAR2(15 BYTE)                 NOT NULL,
  VERSION     NUMBER(10)                        NOT NULL,
  IS_ACTIVE   CHAR(1 BYTE)                      DEFAULT 'Y'                   NOT NULL
);

CREATE UNIQUE INDEX PK_PCETCQD ON TQD_TREATMENT_QUALITY_DETAILS
(TQD_ID);


ALTER TABLE TQD_TREATMENT_QUALITY_DETAILS ADD (
  CONSTRAINT PK_PCETCQD
 PRIMARY KEY
 (TQD_ID));
 
  ALTER TABLE TQD_TREATMENT_QUALITY_DETAILS ADD (
  CONSTRAINT FK_TQD_ID_PCTH_ID
 FOREIGN KEY (PCTH_ID) 
 REFERENCES PCTH_PC_TREATMENT_HEADER (PCTH_ID),
  CONSTRAINT FK_TQD_ID_PCPQ_ID 
 FOREIGN KEY (PCPQ_ID) 
 REFERENCES PCPQ_PC_PRODUCT_QUALITY (PCPQ_ID));
 
  
CREATE TABLE TED_TREATMENT_ELEMENT_DETAILS
(
  TED_ID      VARCHAR2(15 BYTE)                 NOT NULL,
  PCTH_ID      VARCHAR2(15 BYTE)                 NOT NULL,
  ELEMENT_ID  VARCHAR2(15 BYTE)                 NOT NULL,
  VERSION     NUMBER(10)                        NOT NULL,
  IS_ACTIVE   CHAR(1 BYTE)                      DEFAULT 'Y'                   NOT NULL
);

CREATE UNIQUE INDEX PK_TED ON TED_TREATMENT_ELEMENT_DETAILS
(TED_ID);


ALTER TABLE TED_TREATMENT_ELEMENT_DETAILS ADD (
  CONSTRAINT PK_TED
 PRIMARY KEY
 (TED_ID));
 
 ALTER TABLE TED_TREATMENT_ELEMENT_DETAILS ADD (
 CONSTRAINT FK_TED_ID_PCTH_ID
 FOREIGN KEY (PCTH_ID) 
 REFERENCES PCTH_PC_TREATMENT_HEADER (PCTH_ID));
 
  CREATE SEQUENCE SEQ_PCTH
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  
   CREATE SEQUENCE SEQ_TED
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
   CREATE SEQUENCE SEQ_TQD
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
 
 
 
CREATE TABLE PCRH_PC_REFINING_HEADER
(
  PCRH_ID                  VARCHAR2(15 BYTE)   NOT NULL,
  INTERNAL_CONTRACT_REF_NO  VARCHAR2(15 BYTE)   NOT NULL,
  RANGE_TYPE                VARCHAR2(20 BYTE)   NOT NULL,
  RANGE_UNIT_ID             VARCHAR2(15 BYTE)   NULL,
  PRICE_UNIT_ID             VARCHAR2(15 BYTE)   NULL,
  SLAB_TIER                 VARCHAR2(15 BYTE),
  VERSION                   NUMBER(10)          NOT NULL,
  IS_ACTIVE                 CHAR(1 BYTE)        DEFAULT 'Y'                   NOT NULL
);


CREATE UNIQUE INDEX PK_PCRH ON PCRH_PC_REFINING_HEADER
(PCRH_ID);

ALTER TABLE PCRH_PC_REFINING_HEADER ADD (
  CONSTRAINT PK_PCRH
 PRIMARY KEY
 (PCRH_ID));
 
 ALTER TABLE PCRH_PC_REFINING_HEADER ADD (
  CONSTRAINT FK_PCRH_PCM_ID 
 FOREIGN KEY (INTERNAL_CONTRACT_REF_NO) 
 REFERENCES PCM_PHYSICAL_CONTRACT_MAIN (INTERNAL_CONTRACT_REF_NO));
 
  
CREATE TABLE RQD_REFINING_QUALITY_DETAILS
(
  RQD_ID  VARCHAR2(15 BYTE)                 NOT NULL,
  PCRH_ID    VARCHAR2(15 BYTE)                 NOT NULL,
  PCPQ_ID     VARCHAR2(15 BYTE)                 NOT NULL,
  VERSION     NUMBER(10)                        NOT NULL,
  IS_ACTIVE   CHAR(1 BYTE)                      DEFAULT 'Y'                   NOT NULL
);

CREATE UNIQUE INDEX PK_RQD ON RQD_REFINING_QUALITY_DETAILS
(RQD_ID);


ALTER TABLE RQD_REFINING_QUALITY_DETAILS ADD (
  CONSTRAINT PK_RQD
 PRIMARY KEY
 (RQD_ID));
 
 ALTER TABLE RQD_REFINING_QUALITY_DETAILS ADD (
  CONSTRAINT FK_RQD_PCRH_ID
 FOREIGN KEY (PCRH_ID) 
 REFERENCES PCRH_PC_REFINING_HEADER (PCRH_ID),
  CONSTRAINT FK_RQD_PCPQ_ID 
 FOREIGN KEY (PCPQ_ID) 
 REFERENCES PCPQ_PC_PRODUCT_QUALITY (PCPQ_ID));
 
  
CREATE TABLE RED_REFINING_ELEMENT_DETAILS
(
  RED_ID      VARCHAR2(15 BYTE)                 NOT NULL,
  PCRH_ID      VARCHAR2(15 BYTE)                 NOT NULL,
  ELEMENT_ID  VARCHAR2(15 BYTE)                 NOT NULL,
  VERSION     NUMBER(10)                        NOT NULL,
  IS_ACTIVE   CHAR(1 BYTE)                      DEFAULT 'Y'                   NOT NULL
);

CREATE UNIQUE INDEX PK_RED ON RED_REFINING_ELEMENT_DETAILS
(RED_ID);


ALTER TABLE RED_REFINING_ELEMENT_DETAILS ADD (
  CONSTRAINT PK_RED
 PRIMARY KEY
 (RED_ID));
 
 ALTER TABLE RED_REFINING_ELEMENT_DETAILS ADD (
  CONSTRAINT FK_RED_PCRH_ID
 FOREIGN KEY (PCRH_ID) 
 REFERENCES PCRH_PC_REFINING_HEADER (PCRH_ID));
 
  CREATE SEQUENCE SEQ_PCRH
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  
   CREATE SEQUENCE SEQ_RED
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
   CREATE SEQUENCE SEQ_RQD
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  drop sequence SEQ_PCERCQD;
  drop sequence SEQ_PCETCQD;

  
  drop table PCETC_PC_ELEM_TREATMENT_CHARGE;

CREATE TABLE PCETC_PC_ELEM_TREATMENT_CHARGE
(
  PCETC_ID                       VARCHAR2(15 BYTE) NOT NULL,
  PCTH_ID                     VARCHAR2(15 BYTE) NOT NULL,
  RANGE_MIN_OP                   VARCHAR2(2 BYTE),
  RANGE_MIN_VALUE                NUMBER(10,4),
  RANGE_MAX_OP                   VARCHAR2(2 BYTE),
  RANGE_MAX_VALUE                NUMBER(10,4),
    CHARGE_TYPE           VARCHAR2 (15 BYTE),
  POSITION                       VARCHAR2(30 BYTE),
  TREATMENT_CHARGE          NUMBER(10,4),
  TREATMENT_CHARGE_UNIT_ID  VARCHAR2(15 BYTE),
  WEIGHT_TYPE            VARCHAR2(20 BYTE),
  CHARGE_BASIS                   VARCHAR2(20 BYTE),
  ESC_DESC_VALUE                 NUMBER(10,4),
  ESC_DESC_UNIT_ID               VARCHAR2(15 BYTE) ,
  VERSION                        NUMBER(10)     NOT NULL,
  IS_ACTIVE                      CHAR(1 BYTE)   DEFAULT 'Y'                   NOT NULL
);

CREATE UNIQUE INDEX PK_PCETC ON PCETC_PC_ELEM_TREATMENT_CHARGE
(PCETC_ID);


ALTER TABLE PCETC_PC_ELEM_TREATMENT_CHARGE ADD (
  CONSTRAINT PK_PCETC
 PRIMARY KEY
 (PCETC_ID));
 
 
 ALTER TABLE PCETC_PC_ELEM_TREATMENT_CHARGE ADD (
  CONSTRAINT FK_PCETC_PCTH_ID 
 FOREIGN KEY (PCTH_ID) 
 REFERENCES PCTH_PC_TREATMENT_HEADER
 (PCTH_ID));


 drop table PCERC_PC_ELEM_REFINING_CHARGE;
 

CREATE TABLE PCERC_PC_ELEM_REFINING_CHARGE
(
  PCERC_ID                       VARCHAR2(15 BYTE) NOT NULL,
  PCRH_ID                     VARCHAR2(15 BYTE) NOT NULL,
  RANGE_MIN_OP                   VARCHAR2(2 BYTE),
  RANGE_MIN_VALUE                NUMBER(10,4),
  RANGE_MAX_OP                   VARCHAR2(2 BYTE),
  RANGE_MAX_VALUE                NUMBER(10,4),
  CHARGE_TYPE           VARCHAR2 (15 Byte),
  POSITION                       VARCHAR2(30 BYTE),
  REFINING_CHARGE          NUMBER(10,4),
  REFINING_CHARGE_UNIT_ID  VARCHAR2(15 BYTE),
  WEIGHT_TYPE            VARCHAR2(20 BYTE),
  CHARGE_BASIS                   VARCHAR2(20 BYTE),
  ESC_DESC_VALUE                 NUMBER(10,4),
  ESC_DESC_UNIT_ID               VARCHAR2(15 BYTE) ,
  VERSION                        NUMBER(10)     NOT NULL,
  IS_ACTIVE                      CHAR(1 BYTE)   DEFAULT 'Y'                   NOT NULL
);

CREATE UNIQUE INDEX PK_PCERC ON PCERC_PC_ELEM_REFINING_CHARGE
(PCERC_ID);


ALTER TABLE PCERC_PC_ELEM_REFINING_CHARGE ADD (
  CONSTRAINT PK_PCERC
 PRIMARY KEY
 (PCERC_ID));
 
 
 ALTER TABLE PCERC_PC_ELEM_REFINING_CHARGE ADD (
  CONSTRAINT FK_PCERC_PCRH_ID 
 FOREIGN KEY (PCRH_ID) 
 REFERENCES PCRH_PC_REFINING_HEADER
 (PCRH_ID));
 
 alter table PCAP_PC_ATTRIBUTE_PENALTY modify PER_INCREASE_UNIT_ID null;

alter table PCDI_PC_DELIVERY_ITEM drop constraint FK_PCDI_TOL_QTY_UNIT_ID;


CREATE TABLE ARQD_ASSAY_QUALITY_DETAILS
(
  ARQD_ID     VARCHAR2(15 BYTE)                  NOT NULL,
  PCAR_ID   VARCHAR2(15 BYTE)                  NOT NULL,
  PCPQ_ID    VARCHAR2(15 BYTE)                  NOT NULL,
  VERSION    NUMBER(10)                         NOT NULL,
  IS_ACTIVE  CHAR(1 BYTE)                       DEFAULT 'Y'                   NOT NULL
);


CREATE UNIQUE INDEX PK_ARQD ON ARQD_ASSAY_QUALITY_DETAILS
(ARQD_ID);

ALTER TABLE ARQD_ASSAY_QUALITY_DETAILS ADD (
  CONSTRAINT PK_ARQD
 PRIMARY KEY
 (ARQD_ID));
 
 ALTER TABLE ARQD_ASSAY_QUALITY_DETAILS ADD (
  CONSTRAINT FK_ARQD_PCAR_ID
 FOREIGN KEY (PCAR_ID) 
 REFERENCES PCAR_PC_ASSAYING_RULES (PCAR_ID),
  CONSTRAINT FK_ARQD_PCPQ_ID 
 FOREIGN KEY (PCPQ_ID) 
 REFERENCES PCPQ_PC_PRODUCT_QUALITY (PCPQ_ID));


alter table PCAR_PC_ASSAYING_RULES drop column  PCPQ_ID ;

alter table PCAESL_ASSAY_ELEM_SPLIT_LIMITS drop column  SPLIT_LIMIT_UNIT_ID ;

CREATE TABLE SRM_SAMPLING_RULES_MASTER
(
  SRM_ID        VARCHAR2(15 BYTE)               NOT NULL,
  RULE_NAME     VARCHAR2(50 BYTE)             NOT NULL,
  RULE_DESC     VARCHAR2(4000 BYTE)             NOT NULL,
  IS_ACTIVE     CHAR(1 BYTE)                    DEFAULT 'Y'                   NOT NULL,
  VERSION       NUMBER(10)                      NOT NULL
);


CREATE SEQUENCE SEQ_ARQD
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;