ALTER TABLE II_INVOICABLE_ITEM
 ADD (LOGISTICS_ACTION_ID  VARCHAR2(100 CHAR));

 ALTER TABLE AII_ACTION_INVOICABLE_ITEM
 ADD (LOGISTICS_ACTION_ID  VARCHAR2(100 CHAR));

 ALTER TABLE IID_INVOICABLE_ITEM_DETAILS
 ADD (LOGISTICS_ACTION_ID  VARCHAR2(100 CHAR));