ALTER TABLE IIED_INV_ITEM_ELEMENT_DETAILS
 DROP PRIMARY KEY CASCADE;

DROP INDEX IIED_PK;
 
ALTER TABLE IIED_INV_ITEM_ELEMENT_DETAILS
 ADD (
  CONSTRAINT IIED_PK
 PRIMARY KEY
 (ELEMENT_ID, INTERNAL_INVOICE_REF_NO, SUB_LOT_NO));


ALTER TABLE IPPD_INV_PRICE_PREMIUM_DETAILS
 DROP PRIMARY KEY CASCADE;

DROP INDEX IPPD_PK;
 
ALTER TABLE IPPD_INV_PRICE_PREMIUM_DETAILS
 ADD (
  CONSTRAINT IPPD_PK
 PRIMARY KEY
 (ELEMENT_ID, INTERNAL_INVOICE_REF_NO, SUB_LOT_NO));