alter table POFH_PRICE_OPT_FIXATION_HEADER add INTERNAL_ACTION_REF_NO VARCHAR2 (15 Char);


CREATE TABLE POFHL_PRICE_OPT_FIXAT_HEAD_LOG
(
  POFH_ID                     VARCHAR2(15 CHAR),
  POCD_ID                     VARCHAR2(15 CHAR),
  INTERNAL_GMR_REF_NO         VARCHAR2(15 CHAR),
  ENTRY_TYPE                 VARCHAR2(30 CHAR)    NOT NULL,
  QP_START_DATE               DATE,
  QP_END_DATE                 DATE,
  QTY_TO_BE_FIXED_DELTA       NUMBER(25,10),
  PRICED_QTY_DELTA            NUMBER(25,10),
  NO_OF_PROMPT_DAYS_DELTA           NUMBER(25,10),
  PER_DAY_PRICING_QTY_DELTA   NUMBER(25,10),
  FINAL_PRICE_DELTA            NUMBER(25,10),
  FINALIZE_DATE               DATE,
  VERSION                     NUMBER(10),
  IS_ACTIVE                   CHAR(1 CHAR),
  AVG_PRI_IN_PRI_IN_CUR_DELTA   NUMBER(25,10),
  AVG_FX_DELTA                      NUMBER(25,10),
  NO_OF_PROMPT_DAYS_FIXED     NUMBER(25,10)     ,
  EVENT_NAME                  VARCHAR2(50 CHAR),
  DELTA_PRICED_QTY_DELTA      NUMBER(25,10),
  FINAL_PRI_IN_PRIC_CUR_DELTA  NUMBER(25,10),
  INTERNAL_ACTION_REF_NO      VARCHAR2(15 CHAR)
);