ALTER TABLE PQCA_PQ_CHEMICAL_ATTRIBUTES
MODIFY(IS_RETURNABLE CHAR(1 CHAR));


ALTER TABLE POCH_PRICE_OPT_CALL_OFF_HEADER
MODIFY(IS_FREE_METAL_PRICING CHAR(1 CHAR));


ALTER TABLE PCBPH_PC_BASE_PRICE_HEADER
MODIFY(IS_FREE_METAL_APPLICABLE CHAR(1 CHAR));


ALTER TABLE PCM_PHYSICAL_CONTRACT_MAIN
MODIFY(IS_LOT_LEVEL_INVOICE CHAR(1 CHAR));
