CREATE TABLE WSISM_WS_INPUT_STOCK_MAPPING
(
  ASH_ID                    VARCHAR2(15),
  INTERNAL_GRD_DGRD_REF_NO  VARCHAR2(15),
  IS_ACTIVE                 CHAR(1),
  CONSTRAINT PK_WSISM PRIMARY KEY(ASH_ID,INTERNAL_GRD_DGRD_REF_NO),
  CONSTRAINT FK_WSISM_ASH_ID FOREIGN KEY (ASH_ID) REFERENCES ASH_ASSAY_HEADER (ASH_ID)
);
