ALTER TABLE CGAR_CORPORATE_GMR_ACTION_RULE MODIFY(CORPORATE_ID  NOT NULL);
ALTER TABLE CGAR_CORPORATE_GMR_ACTION_RULE MODIFY(PARENT_ACTION_ID  NOT NULL);
ALTER TABLE CGAR_CORPORATE_GMR_ACTION_RULE MODIFY(ACTION_ID  NOT NULL);
ALTER TABLE CGAR_CORPORATE_GMR_ACTION_RULE ADD CONSTRAINT CGAR_CORPORATE_GMR_ACTION_R_PK PRIMARY KEY (CORPORATE_ID, PARENT_ACTION_ID, ACTION_ID);