ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD
(
IS_APPLY_FREIGHT_ALLOWANCE   CHAR(1)    DEFAULT 'N',
CONSTRAINT CHK_GMR_IS_APPLY_FA CHECK ( IS_APPLY_FREIGHT_ALLOWANCE IN ('Y', 'N'))
);

ALTER TABLE GMRUL_GMR_UL ADD
(
IS_APPLY_FREIGHT_ALLOWANCE   CHAR(1)    DEFAULT 'N'
);

ALTER TABLE GMR_GOODS_MOVEMENT_RECORD drop CONSTRAINT CHK_AGMR_TOLLING_GMR_TYPE;

ALTER TABLE AGMR_ACTION_GMR
add CONSTRAINT CHK_AGMR_TOLLING_GMR_TYPE
   CHECK (TOLLING_GMR_TYPE IN ('Mark For Tolling','Received Materials','Output Process','Process Activity','Input Process'));