ALTER TABLE IS_DC_CONC_CHILD_D
RENAME COLUMN OLD_INVOICED_QTY_UNIT_ID TO OLD_INVOICED_QTY_UNIT;

ALTER TABLE IS_DC_CONC_CHILD_D
RENAME COLUMN NEW_INVOICED_QTY_UNIT_ID TO NEW_INVOICED_QTY_UNIT;

ALTER TABLE IS_DC_CONC_CHILD_D
RENAME COLUMN OLD_PAYABLE_PRICE_UNIT_ID TO OLD_PAYABLE_PRICE_UNIT;

ALTER TABLE IS_DC_CONC_CHILD_D
RENAME COLUMN NEW_PAYABLE_PRICE_UNIT_ID TO NEW_PAYABLE_PRICE_UNIT;

ALTER TABLE IS_DC_CONC_CHILD_D
RENAME COLUMN OLD_PAYABLE_AMOUNT_CUR_ID TO OLD_PAYABLE_AMOUNT_CUR;

ALTER TABLE IS_DC_CONC_CHILD_D
RENAME COLUMN NEW_PAYABLE_AMOUNT_CUR_ID TO NEW_PAYABLE_AMOUNT_CUR;


ALTER TABLE IS_DC_CONC_CHILD_D
 ADD (OLD_DRY_QTY  NUMBER(25,10));

ALTER TABLE IS_DC_CONC_CHILD_D
 ADD (NEW_DRY_QTY  NUMBER(25,10));

ALTER TABLE IS_DC_CONC_CHILD_D
 ADD (DRY_QTY_UNIT  VARCHAR2(30 CHAR));

ALTER TABLE IS_DC_CONC_CHILD_D
 ADD (ASSAY_DETAILS  VARCHAR2(300 CHAR));

ALTER TABLE IS_DC_CONC_CHILD_D
 ADD (PAYABLE_PERCENT  NUMBER(25,10));

ALTER TABLE IS_DC_CONC_CHILD_D
 ADD (TC_AMOUNT  NUMBER(25,10));

ALTER TABLE IS_DC_CONC_CHILD_D
 ADD (RC_AMOUNT  NUMBER(25,10));

ALTER TABLE IS_DC_CONC_CHILD_D
 ADD (PENALTY_CHARGE  NUMBER(25,10));

ALTER TABLE IS_DC_CONC_CHILD_D
 ADD (TC_AMOUNT_UNIT  VARCHAR2(30 CHAR));

ALTER TABLE IS_DC_CONC_CHILD_D
 ADD (RC_AMOUNT_UNIT  VARCHAR2(30 CHAR));

ALTER TABLE IS_DC_CONC_CHILD_D
 ADD (PENALTY_CHARGE_UNIT  VARCHAR2(30 CHAR));

ALTER TABLE IS_DC_CONC_CHILD_D
 ADD (TC_ESC_DES  VARCHAR2(300 CHAR));

ALTER TABLE IS_DC_CONC_CHILD_D
 ADD (RC_ESC_DES  VARCHAR2(300 CHAR));
 
 
 
ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(INTERNAL_INV_REF_NO VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(INTERNAL_DOC_REF_NO VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(ELEMENT_ID VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(ELEMENT_NAME VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(OLD_INVOICED_QTY VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(NEW_INVOICED_QTY VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(OLD_INVOICED_QTY_UNIT VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(NEW_INVOICED_QTY_UNIT VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(OLD_PAYABLE_PRICE VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(NEW_PAYABLE_PRICE VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(OLD_PAYABLE_PRICE_UNIT VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(NEW_PAYABLE_PRICE_UNIT VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(OLD_PAYABLE_AMOUNT VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(NEW_PAYABLE_AMOUNT VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(OLD_PAYABLE_AMOUNT_CUR VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(NEW_PAYABLE_AMOUNT_CUR VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(OLD_FX_RATE VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(NEW_FX_RATE VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(OLD_TC_AMOUNT VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(NEW_TC_AMOUNT VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(OLD_RC_AMOUNT VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(NEW_RC_AMOUNT VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(OLD_PENALTY_AMOUNT VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(NEW_PENALTY_AMOUNT VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(OLD_DRY_QTY VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(NEW_DRY_QTY VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(PAYABLE_PERCENT VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(TC_AMOUNT VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(RC_AMOUNT VARCHAR2(30 CHAR));


ALTER TABLE IS_DC_CONC_CHILD_D
MODIFY(PENALTY_CHARGE VARCHAR2(30 CHAR));