CREATE TABLE OCDA_OTHER_CHARGE_DELTA_AMOUNT
(
  OCDA_ID                  VARCHAR2(15),
  INTERNAL_INVOICE_REF_NO  VARCHAR2(15),
  COST_ID                  VARCHAR2(15),
  DELTA_AMOUNT             NUMBER(38,18),
  INVOICE_CUR_ID           VARCHAR2(15),
  COST_NAME                VARCHAR2(100)
);


CREATE UNIQUE INDEX OCDA_PK ON OCDA_OTHER_CHARGE_DELTA_AMOUNT
(OCDA_ID);

ALTER TABLE OCDA_OTHER_CHARGE_DELTA_AMOUNT ADD (
  CONSTRAINT OCDA_PK
 PRIMARY KEY
 (OCDA_ID));
 
ALTER TABLE OCDA_OTHER_CHARGE_DELTA_AMOUNT ADD (
  CONSTRAINT OCDA_IS_FK 
 FOREIGN KEY (INTERNAL_INVOICE_REF_NO) 
 REFERENCES IS_INVOICE_SUMMARY (INTERNAL_INVOICE_REF_NO));

CREATE SEQUENCE SEQ_OCDA
START WITH 1
MAXVALUE 1000000000000000000000000000
MINVALUE 1
NOCYCLE
CACHE 20
NOORDER;