CREATE TABLE SPSM_SALES_POOL_STOCK_MAPPING
(
  SPSM_PSR_ID                VARCHAR2(15 CHAR)      NULL,
  INTERNAL_GRD_REF_NO        VARCHAR2(15 CHAR)      NULL,
  INTERNAL_SALES_GMR_REF_NO  VARCHAR2(15 CHAR)      NULL,
  RELEASED_STOCK_QTY         NUMBER(25,4)           NULL,
  SALES_QTY_UNIT_ID          VARCHAR2(15 CHAR)      NULL,
  IS_ACTIVE                  CHAR(1 CHAR)           NULL
);