ALTER TABLE WND_WEIGHT_NOTE_DETAIL
 ADD (ACTIVITY_REF_NO  VARCHAR2(30));

ALTER TABLE WND_WEIGHT_NOTE_DETAIL
 ADD (ISSUE_DATE  DATE);

ALTER TABLE WNDUL_WEIGHT_NOTE_DETAIL_UL
 ADD (ACTIVITY_REF_NO  VARCHAR2(30));

ALTER TABLE WNDUL_WEIGHT_NOTE_DETAIL_UL
 ADD (ISSUE_DATE  DATE);

ALTER TABLE AGD_ALLOC_GROUP_DETAIL drop CONSTRAINT CHK_AGD_ALLOC_TYPE;

ALTER TABLE AGD_ALLOC_GROUP_DETAIL ADD (
CONSTRAINT CHK_AGD_ALLOC_TYPE CHECK (ALLOC_TYPE IN ('Open', 'Stock','Intransit','Transhipment','Pool'))
);

CREATE TABLE SPQ_STOCK_PAYABLE_QTY
(
  SPQ_ID                        VARCHAR2(15)  NOT NULL,
  INTERNAL_GMR_REF_NO	        VARCHAR2 (15) NOT NULL,	
  ACTION_NO                     NUMBER (2)    NOT NULL,
  STOCK_TYPE                    CHAR(1)       DEFAULT 'P' NOT NULL,
  INTERNAL_GRD_REF_NO	        VARCHAR2 (15),	
  INTERNAL_DGRD_REF_NO	        VARCHAR2 (15),					
  ELEMENT_ID                    VARCHAR2(15),
  PAYABLE_QTY                   NUMBER(25,10),
  QTY_UNIT_ID                   VARCHAR2(15),
  VERSION                       NUMBER(10),
  IS_ACTIVE                     CHAR(1)      DEFAULT 'Y'                   NOT NULL
);



ALTER TABLE SPQ_STOCK_PAYABLE_QTY ADD (
  CONSTRAINT PK_SPQ PRIMARY KEY (SPQ_ID)
);

ALTER TABLE SPQ_STOCK_PAYABLE_QTY ADD (
  CONSTRAINT FK_SPQ_INTERNAL_GMR_REF_NO FOREIGN KEY (INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO),
  CONSTRAINT FK_SPQ_INTERNAL_GRD_REF_NO FOREIGN KEY (INTERNAL_GRD_REF_NO) REFERENCES GRD_GOODS_RECORD_DETAIL (INTERNAL_GRD_REF_NO),
  CONSTRAINT FK_SPQ_INTERNAL_DGRD_REF_NO FOREIGN KEY (INTERNAL_DGRD_REF_NO) REFERENCES DGRD_DELIVERED_GRD (INTERNAL_DGRD_REF_NO),
  CONSTRAINT CHK_SPQ_STOCK_TYPE CHECK ( STOCK_TYPE IN ('P', 'S')),
  CONSTRAINT CHK_SPQ_IS_ACTIVE CHECK ( IS_ACTIVE IN ('Y', 'N'))
);


CREATE SEQUENCE SEQ_SPQ
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;