CREATE TABLE GTH_GMR_TREATMENT_HEADER
(
  GTH_ID                VARCHAR2(15)  NOT NULL,
  INTERNAL_GMR_REF_NO   VARCHAR2(15)  NOT NULL,
  PCDI_ID               VARCHAR2(15)  NOT NULL,
  PCTH_ID               VARCHAR2(15)  NOT NULL,
  VERSION               NUMBER(10)    NOT NULL,
  IS_ACTIVE             CHAR(1)       DEFAULT 'Y'  NOT NULL,
  CONSTRAINT PK_GTH PRIMARY KEY (GTH_ID),
  CONSTRAINT FK_GTH_INTERNAL_GMR_REF_NO FOREIGN KEY (INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO),
  CONSTRAINT FK_GTH_PCDI_ID FOREIGN KEY (PCDI_ID) REFERENCES PCDI_PC_DELIVERY_ITEM (PCDI_ID),
  CONSTRAINT FK_GTH_PCTH_ID FOREIGN KEY (PCTH_ID) REFERENCES PCTH_PC_TREATMENT_HEADER (PCTH_ID)
);


CREATE TABLE GRH_GMR_REFINING_HEADER
(
  GRH_ID                VARCHAR2(15) NOT NULL,
  INTERNAL_GMR_REF_NO   VARCHAR2(15) NOT NULL,
  PCDI_ID               VARCHAR2(15) NOT NULL,
  PCRH_ID               VARCHAR2(15) NOT NULL,
  VERSION               NUMBER(10)   NOT NULL,
  IS_ACTIVE             CHAR(1)      DEFAULT 'Y'    NOT NULL,
  CONSTRAINT PK_GRH PRIMARY KEY (GRH_ID),
  CONSTRAINT FK_GRH_INTERNAL_GMR_REF_NO FOREIGN KEY (INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO),
  CONSTRAINT FK_GRH_PCDI_ID FOREIGN KEY (PCDI_ID) REFERENCES PCDI_PC_DELIVERY_ITEM (PCDI_ID),
  CONSTRAINT FK_GRH_PCRH_ID FOREIGN KEY (PCRH_ID) REFERENCES PCRH_PC_REFINING_HEADER (PCRH_ID)
);



CREATE TABLE GPH_GMR_PENALTY_HEADER
(
  GPH_ID                VARCHAR2(15) NOT NULL,
  INTERNAL_GMR_REF_NO   VARCHAR2(15) NOT NULL,
  PCDI_ID               VARCHAR2(15) NOT NULL,
  PCAPH_ID              VARCHAR2(15) NOT NULL,
  VERSION               NUMBER(10)   NOT NULL,
  IS_ACTIVE             CHAR(1)      DEFAULT 'Y'    NOT NULL,
  CONSTRAINT PK_GPH PRIMARY KEY (GPH_ID),
  CONSTRAINT FK_GPH_INTERNAL_GMR_REF_NO FOREIGN KEY (INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO),
  CONSTRAINT FK_GPH_PCAPH_ID FOREIGN KEY (PCAPH_ID) REFERENCES PCAPH_PC_ATTR_PENALTY_HEADER (PCAPH_ID),
  CONSTRAINT FK_GPH_PCDI_ID FOREIGN KEY (PCDI_ID) REFERENCES PCDI_PC_DELIVERY_ITEM (PCDI_ID)
);

  CREATE SEQUENCE SEQ_GTH
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

  CREATE SEQUENCE SEQ_GRH
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

  CREATE SEQUENCE SEQ_GPH
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;