ALTER TABLE AGMR_ACTION_GMR DROP CONSTRAINT CHK_AGMR_CONTRACT_TYPE;
 
ALTER TABLE AGMR_ACTION_GMR ADD (
 CONSTRAINT CHK_AGMR_CONTRACT_TYPE CHECK (CONTRACT_TYPE IN ('Purchase','Sales','B2B','Tolling'))
);

ALTER TABLE GMR_GOODS_MOVEMENT_RECORD DROP CONSTRAINT CHK_GMR_CONTRACT_TYPE;
ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD (
  CONSTRAINT CHK_GMR_CONTRACT_TYPE CHECK (CONTRACT_TYPE IN ('Purchase','Sales','B2B','Tolling'))
);

ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD
(
TOLLING_QTY NUMBER (20,5) NULL,
TOLLING_GMR_TYPE VARCHAR2(15) NULL,
CONSTRAINT CHK_GMR_TOLLING_GMR_TYPE CHECK (TOLLING_GMR_TYPE IN ('Input Process','Output Process'))
);
COMMENT ON COLUMN GMR_GOODS_MOVEMENT_RECORD.TOLLING_QTY IS 'This column will contain tolling qty if this gmr stock have been considered for tolling';
COMMENT ON COLUMN GMR_GOODS_MOVEMENT_RECORD.TOLLING_GMR_TYPE IS 'This column will contain InputProcess And OutputProcess Vales as tolling type GMR';

ALTER TABLE GMRUL_GMR_UL ADD
(
TOLLING_QTY VARCHAR2(20) NULL,
TOLLING_GMR_TYPE VARCHAR2(15) NULL
);

COMMENT ON COLUMN GMRUL_GMR_UL.TOLLING_QTY IS 'This column will contain tolling qty if this gmr stock have been considered for tolling';
COMMENT ON COLUMN GMRUL_GMR_UL.TOLLING_GMR_TYPE IS 'This column will contain InputProcess And OutputProcess Vales as tolling type GMR';

ALTER TABLE AGMR_ACTION_GMR ADD
(
TOLLING_QTY NUMBER (20,5) NULL,
TOLLING_GMR_TYPE VARCHAR2(15) NULL,
CONSTRAINT CHK_AGMR_TOLLING_GMR_TYPE CHECK (TOLLING_GMR_TYPE IN ('Input Process','Output Process'))
);
COMMENT ON COLUMN AGMR_ACTION_GMR.TOLLING_QTY IS 'This column will contain tolling qty if this gmr stock have been considered for tolling';
COMMENT ON COLUMN AGMR_ACTION_GMR.TOLLING_GMR_TYPE IS 'This column will contain InputProcess And OutputProcess Vales as tolling type GMR';


ALTER TABLE GRD_GOODS_RECORD_DETAIL ADD
(
IS_MARK_FOR_TOLLING CHAR(1) DEFAULT 'N',
TOLLING_QTY NUMBER (20,5) NULL,
TOLLING_STOCK_TYPE VARCHAR2(15)  DEFAULT 'None Tolling',
ELEMENT_ID VARCHAR2(15) NULL,
CONSTRAINT CHK_GRD_IS_MARK_FOR_TOLLING CHECK (IS_MARK_FOR_TOLLING IN ('Y','N')),
CONSTRAINT CHK_GRD_TOLLING_STOCK_TYPE CHECK (TOLLING_STOCK_TYPE IN ('None Tolling','Input Process','Output Process')),
CONSTRAINT FK_GRD_ELEMENT_ID FOREIGN KEY (ELEMENT_ID) REFERENCES AML_ATTRIBUTE_MASTER_LIST (ATTRIBUTE_ID) 
);
COMMENT ON COLUMN GRD_GOODS_RECORD_DETAIL.TOLLING_QTY IS 'This column will contain tolling qty if this stock have been considered for tolling';
COMMENT ON COLUMN GRD_GOODS_RECORD_DETAIL.TOLLING_STOCK_TYPE IS 'This column will contain None Tolling, Input Process and Output Process';
COMMENT ON COLUMN GRD_GOODS_RECORD_DETAIL.ELEMENT_ID IS 'This column will contain element Id only for tolling gmr';

ALTER TABLE GRDUL_GOODS_RECORD_DETAIL_UL ADD
(
IS_MARK_FOR_TOLLING CHAR(1) NULL,
TOLLING_QTY VARCHAR2 (20) NULL,
TOLLING_STOCK_TYPE VARCHAR2(15) NULL,
ELEMENT_ID VARCHAR2(15) NULL
);
COMMENT ON COLUMN GRDUL_GOODS_RECORD_DETAIL_UL.TOLLING_QTY IS 'This column will contain tolling qty if this stock have been considered for tolling';
COMMENT ON COLUMN GRDUL_GOODS_RECORD_DETAIL_UL.ELEMENT_ID IS 'This column will contain element Id only for tolling gmr';

ALTER TABLE AGRD_ACTION_GRD ADD
(
IS_MARK_FOR_TOLLING CHAR(1) DEFAULT 'N',
TOLLING_QTY NUMBER(20,5) NULL,
TOLLING_STOCK_TYPE VARCHAR2(15)  DEFAULT 'None Tolling',
ELEMENT_ID VARCHAR2(15) NULL,
CONSTRAINT CHK_AGRD_IS_MARK_FOR_TOLLING CHECK (IS_MARK_FOR_TOLLING IN ('Y','N')),
CONSTRAINT CHK_AGRD_TOLLING_STOCK_TYPE CHECK (TOLLING_STOCK_TYPE IN ('None Tolling','Input Process','Output Process')),
CONSTRAINT FK_AGRD_ELEMENT_ID FOREIGN KEY (ELEMENT_ID) REFERENCES AML_ATTRIBUTE_MASTER_LIST (ATTRIBUTE_ID) 
);
COMMENT ON COLUMN AGRD_ACTION_GRD.TOLLING_QTY IS 'This column will contain tolling qty if this stock have been considered for tolling';
COMMENT ON COLUMN AGRD_ACTION_GRD.TOLLING_STOCK_TYPE IS 'This column will contain None Tolling, Input Process and Output Process';
COMMENT ON COLUMN AGRD_ACTION_GRD.ELEMENT_ID IS 'This column will contain element Id only for tolling gmr';