
CREATE TABLE GEPD_D
(
  INTERNAL_DOC_REF_NO   VARCHAR2(30 CHAR),  
  PLEDGE_CP_NAME         VARCHAR2(100 CHAR),
  PLEDGE_PERSON_IN_CHARGE   VARCHAR2(100 CHAR),
  PLEDGE_ACTIVITY_DATE  DATE,
  PRODUCT               VARCHAR2(100 CHAR),
  QUALITY               VARCHAR2(200 CHAR),
  SUPPLIER_NAME               VARCHAR2(100 CHAR),
  CONTRACT_REF_NO       VARCHAR2(30 CHAR),  
  SUPPLIER_PERSON_IN_CHARGE   VARCHAR2(100 CHAR),
  SUPPLIER_REF_NO       VARCHAR2(100 CHAR),
  PLEDGE_GMR_REF_NO     VARCHAR2(30 CHAR),  
  ELEMENT_NAME          VARCHAR2(30 CHAR),
  CORPORATE_NAME        VARCHAR2(100 CHAR),
  OUR_PERSON_IN_CHARGE  VARCHAR2(100 CHAR),
  CORPORATE_ID          VARCHAR2(30 CHAR),
  LOGO_PATH     BLOB
);

 