alter table ASH_ASSAY_HEADER add(NO_OF_SUBLOTS NUMBER (10));
alter table ASH_ASSAY_HEADER modify(ASSAY_REF_NO VARCHAR2 (100 Char));

CREATE TABLE WNS_ASSAY_D 
(INTERNAL_CONTRACT_ITEM_REF_NO VARCHAR2(30 BYTE),
INTERNAL_DOC_REF_NO VARCHAR2(30 BYTE),
INTERNAL_GMR_REF_NO VARCHAR2(30 BYTE),
CONTRACT_TYPE       VARCHAR2(30 BYTE),
ACTIVITY_REFNO     VARCHAR2(30 BYTE),
ACTIVITY_DATE      DATE,
BUYER               VARCHAR2(50 BYTE),
SELLER            VARCHAR2(50 BYTE),
OUR_CONTRACT_REF_NO VARCHAR2(30 BYTE),
CP_CONTRACT_REF_NO VARCHAR2(30 BYTE),
GMR_REF_NO         VARCHAR2(30 BYTE),
SHIPMENT_DATE      DATE,
SHIPMENT_DETAILS VARCHAR2(30 BYTE),
WEIGHER_AND_SAMPLER  VARCHAR2(50 BYTE),
PRODUCT_AND_QUALITY VARCHAR2(50 BYTE),
WEIGHING_SAMPLING_DATE DATE,
LOT_NO      VARCHAR2(30 BYTE),
NO_OF_SUBLOTS NUMBER(25));

CREATE TABLE WNS_ASSAY_CHILD_D 
(INTERNAL_DOC_REF_NO VARCHAR2(30 BYTE),
SUBLOT_REF_NO	VARCHAR2(30 BYTE),
NET_WET_WEIGHT NUMBER(10),
DEDUCTIBLE_CONTENT NUMBER(25,10),
DEDUCTIBLE_CONTENT_UOM VARCHAR2(15 BYTE),
DEDUCTIBLE_CONTENT_WEIGHT NUMBER(10),	
NET_DRY_WEIGHT NUMBER(10),
WEIGHT_UNIT_NAME VARCHAR2(15 BYTE));


CREATE TABLE AS_ASSAY_D 
(INTERNAL_CONTRACT_ITEM_REF_NO VARCHAR2(30 BYTE),
INTERNAL_DOC_REF_NO VARCHAR2(30 BYTE),
INTERNAL_GMR_REF_NO VARCHAR2(30 BYTE),
CONTRACT_TYPE       VARCHAR2(30 BYTE),
ASSAY_REFNO     VARCHAR2(30 BYTE),
ACTIVITY_DATE      DATE,
BUYER               VARCHAR2(50 BYTE),
SELLER            VARCHAR2(50 BYTE),
OUR_CONTRACT_REF_NO VARCHAR2(30 BYTE),
CP_CONTRACT_REF_NO VARCHAR2(30 BYTE),
GMR_REF_NO         VARCHAR2(30 BYTE),
SHIPMENT_DATE      DATE,
SHIPMENT_DETAILS VARCHAR2(30 BYTE),
WEIGHING_AND_SAMPLING_REF_NO  VARCHAR2(30 BYTE),
PRODUCT_AND_QUALITY VARCHAR2(50 BYTE),
ASSAYER      VARCHAR2(30 BYTE),
ASSAY_TYPE     VARCHAR2(30 BYTE),
EXCHANGE_OF_ASSAYS VARCHAR2(30 BYTE),
LOT_NO      VARCHAR2(30 BYTE),
NO_OF_SUBLOTS NUMBER(25));

CREATE TABLE AS_ASSAY_CHILD_D 
(INTERNAL_DOC_REF_NO VARCHAR2(30 BYTE),
LOT_REF_NO    VARCHAR2(30 BYTE),
NET_WEIGHT NUMBER(10),
NET_WEIGHT_UNIT_NAME VARCHAR2(15 BYTE),
WEIGHT_TYPE VARCHAR2(30 BYTE),    
ELEMENT_NAME VARCHAR2(30 BYTE),
ASSAY_VALUE VARCHAR2(30 BYTE),
ASSAY_UOM VARCHAR2(15 BYTE));