ALTER TABLE IS_CHILD_SI_D ADD(INV_AMT_IN_INV_CUR VARCHAR2(100));

ALTER TABLE IS_CHILD_SI_D ADD(INVOICE_CURRENCY VARCHAR2(100));

ALTER TABLE IS_CHILD_SI_D ADD(INV_TO_ACCRUAL_FX_RATE VARCHAR2(100));