ALTER TABLE IIED_INV_ITEM_ELEMENT_DETAILS
 DROP PRIMARY KEY CASCADE;

DROP INDEX IIED_PK;
 
ALTER TABLE IIED_INV_ITEM_ELEMENT_DETAILS
 ADD (
  CONSTRAINT IIED_PK
 PRIMARY KEY
 (ELEMENT_ID, INTERNAL_INVOICE_REF_NO, SUB_LOT_NO));