DROP SNAPSHOT LOG ON  FMPFD_PRICE_FIXATION_DETAILS;
CREATE MATERIALIZED VIEW LOG ON  FMPFD_PRICE_FIXATION_DETAILS;
DROP SNAPSHOT LOG ON  FMPFAM_PRICE_ACTION_MAPPING;
CREATE MATERIALIZED VIEW LOG ON  FMPFAM_PRICE_ACTION_MAPPING;

