ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
 ADD (QUALITY_ID  VARCHAR2(15 CHAR));

ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
 ADD (QUALITY_NAME  VARCHAR2(100 CHAR));

ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
 ADD (RATE  NUMBER(25,10));

ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
 ADD (RATE_UNIT_ID  VARCHAR2(15 CHAR));
