DROP VIEW v_invoice_doc;

CREATE OR REPLACE FORCE VIEW v_invoice_doc (section_name,
                                            sub_section,
                                            record_no,
                                            corporate_id,
                                            corporate_name,
                                            address1,
                                            address2,
                                            city,
                                            state,
                                            country,
                                            logo_path,
                                            phone_no,
                                            fax_no,
                                            internal_doc_ref_no,
                                            due_date,
                                            sales_purchase,
                                            cp_name,
                                            cp_address,
                                            cp_city,
                                            cp_state,
                                            cp_country,
                                            cp_zip,
                                            cp_item_stock_ref_no,
                                            business_unit,
                                            self_item_stock_ref_no,
                                            inco_term_location,
                                            self_contract_item_no,
                                            contract_date,
                                            notify_party,
                                            org_name,
                                            cp_contract_ref_no,
                                            productandquality_name,
                                            contract_tolerance,
                                            contract_quantity,
                                            contract_qty_unit,
                                            provisional_invoice_no,
                                            internal_invoice_ref_no,
                                            product,
                                            quality,
                                            amount,
                                            invoice_amount_unit,
                                            payment_term,
                                            invoice_creation_date,
                                            invoice_issue_date,
                                            invoice_quantity,
                                            invoice_dry_quantity,
                                            invoice_wet_quantity,
                                            invoiced_qty_unit,
                                            moisture,
                                            invoice_type,
                                            stock_size,
                                            packing,
                                            provisional_price,
                                            origin,
                                            tarriff,
                                            final_qty,
                                            final_amount,
                                            pi_number,
                                            provisional_amount,
                                            amount_due,
                                            addditional_charges,
                                            taxes,
                                            product_type,
                                            invoice_status,
                                            pledge_gmr_ref_no,
                                            pledge_gmr_qty,
                                            pledge_stock_ref_no,
                                            pledge_stock_qty,
                                            internal_doc_ref_no0,
                                            stock_ref_no,
                                            stock_qty,
                                            gmr_ref_no,
                                            gmr_quality,
                                            gmr_quantity,
                                            price_as_per_defind_uom,
                                            item_amount_in_inv_cur,
                                            invoiced_price_unit,
                                            element_price_unit,
                                            total_quantity,
                                            gmr_qty_unit,
                                            internal_doc_ref_no1,
                                            benificiary_name_c1,
                                            bank_name_c1,
                                            account_no_c1,
                                            iban_c1,
                                            aba_rtn_c1,
                                            instruction_c1,
                                            internal_doc_ref_no2,
                                            benificiary_name_c2,
                                            bank_name_c2,
                                            account_no_c2,
                                            iban_c2,
                                            aba_rtn_c2,
                                            instruction_c2,
                                            internal_doc_ref_no3,
                                            stock_ref_no1,
                                            stock_gmr_ref_no,
                                            cp_gmr_quantity,
                                            stock_qty1,
                                            gmr_qty_unit1,
                                            payable_element_id,
                                            payable_element,
                                            analysis,
                                            analysis_unit,
                                            element_price,
                                            invoiced_price_unit1,
                                            element_price_unit1,
                                            sub_lot_no,
                                            element_inv_amount,
                                            element_invoiced_qty,
                                            element_invoiced_qty_unit,
                                            internal_doc_ref_no4,
                                            tc_element_id,
                                            element_name,
                                            tc_rc_sub_lot_no,
                                            tc_amount,
                                            tc_amount_unit,
                                            internal_doc_ref_no5,
                                            rc_element_id,
                                            element_name1,
                                            rc_amount,
                                            rc_amount_unit,
                                            internal_doc_ref_no6,
                                            pen_element_id,
                                            element_name2,
                                            pen_amount,
                                            pen_amount_unit,
                                            vat_no,
                                            cp_vat_no,
                                            vat_code,
                                            vat_rate,
                                            vat_rate_unit,
                                            vat_amount,
                                            vat_amount_cur,
                                            is_inv_draft,
                                            cost_name,
                                            charge_type,
                                            charge_amount_rate,
                                            charge_amount_rate_unit,
                                            fx_rate,
                                            charges_quantity,
                                            charges_qty_unit,
                                            charges_amount,
                                            charge_amount_unit,
                                            charges_invoice_amount,
                                            charges_invoice_cur_name,
                                            tax_code,
                                            tax_rate,
                                            tax_currency,
                                            taxes_fx_rate,
                                            applicable_on,
                                            taxes_amount,
                                            taxes_amount_unit,
                                            taxes_invoice_amount,
                                            taxes_invoice_amount_cur,
                                            is_free_metal,
                                            is_pledge,
                                            internal_comments,
                                            remarks,
                                            yield,
                                            gmr_product,
                                            child_qty_unit,
                                            iban,
                                            api_internal_doc_ref_no,
                                            api_invoice_ref_no,
                                            api_amount_adjusted,
                                            api_invoice_currency,
                                            provisional_amount_unit,
                                            is_api_pi,
                                            premium_discount
                                           )
AS
   SELECT 'Invoice' section_name, 'Invoice' sub_section, ROWNUM record_no,
          akc.corporate_id, akc.corporate_name, akc.address1, akc.address2,
          akc.city, akc.state, akc.country, akc.logo_path, akc.phone_no,
          akc.fax_no, isd.internal_doc_ref_no, isd.due_date,
          isd.sales_purchase, isd.cp_name, isd.cp_address, isd.cp_city,
          isd.cp_state, isd.cp_country, isd.cp_zip,
          isd.supplire_invoice_no cp_item_stock_ref_no, '' business_unit,
          isd.self_item_stock_ref_no, isd.inco_term_location,
          isd.contract_ref_no self_contract_item_no, isd.contract_date,
          isd.notify_party, isd.org_name, isd.cp_contract_ref_no,
          isd.productandquality_name, isd.contract_tolerance,
          isd.contract_quantity, isd.contract_qty_unit,
          isd.invoice_ref_no provisional_invoice_no,
          isd.internal_invoice_ref_no, isd.product, isd.quality,
          isd.invoice_amount amount, isd.invoice_amount_unit,
          isd.payment_term, isd.invoice_creation_date,
          NULL invoice_issue_date, isd.invoice_quantity,
          isd.invoice_dry_quantity, isd.invoice_wet_quantity,
          isd.invoiced_qty_unit, isd.moisture,
          isd.invoice_type_name invoice_type, isd.stock_size, isd.packing,
          isd.provisional_price, isd.origin, isd.tarriff, '' final_qty,
          isd.material_cost final_amount, NULL pi_number,
          NULL provisional_amount, '' amount_due, isd.addditional_charges,
          isd.taxes, isd.contract_type product_type, isd.invoice_status,
          isd.gmr_ref_no pledge_gmr_ref_no, isd.gmr_quality pledge_gmr_qty,
          isd.stock_ref_no pledge_stock_ref_no,
          isd.stock_quantity pledge_stock_qty,
          isc.internal_doc_ref_no internal_doc_ref_no0, isc.stock_ref_no,
          isc.stock_qty || '  ' || isc.invoiced_qty_unit stock_qty,
          isc.gmr_ref_no, isc.gmr_quality, isc.gmr_quantity,
          isc.price_as_per_defind_uom, isc.item_amount_in_inv_cur,
          isc.invoiced_price_unit, NULL element_price_unit,
          isc.total_price_qty total_quantity, isc.gmr_qty_unit,
          isp_c1.internal_doc_ref_no internal_doc_ref_no1,
          isp_c1.beneficiary_name benificiary_name_c1,
          isp_c1.bank_name bank_name_c1, isp_c1.account_no account_no_c1,
          isp_c1.iban iban_c1, isp_c1.aba_rtn aba_rtn_c1,
          isp_c1.instruction instruction_c1,
          isp_c2.internal_doc_ref_no internal_doc_ref_no2,
          isp_c2.beneficiary_name benificiary_name_c2,
          isp_c2.bank_name bank_name_c2, isp_c2.account_no account_no_c2,
          isp_c2.iban iban_c2, isp_c2.aba_rtn aba_rtn_c2,
          isp_c2.instruction instruction_c2,
          is_cp.internal_doc_ref_no internal_doc_ref_no3,
          is_cp.stock_ref_no stock_ref_no1, is_cp.gmr_ref_no stock_gmr_ref_no,
          is_cp.gmr_quantity cp_gmr_quantity, is_cp.stock_qty stock_qty1,
          is_cp.gmr_qty_unit gmr_qty_unit1,
          is_cp.element_id payable_element_id,
          is_cp.element_name payable_element, is_cp.assay_content analysis,
          is_cp.assay_content_unit analysis_unit,
          is_cp.invoice_price element_price,
          is_cp.invoiced_price_unit invoiced_price_unit1,
          is_cp.element_price_unit element_price_unit1, is_cp.sub_lot_no,
          is_cp.element_inv_amount, is_cp.element_invoiced_qty,
          is_cp.element_invoiced_qty_unit, NULL internal_doc_ref_no4,
          NULL tc_element_id, NULL element_name, NULL tc_rc_sub_lot_no,
          NULL tc_amount, NULL tc_amount_unit, NULL internal_doc_ref_no5,
          NULL rc_element_id, NULL element_name1, NULL rc_amount,
          NULL rc_amount_unit, NULL internal_doc_ref_no6, NULL pen_element_id,
          NULL element_name2, NULL pen_amount, NULL pen_amount_unit,
          vat.vat_no, vat.cp_vat_no, vat.vat_code, vat.vat_rate,
          vat.vat_rate_unit, vat.vat_amount,
          isd.invoice_amount_unit vat_amount_cur, isd.is_inv_draft,
          NULL cost_name, NULL charge_type, NULL charge_amount_rate,
          NULL charge_amount_rate_unit, NULL fx_rate, NULL charges_quantity,
          NULL charges_qty_unit, NULL charges_amount, NULL charge_amount_unit,
          NULL charges_invoice_amount, NULL charges_invoice_cur_name,
          NULL tax_code, NULL tax_rate, NULL tax_currency, NULL taxes_fx_rate,
          NULL applicable_on, NULL taxes_amount, NULL taxes_amount_unit,
          NULL taxes_invoice_amount, NULL taxes_invoice_amount_cur,
          isd.is_free_metal, isd.is_pledge, isd.internal_comments,
          (CASE
              WHEN isd.sales_purchase = 'P'
                 THEN isp_c1.remarks
              WHEN isd.sales_purchase = 'S'
                 THEN isp_c2.remarks
           END
          ) remarks,
          isc.yield, isc.product gmr_product,
          isc.invoiced_qty_unit child_qty_unit, isd.iban,
          NULL api_internal_doc_ref_no, NULL api_invoice_ref_no,
          NULL api_amount_adjusted, NULL api_invoice_currency,
          NULL provisional_amount_unit, 'N' is_api_pi,
          isd.total_premium_amount AS premium_discount
     FROM is_d isd,
          is_child_d isc,
          is_bdp_child_d isp_c1,
          is_bds_child_d isp_c2,
          is_conc_payable_child is_cp,
          ds_document_summary ds,
          v_ak_corporate akc,
          (SELECT vat.internal_invoice_ref_no, vat.our_vat_no vat_no,
                  vat.cp_vat_no, vat.vat_code_name vat_code, vat.vat_rate,
                  vat.vat_rate_unit, vat.vat_amount_in_inv_cur vat_amount
             FROM ivd_invoice_vat_details vat
            WHERE vat.is_separate_invoice = 'N') vat
    WHERE isd.internal_doc_ref_no = ds.internal_doc_ref_no(+)
      AND ds.corporate_id = akc.corporate_id(+)
      AND isd.internal_doc_ref_no = isc.internal_doc_ref_no(+)
      AND isd.internal_doc_ref_no = isp_c1.internal_doc_ref_no(+)
      AND isd.internal_doc_ref_no = isp_c2.internal_doc_ref_no(+)
      AND isd.internal_doc_ref_no = is_cp.internal_doc_ref_no(+)
      AND isd.internal_invoice_ref_no = vat.internal_invoice_ref_no(+)
   UNION ALL
   SELECT 'Invoice' section_name, 'Invoice' sub_section, ROWNUM record_no,
          akc.corporate_id, akc.corporate_name, akc.address1, akc.address2,
          akc.city, akc.state, akc.country, akc.logo_path, akc.phone_no,
          akc.fax_no, isd.internal_doc_ref_no, isd.due_date,
          isd.sales_purchase, isd.cp_name, isd.cp_address, isd.cp_city,
          isd.cp_state, isd.cp_country, isd.cp_zip,
          isd.supplire_invoice_no cp_item_stock_ref_no, '' business_unit,
          isd.self_item_stock_ref_no, isd.inco_term_location,
          isd.contract_ref_no self_contract_item_no, isd.contract_date,
          isd.notify_party, isd.org_name, isd.cp_contract_ref_no,
          isd.productandquality_name, isd.contract_tolerance,
          isd.contract_quantity, isd.contract_qty_unit,
          isd.invoice_ref_no provisional_invoice_no,
          isd.internal_invoice_ref_no, isd.product, isd.quality,
          isd.invoice_amount amount, isd.invoice_amount_unit,
          isd.payment_term, isd.invoice_creation_date,
          NULL invoice_issue_date, isd.invoice_quantity,
          isd.invoice_dry_quantity, isd.invoice_wet_quantity,
          isd.invoiced_qty_unit, isd.moisture,
          isd.invoice_type_name invoice_type, isd.stock_size, isd.packing,
          isd.provisional_price, isd.origin, isd.tarriff, '' final_qty,
          isd.material_cost final_amount, ispcd.invoice_ref_no pi_number,
          ispcd.invoice_amount provisional_amount, '' amount_due,
          isd.addditional_charges, isd.taxes, isd.contract_type product_type,
          isd.invoice_status, isd.gmr_ref_no pledge_gmr_ref_no,
          isd.gmr_quality pledge_gmr_qty,
          isd.stock_ref_no pledge_stock_ref_no,
          isd.stock_quantity pledge_stock_qty, NULL internal_doc_ref_no0,
          NULL stock_ref_no, NULL stock_qty, NULL gmr_ref_no,
          NULL gmr_quality, NULL gmr_quantity, NULL price_as_per_defind_uom,
          NULL item_amount_in_inv_cur, NULL invoiced_price_unit,
          NULL element_price_unit, NULL total_quantity, NULL gmr_qty_unit,
          NULL internal_doc_ref_no1, NULL benificiary_name_c1,
          NULL bank_name_c1, NULL account_no_c1, NULL iban_c1,
          NULL aba_rtn_c1, NULL instruction_c1, NULL internal_doc_ref_no2,
          NULL benificiary_name_c2, NULL bank_name_c2, NULL account_no_c2,
          NULL iban_c2, NULL aba_rtn_c2, NULL instruction_c2,
          NULL internal_doc_ref_no3, NULL stock_ref_no1,
          NULL stock_gmr_ref_no, NULL cp_gmr_quantity, NULL stock_qty1,
          NULL gmr_qty_unit1, NULL payable_element_id, NULL payable_element,
          NULL analysis, NULL analysis_unit, NULL element_price,
          NULL invoiced_price_unit1, NULL element_price_unit1,
          NULL sub_lot_no, NULL element_inv_amount, NULL element_invoiced_qty,
          NULL element_invoiced_qty_unit, NULL internal_doc_ref_no4,
          NULL tc_element_id, NULL element_name, NULL tc_rc_sub_lot_no,
          NULL tc_amount, NULL tc_amount_unit, NULL internal_doc_ref_no5,
          NULL rc_element_id, NULL element_name1, NULL rc_amount,
          NULL rc_amount_unit, NULL internal_doc_ref_no6, NULL pen_element_id,
          NULL element_name2, NULL pen_amount, NULL pen_amount_unit,
          NULL vat_no, NULL cp_vat_no, NULL vat_code, NULL vat_rate,
          NULL vat_rate_unit, NULL vat_amount,
          isd.invoice_amount_unit vat_amount_cur, isd.is_inv_draft,
          NULL cost_name, NULL charge_type, NULL charge_amount_rate,
          NULL charge_amount_rate_unit, NULL fx_rate, NULL charges_quantity,
          NULL charges_qty_unit, NULL charges_amount, NULL charge_amount_unit,
          NULL charges_invoice_amount, NULL charges_invoice_cur_name,
          NULL tax_code, NULL tax_rate, NULL tax_currency, NULL taxes_fx_rate,
          NULL applicable_on, NULL taxes_amount, NULL taxes_amount_unit,
          NULL taxes_invoice_amount, NULL taxes_invoice_amount_cur,
          isd.is_free_metal, isd.is_pledge, isd.internal_comments,
          NULL remarks, NULL yield, NULL gmr_product, NULL child_qty_unit,
          isd.iban,
          --api_d.internal_doc_ref_no api_internal_doc_ref_no,
          --api_d.api_invoice_ref_no,
          --api_d.api_amount_adjusted,
          --api_d.invoice_currency api_invoice_currency,
                   ispcd.internal_doc_ref_no api_internal_doc_ref_no,
          ispcd.invoice_ref_no api_invoice_ref_no,
          ispcd.invoice_amount api_amount_adjusted,
          ispcd.invoice_currency api_invoice_currency,
          ispcd.invoice_currency provisional_amount_unit, 'Y' is_api_pi,
          NULL premium_discount
     FROM is_d isd,
          is_parent_child_d ispcd,
          --api_details_d api_d,
          ds_document_summary ds,
          v_ak_corporate akc
    WHERE isd.internal_doc_ref_no = ds.internal_doc_ref_no(+)
      AND ds.corporate_id = akc.corporate_id(+)
      AND isd.internal_doc_ref_no = ispcd.internal_doc_ref_no(+)
--AND isd.internal_doc_ref_no = api_d.internal_doc_ref_no(+)
   UNION ALL
   SELECT 'Invoice' section_name, 'Invoice' sub_section, ROWNUM record_no,
          akc.corporate_id, akc.corporate_name, akc.address1, akc.address2,
          akc.city, akc.state, akc.country, akc.logo_path, akc.phone_no,
          akc.fax_no, isd.internal_doc_ref_no, isd.due_date,
          isd.sales_purchase, isd.cp_name, isd.cp_address, isd.cp_city,
          isd.cp_state, isd.cp_country, isd.cp_zip,
          isd.supplire_invoice_no cp_item_stock_ref_no, '' business_unit,
          isd.self_item_stock_ref_no, isd.inco_term_location,
          isd.contract_ref_no self_contract_item_no, isd.contract_date,
          isd.notify_party, isd.org_name, isd.cp_contract_ref_no,
          isd.productandquality_name, isd.contract_tolerance,
          isd.contract_quantity, isd.contract_qty_unit,
          isd.invoice_ref_no provisional_invoice_no,
          isd.internal_invoice_ref_no, isd.product, isd.quality,
          isd.invoice_amount amount, isd.invoice_amount_unit,
          isd.payment_term, isd.invoice_creation_date,
          NULL invoice_issue_date, isd.invoice_quantity,
          isd.invoice_dry_quantity, isd.invoice_wet_quantity,
          isd.invoiced_qty_unit, isd.moisture,
          isd.invoice_type_name invoice_type, isd.stock_size, isd.packing,
          isd.provisional_price, isd.origin, isd.tarriff, '' final_qty,
          isd.material_cost final_amount,
                                         --ispcd.invoice_ref_no pi_number,
                                         api_d.api_invoice_ref_no pi_number,
          --ispcd.invoice_amount provisional_amount,
          api_d.api_amount_adjusted provisional_amount, '' amount_due,
          isd.addditional_charges, isd.taxes, isd.contract_type product_type,
          isd.invoice_status, isd.gmr_ref_no pledge_gmr_ref_no,
          isd.gmr_quality pledge_gmr_qty,
          isd.stock_ref_no pledge_stock_ref_no,
          isd.stock_quantity pledge_stock_qty, NULL internal_doc_ref_no0,
          NULL stock_ref_no, NULL stock_qty, NULL gmr_ref_no,
          NULL gmr_quality, NULL gmr_quantity, NULL price_as_per_defind_uom,
          NULL item_amount_in_inv_cur, NULL invoiced_price_unit,
          NULL element_price_unit, NULL total_quantity, NULL gmr_qty_unit,
          NULL internal_doc_ref_no1, NULL benificiary_name_c1,
          NULL bank_name_c1, NULL account_no_c1, NULL iban_c1,
          NULL aba_rtn_c1, NULL instruction_c1, NULL internal_doc_ref_no2,
          NULL benificiary_name_c2, NULL bank_name_c2, NULL account_no_c2,
          NULL iban_c2, NULL aba_rtn_c2, NULL instruction_c2,
          NULL internal_doc_ref_no3, NULL stock_ref_no1,
          NULL stock_gmr_ref_no, NULL cp_gmr_quantity, NULL stock_qty1,
          NULL gmr_qty_unit1, NULL payable_element_id, NULL payable_element,
          NULL analysis, NULL analysis_unit, NULL element_price,
          NULL invoiced_price_unit1, NULL element_price_unit1,
          NULL sub_lot_no, NULL element_inv_amount, NULL element_invoiced_qty,
          NULL element_invoiced_qty_unit, NULL internal_doc_ref_no4,
          NULL tc_element_id, NULL element_name, NULL tc_rc_sub_lot_no,
          NULL tc_amount, NULL tc_amount_unit, NULL internal_doc_ref_no5,
          NULL rc_element_id, NULL element_name1, NULL rc_amount,
          NULL rc_amount_unit, NULL internal_doc_ref_no6, NULL pen_element_id,
          NULL element_name2, NULL pen_amount, NULL pen_amount_unit,
          NULL vat_no, NULL cp_vat_no, NULL vat_code, NULL vat_rate,
          NULL vat_rate_unit, NULL vat_amount,
          isd.invoice_amount_unit vat_amount_cur, isd.is_inv_draft,
          NULL cost_name, NULL charge_type, NULL charge_amount_rate,
          NULL charge_amount_rate_unit, NULL fx_rate, NULL charges_quantity,
          NULL charges_qty_unit, NULL charges_amount, NULL charge_amount_unit,
          NULL charges_invoice_amount, NULL charges_invoice_cur_name,
          NULL tax_code, NULL tax_rate, NULL tax_currency, NULL taxes_fx_rate,
          NULL applicable_on, NULL taxes_amount, NULL taxes_amount_unit,
          NULL taxes_invoice_amount, NULL taxes_invoice_amount_cur,
          isd.is_free_metal, isd.is_pledge, isd.internal_comments,
          NULL remarks, NULL yield, NULL gmr_product, NULL child_qty_unit,
          isd.iban, api_d.internal_doc_ref_no api_internal_doc_ref_no,
          api_d.api_invoice_ref_no, api_d.api_amount_adjusted,
          api_d.invoice_currency api_invoice_currency,
          --ispcd.invoice_currency provisional_amount_unit,
          api_d.invoice_currency provisional_amount_unit, 'Y' is_api_pi,
          NULL premium_discount
     FROM is_d isd,
          --is_parent_child_d ispcd,
          api_details_d api_d,
          ds_document_summary ds,
          v_ak_corporate akc
    WHERE isd.internal_doc_ref_no = ds.internal_doc_ref_no(+)
      AND ds.corporate_id = akc.corporate_id(+)
      --AND isd.internal_doc_ref_no = ispcd.internal_doc_ref_no(+)
      AND isd.internal_doc_ref_no = api_d.internal_doc_ref_no(+)
   UNION ALL
   SELECT 'Invoice' section_name, 'Treatment Charge' sub_section,
          ROWNUM record_no, akc.corporate_id, akc.corporate_name,
          akc.address1, akc.address2, akc.city, akc.state, akc.country,
          akc.logo_path, akc.phone_no, akc.fax_no, isd.internal_doc_ref_no,
          isd.due_date, isd.sales_purchase, isd.cp_name, isd.cp_address,
          isd.cp_city, isd.cp_state, isd.cp_country, isd.cp_zip,
          isd.supplire_invoice_no cp_item_stock_ref_no, '' business_unit,
          isd.self_item_stock_ref_no, isd.inco_term_location,
          isd.contract_ref_no self_contract_item_no, isd.contract_date,
          isd.notify_party, isd.org_name, isd.cp_contract_ref_no,
          isd.productandquality_name, isd.contract_tolerance,
          isd.contract_quantity, isd.contract_qty_unit,
          isd.invoice_ref_no provisional_invoice_no,
          isd.internal_invoice_ref_no, isd.product, isd.quality,
          isd.invoice_amount amount, isd.invoice_amount_unit,
          isd.payment_term, isd.invoice_creation_date,
          NULL invoice_issue_date, isd.invoice_quantity,
          isd.invoice_dry_quantity, isd.invoice_wet_quantity,
          isd.invoiced_qty_unit, isd.moisture,
          isd.invoice_type_name invoice_type, isd.stock_size, isd.packing,
          isd.provisional_price, isd.origin, isd.tarriff, '' final_qty,
          isd.material_cost final_amount, '' pi_number, '' provisional_amount,
          '' amount_due, isd.addditional_charges, isd.taxes,
          isd.contract_type product_type, isd.invoice_status,
          isd.gmr_ref_no pledge_gmr_ref_no, isd.gmr_quality pledge_gmr_qty,
          isd.stock_ref_no pledge_stock_ref_no,
          isd.stock_quantity pledge_stock_qty, NULL internal_doc_ref_no0,
          NULL stock_ref_no1, NULL stock_qty, NULL gmr_ref_no,
          NULL gmr_quality, NULL gmr_quantity, NULL price_as_per_defind_uom,
          NULL item_amount_in_inv_cur, NULL invoiced_price_unit,
          NULL element_price_unit, NULL total_quantity, NULL gmr_qty_unit,
          isp_c1.internal_doc_ref_no internal_doc_ref_no1,
          isp_c1.beneficiary_name benificiary_name_c1,
          isp_c1.bank_name bank_name_c1, isp_c1.account_no account_no_c1,
          isp_c1.iban iban_c1, isp_c1.aba_rtn aba_rtn_c1,
          isp_c1.instruction instruction_c1,
          isp_c2.internal_doc_ref_no internal_doc_ref_no2,
          isp_c2.beneficiary_name benificiary_name_c2,
          isp_c2.bank_name bank_name_c2, isp_c2.account_no account_no_c2,
          isp_c2.iban iban_c2, isp_c2.aba_rtn aba_rtn_c2,
          isp_c2.instruction instruction_c2, NULL internal_doc_ref_no3,
          NULL stock_ref_no1, NULL stock_gmr_ref_no, NULL cp_gmr_quantity,
          NULL stock_qty1, NULL gmr_qty_unit1, NULL payable_element_id,
          NULL payable_element, NULL analysis, NULL analysis_unit,
          NULL element_price, NULL invoiced_price_unit1,
          NULL element_price_unit1, NULL sub_lot_no, NULL element_inv_amount,
          NULL element_invoiced_qty, NULL element_invoiced_qty_unit,
          istc.internal_doc_ref_no internal_doc_ref_no4, istc.tc_element_id,
          istc.element_name, istc.sub_lot_no tc_rc_sub_lot_no, istc.tc_amount,
          istc.tc_amount_unit, NULL internal_doc_ref_no5, NULL rc_element_id,
          NULL element_name1, NULL rc_amount, NULL rc_amount_unit,
          NULL internal_doc_ref_no6, NULL pen_element_id, NULL element_name2,
          NULL pen_amount, NULL pen_amount_unit, vat.vat_no, vat.cp_vat_no,
          vat.vat_code, vat.vat_rate, vat.vat_rate_unit, vat.vat_amount,
          isd.invoice_amount_unit vat_amount_cur, isd.is_inv_draft,
          NULL cost_name, NULL charge_type, NULL charge_amount_rate,
          NULL charge_amount_rate_unit, NULL fx_rate, NULL charges_quantity,
          NULL charges_qty_unit, NULL charges_amount, NULL charge_amount_unit,
          NULL charges_invoice_amount, NULL charges_invoice_cur_name,
          NULL tax_code, NULL tax_rate, NULL tax_currency, NULL taxes_fx_rate,
          NULL applicable_on, NULL taxes_amount, NULL taxes_amount_unit,
          NULL taxes_invoice_amount, NULL taxes_invoice_amount_cur,
          isd.is_free_metal, isd.is_pledge, isd.internal_comments,
          (CASE
              WHEN isd.sales_purchase = 'P'
                 THEN isp_c1.remarks
              WHEN isd.sales_purchase = 'S'
                 THEN isp_c2.remarks
           END
          ) remarks,
          NULL yield, NULL gmr_product, NULL child_qty_unit, isd.iban,
          NULL api_internal_doc_ref_no, NULL api_invoice_ref_no,
          NULL api_amount_adjusted, NULL api_invoice_currency,
          NULL provisional_amount_unit, 'N' is_api_pi, NULL premium_discount
     FROM is_d isd,
          is_bdp_child_d isp_c1,
          is_bds_child_d isp_c2,
          ds_document_summary ds,
          v_ak_corporate akc,
          (SELECT istc.internal_doc_ref_no, istc.element_id tc_element_id,
                  istc.element_name,
                     istc.sub_lot_no
                  || (CASE
                         WHEN istc.assay_detail IS NULL
                            THEN ''
                         ELSE ' : ' || istc.assay_detail
                      END
                     ) sub_lot_no,
                  istc.tc_amount, istc.amount_unit tc_amount_unit
             FROM is_conc_tc_child istc) istc,
          (SELECT vat.internal_invoice_ref_no, vat.our_vat_no vat_no,
                  vat.cp_vat_no, vat.vat_code_name vat_code, vat.vat_rate,
                  vat.vat_rate_unit, vat.vat_amount_in_inv_cur vat_amount
             FROM ivd_invoice_vat_details vat
            WHERE vat.is_separate_invoice = 'N') vat
    WHERE isd.internal_doc_ref_no = ds.internal_doc_ref_no(+)
      AND ds.corporate_id = akc.corporate_id(+)
      AND isd.internal_doc_ref_no = isp_c1.internal_doc_ref_no(+)
      AND isd.internal_doc_ref_no = isp_c2.internal_doc_ref_no(+)
      AND isd.internal_doc_ref_no = istc.internal_doc_ref_no(+)
      AND isd.internal_invoice_ref_no = vat.internal_invoice_ref_no(+)
   UNION ALL
   SELECT 'Invoice' section_name, 'Refining Charge' sub_section,
          ROWNUM record_no, akc.corporate_id, akc.corporate_name,
          akc.address1, akc.address2, akc.city, akc.state, akc.country,
          akc.logo_path, akc.phone_no, akc.fax_no, isd.internal_doc_ref_no,
          isd.due_date, isd.sales_purchase, isd.cp_name, isd.cp_address,
          isd.cp_city, isd.cp_state, isd.cp_country, isd.cp_zip,
          isd.supplire_invoice_no cp_item_stock_ref_no, '' business_unit,
          isd.self_item_stock_ref_no, isd.inco_term_location,
          isd.contract_ref_no self_contract_item_no, isd.contract_date,
          isd.notify_party, isd.org_name, isd.cp_contract_ref_no,
          isd.productandquality_name, isd.contract_tolerance,
          isd.contract_quantity, isd.contract_qty_unit,
          isd.invoice_ref_no provisional_invoice_no,
          isd.internal_invoice_ref_no, isd.product, isd.quality,
          isd.invoice_amount amount, isd.invoice_amount_unit,
          isd.payment_term, isd.invoice_creation_date,
          NULL invoice_issue_date, isd.invoice_quantity,
          isd.invoice_dry_quantity, isd.invoice_wet_quantity,
          isd.invoiced_qty_unit, isd.moisture,
          isd.invoice_type_name invoice_type, isd.stock_size, isd.packing,
          isd.provisional_price, isd.origin, isd.tarriff, '' final_qty,
          isd.material_cost final_amount, '' pi_number, '' provisional_amount,
          '' amount_due, isd.addditional_charges, isd.taxes,
          isd.contract_type product_type, isd.invoice_status,
          isd.gmr_ref_no pledge_gmr_ref_no, isd.gmr_quality pledge_gmr_qty,
          isd.stock_ref_no pledge_stock_ref_no,
          isd.stock_quantity pledge_stock_qty, NULL internal_doc_ref_no0,
          NULL stock_ref_no, NULL stock_qty, NULL gmr_ref_no,
          NULL gmr_quality, NULL gmr_quantity, NULL price_as_per_defind_uom,
          NULL item_amount_in_inv_cur, NULL invoiced_price_unit,
          NULL element_price_unit, NULL total_quantity, NULL gmr_qty_unit,
          isp_c1.internal_doc_ref_no internal_doc_ref_no1,
          isp_c1.beneficiary_name benificiary_name_c1,
          isp_c1.bank_name bank_name_c1, isp_c1.account_no account_no_c1,
          isp_c1.iban iban_c1, isp_c1.aba_rtn aba_rtn_c1,
          isp_c1.instruction instruction_c1,
          isp_c2.internal_doc_ref_no internal_doc_ref_no2,
          isp_c2.beneficiary_name benificiary_name_c2,
          isp_c2.bank_name bank_name_c2, isp_c2.account_no account_no_c2,
          isp_c2.iban iban_c2, isp_c2.aba_rtn aba_rtn_c2,
          isp_c2.instruction instruction_c2, NULL internal_doc_ref_no3,
          NULL stock_ref_no1, NULL stock_gmr_ref_no, NULL cp_gmr_quantity,
          NULL stock_qty1, NULL gmr_qty_unit1, NULL payable_element_id,
          NULL payable_element, NULL analysis, NULL analysis_unit,
          NULL element_price, NULL invoiced_price_unit1,
          NULL element_price_unit1, NULL sub_lot_no, NULL element_inv_amount,
          NULL element_invoiced_qty, NULL element_invoiced_qty_unit,
          NULL internal_doc_ref_no4, NULL tc_element_id, NULL element_name,
          isrc.sub_lot_no tc_rc_sub_lot_no, NULL tc_amount,
          NULL tc_amount_unit, isrc.internal_doc_ref_no internal_doc_ref_no5,
          isrc.rc_element_id, isrc.element_name element_name1, isrc.rc_amount,
          isrc.rc_amount_unit, NULL internal_doc_ref_no6, NULL pen_element_id,
          NULL element_name2, NULL pen_amount, NULL pen_amount_unit,
          vat.vat_no, vat.cp_vat_no, vat.vat_code, vat.vat_rate,
          vat.vat_rate_unit, vat.vat_amount,
          isd.invoice_amount_unit vat_amount_cur, isd.is_inv_draft,
          NULL cost_name, NULL charge_type, NULL charge_amount_rate,
          NULL charge_amount_rate_unit, NULL fx_rate, NULL charges_quantity,
          NULL charges_qty_unit, NULL charges_amount, NULL charge_amount_unit,
          NULL charges_invoice_amount, NULL charges_invoice_cur_name,
          NULL tax_code, NULL tax_rate, NULL tax_currency, NULL taxes_fx_rate,
          NULL applicable_on, NULL taxes_amount, NULL taxes_amount_unit,
          NULL taxes_invoice_amount, NULL taxes_invoice_amount_cur,
          isd.is_free_metal, isd.is_pledge, isd.internal_comments,
          (CASE
              WHEN isd.sales_purchase = 'P'
                 THEN isp_c1.remarks
              WHEN isd.sales_purchase = 'S'
                 THEN isp_c2.remarks
           END
          ) remarks,
          NULL yield, NULL gmr_product, NULL child_qty_unit, isd.iban,
          NULL api_internal_doc_ref_no, NULL api_invoice_ref_no,
          NULL api_amount_adjusted, NULL api_invoice_currency,
          NULL provisional_amount_unit, 'N' is_api_pi, NULL premium_discount
     FROM is_d isd,
          is_bdp_child_d isp_c1,
          is_bds_child_d isp_c2,
          ds_document_summary ds,
          v_ak_corporate akc,
          (SELECT isrc.internal_doc_ref_no, isrc.element_id rc_element_id,
                  isrc.element_name,
                     isrc.sub_lot_no
                  || (CASE
                         WHEN isrc.assay_content IS NULL
                            THEN ''
                         ELSE ' : ' || isrc.assay_content
                      END
                     ) sub_lot_no,
                  isrc.rc_amount, isrc.amount_unit rc_amount_unit
             FROM is_conc_rc_child isrc) isrc,
          (SELECT vat.internal_invoice_ref_no, vat.our_vat_no vat_no,
                  vat.cp_vat_no, vat.vat_code_name vat_code, vat.vat_rate,
                  vat.vat_rate_unit, vat.vat_amount_in_inv_cur vat_amount
             FROM ivd_invoice_vat_details vat
            WHERE vat.is_separate_invoice = 'N') vat
    WHERE isd.internal_doc_ref_no = ds.internal_doc_ref_no(+)
      AND ds.corporate_id = akc.corporate_id(+)
      AND isd.internal_doc_ref_no = isp_c1.internal_doc_ref_no(+)
      AND isd.internal_doc_ref_no = isp_c2.internal_doc_ref_no(+)
      AND isd.internal_doc_ref_no = isrc.internal_doc_ref_no(+)
      AND isd.internal_invoice_ref_no = vat.internal_invoice_ref_no(+)
   UNION ALL
   SELECT 'Invoice' section_name, 'Penalty' sub_section, ROWNUM record_no,
          akc.corporate_id, akc.corporate_name, akc.address1, akc.address2,
          akc.city, akc.state, akc.country, akc.logo_path, akc.phone_no,
          akc.fax_no, isd.internal_doc_ref_no, isd.due_date,
          isd.sales_purchase, isd.cp_name, isd.cp_address, isd.cp_city,
          isd.cp_state, isd.cp_country, isd.cp_zip,
          isd.supplire_invoice_no cp_item_stock_ref_no, '' business_unit,
          isd.self_item_stock_ref_no, isd.inco_term_location,
          isd.contract_ref_no self_contract_item_no, isd.contract_date,
          isd.notify_party, isd.org_name, isd.cp_contract_ref_no,
          isd.productandquality_name, isd.contract_tolerance,
          isd.contract_quantity, isd.contract_qty_unit,
          isd.invoice_ref_no provisional_invoice_no,
          isd.internal_invoice_ref_no, isd.product, isd.quality,
          isd.invoice_amount amount, isd.invoice_amount_unit,
          isd.payment_term, isd.invoice_creation_date,
          NULL invoice_issue_date, isd.invoice_quantity,
          isd.invoice_dry_quantity, isd.invoice_wet_quantity,
          isd.invoiced_qty_unit, isd.moisture,
          isd.invoice_type_name invoice_type, isd.stock_size, isd.packing,
          isd.provisional_price, isd.origin, isd.tarriff,
          isd.material_cost final_qty, '' final_amount, '' pi_number,
          '' provisional_amount, NULL amount_due, isd.addditional_charges,
          isd.taxes, isd.contract_type product_type, isd.invoice_status,
          NULL pledge_gmr_ref_no, NULL pledge_gmr_qty,
          NULL pledge_stock_ref_no, NULL pledge_stock_qty,
          NULL internal_doc_ref_no0, NULL stock_ref_no, NULL stock_qty,
          NULL gmr_ref_no, NULL gmr_quality, NULL gmr_quantity,
          NULL price_as_per_defind_uom, NULL item_amount_in_inv_cur,
          NULL invoiced_price_unit, NULL element_price_unit,
          NULL total_quantity, NULL gmr_qty_unit,
          isp_c1.internal_doc_ref_no internal_doc_ref_no1,
          isp_c1.beneficiary_name benificiary_name_c1,
          isp_c1.bank_name bank_name_c1, isp_c1.account_no account_no_c1,
          isp_c1.iban iban_c1, isp_c1.aba_rtn aba_rtn_c1,
          isp_c1.instruction instruction_c1,
          isp_c2.internal_doc_ref_no internal_doc_ref_no2,
          isp_c2.beneficiary_name benificiary_name_c2,
          isp_c2.bank_name bank_name_c2, isp_c2.account_no account_no_c2,
          isp_c2.iban iban_c2, isp_c2.aba_rtn aba_rtn_c2,
          isp_c2.instruction instruction_c2, NULL internal_doc_ref_no3,
          NULL stock_ref_no1, NULL stock_gmr_ref_no, NULL cp_gmr_quantity,
          NULL stock_qty1, NULL gmr_qty_unit1, NULL payable_element_id,
          NULL payable_element, NULL analysis, NULL analysis_unit,
          NULL element_price, NULL invoiced_price_unit1,
          NULL element_price_unit1, NULL sub_lot_no, NULL element_inv_amount,
          NULL element_invoiced_qty, NULL element_invoiced_qty_unit,
          NULL internal_doc_ref_no4, NULL tc_element_id, NULL element_name,
          NULL tc_rc_sub_lot_no, NULL tc_amount, NULL tc_amount_unit,
          NULL internal_doc_ref_no5, NULL rc_element_id, NULL element_name1,
          NULL rc_amount, NULL rc_amount_unit,
          isp.internal_doc_ref_no internal_doc_ref_no6, isp.pen_element_id,
          isp.element_name element_name2, isp.pen_amount, isp.pen_amount_unit,
          vat.vat_no, vat.cp_vat_no, vat.vat_code, vat.vat_rate,
          vat.vat_rate_unit, vat.vat_amount,
          isd.invoice_amount_unit vat_amount_cur, isd.is_inv_draft,
          NULL cost_name, NULL charge_type, NULL charge_amount_rate,
          NULL charge_amount_rate_unit, NULL fx_rate, NULL charges_quantity,
          NULL charges_qty_unit, NULL charges_amount, NULL charge_amount_unit,
          NULL charges_invoice_amount, NULL charges_invoice_cur_name,
          NULL tax_code, NULL tax_rate, NULL tax_currency, NULL taxes_fx_rate,
          NULL applicable_on, NULL taxes_amount, NULL taxes_amount_unit,
          NULL taxes_invoice_amount, NULL taxes_invoice_amount_cur,
          isd.is_free_metal, isd.is_pledge, isd.internal_comments,
          NULL remarks, NULL yield, NULL gmr_product, NULL child_qty_unit,
          NULL iban, NULL api_internal_doc_ref_no, NULL api_invoice_ref_no,
          NULL api_amount_adjusted, NULL api_invoice_currency,
          NULL provisional_amount_unit, 'N' is_api_pi, NULL premium_discount
     FROM is_d isd,
          ds_document_summary ds,
          v_ak_corporate akc,
          is_bdp_child_d isp_c1,
          is_bds_child_d isp_c2,
          (SELECT   isp.internal_doc_ref_no, isp.element_id pen_element_id,
                    isp.element_name, SUM (isp.penalty_amount) pen_amount,
                    isp.amount_unit pen_amount_unit
               FROM is_conc_penalty_child isp
           GROUP BY isp.internal_doc_ref_no,
                    isp.element_id,
                    isp.element_name,
                    isp.amount_unit) isp,
          (SELECT vat.internal_invoice_ref_no, vat.our_vat_no vat_no,
                  vat.cp_vat_no, vat.vat_code_name vat_code, vat.vat_rate,
                  vat.vat_rate_unit, vat.vat_amount_in_inv_cur vat_amount
             FROM ivd_invoice_vat_details vat
            WHERE vat.is_separate_invoice = 'N') vat
    WHERE isd.internal_doc_ref_no = ds.internal_doc_ref_no(+)
      AND ds.corporate_id = akc.corporate_id(+)
      AND isd.internal_doc_ref_no = isp_c1.internal_doc_ref_no(+)
      AND isd.internal_doc_ref_no = isp_c2.internal_doc_ref_no(+)
      AND isd.internal_doc_ref_no = isp.internal_doc_ref_no(+)
      AND isd.internal_invoice_ref_no = vat.internal_invoice_ref_no(+)
   UNION ALL
   SELECT 'Other Charges' section_name, 'Other Charges' sub_section,
          ROWNUM record_no, akc.corporate_id, akc.corporate_name,
          akc.address1, akc.address2, akc.city, akc.state, akc.country,
          akc.logo_path, akc.phone_no, akc.fax_no, isd.internal_doc_ref_no,
          isd.due_date, isd.sales_purchase, isd.cp_name, isd.cp_address,
          isd.cp_city, isd.cp_state, isd.cp_country, isd.cp_zip,
          isd.supplire_invoice_no cp_item_stock_ref_no, '' business_unit,
          isd.self_item_stock_ref_no, isd.inco_term_location,
          isd.contract_ref_no self_contract_item_no, isd.contract_date,
          isd.notify_party, isd.org_name, isd.cp_contract_ref_no,
          isd.productandquality_name, isd.contract_tolerance,
          isd.contract_quantity, isd.contract_qty_unit,
          isd.invoice_ref_no provisional_invoice_no,
          isd.internal_invoice_ref_no, isd.product, isd.quality,
          isd.invoice_amount amount, isd.invoice_amount_unit,
          isd.payment_term, isd.invoice_creation_date,
          NULL invoice_issue_date, isd.invoice_quantity,
          isd.invoice_dry_quantity, isd.invoice_wet_quantity,
          isd.invoiced_qty_unit, isd.moisture,
          isd.invoice_type_name invoice_type, isd.stock_size, isd.packing,
          isd.provisional_price, isd.origin, isd.tarriff, '' final_qty,
          isd.material_cost final_amount, '' pi_number, '' provisional_amount,
          '' amount_due, isd.addditional_charges, isd.taxes,
          isd.contract_type product_type, isd.invoice_status,
          NULL pledge_gmr_ref_no, NULL pledge_gmr_qty,
          NULL pledge_stock_ref_no, NULL pledge_stock_qty,
          NULL internal_doc_ref_no0, NULL stock_ref_no, NULL stock_qty,
          NULL gmr_ref_no, NULL gmr_quality, NULL gmr_quantity,
          NULL price_as_per_defind_uom, NULL item_amount_in_inv_cur,
          NULL invoiced_price_unit, NULL element_price_unit,
          NULL total_quantity, NULL gmr_qty_unit, NULL internal_doc_ref_no1,
          NULL benificiary_name_c1, NULL bank_name_c1, NULL account_no_c1,
          NULL iban_c1, NULL aba_rtn_c1, NULL instruction_c1,
          NULL internal_doc_ref_no2, NULL benificiary_name_c2,
          NULL bank_name_c2, NULL account_no_c2, NULL iban_c2,
          NULL aba_rtn_c2, NULL instruction_c2, NULL internal_doc_ref_no3,
          NULL stock_ref_no1, NULL stock_gmr_ref_no, NULL cp_gmr_quantity,
          NULL stock_qty1, NULL gmr_qty_unit1, NULL payable_element_id,
          NULL payable_element, NULL analysis, NULL analysis_unit,
          NULL element_price, NULL invoiced_price_unit1,
          NULL element_price_unit1, NULL sub_lot_no, NULL element_inv_amount,
          NULL element_invoiced_qty, NULL element_invoiced_qty_unit,
          NULL internal_doc_ref_no4, NULL tc_element_id, NULL element_name,
          NULL tc_rc_sub_lot_no, NULL tc_amount, NULL tc_amount_unit,
          NULL internal_doc_ref_no5, NULL rc_element_id, NULL element_name1,
          NULL rc_amount, NULL rc_amount_unit, NULL internal_doc_ref_no6,
          NULL pen_element_id, NULL element_name2, NULL pen_amount,
          NULL pen_amount_unit, NULL vat_no, NULL cp_vat_no, NULL vat_code,
          NULL vat_rate, NULL vat_rate_unit, NULL vat_amount,
          NULL vat_amount_cur, isd.is_inv_draft,
          ioc.other_charge_cost_name cost_name, ioc.charge_type,
          ioc.charge_amount_rate,
          ioc.rate_price_unit_name charge_amount_rate_unit, ioc.fx_rate,
          ioc.quantity charges_quantity, ioc.quantity_unit charges_qty_unit,
          ioc.amount charges_amount, ioc.amount_unit charge_amount_unit,
          ioc.invoice_amount charges_invoice_amount,
          ioc.invoice_cur_name charges_invoice_cur_name, NULL tax_code,
          NULL tax_rate, NULL tax_currency, NULL taxes_fx_rate,
          NULL applicable_on, NULL taxes_amount, NULL taxes_amount_unit,
          NULL taxes_invoice_amount, NULL taxes_invoice_amount_cur,
          isd.is_free_metal, isd.is_pledge, isd.internal_comments,
          NULL remarks, NULL yield, NULL gmr_product, NULL child_qty_unit,
          NULL iban, NULL api_internal_doc_ref_no, NULL api_invoice_ref_no,
          NULL api_amount_adjusted, NULL api_invoice_currency,
          NULL provisional_amount_unit, NULL is_api_pi, NULL premium_discount
     FROM ioc_d ioc, is_d isd, ds_document_summary ds, v_ak_corporate akc
    WHERE ioc.internal_doc_ref_no = ds.internal_doc_ref_no
      AND isd.internal_doc_ref_no = ioc.internal_doc_ref_no
      AND ds.corporate_id = akc.corporate_id(+)
   UNION ALL
   SELECT 'Other Taxes' section_name, 'Other Taxes' sub_section,
          ROWNUM record_no, akc.corporate_id, akc.corporate_name,
          akc.address1, akc.address2, akc.city, akc.state, akc.country,
          akc.logo_path, akc.phone_no, akc.fax_no, isd.internal_doc_ref_no,
          isd.due_date, isd.sales_purchase, isd.cp_name, isd.cp_address,
          isd.cp_city, isd.cp_state, isd.cp_country, isd.cp_zip,
          isd.supplire_invoice_no cp_item_stock_ref_no, '' business_unit,
          isd.self_item_stock_ref_no, isd.inco_term_location,
          isd.contract_ref_no self_contract_item_no, isd.contract_date,
          isd.notify_party, isd.org_name, isd.cp_contract_ref_no,
          isd.productandquality_name, isd.contract_tolerance,
          isd.contract_quantity, isd.contract_qty_unit,
          isd.invoice_ref_no provisional_invoice_no,
          isd.internal_invoice_ref_no, isd.product, isd.quality,
          isd.invoice_amount amount, isd.invoice_amount_unit,
          isd.payment_term, isd.invoice_creation_date,
          NULL invoice_issue_date, isd.invoice_quantity,
          isd.invoice_dry_quantity, isd.invoice_wet_quantity,
          isd.invoiced_qty_unit, isd.moisture,
          isd.invoice_type_name invoice_type, isd.stock_size, isd.packing,
          isd.provisional_price, isd.origin, isd.tarriff, '' final_qty,
          isd.material_cost final_amount, '' pi_number, '' provisional_amount,
          '' amount_due, isd.addditional_charges, isd.taxes,
          isd.contract_type product_type, isd.invoice_status,
          NULL pledge_gmr_ref_no, NULL pledge_gmr_qty,
          NULL pledge_stock_ref_no, NULL pledge_stock_qty,
          NULL internal_doc_ref_no0, NULL stock_ref_no, NULL stock_qty,
          NULL gmr_ref_no, NULL gmr_quality, NULL gmr_quantity,
          NULL price_as_per_defind_uom, NULL item_amount_in_inv_cur,
          NULL invoiced_price_unit, NULL element_price_unit,
          NULL total_quantity, NULL gmr_qty_unit, NULL internal_doc_ref_no1,
          NULL benificiary_name_c1, NULL bank_name_c1, NULL account_no_c1,
          NULL iban_c1, NULL aba_rtn_c1, NULL instruction_c1,
          NULL internal_doc_ref_no2, NULL benificiary_name_c2,
          NULL bank_name_c2, NULL account_no_c2, NULL iban_c2,
          NULL aba_rtn_c2, NULL instruction_c2, NULL internal_doc_ref_no3,
          NULL stock_ref_no1, NULL stock_gmr_ref_no, NULL cp_gmr_quantity,
          NULL stock_qty1, NULL gmr_qty_unit1, NULL payable_element_id,
          NULL payable_element, NULL analysis, NULL analysis_unit,
          NULL element_price, NULL invoiced_price_unit1,
          NULL element_price_unit1, NULL sub_lot_no, NULL element_inv_amount,
          NULL element_invoiced_qty, NULL element_invoiced_qty_unit,
          NULL internal_doc_ref_no4, NULL tc_element_id, NULL element_name,
          NULL tc_rc_sub_lot_no, NULL tc_amount, NULL tc_amount_unit,
          NULL internal_doc_ref_no5, NULL rc_element_id, NULL element_name1,
          NULL rc_amount, NULL rc_amount_unit, NULL internal_doc_ref_no6,
          NULL pen_element_id, NULL element_name2, NULL pen_amount,
          NULL pen_amount_unit, NULL vat_no, NULL cp_vat_no, NULL vat_code,
          NULL vat_rate, NULL vat_rate_unit, NULL vat_amount,
          NULL vat_amount_cur, isd.is_inv_draft, NULL cost_name,
          NULL charge_type, NULL charge_amount_rate,
          NULL charge_amount_rate_unit, NULL fx_rate, NULL charges_quantity,
          NULL charges_qty_unit, NULL charges_amount, NULL charge_amount_unit,
          NULL charges_invoice_amount, NULL charges_invoice_cur_name,
          itd.tax_code, itd.tax_rate, itd.tax_currency,
          itd.fx_rate taxes_fx_rate, '' applicable_on,
          itd.amount taxes_amount, itd.tax_currency taxes_amount_unit,
          itd.invoice_amount taxes_invoice_amount,
          itd.invoice_currency taxes_invoice_amount_cur, isd.is_free_metal,
          isd.is_pledge, isd.internal_comments, NULL remarks, NULL yield,
          NULL gmr_product, NULL child_qty_unit, NULL iban,
          NULL api_internal_doc_ref_no, NULL api_invoice_ref_no,
          NULL api_amount_adjusted, NULL api_invoice_currency,
          NULL provisional_amount_unit, NULL is_api_pi, NULL premium_discount
     FROM itd_d itd, is_d isd, ds_document_summary ds, v_ak_corporate akc
    WHERE itd.internal_doc_ref_no = ds.internal_doc_ref_no
      AND isd.internal_doc_ref_no = itd.internal_doc_ref_no
      AND ds.corporate_id = akc.corporate_id(+);