ALTER TABLE DITH_DI_TREATMENT_HEADER
MODIFY(PCDI_ID  NOT NULL);

ALTER TABLE DITH_DI_TREATMENT_HEADER
MODIFY(PCTH_ID  NOT NULL);

ALTER TABLE DITH_DI_TREATMENT_HEADER
MODIFY(VERSION  NOT NULL);

ALTER TABLE DITH_DI_TREATMENT_HEADER
MODIFY(IS_ACTIVE  NOT NULL);



ALTER TABLE DIRH_DI_REFINING_HEADER
MODIFY(PCDI_ID  NOT NULL);


ALTER TABLE DIRH_DI_REFINING_HEADER
MODIFY(PCRH_ID  NOT NULL);


ALTER TABLE DIRH_DI_REFINING_HEADER
MODIFY(VERSION  NOT NULL);


ALTER TABLE DIRH_DI_REFINING_HEADER
MODIFY(IS_ACTIVE  NOT NULL);




ALTER TABLE DIPH_DI_PENALTY_HEADER
MODIFY(PCDI_ID  NOT NULL);


ALTER TABLE DIPH_DI_PENALTY_HEADER
MODIFY(PCAPH_ID  NOT NULL);


ALTER TABLE DIPH_DI_PENALTY_HEADER
MODIFY(VERSION  NOT NULL);


ALTER TABLE DIPH_DI_PENALTY_HEADER
MODIFY(IS_ACTIVE  NOT NULL);




ALTER TABLE DIPCH_DI_PAYABLECONTENT_HEADER
MODIFY(PCDI_ID  NOT NULL);


ALTER TABLE DIPCH_DI_PAYABLECONTENT_HEADER
MODIFY(PCPCH_ID  NOT NULL);


ALTER TABLE DIPCH_DI_PAYABLECONTENT_HEADER
MODIFY(VERSION  NOT NULL);


ALTER TABLE DIPCH_DI_PAYABLECONTENT_HEADER
MODIFY(IS_ACTIVE  NOT NULL);


