ALTER TABLE PID_PAYMENT_INSTRUMENT_DETAILS
DROP CONSTRAINT FK_PID_INT_CONTR_ITEM_REF_NO;


ALTER TABLE PID_PAYMENT_INSTRUMENT_DETAILS ADD (
  CONSTRAINT FK_PIT_PAYMENT_INST_TYPE_ID 
 FOREIGN KEY (PAYMENT_INSTRUMENT_TYPE_ID) 
 REFERENCES PIT_PAYMENT_INSTRUMENT_TYPE (PAYMENT_INSTRUMENT_TYPE_ID));
 