CREATE TABLE PCMAC_PCM_ADDN_CHARGES 
    ( 
     PCMAC_ID VARCHAR2 (15 BYTE)  NOT NULL , 
     INT_CONTRACT_REF_NO VARCHAR2 (15 BYTE)  NOT NULL , 
     ADDN_CHARGE_ID VARCHAR2 (10 BYTE)  NOT NULL , 
     ADDN_CHARGE_NAME VARCHAR2 (50 BYTE)  NOT NULL , 
     CHARGE_TYPE VARCHAR2 (30 BYTE) , 
     POSITION VARCHAR2 (30 BYTE) , 
     RANGE_MIN_OP VARCHAR2 (15 BYTE) , 
     RANGE_MIN_VALUE NUMBER (25,10) , 
     RANGE_MAX_OP VARCHAR2 (15 BYTE) , 
     RANGE_MAX_VALUE NUMBER (25,10) , 
     RANGE_UNIT_ID VARCHAR2 (15 BYTE) , 
     CHARGE NUMBER (25,10)  NOT NULL , 
     CHARGE_CUR_ID VARCHAR2 (15 BYTE)  NOT NULL , 
     CHARGE_RATE_BASIS VARCHAR2 (30 BYTE) , 
     CONTAINER_SIZE VARCHAR2 (30 BYTE) , 
     FX_RATE VARCHAR2 (30 BYTE),
     IS_ACTIVE char (1 char)  NOT NULL , 
     QTY_UNIT_ID VARCHAR2 (10 BYTE) , 
     VERSION NUMBER (10)  NOT NULL 
    ) 
;




ALTER TABLE PCMAC_PCM_ADDN_CHARGES 
    ADD CONSTRAINT PCMAC_PCM_ADDN_CHARGES_PK PRIMARY KEY ( PCMAC_ID ) ;




ALTER TABLE PCMAC_PCM_ADDN_CHARGES 
    ADD CONSTRAINT FK_PCMAC_PCM_ID FOREIGN KEY 
    ( 
     INT_CONTRACT_REF_NO
    ) 
    REFERENCES PCM_PHYSICAL_CONTRACT_MAIN 
    ( 
     INTERNAL_CONTRACT_REF_NO
    ) 
;


CREATE TABLE PCMTE_PCM_TOLLING_EXT 
    ( 
     INT_TOLLING_CONT_REF_NO VARCHAR2 (15 BYTE)  NOT NULL , 
     INT_CONTRACT_REF_NO VARCHAR2 (15 BYTE)  NOT NULL , 
     AGREEMENT_NUMBER VARCHAR2 (50 BYTE) , 
     IS_PASS_THROUGH char (1 char) default 'N'  NOT NULL , 
     
     VERSION NUMBER (10)  NOT NULL 
    ) 
;



ALTER TABLE PCMTE_PCM_TOLLING_EXT 
    ADD CONSTRAINT PCMTE_PK PRIMARY KEY ( INT_TOLLING_CONT_REF_NO ) ;


CREATE TABLE PQDT_PAYABLE_EXT_TOLLING 
    ( 
     PQDT_ID VARCHAR2 (15 BYTE)  NOT NULL , 
     PQD_ID VARCHAR2 (15 BYTE)  NOT NULL , 
     RETURNABLE_PRODUCT_ID VARCHAR2 (15 BYTE)  NOT NULL , 
     RETURNABLE_QUALITY_ID VARCHAR2 (15 BYTE)  NOT NULL , 
     
     
     IS_ACTIVE char (1 char)   default 'N' NOT NULL, 
     PAYABLE_BASIS VARCHAR2 (30 BYTE) , 
     VERSION NUMBER (10)  NOT NULL 
    ) 
;



ALTER TABLE PQDT_PAYABLE_EXT_TOLLING 
    ADD CONSTRAINT PQDT_EXT_PK PRIMARY KEY ( PQDT_ID ) ;



ALTER TABLE PCMTE_PCM_TOLLING_EXT 
    ADD CONSTRAINT FK_PCMTE_INT_CONTRACT_REF_NO FOREIGN KEY 
    ( 
     INT_CONTRACT_REF_NO
    ) 
    REFERENCES PCM_PHYSICAL_CONTRACT_MAIN 
    ( 
     INTERNAL_CONTRACT_REF_NO
    ) 
;


ALTER TABLE PQDT_PAYABLE_EXT_TOLLING 
    ADD CONSTRAINT FK_PQDT_PQD_ID FOREIGN KEY 
    ( 
     PQD_ID
    ) 
    REFERENCES PQD_PAYABLE_QUALITY_DETAILS 
    ( 
     PQD_ID
    ) 
;



CREATE SEQUENCE SEQ_PCMTE
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  
  
  CREATE SEQUENCE SEQ_PQDT_EXT
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

   CREATE SEQUENCE SEQ_PCMAC
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;



  
CREATE TABLE PQCAPD_PRD_QLTY_CATTR_PAY_DTLS 
    ( 
     PQCAPD_ID VARCHAR2 (15 BYTE)  NOT NULL , 
     PQCA_ID VARCHAR2 (15 BYTE)  NOT NULL , 
     PCDI_ID VARCHAR2 (15 BYTE)   , 
     PAYABLE_RULE_ID VARCHAR2 (15 BYTE)  NOT NULL , 
     PAYABLE_PERCENTAGE number(25,10),
     IS_ACTIVE char (1 char)   default 'N' NOT NULL, 
     is_returnable char (1 char) default 'N'
     VERSION NUMBER (10)  NOT NULL 
    ) 
;



ALTER TABLE PQCAPD_PRD_QLTY_CATTR_PAY_DTLS 
    ADD CONSTRAINT PQCAPD_PK PRIMARY KEY ( PQCAPD_ID ) ;



ALTER TABLE PQCAPD_PRD_QLTY_CATTR_PAY_DTLS 
    ADD CONSTRAINT FK_PQCAPD_PQCA_ID FOREIGN KEY 
    ( 
     PQCA_ID
    ) 
    REFERENCES PQCA_PQ_CHEMICAL_ATTRIBUTES 
    ( 
     PQCA_ID
    ) 
;


ALTER TABLE PQCAPD_PRD_QLTY_CATTR_PAY_DTLS 
    ADD CONSTRAINT FK_PQCAPD_PCDI_ID FOREIGN KEY 
    ( 
     PCDI_ID
    ) 
    REFERENCES PCDI_PC_DELIVERY_ITEM 
    ( 
     PCDI_ID
    ) 
;
ALTER TABLE PQCAPD_PRD_QLTY_CATTR_PAY_DTLS 
    ADD CONSTRAINT FK_PQCAPD_PAYABLE_RULE_ID FOREIGN KEY 
    ( 
     PAYABLE_RULE_ID
    ) 
    REFERENCES PCPCH_PC_PAYBLE_CONTENT_HEADER
    ( 
     PCPCH_ID
    ) 
;


  
  
  CREATE SEQUENCE SEQ_PQCAPD
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;