CREATE TABLE IST_INVOICE_SUMMARY_TEMPLATE
(
  INTERNAL_INVOICE_REF_NO        VARCHAR2(15 CHAR) PRIMARY KEY ,
  JAVA_OBJECT             BLOB,
  IS_ACTIVE               CHAR(1 CHAR)          DEFAULT 'Y' NOT NULL
);