
drop table PCAPAD_AP_ATTRIBUTE_DETAILS;
drop table PCAPQD_AP_QUALITY_DETAILS;


CREATE TABLE PQD_PENALTY_QUALITY_DETAILS
(
  PQD_ID  VARCHAR2(15 BYTE)                  NOT NULL,
  PCAPH_ID    VARCHAR2(15 BYTE)                  NOT NULL,
  PCPQ_ID    VARCHAR2(15 BYTE)                  NOT NULL,
  VERSION    NUMBER(10)                         NOT NULL,
  IS_ACTIVE  CHAR(1 BYTE)                       DEFAULT 'Y'                   NOT NULL
);


CREATE UNIQUE INDEX PK_PCAPQD ON PQD_PENALTY_QUALITY_DETAILS
(PQD_ID);

ALTER TABLE PQD_PENALTY_QUALITY_DETAILS ADD (
  CONSTRAINT PK_PCAPQD
 PRIMARY KEY
 (PQD_ID));
 
 
ALTER TABLE PQD_PENALTY_QUALITY_DETAILS ADD (
  CONSTRAINT FK_PCAPQD_PCPQ_ID 
 FOREIGN KEY (PCPQ_ID) 
 REFERENCES PCPQ_PC_PRODUCT_QUALITY
 (PCPQ_ID),
  CONSTRAINT FK_PCAPQD_PCAPH_ID 
 FOREIGN KEY (PCAPH_ID) 
 REFERENCES PCAPH_PC_ATTR_PENALTY_HEADER
 (PCAPH_ID));

CREATE TABLE PAD_PENALTY_ATTRIBUTE_DETAILS
(
  PAD_ID   VARCHAR2(15 BYTE)                 NOT NULL,
  PCAPH_ID   VARCHAR2(15 BYTE)                 NOT NULL,
  ELEMENT_ID  VARCHAR2(15 BYTE)                 NOT NULL,
  PQPA_ID     VARCHAR2(15 BYTE),
  VERSION     NUMBER(10)                        NOT NULL,
  IS_ACTIVE   CHAR(1 BYTE)                      DEFAULT 'Y'                   NOT NULL
);


CREATE UNIQUE INDEX PK_PCAPAD ON PAD_PENALTY_ATTRIBUTE_DETAILS
(PAD_ID);

ALTER TABLE PAD_PENALTY_ATTRIBUTE_DETAILS ADD (
  CONSTRAINT PK_PCAPAD
 PRIMARY KEY
 (PAD_ID));
 
 ALTER TABLE PAD_PENALTY_ATTRIBUTE_DETAILS ADD (
   CONSTRAINT FK_PCAPAD_PCAPH_ID 
 FOREIGN KEY (PCAPH_ID) 
 REFERENCES PCAPH_PC_ATTR_PENALTY_HEADER
 (PCAPH_ID));
 

 
CREATE TABLE PCTH_PC_TREATMENT_HEADER
(
  PCTH_ID                  VARCHAR2(15 BYTE)   NOT NULL,
  INTERNAL_CONTRACT_REF_NO  VARCHAR2(15 BYTE)   NOT NULL,
  RANGE_TYPE                VARCHAR2(20 BYTE)   NOT NULL,
  RANGE_UNIT_ID             VARCHAR2(15 BYTE)   NULL,
  PRICE_UNIT_ID             VARCHAR2(15 BYTE)   NULL,
  SLAB_TIER                 VARCHAR2(15 BYTE),
  VERSION                   NUMBER(10)          NOT NULL,
  IS_ACTIVE                 CHAR(1 BYTE)        DEFAULT 'Y'                   NOT NULL
);


CREATE UNIQUE INDEX PK_PCTH ON PCTH_PC_TREATMENT_HEADER
(PCTH_ID);

ALTER TABLE PCTH_PC_TREATMENT_HEADER ADD (
  CONSTRAINT PK_PCTH
 PRIMARY KEY
 (PCTH_ID));
 
 ALTER TABLE PCTH_PC_TREATMENT_HEADER ADD (
  CONSTRAINT FK_PCTH_PCM_ID 
 FOREIGN KEY (INTERNAL_CONTRACT_REF_NO) 
 REFERENCES PCM_PHYSICAL_CONTRACT_MAIN (INTERNAL_CONTRACT_REF_NO));
 

  
drop table PCETCQD_ETC_QUALITY_DETAILS;
  
CREATE TABLE TQD_TREATMENT_QUALITY_DETAILS
(
  TQD_ID  VARCHAR2(15 BYTE)                 NOT NULL,
  PCTH_ID    VARCHAR2(15 BYTE)                 NOT NULL,
  PCPQ_ID     VARCHAR2(15 BYTE)                 NOT NULL,
  VERSION     NUMBER(10)                        NOT NULL,
  IS_ACTIVE   CHAR(1 BYTE)                      DEFAULT 'Y'                   NOT NULL
);

CREATE UNIQUE INDEX PK_PCETCQD ON TQD_TREATMENT_QUALITY_DETAILS
(TQD_ID);


ALTER TABLE TQD_TREATMENT_QUALITY_DETAILS ADD (
  CONSTRAINT PK_PCETCQD
 PRIMARY KEY
 (TQD_ID));
 
  ALTER TABLE TQD_TREATMENT_QUALITY_DETAILS ADD (
  CONSTRAINT FK_TQD_ID_PCTH_ID
 FOREIGN KEY (PCTH_ID) 
 REFERENCES PCTH_PC_TREATMENT_HEADER (PCTH_ID),
  CONSTRAINT FK_TQD_ID_PCPQ_ID 
 FOREIGN KEY (PCPQ_ID) 
 REFERENCES PCPQ_PC_PRODUCT_QUALITY (PCPQ_ID));
 
  
CREATE TABLE TED_TREATMENT_ELEMENT_DETAILS
(
  TED_ID      VARCHAR2(15 BYTE)                 NOT NULL,
  PCTH_ID      VARCHAR2(15 BYTE)                 NOT NULL,
  ELEMENT_ID  VARCHAR2(15 BYTE)                 NOT NULL,
  VERSION     NUMBER(10)                        NOT NULL,
  IS_ACTIVE   CHAR(1 BYTE)                      DEFAULT 'Y'                   NOT NULL
);

CREATE UNIQUE INDEX PK_TED ON TED_TREATMENT_ELEMENT_DETAILS
(TED_ID);


ALTER TABLE TED_TREATMENT_ELEMENT_DETAILS ADD (
  CONSTRAINT PK_TED
 PRIMARY KEY
 (TED_ID));
 
 ALTER TABLE TED_TREATMENT_ELEMENT_DETAILS ADD (
 CONSTRAINT FK_TED_ID_PCTH_ID
 FOREIGN KEY (PCTH_ID) 
 REFERENCES PCTH_PC_TREATMENT_HEADER (PCTH_ID));
 
  CREATE SEQUENCE SEQ_PCTH
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  
   CREATE SEQUENCE SEQ_TED
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
   CREATE SEQUENCE SEQ_TQD
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
 
 
 
CREATE TABLE PCRH_PC_REFINING_HEADER
(
  PCRH_ID                  VARCHAR2(15 BYTE)   NOT NULL,
  INTERNAL_CONTRACT_REF_NO  VARCHAR2(15 BYTE)   NOT NULL,
  RANGE_TYPE                VARCHAR2(20 BYTE)   NOT NULL,
  RANGE_UNIT_ID             VARCHAR2(15 BYTE)   NULL,
  PRICE_UNIT_ID             VARCHAR2(15 BYTE)   NULL,
  SLAB_TIER                 VARCHAR2(15 BYTE),
  VERSION                   NUMBER(10)          NOT NULL,
  IS_ACTIVE                 CHAR(1 BYTE)        DEFAULT 'Y'                   NOT NULL
);


CREATE UNIQUE INDEX PK_PCRH ON PCRH_PC_REFINING_HEADER
(PCRH_ID);

ALTER TABLE PCRH_PC_REFINING_HEADER ADD (
  CONSTRAINT PK_PCRH
 PRIMARY KEY
 (PCRH_ID));
 
 ALTER TABLE PCRH_PC_REFINING_HEADER ADD (
  CONSTRAINT FK_PCRH_PCM_ID 
 FOREIGN KEY (INTERNAL_CONTRACT_REF_NO) 
 REFERENCES PCM_PHYSICAL_CONTRACT_MAIN (INTERNAL_CONTRACT_REF_NO));
 
  
CREATE TABLE RQD_REFINING_QUALITY_DETAILS
(
  RQD_ID  VARCHAR2(15 BYTE)                 NOT NULL,
  PCRH_ID    VARCHAR2(15 BYTE)                 NOT NULL,
  PCPQ_ID     VARCHAR2(15 BYTE)                 NOT NULL,
  VERSION     NUMBER(10)                        NOT NULL,
  IS_ACTIVE   CHAR(1 BYTE)                      DEFAULT 'Y'                   NOT NULL
);

CREATE UNIQUE INDEX PK_RQD ON RQD_REFINING_QUALITY_DETAILS
(RQD_ID);


ALTER TABLE RQD_REFINING_QUALITY_DETAILS ADD (
  CONSTRAINT PK_RQD
 PRIMARY KEY
 (RQD_ID));
 
 ALTER TABLE RQD_REFINING_QUALITY_DETAILS ADD (
  CONSTRAINT FK_RQD_PCRH_ID
 FOREIGN KEY (PCRH_ID) 
 REFERENCES PCRH_PC_REFINING_HEADER (PCRH_ID),
  CONSTRAINT FK_RQD_PCPQ_ID 
 FOREIGN KEY (PCPQ_ID) 
 REFERENCES PCPQ_PC_PRODUCT_QUALITY (PCPQ_ID));
 
  
CREATE TABLE RED_REFINING_ELEMENT_DETAILS
(
  RED_ID      VARCHAR2(15 BYTE)                 NOT NULL,
  PCRH_ID      VARCHAR2(15 BYTE)                 NOT NULL,
  ELEMENT_ID  VARCHAR2(15 BYTE)                 NOT NULL,
  VERSION     NUMBER(10)                        NOT NULL,
  IS_ACTIVE   CHAR(1 BYTE)                      DEFAULT 'Y'                   NOT NULL
);

CREATE UNIQUE INDEX PK_RED ON RED_REFINING_ELEMENT_DETAILS
(RED_ID);


ALTER TABLE RED_REFINING_ELEMENT_DETAILS ADD (
  CONSTRAINT PK_RED
 PRIMARY KEY
 (RED_ID));
 
 ALTER TABLE RED_REFINING_ELEMENT_DETAILS ADD (
  CONSTRAINT FK_RED_PCRH_ID
 FOREIGN KEY (PCRH_ID) 
 REFERENCES PCRH_PC_REFINING_HEADER (PCRH_ID));
 
  CREATE SEQUENCE SEQ_PCRH
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  
   CREATE SEQUENCE SEQ_RED
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
   CREATE SEQUENCE SEQ_RQD
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  drop sequence SEQ_PCERCQD;
  drop sequence SEQ_PCETCQD;

  
  drop table PCETC_PC_ELEM_TREATMENT_CHARGE;

CREATE TABLE PCETC_PC_ELEM_TREATMENT_CHARGE
(
  PCETC_ID                       VARCHAR2(15 BYTE) NOT NULL,
  PCTH_ID                     VARCHAR2(15 BYTE) NOT NULL,
  RANGE_MIN_OP                   VARCHAR2(2 BYTE),
  RANGE_MIN_VALUE                NUMBER(10,4),
  RANGE_MAX_OP                   VARCHAR2(2 BYTE),
  RANGE_MAX_VALUE                NUMBER(10,4),
    CHARGE_TYPE           VARCHAR2 (15 BYTE),
  POSITION                       VARCHAR2(30 BYTE),
  TREATMENT_CHARGE          NUMBER(10,4),
  TREATMENT_CHARGE_UNIT_ID  VARCHAR2(15 BYTE),
  WEIGHT_TYPE            VARCHAR2(20 BYTE),
  CHARGE_BASIS                   VARCHAR2(20 BYTE),
  ESC_DESC_VALUE                 NUMBER(10,4),
  ESC_DESC_UNIT_ID               VARCHAR2(15 BYTE) ,
  VERSION                        NUMBER(10)     NOT NULL,
  IS_ACTIVE                      CHAR(1 BYTE)   DEFAULT 'Y'                   NOT NULL
);

CREATE UNIQUE INDEX PK_PCETC ON PCETC_PC_ELEM_TREATMENT_CHARGE
(PCETC_ID);


ALTER TABLE PCETC_PC_ELEM_TREATMENT_CHARGE ADD (
  CONSTRAINT PK_PCETC
 PRIMARY KEY
 (PCETC_ID));
 
 
 ALTER TABLE PCETC_PC_ELEM_TREATMENT_CHARGE ADD (
  CONSTRAINT FK_PCETC_PCTH_ID 
 FOREIGN KEY (PCTH_ID) 
 REFERENCES PCTH_PC_TREATMENT_HEADER
 (PCTH_ID));


 drop table PCERC_PC_ELEM_REFINING_CHARGE;
 

CREATE TABLE PCERC_PC_ELEM_REFINING_CHARGE
(
  PCERC_ID                       VARCHAR2(15 BYTE) NOT NULL,
  PCRH_ID                     VARCHAR2(15 BYTE) NOT NULL,
  RANGE_MIN_OP                   VARCHAR2(2 BYTE),
  RANGE_MIN_VALUE                NUMBER(10,4),
  RANGE_MAX_OP                   VARCHAR2(2 BYTE),
  RANGE_MAX_VALUE                NUMBER(10,4),
  CHARGE_TYPE           VARCHAR2 (15 Byte),
  POSITION                       VARCHAR2(30 BYTE),
  REFINING_CHARGE          NUMBER(10,4),
  REFINING_CHARGE_UNIT_ID  VARCHAR2(15 BYTE),
  WEIGHT_TYPE            VARCHAR2(20 BYTE),
  CHARGE_BASIS                   VARCHAR2(20 BYTE),
  ESC_DESC_VALUE                 NUMBER(10,4),
  ESC_DESC_UNIT_ID               VARCHAR2(15 BYTE) ,
  VERSION                        NUMBER(10)     NOT NULL,
  IS_ACTIVE                      CHAR(1 BYTE)   DEFAULT 'Y'                   NOT NULL
);

CREATE UNIQUE INDEX PK_PCERC ON PCERC_PC_ELEM_REFINING_CHARGE
(PCERC_ID);


ALTER TABLE PCERC_PC_ELEM_REFINING_CHARGE ADD (
  CONSTRAINT PK_PCERC
 PRIMARY KEY
 (PCERC_ID));
 
 
 ALTER TABLE PCERC_PC_ELEM_REFINING_CHARGE ADD (
  CONSTRAINT FK_PCERC_PCRH_ID 
 FOREIGN KEY (PCRH_ID) 
 REFERENCES PCRH_PC_REFINING_HEADER
 (PCRH_ID));
 
 alter table PCAP_PC_ATTRIBUTE_PENALTY modify PER_INCREASE_UNIT_ID null;

alter table PCDI_PC_DELIVERY_ITEM drop constraint FK_PCDI_TOL_QTY_UNIT_ID;


CREATE TABLE ARQD_ASSAY_QUALITY_DETAILS
(
  ARQD_ID     VARCHAR2(15 BYTE)                  NOT NULL,
  PCAR_ID   VARCHAR2(15 BYTE)                  NOT NULL,
  PCPQ_ID    VARCHAR2(15 BYTE)                  NOT NULL,
  VERSION    NUMBER(10)                         NOT NULL,
  IS_ACTIVE  CHAR(1 BYTE)                       DEFAULT 'Y'                   NOT NULL
);


CREATE UNIQUE INDEX PK_ARQD ON ARQD_ASSAY_QUALITY_DETAILS
(ARQD_ID);

ALTER TABLE ARQD_ASSAY_QUALITY_DETAILS ADD (
  CONSTRAINT PK_ARQD
 PRIMARY KEY
 (ARQD_ID));
 
 ALTER TABLE ARQD_ASSAY_QUALITY_DETAILS ADD (
  CONSTRAINT FK_ARQD_PCAR_ID
 FOREIGN KEY (PCAR_ID) 
 REFERENCES PCAR_PC_ASSAYING_RULES (PCAR_ID),
  CONSTRAINT FK_ARQD_PCPQ_ID 
 FOREIGN KEY (PCPQ_ID) 
 REFERENCES PCPQ_PC_PRODUCT_QUALITY (PCPQ_ID));


alter table PCAR_PC_ASSAYING_RULES drop column  PCPQ_ID ;

alter table PCAESL_ASSAY_ELEM_SPLIT_LIMITS drop column  SPLIT_LIMIT_UNIT_ID ;

CREATE TABLE SRM_SAMPLING_RULES_MASTER
(
  SRM_ID        VARCHAR2(15 BYTE)               NOT NULL,
  RULE_NAME     VARCHAR2(50 BYTE)             NOT NULL,
  RULE_DESC     VARCHAR2(4000 BYTE)             NOT NULL,
  IS_ACTIVE     CHAR(1 BYTE)                    DEFAULT 'Y'                   NOT NULL,
  VERSION       NUMBER(10)                      NOT NULL
);


CREATE SEQUENCE SEQ_ARQD
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

  CREATE TABLE PCPCHUL_PAYBLE_CONTNT_HEADR_UL
(
  PCPCHUL_ID                VARCHAR2(15 BYTE)   NOT NULL,
  INTERNAL_ACTION_REF_NO    VARCHAR2(15 BYTE)   NOT NULL,
  ENTRY_TYPE                VARCHAR2(30 BYTE)   NOT NULL,
  PCPCH_ID                  VARCHAR2(15 BYTE)   NOT NULL,
  INTERNAL_CONTRACT_REF_NO  VARCHAR2(15 BYTE)   NOT NULL,
  RANGE_TYPE                VARCHAR2(20 BYTE),
  RANGE_UNIT_ID             VARCHAR2(15 BYTE)   NOT NULL,
  ELEMENT_ID                VARCHAR2(15 BYTE)   NOT NULL,
  SLAB_TIER                 VARCHAR2(15 BYTE),
  VERSION                   NUMBER(10)          NOT NULL,
  IS_ACTIVE                 CHAR(1 BYTE)        NOT NULL
);


CREATE UNIQUE INDEX PK_PCPCHUL ON PCPCHUL_PAYBLE_CONTNT_HEADR_UL
(PCPCHUL_ID);


ALTER TABLE PCPCHUL_PAYBLE_CONTNT_HEADR_UL ADD (
  CONSTRAINT PK_PCPCHUL
 PRIMARY KEY
 (PCPCHUL_ID));




CREATE TABLE PCEPCUL_ELEM_PAYBLE_CONTENT_UL
(
  PCEPCUL_ID               VARCHAR2(15 BYTE)    NOT NULL,
  INTERNAL_ACTION_REF_NO   VARCHAR2(15 BYTE)   NOT NULL,
  ENTRY_TYPE               VARCHAR2(30 BYTE)   NOT NULL,
  PCEPC_ID                 VARCHAR2(15 BYTE)    NOT NULL,
  RANGE_MIN_OP             VARCHAR2(2 BYTE),
  RANGE_MIN_VALUE          VARCHAR2(15 BYTE),
  RANGE_MAX_OP             VARCHAR2(2 BYTE),
  RANGE_MAX_VALUE          VARCHAR2(15 BYTE),
  PAYABLE_FORMULA_ID       VARCHAR2(15 BYTE),
  PAYABLE_CONTENT_VALUE    VARCHAR2(15 BYTE),
  PAYABLE_CONTENT_UNIT_ID  VARCHAR2(15 BYTE),
  ASSAY_DEDUCTION          VARCHAR2(15 BYTE),
  ASSAY_DEDUCTION_UNIT_ID  VARCHAR2(15 BYTE),
  INCLUDE_REF_CHARGES      CHAR(1 BYTE),
  REFINING_CHARGE_VALUE    VARCHAR2(15 BYTE),
  REFINING_CHARGE_UNIT_ID  VARCHAR2(15 BYTE),
  VERSION                  NUMBER(10)           NOT NULL,
  IS_ACTIVE                CHAR(1 BYTE)         NOT NULL,
  PCPCH_ID                 VARCHAR2(15 BYTE)    NOT NULL,
  POSITION                 VARCHAR2(30 BYTE)
);


CREATE UNIQUE INDEX PK_PCEPCUL ON PCEPCUL_ELEM_PAYBLE_CONTENT_UL
(PCEPCUL_ID);


ALTER TABLE PCEPCUL_ELEM_PAYBLE_CONTENT_UL ADD (
  CONSTRAINT PK_PCEPCUL
 PRIMARY KEY
 (PCEPCUL_ID));





CREATE TABLE PQDUL_PAYABLE_QUALITY_DTL_UL
(
  PQDUL_ID                 VARCHAR2(15 BYTE)                  NOT NULL,
  INTERNAL_ACTION_REF_NO   VARCHAR2(15 BYTE)                  NOT NULL,
  ENTRY_TYPE               VARCHAR2(30 BYTE)                  NOT NULL,
  PQD_ID                   VARCHAR2(15 BYTE)                  NOT NULL,
  PCPCH_ID                 VARCHAR2(15 BYTE)                  NOT NULL,
  PCPQ_ID                  VARCHAR2(15 BYTE)                  NOT NULL,
  VERSION                  NUMBER(10)                         NOT NULL,
  IS_ACTIVE                CHAR(1 BYTE)                       NOT NULL
);


CREATE UNIQUE INDEX PK_PQDUL ON PQDUL_PAYABLE_QUALITY_DTL_UL
(PQDUL_ID);


ALTER TABLE PQDUL_PAYABLE_QUALITY_DTL_UL ADD (
  CONSTRAINT PK_PQDUL
 PRIMARY KEY
 (PQDUL_ID));





CREATE TABLE PCAPHUL_ATTR_PENALTY_HEADER_UL
(
  PCAPHUL_ID                VARCHAR2(15 BYTE)   NOT NULL,
  INTERNAL_ACTION_REF_NO    VARCHAR2(15 BYTE)   NOT NULL,
  ENTRY_TYPE                VARCHAR2(30 BYTE)   NOT NULL,
  PCAPH_ID                  VARCHAR2(15 BYTE)   NOT NULL,
  INTERNAL_CONTRACT_REF_NO  VARCHAR2(15 BYTE)   NOT NULL,
  ATTRIBUTE_TYPE            VARCHAR2(20 BYTE),
  RANGE_UNIT_ID             VARCHAR2(15 BYTE)   NOT NULL,
  SLAB_TIER                 VARCHAR2(15 BYTE)   NOT NULL,
  VERSION                   NUMBER(10)          NOT NULL,
  IS_ACTIVE                 CHAR(1 BYTE)        NOT NULL
);


CREATE UNIQUE INDEX PK_PCAPHUL ON PCAPHUL_ATTR_PENALTY_HEADER_UL
(PCAPHUL_ID);


ALTER TABLE PCAPHUL_ATTR_PENALTY_HEADER_UL ADD (
  CONSTRAINT PK_PCAPHUL
 PRIMARY KEY
 (PCAPHUL_ID));





CREATE TABLE PCAPUL_ATTRIBUTE_PENALTY_UL
(
  PCAPUL_ID                 VARCHAR2(15 BYTE)   NOT NULL,
  INTERNAL_ACTION_REF_NO    VARCHAR2(15 BYTE)   NOT NULL,
  ENTRY_TYPE                VARCHAR2(30 BYTE)   NOT NULL,
  PCAP_ID                   VARCHAR2(15 BYTE)   NOT NULL,
  RANGE_MIN_OP              VARCHAR2(2 BYTE),
  RANGE_MIN_VALUE           VARCHAR2(15 BYTE),
  RANGE_MAX_OP              VARCHAR2(2 BYTE),
  RANGE_MAX_VALUE           VARCHAR2(15 BYTE),
  PENALTY_CHARGE_TYPE       VARCHAR2(20 BYTE),
  PENALTY_BASIS             VARCHAR2(15 BYTE),
  PENALTY_AMOUNT            VARCHAR2(15 BYTE),
  PENALTY_UNIT_ID           VARCHAR2(15 BYTE)   NOT NULL,
  PENALTY_WEIGHT_TYPE       VARCHAR2(20 BYTE),
  PER_INCREASE_VALUE        VARCHAR2(15 BYTE),
  PER_INCREASE_UNIT_ID      VARCHAR2(15 BYTE),
  DEDUCTED_PAYABLE_ELEMENT  VARCHAR2(15 BYTE),
  DEDUCTED_PAYABLE_VALUE    VARCHAR2(15 BYTE),
  DEDUCTED_PAYABLE_UNIT_ID  VARCHAR2(15 BYTE),
  CHARGE_BASIS              VARCHAR2(20 BYTE),
  VERSION                   NUMBER(10)          NOT NULL,
  IS_ACTIVE                 CHAR(1 BYTE)        DEFAULT 'Y'                   NOT NULL,
  PCAPH_ID                  VARCHAR2(15 BYTE)   NOT NULL,
  POSITION                  VARCHAR2(30 BYTE)
);

CREATE UNIQUE INDEX PK_PCAPUL ON PCAPUL_ATTRIBUTE_PENALTY_UL
(PCAPUL_ID);


ALTER TABLE PCAPUL_ATTRIBUTE_PENALTY_UL ADD (
  CONSTRAINT PK_PCAPUL
 PRIMARY KEY
 (PCAPUL_ID));




CREATE TABLE PQDUL_PENALTY_QUALITY_DTL_UL
(
  PQDUL_ID                  VARCHAR2(15 BYTE)                  NOT NULL,
  INTERNAL_ACTION_REF_NO    VARCHAR2(15 BYTE)                  NOT NULL,
  ENTRY_TYPE                VARCHAR2(30 BYTE)                  NOT NULL,
  PQD_ID                    VARCHAR2(15 BYTE)                  NOT NULL,
  PCAPH_ID                  VARCHAR2(15 BYTE)                  NOT NULL,
  PCPQ_ID                   VARCHAR2(15 BYTE)                  NOT NULL,
  VERSION                   NUMBER(10)                         NOT NULL,
  IS_ACTIVE                 CHAR(1 BYTE)                       NOT NULL
);


CREATE UNIQUE INDEX PK_PCAPQDUL ON PQDUL_PENALTY_QUALITY_DTL_UL
(PQDUL_ID);


ALTER TABLE PQDUL_PENALTY_QUALITY_DTL_UL ADD (
  CONSTRAINT PK_PCAPQDUL
 PRIMARY KEY
 (PQDUL_ID));



CREATE TABLE PADUL_PENALTY_ATTRIBUTE_DTL_UL
(
  PADUL_ID                  VARCHAR2(15 BYTE)                 NOT NULL,
  INTERNAL_ACTION_REF_NO    VARCHAR2(15 BYTE)                 NOT NULL,
  ENTRY_TYPE                VARCHAR2(30 BYTE)                 NOT NULL,
  PAD_ID                    VARCHAR2(15 BYTE)                 NOT NULL,
  PCAPH_ID                  VARCHAR2(15 BYTE)                 NOT NULL,
  ELEMENT_ID                VARCHAR2(15 BYTE)                 NOT NULL,
  PQPA_ID                   VARCHAR2(15 BYTE),
  VERSION                   NUMBER(10)                        NOT NULL,
  IS_ACTIVE                 CHAR(1 BYTE)                      NOT NULL
);


CREATE UNIQUE INDEX PK_PCAPADUL ON PADUL_PENALTY_ATTRIBUTE_DTL_UL
(PADUL_ID);


ALTER TABLE PADUL_PENALTY_ATTRIBUTE_DTL_UL ADD (
  CONSTRAINT PK_PCAPADUL
 PRIMARY KEY
 (PADUL_ID));




CREATE TABLE PCRHUL_REFINING_HEADER_UL
(
  PCRHUL_ID                 VARCHAR2(15 BYTE)   NOT NULL,
  INTERNAL_ACTION_REF_NO    VARCHAR2(15 BYTE)   NOT NULL,
  ENTRY_TYPE                VARCHAR2(30 BYTE)   NOT NULL,
  PCRH_ID                   VARCHAR2(15 BYTE)   NOT NULL,
  INTERNAL_CONTRACT_REF_NO  VARCHAR2(15 BYTE)   NOT NULL,
  RANGE_TYPE                VARCHAR2(20 BYTE)   NOT NULL,
  RANGE_UNIT_ID             VARCHAR2(15 BYTE),
  PRICE_UNIT_ID             VARCHAR2(15 BYTE),
  SLAB_TIER                 VARCHAR2(15 BYTE),
  VERSION                   NUMBER(10)          NOT NULL,
  IS_ACTIVE                 CHAR(1 BYTE)        NOT NULL
);


CREATE UNIQUE INDEX PK_PCRHUL ON PCRHUL_REFINING_HEADER_UL
(PCRHUL_ID);


ALTER TABLE PCRHUL_REFINING_HEADER_UL ADD (
  CONSTRAINT PK_PCRHUL
 PRIMARY KEY
 (PCRHUL_ID));





CREATE TABLE PCERCUL_ELEM_REFING_CHARGE_UL
(
  PCERCUL_ID               VARCHAR2(15 BYTE)    NOT NULL,
  INTERNAL_ACTION_REF_NO   VARCHAR2(15 BYTE)    NOT NULL,
  ENTRY_TYPE               VARCHAR2(30 BYTE)    NOT NULL,
  PCERC_ID                 VARCHAR2(15 BYTE)    NOT NULL,
  PCRH_ID                  VARCHAR2(15 BYTE)    NOT NULL,
  RANGE_MIN_OP             VARCHAR2(2 BYTE),
  RANGE_MIN_VALUE          VARCHAR2(15 BYTE),
  RANGE_MAX_OP             VARCHAR2(2 BYTE),
  RANGE_MAX_VALUE          VARCHAR2(15 BYTE),
  CHARGE_TYPE              VARCHAR2(15 BYTE),
  POSITION                 VARCHAR2(30 BYTE),
  REFINING_CHARGE          VARCHAR2(15 BYTE),
  REFINING_CHARGE_UNIT_ID  VARCHAR2(15 BYTE),
  WEIGHT_TYPE              VARCHAR2(20 BYTE),
  CHARGE_BASIS             VARCHAR2(20 BYTE),
  ESC_DESC_VALUE           VARCHAR2(15 BYTE),
  ESC_DESC_UNIT_ID         VARCHAR2(15 BYTE),
  VERSION                  NUMBER(10)           NOT NULL,
  IS_ACTIVE                CHAR(1 BYTE)         NOT NULL
);


CREATE UNIQUE INDEX PK_PCERCUL ON PCERCUL_ELEM_REFING_CHARGE_UL
(PCERCUL_ID);


ALTER TABLE PCERCUL_ELEM_REFING_CHARGE_UL ADD (
  CONSTRAINT PK_PCERCUL
 PRIMARY KEY
 (PCERCUL_ID));





CREATE TABLE REDUL_REFINING_ELEMENT_DTL_UL
(
  REDUL_ID                 VARCHAR2(15 BYTE)                 NOT NULL,
  INTERNAL_ACTION_REF_NO   VARCHAR2(15 BYTE)                 NOT NULL,
  ENTRY_TYPE               VARCHAR2(30 BYTE)                 NOT NULL,
  RED_ID                   VARCHAR2(15 BYTE)                 NOT NULL,
  PCRH_ID                  VARCHAR2(15 BYTE)                 NOT NULL,
  ELEMENT_ID               VARCHAR2(15 BYTE)                 NOT NULL,
  VERSION                  NUMBER(10)                        NOT NULL,
  IS_ACTIVE                CHAR(1 BYTE)                      NOT NULL
);


CREATE UNIQUE INDEX PK_REDUL ON REDUL_REFINING_ELEMENT_DTL_UL
(REDUL_ID);


ALTER TABLE REDUL_REFINING_ELEMENT_DTL_UL ADD (
  CONSTRAINT PK_REDUL
 PRIMARY KEY
 (REDUL_ID));





CREATE TABLE RQDUL_REFINING_QUALITY_DTL_UL
(
  RQDUL_ID                 VARCHAR2(15 BYTE)                  NOT NULL,
  INTERNAL_ACTION_REF_NO   VARCHAR2(15 BYTE)                  NOT NULL,
  ENTRY_TYPE               VARCHAR2(30 BYTE)                  NOT NULL,
  RQD_ID                   VARCHAR2(15 BYTE)                  NOT NULL,
  PCRH_ID                  VARCHAR2(15 BYTE)                  NOT NULL,
  PCPQ_ID                  VARCHAR2(15 BYTE)                  NOT NULL,
  VERSION                  NUMBER(10)                         NOT NULL,
  IS_ACTIVE                CHAR(1 BYTE)                       NOT NULL
);


CREATE UNIQUE INDEX PK_RQDUL ON RQDUL_REFINING_QUALITY_DTL_UL
(RQDUL_ID);


ALTER TABLE RQDUL_REFINING_QUALITY_DTL_UL ADD (
  CONSTRAINT PK_RQDUL
 PRIMARY KEY
 (RQDUL_ID));



CREATE TABLE PCTHUL_TREATMENT_HEADER_UL
(
  PCTHUL_ID                 VARCHAR2(15 BYTE)   NOT NULL,
  INTERNAL_ACTION_REF_NO    VARCHAR2(15 BYTE)   NOT NULL,
  ENTRY_TYPE                VARCHAR2(30 BYTE)   NOT NULL,
  PCTH_ID                   VARCHAR2(15 BYTE)   NOT NULL,
  INTERNAL_CONTRACT_REF_NO  VARCHAR2(15 BYTE)   NOT NULL,
  RANGE_TYPE                VARCHAR2(20 BYTE)   NOT NULL,
  RANGE_UNIT_ID             VARCHAR2(15 BYTE),
  PRICE_UNIT_ID             VARCHAR2(15 BYTE),
  SLAB_TIER                 VARCHAR2(15 BYTE),
  VERSION                   NUMBER(10)          NOT NULL,
  IS_ACTIVE                 CHAR(1 BYTE)        NOT NULL
);


CREATE UNIQUE INDEX PK_PCTHUL ON PCTHUL_TREATMENT_HEADER_UL
(PCTHUL_ID);


ALTER TABLE PCTHUL_TREATMENT_HEADER_UL ADD (
  CONSTRAINT PK_PCTHUL
 PRIMARY KEY
 (PCTHUL_ID));





CREATE TABLE PCETCUL_ELEM_TREATMNT_CHRG_UL
(
  PCETCUL_ID                VARCHAR2(15 BYTE)   NOT NULL,
  INTERNAL_ACTION_REF_NO    VARCHAR2(15 BYTE)   NOT NULL,
  ENTRY_TYPE                VARCHAR2(30 BYTE)   NOT NULL,
  PCETC_ID                  VARCHAR2(15 BYTE)   NOT NULL,
  PCTH_ID                   VARCHAR2(15 BYTE)   NOT NULL,
  RANGE_MIN_OP              VARCHAR2(2 BYTE),
  RANGE_MIN_VALUE           VARCHAR2(15 BYTE),
  RANGE_MAX_OP              VARCHAR2(2 BYTE),
  RANGE_MAX_VALUE           VARCHAR2(15 BYTE),
  POSITION                  VARCHAR2(30 BYTE),
  TREATMENT_CHARGE          VARCHAR2(15 BYTE),
  TREATMENT_CHARGE_UNIT_ID  VARCHAR2(15 BYTE),
  WEIGHT_TYPE               VARCHAR2(20 BYTE),
  CHARGE_BASIS              VARCHAR2(20 BYTE),
  ESC_DESC_VALUE            VARCHAR2(15 BYTE),
  ESC_DESC_UNIT_ID          VARCHAR2(15 BYTE),
  VERSION                   NUMBER(10)          NOT NULL,
  IS_ACTIVE                 CHAR(1 BYTE)        NOT NULL,
  CHARGE_TYPE               VARCHAR2(15 BYTE)
);


CREATE UNIQUE INDEX PK_PCETCUL ON PCETCUL_ELEM_TREATMNT_CHRG_UL
(PCETCUL_ID);


ALTER TABLE PCETCUL_ELEM_TREATMNT_CHRG_UL ADD (
  CONSTRAINT PK_PCETCUL
 PRIMARY KEY
 (PCETCUL_ID));



CREATE TABLE TEDUL_TREATMENT_ELEMENT_DTL_UL
(
  TEDUL_ID                 VARCHAR2(15 BYTE)                 NOT NULL,
  INTERNAL_ACTION_REF_NO   VARCHAR2(15 BYTE)                 NOT NULL,
  ENTRY_TYPE               VARCHAR2(30 BYTE)                 NOT NULL,
  TED_ID                   VARCHAR2(15 BYTE)                 NOT NULL,
  PCTH_ID                  VARCHAR2(15 BYTE)                 NOT NULL,
  ELEMENT_ID               VARCHAR2(15 BYTE)                 NOT NULL,
  VERSION                  NUMBER(10)                        NOT NULL,
  IS_ACTIVE                CHAR(1 BYTE)                      NOT NULL
);


CREATE UNIQUE INDEX PK_TEDUL ON TEDUL_TREATMENT_ELEMENT_DTL_UL
(TEDUL_ID);


ALTER TABLE TEDUL_TREATMENT_ELEMENT_DTL_UL ADD (
  CONSTRAINT PK_TEDUL
 PRIMARY KEY
 (TEDUL_ID));




CREATE TABLE TQDUL_TREATMENT_QUALITY_DTL_UL
(
  TQDUL_ID                 VARCHAR2(15 BYTE)                  NOT NULL,
  INTERNAL_ACTION_REF_NO   VARCHAR2(15 BYTE)                  NOT NULL,
  ENTRY_TYPE               VARCHAR2(30 BYTE)                  NOT NULL,
  TQD_ID                   VARCHAR2(15 BYTE)                  NOT NULL,
  PCTH_ID                  VARCHAR2(15 BYTE)                  NOT NULL,
  PCPQ_ID                  VARCHAR2(15 BYTE)                  NOT NULL,
  VERSION                  NUMBER(10)                         NOT NULL,
  IS_ACTIVE                CHAR(1 BYTE)                       NOT NULL
);


CREATE UNIQUE INDEX PK_PCETCQDUL ON TQDUL_TREATMENT_QUALITY_DTL_UL
(TQDUL_ID);


ALTER TABLE TQDUL_TREATMENT_QUALITY_DTL_UL ADD (
  CONSTRAINT PK_PCETCQDUL
 PRIMARY KEY
 (TQDUL_ID));








  CREATE SEQUENCE SEQ_PCPCHUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;




  CREATE SEQUENCE SEQ_PCEPCUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


  CREATE SEQUENCE SEQ_PQDUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

  
  CREATE SEQUENCE SEQ_PCAPHUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


  CREATE SEQUENCE SEQ_PCAPUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


  CREATE SEQUENCE SEQ_PCAPQDUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


  CREATE SEQUENCE SEQ_PCAPADUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


  CREATE SEQUENCE SEQ_PCRHUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


  CREATE SEQUENCE SEQ_PCERCUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


  CREATE SEQUENCE SEQ_REDUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

  CREATE SEQUENCE SEQ_RQDUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

  CREATE SEQUENCE SEQ_PCTHUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

  CREATE SEQUENCE SEQ_PCETCUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

  CREATE SEQUENCE SEQ_TEDUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

  CREATE SEQUENCE SEQ_TQDUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

DROP TRIGGER FKNTM_PAR_PHYSICAL_AMEND_REASO;

CREATE SEQUENCE SEQ_PAR
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
