ALTER TABLE EKAUSER_BOL_PRD.IUD_INVOICE_UTILITY_DETAIL
MODIFY(INVOICE_MAIN_TYPE VARCHAR2(50 CHAR));

ALTER TABLE EKAUSER_BOL_PRD.IUD_INVOICE_UTILITY_DETAIL
MODIFY(DELIVERY_ITEM_REF_NO VARCHAR2(50 CHAR));

ALTER TABLE EKAUSER_BOL_PRD.IUD_INVOICE_UTILITY_DETAIL
MODIFY(PRODUCT_NAME VARCHAR2(100 CHAR));

ALTER TABLE EKAUSER_BOL_PRD.IUD_INVOICE_UTILITY_DETAIL
MODIFY(FEED_REG_REF_NO VARCHAR2(100 CHAR));

ALTER TABLE EKAUSER_BOL_PRD.IUD_INVOICE_UTILITY_DETAIL
MODIFY(FEED_REG_REF_NO VARCHAR2(100 CHAR));

commit;