UPDATE AMC_APP_MENU_CONFIGURATION AMC
SET AMC.MENU_DISPLAY_NAME ='Arrival Report'
WHERE AMC.MENU_ID ='RPT-D255';

UPDATE AMC_APP_MENU_CONFIGURATION AMC
SET AMC.MENU_DISPLAY_NAME ='Closing Balance Report'
WHERE AMC.MENU_ID ='RPT-D257';

COMMIT;

