CREATE TABLE CIAPM_COMM_INV_ADV_PAY_MAPPING
(
  CIAPM_ID                      VARCHAR2(15 BYTE)    NOT NULL,
  INTERNAL_INVOICE_REF_NO       VARCHAR2(15 BYTE)    NOT NULL,
  API_INTERNAL_INVOICE_REF_NO   VARCHAR2(15 BYTE)    NOT NULL,
  API_AMOUNT_ADJUSTED           NUMBER(38,18)        NOT NULL
);

ALTER TABLE CIAPM_COMM_INV_ADV_PAY_MAPPING ADD (
  CONSTRAINT CIAPM_PK
 PRIMARY KEY
 (CIAPM_ID));
 
ALTER TABLE CIAPM_COMM_INV_ADV_PAY_MAPPING ADD (
  CONSTRAINT CIAPM_IS_FK 
 FOREIGN KEY (INTERNAL_INVOICE_REF_NO) 
 REFERENCES IS_INVOICE_SUMMARY (INTERNAL_INVOICE_REF_NO));

ALTER TABLE CIAPM_COMM_INV_ADV_PAY_MAPPING ADD (
  CONSTRAINT CIAPM_ISAP_FK 
 FOREIGN KEY (API_INTERNAL_INVOICE_REF_NO) 
 REFERENCES IS_INVOICE_SUMMARY (INTERNAL_INVOICE_REF_NO));

CREATE SEQUENCE SEQ_CIAPM
  START WITH 1
  MAXVALUE 999999999999999999999999999
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
