ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD
(
PRODUCT_ID                  VARCHAR2(15),
CONSTRAINT FK_GMR_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PDM_PRODUCTMASTER (PRODUCT_ID)
);

ALTER TABLE GMRUL_GMR_UL ADD
(
PRODUCT_ID                  VARCHAR2(15)
);