

CREATE TABLE YPD_YIELD_PCT_DETAIL
(
  YPD_ID               VARCHAR2(15 CHAR),
  INTERNAL_GMR_REF_NO  VARCHAR2(15 CHAR),
  ELEMENT_ID           VARCHAR2(15 CHAR),
  YIELD_PCT            NUMBER(5,2),
  VERSION              NUMBER(10)               NOT NULL
);


ALTER TABLE YPD_YIELD_PCT_DETAIL ADD (
  CONSTRAINT PK_YPD
 PRIMARY KEY
 (YPD_ID));

ALTER TABLE YPD_YIELD_PCT_DETAIL ADD (
  CONSTRAINT FK_YPD_INTERNAL_GMR_REF_NO 
 FOREIGN KEY (INTERNAL_GMR_REF_NO) 
 REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO));


 CREATE SEQUENCE SEQ_YPD
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  


  ALTER TABLE GRD_GOODS_RECORD_DETAIL
drop CONSTRAINT CHK_GRD_TOLLING_STOCK_TYPE;


ALTER TABLE GRD_GOODS_RECORD_DETAIL
add CONSTRAINT CHK_GRD_TOLLING_STOCK_TYPE
   CHECK (TOLLING_STOCK_TYPE IN ('None Tolling','MFT In Process Stock','RM In Process Stock','RM Out Process Stock','Process Activity','Clone Stock','Input Process','Output Process','Free Material Stock'));  
   

ALTER TABLE AGRD_ACTION_GRD
drop CONSTRAINT CHK_AGRD_TOLLING_STOCK_TYPE;


ALTER TABLE AGRD_ACTION_GRD
add CONSTRAINT CHK_AGRD_TOLLING_STOCK_TYPE
   CHECK (TOLLING_STOCK_TYPE IN ('None Tolling','MFT In Process Stock','RM In Process Stock','RM Out Process Stock','Process Activity','Clone Stock','Input Process','Output Process','Free Material Stock'));

