ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD
(
IS_PASS_THROUGH CHAR(1) DEFAULT 'N' NULL,
CONSTRAINT CHK_GMR_IS_PASS_THROUGH CHECK ( IS_PASS_THROUGH IN ('Y', 'N'))
);

ALTER TABLE GMRUL_GMR_UL ADD
(
IS_PASS_THROUGH CHAR(1) NULL
);

ALTER TABLE GRD_GOODS_RECORD_DETAIL ADD
(
PCDI_ID VARCHAR2 (15) NULL,
SUPP_CONTRACT_ITEM_REF_NO VARCHAR2 (15) NULL,
SUPPLIER_PCDI_ID VARCHAR2 (15) NULL,
CONSTRAINT FK_GRD_PCDI_ID FOREIGN KEY (PCDI_ID) REFERENCES PCDI_PC_DELIVERY_ITEM (PCDI_ID),
CONSTRAINT FK_GRD_SUPP_ITEM_REF_NO FOREIGN KEY (SUPP_CONTRACT_ITEM_REF_NO) REFERENCES PCI_PHYSICAL_CONTRACT_ITEM (INTERNAL_CONTRACT_ITEM_REF_NO),
CONSTRAINT FK_GRD_SUPPLIER_PCDI_ID FOREIGN KEY (SUPPLIER_PCDI_ID) REFERENCES PCDI_PC_DELIVERY_ITEM (PCDI_ID)
);

ALTER TABLE GRDUL_GOODS_RECORD_DETAIL_UL ADD
(
PCDI_ID VARCHAR2 (15) NULL,
SUPP_CONTRACT_ITEM_REF_NO VARCHAR2 (15) NULL,
SUPPLIER_PCDI_ID VARCHAR2 (15) NULL
);

ALTER TABLE AGRD_ACTION_GRD ADD
(
PCDI_ID VARCHAR2 (15) NULL,
SUPP_CONTRACT_ITEM_REF_NO VARCHAR2 (15) NULL,
SUPPLIER_PCDI_ID VARCHAR2 (15) NULL,
CONSTRAINT FK_AGRD_PCDI_ID FOREIGN KEY (PCDI_ID) REFERENCES PCDI_PC_DELIVERY_ITEM (PCDI_ID),
CONSTRAINT FK_AGRD_SUPP_ITEM_REF_NO FOREIGN KEY (SUPP_CONTRACT_ITEM_REF_NO) REFERENCES PCI_PHYSICAL_CONTRACT_ITEM (INTERNAL_CONTRACT_ITEM_REF_NO),
CONSTRAINT FK_AGRD_SUPPLIER_PCDI_ID FOREIGN KEY (SUPPLIER_PCDI_ID) REFERENCES PCDI_PC_DELIVERY_ITEM (PCDI_ID)
);