
CREATE TABLE DI_DEL_ITEM_EXP_QP_DETAILS( 
DIPQD_ID VARCHAR2(15) NOT NULL,
PCBPH_ID VARCHAR2(15) NOT NULL,
PCBPD_ID VARCHAR2(15) NOT NULL,
PCDI_ID VARCHAR2(15) NOT NULL,
EXPECTED_QP_START_DATE DATE NOT NULL,
EXPECTED_QP_END_DATE DATE NOT NULL,
CONSTRAINT dipqd_id_pk PRIMARY KEY (DIPQD_ID),
CONSTRAINT fk_pcbph_id FOREIGN KEY (PCBPH_ID) REFERENCES PCBPH_PC_BASE_PRICE_HEADER(PCBPH_ID),
CONSTRAINT fk_pcbpd_id FOREIGN KEY (PCBPD_ID) REFERENCES PCBPD_PC_BASE_PRICE_DETAIL(PCBPD_ID),
CONSTRAINT fk_pcdi_id FOREIGN KEY (PCDI_ID) REFERENCES PCDI_PC_DELIVERY_ITEM(PCDI_ID)
);


alter table POFH_PRICE_OPT_FIXATION_HEADER 
add (AVG_PRICE_IN_PRICE_IN_CUR  NUMBER(25,10), AVG_FX  NUMBER(25,10));