CREATE SEQUENCE SEQ_VCS
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;


CREATE SEQUENCE SEQ_VCA
  START WITH 18
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

drop table VCA_VALUATION_CURVE_ATTRIBUTE;
drop table VCS_VALUATION_CURVE_SETUP;
CREATE TABLE VCS_VALUATION_CURVE_SETUP
(
  VCS_ID          VARCHAR2(15 BYTE)             NOT NULL,
  CORPORATE_ID    VARCHAR2(15 BYTE)             NOT NULL,
  PRODUCT_ID      VARCHAR2(15 BYTE)             NOT NULL,
  CURVE_NAME      VARCHAR2(50 BYTE)             NOT NULL,
  APPLICABLE_ID   VARCHAR2(15 BYTE)             NOT NULL,
  IS_CONCENTRATE  CHAR(1 BYTE),
  IS_ACTIVE       CHAR(1 BYTE)                  DEFAULT 'Y'                   NOT NULL,
  IS_DELETE       CHAR(1 BYTE)                  DEFAULT 'N'                   NOT NULL
);


CREATE UNIQUE INDEX PK_VCS_ID ON VCS_VALUATION_CURVE_SETUP
(VCS_ID);


ALTER TABLE VCS_VALUATION_CURVE_SETUP ADD (
  CONSTRAINT PK_VCS_ID
 PRIMARY KEY
 (VCS_ID));



CREATE TABLE VCA_VALUATION_CURVE_ATTRIBUTE
(
  VCA_ID         VARCHAR2(15 BYTE)              NOT NULL,
  VCS_ID         VARCHAR2(15 BYTE)              NOT NULL,
  ATTRIBUTE_ID   VARCHAR2(15 BYTE),
  PRICE_UNIT_ID  VARCHAR2(50 BYTE)
);


CREATE UNIQUE INDEX PK_VCA_ID ON VCA_VALUATION_CURVE_ATTRIBUTE
(VCA_ID);


ALTER TABLE VCA_VALUATION_CURVE_ATTRIBUTE ADD (
  CONSTRAINT PK_VCA_ID
 PRIMARY KEY
 (VCA_ID));

 DROP TABLE MDCD_M2M_DED_CHARGE_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE MDCD_M2M_DED_CHARGE_DETAILS
(
  INTERNAL_MDCD_REF_NO  VARCHAR2(15 BYTE)       NOT NULL,
  CORPORATE_ID          VARCHAR2(15 BYTE)       NOT NULL,
  AS_OF_DATE            DATE                    NOT NULL,
  PRODUCT_ID            VARCHAR2(15 BYTE)       NOT NULL,
  QUALITY_ID            VARCHAR2(15 BYTE)       NOT NULL,
  VALUATION_REGION_ID   VARCHAR2(15 BYTE)       NOT NULL,
  CHARGE_TYPE           VARCHAR2(17 BYTE)       NOT NULL,
  CALENDAR_MONTH        VARCHAR2(15 BYTE),
  CALENDAR_YEAR         VARCHAR2(15 BYTE),
  INTERNAL_ELEMENT_ID   VARCHAR2(15 BYTE),
  CHARGE_VALUE          NUMBER(25,5),
  CHARGE_UNIT_ID        VARCHAR2(15 BYTE)
);

COMMENT ON TABLE MDCD_M2M_DED_CHARGE_DETAILS IS 'This table contains Deduction Charges details for a Product and Valuation Region';

COMMENT ON COLUMN MDCD_M2M_DED_CHARGE_DETAILS.INTERNAL_MDCD_REF_NO IS 'This field will contain MDCD_ID.';

COMMENT ON COLUMN MDCD_M2M_DED_CHARGE_DETAILS.CORPORATE_ID IS 'This field will contain corporateId';

COMMENT ON COLUMN MDCD_M2M_DED_CHARGE_DETAILS.AS_OF_DATE IS 'This field will contain Date on which Charges are entered';

COMMENT ON COLUMN MDCD_M2M_DED_CHARGE_DETAILS.PRODUCT_ID IS 'This field will contain Product Id.';

COMMENT ON COLUMN MDCD_M2M_DED_CHARGE_DETAILS.VALUATION_REGION_ID IS 'This field will contain Valuation Region Id.';

COMMENT ON COLUMN MDCD_M2M_DED_CHARGE_DETAILS.CHARGE_TYPE IS 'Refining Charge or Treatment Charge or Penalty Charge.';

COMMENT ON COLUMN MDCD_M2M_DED_CHARGE_DETAILS.CALENDAR_MONTH IS 'This field will contain Month.';

COMMENT ON COLUMN MDCD_M2M_DED_CHARGE_DETAILS.CALENDAR_YEAR IS 'This field will contain Year.';

COMMENT ON COLUMN MDCD_M2M_DED_CHARGE_DETAILS.INTERNAL_ELEMENT_ID IS 'This field will contain Internal Element Id.';

COMMENT ON COLUMN MDCD_M2M_DED_CHARGE_DETAILS.CHARGE_VALUE IS 'This field will contain Charge value.';

COMMENT ON COLUMN MDCD_M2M_DED_CHARGE_DETAILS.CHARGE_UNIT_ID IS 'This field will contain Charge Unit Id.';


CREATE UNIQUE INDEX PK_MDCD ON MDCD_M2M_DED_CHARGE_DETAILS
(INTERNAL_MDCD_REF_NO);


ALTER TABLE MDCD_M2M_DED_CHARGE_DETAILS ADD (
  CONSTRAINT CHK_CHARGE_TYPE
 CHECK (CHARGE_TYPE in('Refining Charges','Treatment Charges','Penalties')),
  CONSTRAINT PK_MDCD
 PRIMARY KEY
 (INTERNAL_MDCD_REF_NO));


alter table VCS_VALUATION_CURVE_SETUP  modify  APPLICABLE_ID VARCHAR2 (50 Byte);

