alter table ASH_ASSAY_HEADER modify(NET_WEIGHT NUMBER (25,10));
alter table ASH_ASSAY_HEADER add(ASSAY_RECEIVED_DATE DATE);
alter table ASH_ASSAY_HEADER add(OUR_REF_NUMBER VARCHAR2 (50 Byte));
alter table ASH_ASSAY_HEADER add(EXT_REF_NUMBER VARCHAR2 (50 Byte));
alter table ASH_ASSAY_HEADER add(ASSAY_RECEIVED_FROM VARCHAR2 (50 Byte));