 

CREATE TABLE PCDT_PHY_CON_DRAFT_TEMPLATE
(
  ID                      VARCHAR2(15  )     NOT NULL,
  DRAFT_TEMPLATE_TYPE     VARCHAR2(15  ),
  DRAFT_TEMPLATE_NAME     VARCHAR2(15  ),
  CP_NAME                 VARCHAR2(20  ),
  TYPE                    VARCHAR2(15  ),
  JAVA_OBJECT             BLOB,
  INTERNAL_ACTION_REF_NO  VARCHAR2(15  )     NOT NULL,
  PROFIT_CENTER           VARCHAR2(20  ),
  DRAFT_NO                VARCHAR2(15  )     NOT NULL,
  IS_ACTIVE               CHAR(1  )          DEFAULT 'Y'                   NOT NULL,
  CORPORATE_ID            VARCHAR2(15  ),
  TRADER                  VARCHAR2(15  ),
  EXECUTION_TYPE          VARCHAR2(15  ),
  STRATEGY                VARCHAR2(15  ),
  CONTRACT_ISSUE_DATE     DATE,
  PRODUCT                 VARCHAR2(15  )
);



ALTER TABLE PCDT_PHY_CON_DRAFT_TEMPLATE ADD (
  CONSTRAINT PK_PCDT_ID
 PRIMARY KEY
 (ID));


CREATE SEQUENCE SEQ_PCDT
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;