alter table IS_D add (INVOICED_QTY_UNIT VARCHAR2(30));

alter table IS_D add(SALES_PURCHASE VARCHAR2(30 BYTE));

alter table DGM add(IS_CONCENTRATE CHAR(1) default 'N');

ALTER table IS_D MODIFY(INCO_TERM_LOCATION VARCHAR2(100 BYTE));

CREATE TABLE IS_CONC_PAYABLE_CHILD
(
  INTERNAL_INVOICE_REF_NO           VARCHAR2(30 BYTE),
  INTERNAL_DOC_REF_NO               VARCHAR2(30 BYTE),
  ELEMENT_NAME                      VARCHAR2(30 BYTE),
  INVOICE_PRICE                     VARCHAR2(30 BYTE),
  ELEMENT_PRICE_UNIT                VARCHAR2(50 BYTE),
  SUB_LOT_NO                        VARCHAR2(30 BYTE),
  ASSAY_CONTENT                     VARCHAR2(30 BYTE),
  ASSAY_CONTENT_UNIT                VARCHAR2(30 BYTE),
  STOCK_REF_NO                      VARCHAR2(30 BYTE),
  STOCK_QTY                         VARCHAR2(30 BYTE),
  ELEMENT_INVOICED_QTY_UNIT         VARCHAR2(30 BYTE),
  GMR_REF_NO                        VARCHAR2(30 BYTE),
  GMR_QUANTITY                      VARCHAR2(30 BYTE),
  GMR_QUALITY                       VARCHAR2(30 BYTE),
  GMR_QTY_UNIT                      VARCHAR2(30 BYTE),
  INVOICED_PRICE_UNIT               VARCHAR2(30 BYTE),
  ELEMENT_INVOICED_QTY              VARCHAR2(30 BYTE),
  ELEMENT_ID                        VARCHAR2(30 BYTE)
);

CREATE TABLE IS_CONC_TC_CHILD
(
  INTERNAL_INVOICE_REF_NO           VARCHAR2(30 BYTE),
  INTERNAL_DOC_REF_NO               VARCHAR2(30 BYTE),
  ELEMENT_NAME                      VARCHAR2(30 BYTE),
  ELEMENT_ID                        VARCHAR2(30 BYTE),
  TC_AMOUNT                         VARCHAR2(30 BYTE),
  AMOUNT_UNIT                       VARCHAR2(30 BYTE)
);


CREATE TABLE IS_CONC_RC_CHILD
(
  INTERNAL_INVOICE_REF_NO           VARCHAR2(30 BYTE),
  INTERNAL_DOC_REF_NO               VARCHAR2(30 BYTE),
  ELEMENT_NAME                      VARCHAR2(30 BYTE),
  ELEMENT_ID                        VARCHAR2(30 BYTE),
  RC_AMOUNT                         VARCHAR2(30 BYTE),
  AMOUNT_UNIT                       VARCHAR2(30 BYTE)
);

CREATE TABLE IS_CONC_PENALTY_CHILD
(
  INTERNAL_INVOICE_REF_NO           VARCHAR2(30 BYTE),
  INTERNAL_DOC_REF_NO               VARCHAR2(30 BYTE),
  ELEMENT_NAME                      VARCHAR2(30 BYTE),
  ELEMENT_ID                        VARCHAR2(30 BYTE),
  PENALTY_AMOUNT                    VARCHAR2(30 BYTE),
  AMOUNT_UNIT                       VARCHAR2(30 BYTE)
);

CREATE TABLE IS_BDP_CHILD_D
(
  INTERNAL_INVOICE_REF_NO  VARCHAR2(30 BYTE),
  INTERNAL_DOC_REF_NO      VARCHAR2(30 BYTE),
  BENEFICIARY_NAME         VARCHAR2(30 BYTE),
  BANK_NAME                VARCHAR2(30 BYTE),
  ACCOUNT_NO               VARCHAR2(50 BYTE),
  IBAN                     VARCHAR2(30 BYTE),
  ABA_RTN                  VARCHAR2(30 BYTE),
  INSTRUCTION              VARCHAR2(100 BYTE)
);

CREATE TABLE IS_BDS_CHILD_D
(
  INTERNAL_INVOICE_REF_NO  VARCHAR2(30 BYTE),
  INTERNAL_DOC_REF_NO      VARCHAR2(30 BYTE),
  BENEFICIARY_NAME         VARCHAR2(30 BYTE),
  BANK_NAME                VARCHAR2(30 BYTE),
  ACCOUNT_NO               VARCHAR2(50 BYTE),
  IBAN                     VARCHAR2(30 BYTE),
  ABA_RTN                  VARCHAR2(30 BYTE),
  INSTRUCTION              VARCHAR2(100 BYTE)
);