ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(PAYABLE_QTY_DISPLAY VARCHAR2(4000 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(FREE_METAL_QTY_DISPLAY VARCHAR2(4000 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(TC_AMOUNT_DISPLAY VARCHAR2(4000 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(RC_AMOUNT_DISPLAY VARCHAR2(4000 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(PENALTY_AMOUNT_DISPLAY VARCHAR2(4000 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(FREE_METAL_AMOUNT_DISPLAY VARCHAR2(4000 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(TOTAL_INVOICE_AMOUNT VARCHAR2(1000 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(PARENT_INVOICE_AMOUNT VARCHAR2(1000 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(VAT_AMOUNT_IN_INVOICE_CURRENCY VARCHAR2(1000 CHAR));