ALTER TABLE II_INVOICABLE_ITEM
 ADD (IS_PASS_THROUGH  CHAR(1 CHAR) DEFAULT 'N');

ALTER TABLE II_INVOICABLE_ITEM
 ADD (SUPP_INTERNAL_CONTRACT_REF_NO  VARCHAR2(15 CHAR));

ALTER TABLE II_INVOICABLE_ITEM
 ADD (SUPPLIER_PCDI_ID  VARCHAR2(15 CHAR));

ALTER TABLE II_INVOICABLE_ITEM
 ADD (IS_TOLLING  CHAR(1 CHAR) DEFAULT 'N');

