CREATE TABLE DIPCH_DI_PAYABLECONTENT_HEADER
(
  DIPCH_ID    VARCHAR2(15 CHAR),
  PCDI_ID    VARCHAR2(15 CHAR),
  PCPCH_ID    VARCHAR2(15 CHAR),
  VERSION    NUMBER(10),
  IS_ACTIVE  CHAR(1 CHAR)                       DEFAULT 'Y'
);


ALTER TABLE DIPCH_DI_PAYABLECONTENT_HEADER ADD (
  CONSTRAINT PK_DIPCH
 PRIMARY KEY
 (DIPCH_ID));

 CREATE SEQUENCE SEQ_DIPCH
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;



CREATE TABLE DIPCHUL_DI_PAYBLECON_HEADER_UL
(
  DIPCHUL_ID              VARCHAR2(15 CHAR),
  INTERNAL_ACTION_REF_NO  VARCHAR2(15 CHAR)     NOT NULL,
  ENTRY_TYPE              VARCHAR2(30 CHAR)     NOT NULL,
  DIPCH_ID                VARCHAR2(15 CHAR)     NOT NULL,
  PCDI_ID                 VARCHAR2(15 CHAR)     NOT NULL,
  PCPCH_ID                VARCHAR2(15 CHAR)     NOT NULL,
  VERSION                 NUMBER(10)            NOT NULL,
  IS_ACTIVE               CHAR(1 CHAR)          DEFAULT 'Y'                   NOT NULL
);


ALTER TABLE DIPCHUL_DI_PAYBLECON_HEADER_UL ADD (
  CONSTRAINT PK_DIPCHUL
 PRIMARY KEY
 (DIPCHUL_ID));


CREATE SEQUENCE SEQ_DIPCHUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;