ALTER TABLE IS_BDS_CHILD_D MODIFY(BENEFICIARY_NAME VARCHAR2(100 CHAR));

ALTER TABLE IS_BDS_CHILD_D MODIFY(BANK_NAME VARCHAR2(100 CHAR));

ALTER TABLE IS_BDP_CHILD_D MODIFY(BENEFICIARY_NAME VARCHAR2(100 CHAR));

ALTER TABLE IS_BDP_CHILD_D MODIFY(BANK_NAME VARCHAR2(100 CHAR));


