
ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD (IS_INTERFACE_GMR  CHAR(1) DEFAULT 'N');

ALTER TABLE GMRUL_GMR_UL ADD (IS_OPEN_BACK_TO_BACK  CHAR(1));
ALTER TABLE GMRUL_GMR_UL ADD (IS_INTERFACE_GMR  CHAR(1));