ALTER TABLE EVD_ECONOMIC_VALUE_DETAILS ADD (CREATED_DATE  TIMESTAMP(6));

ALTER TABLE EVD_ECONOMIC_VALUE_DETAILS ADD (CREATED_USER_ID  VARCHAR2(15));

ALTER TABLE EVD_ECONOMIC_VALUE_DETAILS ADD (UPDATED_DATE  TIMESTAMP(6));

ALTER TABLE EVD_ECONOMIC_VALUE_DETAILS ADD (UPDATED_BY_USER_ID  VARCHAR2(15));

ALTER TABLE EVD_ECONOMIC_VALUE_DETAILS MODIFY(IS_DELETED  DEFAULT 'N');

ALTER TABLE EVD_ECONOMIC_VALUE_DETAILS MODIFY(IS_DEDUCTABLE  DEFAULT 'N');