ALTER TABLE PE_METALS_BUILD3_DEV.IEPD_INV_EPENALTY_DETAILS
 DROP PRIMARY KEY CASCADE;
DROP TABLE IEPD_INV_EPENALTY_DETAILS CASCADE CONSTRAINTS;

CREATE TABLE IEPD_INV_EPENALTY_DETAILS
(
  IEPD_ID                  VARCHAR2(15 BYTE)    NOT NULL,
  INTERNAL_INVOICE_REF_NO  VARCHAR2(15 BYTE)    NOT NULL,
  ELEMENT_ID               VARCHAR2(15 BYTE),
  ELEMENT_QTY              NUMBER(38,18),
  ELEMENT_PENALTY_PRICE    NUMBER(38,18),
  ELEMENT_QTY_UNIT_ID      VARCHAR2(15 BYTE),
  ELEMENT_PENALTY_AMOUNT   NUMBER(38,18),
  ELEMENT_PRICE_UNIT_ID    VARCHAR2(15 BYTE),
  SUB_LOT_NO               VARCHAR2(15 BYTE),
  STOCK_ID                 VARCHAR2(15 BYTE)
);


CREATE UNIQUE INDEX IEPD_PK ON IEPD_INV_EPENALTY_DETAILS
(IEPD_ID);


ALTER TABLE IEPD_INV_EPENALTY_DETAILS ADD (
  CONSTRAINT IEPD_PK
 PRIMARY KEY
 (IEPD_ID));

ALTER TABLE IEPD_INV_EPENALTY_DETAILS ADD (
  CONSTRAINT IEPD_IS_FK 
 FOREIGN KEY (INTERNAL_INVOICE_REF_NO) 
 REFERENCES IS_INVOICE_SUMMARY (INTERNAL_INVOICE_REF_NO));
