
CREATE TABLE PFD_D
(
  INTERNAL_DOC_REF_NO   VARCHAR2(30 CHAR),
  CORPORATE_NAME        VARCHAR2(100 CHAR),
  CP_ADDRESS            VARCHAR2(100 CHAR),
  CP_CITY               VARCHAR2(100 CHAR),
  CP_COUNTRY            VARCHAR2(100 CHAR),
  CP_ZIP                VARCHAR2(100 CHAR),
  CP_STATE              VARCHAR2(100 CHAR),
  CP_NAME               VARCHAR2(100 CHAR),
  CP_PERSON_IN_CHARGE   VARCHAR2(100 CHAR),
  CONTRACT_TYPE         VARCHAR2(30 CHAR),
  CONTRACT_REF_NO       VARCHAR2(30 CHAR),
  DELIVERY_ITEM_REF_NO  VARCHAR2(80 CHAR),
  PAY_IN_CURRENCY       VARCHAR2(15 CHAR),
  PRODUCT               VARCHAR2(100 CHAR),
  QUALITY               VARCHAR2(200 CHAR),
  ELEMENT_NAME          VARCHAR2(30 CHAR),
  PRICING_FORMULA       VARCHAR2(200 CHAR),
  QUOTA_PERIOD          VARCHAR2(50 CHAR),
  GMR_REF_NO            VARCHAR2(30 CHAR),
  QP                    VARCHAR2(50 CHAR),
  CURRENCY_PRODUCT      VARCHAR2(30 CHAR),
  QUANTITY_UNIT         VARCHAR2(30 CHAR)
);

CREATE TABLE PFD_CHILD_D
(
  PFD_ID                 VARCHAR2(15 CHAR),
  INTERNAL_DOC_REF_NO    VARCHAR2(30 CHAR),
  PRICE_FIXATION_REF_NO  VARCHAR2(30 CHAR),
  PRICE                  VARCHAR2(30 CHAR),
  PRICE_UNIT             VARCHAR2(30 CHAR),
  PRICE_FIXATION_DATE    DATE,
  PRICED_QUANTITY        VARCHAR2(30 CHAR),
  FX_RATE                VARCHAR2(30 CHAR),
  PRICE_TYPE            VARCHAR2(30 CHAR)
);