CREATE TABLE IS_PARENT_CHILD_D
(
  INTERNAL_INVOICE_REF_NO  VARCHAR2(30 BYTE),
  INTERNAL_DOC_REF_NO      VARCHAR2(30 BYTE),
  INVOICE_REF_NO           VARCHAR2(30 BYTE),
  INVOICE_AMOUNT           VARCHAR2(30 BYTE),
  INVOICE_CURRENCY         VARCHAR2(30 BYTE),
  INVOICE_ISSUE_DATE       VARCHAR2(30 BYTE),
  DUE_DATE                 VARCHAR2(30 BYTE)
);

alter table IS_D add (MATERIAL_COST VARCHAR2(30));