
 alter table GRD_GOODS_RECORD_DETAIL add WGTD_AVG_PRICING_ASSAY_ID varchar2(15);
 alter table GRDUL_GOODS_RECORD_DETAIL_UL add WGTD_AVG_PRICING_ASSAY_ID varchar2(15);
 alter table DGRD_DELIVERED_GRD add WGTD_AVG_PRICING_ASSAY_ID varchar2(15);
 alter table DGRDUL_DELIVERED_GRD_UL add WGTD_AVG_PRICING_ASSAY_ID varchar2(15);
 
 
 alter table GMR_GOODS_MOVEMENT_RECORD add (LATEST_ASSAY_TYPE varchar2(50),ASSAY_DATE Date);
 alter table GMRUL_GMR_UL add (LATEST_ASSAY_TYPE varchar2(50),ASSAY_DATE Date);
 