alter table SPQL_STOCK_PAYABLE_QTY_LOG add (
  IS_PURE_FREE_METAL_ELEM  CHAR(1),
  EXT_ASSAY_HEADER_ID      VARCHAR2(15),
  EXT_ASSAY_CONTENT        NUMBER(25,10),
  EXT_PAYABLE_QTY          NUMBER(25,10)
)