ALTER TABLE PE_METALS_BUILD3_DEV.PCPDQD_PD_QUALITY_DETAILS
 ADD (QUALITY_NAME  VARCHAR2(30 BYTE));

ALTER TABLE PE_METALS_BUILD3_DEV.PQD_PAYABLE_QUALITY_DETAILS
 ADD (QUALITY_NAME  VARCHAR2(30 BYTE));

ALTER TABLE PE_METALS_BUILD3_DEV.TQD_TREATMENT_QUALITY_DETAILS
 ADD (QUALITY_NAME  VARCHAR2(30 BYTE));

ALTER TABLE PE_METALS_BUILD3_DEV.RQD_REFINING_QUALITY_DETAILS
 ADD (QUALITY_NAME  VARCHAR2(30 BYTE));

ALTER TABLE PE_METALS_BUILD3_DEV.PQD_PENALTY_QUALITY_DETAILS
 ADD (QUALITY_NAME  VARCHAR2(30 BYTE));

ALTER TABLE PE_METALS_BUILD3_DEV.ARQD_ASSAY_QUALITY_DETAILS
 ADD (QUALITY_NAME  VARCHAR2(30 BYTE));


ALTER TABLE PE_METALS_BUILD3_DEV.TED_TREATMENT_ELEMENT_DETAILS
 ADD (ELEMENT_NAME  VARCHAR2(30 BYTE));

ALTER TABLE PE_METALS_BUILD3_DEV.RED_REFINING_ELEMENT_DETAILS
 ADD (ELEMENT_NAME  VARCHAR2(30 BYTE));

ALTER TABLE PE_METALS_BUILD3_DEV.PAD_PENALTY_ATTRIBUTE_DETAILS
 ADD (ELEMENT_NAME  VARCHAR2(30 BYTE));

ALTER TABLE PE_METALS_BUILD3_DEV.PCAR_PC_ASSAYING_RULES
 ADD (ELEMENT_NAME  VARCHAR2(30 BYTE));