CREATE TABLE PCBPH_PC_BASE_PRICE_HEADER
(
  PCBPH_ID                  VARCHAR2(15 BYTE)   NOT NULL,
  OPTIONALITY_DESC          VARCHAR2(4000 BYTE),
  VERSION                   NUMBER(10)          NOT NULL,
  IS_ACTIVE                 CHAR(1 BYTE)        DEFAULT 'Y'                   NOT NULL,
  INTERNAL_CONTRACT_REF_NO  VARCHAR2(15 BYTE)   NOT NULL
);


CREATE UNIQUE INDEX PK_PCBPH_ID ON PCBPH_PC_BASE_PRICE_HEADER
(PCBPH_ID);


ALTER TABLE PCBPH_PC_BASE_PRICE_HEADER ADD (
  CONSTRAINT PK_PCBPH_ID
 PRIMARY KEY
 (PCBPH_ID));

ALTER TABLE PCBPH_PC_BASE_PRICE_HEADER ADD (
  CONSTRAINT FK_PCBPH_PCM_ID 
 FOREIGN KEY (INTERNAL_CONTRACT_REF_NO) 
 REFERENCES PCM_PHYSICAL_CONTRACT_MAIN (INTERNAL_CONTRACT_REF_NO));


ALTER TABLE PFQPP_PHY_FORMULA_QP_PRICING
 ADD (EVENT_ID  VARCHAR2(15 BYTE));



ALTER TABLE PCBPD_PC_BASE_PRICE_DETAIL
 ADD (QTY_TO_BE_PRICED  NUMBER(10,4));



ALTER TABLE PCBPD_PC_BASE_PRICE_DETAIL ADD(PCBPH_ID VARCHAR(15 BYTE)); 

ALTER TABLE PCBPD_PC_BASE_PRICE_DETAIL
 ADD CONSTRAINT FK_PCBPD_PCBPH_ID 
 FOREIGN KEY (PCBPH_ID) REFERENCES PCBPH_PC_BASE_PRICE_HEADER(PCBPH_ID);  

ALTER TABLE PCBPD_PC_BASE_PRICE_DETAIL
 ADD (DESCRIPTION  VARCHAR2(4000 BYTE));



CREATE SEQUENCE SEQ_PCBPH
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;




alter table PCI_PHYSICAL_CONTRACT_ITEM
 modify DEL_DISTRIBUTION_ITEM_NO NUMBER(10,5);


drop table PCDIPE_DI_PRICING_ELEMENTS;

CREATE TABLE PCDIPE_DI_PRICING_ELEMENTS
(
  PCDIPE_ID  VARCHAR2(15 BYTE)                  NOT NULL,
  PCDI_ID    VARCHAR2(15 BYTE)                  NOT NULL,
  PCBPH_ID   VARCHAR2(15 BYTE)                  NOT NULL,  
  VERSION    NUMBER(10)                         NOT NULL,
  IS_ACTIVE  CHAR(1 BYTE)                       DEFAULT 'Y'                   NOT NULL
);


COMMENT ON COLUMN PCDIPE_DI_PRICING_ELEMENTS.PCBPH_ID IS 'Base Price elements';

CREATE UNIQUE INDEX PK_PCDIPE ON PCDIPE_DI_PRICING_ELEMENTS
(PCDIPE_ID);

ALTER TABLE PCDIPE_DI_PRICING_ELEMENTS ADD (
  CONSTRAINT PK_PCDIPE
 PRIMARY KEY
 (PCDIPE_ID));

ALTER TABLE PCDIPE_DI_PRICING_ELEMENTS ADD (
  CONSTRAINT FK_PCDIPE_PCDI_ID 
 FOREIGN KEY (PCDI_ID) 
 REFERENCES PCDI_PC_DELIVERY_ITEM (PCDI_ID));

 
 ALTER TABLE PCDIPE_DI_PRICING_ELEMENTS ADD (
  CONSTRAINT FK_PCDIPE_PCBPH_ID 
 FOREIGN KEY (PCBPH_ID) 
 REFERENCES PCBPH_PC_BASE_PRICE_HEADER (PCBPH_ID));


DROP TABLE PCIPF_PCI_PRICING_FORMULA ;

CREATE TABLE PCIPF_PCI_PRICING_FORMULA
(
  PCIPF_ID                       VARCHAR2(15 BYTE) NOT NULL,
  INTERNAL_CONTRACT_ITEM_REF_NO  VARCHAR2(15 BYTE) NOT NULL,
  PCBPH_ID                       VARCHAR2(15 BYTE) NOT NULL,
  VERSION                        NUMBER(10)     NOT NULL,
  IS_ACTIVE                      CHAR(1 BYTE)   DEFAULT 'Y'                   NOT NULL
);



CREATE UNIQUE INDEX PK_PCIPF_ID ON PCIPF_PCI_PRICING_FORMULA
(PCIPF_ID);

ALTER TABLE PCIPF_PCI_PRICING_FORMULA ADD (
  CONSTRAINT PK_PCIPF_ID
 PRIMARY KEY
 (PCIPF_ID));
 
 ALTER TABLE PCIPF_PCI_PRICING_FORMULA ADD (
  CONSTRAINT FK_PCIPF_PCBPH_ID 
 FOREIGN KEY (PCBPH_ID) 
 REFERENCES PCBPH_PC_BASE_PRICE_HEADER (PCBPH_ID),
  CONSTRAINT FK_PCIPF_PCI_ID 
 FOREIGN KEY (INTERNAL_CONTRACT_ITEM_REF_NO) 
 REFERENCES PCI_PHYSICAL_CONTRACT_ITEM (INTERNAL_CONTRACT_ITEM_REF_NO));

 alter table PCBPD_PC_BASE_PRICE_DETAIL drop column INTERNAL_CONTRACT_REF_NO ;



CREATE TABLE PCPCH_PC_PAYBLE_CONTENT_HEADER
(
  PCPCH_ID                  VARCHAR2(15 BYTE)   NOT NULL,
  INTERNAL_CONTRACT_REF_NO  VARCHAR2(15 BYTE)   NOT NULL,
  RANGE_TYPE                VARCHAR2(20 BYTE),
  RANGE_UNIT_ID             VARCHAR2(15 BYTE)   NOT NULL,
  ELEMENT_ID                VARCHAR2(15 BYTE)   NOT NULL,
  SLAB_TIER                 VARCHAR2(15 BYTE)   NOT NULL,
  VERSION                   NUMBER(10)          NOT NULL,
  IS_ACTIVE                 CHAR(1 BYTE)        DEFAULT 'Y'                   NOT NULL
);

CREATE UNIQUE INDEX PK_PCPCH ON PCPCH_PC_PAYBLE_CONTENT_HEADER
(PCPCH_ID);

ALTER TABLE PCPCH_PC_PAYBLE_CONTENT_HEADER ADD (
  CONSTRAINT PK_PCPCH
 PRIMARY KEY
 (PCPCH_ID));

ALTER TABLE PCPCH_PC_PAYBLE_CONTENT_HEADER ADD (
  CONSTRAINT FK_PCPCH_PCM_ID 
 FOREIGN KEY (INTERNAL_CONTRACT_REF_NO) 
 REFERENCES PCM_PHYSICAL_CONTRACT_MAIN (INTERNAL_CONTRACT_REF_NO));
 
 alter table PCEPC_PC_ELEM_PAYABLE_CONTENT drop (INTERNAL_CONTRACT_REF_NO,RANGE_TYPE,ELEMENT_ID,PRICE_RANGE_UNIT_ID,ASSAY_RANGE_UNIT_ID);
 
 alter table PCEPC_PC_ELEM_PAYABLE_CONTENT add (PCPCH_ID  VARCHAR2(15 BYTE)   NOT NULL);
  
 alter table PCEPC_PC_ELEM_PAYABLE_CONTENT add (POSITION  VARCHAR2(30 BYTE)   );
 
 CREATE TABLE PCAPH_PC_ATTR_PENALTY_HEADER
(
  PCAPH_ID                  VARCHAR2(15 BYTE)   NOT NULL,
  INTERNAL_CONTRACT_REF_NO  VARCHAR2(15 BYTE)   NOT NULL,
  ATTRIBUTE_TYPE            VARCHAR2(20 BYTE),
  RANGE_UNIT_ID             VARCHAR2(15 BYTE)   NOT NULL,
  SLAB_TIER                 VARCHAR2(15 BYTE)   NOT NULL,
  VERSION                   NUMBER(10)          NOT NULL,
  IS_ACTIVE                 CHAR(1 BYTE)        DEFAULT 'Y'                   NOT NULL
);


CREATE UNIQUE INDEX PK_PCAPH ON PCAPH_PC_ATTR_PENALTY_HEADER
(PCAPH_ID);


ALTER TABLE PCAPH_PC_ATTR_PENALTY_HEADER ADD (
  CONSTRAINT PK_PCAPH
 PRIMARY KEY
 (PCAPH_ID));

ALTER TABLE PCAPH_PC_ATTR_PENALTY_HEADER ADD (
  CONSTRAINT FK_PCAPH_PCM_ID 
 FOREIGN KEY (INTERNAL_CONTRACT_REF_NO) 
 REFERENCES PCM_PHYSICAL_CONTRACT_MAIN (INTERNAL_CONTRACT_REF_NO));
 
alter table PCAP_PC_ATTRIBUTE_PENALTY drop (INTERNAL_CONTRACT_REF_NO,ATTRIBUTE_TYPE,RANGE_UNIT_ID);
 
 alter table PCAP_PC_ATTRIBUTE_PENALTY add (PCAPH_ID  VARCHAR2(15 BYTE)   NOT NULL);
  
 alter table PCAP_PC_ATTRIBUTE_PENALTY add (POSITION  VARCHAR2(30 BYTE)   );
 
 
alter table PCAP_PC_ATTRIBUTE_PENALTY rename column PENALTY_INC_DEC_VALUE to PER_INCREASE_VALUE; 
alter table PCAP_PC_ATTRIBUTE_PENALTY rename column PNLTY_INC_DEC_UNIT_ID to PER_INCREASE_UNIT_ID; 
 

 CREATE SEQUENCE SEQ_PCAPH
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  
 CREATE SEQUENCE SEQ_PCPCH
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
 
alter table PCBPH_PC_BASE_PRICE_HEADER add (ELEMENT_ID varchar2(15),ELEMENT_NAME varchar2(30));





CREATE TABLE CIPQ_CONTRACT_ITEM_PAYABLE_QTY (
CIPQ_ID  VARCHAR2(15 BYTE) NOT NULL,
INTERNAl_CONTRACT_REF_NO VARCHAR2(15 BYTE) NOT NULL,
ELEMENT_ID VARCHAR(15 BYTE),
PAYABLE_QTY NUMBER(25,10),
QTY_UNIT_ID VARCHAR(15 BYTE),
VERSION    NUMBER(10)  NOT NULL,
IS_ACTIVE  CHAR(1 BYTE)  DEFAULT 'Y'  NOT NULL

);

CREATE TABLE DIPQ_DELIVERY_ITEM_PAYABLE_QTY (
DIPQ_ID  VARCHAR2(15 BYTE) NOT NULL,
PCDI_ID VARCHAR2(15 BYTE) NOT NULL,
ELEMENT_ID VARCHAR(15 BYTE),
PAYABLE_QTY NUMBER(25,10),
QTY_UNIT_ID VARCHAR(15 BYTE),
PRICE_OPTION_CALL_OFF_STATUS VARCHAR(30 BYTE) NOT NULL,
VERSION    NUMBER(10)         NOT NULL,
IS_ACTIVE   CHAR(1 BYTE)  DEFAULT 'Y'  NOT NULL

);



ALTER TABLE CIPQ_CONTRACT_ITEM_PAYABLE_QTY ADD (
  CONSTRAINT PK_CIPQ_ID
 PRIMARY KEY
 (CIPQ_ID));
 
 
ALTER TABLE DIPQ_DELIVERY_ITEM_PAYABLE_QTY  ADD (
  CONSTRAINT PK_DIPQ_ID
 PRIMARY KEY
 (DIPQ_ID));


ALTER TABLE CIPQ_CONTRACT_ITEM_PAYABLE_QTY
RENAME COLUMN INTERNAL_CONTRACT_REF_NO TO INTERNAL_CONTRACT_ITEM_REF_NO;


ALTER TABLE CIPQ_CONTRACT_ITEM_PAYABLE_QTY ADD (
  CONSTRAINT FK_CIPQ_PCI_ID 
 FOREIGN KEY (INTERNAL_CONTRACT_ITEM_REF_NO) 
 REFERENCES PCI_PHYSICAL_CONTRACT_ITEM (INTERNAL_CONTRACT_ITEM_REF_NO));

 
ALTER TABLE DIPQ_DELIVERY_ITEM_PAYABLE_QTY ADD (
  CONSTRAINT FK_DIPQ_PCDI_ID 
 FOREIGN KEY (PCDI_ID) 
 REFERENCES PCDI_PC_DELIVERY_ITEM (PCDI_ID));

drop table PQCA_PQ_CHEMICAL_ATTRIBUTES;

CREATE TABLE PQCA_PQ_CHEMICAL_ATTRIBUTES
(
  PQCA_ID              VARCHAR2(15 BYTE)        NOT NULL,
  ASM_ID      VARCHAR2(15 BYTE)       ,
  ELEMENT_ID           VARCHAR2(15 BYTE)        NOT NULL,
  MIN_VALUE            NUMBER(10,4),
  MAX_VALUE            NUMBER(10,4),
  UNIT_OF_MEASURE      VARCHAR2(15 BYTE),
  IS_ELEM_FOR_PRICING  CHAR(1 BYTE),
  TYPICAL              NUMBER(10,4),
  REJECTION            VARCHAR2(100 BYTE),
  IS_DEDUCTIBLE char(1),
  PAYABLE_PERCENTAGE number(25,10),
  VERSION              NUMBER(10),
  IS_ACTIVE            CHAR(1 BYTE)
);

CREATE UNIQUE INDEX PK_PQCA ON PQCA_PQ_CHEMICAL_ATTRIBUTES
(PQCA_ID);

ALTER TABLE PQCA_PQ_CHEMICAL_ATTRIBUTES ADD (
  CONSTRAINT PK_PQCA
 PRIMARY KEY
 (PQCA_ID));
 
 ALTER TABLE PQCA_PQ_CHEMICAL_ATTRIBUTES ADD (
  CONSTRAINT FK_PQCA_ASM_ID 
 FOREIGN KEY (ASM_ID) 
 REFERENCES ASM_ASSAY_SUBLOT_MAPPING (ASM_ID));

 
drop table PCEPCQD_EPC_QUALITY_DETAILS;
drop sequence SEQ_PCEPCQD;

CREATE TABLE PQD_PAYABLE_QUALITY_DETAILS
(
  PQD_ID  VARCHAR2(15 BYTE)                 NOT NULL,
  PCPCH_ID    VARCHAR2(15 BYTE)                 NOT NULL,
  PCPQ_ID     VARCHAR2(15 BYTE)                 NOT NULL,
  VERSION     NUMBER(10)                        NOT NULL,
  IS_ACTIVE   CHAR(1 BYTE)                      DEFAULT 'Y'                   NOT NULL
);

CREATE UNIQUE INDEX PK_PQD ON PQD_PAYABLE_QUALITY_DETAILS
(PQD_ID);

ALTER TABLE PQD_PAYABLE_QUALITY_DETAILS ADD (
  CONSTRAINT PK_PQD
 PRIMARY KEY
 (PQD_ID));
 
 ALTER TABLE PQD_PAYABLE_QUALITY_DETAILS ADD (
  CONSTRAINT FK_PQD_PCPCH_ID 
 FOREIGN KEY (PCPCH_ID) 
 REFERENCES PCPCH_PC_PAYBLE_CONTENT_HEADER (PCPCH_ID),
  CONSTRAINT FK_PQD_PCPQ_ID 
 FOREIGN KEY (PCPQ_ID) 
 REFERENCES PCPQ_PC_PRODUCT_QUALITY (PCPQ_ID));

   
CREATE SEQUENCE SEQ_PQD
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER; 

  


