ALTER TABLE DGRD_DELIVERED_GRD
 ADD (PROFIT_CENTER_ID  VARCHAR2(15 Char));
 
 ALTER TABLE DGRD_DELIVERED_GRD
 ADD (STRATEGY_ID  VARCHAR2(15 Char));


ALTER TABLE DGRDUL_DELIVERED_GRD_UL
 ADD (PROFIT_CENTER_ID  VARCHAR2(15 Char));
 
 ALTER TABLE DGRDUL_DELIVERED_GRD_UL
 ADD (STRATEGY_ID  VARCHAR2(15 Char));
 
ALTER TABLE ADGRD_ACTION_DGRD
 ADD (PROFIT_CENTER_ID  VARCHAR2(15 Char));
 
 ALTER TABLE ADGRD_ACTION_DGRD
 ADD (STRATEGY_ID  VARCHAR2(15 Char));

--FK REFERENCES FOR SALES SIDE

ALTER TABLE DGRD_DELIVERED_GRD ADD (
  CONSTRAINT FK_DGRD_PROFIT_CENTER_ID 
 FOREIGN KEY (PROFIT_CENTER_ID) 
 REFERENCES CPC_CORPORATE_PROFIT_CENTER (PROFIT_CENTER_ID),
  CONSTRAINT FK_DGRD_STRATEGY_ID 
 FOREIGN KEY (STRATEGY_ID) 
 REFERENCES CSS_CORPORATE_STRATEGY_SETUP (STRATEGY_ID));


 ALTER TABLE ADGRD_ACTION_DGRD ADD (
  CONSTRAINT FK_ADGRD_PROFIT_CENTER_ID 
 FOREIGN KEY (PROFIT_CENTER_ID) 
 REFERENCES CPC_CORPORATE_PROFIT_CENTER (PROFIT_CENTER_ID),
  CONSTRAINT FK_ADGRD_STRATEGY_ID 
 FOREIGN KEY (STRATEGY_ID) 
 REFERENCES CSS_CORPORATE_STRATEGY_SETUP (STRATEGY_ID));

--FK REFERENCES FOR PURCHASE SIDE 

 ALTER TABLE GRD_GOODS_RECORD_DETAIL ADD (
  CONSTRAINT FK_GRD_PROFIT_CENTER_ID 
 FOREIGN KEY (PROFIT_CENTER_ID) 
 REFERENCES CPC_CORPORATE_PROFIT_CENTER (PROFIT_CENTER_ID),
  CONSTRAINT FK_GRD_STRATEGY_ID 
 FOREIGN KEY (STRATEGY_ID) 
 REFERENCES CSS_CORPORATE_STRATEGY_SETUP (STRATEGY_ID));


 ALTER TABLE AGRD_ACTION_GRD ADD (
  CONSTRAINT FK_AGRD_PROFIT_CENTER_ID 
 FOREIGN KEY (PROFIT_CENTER_ID) 
 REFERENCES CPC_CORPORATE_PROFIT_CENTER (PROFIT_CENTER_ID),
  CONSTRAINT FK_AGRD_STRATEGY_ID 
 FOREIGN KEY (STRATEGY_ID) 
 REFERENCES CSS_CORPORATE_STRATEGY_SETUP (STRATEGY_ID));