Alter Table PPF_PHY_PAYABLE_FORMULA drop (PRODUCT_ID,QUALITY_ID) ;

alter table PPF_PHY_PAYABLE_FORMULA add (INTERNAL_FORMULA  VARCHAR2(4000 ));

ALTER TABLE PPF_PHY_PAYABLE_FORMULA RENAME COLUMN FORMULA_DESC TO EXTERNAL_FORMULA;
