
CREATE TABLE GPRH_GMR_PAYABLE_RULE_HEADER(GPRH_ID VARCHAR2(15),
INTERNAL_GMR_REF_NO VARCHAR2(15),PCDI_ID VARCHAR2(15),
PCPCH_ID VARCHAR2(15),VERSION NUMBER(10),IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL ,INTERNAL_ACTION_REF_NO VARCHAR2(15));

CREATE TABLE GPRHUL_GMR_PAYABLE_RULE_HEADER(GPRHUL_ID VARCHAR2(15),GPRH_ID VARCHAR2(15),ENTRY_TYPE VARCHAR2(15),
INTERNAL_GMR_REF_NO VARCHAR2(15),PCDI_ID VARCHAR2(15),
PCPCH_ID VARCHAR2(15),VERSION NUMBER(10),IS_ACTIVE CHAR(1) DEFAULT 'Y' NOT NULL,INTERNAL_ACTION_REF_NO VARCHAR2(15));



ALTER TABLE GPRH_GMR_PAYABLE_RULE_HEADER ADD (
CONSTRAINT PK_GPRH PRIMARY KEY(GPRH_ID),
  CONSTRAINT FK_GPRH_INTERNAL_GMR_REF_NO
 FOREIGN KEY (INTERNAL_GMR_REF_NO)
 REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO),
  CONSTRAINT FK_GPRH_PCDI_ID
 FOREIGN KEY (PCDI_ID)
 REFERENCES PCDI_PC_DELIVERY_ITEM (PCDI_ID),
  CONSTRAINT FK_GPRH_PCPCH_ID
 FOREIGN KEY (PCPCH_ID)
 REFERENCES PCPCH_PC_PAYBLE_CONTENT_HEADER (PCPCH_ID));
 
 ALTER TABLE GPRHUL_GMR_PAYABLE_RULE_HEADER ADD (
CONSTRAINT PK_GPRHUL PRIMARY KEY(GPRHUL_ID),
  CONSTRAINT FK_GPRHUL_INTERNAL_GMR_REF_NO
 FOREIGN KEY (INTERNAL_GMR_REF_NO)
 REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO),
  CONSTRAINT FK_GPRHUL_PCDI_ID
 FOREIGN KEY (PCDI_ID)
 REFERENCES PCDI_PC_DELIVERY_ITEM (PCDI_ID),
  CONSTRAINT FK_GPRHUL_PCPCH_ID
 FOREIGN KEY (PCPCH_ID)
 REFERENCES PCPCH_PC_PAYBLE_CONTENT_HEADER (PCPCH_ID));
 
 
 CREATE SEQUENCE SEQ_GPRH
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
  
  
CREATE SEQUENCE SEQ_GPRHUL
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  