ALTER TABLE ASH_ASSAY_HEADER
 DROP PRIMARY KEY CASCADE;
DROP TABLE ASH_ASSAY_HEADER CASCADE CONSTRAINTS;

CREATE TABLE ASH_ASSAY_HEADER
(
  ASH_ID                    VARCHAR2(15 CHAR)   NOT NULL,
  ASSAY_REF_NO              VARCHAR2(20 CHAR),
  SAMPLE_DATE               TIMESTAMP(6),
  ACTIVITY_DATE             TIMESTAMP(6),
  ASSAY_TYPE                VARCHAR2(25 BYTE),
  USE_FOR_FINALIZATION      CHAR(1 BYTE),
  CP_ASSAY_REF_NO           VARCHAR2(20 CHAR),
  ASSAYER                   VARCHAR2(15 BYTE),
  SAMPLE_COLLECTED_AT       VARCHAR2(25 CHAR),
  SAMPLE_REF_NO             VARCHAR2(20 CHAR),
  VERSION                   NUMBER(10),
  IS_ACTIVE                 CHAR(1 BYTE),
  NET_WEIGHT                NUMBER(10),
  NET_WEIGHT_UNIT           VARCHAR2(15 BYTE),
  INTERNAL_CONTRACT_REF_NO  VARCHAR2(15 CHAR),
  LOT_NO                    VARCHAR2(20 BYTE),
  INTERNAL_GRD_REF_NO       VARCHAR2(15 BYTE),
  INTERNAL_GMR_REF_NO       VARCHAR2(15 BYTE),
  ACTION_NO                 NUMBER(2),
  PURCHASE_SALES            VARCHAR2(10 BYTE)
);



CREATE UNIQUE INDEX ASH_ASSAY_HEADER_PK ON ASH_ASSAY_HEADER
(ASH_ID);


ALTER TABLE ASH_ASSAY_HEADER ADD (
  CONSTRAINT ASH_ASSAY_HEADER_PK
 PRIMARY KEY
 (ASH_ID));



ALTER TABLE ASM_ASSAY_SUBLOT_MAPPING
 DROP PRIMARY KEY CASCADE;
DROP TABLE ASM_ASSAY_SUBLOT_MAPPING CASCADE CONSTRAINTS;

CREATE TABLE ASM_ASSAY_SUBLOT_MAPPING
(
  ASH_ID           VARCHAR2(15 CHAR),
  ASM_ID           VARCHAR2(15 CHAR)            NOT NULL,
  SUBLOT_REF_NO    VARCHAR2(15 BYTE),
  SUB_LOT_NO       VARCHAR2(20 BYTE),
  IS_ACTIVE        CHAR(1 BYTE),
  VERSION          NUMBER(10),
  NET_WEIGHT       NUMBER(10),
  NET_WEIGHT_UNIT  VARCHAR2(15 BYTE)
);


CREATE UNIQUE INDEX ASM_ASSAY_SUBLOT_MAPPING_PK ON ASM_ASSAY_SUBLOT_MAPPING
(ASM_ID);


ALTER TABLE ASM_ASSAY_SUBLOT_MAPPING ADD (
  CONSTRAINT ASM_ASSAY_SUBLOT_MAPPING_PK
 PRIMARY KEY
 (ASM_ID));

ALTER TABLE ASM_ASSAY_SUBLOT_MAPPING ADD (
  FOREIGN KEY (ASH_ID) 
 REFERENCES ASH_ASSAY_HEADER (ASH_ID));

