ALTER TABLE GRD_GOODS_RECORD_DETAIL
 ADD (PQPA_PHY_ATTRIBUTE_GROUP_NO  VARCHAR2(15));
 
ALTER TABLE AGRD_ACTION_GRD
 ADD (PQPA_PHY_ATTRIBUTE_GROUP_NO  VARCHAR2(15));
 
ALTER TABLE GRDUL_GOODS_RECORD_DETAIL_UL
 ADD (PQPA_PHY_ATTRIBUTE_GROUP_NO  VARCHAR2(15));
