CREATE TABLE DITH_DI_TREATMENT_HEADER
(
  DITH_ID  VARCHAR2(15)                  NOT NULL,
  PCDI_ID    VARCHAR2(15)                  NOT NULL,
  PCTH_ID   VARCHAR2(15)                  NOT NULL,
  VERSION    NUMBER(10)                         NOT NULL,
  IS_ACTIVE  CHAR(1)                       DEFAULT 'Y'                   NOT NULL
 );
 
 
 ALTER TABLE DITH_DI_TREATMENT_HEADER ADD (
  CONSTRAINT PK_DITH
 PRIMARY KEY
 (DITH_ID));

ALTER TABLE DITH_DI_TREATMENT_HEADER ADD (
  CONSTRAINT FK_DITH_PCTH_ID
 FOREIGN KEY (PCTH_ID) 
 REFERENCES PCTH_PC_TREATMENT_HEADER (PCTH_ID),
  CONSTRAINT FK_DITH_PCDI_ID 
 FOREIGN KEY (PCDI_ID) 
 REFERENCES PCDI_PC_DELIVERY_ITEM (PCDI_ID));
 
 
 CREATE TABLE DIRH_DI_REFINING_HEADER
(
  DIRH_ID  VARCHAR2(15)                  NOT NULL,
  PCDI_ID    VARCHAR2(15)                  NOT NULL,
  PCRH_ID   VARCHAR2(15)                  NOT NULL,
  VERSION    NUMBER(10)                         NOT NULL,
  IS_ACTIVE  CHAR(1)                       DEFAULT 'Y'                   NOT NULL
 );
 
 
 ALTER TABLE DIRH_DI_REFINING_HEADER ADD (
  CONSTRAINT PK_DIRH
 PRIMARY KEY
 (DIRH_ID));

ALTER TABLE DIRH_DI_REFINING_HEADER ADD (
  CONSTRAINT FK_DIRH_PCRH_ID
 FOREIGN KEY (PCRH_ID) 
 REFERENCES PCRH_PC_REFINING_HEADER (PCRH_ID),
  CONSTRAINT FK_DIRH_PCDI_ID 
 FOREIGN KEY (PCDI_ID) 
 REFERENCES PCDI_PC_DELIVERY_ITEM (PCDI_ID));
 
 
 
 CREATE TABLE DIPH_DI_PENALTY_HEADER
(
  DIPH_ID  VARCHAR2(15)                  NOT NULL,
  PCDI_ID    VARCHAR2(15)                  NOT NULL,
  PCAPH_ID   VARCHAR2(15)                  NOT NULL,
  VERSION    NUMBER(10)                         NOT NULL,
  IS_ACTIVE  CHAR(1)                       DEFAULT 'Y'                   NOT NULL
 );
 
 
 ALTER TABLE DIPH_DI_PENALTY_HEADER ADD (
  CONSTRAINT PK_DIPH
 PRIMARY KEY
 (DIPH_ID));

ALTER TABLE DIPH_DI_PENALTY_HEADER ADD (
  CONSTRAINT FK_DIPH_PCAPH_ID
 FOREIGN KEY (PCAPH_ID) 
 REFERENCES PCAPH_PC_ATTR_PENALTY_HEADER (PCAPH_ID),
  CONSTRAINT FK_DIPH_PCDI_ID 
 FOREIGN KEY (PCDI_ID) 
 REFERENCES PCDI_PC_DELIVERY_ITEM (PCDI_ID));
 
 
 CREATE SEQUENCE SEQ_DIRH
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE SEQ_DITH
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;


CREATE SEQUENCE SEQ_DIPH
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
