drop table MDCD_M2M_DED_CHARGE_DETAILS;

CREATE TABLE MDCD_M2M_DED_CHARGE_DETAILS
(
  INTERNAL_MDCD_REF_NO  VARCHAR2(15 BYTE)       NOT NULL,
  CORPORATE_ID          VARCHAR2(15 BYTE)       NOT NULL,
  AS_OF_DATE            DATE                    NOT NULL,
  PRODUCT_ID            VARCHAR2(15 BYTE)       NOT NULL,
  QUALITY_ID            VARCHAR2(15 BYTE)       NOT NULL,
  VALUATION_REGION_ID   VARCHAR2(15 BYTE)       NOT NULL,
  CHARGE_TYPE           VARCHAR2(17 BYTE)       NOT NULL,
  INTERNAL_ELEMENT_ID   VARCHAR2(15 BYTE),
  VALUATION_CURVE_ID    VARCHAR2(15 BYTE),
  CREATED_BY          VARCHAR2(15 BYTE)        ,
  CREATED_DATE        TIMESTAMP(6)              DEFAULT SYSTIMESTAMP
 
);

CREATE UNIQUE INDEX PK_MDCD_ID ON MDCD_M2M_DED_CHARGE_DETAILS
(INTERNAL_MDCD_REF_NO);


ALTER TABLE MDCD_M2M_DED_CHARGE_DETAILS ADD (
  CONSTRAINT PK_MDCD_ID
 PRIMARY KEY
 (INTERNAL_MDCD_REF_NO));
 
 
CREATE TABLE MDCBM_DED_CHARGES_BY_MONTH
(
  MDCBM_ID        VARCHAR2(15 BYTE)             NOT NULL,
  MDCD_ID         VARCHAR2(15 BYTE)             NOT NULL,
  CHARGE_VALUE    NUMBER(25,10)                 NOT NULL,
  CHARGE_UNIT_ID  VARCHAR2(15 BYTE)             NOT NULL,
  CALENDAR_MONTH  VARCHAR2(15 BYTE),
  CALENDAR_YEAR   VARCHAR2(15 BYTE),
  IS_BEYOND       CHAR(1 BYTE),
  BEYOND_MONTH    VARCHAR2(15 BYTE),
  BEYOND_YEAR     VARCHAR2(15 BYTE)
);


CREATE UNIQUE INDEX PK_MDCBM_ID ON MDCBM_DED_CHARGES_BY_MONTH
(MDCBM_ID);


ALTER TABLE MDCBM_DED_CHARGES_BY_MONTH ADD (
  CONSTRAINT PK_MDCBM_ID
 PRIMARY KEY
 (MDCBM_ID));
 
 
 CREATE SEQUENCE SEQ_MDCD
  START WITH 1
  MAXVALUE 999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;
CREATE SEQUENCE SEQ_MDCBM
  START WITH 1
  MAXVALUE 999999999999999999999
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;

SET DEFINE OFF;
Insert into IRC_INTERNAL_REF_NO_CONFIG
   (INTERNAL_REF_NO_KEY, PREFIX, SEQ_NAME)
 Values
   ('PK_MDCBM', 'MDCBM', 'SEQ_MDCBM');
Insert into IRC_INTERNAL_REF_NO_CONFIG
   (INTERNAL_REF_NO_KEY, PREFIX, SEQ_NAME)
 Values
   ('PK_MDCD', 'MDCD', 'SEQ_MDCD');
COMMIT;
