CREATE TABLE ECS_ELEMENT_COST_STORE
(
  ELEMENT_COST_ID                 VARCHAR2(15 CHAR) PRIMARY KEY ,
  INTERNAL_COST_ID                VARCHAR2(15 CHAR) NOT NULL,
  ELEMENT_ID                      VARCHAR2(15 CHAR) NOT NULL,
  PAYABLE_QTY                     NUMBER(25,10),
  PAYABLE_QTY_IN_BASE_QTY_UNIT    NUMBER(25,10),
  QTY_UNIT_ID                     VARCHAR2(15 CHAR),
  COST_VALUE                      NUMBER(25,10),
  RATE_PRICE_UNIT_ID              VARCHAR2(15 CHAR),
  TRANSACTION_AMT                 NUMBER(25,10),
  TRANSACTION_AMT_CUR_ID          VARCHAR2(15 CHAR),
  FX_TO_BASE                      NUMBER(25,10),
  BASE_AMT                        NUMBER(25,10),
  BASE_AMT_CUR_ID                 VARCHAR2(15 CHAR),
  COST_IN_BASE_PRICE_UNIT_ID      NUMBER(25,10),
  COST_IN_TRANSACT_PRICE_UNIT_ID  NUMBER(25,10),
  VERSION                         NUMBER(10),
  IS_DELETED                      CHAR(1 CHAR)
);

ALTER TABLE ECS_ELEMENT_COST_STORE
 ADD CONSTRAINT FK_CS_ID 
 FOREIGN KEY (INTERNAL_COST_ID) 
 REFERENCES CS_COST_STORE (INTERNAL_COST_ID);





CREATE SEQUENCE SEQ_ECS
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;