ALTER TABLE DGRD_DELIVERED_GRD ADD
(
PCDI_ID                         VARCHAR2(15),
CONSTRAINT FK_DGRD_PCDI_ID FOREIGN KEY (PCDI_ID) REFERENCES PCDI_PC_DELIVERY_ITEM (PCDI_ID)
);

ALTER TABLE DGRDUL_DELIVERED_GRD_UL ADD
(
PCDI_ID                         VARCHAR2(15)
);

ALTER TABLE ADGRD_ACTION_DGRD ADD
(
PCDI_ID                         VARCHAR2(15),
CONSTRAINT FK_ADGRD_PCDI_ID FOREIGN KEY (PCDI_ID) REFERENCES PCDI_PC_DELIVERY_ITEM (PCDI_ID)
);


ALTER TABLE PRRQS_PRR_QTY_STATUS ADD
(
ASSAY_CONTENT           NUMBER(25,10)
);