
CREATE TABLE SFP_SMELTER_FEEDING_POINT
(
FEEDING_POINT_ID       VARCHAR2(15)  NOT NULL,
FEEDING_POINT_NAME     VARCHAR2(30) NOT NULL,
SMELTER_CP_ID          VARCHAR2(20) NOT NULL,
IS_ACTIVE              CHAR(1)      DEFAULT 'Y'                   NOT NULL,
CONSTRAINT CHK_SFP_IS_ACTIVE CHECK ( IS_ACTIVE IN ('Y', 'N')),
CONSTRAINT FK_SFP_SMELTER_CP_ID FOREIGN KEY (SMELTER_CP_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT PK_SFP PRIMARY KEY (FEEDING_POINT_ID)
);





ALTER TABLE WRD_WAREHOUSE_RECEIPT_DETAIL ADD
(
FEEDING_POINT_ID VARCHAR2(15),
CONSTRAINT FK_WRD_FEEDING_POINT_ID FOREIGN KEY (FEEDING_POINT_ID) REFERENCES SFP_SMELTER_FEEDING_POINT (FEEDING_POINT_ID)
);

ALTER TABLE WRDUL_WAREHOUSE_RECEIPT_UL ADD
(
FEEDING_POINT_ID VARCHAR2(15)
);