CREATE TABLE MCC_MISCELLANEOUS_COMM_CHARGES
(
  MCC_ID 	     VARCHAR2(15) 		NOT NULL,
  CP_ID              VARCHAR2(15 CHAR)          NOT NULL,
  QUALITY_ID         VARCHAR2(15 CHAR)          NOT NULL,
  PRODUCT_ID         VARCHAR2(15 CHAR)          NOT NULL,
  CHARGE_ID          VARCHAR2(15 CHAR)          NOT NULL,
  CHARGE_NAME        VARCHAR2(50 CHAR)          NOT NULL,
  CHARGE_TYPE        VARCHAR2(30 CHAR)          NOT NULL,
  CHARGE             NUMBER(38,18)              NOT NULL,
  CHARGE_CUR_ID      VARCHAR2(15 CHAR)          NOT NULL,
  IS_ACTIVE          CHAR(1 CHAR)               DEFAULT 'Y',
  TO_DATE            DATE,
  FROM_DATE          DATE,
  QTY_UNIT_ID        VARCHAR2(10 CHAR),
  WEIGHT_RATE_BASIS  VARCHAR2(30 CHAR),
  FX_RATE            VARCHAR2(30 CHAR)
);
 
CREATE UNIQUE INDEX MCC_PK ON MCC_MISCELLANEOUS_COMM_CHARGES (MCC_ID);

ALTER TABLE MCC_MISCELLANEOUS_COMM_CHARGES ADD (
  CONSTRAINT FK_MCC_CHARGE_CUR_ID 
 FOREIGN KEY (CHARGE_CUR_ID) 
 REFERENCES CM_CURRENCY_MASTER (CUR_ID),
  CONSTRAINT FK_MCC_QUALITY_ID 
 FOREIGN KEY (QUALITY_ID) 
 REFERENCES QAT_QUALITY_ATTRIBUTES (QUALITY_ID),
  CONSTRAINT FK_MCC_CP_ID 
 FOREIGN KEY (CP_ID) 
 REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
  CONSTRAINT FK_MCC_PRODUCT_ID 
 FOREIGN KEY (PRODUCT_ID) 
 REFERENCES PDM_PRODUCTMASTER (PRODUCT_ID),
  CONSTRAINT FK_MCC_QTY_UNIT_ID 
 FOREIGN KEY (QTY_UNIT_ID) 
 REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID));

CREATE SEQUENCE SEQ_MCC
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;