ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(FEED_QTY VARCHAR2(15 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(PAYABLE_QTY_DISPLAY VARCHAR2(15 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(FREE_METAL_QTY_DISPLAY VARCHAR2(15 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(TC_AMOUNT_DISPLAY VARCHAR2(100 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(RC_AMOUNT_DISPLAY VARCHAR2(100 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(PENALTY_AMOUNT_DISPLAY VARCHAR2(100 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(FREE_METAL_AMOUNT_DISPLAY VARCHAR2(100 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(TOTAL_INVOICE_AMOUNT VARCHAR2(15 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(PARENT_INVOICE_AMOUNT VARCHAR2(15 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(VAT_AMOUNT_IN_INVOICE_CURRENCY VARCHAR2(15 CHAR));


ALTER TABLE IUD_INVOICE_UTILITY_DETAIL
MODIFY(FX_RATE VARCHAR2(15 CHAR));


