ALTER TABLE IS_CHILD_SI_D
 ADD (COST_DESCRIPTION  VARCHAR2(1000 CHAR));

 ALTER TABLE CS_COST_STORE
 ADD (COST_DESCRIPTION  VARCHAR2(1000 CHAR));


CREATE TABLE DCS_DRAFT_COST_STORE
(
  INTERNAL_COST_ID        VARCHAR2(30 CHAR),
  INT_ACTION_REF_NO       VARCHAR2(30 CHAR),
  COST_COMPONENT_ID       VARCHAR2(30 CHAR),
  COST_DESCRIPTION        VARCHAR2(1000 CHAR),
  INV_AMT_IN_INV_CUR      NUMBER(25,10),
  INVOICE_CURRENCY        VARCHAR2(30 CHAR),
  FX_TO_ACCRUAL           NUMBER(25,10),
  INV_AMT_IN_ACCRUAL_CUR  NUMBER(25,10),
  FX_TO_BASE              NUMBER(25,10),
  INV_AMT_IN_BASE_CUR     NUMBER(25,10),
  IS_ACTIVE               CHAR(1)               DEFAULT 'Y'
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE DCS_DRAFT_COST_STORE ADD (
  CONSTRAINT DRAFT_COST_STORE_PK
 PRIMARY KEY
 (INTERNAL_COST_ID));

ALTER TABLE DCS_DRAFT_COST_STORE
 ADD (ACCRUAL_CUR_ID  VARCHAR2(30 CHAR));

ALTER TABLE DCS_DRAFT_COST_STORE
 ADD (BASE_CUR_ID  VARCHAR2(30 CHAR));


CREATE SEQUENCE SEQ_DCS
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 100000000000000000000000000
NOCACHE 
NOCYCLE 
NOORDER 
