CREATE TABLE API_D
(
  INTERNAL_INVOICE_REF_NO         VARCHAR2(30),
  INTERNAL_DOC_REF_NO             VARCHAR2(30),
  CP_NAME                         VARCHAR2(100),
  BUYER                           VARCHAR2(100),
  CP_ITEM_STOCK_REF_NO            VARCHAR2(30),
  SELF_ITEM_STOCK_REF_NO          VARCHAR2(30),
  INCO_TERM_LOCATION              VARCHAR2(100),
  CONTRACT_REF_NO                 VARCHAR2(30),
  CP_CONTRACT_REF_NO              VARCHAR2(30),
  CONTRACT_DATE                   DATE,
  PRODUCT                         VARCHAR2(30),
  NOTIFY_PARTY                    VARCHAR2(500),
  INVOICE_QUANTITY                VARCHAR2(30),
  INVOICE_QUANTITY_UNIT           VARCHAR2(30),
  QUALITY                         VARCHAR2(30),
  PAYMENT_TERM                    VARCHAR2(30),
  PAYMENT_DUE_DATE                DATE,
  INVOICE_ISSUE_DATE              DATE,
  INVOICE_AMOUNT_UNIT             VARCHAR2(30),
  INVOICE_AMOUNT                  VARCHAR2(30),
  INVOICE_REF_NO                  VARCHAR2(30)
)

ALTER TABLE API_D
 ADD (CONTRACT_TYPE  VARCHAR2(30));

ALTER TABLE API_D
 ADD (INVOICE_STATUS  VARCHAR2(30));

ALTER TABLE API_D
 ADD (SALES_PURCHASE  VARCHAR2(30));