CREATE TABLE CLED_CREDIT_LIMIT_EXP_DETAIL
(
  CLED_ID                 VARCHAR2(30 CHAR),
  INTERNAL_ACTION_REF_NO  VARCHAR2(30 CHAR),
  ACTIVITY              VARCHAR2(30 CHAR),
  ACTIVITY_REF_NO       VARCHAR2(30 CHAR),
  ACTIVITY_DATE         DATE,
  LIMIT_CONSUMED   NUMBER(25,10),
  REMAINING_EXP_LIMIT    NUMBER(25,10),
  CP_CURRENT_EXP   NUMBER(25,10),
  ALERT_REQUIRED        CHAR (1 Char),
  INTERNAL_GMR_REF_NO   VARCHAR2(30 CHAR),
  IS_ACTIVE             CHAR (1 Char),
  COUNTER_PARTY_ID      VARCHAR2(30 CHAR),
  UNIT_ID               VARCHAR2(30 CHAR),
  VERSION                 NUMBER(10),
  CONSTRAINT cled_id_pk PRIMARY KEY (CLED_ID)
);

CREATE SEQUENCE SEQ_CLED
  START WITH 209
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  NOCACHE
  NOORDER;