ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD 
(
CONSTRAINT FK_GMR_FIRST_ACTION_REF_NO FOREIGN KEY (GMR_FIRST_INT_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO),
CONSTRAINT FK_GMR_LATEST_ACTION_ID FOREIGN KEY (GMR_LATEST_ACTION_ACTION_ID) REFERENCES AXM_ACTION_MASTER (ACTION_ID),

CONSTRAINT FK_GMR_CORPORATE_ID FOREIGN KEY (CORPORATE_ID) REFERENCES AK_CORPORATE (CORPORATE_ID),
CONSTRAINT FK_GMR_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AK_CORPORATE_USER (USER_ID),
CONSTRAINT FK_GMR_QTY_UNIT_ID FOREIGN KEY (QTY_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID),

CONSTRAINT FK_GMR_ORIGIN_COUNTRY_ID FOREIGN KEY (ORIGIN_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_GMR_ORIGIN_CITY_ID FOREIGN KEY (ORIGIN_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),

CONSTRAINT FK_GMR_DESTINATION_COUNTRY_ID FOREIGN KEY (DESTINATION_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_GMR_DESTINATION_CITY_ID FOREIGN KEY (DESTINATION_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),

CONSTRAINT FK_GMR_LOADING_COUNTRY_ID FOREIGN KEY (LOADING_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_GMR_LOADING_PORT_ID FOREIGN KEY (LOADING_PORT_ID) REFERENCES PMT_PORTMASTER (PORT_ID),

CONSTRAINT FK_GMR_DISCHARGE_COUNTRY_ID FOREIGN KEY (DISCHARGE_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_GMR_DISCHARGE_PORT_ID FOREIGN KEY (DISCHARGE_PORT_ID) REFERENCES PMT_PORTMASTER (PORT_ID),

CONSTRAINT FK_GMR_TRANS_COUNTRY_ID FOREIGN KEY (TRANS_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_GMR_TRANS_PORT_ID FOREIGN KEY (TRANS_PORT_ID) REFERENCES PMT_PORTMASTER (PORT_ID),

CONSTRAINT FK_GMR_WAREHOUSE_PROFILE_ID FOREIGN KEY (WAREHOUSE_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_GMR_SHIP_LINE_PROFILE_ID FOREIGN KEY (SHIPPING_LINE_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_GMR_CONTROLLER_PROFILE_ID FOREIGN KEY (CONTROLLER_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),

CONSTRAINT FK_GMR_INTERNAL_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO),

CONSTRAINT FK_GMR_LOADING_STATE_ID FOREIGN KEY (LOADING_STATE_ID) REFERENCES SM_STATE_MASTER (STATE_ID),
CONSTRAINT FK_GMR_LOADING_CITY_ID FOREIGN KEY (LOADING_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),

CONSTRAINT FK_GMR_TRANS_STATE_ID FOREIGN KEY (TRANS_STATE_ID) REFERENCES SM_STATE_MASTER (STATE_ID),
CONSTRAINT FK_GMR_TRANS_CITY_ID FOREIGN KEY (TRANS_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),

CONSTRAINT FK_GMR_DISCHARGE_STATE_ID FOREIGN KEY (DISCHARGE_STATE_ID) REFERENCES SM_STATE_MASTER (STATE_ID),
CONSTRAINT FK_GMR_DISCHARGE_CITY_ID FOREIGN KEY (DISCHARGE_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),

CONSTRAINT FK_GMR_POR_COUNTRY_ID FOREIGN KEY (PLACE_OF_RECEIPT_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_GMR_POR_STATE_ID FOREIGN KEY (PLACE_OF_RECEIPT_STATE_ID) REFERENCES SM_STATE_MASTER (STATE_ID),
CONSTRAINT FK_GMR_POR_CITY_ID FOREIGN KEY (PLACE_OF_RECEIPT_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),

CONSTRAINT FK_GMR_POD_COUNTRY_ID FOREIGN KEY (PLACE_OF_DELIVERY_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_GMR_POD_STATE_ID FOREIGN KEY (PLACE_OF_DELIVERY_STATE_ID) REFERENCES SM_STATE_MASTER (STATE_ID),
CONSTRAINT FK_GMR_POD_CITY_ID FOREIGN KEY (PLACE_OF_DELIVERY_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),

CONSTRAINT FK_GMR_POOL_ID FOREIGN KEY (POOL_ID) REFERENCES PM_POOL_MASTER (POOL_ID)
);

ALTER TABLE GMRUL_GMR_UL ADD 
(
CONSTRAINT FK_GMRUL_INT_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO)
);

ALTER TABLE AGMR_ACTION_GMR ADD 
(
CONSTRAINT FK_AGMR_FIRST_ACTION_REF_NO FOREIGN KEY (GMR_FIRST_INT_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO),
CONSTRAINT FK_AGMR_LATEST_ACTION_ID FOREIGN KEY (GMR_LATEST_ACTION_ACTION_ID) REFERENCES AXM_ACTION_MASTER (ACTION_ID),

CONSTRAINT FK_AGMR_CORPORATE_ID FOREIGN KEY (CORPORATE_ID) REFERENCES AK_CORPORATE (CORPORATE_ID),
CONSTRAINT FK_AGMR_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AK_CORPORATE_USER (USER_ID),
CONSTRAINT FK_AGMR_QTY_UNIT_ID FOREIGN KEY (QTY_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID),

CONSTRAINT FK_AGMR_ORIGIN_COUNTRY_ID FOREIGN KEY (ORIGIN_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_AGMR_ORIGIN_CITY_ID FOREIGN KEY (ORIGIN_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),

CONSTRAINT FK_AGMR_DEST_COUNTRY_ID FOREIGN KEY (DESTINATION_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_AGMR_DESTINATION_CITY_ID FOREIGN KEY (DESTINATION_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),

CONSTRAINT FK_AGMR_LOADING_COUNTRY_ID FOREIGN KEY (LOADING_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_AGMR_LOADING_PORT_ID FOREIGN KEY (LOADING_PORT_ID) REFERENCES PMT_PORTMASTER (PORT_ID),

CONSTRAINT FK_AGMR_DISCHARGE_COUNTRY_ID FOREIGN KEY (DISCHARGE_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_AGMR_DISCHARGE_PORT_ID FOREIGN KEY (DISCHARGE_PORT_ID) REFERENCES PMT_PORTMASTER (PORT_ID),

CONSTRAINT FK_AGMR_TRANS_COUNTRY_ID FOREIGN KEY (TRANS_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_AGMR_TRANS_PORT_ID FOREIGN KEY (TRANS_PORT_ID) REFERENCES PMT_PORTMASTER (PORT_ID),

CONSTRAINT FK_AGMR_WAREHOUSE_PROFILE_ID FOREIGN KEY (WAREHOUSE_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_AGMR_SHIP_LINE_PROFILE_ID FOREIGN KEY (SHIPPING_LINE_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_AGMR_CONTROLLER_PROFILE_ID FOREIGN KEY (CONTROLLER_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID)
);

ALTER TABLE SD_SHIPMENT_DETAIL ADD 
(
CONSTRAINT FK_SD_GMR_REF_NO_ACTION_NO FOREIGN KEY(INTERNAL_GMR_REF_NO,ACTION_NO) REFERENCES AGMR_ACTION_GMR(INTERNAL_GMR_REF_NO, ACTION_NO),
CONSTRAINT FK_SD_CONTROLLER_PROFILE_ID FOREIGN KEY (CONTROLLER_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_SD_SENDER_ID FOREIGN KEY (SENDER_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID), 
CONSTRAINT FK_SD_CONSIGNEE_ID FOREIGN KEY (CONSIGNEE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID), 
CONSTRAINT FK_SD_NOTIFY_PARTY_ID FOREIGN KEY (NOTIFY_PARTY_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID), 
CONSTRAINT FK_SD_FORWARDING_AGENT_ID FOREIGN KEY (FORWARDING_AGENT_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),

CONSTRAINT FK_SD_POA_COUNTRY_ID FOREIGN KEY (PORT_OF_ARRIVAL_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_SD_POA_STATE_ID FOREIGN KEY (PORT_OF_ARRIVAL_STATE_ID) REFERENCES SM_STATE_MASTER (STATE_ID),
CONSTRAINT FK_SD_POA_CITY_ID FOREIGN KEY (PORT_OF_ARRIVAL_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID)
);

ALTER TABLE SDUL_SHIPMENT_DETAIL_UL ADD 
(
CONSTRAINT FK_SDUL_INTERNAL_GMR_REF_NO FOREIGN KEY (INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO),
CONSTRAINT FK_SDUL_INT_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO)
);

ALTER TABLE VD_VOYAGE_DETAIL ADD 
(
CONSTRAINT FK_VD_GMR_REF_NO_ACTION_NO FOREIGN KEY(INTERNAL_GMR_REF_NO,ACTION_NO) REFERENCES AGMR_ACTION_GMR(INTERNAL_GMR_REF_NO, ACTION_NO),
CONSTRAINT FK_VD_SHIP_LINE_PROFILE_ID FOREIGN KEY (SHIPPING_LINE_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_VD_LOADING_PORT_ID FOREIGN KEY (LOADING_PORT_ID) REFERENCES PMT_PORTMASTER (PORT_ID), 
CONSTRAINT FK_VD_DISCHARGE_PORT_ID FOREIGN KEY (DISCHARGE_PORT_ID) REFERENCES PMT_PORTMASTER (PORT_ID), 
CONSTRAINT FK_VD_TRANS_SHIPMENT_PORT_ID FOREIGN KEY (TRANS_SHIPMENT_PORT_ID) REFERENCES PMT_PORTMASTER (PORT_ID), 

CONSTRAINT FK_VD_TRANS_SHIP_COUNTRY_ID FOREIGN KEY (TRANS_SHIPMENT_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_VD_TRANS_SHIPMENT_STATE_ID FOREIGN KEY (TRANS_SHIPMENT_STATE_ID) REFERENCES SM_STATE_MASTER (STATE_ID),
CONSTRAINT FK_VD_TRANS_SHIPMENT_CITY_ID FOREIGN KEY (TRANS_SHIPMENT_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),

CONSTRAINT FK_VD_DESTINATION_COUNTRY_ID FOREIGN KEY (DESTINATION_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_VD_DESTINATION_CITY_ID FOREIGN KEY (DESTINATION_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),

CONSTRAINT FK_VD_ORIGINATION_COUNTRY_ID FOREIGN KEY (ORIGINATION_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_VD_ORIGINATION_CITY_ID FOREIGN KEY (ORIGINATION_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),

CONSTRAINT FK_VD_SHIP_AGENT_PROFILE_ID FOREIGN KEY (SHIPPING_AGENT_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_VD_VOYAGE_QTY_UNIT_ID FOREIGN KEY (VOYAGE_QTY_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID),

CONSTRAINT FK_VD_LOADING_COUNTRY_ID FOREIGN KEY (LOADING_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_VD_LOADING_STATE_ID FOREIGN KEY (LOADING_STATE_ID) REFERENCES SM_STATE_MASTER (STATE_ID),
CONSTRAINT FK_VD_LOADING_CITY_ID FOREIGN KEY (LOADING_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),

CONSTRAINT FK_VD_DISCHARGE_COUNTRY_ID FOREIGN KEY (DISCHARGE_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_VD_DISCHARGE_STATE_ID FOREIGN KEY (DISCHARGE_STATE_ID) REFERENCES SM_STATE_MASTER (STATE_ID),
CONSTRAINT FK_VD_DISCHARGE_CITY_ID FOREIGN KEY (DISCHARGE_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),

CONSTRAINT FK_VD_POR_COUNTRY_ID FOREIGN KEY (PLACE_OF_RECEIPT_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_VD_POR_STATE_ID FOREIGN KEY (PLACE_OF_RECEIPT_STATE_ID) REFERENCES SM_STATE_MASTER (STATE_ID),
CONSTRAINT FK_VD_POR_CITY_ID FOREIGN KEY (PLACE_OF_RECEIPT_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),

CONSTRAINT FK_VD_POD_COUNTRY_ID FOREIGN KEY (PLACE_OF_DELIVERY_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_VD_POD_STATE_ID FOREIGN KEY (PLACE_OF_DELIVERY_STATE_ID) REFERENCES SM_STATE_MASTER (STATE_ID),
CONSTRAINT FK_VD_POD_CITY_ID FOREIGN KEY (PLACE_OF_DELIVERY_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),

CONSTRAINT FK_VD_CUSTOMS_CUR_ID FOREIGN KEY (DECLARED_VALUE_CUSTOMS_CUR_ID) REFERENCES CM_CURRENCY_MASTER (CUR_ID)
);

ALTER TABLE VDUL_VOYAGE_DETAIL_UL ADD 
(
CONSTRAINT FK_VDUL_INTERNAL_GMR_REF_NO FOREIGN KEY (INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO),
CONSTRAINT FK_VDUL_INT_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO)
);


ALTER TABLE VAD_VOYAGE_ALLOCATION_DETAIL ADD 
(
CONSTRAINT FK_VAD_INTERNAL_GMR_REF_NO FOREIGN KEY (INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO)
);

ALTER TABLE WRD_WAREHOUSE_RECEIPT_DETAIL ADD 
(
CONSTRAINT FK_WRD_GMR_REF_NO_ACTION_NO FOREIGN KEY(INTERNAL_GMR_REF_NO,ACTION_NO) REFERENCES AGMR_ACTION_GMR(INTERNAL_GMR_REF_NO, ACTION_NO),
CONSTRAINT FK_WRD_WAREHOUSE_PROFILE_ID FOREIGN KEY (WAREHOUSE_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),

CONSTRAINT FK_WRD_SENDER_ID FOREIGN KEY (SENDER_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID), 

CONSTRAINT FK_WRD_CONSIGNEE_ID FOREIGN KEY (CONSIGNEE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID), 

CONSTRAINT FK_WRD_TO_WAREHOUSE_ID FOREIGN KEY (TO_WAREHOUSE_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_WRD_TO_SHED_ID FOREIGN KEY (TO_SHED_ID) REFERENCES SLD_STORAGE_LOCATION_DETAIL (STORAGE_LOC_ID)
);

ALTER TABLE WRDUL_WAREHOUSE_RECEIPT_UL ADD 
(
CONSTRAINT FK_WRDUL_INTERNAL_GMR_REF_NO FOREIGN KEY (INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO),
CONSTRAINT FK_WRDUL_INT_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO)
);

ALTER TABLE SAD_SHIPMENT_ADVICE ADD 
(
CONSTRAINT FK_SAD_GMR_REF_NO_ACTION_NO FOREIGN KEY(INTERNAL_GMR_REF_NO,ACTION_NO) REFERENCES AGMR_ACTION_GMR(INTERNAL_GMR_REF_NO, ACTION_NO),
CONSTRAINT FK_SAD_CONTROLLER_PROFILE_ID FOREIGN KEY (CONTROLLER_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_SAD_SENDER_ID FOREIGN KEY (SENDER_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID), 
CONSTRAINT FK_SAD_CONSIGNEE_ID FOREIGN KEY (CONSIGNEE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID), 
CONSTRAINT FK_SAD_NOTIFY_PARTY_ID FOREIGN KEY (NOTIFY_PARTY_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID), 
CONSTRAINT FK_SAD_FORWARDING_AGENT_ID FOREIGN KEY (FORWARDING_AGENT_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),

CONSTRAINT FK_SAD_POA_COUNTRY_ID FOREIGN KEY (PORT_OF_ARRIVAL_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_SAD_POA_STATE_ID FOREIGN KEY (PORT_OF_ARRIVAL_STATE_ID) REFERENCES SM_STATE_MASTER (STATE_ID),
CONSTRAINT FK_SAD_POA_CITY_ID FOREIGN KEY (PORT_OF_ARRIVAL_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID)
);

ALTER TABLE SADUL_SHIPMENT_ADVICE_UL ADD 
(
CONSTRAINT FK_SADUL_INTERNAL_GMR_REF_NO FOREIGN KEY (INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO),
CONSTRAINT FK_SADUL_INT_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO)
);

ALTER TABLE ROD_RELEASE_ORDER_DETAIL ADD 
(
CONSTRAINT FK_ROD_GMR_REF_NO_ACTION_NO FOREIGN KEY(INTERNAL_GMR_REF_NO,ACTION_NO) REFERENCES AGMR_ACTION_GMR(INTERNAL_GMR_REF_NO, ACTION_NO),
CONSTRAINT FK_ROD_WAREHOUSE_PROFILE_ID FOREIGN KEY (WAREHOUSE_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_ROD_WAREHOUSE_SHED_ID FOREIGN KEY (WAREHOUSE_SHED_ID) REFERENCES SLD_STORAGE_LOCATION_DETAIL (STORAGE_LOC_ID),

CONSTRAINT FK_ROD_FD_COUNTRY_ID FOREIGN KEY (FINAL_DESTINATION_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_ROD_FD_CITY_ID FOREIGN KEY (FINAL_DESTINATION_CITY_ID) REFERENCES CIM_CITYMASTER (CITY_ID),

CONSTRAINT FK_ROD_ISSUE_ID FOREIGN KEY (ISSUE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID), 

CONSTRAINT FK_ROD_CONSIGNEE_ID FOREIGN KEY (CONSIGNEE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_ROD_WAREHOUSE_RENT_CUR_ID FOREIGN KEY (WAREHOUSE_RENT_CUR_ID) REFERENCES CM_CURRENCY_MASTER (CUR_ID)
);

ALTER TABLE RODUL_RELEASE_ORDER_DETAIL_UL ADD 
(
CONSTRAINT FK_RODUL_INTERNAL_GMR_REF_NO FOREIGN KEY (INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO),
CONSTRAINT FK_RODUL_INT_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO)
);


ALTER TABLE GRD_GOODS_RECORD_DETAIL ADD 
(
CONSTRAINT FK_GRD_INTERNAL_GMR_REF_NO FOREIGN KEY (INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO),
CONSTRAINT FK_GRD_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PDM_PRODUCTMASTER (PRODUCT_ID),
CONSTRAINT FK_GRD_QTY_UNIT_ID FOREIGN KEY (QTY_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID),
CONSTRAINT FK_GRD_QUALITY_ID FOREIGN KEY (QUALITY_ID) REFERENCES QAT_QUALITY_ATTRIBUTES (QUALITY_ID),
CONSTRAINT FK_GRD_WAREHOUSE_PROFILE_ID FOREIGN KEY (WAREHOUSE_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_GRD_PARENT_INT_GRD_REF_NO FOREIGN KEY (PARENT_INTERNAL_GRD_REF_NO) REFERENCES GRD_GOODS_RECORD_DETAIL (INTERNAL_GRD_REF_NO),
CONSTRAINT FK_GRD_INTERNAL_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO),
CONSTRAINT FK_GRD_CUSTOMS_ID FOREIGN KEY (CUSTOMS_ID) REFERENCES SLV_STATIC_LIST_VALUE (VALUE_ID),
CONSTRAINT FK_GRD_TAX_ID FOREIGN KEY (TAX_ID) REFERENCES SLV_STATIC_LIST_VALUE (VALUE_ID),
CONSTRAINT FK_GRD_DUTY_ID FOREIGN KEY (DUTY_ID) REFERENCES SLV_STATIC_LIST_VALUE (VALUE_ID),
CONSTRAINT FK_GRD_PARTNERSHIP_TYPE FOREIGN KEY (PARTNERSHIP_TYPE) REFERENCES SLV_STATIC_LIST_VALUE (VALUE_ID)
);

ALTER TABLE GRDUL_GOODS_RECORD_DETAIL_UL ADD 
(
CONSTRAINT FK_GRDUL_INT_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO)
);

ALTER TABLE AGRD_ACTION_GRD ADD 
(
CONSTRAINT FK_AGRD_INTERNAL_GRD_REF_NO FOREIGN KEY (INTERNAL_GRD_REF_NO) REFERENCES GRD_GOODS_RECORD_DETAIL (INTERNAL_GRD_REF_NO),
CONSTRAINT FK_AGRD_INTERNAL_GMR_REF_NO FOREIGN KEY (INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO),
CONSTRAINT FK_AGRD_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PDM_PRODUCTMASTER (PRODUCT_ID),
CONSTRAINT FK_AGRD_QTY_UNIT_ID FOREIGN KEY (QTY_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID),
CONSTRAINT FK_AGRD_QUALITY_ID FOREIGN KEY (QUALITY_ID) REFERENCES QAT_QUALITY_ATTRIBUTES (QUALITY_ID),
CONSTRAINT FK_AGRD_WAREHOUSE_PROFILE_ID FOREIGN KEY (WAREHOUSE_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_AGRD_PARENT_INT_GRD_REF_NO FOREIGN KEY (PARENT_INTERNAL_GRD_REF_NO) REFERENCES GRD_GOODS_RECORD_DETAIL (INTERNAL_GRD_REF_NO),
CONSTRAINT FK_AGRD_CUSTOMS_ID FOREIGN KEY (CUSTOMS_ID) REFERENCES SLV_STATIC_LIST_VALUE (VALUE_ID),
CONSTRAINT FK_AGRD_TAX_ID FOREIGN KEY (TAX_ID) REFERENCES SLV_STATIC_LIST_VALUE (VALUE_ID),
CONSTRAINT FK_AGRD_DUTY_ID FOREIGN KEY (DUTY_ID) REFERENCES SLV_STATIC_LIST_VALUE (VALUE_ID),
CONSTRAINT FK_AGRD_PARTNERSHIP_TYPE FOREIGN KEY (PARTNERSHIP_TYPE) REFERENCES SLV_STATIC_LIST_VALUE (VALUE_ID)
);

ALTER TABLE DGRD_DELIVERED_GRD ADD 
(
CONSTRAINT FK_DGRD_DISCHARGE_COUNTRY_ID FOREIGN KEY (DISCHARGE_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_DGRD_DISCHARGE_PORT_ID FOREIGN KEY (DISCHARGE_PORT_ID) REFERENCES PMT_PORTMASTER (PORT_ID),

CONSTRAINT FK_DGRD_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PDM_PRODUCTMASTER (PRODUCT_ID),
CONSTRAINT FK_DGRD_QUALITY_ID FOREIGN KEY (QUALITY_ID) REFERENCES QAT_QUALITY_ATTRIBUTES (QUALITY_ID),

CONSTRAINT FK_DGRD_NET_WEIGHT_UNIT_ID FOREIGN KEY (NET_WEIGHT_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID),
CONSTRAINT FK_DGRD_PARENT_DGRD_REF_NO FOREIGN KEY (PARENT_DGRD_REF_NO) REFERENCES DGRD_DELIVERED_GRD (INTERNAL_DGRD_REF_NO),

CONSTRAINT FK_DGRD_WAREHOUSE_PROFILE_ID FOREIGN KEY (WAREHOUSE_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_DGRD_SHED_ID FOREIGN KEY (SHED_ID) REFERENCES SLD_STORAGE_LOCATION_DETAIL (STORAGE_LOC_ID),

CONSTRAINT FK_DGRD_CONTRACT_ITEM_REF_NO FOREIGN KEY (INTERNAL_CONTRACT_ITEM_REF_NO) REFERENCES PCI_PHYSICAL_CONTRACT_ITEM (INTERNAL_CONTRACT_ITEM_REF_NO),

CONSTRAINT FK_DGRD_INT_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO),

CONSTRAINT FK_DGRD_CUSTOMS_ID FOREIGN KEY (CUSTOMS_ID) REFERENCES SLV_STATIC_LIST_VALUE (VALUE_ID),
CONSTRAINT FK_DGRD_TAX_ID FOREIGN KEY (TAX_ID) REFERENCES SLV_STATIC_LIST_VALUE (VALUE_ID),
CONSTRAINT FK_DGRD_DUTY_ID FOREIGN KEY (DUTY_ID) REFERENCES SLV_STATIC_LIST_VALUE (VALUE_ID),

CONSTRAINT FK_DGRD_PARTNERSHIP_TYPE FOREIGN KEY (PARTNERSHIP_TYPE) REFERENCES SLV_STATIC_LIST_VALUE (VALUE_ID),

CONSTRAINT FK_DGRD_ASSAY_HEADER_ID FOREIGN KEY (ASSAY_HEADER_ID) REFERENCES ASH_ASSAY_HEADER (ASH_ID)
);

ALTER TABLE DGRDUL_DELIVERED_GRD_UL ADD 
(
CONSTRAINT FK_DGRDUL_INT_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO)
);


ALTER TABLE ADGRD_ACTION_DGRD ADD 
(
CONSTRAINT FK_ADGRD_DISCHARGE_COUNTRY_ID FOREIGN KEY (DISCHARGE_COUNTRY_ID) REFERENCES CYM_COUNTRYMASTER (COUNTRY_ID),
CONSTRAINT FK_ADGRD_DISCHARGE_PORT_ID FOREIGN KEY (DISCHARGE_PORT_ID) REFERENCES PMT_PORTMASTER (PORT_ID),

CONSTRAINT FK_ADGRD_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PDM_PRODUCTMASTER (PRODUCT_ID),
CONSTRAINT FK_ADGRD_QUALITY_ID FOREIGN KEY (QUALITY_ID) REFERENCES QAT_QUALITY_ATTRIBUTES (QUALITY_ID),

CONSTRAINT FK_ADGRD_NET_WEIGHT_UNIT_ID FOREIGN KEY (NET_WEIGHT_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID),

CONSTRAINT FK_ADGRD_WAREHOUSE_PROFILE_ID FOREIGN KEY (WAREHOUSE_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),

CONSTRAINT FK_ADGRD_CONTRACT_ITEM_REF_NO FOREIGN KEY (INTERNAL_CONTRACT_ITEM_REF_NO) REFERENCES PCI_PHYSICAL_CONTRACT_ITEM (INTERNAL_CONTRACT_ITEM_REF_NO),

CONSTRAINT FK_ADGRD_CUSTOMS_ID FOREIGN KEY (CUSTOMS_ID) REFERENCES SLV_STATIC_LIST_VALUE (VALUE_ID),
CONSTRAINT FK_ADGRD_TAX_ID FOREIGN KEY (TAX_ID) REFERENCES SLV_STATIC_LIST_VALUE (VALUE_ID),
CONSTRAINT FK_ADGRD_DUTY_ID FOREIGN KEY (DUTY_ID) REFERENCES SLV_STATIC_LIST_VALUE (VALUE_ID),

CONSTRAINT FK_ADGRD_PARTNERSHIP_TYPE FOREIGN KEY (PARTNERSHIP_TYPE) REFERENCES SLV_STATIC_LIST_VALUE (VALUE_ID),

CONSTRAINT FK_ADGRD_ASSAY_HEADER_ID FOREIGN KEY (ASSAY_HEADER_ID) REFERENCES ASH_ASSAY_HEADER (ASH_ID)
);


ALTER TABLE GEPD_GMR_ELEMENT_PLEDGE_DETAIL ADD 
(
CONSTRAINT FK_GEPD_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PDM_PRODUCTMASTER (PRODUCT_ID)
);

ALTER TABLE SPQ_STOCK_PAYABLE_QTY ADD 
(
CONSTRAINT FK_SPQ_ELEMENT_ID FOREIGN KEY (ELEMENT_ID) REFERENCES AML_ATTRIBUTE_MASTER_LIST (ATTRIBUTE_ID),
CONSTRAINT FK_SPQ_QTY_UNIT_ID FOREIGN KEY (QTY_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID),
CONSTRAINT FK_SPQ_INTERNAL_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO)
);

ALTER TABLE PM_POOL_MASTER ADD 
(
CONSTRAINT FK_PM_POOL_CORPORATE_ID FOREIGN KEY (CORPORATE_ID) REFERENCES AK_CORPORATE (CORPORATE_ID),
CONSTRAINT FK_PM_POOL_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PDM_PRODUCTMASTER (PRODUCT_ID),
CONSTRAINT FK_PM_POOL_QUALITY_ID FOREIGN KEY (QUALITY_ID) REFERENCES QAT_QUALITY_ATTRIBUTES (QUALITY_ID),
CONSTRAINT FK_PM_POOL_QTY_UNIT_ID FOREIGN KEY (POOL_QTY_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID),
CONSTRAINT FK_PM_POOL_WAREHOUSE_ID FOREIGN KEY (WAREHOUSE_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
CONSTRAINT FK_PM_POOL_VALUATION_METHOD FOREIGN KEY (VALUATION_METHOD) REFERENCES SLV_STATIC_LIST_VALUE (VALUE_ID),
CONSTRAINT FK_PM_POOL_PROFIT_CENTER_ID FOREIGN KEY (PROFIT_CENTER_ID) REFERENCES CPC_CORPORATE_PROFIT_CENTER (PROFIT_CENTER_ID),
CONSTRAINT FK_PM_POOL_CP_PROFILE_ID FOREIGN KEY (CP_PROFILE_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID)
);

ALTER TABLE PAQ_POOL_ALLOCATED_QUALITY ADD 
(
CONSTRAINT FK_PAQ_POOL_ID FOREIGN KEY (POOL_ID) REFERENCES PM_POOL_MASTER (POOL_ID),
CONSTRAINT FK_PAQ_ALLOCATED_QUALITY_ID FOREIGN KEY (ALLOCATED_QUALITY_ID) REFERENCES QAT_QUALITY_ATTRIBUTES (QUALITY_ID)
);

ALTER TABLE PQS_POOL_QUANTITY_STATUS ADD 
(
CONSTRAINT FK_PQS_QTY_UNIT_ID FOREIGN KEY (QTY_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID)
);

ALTER TABLE PQUH_POOL_QTY_UPDATE_HISTORY ADD 
(
CONSTRAINT FK_PQUH_POOL_ID FOREIGN KEY (POOL_ID) REFERENCES PM_POOL_MASTER (POOL_ID),
CONSTRAINT FK_PQUH_INT_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO),
CONSTRAINT FK_PQUH_INTERNAL_GMR_REF_NO FOREIGN KEY (INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO),
CONSTRAINT FK_PQUH_QTY_UNIT_ID FOREIGN KEY (QTY_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID)
);

ALTER TABLE PSR_POOL_STOCK_REGISTER ADD 
(
CONSTRAINT FK_PSR_POOL_ID FOREIGN KEY (POOL_ID) REFERENCES PM_POOL_MASTER (POOL_ID),
CONSTRAINT FK_PSR_INTERNAL_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO),
CONSTRAINT FK_PSR_INTERNAL_GMR_REF_NO FOREIGN KEY (INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO),
CONSTRAINT FK_PSR_INTERNAL_GRD_REF_NO FOREIGN KEY (INTERNAL_GRD_REF_NO) REFERENCES GRD_GOODS_RECORD_DETAIL (INTERNAL_GRD_REF_NO),
CONSTRAINT FK_PSR_QTY_UNIT_ID FOREIGN KEY (QTY_UNIT) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID)
);

ALTER TABLE SPSM_SALES_POOL_STOCK_MAPPING ADD 
(
CONSTRAINT FK_SPSM_INT_SALES_GMR_REF_NO FOREIGN KEY (INTERNAL_SALES_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO),
CONSTRAINT FK_SPSM_INTERNAL_GRD_REF_NO FOREIGN KEY (INTERNAL_GRD_REF_NO) REFERENCES GRD_GOODS_RECORD_DETAIL (INTERNAL_GRD_REF_NO),
CONSTRAINT FK_SPSM_SALES_QTY_UNIT_ID FOREIGN KEY (SALES_QTY_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID)
);

ALTER TABLE WOP_WRITE_OFF_POOL ADD 
(
CONSTRAINT FK_WOP_POOL_ID FOREIGN KEY (POOL_ID) REFERENCES PM_POOL_MASTER (POOL_ID),
CONSTRAINT FK_WOP_INTERNAL_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO),
CONSTRAINT FK_WOP_WRITE_OFF_QTY_UNIT_ID FOREIGN KEY (WRITE_OFF_QTY_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID)
);

ALTER TABLE AGH_ALLOC_GROUP_HEADER ADD 
(
CONSTRAINT FK_AGH_ALLOC_ITEM_QTY_UNIT_ID FOREIGN KEY (ALLOC_ITEM_QTY_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID),
CONSTRAINT FK_AGH_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AK_CORPORATE_USER (USER_ID),
CONSTRAINT FK_AGH_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AK_CORPORATE_USER (USER_ID),
CONSTRAINT FK_AGH_CANCELLED_BY FOREIGN KEY (CANCELLED_BY) REFERENCES AK_CORPORATE_USER (USER_ID),
CONSTRAINT FK_AGH_INTERNAL_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO),
CONSTRAINT FK_AGH_PARTNERSHIP_TYPE FOREIGN KEY (PARTNERSHIP_TYPE) REFERENCES SLV_STATIC_LIST_VALUE (VALUE_ID)
);

ALTER TABLE AGHUL_ALLOC_GROUP_HEADER_UL ADD 
(
CONSTRAINT FK_AGHUL_INT_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO)
);

ALTER TABLE AAGD_ACTION_ALLOC_GROUP_DETAIL ADD 
(
CONSTRAINT FK_AAGD_INTERNAL_STOCK_REF_NO FOREIGN KEY (INTERNAL_STOCK_REF_NO) REFERENCES GRD_GOODS_RECORD_DETAIL (INTERNAL_GRD_REF_NO)
);

ALTER TABLE AGD_ALLOC_GROUP_DETAIL ADD 
(
CONSTRAINT FK_AGD_CONTRACT_ITEM_REF_NO FOREIGN KEY (INTERNAL_CONTRACT_ITEM_REF_NO) REFERENCES PCI_PHYSICAL_CONTRACT_ITEM (INTERNAL_CONTRACT_ITEM_REF_NO),
CONSTRAINT FK_AGD_QTY_UNIT_ID FOREIGN KEY (QTY_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID),
CONSTRAINT FK_AGD_SALES_QTY_UNIT_ID FOREIGN KEY (SALES_QTY_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID),
CONSTRAINT FK_AGD_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES AK_CORPORATE_USER (USER_ID),
CONSTRAINT FK_AGD_UPDATED_BY FOREIGN KEY (UPDATED_BY) REFERENCES AK_CORPORATE_USER (USER_ID),
CONSTRAINT FK_AGD_CANCELLED_BY FOREIGN KEY (CANCELLED_BY) REFERENCES AK_CORPORATE_USER (USER_ID),
CONSTRAINT FK_AGD_INTERNAL_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO)
);

ALTER TABLE AGDUL_ALLOC_GROUP_DETAIL_UL ADD 
(
CONSTRAINT FK_AGDUL_INT_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO)
);

ALTER TABLE GAM_GMR_ACTION_MAPPING ADD 
(
CONSTRAINT FK_GAM_INTERNAL_ACTION_REF_NO FOREIGN KEY (INTERNAL_ACTION_REF_NO) REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO),
CONSTRAINT FK_GAM_INTERNAL_GMR_REF_NO FOREIGN KEY (INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO),
CONSTRAINT FK_GAM_ACTIVITY_QTY_UNIT_ID FOREIGN KEY (ACTIVITY_QTY_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID),
CONSTRAINT FK_GAM_POOL_ID FOREIGN KEY (POOL_ID) REFERENCES PM_POOL_MASTER (POOL_ID)
);


ALTER TABLE GCIM_GMR_CONTRACT_ITEM_MAPPING ADD
(
CONSTRAINT FK_GCIM_INTERNAL_GMR_REF_NO FOREIGN KEY (INTERNAL_GMR_REF_NO) REFERENCES GMR_GOODS_MOVEMENT_RECORD (INTERNAL_GMR_REF_NO)
);

ALTER TABLE MOGRD_MOVED_OUT_GRD ADD 
(
CONSTRAINT FK_MOGRD_INTERNAL_GRD_REF_NO FOREIGN KEY (INTERNAL_GRD_REF_NO) REFERENCES GRD_GOODS_RECORD_DETAIL (INTERNAL_GRD_REF_NO),
CONSTRAINT FK_MOGRD_QTY_UNIT_ID FOREIGN KEY (QTY_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID),
CONSTRAINT FK_MOGRD_POOL_ID FOREIGN KEY (POOL_ID) REFERENCES PM_POOL_MASTER (POOL_ID)
);

DELETE  CGAR_CORPORATE_GMR_ACTION_RULE CGAR
WHERE CGAR.ACTION_ID IN ('undoWrtOffCMAStocks', 'writeOffCMAStocks')
OR CGAR.PARENT_ACTION_ID IN
					 ('undoWrtOffCMAStocks', 'writeOffCMAStocks');
					 
ALTER TABLE CGAR_CORPORATE_GMR_ACTION_RULE ADD 
(
CONSTRAINT FK_CGAR_CORPORATE_ID FOREIGN KEY (CORPORATE_ID) REFERENCES AK_CORPORATE (CORPORATE_ID),
CONSTRAINT FK_CGAR_PARENT_ACTION_ID FOREIGN KEY (PARENT_ACTION_ID) REFERENCES AXM_ACTION_MASTER (ACTION_ID),
CONSTRAINT FK_CGAR_ACTION_ID FOREIGN KEY (ACTION_ID) REFERENCES AXM_ACTION_MASTER (ACTION_ID)
);