alter table TAD_TRADE_ALLOCATION_DETAILS add IS_FREE_METAL_PRICE_FIXATION char(1 ) default 'N';
alter table TAD_TRADE_ALLOCATION_DETAILS add FREE_METAL_PRICE_FIXATION_ID VARCHAR2(15 CHAR);

ALTER TABLE TAD_TRADE_ALLOCATION_DETAILS ADD (
  FOREIGN KEY (FREE_METAL_PRICE_FIXATION_ID) 
 REFERENCES FMPFD_PRICE_FIXATION_DETAILS (FMPFD_ID));