CREATE TABLE SBS_SMELTER_BASE_STOCK
(
  SBS_ID                    VARCHAR2(15)        NOT NULL,
  CORPORATE_ID              VARCHAR2(15)        NOT NULL,
  ACTIVITY_ACTION_ID        VARCHAR2(30),
  ACTIVITY_REF_NO           VARCHAR2(30),
  ACTIVITY_DATE             DATE                NOT NULL,
  SMELTER_CP_ID             VARCHAR2(20)        NOT NULL,
  PRODUCT_ID                VARCHAR2(15)        NOT NULL,
  QUALITY_ID                VARCHAR2(15)        NOT NULL,
  ELEMENT_ID                VARCHAR2(15),
  QTY                       NUMBER(25,10)       NOT NULL,
  QTY_UNIT_ID               VARCHAR2(15)        NOT NULL,
  WAREHOUSE_PROFILE_ID      VARCHAR2(15)        NOT NULL,
  SHED_ID                   VARCHAR2(15)        NOT NULL,
  IS_ACTIVE                 CHAR(1)             DEFAULT 'Y'                   NOT NULL
);

ALTER TABLE SBS_SMELTER_BASE_STOCK ADD (
  CONSTRAINT CHK_SBS_IS_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N')),
  CONSTRAINT PK_SBS PRIMARY KEY (SBS_ID),
  CONSTRAINT FK_SBS_CORPORATE_ID FOREIGN KEY (CORPORATE_ID) REFERENCES AK_CORPORATE (CORPORATE_ID),
  CONSTRAINT FK_SBS_SMELTER_CP_ID FOREIGN KEY (SMELTER_CP_ID) REFERENCES PHD_PROFILEHEADERDETAILS (PROFILEID),
  CONSTRAINT FK_SBS_PRODUCT_ID FOREIGN KEY (PRODUCT_ID) REFERENCES PDM_PRODUCTMASTER (PRODUCT_ID),
  CONSTRAINT FK_SBS_QUALITY_ID FOREIGN KEY (QUALITY_ID) REFERENCES QAT_QUALITY_ATTRIBUTES (QUALITY_ID),
  CONSTRAINT FK_SBS_ELEMENT_ID FOREIGN KEY (ELEMENT_ID) REFERENCES AML_ATTRIBUTE_MASTER_LIST (ATTRIBUTE_ID),
  CONSTRAINT FK_SBS_QTY_UNIT_ID FOREIGN KEY (QTY_UNIT_ID) REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID)
);