ALTER TABLE SPQ_STOCK_PAYABLE_QTY ADD
(
    EXT_ASSAY_HEADER_ID     VARCHAR2(15),
    EXT_ASSAY_CONTENT       NUMBER(25,10),
    EXT_PAYABLE_QTY         NUMBER(25,10),
    CONSTRAINT FK_SPQ_EXT_ASH_ID FOREIGN KEY (EXT_ASSAY_HEADER_ID) REFERENCES ASH_ASSAY_HEADER (ASH_ID)     
);

ALTER TABLE GEPD_GMR_ELEMENT_PLEDGE_DETAIL ADD
(
    EXT_PLEDGE_QTY NUMBER (25,10)
);

ALTER TABLE MTFS_MBT_FIN_SETTLEMENT ADD
(
    EXT_QTY NUMBER (25,10)
);

ALTER TABLE PRRQS_PRR_QTY_STATUS ADD
(
    EXT_QTY NUMBER (25,10)
);