ALTER TABLE DGRD_DELIVERED_GRD
drop CONSTRAINT CHK_DRD_TOLLING_STOCK_TYPE;



ALTER TABLE DGRD_DELIVERED_GRD
add CONSTRAINT CHK_DRD_TOLLING_STOCK_TYPE
   CHECK (TOLLING_STOCK_TYPE IN ('None Tolling','Financial Settlement Stock','Return Material Stock'));
   
  
ALTER TABLE ADGRD_ACTION_DGRD
drop CONSTRAINT CHK_ADRD_TOLLING_STOCK_TYPE;



ALTER TABLE ADGRD_ACTION_DGRD
add CONSTRAINT CHK_ADRD_TOLLING_STOCK_TYPE
   CHECK (TOLLING_STOCK_TYPE IN ('None Tolling','Financial Settlement Stock','Return Material Stock'));
    
   
 
ALTER TABLE WRD_WAREHOUSE_RECEIPT_DETAIL

DROP COLUMN WAREHOUSE_ADDRESS;





CREATE TABLE TAS_TRADE_ALLOCATION_STATUS
(
  INTERNAL_DERIVATIVE_REF_NO  NUMBER(5),
  TRADE_ALLOC_QTY             NUMBER(25,5)      DEFAULT 0,
  QTY_UNIT_ID                 VARCHAR2(15),
  IS_ACTIVE                   CHAR(1),
  STATUS                      VARCHAR2(50),
  CORPORATE_ID                VARCHAR2(15),
  TAS_ID                      VARCHAR2(15) NOT NULL
);
ALTER TABLE TAS_TRADE_ALLOCATION_STATUS ADD (
  CONSTRAINT TAS_PK
 PRIMARY KEY
 (TAS_ID));

ALTER TABLE TAS_TRADE_ALLOCATION_STATUS ADD (
  FOREIGN KEY (CORPORATE_ID) 
 REFERENCES AK_CORPORATE (CORPORATE_ID),
  FOREIGN KEY (QTY_UNIT_ID) 
 REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID),
  FOREIGN KEY (INTERNAL_DERIVATIVE_REF_NO) 
 REFERENCES DT_DERIVATIVE_TRADE (INTERNAL_DERIVATIVE_REF_NO));






CREATE TABLE TAD_TRADE_ALLOCATION_DETAILS
(
  INTERNAL_DERIVATIVE_REF_NO  NUMBER(5),
  PRICE_FIXATION_ID           VARCHAR2(15),
  ALLOCATED_QTY               NUMBER(25,5)      DEFAULT 0,
  IS_ACTIVE                   CHAR(1)      DEFAULT 'Y',
  TAD_ID                      VARCHAR2(15),
  ALLOCATED_QTY_UNIT_ID       VARCHAR2(15),
  VERSION                     NUMBER(10),
  INTERNAL_ACTION_REF_NO      VARCHAR2(15)
);


ALTER TABLE TAD_TRADE_ALLOCATION_DETAILS ADD (
  CONSTRAINT PK_TFM
 PRIMARY KEY
 (TAD_ID));

ALTER TABLE TAD_TRADE_ALLOCATION_DETAILS ADD (
  FOREIGN KEY (INTERNAL_ACTION_REF_NO) 
 REFERENCES AXS_ACTION_SUMMARY (INTERNAL_ACTION_REF_NO),
  FOREIGN KEY (INTERNAL_DERIVATIVE_REF_NO) 
 REFERENCES DT_DERIVATIVE_TRADE (INTERNAL_DERIVATIVE_REF_NO),
  FOREIGN KEY (PRICE_FIXATION_ID) 
 REFERENCES PFD_PRICE_FIXATION_DETAILS (PFD_ID),
  FOREIGN KEY (ALLOCATED_QTY_UNIT_ID) 
 REFERENCES QUM_QUANTITY_UNIT_MASTER (QTY_UNIT_ID));


CREATE SEQUENCE SEQ_TAD
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;
  

CREATE SEQUENCE SEQ_TAS
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;