ALTER TABLE IID_INVOICABLE_ITEM_DETAILS
 ADD (CONTRACT_TYPE  VARCHAR2(15 BYTE));

ALTER TABLE ITD_INVOICE_TAX_DETAILS
 ADD (FX_RATE  NUMBER(38,18));

ALTER TABLE IS_INVOICE_SUMMARY
 ADD (IS_PROV_CREATED  CHAR(1 BYTE) DEFAULT 'N');