CREATE TABLE DC_DOCUMENT_CONFIGURATION
(
  ACTIVITY_ID               VARCHAR2(30 BYTE)   NOT NULL,
  CORPORATE_ID              VARCHAR2(20 BYTE)   NOT NULL,
  IS_GENERATE_DOC_REQD      CHAR(1 BYTE)        NOT NULL,
  IS_UPLOAD_DOC_REQD        CHAR(1 BYTE)        NOT NULL,
  DOC_VALIDATION_QUERY      CLOB                NOT NULL,
  NAVIGATION                VARCHAR2(1000 BYTE) NOT NULL
);


CREATE UNIQUE INDEX PK_DC_ID ON DC_DOCUMENT_CONFIGURATION
(ACTIVITY_ID,CORPORATE_ID);


ALTER TABLE DC_DOCUMENT_CONFIGURATION ADD (
  CONSTRAINT PK_DC_ID
 PRIMARY KEY
 (ACTIVITY_ID,CORPORATE_ID));



alter table DHD_DOCUMENT_HEADER_DETAILS add action_no varchar2(30);
