alter table POFH_PRICE_OPT_FIXATION_HEADER  add IS_REQ_FX_EXPOSURE_AMOUNT char(1 char);
alter table GPAD_GMR_PRICE_ALLOC_DTLS  add HEDGE_AMOUNT number(25,10);
alter table PFD_PRICE_FIXATION_DETAILS  add IS_FX_EXPOSURE_AMOUNT char(1 char);
alter table GPAD_GMR_PRICE_ALLOC_DTLS  add IS_FX_EXPOSURE_AMOUNT char(1 char);
alter table GPAH_GMR_PRICE_ALLOC_HEADER  add IS_REQ_FX_EXPOSURE_AMOUNT char(1 char);
alter table PPL_PRICE_PROCESS_LIST  add CORPORATE_ID varchar2(25);
alter table PPL_PRICE_PROCESS_LIST  add EXEC_STATUS_DESCRIPTION varchar2(500);