alter table HCD_HEDGE_CORRECTION_DETAILS drop column EVENT_SEQUENC_NO;
alter table HCD_HEDGE_CORRECTION_DETAILS add EVENT_SEQUENC_NO number(25,10);
alter table HCD_HEDGE_CORRECTION_DETAILS add IS_HEDGE_CORRECTION_POSTED CHAR(1 char);

ALTER TABLE HCD_HEDGE_CORRECTION_DETAILS ADD (
  CONSTRAINT PK_HCD
 PRIMARY KEY
 (HCD_ID));

create table HQPM_HEDGE_QTY_PROCESS_MAPPING
(
  HQP_ID varchar(30),
  HCD_ID varchar(15),
  PRICE_PROCESS_ID varchar(30),
  IS_ACTIVE CHAR(1 char),
  VERSION NUMBER(10)
  
);
CREATE UNIQUE INDEX PK_HQPM ON HQPM_HEDGE_QTY_PROCESS_MAPPING
(HQP_ID);
CREATE INDEX IDX_FK_HQPM_HCD_ID ON HQPM_HEDGE_QTY_PROCESS_MAPPING
(HCD_ID);
CREATE INDEX IDX_FK_HQPM_PRICE_PROCESS_ID ON HQPM_HEDGE_QTY_PROCESS_MAPPING
(PRICE_PROCESS_ID);

ALTER TABLE HQPM_HEDGE_QTY_PROCESS_MAPPING ADD (
  CONSTRAINT PK_HQPM
 PRIMARY KEY
 (HQP_ID));
 ALTER TABLE HQPM_HEDGE_QTY_PROCESS_MAPPING ADD (
  CONSTRAINT FK_HQPM_HCD_ID 
 FOREIGN KEY (HCD_ID) 
 REFERENCES HCD_HEDGE_CORRECTION_DETAILS(HCD_ID));
 
  ALTER TABLE HQPM_HEDGE_QTY_PROCESS_MAPPING ADD (
  CONSTRAINT FK_HQPM_PRICE_PROCESS_ID 
 FOREIGN KEY (PRICE_PROCESS_ID) ;
CREATE SEQUENCE SEQ_HQPM
MINVALUE 10
START WITH 10
INCREMENT BY 1;
 REFERENCES PPL_PRICE_PROCESS_LIST (PRICE_PROCESS_ID));


alter table PFD_PRICE_FIXATION_DETAILS add event_sequence_no number(25,10);

alter table POFHL_PRICE_OPT_FIXAT_HEAD_LOG add HEDGE_CORRECTION_QTY_DELTA number(25,10);
alter table POFHL_PRICE_OPT_FIXAT_HEAD_LOG add QP_START_QTY_DELTA number(25,10);
alter table POFHL_PRICE_OPT_FIXAT_HEAD_LOG add IS_PROVESIONAL_ASSAY_EXIST CHAR(1 CHAR);
alter table POFHL_PRICE_OPT_FIXAT_HEAD_LOG add BALANCE_PRICED_QTY_DELTA number(25,10);
alter table POFHL_PRICE_OPT_FIXAT_HEAD_LOG add PER_DAY_HEDGE_CORR_QTY_DELTA number(25,10);
alter table POFHL_PRICE_OPT_FIXAT_HEAD_LOG add TOTAL_HEDGE_CORRE_QTY_DELTA number(25,10);


