CREATE TABLE IPP_INVOICE_PROVISIONAL_PRICE
(
  IPP_ID                  VARCHAR2(15 CHAR),
  EFFECTIVE_DATE          DATE,
  ELEMENT_ID              VARCHAR2(25 CHAR),
  PROV_PRICE              NUMBER(25,10),
  PRICE_UNIT_ID           VARCHAR2(25 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE IPP_INVOICE_PROVISIONAL_PRICE ADD (
  CONSTRAINT IPP_INVOICE_PROVISIONAL_PRI_PK
 PRIMARY KEY
 (IPP_ID));


ALTER TABLE IPP_INVOICE_PROVISIONAL_PRICE
 ADD (IPPH_ID  VARCHAR2(15 CHAR));

ALTER TABLE IPP_INVOICE_PROVISIONAL_PRICE
 ADD (PRICE_UNIT_NAME  VARCHAR2(50 CHAR));



CREATE SEQUENCE SEQ_IPP
START WITH 1
INCREMENT BY 1
MINVALUE 1
MAXVALUE 100000000000000000000000000
NOCACHE 
NOCYCLE 
NOORDER 

CREATE TABLE IPPH_INV_PRO_PRICE_HEADER
(
  IPPH_ID        VARCHAR2(15 CHAR),
  EFF_DATE       DATE,
  RECORDED_BY    VARCHAR2(25 CHAR),
  RECORDED_DATE  DATE
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
NOMONITORING;


ALTER TABLE IPPH_INV_PRO_PRICE_HEADER ADD (
  CONSTRAINT IPPH_INV_PRO_PRICE_HEADER_PK
 PRIMARY KEY
 (IPPH_ID));

CREATE SEQUENCE SEQ_IPPH
START WITH 0
INCREMENT BY 1
MINVALUE 1
MAXVALUE 100000000000000000000000000
CACHE 2
NOCYCLE 
NOORDER 

