

alter table is_d modify CP_ADDRESS VARCHAR2(1000 CHAR); 

alter table IS_INVOICE_SUMMARY modify BILL_TO_ADDRESS VARCHAR2(1000 CHAR);

alter table IS_UL_INVOICE_SUMMARY_UL modify BILL_TO_ADDRESS VARCHAR2(1000 CHAR);

