CREATE TABLE IJAD_INV_JV_AGENCY_DETAILS
(
  IJAD_ID                        VARCHAR2(15 BYTE) NOT NULL,
  INTERNAL_INVOICE_REF_NO         VARCHAR2(15 BYTE),
  JV_PHD_ID                       VARCHAR2(15 BYTE),
  JV_NAME                         VARCHAR2(100 BYTE),
  JV_AMOUNT                       NUMBER(38,18),
  JV_PERCENTAGE                   NUMBER(38,18),
  COMMISSION_AMOUNT               NUMBER(38,18),
  COMMISSION_FORMULA_ID           VARCHAR2(15 BYTE),
  CURRENCY_ID                     VARCHAR2(15 BYTE)
);

ALTER TABLE IJAD_INV_JV_AGENCY_DETAILS ADD (
  CONSTRAINT IJAD_PK
 PRIMARY KEY
 (IJAD_ID));
 
ALTER TABLE IJAD_INV_JV_AGENCY_DETAILS ADD (
 CONSTRAINT IJAD_IS_FK 
 FOREIGN KEY (INTERNAL_INVOICE_REF_NO) 
 REFERENCES IS_INVOICE_SUMMARY (INTERNAL_INVOICE_REF_NO));
               
CREATE SEQUENCE SEQ_IJAD
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;

CREATE TABLE IJAOC_INV_JV_AGEN_OTHER_CHARGE
(
  INTERNAL_INVOICE_REF_NO  VARCHAR2(15 BYTE)    NOT NULL,
  OTHER_CHARGE_COST_ID     VARCHAR2(15 BYTE)    NOT NULL,
  CONTRACT_TYPE            VARCHAR2(15 BYTE)    NOT NULL,
  FLAT_AMOUNT              NUMBER(38,18),
  RATE_AMOUNT              NUMBER(38,18),
  FLAT_AMOUNT_CUR_UNIT_ID  VARCHAR2(15 BYTE),
  FLAT_AMOUNT_FX_RATE      NUMBER(38,18),
  RATE_FX_RATE             NUMBER(38,18),
  OTHER_CHARGE_DESC        VARCHAR2(50 BYTE),
  QTY_UNIT_ID              VARCHAR2(15 BYTE),
  QUANTITY                 NUMBER(38,18),
  INVOICE_CUR_ID           VARCHAR2(15 BYTE),
  AMOUNT_IN_INV_CUR        NUMBER(38,18),
  RATE_PRICE_UNIT          VARCHAR2(15 BYTE),
  RATE_CHARGE              NUMBER(38,18)
);

ALTER TABLE IJAOC_INV_JV_AGEN_OTHER_CHARGE ADD (
  CONSTRAINT IJAOC_PK
 PRIMARY KEY
 (INTERNAL_INVOICE_REF_NO, OTHER_CHARGE_COST_ID, CONTRACT_TYPE));

ALTER TABLE IJAOC_INV_JV_AGEN_OTHER_CHARGE ADD (
  CONSTRAINT IJAOC_IJAOC_IS_FK 
 FOREIGN KEY (INTERNAL_INVOICE_REF_NO) 
 REFERENCES IS_INVOICE_SUMMARY (INTERNAL_INVOICE_REF_NO));
 
ALTER TABLE IJAOC_INV_JV_AGEN_OTHER_CHARGE ADD (
  CONSTRAINT IJAOC_IJAOC_SCM_FK 
 FOREIGN KEY (OTHER_CHARGE_COST_ID) 
 REFERENCES SCM_SERVICE_CHARGE_MASTER (COST_ID));
