CREATE TABLE TDA_TAX_DELTA_AMOUNT
(
  TDA_ID                   VARCHAR2(15),
  INTERNAL_INVOICE_REF_NO  VARCHAR2(15),
  TAX_ID                   VARCHAR2(15),
  DELTA_AMOUNT             NUMBER(38,18),
  INVOICE_CUR_ID           VARCHAR2(15),
  TAX_NAME                 VARCHAR2(100)
);


CREATE UNIQUE INDEX TDA_PK ON TDA_TAX_DELTA_AMOUNT
(TDA_ID);

ALTER TABLE TDA_TAX_DELTA_AMOUNT ADD (
  CONSTRAINT TDA_PK
 PRIMARY KEY
 (TDA_ID));
 
ALTER TABLE TDA_TAX_DELTA_AMOUNT ADD (
  CONSTRAINT TDA_IS_FK 
 FOREIGN KEY (INTERNAL_INVOICE_REF_NO) 
 REFERENCES IS_INVOICE_SUMMARY (INTERNAL_INVOICE_REF_NO));

CREATE SEQUENCE SEQ_TDA
START WITH 1
MAXVALUE 1000000000000000000000000000
MINVALUE 1
NOCYCLE
CACHE 20
NOORDER;