DROP MATERIALIZED VIEW LOG ON PCMTE_PCM_TOLLING_EXT;
DROP MATERIALIZED VIEW LOG ON PQDT_PAYABLE_EXT_TOLLING;
DROP MATERIALIZED VIEW LOG ON PQCAPD_PRD_QLTY_CATTR_PAY_DTLS;
DROP MATERIALIZED VIEW LOG ON SAM_STOCK_ASSAY_MAPPING;

CREATE MATERIALIZED VIEW LOG ON  PCMTE_PCM_TOLLING_EXT;
CREATE MATERIALIZED VIEW LOG ON  PQDT_PAYABLE_EXT_TOLLING;
CREATE MATERIALIZED VIEW LOG ON  PQCAPD_PRD_QLTY_CATTR_PAY_DTLS;
CREATE MATERIALIZED VIEW LOG ON  SAM_STOCK_ASSAY_MAPPING;