ALTER TABLE PCBPD_PC_BASE_PRICE_DETAIL
 ADD (IS_FX_BY_REQUEST  CHAR(1 CHAR));

ALTER TABLE PCBPDUL_PC_BASE_PRICE_DTL_UL
 ADD (IS_FX_BY_REQUEST  CHAR(1 CHAR));

ALTER TABLE PFD_PRICE_FIXATION_DETAILS
 ADD (IS_FX_BY_REQUEST  CHAR(1 CHAR));
