DROP TRIGGER TRG_INSERT_DGRDL;

CREATE OR REPLACE TRIGGER "TRG_INSERT_DGRDL" 
    /**************************************************************************************************
           Trigger Name                       : trg_insert_dgrdl
           Author                             : Mohit
           Created Date                       : 07th JUNE 2011
           Purpose                            : To Insert into DGRDL Table

           Modification History

           Modified Date  :
           Modified By  :
           Modify Description :

   ***************************************************************************************************/
AFTER INSERT OR UPDATE
   ON DGRD_DELIVERED_GRD    FOR EACH ROW
BEGIN
   --
   -- If updating then put the delta for Quantity columns as Old - New when DGRD is Active
   -- If DGRD is inactive then negate all the quantity columns
   -- If inserting put the new value as is as Delta
   --
   IF UPDATING
   THEN
      IF    :NEW.STATUS = 'Active'
      THEN
         --Qty Unit is Not Updated
         IF :NEW.NET_WEIGHT_UNIT_ID = :OLD.NET_WEIGHT_UNIT_ID
         THEN
            INSERT INTO DGRDL_DELIVERED_GRD_LOG
                        (INTERNAL_DGRD_REF_NO,
            ACTION_NO,
            INTERNAL_GMR_REF_NO,
            INT_ALLOC_GROUP_ID,
            CONTAINER_NO,
            SEAL_NO,
            MARK_NO,
            RELEASE_SHIPPED_NO_UNT_DELTA,
            OLD_NET_WEIGHT_DELTA,
            GROSS_WEIGHT_DELTA,
            TARE_WEIGHT_DELTA,
            NET_WEIGHT_DELTA,
            NET_WEIGHT_UNIT_ID,
            DISCHARGE_DATE,
            DISCHARGE_COUNTRY_ID,
            DISCHARGE_PORT_ID,
            FULFILLMENT_DATE,
            REMARKS,
            VESSEL_QTY_BEFOR_DISCRG_DELTA,
            IS_VOYAGE_STOCK,
            CONTAINER_SIZE,
            BL_DATE,
            BL_NUMBER,
            SHED_ID,
            REALIZED_QTY_DELTA,
            PARENT_DGRD_REF_NO,
            INTERNAL_STOCK_REF_NO,
            WAREHOUSE_REF_NO,
            WAREHOUSE_PROFILE_ID,
            WAREHOUSE_RECEIPT_NO,
            WAREHOUSE_RECEIPT_DATE,
            IS_FINAL_WEIGHT,
            BANK_ID,
            BANK_ACCOUNT_ID,
            INVENTORY_STATUS,
            IS_AFLOAT,
            CROP_YEAR_ID,
            CURRENT_QTY_DELTA,
            INTERNAL_CONTRACT_ITEM_REF_NO,
            IS_WEIGHT_FINAL,
            ORIGIN_ID,
            PACKING_SIZE_ID,
            PRODUCT_ID,
            PRODUCT_SPECS,
            QUALITY_ID,
            WRITE_OFF_QTY_DELTA,
            IS_WRITE_OFF,
            REALIZED_STATUS,
            REALIZED_DATE,
            REALIZED_CREATION_DATE,
            STOCK_STATUS,
            ITEM_PRICE_DELTA,
            ITEM_PRICE_UNIT,
            CURRENT_NO_OF_UNITS_DELTA,
            TOTAL_NO_OF_UNITS_DELTA,
            NO_OF_UNITS_DELTA,
            TOTAL_QTY_DELTA,
            PACKING_TYPE_ID,
            WRITE_OFF_NO_OF_UNITS_DELTA,
            HANDLED_AS,
            INTERNAL_GRD_REF_NO,
            STOCK_CONDITION,
            GRAVITY_TYPE_ID,
            GRAVITY_DELTA,
            DENSITY_MASS_QTY_UNIT_ID,
            DENSITY_VOLUME_QTY_UNIT_ID,
            GRAVITY_TYPE,
            CUSTOMS_ID,
            TAX_ID,
            DUTY_ID,
            PHY_ATTRIBUTE_GROUP_NO,
            ASSAY_HEADER_ID,
            CUSTOMER_SEAL_NO,
            BRAND,
            NO_OF_BAGS_DELTA,
            NO_OF_CONTAINERS_DELTA,
            NO_OF_PIECES_DELTA,
            P_SHIPPED_NET_WEIGHT_DELTA,
            P_SHIPPED_GROSS_WEIGHT_DELTA,
            P_SHIPPED_TARE_WEIGHT_DELTA,
            SDCTS_ID,
            PARTNERSHIP_TYPE,
            INTERNAL_ACTION_REF_NO,
            ENTRY_TYPE,
            STATUS
                        )
                 VALUES (:NEW.INTERNAL_DGRD_REF_NO,
                :NEW.ACTION_NO,
            :NEW.INTERNAL_GMR_REF_NO,
            :NEW.INT_ALLOC_GROUP_ID,
            :NEW.CONTAINER_NO,
            :NEW.SEAL_NO,
            :NEW.MARK_NO,
             :NEW.RELEASE_SHIPPED_NO_OF_UNITS - :OLD.RELEASE_SHIPPED_NO_OF_UNITS,
             :NEW.OLD_NET_WEIGHT - :OLD.OLD_NET_WEIGHT,
             :NEW.GROSS_WEIGHT - :OLD.GROSS_WEIGHT,
             :NEW.TARE_WEIGHT - :OLD.TARE_WEIGHT,
             :NEW.NET_WEIGHT - :OLD.NET_WEIGHT,
             :NEW.NET_WEIGHT_UNIT_ID,
            :NEW.DISCHARGE_DATE,
            :NEW.DISCHARGE_COUNTRY_ID,
            :NEW.DISCHARGE_PORT_ID,
            :NEW.FULFILLMENT_DATE,
            :NEW.REMARKS,
            :NEW.VESSEL_QTY_BEFORE_DISCHARGE - :OLD.VESSEL_QTY_BEFORE_DISCHARGE,
            :NEW.IS_VOYAGE_STOCK,
            :NEW.CONTAINER_SIZE,
            :NEW.BL_DATE,
            :NEW.BL_NUMBER,
            :NEW.SHED_ID,
            :NEW.REALIZED_QTY - :OLD.REALIZED_QTY,
            :NEW.PARENT_DGRD_REF_NO,
            :NEW.INTERNAL_STOCK_REF_NO,
            :NEW.WAREHOUSE_REF_NO,
            :NEW.WAREHOUSE_PROFILE_ID,
            :NEW.WAREHOUSE_RECEIPT_NO,
            :NEW.WAREHOUSE_RECEIPT_DATE,
            :NEW.IS_FINAL_WEIGHT,
            :NEW.BANK_ID,
            :NEW.BANK_ACCOUNT_ID,
            :NEW.INVENTORY_STATUS,
            :NEW.IS_AFLOAT,
            :NEW.CROP_YEAR_ID,
            :NEW.CURRENT_QTY - :OLD.CURRENT_QTY,
            :NEW.INTERNAL_CONTRACT_ITEM_REF_NO,
            :NEW.IS_WEIGHT_FINAL,
            :NEW.ORIGIN_ID,
            :NEW.PACKING_SIZE_ID,
            :NEW.PRODUCT_ID,
            :NEW.PRODUCT_SPECS,
            :NEW.QUALITY_ID,
            :NEW.WRITE_OFF_QTY - :OLD.WRITE_OFF_QTY,
            :NEW.IS_WRITE_OFF,
            :NEW.REALIZED_STATUS,
            :NEW.REALIZED_DATE,
            :NEW.REALIZED_CREATION_DATE,
            :NEW.STOCK_STATUS,
            :NEW.ITEM_PRICE - :OLD.ITEM_PRICE,
            :NEW.ITEM_PRICE_UNIT,
            :NEW.CURRENT_NO_OF_UNITS - :OLD.CURRENT_NO_OF_UNITS,
            :NEW.TOTAL_NO_OF_UNITS - :OLD.TOTAL_NO_OF_UNITS,
            :NEW.NO_OF_UNITS - :OLD.NO_OF_UNITS,
            :NEW.TOTAL_QTY - :OLD.TOTAL_QTY,
            :NEW.PACKING_TYPE_ID,
            :NEW.WRITE_OFF_NO_OF_UNITS - :OLD.WRITE_OFF_NO_OF_UNITS,
            :NEW.HANDLED_AS,
            :NEW.INTERNAL_GRD_REF_NO,
            :NEW.STOCK_CONDITION,
            :NEW.GRAVITY_TYPE_ID,
            :NEW.GRAVITY - :OLD.GRAVITY,
            :NEW.DENSITY_MASS_QTY_UNIT_ID,
            :NEW.DENSITY_VOLUME_QTY_UNIT_ID,
            :NEW.GRAVITY_TYPE,
            :NEW.CUSTOMS_ID,
            :NEW.TAX_ID,
            :NEW.DUTY_ID,
            :NEW.PHY_ATTRIBUTE_GROUP_NO,
            :NEW.ASSAY_HEADER_ID,
            :NEW.CUSTOMER_SEAL_NO,
            :NEW.BRAND,
            :NEW.NO_OF_BAGS - :OLD.NO_OF_BAGS,
            :NEW.NO_OF_CONTAINERS - :OLD.NO_OF_CONTAINERS,
            :NEW.NO_OF_PIECES - :OLD.NO_OF_PIECES,
            :NEW.P_SHIPPED_NET_WEIGHT - :OLD.P_SHIPPED_NET_WEIGHT,
            :NEW.P_SHIPPED_GROSS_WEIGHT - :OLD.P_SHIPPED_GROSS_WEIGHT,
            :NEW.P_SHIPPED_TARE_WEIGHT - :OLD.P_SHIPPED_TARE_WEIGHT,
            :NEW.SDCTS_ID,
            :NEW.PARTNERSHIP_TYPE,
             :NEW.INTERNAL_ACTION_REF_NO,'Update','Active'
                        );
         ELSE
            --Qty Unit is Updated
            INSERT INTO DGRDL_DELIVERED_GRD_LOG
                        (INTERNAL_DGRD_REF_NO,
            ACTION_NO,
            INTERNAL_GMR_REF_NO,
            INT_ALLOC_GROUP_ID,
            CONTAINER_NO,
            SEAL_NO,
            MARK_NO,
            RELEASE_SHIPPED_NO_UNT_DELTA,
            OLD_NET_WEIGHT_DELTA,
            GROSS_WEIGHT_DELTA,
            TARE_WEIGHT_DELTA,
            NET_WEIGHT_DELTA,
            NET_WEIGHT_UNIT_ID,
            DISCHARGE_DATE,
            DISCHARGE_COUNTRY_ID,
            DISCHARGE_PORT_ID,
            FULFILLMENT_DATE,
            REMARKS,
            VESSEL_QTY_BEFOR_DISCRG_DELTA,
            IS_VOYAGE_STOCK,
            CONTAINER_SIZE,
            BL_DATE,
            BL_NUMBER,
            SHED_ID,
            REALIZED_QTY_DELTA,
            PARENT_DGRD_REF_NO,
            INTERNAL_STOCK_REF_NO,
            WAREHOUSE_REF_NO,
            WAREHOUSE_PROFILE_ID,
            WAREHOUSE_RECEIPT_NO,
            WAREHOUSE_RECEIPT_DATE,
            IS_FINAL_WEIGHT,
            BANK_ID,
            BANK_ACCOUNT_ID,
            INVENTORY_STATUS,
            IS_AFLOAT,
            CROP_YEAR_ID,
            CURRENT_QTY_DELTA,
            INTERNAL_CONTRACT_ITEM_REF_NO,
            IS_WEIGHT_FINAL,
            ORIGIN_ID,
            PACKING_SIZE_ID,
            PRODUCT_ID,
            PRODUCT_SPECS,
            QUALITY_ID,
            WRITE_OFF_QTY_DELTA,
            IS_WRITE_OFF,
            REALIZED_STATUS,
            REALIZED_DATE,
            REALIZED_CREATION_DATE,
            STOCK_STATUS,
            ITEM_PRICE_DELTA,
            ITEM_PRICE_UNIT,
            CURRENT_NO_OF_UNITS_DELTA,
            TOTAL_NO_OF_UNITS_DELTA,
            NO_OF_UNITS_DELTA,
            TOTAL_QTY_DELTA,
            PACKING_TYPE_ID,
            WRITE_OFF_NO_OF_UNITS_DELTA,
            HANDLED_AS,
            INTERNAL_GRD_REF_NO,
            STOCK_CONDITION,
            GRAVITY_TYPE_ID,
            GRAVITY_DELTA,
            DENSITY_MASS_QTY_UNIT_ID,
            DENSITY_VOLUME_QTY_UNIT_ID,
            GRAVITY_TYPE,
            CUSTOMS_ID,
            TAX_ID,
            DUTY_ID,
            PHY_ATTRIBUTE_GROUP_NO,
            ASSAY_HEADER_ID,
            CUSTOMER_SEAL_NO,
            BRAND,
            NO_OF_BAGS_DELTA,
            NO_OF_CONTAINERS_DELTA,
            NO_OF_PIECES_DELTA,
            P_SHIPPED_NET_WEIGHT_DELTA,
            P_SHIPPED_GROSS_WEIGHT_DELTA,
            P_SHIPPED_TARE_WEIGHT_DELTA,
            SDCTS_ID,
            PARTNERSHIP_TYPE,
            INTERNAL_ACTION_REF_NO,
            ENTRY_TYPE,
            STATUS
                        )
                 VALUES (:NEW.INTERNAL_DGRD_REF_NO,
                :NEW.ACTION_NO,
            :NEW.INTERNAL_GMR_REF_NO,
            :NEW.INT_ALLOC_GROUP_ID,
            :NEW.CONTAINER_NO,
            :NEW.SEAL_NO,
            :NEW.MARK_NO,
             :NEW.RELEASE_SHIPPED_NO_OF_UNITS - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.RELEASE_SHIPPED_NO_OF_UNITS
                                                            ),
             :NEW.OLD_NET_WEIGHT - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.OLD_NET_WEIGHT
                                                            ),
             :NEW.GROSS_WEIGHT - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.GROSS_WEIGHT
                                                            ),
             :NEW.TARE_WEIGHT - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.TARE_WEIGHT
                                                            ),
             :NEW.NET_WEIGHT - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.NET_WEIGHT
                                                            ),
             :NEW.NET_WEIGHT_UNIT_ID,
            :NEW.DISCHARGE_DATE,
            :NEW.DISCHARGE_COUNTRY_ID,
            :NEW.DISCHARGE_PORT_ID,
            :NEW.FULFILLMENT_DATE,
            :NEW.REMARKS,
            :NEW.VESSEL_QTY_BEFORE_DISCHARGE - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.VESSEL_QTY_BEFORE_DISCHARGE
                                                            ),
            :NEW.IS_VOYAGE_STOCK,
            :NEW.CONTAINER_SIZE,
            :NEW.BL_DATE,
            :NEW.BL_NUMBER,
            :NEW.SHED_ID,
            :NEW.REALIZED_QTY - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.REALIZED_QTY
                                                            ),
            :NEW.PARENT_DGRD_REF_NO,
            :NEW.INTERNAL_STOCK_REF_NO,
            :NEW.WAREHOUSE_REF_NO,
            :NEW.WAREHOUSE_PROFILE_ID,
            :NEW.WAREHOUSE_RECEIPT_NO,
            :NEW.WAREHOUSE_RECEIPT_DATE,
            :NEW.IS_FINAL_WEIGHT,
            :NEW.BANK_ID,
            :NEW.BANK_ACCOUNT_ID,
            :NEW.INVENTORY_STATUS,
            :NEW.IS_AFLOAT,
            :NEW.CROP_YEAR_ID,
            :NEW.CURRENT_QTY - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.CURRENT_QTY
                                                            ),
            :NEW.INTERNAL_CONTRACT_ITEM_REF_NO,
            :NEW.IS_WEIGHT_FINAL,
            :NEW.ORIGIN_ID,
            :NEW.PACKING_SIZE_ID,
            :NEW.PRODUCT_ID,
            :NEW.PRODUCT_SPECS,
            :NEW.QUALITY_ID,
            :NEW.WRITE_OFF_QTY - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.WRITE_OFF_QTY
                                                            ),
            :NEW.IS_WRITE_OFF,
            :NEW.REALIZED_STATUS,
            :NEW.REALIZED_DATE,
            :NEW.REALIZED_CREATION_DATE,
            :NEW.STOCK_STATUS,
            :NEW.ITEM_PRICE - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.ITEM_PRICE
                                                            ),
            :NEW.ITEM_PRICE_UNIT,
            :NEW.CURRENT_NO_OF_UNITS - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.CURRENT_NO_OF_UNITS
                                                            ),
            :NEW.TOTAL_NO_OF_UNITS - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.TOTAL_NO_OF_UNITS
                                                            ),
            :NEW.NO_OF_UNITS - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.NO_OF_UNITS
                                                            ),
            :NEW.TOTAL_QTY - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.TOTAL_QTY
                                                            ),
            :NEW.PACKING_TYPE_ID,
            :NEW.WRITE_OFF_NO_OF_UNITS - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.WRITE_OFF_NO_OF_UNITS
                                                            ),
            :NEW.HANDLED_AS,
            :NEW.INTERNAL_GRD_REF_NO,
            :NEW.STOCK_CONDITION,
            :NEW.GRAVITY_TYPE_ID,
            :NEW.GRAVITY - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.GRAVITY
                                                            ),
            :NEW.DENSITY_MASS_QTY_UNIT_ID,
            :NEW.DENSITY_VOLUME_QTY_UNIT_ID,
            :NEW.GRAVITY_TYPE,
            :NEW.CUSTOMS_ID,
            :NEW.TAX_ID,
            :NEW.DUTY_ID,
            :NEW.PHY_ATTRIBUTE_GROUP_NO,
            :NEW.ASSAY_HEADER_ID,
            :NEW.CUSTOMER_SEAL_NO,
            :NEW.BRAND,
            :NEW.NO_OF_BAGS - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.NO_OF_BAGS
                                                            ),
            :NEW.NO_OF_CONTAINERS - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.NO_OF_CONTAINERS
                                                            ),
            :NEW.NO_OF_PIECES - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.NO_OF_PIECES
                                                            ),
            :NEW.P_SHIPPED_NET_WEIGHT - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.P_SHIPPED_NET_WEIGHT
                                                            ),
            :NEW.P_SHIPPED_GROSS_WEIGHT - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.P_SHIPPED_GROSS_WEIGHT
                                                            ),
            :NEW.P_SHIPPED_TARE_WEIGHT - pkg_general.f_get_converted_quantity
                                                            (:NEW.PRODUCT_ID,
                                                             :OLD.NET_WEIGHT_UNIT_ID,
                                                             :NEW.NET_WEIGHT_UNIT_ID,
                                                             :OLD.P_SHIPPED_TARE_WEIGHT
                                                            ),
            :NEW.SDCTS_ID,
            :NEW.PARTNERSHIP_TYPE,
             :NEW.INTERNAL_ACTION_REF_NO,'Update','Active'
                        );
         END IF;
      ELSE
         -- Status is yes
         INSERT INTO DGRDL_DELIVERED_GRD_LOG
                        (INTERNAL_DGRD_REF_NO,
            ACTION_NO,
            INTERNAL_GMR_REF_NO,
            INT_ALLOC_GROUP_ID,
            CONTAINER_NO,
            SEAL_NO,
            MARK_NO,
            RELEASE_SHIPPED_NO_UNT_DELTA,
            OLD_NET_WEIGHT_DELTA,
            GROSS_WEIGHT_DELTA,
            TARE_WEIGHT_DELTA,
            NET_WEIGHT_DELTA,
            NET_WEIGHT_UNIT_ID,
            DISCHARGE_DATE,
            DISCHARGE_COUNTRY_ID,
            DISCHARGE_PORT_ID,
            FULFILLMENT_DATE,
            REMARKS,
            VESSEL_QTY_BEFOR_DISCRG_DELTA,
            IS_VOYAGE_STOCK,
            CONTAINER_SIZE,
            BL_DATE,
            BL_NUMBER,
            SHED_ID,
            REALIZED_QTY_DELTA,
            PARENT_DGRD_REF_NO,
            INTERNAL_STOCK_REF_NO,
            WAREHOUSE_REF_NO,
            WAREHOUSE_PROFILE_ID,
            WAREHOUSE_RECEIPT_NO,
            WAREHOUSE_RECEIPT_DATE,
            IS_FINAL_WEIGHT,
            BANK_ID,
            BANK_ACCOUNT_ID,
            INVENTORY_STATUS,
            IS_AFLOAT,
            CROP_YEAR_ID,
            CURRENT_QTY_DELTA,
            INTERNAL_CONTRACT_ITEM_REF_NO,
            IS_WEIGHT_FINAL,
            ORIGIN_ID,
            PACKING_SIZE_ID,
            PRODUCT_ID,
            PRODUCT_SPECS,
            QUALITY_ID,
            WRITE_OFF_QTY_DELTA,
            IS_WRITE_OFF,
            REALIZED_STATUS,
            REALIZED_DATE,
            REALIZED_CREATION_DATE,
            STOCK_STATUS,
            ITEM_PRICE_DELTA,
            ITEM_PRICE_UNIT,
            CURRENT_NO_OF_UNITS_DELTA,
            TOTAL_NO_OF_UNITS_DELTA,
            NO_OF_UNITS_DELTA,
            TOTAL_QTY_DELTA,
            PACKING_TYPE_ID,
            WRITE_OFF_NO_OF_UNITS_DELTA,
            HANDLED_AS,
            INTERNAL_GRD_REF_NO,
            STOCK_CONDITION,
            GRAVITY_TYPE_ID,
            GRAVITY_DELTA,
            DENSITY_MASS_QTY_UNIT_ID,
            DENSITY_VOLUME_QTY_UNIT_ID,
            GRAVITY_TYPE,
            CUSTOMS_ID,
            TAX_ID,
            DUTY_ID,
            PHY_ATTRIBUTE_GROUP_NO,
            ASSAY_HEADER_ID,
            CUSTOMER_SEAL_NO,
            BRAND,
            NO_OF_BAGS_DELTA,
            NO_OF_CONTAINERS_DELTA,
            NO_OF_PIECES_DELTA,
            P_SHIPPED_NET_WEIGHT_DELTA,
            P_SHIPPED_GROSS_WEIGHT_DELTA,
            P_SHIPPED_TARE_WEIGHT_DELTA,
            SDCTS_ID,
            PARTNERSHIP_TYPE,
            INTERNAL_ACTION_REF_NO,
            ENTRY_TYPE,
            STATUS
                        )
                 VALUES (:NEW.INTERNAL_DGRD_REF_NO,
                :NEW.ACTION_NO,
            :NEW.INTERNAL_GMR_REF_NO,
            :NEW.INT_ALLOC_GROUP_ID,
            :NEW.CONTAINER_NO,
            :NEW.SEAL_NO,
            :NEW.MARK_NO,
             :NEW.RELEASE_SHIPPED_NO_OF_UNITS - :OLD.RELEASE_SHIPPED_NO_OF_UNITS,
             :NEW.OLD_NET_WEIGHT - :OLD.OLD_NET_WEIGHT,
             :NEW.GROSS_WEIGHT - :OLD.GROSS_WEIGHT,
             :NEW.TARE_WEIGHT - :OLD.TARE_WEIGHT,
             :NEW.NET_WEIGHT - :OLD.NET_WEIGHT,
             :NEW.NET_WEIGHT_UNIT_ID,
            :NEW.DISCHARGE_DATE,
            :NEW.DISCHARGE_COUNTRY_ID,
            :NEW.DISCHARGE_PORT_ID,
            :NEW.FULFILLMENT_DATE,
            :NEW.REMARKS,
            :NEW.VESSEL_QTY_BEFORE_DISCHARGE - :OLD.VESSEL_QTY_BEFORE_DISCHARGE,
            :NEW.IS_VOYAGE_STOCK,
            :NEW.CONTAINER_SIZE,
            :NEW.BL_DATE,
            :NEW.BL_NUMBER,
            :NEW.SHED_ID,
            :NEW.REALIZED_QTY - :OLD.REALIZED_QTY,
            :NEW.PARENT_DGRD_REF_NO,
            :NEW.INTERNAL_STOCK_REF_NO,
            :NEW.WAREHOUSE_REF_NO,
            :NEW.WAREHOUSE_PROFILE_ID,
            :NEW.WAREHOUSE_RECEIPT_NO,
            :NEW.WAREHOUSE_RECEIPT_DATE,
            :NEW.IS_FINAL_WEIGHT,
            :NEW.BANK_ID,
            :NEW.BANK_ACCOUNT_ID,
            :NEW.INVENTORY_STATUS,
            :NEW.IS_AFLOAT,
            :NEW.CROP_YEAR_ID,
            :NEW.CURRENT_QTY - :OLD.CURRENT_QTY,
            :NEW.INTERNAL_CONTRACT_ITEM_REF_NO,
            :NEW.IS_WEIGHT_FINAL,
            :NEW.ORIGIN_ID,
            :NEW.PACKING_SIZE_ID,
            :NEW.PRODUCT_ID,
            :NEW.PRODUCT_SPECS,
            :NEW.QUALITY_ID,
            :NEW.WRITE_OFF_QTY - :OLD.WRITE_OFF_QTY,
            :NEW.IS_WRITE_OFF,
            :NEW.REALIZED_STATUS,
            :NEW.REALIZED_DATE,
            :NEW.REALIZED_CREATION_DATE,
            :NEW.STOCK_STATUS,
            :NEW.ITEM_PRICE - :OLD.ITEM_PRICE,
            :NEW.ITEM_PRICE_UNIT,
            :NEW.CURRENT_NO_OF_UNITS - :OLD.CURRENT_NO_OF_UNITS,
            :NEW.TOTAL_NO_OF_UNITS - :OLD.TOTAL_NO_OF_UNITS,
            :NEW.NO_OF_UNITS - :OLD.NO_OF_UNITS,
            :NEW.TOTAL_QTY - :OLD.TOTAL_QTY,
            :NEW.PACKING_TYPE_ID,
            :NEW.WRITE_OFF_NO_OF_UNITS - :OLD.WRITE_OFF_NO_OF_UNITS,
            :NEW.HANDLED_AS,
            :NEW.INTERNAL_GRD_REF_NO,
            :NEW.STOCK_CONDITION,
            :NEW.GRAVITY_TYPE_ID,
            :NEW.GRAVITY - :OLD.GRAVITY,
            :NEW.DENSITY_MASS_QTY_UNIT_ID,
            :NEW.DENSITY_VOLUME_QTY_UNIT_ID,
            :NEW.GRAVITY_TYPE,
            :NEW.CUSTOMS_ID,
            :NEW.TAX_ID,
            :NEW.DUTY_ID,
            :NEW.PHY_ATTRIBUTE_GROUP_NO,
            :NEW.ASSAY_HEADER_ID,
            :NEW.CUSTOMER_SEAL_NO,
            :NEW.BRAND,
            :NEW.NO_OF_BAGS - :OLD.NO_OF_BAGS,
            :NEW.NO_OF_CONTAINERS - :OLD.NO_OF_CONTAINERS,
            :NEW.NO_OF_PIECES - :OLD.NO_OF_PIECES,
            :NEW.P_SHIPPED_NET_WEIGHT - :OLD.P_SHIPPED_NET_WEIGHT,
            :NEW.P_SHIPPED_GROSS_WEIGHT - :OLD.P_SHIPPED_GROSS_WEIGHT,
            :NEW.P_SHIPPED_TARE_WEIGHT - :OLD.P_SHIPPED_TARE_WEIGHT,
            :NEW.SDCTS_ID,
            :NEW.PARTNERSHIP_TYPE,
             :NEW.INTERNAL_ACTION_REF_NO,'Update','Inactive'
                        );
      END IF;
   ELSE
      --
      -- New Entry ( Entry Type=Insert)
      --
      INSERT INTO DGRDL_DELIVERED_GRD_LOG
                        (INTERNAL_DGRD_REF_NO,
            ACTION_NO,
            INTERNAL_GMR_REF_NO,
            INT_ALLOC_GROUP_ID,
            CONTAINER_NO,
            SEAL_NO,
            MARK_NO,
            RELEASE_SHIPPED_NO_UNT_DELTA,
            OLD_NET_WEIGHT_DELTA,
            GROSS_WEIGHT_DELTA,
            TARE_WEIGHT_DELTA,
            NET_WEIGHT_DELTA,
            NET_WEIGHT_UNIT_ID,
            DISCHARGE_DATE,
            DISCHARGE_COUNTRY_ID,
            DISCHARGE_PORT_ID,
            FULFILLMENT_DATE,
            REMARKS,
            VESSEL_QTY_BEFOR_DISCRG_DELTA,
            IS_VOYAGE_STOCK,
            CONTAINER_SIZE,
            BL_DATE,
            BL_NUMBER,
            SHED_ID,
            REALIZED_QTY_DELTA,
            PARENT_DGRD_REF_NO,
            INTERNAL_STOCK_REF_NO,
            WAREHOUSE_REF_NO,
            WAREHOUSE_PROFILE_ID,
            WAREHOUSE_RECEIPT_NO,
            WAREHOUSE_RECEIPT_DATE,
            IS_FINAL_WEIGHT,
            BANK_ID,
            BANK_ACCOUNT_ID,
            INVENTORY_STATUS,
            IS_AFLOAT,
            CROP_YEAR_ID,
            CURRENT_QTY_DELTA,
            INTERNAL_CONTRACT_ITEM_REF_NO,
            IS_WEIGHT_FINAL,
            ORIGIN_ID,
            PACKING_SIZE_ID,
            PRODUCT_ID,
            PRODUCT_SPECS,
            QUALITY_ID,
            WRITE_OFF_QTY_DELTA,
            IS_WRITE_OFF,
            REALIZED_STATUS,
            REALIZED_DATE,
            REALIZED_CREATION_DATE,
            STOCK_STATUS,
            ITEM_PRICE_DELTA,
            ITEM_PRICE_UNIT,
            CURRENT_NO_OF_UNITS_DELTA,
            TOTAL_NO_OF_UNITS_DELTA,
            NO_OF_UNITS_DELTA,
            TOTAL_QTY_DELTA,
            PACKING_TYPE_ID,
            WRITE_OFF_NO_OF_UNITS_DELTA,
            HANDLED_AS,
            INTERNAL_GRD_REF_NO,
            STOCK_CONDITION,
            GRAVITY_TYPE_ID,
            GRAVITY_DELTA,
            DENSITY_MASS_QTY_UNIT_ID,
            DENSITY_VOLUME_QTY_UNIT_ID,
            GRAVITY_TYPE,
            CUSTOMS_ID,
            TAX_ID,
            DUTY_ID,
            PHY_ATTRIBUTE_GROUP_NO,
            ASSAY_HEADER_ID,
            CUSTOMER_SEAL_NO,
            BRAND,
            NO_OF_BAGS_DELTA,
            NO_OF_CONTAINERS_DELTA,
            NO_OF_PIECES_DELTA,
            P_SHIPPED_NET_WEIGHT_DELTA,
            P_SHIPPED_GROSS_WEIGHT_DELTA,
            P_SHIPPED_TARE_WEIGHT_DELTA,
            SDCTS_ID,
            PARTNERSHIP_TYPE,
            INTERNAL_ACTION_REF_NO,
            ENTRY_TYPE,
            STATUS
                        )
                 VALUES (:NEW.INTERNAL_DGRD_REF_NO,
                :NEW.ACTION_NO,
            :NEW.INTERNAL_GMR_REF_NO,
            :NEW.INT_ALLOC_GROUP_ID,
            :NEW.CONTAINER_NO,
            :NEW.SEAL_NO,
            :NEW.MARK_NO,
             :NEW.RELEASE_SHIPPED_NO_OF_UNITS,
             :NEW.OLD_NET_WEIGHT,
             :NEW.GROSS_WEIGHT,
             :NEW.TARE_WEIGHT,
             :NEW.NET_WEIGHT,
             :NEW.NET_WEIGHT_UNIT_ID,
            :NEW.DISCHARGE_DATE,
            :NEW.DISCHARGE_COUNTRY_ID,
            :NEW.DISCHARGE_PORT_ID,
            :NEW.FULFILLMENT_DATE,
            :NEW.REMARKS,
            :NEW.VESSEL_QTY_BEFORE_DISCHARGE,
            :NEW.IS_VOYAGE_STOCK,
            :NEW.CONTAINER_SIZE,
            :NEW.BL_DATE,
            :NEW.BL_NUMBER,
            :NEW.SHED_ID,
            :NEW.REALIZED_QTY,
            :NEW.PARENT_DGRD_REF_NO,
            :NEW.INTERNAL_STOCK_REF_NO,
            :NEW.WAREHOUSE_REF_NO,
            :NEW.WAREHOUSE_PROFILE_ID,
            :NEW.WAREHOUSE_RECEIPT_NO,
            :NEW.WAREHOUSE_RECEIPT_DATE,
            :NEW.IS_FINAL_WEIGHT,
            :NEW.BANK_ID,
            :NEW.BANK_ACCOUNT_ID,
            :NEW.INVENTORY_STATUS,
            :NEW.IS_AFLOAT,
            :NEW.CROP_YEAR_ID,
            :NEW.CURRENT_QTY,
            :NEW.INTERNAL_CONTRACT_ITEM_REF_NO,
            :NEW.IS_WEIGHT_FINAL,
            :NEW.ORIGIN_ID,
            :NEW.PACKING_SIZE_ID,
            :NEW.PRODUCT_ID,
            :NEW.PRODUCT_SPECS,
            :NEW.QUALITY_ID,
            :NEW.WRITE_OFF_QTY,
            :NEW.IS_WRITE_OFF,
            :NEW.REALIZED_STATUS,
            :NEW.REALIZED_DATE,
            :NEW.REALIZED_CREATION_DATE,
            :NEW.STOCK_STATUS,
            :NEW.ITEM_PRICE,
            :NEW.ITEM_PRICE_UNIT,
            :NEW.CURRENT_NO_OF_UNITS,
            :NEW.TOTAL_NO_OF_UNITS,
            :NEW.NO_OF_UNITS,
            :NEW.TOTAL_QTY,
            :NEW.PACKING_TYPE_ID,
            :NEW.WRITE_OFF_NO_OF_UNITS,
            :NEW.HANDLED_AS,
            :NEW.INTERNAL_GRD_REF_NO,
            :NEW.STOCK_CONDITION,
            :NEW.GRAVITY_TYPE_ID,
            :NEW.GRAVITY,
            :NEW.DENSITY_MASS_QTY_UNIT_ID,
            :NEW.DENSITY_VOLUME_QTY_UNIT_ID,
            :NEW.GRAVITY_TYPE,
            :NEW.CUSTOMS_ID,
            :NEW.TAX_ID,
            :NEW.DUTY_ID,
            :NEW.PHY_ATTRIBUTE_GROUP_NO,
            :NEW.ASSAY_HEADER_ID,
            :NEW.CUSTOMER_SEAL_NO,
            :NEW.BRAND,
            :NEW.NO_OF_BAGS,
            :NEW.NO_OF_CONTAINERS,
            :NEW.NO_OF_PIECES,
            :NEW.P_SHIPPED_NET_WEIGHT,
            :NEW.P_SHIPPED_GROSS_WEIGHT,
            :NEW.P_SHIPPED_TARE_WEIGHT,
            :NEW.SDCTS_ID,
            :NEW.PARTNERSHIP_TYPE,
             :NEW.INTERNAL_ACTION_REF_NO,'Insert','Active'
                        );
   END IF;
    INSERT INTO ACI_ASSAY_CONTENT_UPDATE_INPUT
			(INTERNAL_GRD_NO,CONT_TYPE, 
			ASH_ID, IS_DELETED) 
		VALUES (:NEW.INTERNAL_DGRD_REF_NO,
			'DGRD',NULL, 'N'
		       );
END;
/

