ALTER TABLE TMPC_TEMP_M2M_PRE_CHECK ADD QP_END_DATE DATE;

ALTER TABLE    PCI_PHYSICAL_CONTRACT_ITEM ADD
(PRICE_BASIS VARCHAR2(30),
QP_START_DATE DATE,
QP_END_DATE DATE,
QP_PERIOD_TYPE VARCHAR2(30),
PCBPD_ID VARCHAR2(15));

ALTER TABLE PCI_PHYSICAL_CONTRACT_ITEM ADD(price_option_call_off_status VARCHAR2(30));