SET DEFINE OFF;
Insert into AMC_APP_MENU_CONFIGURATION (MENU_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, LINK_CALLED, ICON_CLASS, MENU_PARENT_ID, ACL_ID, TAB_ID, FEATURE_ID,IS_DELETED)
Values ('BI-19', 'Risk Dashboard', 1, 2, '/metalRiskExposureDashboardForwardServlet', NULL, 'BI-1', 'APP-ACL-N897', 'iEka', 'APP-PFL-N-161', 'N');
Insert into AMC_APP_MENU_CONFIGURATION (MENU_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, LINK_CALLED, ICON_CLASS, MENU_PARENT_ID, ACL_ID, TAB_ID, FEATURE_ID,IS_DELETED)
Values ('BI-20', 'P&L Attribute Dashboard', 1, 2, '/attributePnlDashboardForwardServlet', NULL, 'BI-1', 'APP-ACL-N897', 'iEka', 'APP-PFL-N-161', 'N');
Insert into AMC_APP_MENU_CONFIGURATION (MENU_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, LINK_CALLED, ICON_CLASS, MENU_PARENT_ID, ACL_ID, TAB_ID, FEATURE_ID,IS_DELETED)
Values ('BI-21', 'KYC Dashboard', 1, 2, '/attributePnlDashboardForwardServlet', NULL, 'BI-1', 'APP-ACL-N897', 'iEka', 'APP-PFL-N-161', 'N');
COMMIT;
