INSERT INTO AXM_ACTION_MASTER
   (ACTION_ID, ENTITY_ID, ACTION_NAME, IS_NEW_GMR_APPLICABLE, ACTION_DESC, 
    IS_GENERATE_DOC_APPLICABLE, IS_REF_NO_GEN_APPLICABLE)
 VALUES
   ('CANCEL_WNS_ASSAY', 'WS Assay', 'Cancel WS Assay', 'N', 'Cancel WS Assay', 
    'N', NULL);


INSERT INTO CAC_CORPORATE_ACTION_CONFIG
   (ACTION_ID, IS_ACCRUAL_POSSIBLE, IS_ESTIMATE_POSSIBLE, EFF_DATE_FIELD, IS_DOC_APPLICABLE, 
    GMR_STATUS_ID, SHIPMENT_STATUS, IS_AFLOAT, IS_INV_POSTING_REQD)
 VALUES
   ('CANCEL_WNS_ASSAY', 'N', 'N', 'activityDate', 'N', 
    null, 'In Warehouse', 'N', 'N');

Insert into GMC_GRID_MENU_CONFIGURATION
   (MENU_ID, GRID_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, 
    FEATURE_ID, LINK_CALLED, ICON_CLASS, MENU_PARENT_ID, ACL_ID)
 Values
   ('MLOCI_1', 'MLOCI', 'Purchase Operations', 2, 1, 
    NULL, 'function(){}', NULL, NULL, NULL);

Insert into GMC_GRID_MENU_CONFIGURATION
   (MENU_ID, GRID_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, 
    FEATURE_ID, LINK_CALLED, ICON_CLASS, MENU_PARENT_ID, ACL_ID)
 Values
   ('MLOCI_1_2', 'MLOCI', 'Shipment Details', 1, 2, 
    NULL, 'function(){shipmentDetails();}', NULL, 'MLOCI_1', NULL);

Insert into GMC_GRID_MENU_CONFIGURATION
   (MENU_ID, GRID_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, 
    FEATURE_ID, LINK_CALLED, ICON_CLASS, MENU_PARENT_ID, ACL_ID)
 Values
   ('MLOCI_1_1', 'MLOCI', 'Warehouse Receipt', 2, 2, 
    NULL, 'function(){warehouseReceipt();}', NULL, 'MLOCI_1', NULL);