DECLARE fetchQueryISDOCI clob :='INSERT INTO IS_D(
INTERNAL_INVOICE_REF_NO,
INVOICE_REF_NO,
CP_NAME,
SUPPLIRE_INVOICE_NO,
CP_ADDRESS,
CP_COUNTRY,
CP_CITY,
CP_STATE,
CP_ZIP,
INVOICE_CREATION_DATE,
DUE_DATE,
PAYMENT_TERM,
CONTRACT_TYPE,
internal_comments, invoice_status,invoice_amount, adjustment_amount, invoice_amount_unit, our_person_incharge, internal_doc_ref_no
)
select
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
INVS.INVOICE_REF_NO as INVOICE_REF_NO,
PHD.COMPANYNAME as CP_NAME,
INVS.CP_REF_NO as SUPPLIRE_INVOICE_NO,
PAD.ADDRESS as CP_ADDRESS,
CYM.COUNTRY_NAME as CP_COUNTRY,
CIM.CITY_NAME as CP_CITY,
SM.STATE_NAME as CP_STATE,
PAD.ZIP as CP_ZIP,
INVS.INVOICE_ISSUE_DATE as INVOICE_CREATION_DATE,
INVS.PAYMENT_DUE_DATE as DUE_DATE,
PYM.PAYMENT_TERM as PAYMENT_TERM,
INVS.RECIEVED_RAISED_TYPE as CONTRACT_TYPE, INVS.INTERNAL_COMMENTS as internal_comments, INVS.INVOICE_STATUS as invoice_status, INVS.TOTAL_AMOUNT_TO_PAY as invoice_amount,
invs.invoice_adjustment_amount As adjustment_amount, cm.cur_code AS invoice_amount_unit, (GAB.FIRSTNAME||'' ''||GAB.LASTNAME) as our_person_incharge, ?
from
IS_INVOICE_SUMMARY invs,
PHD_PROFILEHEADERDETAILS phd,
PYM_PAYMENT_TERMS_MASTER pym,
CM_CURRENCY_MASTER cm,
IAM_INVOICE_ACTION_MAPPING iam,
AXS_ACTION_SUMMARY axs,
AK_CORPORATE_USER akuser,
GAB_GLOBALADDRESSBOOK gab,
PAD_PROFILE_ADDRESSES pad,
CYM_COUNTRYMASTER cym,
CIM_CITYMASTER cim,
SM_STATE_MASTER sm
where
INVS.CP_ID = PHD.PROFILEID
and PHD.PROFILEID = PAD.PROFILE_ID(+)
and PAD.COUNTRY_ID = CYM.COUNTRY_ID(+)
and PAD.CITY_ID = CIM.CITY_ID(+)
and PAD.STATE_ID = SM.STATE_ID(+)
and PAD.ADDRESS_TYPE(+) = ''Billing''
AND INVS.INVOICE_CUR_ID = CM.CUR_ID
and PYM.PAYMENT_TERM_ID(+) = INVS.CREDIT_TERM 
And INVS.INTERNAL_INVOICE_REF_NO = IAM.INTERNAL_INVOICE_REF_NO
AND IAM.INVOICE_ACTION_REF_NO = AXS.INTERNAL_ACTION_REF_NO
AND AXS.CREATED_BY = AKUSER.USER_ID
AND AKUSER.GABID = GAB.GABID
and INVS.INTERNAL_INVOICE_REF_NO = ?';

BEGIN
    UPDATE DGM_DOCUMENT_GENERATION_MASTER DGM SET DGM.FETCH_QUERY = fetchQueryISDOCI WHERE DGM.DGM_ID='DGM_OCI_1' AND DGM.DOC_ID='CREATE_OCI' AND DGM.SEQUENCE_ORDER=1 AND DGM.IS_CONCENTRATE='N';
COMMIT;
END;