DECLARE
   fetchqueryfor_api_d   CLOB
      := 'INSERT INTO API_D (
INTERNAL_INVOICE_REF_NO,
CONTRACT_REF_NO,
PRODUCT,
INVOICE_QUANTITY,
INVOICE_QUANTITY_UNIT,
QUALITY,
INVOICE_AMOUNT_UNIT,
INVOICE_AMOUNT,
PRICE,
PRICE_UNIT,
INVOICE_ITEM_AMOUNT,
INTERNAL_DOC_REF_NO
)
select
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
PCM.CONTRACT_REF_NO as CONTRACT_REF_NO,
PDM.PRODUCT_DESC as PRODUCT,
APID.INVOICE_ITEM_QTY as INVOICE_QUANTITY,
QUM.QTY_UNIT as INVOICE_QUANTITY_UNIT,
QAT.QUALITY_NAME as QUALITY,
CM.CUR_CODE as INVOICE_AMOUNT_UNIT,
INVS.TOTAL_AMOUNT_TO_PAY as INVOICE_AMOUNT,
APID.INVOICE_ITEM_PRICE as PRICE,
PUM.PRICE_UNIT_NAME as PRICE_UNIT,
APID.INVOICE_ITEM_AMOUNT as INVOICE_ITEM_AMOUNT,
?
from
IS_INVOICE_SUMMARY invs,
APID_ADV_PAYMENT_ITEM_DETAILS apid,
PCM_PHYSICAL_CONTRACT_MAIN pcm,
PCI_PHYSICAL_CONTRACT_ITEM pci,
PDM_PRODUCTMASTER pdm,
QAT_QUALITY_ATTRIBUTES qat,
PCPD_PC_PRODUCT_DEFINITION pcpd,
CM_CURRENCY_MASTER cm,
QUM_QUANTITY_UNIT_MASTER qum,
PPU_PRODUCT_PRICE_UNITS ppu,
PUM_PRICE_UNIT_MASTER pum,
PCPQ_PC_PRODUCT_QUALITY pcpq
where
INVS.INTERNAL_INVOICE_REF_NO = APID.INTERNAL_INVOICE_REF_NO
and APID.CONTRACT_ITEM_REF_NO = PCI.INTERNAL_CONTRACT_ITEM_REF_NO
and INVS.INTERNAL_CONTRACT_REF_NO = PCM.INTERNAL_CONTRACT_REF_NO
and PCPD.INTERNAL_CONTRACT_REF_NO = PCM.INTERNAL_CONTRACT_REF_NO
and PCPD.PRODUCT_ID = PDM.PRODUCT_ID
and PCPD.QTY_UNIT_ID = QUM.QTY_UNIT_ID
and PCPD.INPUT_OUTPUT = ''Input''
and PCI.PCPQ_ID = PCPQ.PCPQ_ID
and PCPQ.PCPD_ID = PCPD.PCPD_ID
and PCPQ.QUALITY_TEMPLATE_ID = QAT.QUALITY_ID
and INVS.INVOICE_CUR_ID = CM.CUR_ID
and APID.INVOICE_ITEM_PRICE_UNIT_ID = PPU.INTERNAL_PRICE_UNIT_ID(+)
and PPU.PRICE_UNIT_ID = PUM.PRICE_UNIT_ID
and INVS.INTERNAL_INVOICE_REF_NO = ?
group by
PCM.CONTRACT_REF_NO,
PDM.PRODUCT_DESC,
QAT.QUALITY_NAME,
INVS.TOTAL_AMOUNT_TO_PAY,
CM.CUR_CODE,
INVS.INVOICE_STATUS,
INVS.TOTAL_TAX_AMOUNT,
INVS.TOTAL_OTHER_CHARGE_AMOUNT,
APID.INVOICE_ITEM_PRICE,
PUM.PRICE_UNIT_NAME,
INVS.INTERNAL_INVOICE_REF_NO,
QUM.QTY_UNIT,
INVOICE_ITEM_AMOUNT,
APID.INVOICE_ITEM_QTY';
BEGIN
   UPDATE dgm_document_generation_master dgm
      SET dgm.fetch_query = fetchqueryfor_api_d
    WHERE dgm.doc_id = 'CREATE_API'
      AND dgm.dgm_id = 'DGM-API-1'
      AND dgm.is_concentrate = 'N'
      AND dgm.sequence_order = 2;

   UPDATE dgm_document_generation_master dgm
      SET dgm.fetch_query = fetchqueryfor_api_d
    WHERE dgm.doc_id = 'CREATE_API'
      AND dgm.dgm_id = 'DGM-API-1-CONC'
      AND dgm.is_concentrate = 'Y'
      AND dgm.sequence_order = 2;

   COMMIT;
END;