update ERC_EXTERNAL_REF_NO_CONFIG erc set ERC.MIDDLE_NO_LAST_USED_VALUE = 400005 where ERC.EXTERNAL_REF_NO_KEY = 'PROV_INV_REF_NO';
update ERC_EXTERNAL_REF_NO_CONFIG erc set ERC.MIDDLE_NO_LAST_USED_VALUE = 499999 where ERC.EXTERNAL_REF_NO_KEY = 'FINAL_INV_REF_NO';
update ERC_EXTERNAL_REF_NO_CONFIG erc set ERC.MIDDLE_NO_LAST_USED_VALUE = 599999 where ERC.EXTERNAL_REF_NO_KEY = 'DIRECT_FINAL_INV_REF_NO';
update ERC_EXTERNAL_REF_NO_CONFIG erc set ERC.MIDDLE_NO_LAST_USED_VALUE = 699999 where ERC.EXTERNAL_REF_NO_KEY = 'VAT_INV_REF_NO';