Insert into GMC_GRID_MENU_CONFIGURATION
   (MENU_ID, GRID_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, 
    FEATURE_ID, LINK_CALLED, ICON_CLASS, MENU_PARENT_ID, ACL_ID)
 Values
   ('MLOCI_1_4', 'MLOCI', 'Truck Details', 3, 2, 
    NULL, 'function(){truckDetail();}', NULL, 'MLOCI_1', NULL);

Insert into GMC_GRID_MENU_CONFIGURATION
   (MENU_ID, GRID_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, 
    FEATURE_ID, LINK_CALLED, ICON_CLASS, MENU_PARENT_ID, ACL_ID)
 Values
   ('MLOCI_1_3', 'MLOCI', 'Airway bill',4, 2, 
    NULL, 'function(){airDetail();}', NULL, 'MLOCI_1', NULL);

Insert into GMC_GRID_MENU_CONFIGURATION
   (MENU_ID, GRID_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, 
    FEATURE_ID, LINK_CALLED, ICON_CLASS, MENU_PARENT_ID, ACL_ID)
 Values
   ('MLOCI_1_5', 'MLOCI', 'RailDetails', 5, 2, 
    NULL, 'function(){railDetail();}', NULL, 'MLOCI_1', NULL);