SET DEFINE OFF;
Insert into AMC_APP_MENU_CONFIGURATION
   (MENU_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, LINK_CALLED, 
    ICON_CLASS, MENU_PARENT_ID, ACL_ID, TAB_ID, FEATURE_ID, 
    IS_DELETED)
 Values
   ('RPT-D24', 'MBV', 14, 4, NULL, 
    NULL, 'RPT-D2', 'APP-ACL-N1278', 'Reports', 'APP-PFL-N-212', 
    'N');

UPDATE AMC_APP_MENU_CONFIGURATION AMC
SET AMC.MENU_PARENT_ID ='RPT-D24'
WHERE menu_id in ( 'RPT-D369','RPT-D370','RPT-D371','RPT-D372','RPT-D373','RPT-D374');
COMMIT;
