Insert into DGM_DOCUMENT_GENERATION_MASTER
   (DGM_ID, DOC_ID, DOC_NAME, ACTIVITY_ID, SEQUENCE_ORDER, 
    FETCH_QUERY, IS_CONCENTRATE)
 Values
   ('DGM-PFI-1', 'CREATE_PFI', 'Profoma Invoice', 'CREATE_PFI', 1, 
    'INSERT into PFI_D(
INTERNAL_INVOICE_REF_NO,
INVOICE_REF_NO,
CP_NAME,
INCO_TERM_LOCATION,
INVOICE_QUANTITY,
INVOICE_QUANTITY_UNIT,
INVOICE_AMOUNT,
INVOICE_AMOUNT_UNIT,
PAYMENT_TERM,
CP_ITEM_STOCK_REF_NO,
SELF_ITEM_STOCK_REF_NO,
DOCUMENT_DATE,
INTERNAL_COMMENTS,
PRODUCT,
QUALITY,
NOTIFY_PARTY,
INVOICE_ISSUE_DATE,
ORIGIN,
DOC_REF_NO,
CONTRACT_TYPE,
INVOICE_STATUS,
SALES_PURCHASE,
INTERNAL_DOC_REF_NO
)
select INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
INVS.INVOICE_REF_NO as INVOICE_REF_NO,
PHD.COMPANYNAME as CP_NAME, PCI.TERMS as INCO_TERM_LOCATION, 
sum(PFID.INVOICED_QTY) as INVOICE_QUANTITY,
QUM.QTY_UNIT as INVOICE_QUANTITY_UNIT,
sum(PFID.INVOICE_ITEM_AMOUNT) as INVOICE_AMOUNT,
CM.CUR_CODE as INVOICE_AMOUNT_UNIT,
PYM.PAYMENT_TERM as PAYMENT_TERM,
INVS.CP_REF_NO as CP_ITEM_STOCK_REF_NO,
'''' as SELF_ITEM_STOCK_REF_NO,
TO_CHAR(INVS.INVOICE_ISSUE_DATE,''dd-Mon-yyyy'') as DOCUMENT_DATE,
INVS.INTERNAL_COMMENTS as INTERNAL_COMMENTS,
PDM.PRODUCT_DESC as PRODUCT,
QAT.QUALITY_NAME as QUALITY,
'''' as NOTIFY_PARTY,
TO_CHAR(INVS.INVOICE_ISSUE_DATE,''dd-Mon-yyyy'') as INVOICE_ISSUE_DATE,
'''' as ORIGIN,
'''' as DOC_REF_NO,
PCM.CONTRACT_TYPE as CONTRACT_TYPE,
invs.INVOICE_STATUS as INVOICE_STATUS,
PCM.PURCHASE_SALES as SALES_PURCHASE,
?
from
PFID_PROFOMA_INVOICE_DETAILS pfid,
IS_INVOICE_SUMMARY invs,
PCM_PHYSICAL_CONTRACT_MAIN pcm,
v_pci pci,
PHD_PROFILEHEADERDETAILS phd,
PCPD_PC_PRODUCT_DEFINITION pcpd,
PYM_PAYMENT_TERMS_MASTER pym,
CM_CURRENCY_MASTER cm,
QAT_QUALITY_ATTRIBUTES qat,
PDM_PRODUCTMASTER pdm,
QUM_QUANTITY_UNIT_MASTER qum
where
INVS.INTERNAL_INVOICE_REF_NO = PFID.INTERNAL_INVOICE_REF_NO
and PFID.INTERNAL_CONTRACT_ITEM_REF_NO = PCI.INTERNAL_CONTRACT_ITEM_REF_NO
and PCM.INTERNAL_CONTRACT_REF_NO = INVS.INTERNAL_CONTRACT_REF_NO
and PCPD.INTERNAL_CONTRACT_REF_NO = PCM.INTERNAL_CONTRACT_REF_NO
and PCPD.PRODUCT_ID = PDM.PRODUCT_ID
and PCPD.QTY_UNIT_ID = QUM.QTY_UNIT_ID
and PCI.QUALITY_ID = QAT.QUALITY_ID
AND PCM.CP_ID = PHD.PROFILEID(+)
and INVS.INVOICE_CUR_ID = CM.CUR_ID
and INVS.CREDIT_TERM = PYM.PAYMENT_TERM_ID
and INVS.INTERNAL_INVOICE_REF_NO = ?
group by
INVS.INTERNAL_INVOICE_REF_NO,
INVS.INVOICE_REF_NO,
PFID.INVOICED_QTY,
PYM.PAYMENT_TERM,
PCI.TERMS,
PHD.COMPANYNAME,
INVS.CP_REF_NO,
INVS.INVOICE_ISSUE_DATE,
INVS.INTERNAL_COMMENTS,
PFID.INVOICE_ITEM_AMOUNT,
PDM.PRODUCT_DESC,
QAT.QUALITY_NAME,
PCM.CONTRACT_TYPE,
PCM.PURCHASE_SALES,
INVS.INVOICE_STATUS,
CM.CUR_CODE,
QUM.QTY_UNIT', 'N');

Insert into DGM_DOCUMENT_GENERATION_MASTER
   (DGM_ID, DOC_ID, DOC_NAME, ACTIVITY_ID, SEQUENCE_ORDER, 
    FETCH_QUERY, IS_CONCENTRATE)
 Values
   ('DGM-PFI-2', 'CREATE_PFI', 'Profoma Invoice', 'CREATE_PFI', 2, 
    'INSERT INTO PFI_CHILD_D
            (INTERNAL_INVOICE_REF_NO, STOCK_REF_NO, CONTRACT_ITEM_REF_NO, QUANTITY,
             QUANTITY_UNIT, PRICE, PRICE_UNIT, AMOUNT, AMOUNT_UNIT, IS_FROM, INTERNAL_DOC_REF_NO)
   select
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
'''' as  STOCK_REF_NO,
PCI.CONTRACT_ITEM_REF_NO as CONTRACT_ITEM_REF_NO,
PFID.INVOICED_QTY as QUANTITY,
QUM.QTY_UNIT as QUANTITY_UNIT,
PFID.NEW_INVOICE_PRICE as PRICE,
PUM.PRICE_UNIT_NAME as PRICE_UNIT,
PFID.INVOICE_ITEM_AMOUNT as AMOUNT,
CM.CUR_CODE as AMOUNT_UNIT,
'''' as IS_FROM,
?
from
PFID_PROFOMA_INVOICE_DETAILS pfid,
IS_INVOICE_SUMMARY invs,
PCM_PHYSICAL_CONTRACT_MAIN pcm,
V_PCI pci,
CM_CURRENCY_MASTER cm,
PPU_PRODUCT_PRICE_UNITS ppu,
PUM_PRICE_UNIT_MASTER pum,
QUM_QUANTITY_UNIT_MASTER qum
where
INVS.INTERNAL_INVOICE_REF_NO = PFID.INTERNAL_INVOICE_REF_NO
and PFID.INTERNAL_CONTRACT_ITEM_REF_NO = PCI.INTERNAL_CONTRACT_ITEM_REF_NO
and INVS.INTERNAL_CONTRACT_REF_NO = PCM.INTERNAL_CONTRACT_REF_NO
and PFID.INVOICE_CURRENCY_ID = CM.CUR_ID
and PFID.NEW_INVOICE_PRICE_UNIT_ID = PPU.INTERNAL_PRICE_UNIT_ID
and PPU.PRICE_UNIT_ID = PUM.PRICE_UNIT_ID
and PFID.INVOICED_QTY_UNIT_ID = QUM.QTY_UNIT_ID
and INVS.INTERNAL_INVOICE_REF_NO = ?', 'N');



Insert into DM_DOCUMENT_MASTER
   (DOC_ID, DOC_NAME, DISPLAY_ORDER, VERSION, IS_ACTIVE, 
    IS_DELETED, ACTIVITY_ID)
 Values
   ('CREATE_PFI', 'Profoma Invoice', 1, NULL, 'Y', 
    'N', NULL);

Insert into ADM_ACTION_DOCUMENT_MASTER
   (ADM_ID, ACTION_ID, DOC_ID, IS_DELETED)
 Values
   ('ADM-PFI-1', 'CREATE_PFI', 'CREATE_PFI', 'N');

Insert into DKM_DOC_REF_KEY_MASTER
   (DOC_KEY_ID, DOC_KEY_DESC, VALIDATION_QUERY)
 Values
   ('PFI_KEY_1', 'Profoma Invoice', 'SELECT COUNT (*) FROM DS_DOCUMENT_SUMMARY ds WHERE DS.DOC_REF_NO = :pc_document_ref_no AND DS.CORPORATE_ID = :pc_corporate_id');

Insert into DKM_DOC_REF_KEY_MASTER
   (DOC_KEY_ID, DOC_KEY_DESC, VALIDATION_QUERY)
 Values
   ('PFI_KEY_2', 'Profoma Invoice', 'SELECT COUNT (*) FROM DS_DOCUMENT_SUMMARY ds WHERE DS.DOC_REF_NO = :pc_document_ref_no AND DS.CORPORATE_ID = :pc_corporate_id');