delete from SLS_STATIC_LIST_SETUP where VALUE_ID IN ('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec');
delete from SLV_STATIC_LIST_VALUE where VALUE_ID IN ('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec');
commit;
SET DEFINE OFF;
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Jan', 'Jan');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Feb', 'Feb');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Mar', 'Mar');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Apr', 'Apr');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('May', 'May');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Jun', 'Jun');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Jul', 'Jul');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Aug', 'Aug');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Sep', 'Sep');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Oct', 'Oct');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Nov', 'Nov');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Dec', 'Dec');
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Jan', 'N', 1);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Feb', 'N', 2);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Mar', 'N', 3);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Apr', 'N', 4);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'May', 'N', 5);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Jun', 'N', 6);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Jul', 'N', 7);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Aug', 'N', 8);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Sep', 'N', 9);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Oct', 'N', 10);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Nov', 'N', 11);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Dec', 'N', 12);
COMMIT;

