UPDATE GMC_GRID_MENU_CONFIGURATION GMC SET GMC.LINK_CALLED='function(){cloneContract();}' WHERE GMC.MENU_ID='MIN_1_5';


ALTER TABLE SAM_STOCK_ASSAY_MAPPING
 ADD (IS_LATEST_PRICING_ASSAY  CHAR(1 CHAR)         DEFAULT 'N');

ALTER TABLE SAM_STOCK_ASSAY_MAPPING
 ADD (IS_LATEST_WEIGHTED_AVG_PRICING  CHAR(1 CHAR)         DEFAULT 'N');

ALTER TABLE SAM_STOCK_ASSAY_MAPPING
 ADD (PREV_POSITION_ASSAY_ID  CHAR(15 CHAR));

ALTER TABLE SAM_STOCK_ASSAY_MAPPING
 ADD (PREV_PRICING_ASSAY_ID  CHAR(15 CHAR));

ALTER TABLE SAM_STOCK_ASSAY_MAPPING
 ADD (PREV_WEIGHTED_AVG_PRICINGASSAY  CHAR(15 CHAR));