DELETE ARFM_ACTION_REF_NO_MAPPING ARFM WHERE ARFM.ACTION_ID = 'writeOffCMAStocks';
DELETE ARF_ACTION_REF_NUMBER_FORMAT ARF WHERE ARF.ACTION_KEY_ID = 'writeOffCMARef';
DELETE AKM_ACTION_REF_KEY_MASTER AKM WHERE AKM.ACTION_KEY_ID = 'writeOffCMARef';


DELETE CAC_CORPORATE_ACTION_CONFIG CAC WHERE CAC.ACTION_ID = 'writeOffCMAStocks';
DELETE AXM_ACTION_MASTER AXM WHERE AXM.ACTION_ID = 'writeOffCMAStocks'; 


DELETE ARFM_ACTION_REF_NO_MAPPING ARFM WHERE ARFM.ACTION_ID = 'undoWrtOffCMAStocks';
DELETE ARF_ACTION_REF_NUMBER_FORMAT ARF WHERE ARF.ACTION_KEY_ID = 'unWrtOffCMARef';
DELETE AKM_ACTION_REF_KEY_MASTER AKM WHERE AKM.ACTION_KEY_ID = 'unWrtOffCMARef';


DELETE CAC_CORPORATE_ACTION_CONFIG CAC WHERE CAC.ACTION_ID = 'undoWrtOffCMAStocks';
DELETE AXM_ACTION_MASTER AXM WHERE AXM.ACTION_ID = 'undoWrtOffCMAStocks'; 

DELETE ARFM_ACTION_REF_NO_MAPPING ARFM WHERE ARFM.ACTION_ID = 'cmaReleaseOrder';
DELETE ARF_ACTION_REF_NUMBER_FORMAT ARF WHERE ARF.ACTION_KEY_ID = 'cmaRefNo';
DELETE AKM_ACTION_REF_KEY_MASTER AKM WHERE AKM.ACTION_KEY_ID = 'cmaRefNo';


DELETE CAC_CORPORATE_ACTION_CONFIG CAC WHERE CAC.ACTION_ID = 'cmaReleaseOrder';
DELETE AXM_ACTION_MASTER AXM WHERE AXM.ACTION_ID = 'cmaReleaseOrder';



DELETE ARFM_ACTION_REF_NO_MAPPING ARFM WHERE ARFM.ACTION_ID = 'CANCEL_CMA';
DELETE ARF_ACTION_REF_NUMBER_FORMAT ARF WHERE ARF.ACTION_KEY_ID = 'CancelCMANo';
DELETE AKM_ACTION_REF_KEY_MASTER AKM WHERE AKM.ACTION_KEY_ID = 'CancelCMANo';


DELETE CAC_CORPORATE_ACTION_CONFIG CAC WHERE CAC.ACTION_ID = 'CANCEL_CMA';
DELETE AXM_ACTION_MASTER AXM WHERE AXM.ACTION_ID = 'CANCEL_CMA';
