DECLARE
   fetchqry   CLOB
      := 'INSERT INTO IS_DC_CHILD_D(
INTERNAL_INVOICE_REF_NO,
DESCRIPTION,
INVOICED_WEIGHT,
NEW_INVOICED_WEIGHT,
INVOICE_PRICE,
NEW_INVOICE_PRICE,
AMOUNT,
NEW_AMOUNT,
OLD_INVOICE_AMOUNT,
NEW_INVOICE_AMOUNT,
NET_ADJUSTMENT,
OLD_PRICE_UNIT_NAME,
NEW_PRICE_UNIT_NAME,
OLD_INVOICE_CUR_UNIT,
NEW_INVOICE_CUR_UNIT,
INVOICE_CUR_UNIT,
INVOICE_QTY_UNIT_NAME,
INTERNAL_DOC_REF_NO
)
select
IID.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
GMR.GMR_REF_NO as DESCRIPTION,
IID.INVOICED_QTY as INVOICED_WEIGHT,
IID.NEW_INVOICED_QTY as NEW_INVOICED_WEIGHT,
IID.INVOICED_PRICE as INVOICE_PRICE,
IID.NEW_INVOICE_PRICE as NEW_INVOICE_PRICE,
IID.ITEM_AMOUNT as AMOUNT,
IID.INVOICE_ITEM_AMOUNT as NEW_AMOUNT,
IID.ITEM_AMOUNT as OLD_INVOICE_AMOUNT,
(IID.NEW_INVOICED_QTY * IID.NEW_INVOICE_PRICE) as NEW_INVOICE_AMOUNT,
(IID.INVOICE_ITEM_AMOUNT - IID.ITEM_AMOUNT) as NET_ADJUSTMENT,
PUM.PRICE_UNIT_NAME as OLD_PRICE_UNIT_NAME,
PUM.PRICE_UNIT_NAME as NEW_PRICE_UNIT_NAME,
CM.CUR_CODE as OLD_INVOICE_CUR_UNIT,
CM.CUR_CODE as NEW_INVOICE_CUR_UNIT,
CM.CUR_CODE as INVOICE_CUR_UNIT,
QUM.QTY_UNIT as INVOICE_QTY_UNIT_NAME,
?
from
IS_INVOICE_SUMMARY invs,
IID_INVOICABLE_ITEM_DETAILS iid,
QUM_QUANTITY_UNIT_MASTER qum,
CM_CURRENCY_MASTER cm,
PPU_PRODUCT_PRICE_UNITS ppu,
PUM_PRICE_UNIT_MASTER pum,
GMR_GOODS_MOVEMENT_RECORD gmr
where
INVS.INTERNAL_INVOICE_REF_NO = IID.INTERNAL_INVOICE_REF_NO
and IID.INVOICE_CURRENCY_ID = CM.CUR_ID
and IID.INVOICED_PRICE_UNIT_ID = PPU.INTERNAL_PRICE_UNIT_ID
and PPU.PRICE_UNIT_ID = PUM.PRICE_UNIT_ID
and IID.INVOICED_QTY_UNIT_ID = QUM.QTY_UNIT_ID
and IID.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO
and INVS.INTERNAL_INVOICE_REF_NO = ?';

BEGIN
   UPDATE dgm_document_generation_master dgm
      SET dgm.fetch_query = fetchqry
    WHERE dgm.doc_id IN ('CREATE_DC')
      AND dgm.is_concentrate = 'N'
      AND dgm.dgm_id IN ('DGM-DC-C1');
commit;
END;



DECLARE
   fetchqry   CLOB
      := 'INSERT into IOC_D (
    INTERNAL_INVOICE_REF_NO,
    OTHER_CHARGE_COST_NAME,
    CHARGE_TYPE,
    FX_RATE,
    QUANTITY,
    AMOUNT,
    INVOICE_AMOUNT,
    INVOICE_CUR_NAME,
    RATE_PRICE_UNIT_NAME,
    CHARGE_AMOUNT_RATE,
    QUANTITY_UNIT,
    AMOUNT_UNIT,
    INTERNAL_DOC_REF_NO
    )
    select 
    INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
    SCM.COST_DISPLAY_NAME as OTHER_CHARGE_COST_NAME,
    IOC.CHARGE_TYPE as CHARGE_TYPE,
    nvl(IOC.RATE_FX_RATE, IOC.FLAT_AMOUNT_FX_RATE) as FX_RATE,
    IOC.QUANTITY as QUANTITY,
    nvl(IOC.RATE_AMOUNT, IOC.FLAT_AMOUNT) as AMOUNT,
    IOC.AMOUNT_IN_INV_CUR as INVOICE_AMOUNT,
    CM.CUR_CODE as INVOICE_CUR_NAME,
    PUM.PRICE_UNIT_NAME as RATE_PRICE_UNIT_NAME,
    nvl(IOC.FLAT_AMOUNT, IOC.RATE_CHARGE) as CHARGE_AMOUNT_RATE,
    QUM.QTY_UNIT as QUANTITY_UNIT,
    CM_IOC.CUR_CODE as AMOUNT_UNIT,
    ?
    from
    IS_INVOICE_SUMMARY invs,
    IOC_INVOICE_OTHER_CHARGE ioc,
    CM_CURRENCY_MASTER cm,
    SCM_SERVICE_CHARGE_MASTER scm,
    PPU_PRODUCT_PRICE_UNITS ppu,
    PUM_PRICE_UNIT_MASTER pum,
    QUM_QUANTITY_UNIT_MASTER qum,
    CM_CURRENCY_MASTER cm_ioc
    where
    INVS.INTERNAL_INVOICE_REF_NO = IOC.INTERNAL_INVOICE_REF_NO
    and IOC.OTHER_CHARGE_COST_ID = SCM.COST_ID
    and IOC.INVOICE_CUR_ID = CM.CUR_ID
    and IOC.RATE_PRICE_UNIT = PPU.INTERNAL_PRICE_UNIT_ID(+)
    and PPU.PRICE_UNIT_ID = PUM.PRICE_UNIT_ID(+)
    and IOC.QTY_UNIT_ID = QUM.QTY_UNIT_ID(+)
    and IOC.FLAT_AMOUNT_CUR_UNIT_ID = CM_IOC.CUR_ID(+)
    and IOC.INTERNAL_INVOICE_REF_NO = ?';

BEGIN
   UPDATE dgm_document_generation_master dgm
      SET dgm.fetch_query = fetchqry
    WHERE dgm.doc_id IN ('CREATE_DC')
      AND dgm.is_concentrate = 'N'
      AND dgm.dgm_id IN ('DGM-IOC_BM');
commit;
END;