DELETE FROM ARF_ACTION_REF_NUMBER_FORMAT ARF WHERE ARF.ACTION_REF_NUMBER_FORMAT_ID IN ('ARF-DRFI-BAM','ARF-DRFI-LDE','ARF-DRFI-BLD','ARF-DRFI-BAT');

Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED, SEQ_NAME)
 Values
   ('ARF-4075', 'DFTPFIRefNo', 'BLD', 'DFT-PFI-', 1, 
    0, '-BLD', NULL, 'N', 'SEQAXM_DFTPFI_BLD');
    
Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED, SEQ_NAME)
 Values
   ('ARF-DFT-PFI-LDE', 'DFTPFIRefNo', 'LDE', 'DFT-PFI-', 1, 
    0, '-LDE', 1, 'N', 'SEQAXM_DFTPFI_LDE');
    
Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED, SEQ_NAME)
 Values
   ('ARF-4076', 'DFTPFIRefNo', 'BAM', 'DFT-PFI-', 1, 
    0, '-BAM', NULL, 'N', 'SEQAXM_DFTPFI_BAM');
    
Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED, SEQ_NAME)
 Values
   ('ARF-4077', 'DFTPFIRefNo', 'BAT', 'DFT-PFI-', 1, 
    0, '-BAT', NULL, 'N', 'SEQAXM_DFTPFI_BAT');
    
DELETE FROM ARFM_ACTION_REF_NO_MAPPING ARFM WHERE ARFM.ACTION_REF_NO_MAPPING_ID IN ('ARFM-DRFI-BAM','ARFM-DRFI-LDE','ARFM-DRFI-BLD','ARFM-DRFI-BAT');

Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-6121', 'BLD', 'CREATE_DFT_PFI', 'DFTPFIRefNo', 'N');
   
Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-DFT-PFI-LDE', 'LDE', 'CREATE_DFT_PFI', 'DFTPFIRefNo', 'N');
   
Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-6122', 'BAM', 'CREATE_DFT_PFI', 'DFTPFIRefNo', 'N');
   
Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-6123', 'BAT', 'CREATE_DFT_PFI', 'DFTPFIRefNo', 'N');
   
UPDATE ERC_EXTERNAL_REF_NO_CONFIG ERC SET ERC.SUFFIX='-BAM', ERC.SEQ_NAME='SEQERC_DFTPFI_BAM' WHERE ERC.EXTERNAL_REF_NO_KEY='CREATE_DFT_PFI' AND ERC.CORPORATE_ID='BAM';
UPDATE ERC_EXTERNAL_REF_NO_CONFIG ERC SET ERC.SUFFIX='-LDE', ERC.SEQ_NAME='SEQERC_DFTPFI_LDE' WHERE ERC.EXTERNAL_REF_NO_KEY='CREATE_DFT_PFI' AND ERC.CORPORATE_ID='LDE';
UPDATE ERC_EXTERNAL_REF_NO_CONFIG ERC SET ERC.SUFFIX='-BLD', ERC.SEQ_NAME='SEQERC_DFTPFI_BLD' WHERE ERC.EXTERNAL_REF_NO_KEY='CREATE_DFT_PFI' AND ERC.CORPORATE_ID='BLD';
UPDATE ERC_EXTERNAL_REF_NO_CONFIG ERC SET ERC.SUFFIX='-BAT', ERC.SEQ_NAME='SEQERC_DFTPFI_BAT' WHERE ERC.EXTERNAL_REF_NO_KEY='CREATE_DFT_PFI' AND ERC.CORPORATE_ID='BAT';