Insert into DGM_DOCUMENT_GENERATION_MASTER
   (DGM_ID, DOC_ID, DOC_NAME, ACTIVITY_ID, SEQUENCE_ORDER, 
    FETCH_QUERY, IS_CONCENTRATE)
 Values
   ('DGM-IEPD_BM', 'CREATE_FI', 'Final Invoice', 'CREATE_FI', 9, 
    ' INSERT INTO IEPD_D(
INTERNAL_INVOICE_REF_NO,
INVOICE_AMOUNT,
DELIVERY_ITEM_REF_NO,
INTERNAL_GMR_REF_NO,
ELEMENT_ID,
ELEMENT_NAME,
FX_RATE,
GMR_REF_NO,
INVOICE_CUR_NAME,
INVOICE_PRICE_UNIT_NAME,
ADJUSTMENT,
PRICE,
PRICE_FIXATION_DATE,
PRICE_FIXATION_REF_NO,
PRICE_IN_PAY_IN_CUR,
PRICING_CUR_NAME,
PRICING_PRICE_UNIT_NAME,
PRICING_TYPE,
PRODUCT_NAME,
QTY_PRICED,
QTY_UNIT_NAME,
QP_START_DATE,
QP_END_DATE,
QP_PERIOD_TYPE,
INTERNAL_DOC_REF_NO)
select distinct
    INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
    IEPD.AMOUNT_IN_PAY_IN_CUR AS INVOICE_AMOUNT,
    IEPD.DELIVERY_ITEM_REF_NO AS DELIVERY_ITEM_REF_NO,
    IEPD.INTERNAL_GMR_REF_NO AS INTERNAL_GMR_REF_NO,
    IEPD.ELEMENT_ID AS ELEMENT_ID,
    IEPD.ELEMENT_NAME AS ELEMENT_NAME,
    IEPD.FX_RATE AS FX_RATE,
    GMR.GMR_REF_NO AS GMR_REF_NO, 
    IEPD.PAY_IN_CUR_NAME AS INVOICE_CUR_NAME,
    IEPD.PAY_IN_PRICE_UNIT_NAME AS INVOICE_PRICE_UNIT_NAME,
    IEPD.ADJUSTMENT AS ADJUSTMENT,
    IEPD.PRICE AS PRICE,
    IEPD.PRICE_FIXATION_DATE AS PRICE_FIXATION_DATE,
    IEPD.PRICE_FIXATION_REF_NO AS PRICE_FIXATION_REF_NO,
    IEPD.PRICE_IN_PAY_IN_CUR AS PRICE_IN_PAY_IN_CUR,
    IEPD.PRICING_CUR_NAME AS PRICING_CUR_NAME,
    IEPD.PRICING_PRICE_UNIT_NAME AS PRICING_PRICE_UNIT_NAME,
    IEPD.PRICING_TYPE AS PRICING_TYPE,
    PDM.PRODUCT_DESC AS PRODUCT_NAME,
    IEPD.QTY_PRICED AS QTY_PRICED,
    IEPD.QTY_UNIT_NAME AS QTY_UNIT_NAME,
    POFH.QP_START_DATE AS QP_START_DATE,
    POFH.QP_END_DATE AS QP_END_DATE,
    PFQPP.QP_PRICING_PERIOD_TYPE AS QP_PERIOD_TYPE,
    ?
    from
    IS_INVOICE_SUMMARY invs,
    IEPD_INV_ELE_PRICING_DETAIL IEPD,
    PDM_PRODUCTMASTER PDM,
    POFH_PRICE_OPT_FIXATION_HEADER POFH,
    PCBPH_PC_BASE_PRICE_HEADER PCBPH,
    PCBPD_PC_BASE_PRICE_DETAIL PCBPD,
    PPFH_PHY_PRICE_FORMULA_HEADER PPFH,
    PFQPP_PHY_FORMULA_QP_PRICING PFQPP,
    GMR_GOODS_MOVEMENT_RECORD GMR
    where
    INVS.INTERNAL_INVOICE_REF_NO = IEPD.INTERNAL_INVOICE_REF_NO
    AND IEPD.PRODUCT_ID = PDM.PRODUCT_ID(+)
    AND IEPD.POFH_ID = POFH.POFH_ID(+)
    AND IEPD.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO(+)
    and pcbph.internal_contract_ref_no = INVS.INTERNAL_CONTRACT_REF_NO 
    and pcbph.pcbph_id = pcbpd.pcbph_id
    and pcbpd.pcbpd_id = ppfh.pcbpd_id
    and ppfh.ppfh_id = pfqpp.ppfh_id
    and IEPD.INTERNAL_INVOICE_REF_NO = ?
    ', 'N');
COMMIT;

Insert into DGM_DOCUMENT_GENERATION_MASTER
   (DGM_ID, DOC_ID, DOC_NAME, ACTIVITY_ID, SEQUENCE_ORDER, 
    FETCH_QUERY, IS_CONCENTRATE)
 Values
   ('DGM-IEFPD_BM', 'CREATE_FI', 'Final Invoice', 'CREATE_FI', 10, 
    'INSERT INTO IEFPD_D(
  INTERNAL_INVOICE_REF_NO,
  INTERNAL_GMR_REF_NO,
  GMR_REF_NO,
  ELEMENT_ID,
  ELEMENT_NAME,
  QTY_UNIT_NAME,
  TOTAL_QTY_PRICED,
  WT_AVG_FX_RATE,
  WT_AVG_PRICE_IN_PRICING_CUR,
  PRICING_CUR_NAME,
  WT_AVG_PRICE_IN_PAY_IN_CUR,
  PAY_IN_CUR_NAME,
  INTERNAL_DOC_REF_NO
  )
  select distinct
    INVS.INTERNAL_INVOICE_REF_NO AS INTERNAL_INVOICE_REF_NO,
    GMR.INTERNAL_GMR_REF_NO AS INTERNAL_GMR_REF_NO,
    GMR.GMR_REF_NO AS GMR_REF_NO,
    IEFPD.ELEMENT_ID AS ELEMENT_ID,
    IEFPD.ELEMENT_NAME AS ELEMENT_NAME,
    IEFPD.QTY_UNIT_NAME AS QTY_UNIT_NAME,
    IEFPD.TOTAL_QTY_PRICED AS TOTAL_QTY_PRICED,
    IEFPD.WT_AVG_FX_RATE AS WT_AVG_FX_RATE,
    IEFPD.WT_AVG_PRICE_IN_PRICING_CUR AS WT_AVG_PRICE_IN_PRICING_CUR,
    IEFPD.PRICING_CUR_NAME AS PRICING_CUR_NAME, 
    IEFPD.WT_AVG_PRICE_IN_PAY_IN_CUR AS WT_AVG_PRICE_IN_PAY_IN_CUR,
    IEFPD.PAY_IN_CUR_NAME AS PAY_IN_CUR_NAME,
     ?
    from
    IS_INVOICE_SUMMARY invs,
    IEFPD_IEF_PRICING_DETAIL IEFPD,
    GMR_GOODS_MOVEMENT_RECORD GMR
    where
    INVS.INTERNAL_INVOICE_REF_NO = IEFPD.INTERNAL_INVOICE_REF_NO
    AND IEFPD.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO(+)
    AND IEFPD.INTERNAL_INVOICE_REF_NO = ?', 'N');
COMMIT;

Insert into DGM_DOCUMENT_GENERATION_MASTER
   (DGM_ID, DOC_ID, DOC_NAME, ACTIVITY_ID, SEQUENCE_ORDER, 
    FETCH_QUERY, IS_CONCENTRATE)
 Values
   ('DGM-DFI-C8', 'CREATE_DFI', 'Direct Final Invoice', 'CREATE_DFI', 9, 
    ' INSERT INTO IEPD_D(
INTERNAL_INVOICE_REF_NO,
INVOICE_AMOUNT,
DELIVERY_ITEM_REF_NO,
INTERNAL_GMR_REF_NO,
ELEMENT_ID,
ELEMENT_NAME,
FX_RATE,
GMR_REF_NO,
INVOICE_CUR_NAME,
INVOICE_PRICE_UNIT_NAME,
ADJUSTMENT,
PRICE,
PRICE_FIXATION_DATE,
PRICE_FIXATION_REF_NO,
PRICE_IN_PAY_IN_CUR,
PRICING_CUR_NAME,
PRICING_PRICE_UNIT_NAME,
PRICING_TYPE,
PRODUCT_NAME,
QTY_PRICED,
QTY_UNIT_NAME,
QP_START_DATE,
QP_END_DATE,
QP_PERIOD_TYPE,
INTERNAL_DOC_REF_NO)
select distinct
    INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
    IEPD.AMOUNT_IN_PAY_IN_CUR AS INVOICE_AMOUNT,
    IEPD.DELIVERY_ITEM_REF_NO AS DELIVERY_ITEM_REF_NO,
    IEPD.INTERNAL_GMR_REF_NO AS INTERNAL_GMR_REF_NO,
    IEPD.ELEMENT_ID AS ELEMENT_ID,
    IEPD.ELEMENT_NAME AS ELEMENT_NAME,
    IEPD.FX_RATE AS FX_RATE,
    GMR.GMR_REF_NO AS GMR_REF_NO, 
    IEPD.PAY_IN_CUR_NAME AS INVOICE_CUR_NAME,
    IEPD.PAY_IN_PRICE_UNIT_NAME AS INVOICE_PRICE_UNIT_NAME,
    IEPD.ADJUSTMENT AS ADJUSTMENT,
    IEPD.PRICE AS PRICE,
    IEPD.PRICE_FIXATION_DATE AS PRICE_FIXATION_DATE,
    IEPD.PRICE_FIXATION_REF_NO AS PRICE_FIXATION_REF_NO,
    IEPD.PRICE_IN_PAY_IN_CUR AS PRICE_IN_PAY_IN_CUR,
    IEPD.PRICING_CUR_NAME AS PRICING_CUR_NAME,
    IEPD.PRICING_PRICE_UNIT_NAME AS PRICING_PRICE_UNIT_NAME,
    IEPD.PRICING_TYPE AS PRICING_TYPE,
    PDM.PRODUCT_DESC AS PRODUCT_NAME,
    IEPD.QTY_PRICED AS QTY_PRICED,
    IEPD.QTY_UNIT_NAME AS QTY_UNIT_NAME,
    POFH.QP_START_DATE AS QP_START_DATE,
    POFH.QP_END_DATE AS QP_END_DATE,
    PFQPP.QP_PRICING_PERIOD_TYPE AS QP_PERIOD_TYPE,
    ?
    from
    IS_INVOICE_SUMMARY invs,
    IEPD_INV_ELE_PRICING_DETAIL IEPD,
    PDM_PRODUCTMASTER PDM,
    POFH_PRICE_OPT_FIXATION_HEADER POFH,
    PCBPH_PC_BASE_PRICE_HEADER PCBPH,
    PCBPD_PC_BASE_PRICE_DETAIL PCBPD,
    PPFH_PHY_PRICE_FORMULA_HEADER PPFH,
    PFQPP_PHY_FORMULA_QP_PRICING PFQPP,
    GMR_GOODS_MOVEMENT_RECORD GMR
    where
    INVS.INTERNAL_INVOICE_REF_NO = IEPD.INTERNAL_INVOICE_REF_NO
    AND IEPD.PRODUCT_ID = PDM.PRODUCT_ID(+)
    AND IEPD.POFH_ID = POFH.POFH_ID(+)
    AND IEPD.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO(+)
    and pcbph.internal_contract_ref_no = INVS.INTERNAL_CONTRACT_REF_NO 
    and pcbph.pcbph_id = pcbpd.pcbph_id
    and pcbpd.pcbpd_id = ppfh.pcbpd_id
    and ppfh.ppfh_id = pfqpp.ppfh_id
    and IEPD.INTERNAL_INVOICE_REF_NO = ?
    ', 'N');
COMMIT;

Insert into DGM_DOCUMENT_GENERATION_MASTER
   (DGM_ID, DOC_ID, DOC_NAME, ACTIVITY_ID, SEQUENCE_ORDER, 
    FETCH_QUERY, IS_CONCENTRATE)
 Values
   ('DGM-DFI-C9', 'CREATE_DFI', 'Direct Final Invoice', 'CREATE_DFI', 10, 
    'INSERT INTO IEFPD_D(
  INTERNAL_INVOICE_REF_NO,
  INTERNAL_GMR_REF_NO,
  GMR_REF_NO,
  ELEMENT_ID,
  ELEMENT_NAME,
  QTY_UNIT_NAME,
  TOTAL_QTY_PRICED,
  WT_AVG_FX_RATE,
  WT_AVG_PRICE_IN_PRICING_CUR,
  PRICING_CUR_NAME,
  WT_AVG_PRICE_IN_PAY_IN_CUR,
  PAY_IN_CUR_NAME,
  INTERNAL_DOC_REF_NO
  )
  select distinct
    INVS.INTERNAL_INVOICE_REF_NO AS INTERNAL_INVOICE_REF_NO,
    GMR.INTERNAL_GMR_REF_NO AS INTERNAL_GMR_REF_NO,
    GMR.GMR_REF_NO AS GMR_REF_NO,
    IEFPD.ELEMENT_ID AS ELEMENT_ID,
    IEFPD.ELEMENT_NAME AS ELEMENT_NAME,
    IEFPD.QTY_UNIT_NAME AS QTY_UNIT_NAME,
    IEFPD.TOTAL_QTY_PRICED AS TOTAL_QTY_PRICED,
    IEFPD.WT_AVG_FX_RATE AS WT_AVG_FX_RATE,
    IEFPD.WT_AVG_PRICE_IN_PRICING_CUR AS WT_AVG_PRICE_IN_PRICING_CUR,
    IEFPD.PRICING_CUR_NAME AS PRICING_CUR_NAME, 
    IEFPD.WT_AVG_PRICE_IN_PAY_IN_CUR AS WT_AVG_PRICE_IN_PAY_IN_CUR,
    IEFPD.PAY_IN_CUR_NAME AS PAY_IN_CUR_NAME,
     ?
    from
    IS_INVOICE_SUMMARY invs,
    IEFPD_IEF_PRICING_DETAIL IEFPD,
    GMR_GOODS_MOVEMENT_RECORD GMR
    where
    INVS.INTERNAL_INVOICE_REF_NO = IEFPD.INTERNAL_INVOICE_REF_NO
    AND IEFPD.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO(+)
    AND IEFPD.INTERNAL_INVOICE_REF_NO = ?', 'N');
COMMIT;

Insert into DGM_DOCUMENT_GENERATION_MASTER
   (DGM_ID, DOC_ID, DOC_NAME, ACTIVITY_ID, SEQUENCE_ORDER, 
    FETCH_QUERY, IS_CONCENTRATE)
 Values
   ('DGM-IEPD_C', 'CREATE_DFI', 'Concentrate Direct Final Invoice', 'CREATE_DFI', 12, 
    ' INSERT INTO IEPD_D(
INTERNAL_INVOICE_REF_NO,
INVOICE_AMOUNT,
DELIVERY_ITEM_REF_NO,
INTERNAL_GMR_REF_NO,
ELEMENT_ID,
ELEMENT_NAME,
FX_RATE,
GMR_REF_NO,
INVOICE_CUR_NAME,
INVOICE_PRICE_UNIT_NAME,
ADJUSTMENT,
PRICE,
PRICE_FIXATION_DATE,
PRICE_FIXATION_REF_NO,
PRICE_IN_PAY_IN_CUR,
PRICING_CUR_NAME,
PRICING_PRICE_UNIT_NAME,
PRICING_TYPE,
PRODUCT_NAME,
QTY_PRICED,
QTY_UNIT_NAME,
QP_START_DATE,
QP_END_DATE,
QP_PERIOD_TYPE,
INTERNAL_DOC_REF_NO)
select distinct
    INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
    IEPD.AMOUNT_IN_PAY_IN_CUR AS INVOICE_AMOUNT,
    IEPD.DELIVERY_ITEM_REF_NO AS DELIVERY_ITEM_REF_NO,
    IEPD.INTERNAL_GMR_REF_NO AS INTERNAL_GMR_REF_NO,
    IEPD.ELEMENT_ID AS ELEMENT_ID,
    IEPD.ELEMENT_NAME AS ELEMENT_NAME,
    IEPD.FX_RATE AS FX_RATE,
    GMR.GMR_REF_NO AS GMR_REF_NO, 
    IEPD.PAY_IN_CUR_NAME AS INVOICE_CUR_NAME,
    IEPD.PAY_IN_PRICE_UNIT_NAME AS INVOICE_PRICE_UNIT_NAME,
    IEPD.ADJUSTMENT AS ADJUSTMENT,
    IEPD.PRICE AS PRICE,
    IEPD.PRICE_FIXATION_DATE AS PRICE_FIXATION_DATE,
    IEPD.PRICE_FIXATION_REF_NO AS PRICE_FIXATION_REF_NO,
    IEPD.PRICE_IN_PAY_IN_CUR AS PRICE_IN_PAY_IN_CUR,
    IEPD.PRICING_CUR_NAME AS PRICING_CUR_NAME,
    IEPD.PRICING_PRICE_UNIT_NAME AS PRICING_PRICE_UNIT_NAME,
    IEPD.PRICING_TYPE AS PRICING_TYPE,
    PDM.PRODUCT_DESC AS PRODUCT_NAME,
    IEPD.QTY_PRICED AS QTY_PRICED,
    IEPD.QTY_UNIT_NAME AS QTY_UNIT_NAME,
    POFH.QP_START_DATE AS QP_START_DATE,
    POFH.QP_END_DATE AS QP_END_DATE,
    PFQPP.QP_PRICING_PERIOD_TYPE AS QP_PERIOD_TYPE,
    ?
    from
    IS_INVOICE_SUMMARY invs,
    IEPD_INV_ELE_PRICING_DETAIL IEPD,
    PDM_PRODUCTMASTER PDM,
    POFH_PRICE_OPT_FIXATION_HEADER POFH,
    PCBPH_PC_BASE_PRICE_HEADER PCBPH,
    PCBPD_PC_BASE_PRICE_DETAIL PCBPD,
    PPFH_PHY_PRICE_FORMULA_HEADER PPFH,
    PFQPP_PHY_FORMULA_QP_PRICING PFQPP,
    GMR_GOODS_MOVEMENT_RECORD GMR
    where
    INVS.INTERNAL_INVOICE_REF_NO = IEPD.INTERNAL_INVOICE_REF_NO
    AND IEPD.PRODUCT_ID = PDM.PRODUCT_ID(+)
    AND IEPD.POFH_ID = POFH.POFH_ID(+)
    AND IEPD.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO(+)
    and pcbph.internal_contract_ref_no = INVS.INTERNAL_CONTRACT_REF_NO 
    and pcbph.pcbph_id = pcbpd.pcbph_id
    and pcbpd.pcbpd_id = ppfh.pcbpd_id
    and ppfh.ppfh_id = pfqpp.ppfh_id
    and IEPD.INTERNAL_INVOICE_REF_NO = ?
    ', 'Y');
COMMIT;

Insert into DGM_DOCUMENT_GENERATION_MASTER
   (DGM_ID, DOC_ID, DOC_NAME, ACTIVITY_ID, SEQUENCE_ORDER, 
    FETCH_QUERY, IS_CONCENTRATE)
 Values
   ('DGM-IEFPD_C', 'CREATE_DFI', 'Concentrate Direct Final Invoice', 'CREATE_DFI', 13, 
    'INSERT INTO IEFPD_D(
  INTERNAL_INVOICE_REF_NO,
  INTERNAL_GMR_REF_NO,
  GMR_REF_NO,
  ELEMENT_ID,
  ELEMENT_NAME,
  QTY_UNIT_NAME,
  TOTAL_QTY_PRICED,
  WT_AVG_FX_RATE,
  WT_AVG_PRICE_IN_PRICING_CUR,
  PRICING_CUR_NAME,
  WT_AVG_PRICE_IN_PAY_IN_CUR,
  PAY_IN_CUR_NAME,
  INTERNAL_DOC_REF_NO
  )
  select distinct
    INVS.INTERNAL_INVOICE_REF_NO AS INTERNAL_INVOICE_REF_NO,
    GMR.INTERNAL_GMR_REF_NO AS INTERNAL_GMR_REF_NO,
    GMR.GMR_REF_NO AS GMR_REF_NO,
    IEFPD.ELEMENT_ID AS ELEMENT_ID,
    IEFPD.ELEMENT_NAME AS ELEMENT_NAME,
    IEFPD.QTY_UNIT_NAME AS QTY_UNIT_NAME,
    IEFPD.TOTAL_QTY_PRICED AS TOTAL_QTY_PRICED,
    IEFPD.WT_AVG_FX_RATE AS WT_AVG_FX_RATE,
    IEFPD.WT_AVG_PRICE_IN_PRICING_CUR AS WT_AVG_PRICE_IN_PRICING_CUR,
    IEFPD.PRICING_CUR_NAME AS PRICING_CUR_NAME, 
    IEFPD.WT_AVG_PRICE_IN_PAY_IN_CUR AS WT_AVG_PRICE_IN_PAY_IN_CUR,
    IEFPD.PAY_IN_CUR_NAME AS PAY_IN_CUR_NAME,
     ?
    from
    IS_INVOICE_SUMMARY invs,
    IEFPD_IEF_PRICING_DETAIL IEFPD,
    GMR_GOODS_MOVEMENT_RECORD GMR
    where
    INVS.INTERNAL_INVOICE_REF_NO = IEFPD.INTERNAL_INVOICE_REF_NO
    AND IEFPD.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO(+)
    AND IEFPD.INTERNAL_INVOICE_REF_NO = ?', 'Y');
COMMIT;


Insert into DGM_DOCUMENT_GENERATION_MASTER
   (DGM_ID, DOC_ID, DOC_NAME, ACTIVITY_ID, SEQUENCE_ORDER, 
    FETCH_QUERY, IS_CONCENTRATE)
 Values
   ('DGM-IEPD_C', 'CREATE_FI', 'Concentrate Final Invoice', 'CREATE_FI', 12, 
    ' INSERT INTO IEPD_D(
INTERNAL_INVOICE_REF_NO,
INVOICE_AMOUNT,
DELIVERY_ITEM_REF_NO,
INTERNAL_GMR_REF_NO,
ELEMENT_ID,
ELEMENT_NAME,
FX_RATE,
GMR_REF_NO,
INVOICE_CUR_NAME,
INVOICE_PRICE_UNIT_NAME,
ADJUSTMENT,
PRICE,
PRICE_FIXATION_DATE,
PRICE_FIXATION_REF_NO,
PRICE_IN_PAY_IN_CUR,
PRICING_CUR_NAME,
PRICING_PRICE_UNIT_NAME,
PRICING_TYPE,
PRODUCT_NAME,
QTY_PRICED,
QTY_UNIT_NAME,
QP_START_DATE,
QP_END_DATE,
QP_PERIOD_TYPE,
INTERNAL_DOC_REF_NO)
select distinct
    INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
    IEPD.AMOUNT_IN_PAY_IN_CUR AS INVOICE_AMOUNT,
    IEPD.DELIVERY_ITEM_REF_NO AS DELIVERY_ITEM_REF_NO,
    IEPD.INTERNAL_GMR_REF_NO AS INTERNAL_GMR_REF_NO,
    IEPD.ELEMENT_ID AS ELEMENT_ID,
    IEPD.ELEMENT_NAME AS ELEMENT_NAME,
    IEPD.FX_RATE AS FX_RATE,
    GMR.GMR_REF_NO AS GMR_REF_NO, 
    IEPD.PAY_IN_CUR_NAME AS INVOICE_CUR_NAME,
    IEPD.PAY_IN_PRICE_UNIT_NAME AS INVOICE_PRICE_UNIT_NAME,
    IEPD.ADJUSTMENT AS ADJUSTMENT,
    IEPD.PRICE AS PRICE,
    IEPD.PRICE_FIXATION_DATE AS PRICE_FIXATION_DATE,
    IEPD.PRICE_FIXATION_REF_NO AS PRICE_FIXATION_REF_NO,
    IEPD.PRICE_IN_PAY_IN_CUR AS PRICE_IN_PAY_IN_CUR,
    IEPD.PRICING_CUR_NAME AS PRICING_CUR_NAME,
    IEPD.PRICING_PRICE_UNIT_NAME AS PRICING_PRICE_UNIT_NAME,
    IEPD.PRICING_TYPE AS PRICING_TYPE,
    PDM.PRODUCT_DESC AS PRODUCT_NAME,
    IEPD.QTY_PRICED AS QTY_PRICED,
    IEPD.QTY_UNIT_NAME AS QTY_UNIT_NAME,
    POFH.QP_START_DATE AS QP_START_DATE,
    POFH.QP_END_DATE AS QP_END_DATE,
    PFQPP.QP_PRICING_PERIOD_TYPE AS QP_PERIOD_TYPE,
    ?
    from
    IS_INVOICE_SUMMARY invs,
    IEPD_INV_ELE_PRICING_DETAIL IEPD,
    PDM_PRODUCTMASTER PDM,
    POFH_PRICE_OPT_FIXATION_HEADER POFH,
    PCBPH_PC_BASE_PRICE_HEADER PCBPH,
    PCBPD_PC_BASE_PRICE_DETAIL PCBPD,
    PPFH_PHY_PRICE_FORMULA_HEADER PPFH,
    PFQPP_PHY_FORMULA_QP_PRICING PFQPP,
    GMR_GOODS_MOVEMENT_RECORD GMR
    where
    INVS.INTERNAL_INVOICE_REF_NO = IEPD.INTERNAL_INVOICE_REF_NO
    AND IEPD.PRODUCT_ID = PDM.PRODUCT_ID(+)
    AND IEPD.POFH_ID = POFH.POFH_ID(+)
    AND IEPD.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO(+)
    and pcbph.internal_contract_ref_no = INVS.INTERNAL_CONTRACT_REF_NO 
    and pcbph.pcbph_id = pcbpd.pcbph_id
    and pcbpd.pcbpd_id = ppfh.pcbpd_id
    and ppfh.ppfh_id = pfqpp.ppfh_id
    and IEPD.INTERNAL_INVOICE_REF_NO = ?
    ', 'Y');
COMMIT;

Insert into DGM_DOCUMENT_GENERATION_MASTER
   (DGM_ID, DOC_ID, DOC_NAME, ACTIVITY_ID, SEQUENCE_ORDER, 
    FETCH_QUERY, IS_CONCENTRATE)
 Values
   ('DGM-IEFPD_C', 'CREATE_FI', 'Concentrate Final Invoice', 'CREATE_FI', 13, 
    'INSERT INTO IEFPD_D(
  INTERNAL_INVOICE_REF_NO,
  INTERNAL_GMR_REF_NO,
  GMR_REF_NO,
  ELEMENT_ID,
  ELEMENT_NAME,
  QTY_UNIT_NAME,
  TOTAL_QTY_PRICED,
  WT_AVG_FX_RATE,
  WT_AVG_PRICE_IN_PRICING_CUR,
  PRICING_CUR_NAME,
  WT_AVG_PRICE_IN_PAY_IN_CUR,
  PAY_IN_CUR_NAME,
  INTERNAL_DOC_REF_NO
  )
  select distinct
    INVS.INTERNAL_INVOICE_REF_NO AS INTERNAL_INVOICE_REF_NO,
    GMR.INTERNAL_GMR_REF_NO AS INTERNAL_GMR_REF_NO,
    GMR.GMR_REF_NO AS GMR_REF_NO,
    IEFPD.ELEMENT_ID AS ELEMENT_ID,
    IEFPD.ELEMENT_NAME AS ELEMENT_NAME,
    IEFPD.QTY_UNIT_NAME AS QTY_UNIT_NAME,
    IEFPD.TOTAL_QTY_PRICED AS TOTAL_QTY_PRICED,
    IEFPD.WT_AVG_FX_RATE AS WT_AVG_FX_RATE,
    IEFPD.WT_AVG_PRICE_IN_PRICING_CUR AS WT_AVG_PRICE_IN_PRICING_CUR,
    IEFPD.PRICING_CUR_NAME AS PRICING_CUR_NAME, 
    IEFPD.WT_AVG_PRICE_IN_PAY_IN_CUR AS WT_AVG_PRICE_IN_PAY_IN_CUR,
    IEFPD.PAY_IN_CUR_NAME AS PAY_IN_CUR_NAME,
     ?
    from
    IS_INVOICE_SUMMARY invs,
    IEFPD_IEF_PRICING_DETAIL IEFPD,
    GMR_GOODS_MOVEMENT_RECORD GMR
    where
    INVS.INTERNAL_INVOICE_REF_NO = IEFPD.INTERNAL_INVOICE_REF_NO
    AND IEFPD.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO(+)
    AND IEFPD.INTERNAL_INVOICE_REF_NO = ?', 'Y');
COMMIT;
