SET DEFINE OFF;
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1950', '04', 'Apr', 'Quarter 2 1950', '1950');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1950', '07', 'Jul', 'Quarter 3 1950', '1950');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1950', '11', 'Nov', 'Quarter 4 1950', '1950');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1951', '02', 'Feb', 'Quarter 1 1951', '1951');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1951', '09', 'Sep', 'Quarter 3 1951', '1951');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1952', '11', 'Nov', 'Quarter 4 1952', '1952');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1953', '11', 'Nov', 'Quarter 4 1953', '1953');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1953', '12', 'Dec', 'Quarter 4 1953', '1953');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1954', '03', 'Mar', 'Quarter 1 1954', '1954');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1954', '05', 'May', 'Quarter 2 1954', '1954');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1954', '06', 'Jun', 'Quarter 2 1954', '1954');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1955', '08', 'Aug', 'Quarter 3 1955', '1955');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1955', '12', 'Dec', 'Quarter 4 1955', '1955');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1956', '06', 'Jun', 'Quarter 2 1956', '1956');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1957', '03', 'Mar', 'Quarter 1 1957', '1957');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1957', '05', 'May', 'Quarter 2 1957', '1957');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1958', '02', 'Feb', 'Quarter 1 1958', '1958');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1958', '03', 'Mar', 'Quarter 1 1958', '1958');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1959', '09', 'Sep', 'Quarter 3 1959', '1959');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1960', '04', 'Apr', 'Quarter 2 1960', '1960');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1961', '01', 'Jan', 'Quarter 1 1961', '1961');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1961', '12', 'Dec', 'Quarter 4 1961', '1961');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1962', '01', 'Jan', 'Quarter 1 1962', '1962');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1962', '02', 'Feb', 'Quarter 1 1962', '1962');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1963', '02', 'Feb', 'Quarter 1 1963', '1963');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1964', '11', 'Nov', 'Quarter 4 1964', '1964');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1966', '03', 'Mar', 'Quarter 1 1966', '1966');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1966', '10', 'Oct', 'Quarter 4 1966', '1966');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1967', '05', 'May', 'Quarter 2 1967', '1967');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1967', '06', 'Jun', 'Quarter 2 1967', '1967');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1968', '06', 'Jun', 'Quarter 2 1968', '1968');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1969', '03', 'Mar', 'Quarter 1 1969', '1969');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1969', '05', 'May', 'Quarter 2 1969', '1969');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1969', '10', 'Oct', 'Quarter 4 1969', '1969');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1970', '11', 'Nov', 'Quarter 4 1970', '1970');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1971', '11', 'Nov', 'Quarter 4 1971', '1971');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1972', '06', 'Jun', 'Quarter 2 1972', '1972');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1972', '07', 'Jul', 'Quarter 3 1972', '1972');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1973', '09', 'Sep', 'Quarter 3 1973', '1973');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1974', '07', 'Jul', 'Quarter 3 1974', '1974');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1974', '11', 'Nov', 'Quarter 4 1974', '1974');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1974', '12', 'Dec', 'Quarter 4 1974', '1974');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1975', '05', 'May', 'Quarter 2 1975', '1975');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1977', '02', 'Feb', 'Quarter 1 1977', '1977');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1979', '02', 'Feb', 'Quarter 1 1979', '1979');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1979', '05', 'May', 'Quarter 2 1979', '1979');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1982', '04', 'Apr', 'Quarter 2 1982', '1982');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1982', '08', 'Aug', 'Quarter 3 1982', '1982');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1983', '05', 'May', 'Quarter 2 1983', '1983');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1983', '11', 'Nov', 'Quarter 4 1983', '1983');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1985', '01', 'Jan', 'Quarter 1 1985', '1985');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1985', '11', 'Nov', 'Quarter 4 1985', '1985');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1985', '12', 'Dec', 'Quarter 4 1985', '1985');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1986', '01', 'Jan', 'Quarter 1 1986', '1986');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1986', '06', 'Jun', 'Quarter 2 1986', '1986');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1987', '01', 'Jan', 'Quarter 1 1987', '1987');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1988', '04', 'Apr', 'Quarter 2 1988', '1988');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1988', '08', 'Aug', 'Quarter 3 1988', '1988');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1989', '10', 'Oct', 'Quarter 4 1989', '1989');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1990', '02', 'Feb', 'Quarter 1 1990', '1990');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1990', '12', 'Dec', 'Quarter 4 1990', '1990');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1991', '07', 'Jul', 'Quarter 3 1991', '1991');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1991', '08', 'Aug', 'Quarter 3 1991', '1991');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1993', '05', 'May', 'Quarter 2 1993', '1993');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1993', '09', 'Sep', 'Quarter 3 1993', '1993');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1994', '04', 'Apr', 'Quarter 2 1994', '1994');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1995', '02', 'Feb', 'Quarter 1 1995', '1995');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1995', '08', 'Aug', 'Quarter 3 1995', '1995');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1996', '04', 'Apr', 'Quarter 2 1996', '1996');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1996', '08', 'Aug', 'Quarter 3 1996', '1996');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1996', '11', 'Nov', 'Quarter 4 1996', '1996');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1997', '03', 'Mar', 'Quarter 1 1997', '1997');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1997', '09', 'Sep', 'Quarter 3 1997', '1997');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1998', '03', 'Mar', 'Quarter 1 1998', '1998');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2000', '03', 'Mar', 'Quarter 1 2000', '2000');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2001', '01', 'Jan', 'Quarter 1 2001', '2001');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2001', '07', 'Jul', 'Quarter 3 2001', '2001');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2001', '10', 'Oct', 'Quarter 4 2001', '2001');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2001', '11', 'Nov', 'Quarter 4 2001', '2001');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2002', '03', 'Mar', 'Quarter 1 2002', '2002');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2003', '04', 'Apr', 'Quarter 2 2003', '2003');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2003', '08', 'Aug', 'Quarter 3 2003', '2003');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2003', '10', 'Oct', 'Quarter 4 2003', '2003');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2003', '12', 'Dec', 'Quarter 4 2003', '2003');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2004', '01', 'Jan', 'Quarter 1 2004', '2004');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2004', '03', 'Mar', 'Quarter 1 2004', '2004');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2004', '05', 'May', 'Quarter 2 2004', '2004');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2004', '09', 'Sep', 'Quarter 3 2004', '2004');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2005', '01', 'Jan', 'Quarter 1 2005', '2005');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2007', '03', 'Mar', 'Quarter 1 2007', '2007');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2007', '07', 'Jul', 'Quarter 3 2007', '2007');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2008', '04', 'Apr', 'Quarter 2 2008', '2008');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2008', '05', 'May', 'Quarter 2 2008', '2008');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2009', '04', 'Apr', 'Quarter 2 2009', '2009');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2009', '07', 'Jul', 'Quarter 3 2009', '2009');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2011', '02', 'Feb', 'Quarter 1 2011', '2011');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2012', '07', 'Jul', 'Quarter 3 2012', '2012');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2013', '03', 'Mar', 'Quarter 1 2013', '2013');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2013', '08', 'Aug', 'Quarter 3 2013', '2013');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2013', '09', 'Sep', 'Quarter 3 2013', '2013');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2013', '10', 'Oct', 'Quarter 4 2013', '2013');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2015', '03', 'Mar', 'Quarter 1 2015', '2015');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2015', '09', 'Sep', 'Quarter 3 2015', '2015');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2016', '07', 'Jul', 'Quarter 3 2016', '2016');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2016', '10', 'Oct', 'Quarter 4 2016', '2016');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2018', '02', 'Feb', 'Quarter 1 2018', '2018');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2018', '07', 'Jul', 'Quarter 3 2018', '2018');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2018', '08', 'Aug', 'Quarter 3 2018', '2018');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2019', '02', 'Feb', 'Quarter 1 2019', '2019');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2019', '07', 'Jul', 'Quarter 3 2019', '2019');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2020', '11', 'Nov', 'Quarter 4 2020', '2020');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1951', '06', 'Jun', 'Quarter 2 1951', '1951');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1951', '12', 'Dec', 'Quarter 4 1951', '1951');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1952', '06', 'Jun', 'Quarter 2 1952', '1952');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1952', '12', 'Dec', 'Quarter 4 1952', '1952');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1953', '02', 'Feb', 'Quarter 1 1953', '1953');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1953', '07', 'Jul', 'Quarter 3 1953', '1953');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1953', '09', 'Sep', 'Quarter 3 1953', '1953');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1954', '01', 'Jan', 'Quarter 1 1954', '1954');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1954', '02', 'Feb', 'Quarter 1 1954', '1954');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1954', '10', 'Oct', 'Quarter 4 1954', '1954');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1955', '03', 'Mar', 'Quarter 1 1955', '1955');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1956', '08', 'Aug', 'Quarter 3 1956', '1956');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1957', '07', 'Jul', 'Quarter 3 1957', '1957');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1957', '08', 'Aug', 'Quarter 3 1957', '1957');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1958', '09', 'Sep', 'Quarter 3 1958', '1958');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1958', '10', 'Oct', 'Quarter 4 1958', '1958');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1959', '11', 'Nov', 'Quarter 4 1959', '1959');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1960', '05', 'May', 'Quarter 2 1960', '1960');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1960', '11', 'Nov', 'Quarter 4 1960', '1960');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1960', '12', 'Dec', 'Quarter 4 1960', '1960');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1961', '02', 'Feb', 'Quarter 1 1961', '1961');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1962', '06', 'Jun', 'Quarter 2 1962', '1962');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1963', '07', 'Jul', 'Quarter 3 1963', '1963');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1963', '11', 'Nov', 'Quarter 4 1963', '1963');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1965', '07', 'Jul', 'Quarter 3 1965', '1965');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1965', '12', 'Dec', 'Quarter 4 1965', '1965');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1966', '04', 'Apr', 'Quarter 2 1966', '1966');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1966', '12', 'Dec', 'Quarter 4 1966', '1966');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1967', '04', 'Apr', 'Quarter 2 1967', '1967');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1969', '02', 'Feb', 'Quarter 1 1969', '1969');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1969', '04', 'Apr', 'Quarter 2 1969', '1969');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1969', '07', 'Jul', 'Quarter 3 1969', '1969');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1969', '08', 'Aug', 'Quarter 3 1969', '1969');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1969', '09', 'Sep', 'Quarter 3 1969', '1969');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1969', '12', 'Dec', 'Quarter 4 1969', '1969');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1970', '04', 'Apr', 'Quarter 2 1970', '1970');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1970', '12', 'Dec', 'Quarter 4 1970', '1970');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1972', '05', 'May', 'Quarter 2 1972', '1972');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1973', '01', 'Jan', 'Quarter 1 1973', '1973');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1973', '10', 'Oct', 'Quarter 4 1973', '1973');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1974', '02', 'Feb', 'Quarter 1 1974', '1974');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1974', '05', 'May', 'Quarter 2 1974', '1974');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1974', '08', 'Aug', 'Quarter 3 1974', '1974');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1975', '01', 'Jan', 'Quarter 1 1975', '1975');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1975', '03', 'Mar', 'Quarter 1 1975', '1975');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1975', '06', 'Jun', 'Quarter 2 1975', '1975');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1975', '08', 'Aug', 'Quarter 3 1975', '1975');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1976', '07', 'Jul', 'Quarter 3 1976', '1976');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1977', '11', 'Nov', 'Quarter 4 1977', '1977');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1977', '12', 'Dec', 'Quarter 4 1977', '1977');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1978', '03', 'Mar', 'Quarter 1 1978', '1978');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1978', '04', 'Apr', 'Quarter 2 1978', '1978');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1978', '05', 'May', 'Quarter 2 1978', '1978');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1979', '06', 'Jun', 'Quarter 2 1979', '1979');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1979', '07', 'Jul', 'Quarter 3 1979', '1979');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1979', '11', 'Nov', 'Quarter 4 1979', '1979');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1980', '03', 'Mar', 'Quarter 1 1980', '1980');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1980', '09', 'Sep', 'Quarter 3 1980', '1980');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1981', '06', 'Jun', 'Quarter 2 1981', '1981');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1981', '12', 'Dec', 'Quarter 4 1981', '1981');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1982', '10', 'Oct', 'Quarter 4 1982', '1982');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1984', '04', 'Apr', 'Quarter 2 1984', '1984');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1986', '02', 'Feb', 'Quarter 1 1986', '1986');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1986', '10', 'Oct', 'Quarter 4 1986', '1986');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1987', '03', 'Mar', 'Quarter 1 1987', '1987');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1987', '06', 'Jun', 'Quarter 2 1987', '1987');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1987', '07', 'Jul', 'Quarter 3 1987', '1987');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1988', '07', 'Jul', 'Quarter 3 1988', '1988');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1989', '02', 'Feb', 'Quarter 1 1989', '1989');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1989', '06', 'Jun', 'Quarter 2 1989', '1989');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1989', '11', 'Nov', 'Quarter 4 1989', '1989');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1991', '05', 'May', 'Quarter 2 1991', '1991');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1991', '10', 'Oct', 'Quarter 4 1991', '1991');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1991', '12', 'Dec', 'Quarter 4 1991', '1991');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1992', '02', 'Feb', 'Quarter 1 1992', '1992');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1992', '04', 'Apr', 'Quarter 2 1992', '1992');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1992', '07', 'Jul', 'Quarter 3 1992', '1992');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1992', '11', 'Nov', 'Quarter 4 1992', '1992');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1993', '04', 'Apr', 'Quarter 2 1993', '1993');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1993', '06', 'Jun', 'Quarter 2 1993', '1993');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1993', '10', 'Oct', 'Quarter 4 1993', '1993');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1997', '02', 'Feb', 'Quarter 1 1997', '1997');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1997', '10', 'Oct', 'Quarter 4 1997', '1997');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1997', '11', 'Nov', 'Quarter 4 1997', '1997');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1998', '11', 'Nov', 'Quarter 4 1998', '1998');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1999', '07', 'Jul', 'Quarter 3 1999', '1999');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2001', '04', 'Apr', 'Quarter 2 2001', '2001');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2002', '05', 'May', 'Quarter 2 2002', '2002');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2002', '07', 'Jul', 'Quarter 3 2002', '2002');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2003', '07', 'Jul', 'Quarter 3 2003', '2003');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2004', '04', 'Apr', 'Quarter 2 2004', '2004');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2004', '08', 'Aug', 'Quarter 3 2004', '2004');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2005', '04', 'Apr', 'Quarter 2 2005', '2005');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2005', '05', 'May', 'Quarter 2 2005', '2005');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2005', '11', 'Nov', 'Quarter 4 2005', '2005');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2006', '06', 'Jun', 'Quarter 2 2006', '2006');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2007', '10', 'Oct', 'Quarter 4 2007', '2007');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2009', '01', 'Jan', 'Quarter 1 2009', '2009');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2009', '03', 'Mar', 'Quarter 1 2009', '2009');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2009', '09', 'Sep', 'Quarter 3 2009', '2009');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2009', '12', 'Dec', 'Quarter 4 2009', '2009');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2010', '06', 'Jun', 'Quarter 2 2010', '2010');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2010', '08', 'Aug', 'Quarter 3 2010', '2010');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2011', '08', 'Aug', 'Quarter 3 2011', '2011');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2011', '12', 'Dec', 'Quarter 4 2011', '2011');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2012', '03', 'Mar', 'Quarter 1 2012', '2012');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2012', '05', 'May', 'Quarter 2 2012', '2012');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2012', '09', 'Sep', 'Quarter 3 2012', '2012');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2012', '10', 'Oct', 'Quarter 4 2012', '2012');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2012', '11', 'Nov', 'Quarter 4 2012', '2012');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2012', '12', 'Dec', 'Quarter 4 2012', '2012');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2013', '12', 'Dec', 'Quarter 4 2013', '2013');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2014', '01', 'Jan', 'Quarter 1 2014', '2014');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2014', '04', 'Apr', 'Quarter 2 2014', '2014');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2014', '08', 'Aug', 'Quarter 3 2014', '2014');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2014', '12', 'Dec', 'Quarter 4 2014', '2014');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2016', '04', 'Apr', 'Quarter 2 2016', '2016');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2017', '11', 'Nov', 'Quarter 4 2017', '2017');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2018', '04', 'Apr', 'Quarter 2 2018', '2018');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2018', '10', 'Oct', 'Quarter 4 2018', '2018');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2018', '11', 'Nov', 'Quarter 4 2018', '2018');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2019', '06', 'Jun', 'Quarter 2 2019', '2019');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2019', '09', 'Sep', 'Quarter 3 2019', '2019');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2019', '11', 'Nov', 'Quarter 4 2019', '2019');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2019', '12', 'Dec', 'Quarter 4 2019', '2019');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2020', '01', 'Jan', 'Quarter 1 2020', '2020');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2020', '03', 'Mar', 'Quarter 1 2020', '2020');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2020', '10', 'Oct', 'Quarter 4 2020', '2020');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1950', '08', 'Aug', 'Quarter 3 1950', '1950');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1952', '01', 'Jan', 'Quarter 1 1952', '1952');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1952', '10', 'Oct', 'Quarter 4 1952', '1952');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1953', '08', 'Aug', 'Quarter 3 1953', '1953');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1954', '07', 'Jul', 'Quarter 3 1954', '1954');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1954', '08', 'Aug', 'Quarter 3 1954', '1954');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1954', '12', 'Dec', 'Quarter 4 1954', '1954');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1955', '04', 'Apr', 'Quarter 2 1955', '1955');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1955', '06', 'Jun', 'Quarter 2 1955', '1955');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1955', '07', 'Jul', 'Quarter 3 1955', '1955');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1956', '03', 'Mar', 'Quarter 1 1956', '1956');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1956', '05', 'May', 'Quarter 2 1956', '1956');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1956', '12', 'Dec', 'Quarter 4 1956', '1956');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1958', '01', 'Jan', 'Quarter 1 1958', '1958');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1958', '04', 'Apr', 'Quarter 2 1958', '1958');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1958', '11', 'Nov', 'Quarter 4 1958', '1958');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1959', '06', 'Jun', 'Quarter 2 1959', '1959');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1960', '07', 'Jul', 'Quarter 3 1960', '1960');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1963', '09', 'Sep', 'Quarter 3 1963', '1963');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1965', '06', 'Jun', 'Quarter 2 1965', '1965');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1965', '09', 'Sep', 'Quarter 3 1965', '1965');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1965', '10', 'Oct', 'Quarter 4 1965', '1965');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1966', '06', 'Jun', 'Quarter 2 1966', '1966');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1966', '11', 'Nov', 'Quarter 4 1966', '1966');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1967', '09', 'Sep', 'Quarter 3 1967', '1967');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1967', '11', 'Nov', 'Quarter 4 1967', '1967');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1967', '12', 'Dec', 'Quarter 4 1967', '1967');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1968', '12', 'Dec', 'Quarter 4 1968', '1968');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1969', '06', 'Jun', 'Quarter 2 1969', '1969');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1970', '07', 'Jul', 'Quarter 3 1970', '1970');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1971', '04', 'Apr', 'Quarter 2 1971', '1971');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1971', '05', 'May', 'Quarter 2 1971', '1971');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1971', '06', 'Jun', 'Quarter 2 1971', '1971');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1971', '09', 'Sep', 'Quarter 3 1971', '1971');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1972', '08', 'Aug', 'Quarter 3 1972', '1972');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1973', '11', 'Nov', 'Quarter 4 1973', '1973');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1974', '04', 'Apr', 'Quarter 2 1974', '1974');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1975', '10', 'Oct', 'Quarter 4 1975', '1975');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1976', '02', 'Feb', 'Quarter 1 1976', '1976');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1976', '05', 'May', 'Quarter 2 1976', '1976');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1976', '06', 'Jun', 'Quarter 2 1976', '1976');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1976', '10', 'Oct', 'Quarter 4 1976', '1976');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1978', '02', 'Feb', 'Quarter 1 1978', '1978');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1978', '07', 'Jul', 'Quarter 3 1978', '1978');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1979', '12', 'Dec', 'Quarter 4 1979', '1979');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1980', '05', 'May', 'Quarter 2 1980', '1980');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1981', '08', 'Aug', 'Quarter 3 1981', '1981');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1981', '09', 'Sep', 'Quarter 3 1981', '1981');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1982', '01', 'Jan', 'Quarter 1 1982', '1982');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1982', '06', 'Jun', 'Quarter 2 1982', '1982');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1982', '07', 'Jul', 'Quarter 3 1982', '1982');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1983', '03', 'Mar', 'Quarter 1 1983', '1983');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1983', '09', 'Sep', 'Quarter 3 1983', '1983');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1984', '02', 'Feb', 'Quarter 1 1984', '1984');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1984', '10', 'Oct', 'Quarter 4 1984', '1984');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1984', '12', 'Dec', 'Quarter 4 1984', '1984');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1985', '02', 'Feb', 'Quarter 1 1985', '1985');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1985', '03', 'Mar', 'Quarter 1 1985', '1985');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1986', '04', 'Apr', 'Quarter 2 1986', '1986');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1986', '05', 'May', 'Quarter 2 1986', '1986');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1986', '07', 'Jul', 'Quarter 3 1986', '1986');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1987', '04', 'Apr', 'Quarter 2 1987', '1987');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1987', '12', 'Dec', 'Quarter 4 1987', '1987');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1988', '11', 'Nov', 'Quarter 4 1988', '1988');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1989', '03', 'Mar', 'Quarter 1 1989', '1989');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1989', '07', 'Jul', 'Quarter 3 1989', '1989');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1989', '12', 'Dec', 'Quarter 4 1989', '1989');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1992', '05', 'May', 'Quarter 2 1992', '1992');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1993', '07', 'Jul', 'Quarter 3 1993', '1993');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1994', '09', 'Sep', 'Quarter 3 1994', '1994');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1994', '10', 'Oct', 'Quarter 4 1994', '1994');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1995', '12', 'Dec', 'Quarter 4 1995', '1995');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1996', '02', 'Feb', 'Quarter 1 1996', '1996');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1997', '08', 'Aug', 'Quarter 3 1997', '1997');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1998', '05', 'May', 'Quarter 2 1998', '1998');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1998', '08', 'Aug', 'Quarter 3 1998', '1998');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1999', '01', 'Jan', 'Quarter 1 1999', '1999');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1999', '04', 'Apr', 'Quarter 2 1999', '1999');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1999', '05', 'May', 'Quarter 2 1999', '1999');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1999', '08', 'Aug', 'Quarter 3 1999', '1999');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1999', '10', 'Oct', 'Quarter 4 1999', '1999');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2000', '07', 'Jul', 'Quarter 3 2000', '2000');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2000', '09', 'Sep', 'Quarter 3 2000', '2000');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2001', '05', 'May', 'Quarter 2 2001', '2001');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2001', '06', 'Jun', 'Quarter 2 2001', '2001');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2002', '02', 'Feb', 'Quarter 1 2002', '2002');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2002', '06', 'Jun', 'Quarter 2 2002', '2002');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2002', '10', 'Oct', 'Quarter 4 2002', '2002');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2003', '03', 'Mar', 'Quarter 1 2003', '2003');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2004', '11', 'Nov', 'Quarter 4 2004', '2004');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2005', '08', 'Aug', 'Quarter 3 2005', '2005');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2007', '08', 'Aug', 'Quarter 3 2007', '2007');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2009', '11', 'Nov', 'Quarter 4 2009', '2009');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2010', '07', 'Jul', 'Quarter 3 2010', '2010');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2011', '10', 'Oct', 'Quarter 4 2011', '2011');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2013', '04', 'Apr', 'Quarter 2 2013', '2013');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2015', '01', 'Jan', 'Quarter 1 2015', '2015');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2015', '07', 'Jul', 'Quarter 3 2015', '2015');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2015', '10', 'Oct', 'Quarter 4 2015', '2015');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2017', '03', 'Mar', 'Quarter 1 2017', '2017');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2017', '07', 'Jul', 'Quarter 3 2017', '2017');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2017', '09', 'Sep', 'Quarter 3 2017', '2017');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2017', '10', 'Oct', 'Quarter 4 2017', '2017');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2020', '04', 'Apr', 'Quarter 2 2020', '2020');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2020', '12', 'Dec', 'Quarter 4 2020', '2020');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1950', '12', 'Dec', 'Quarter 4 1950', '1950');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1951', '07', 'Jul', 'Quarter 3 1951', '1951');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1952', '09', 'Sep', 'Quarter 3 1952', '1952');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1953', '03', 'Mar', 'Quarter 1 1953', '1953');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1956', '07', 'Jul', 'Quarter 3 1956', '1956');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1956', '09', 'Sep', 'Quarter 3 1956', '1956');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1958', '05', 'May', 'Quarter 2 1958', '1958');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1959', '01', 'Jan', 'Quarter 1 1959', '1959');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1959', '07', 'Jul', 'Quarter 3 1959', '1959');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1961', '04', 'Apr', 'Quarter 2 1961', '1961');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1961', '10', 'Oct', 'Quarter 4 1961', '1961');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1962', '05', 'May', 'Quarter 2 1962', '1962');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1964', '10', 'Oct', 'Quarter 4 1964', '1964');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1964', '12', 'Dec', 'Quarter 4 1964', '1964');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1965', '01', 'Jan', 'Quarter 1 1965', '1965');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1965', '04', 'Apr', 'Quarter 2 1965', '1965');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1965', '08', 'Aug', 'Quarter 3 1965', '1965');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1966', '01', 'Jan', 'Quarter 1 1966', '1966');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1966', '02', 'Feb', 'Quarter 1 1966', '1966');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1967', '01', 'Jan', 'Quarter 1 1967', '1967');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1967', '02', 'Feb', 'Quarter 1 1967', '1967');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1967', '03', 'Mar', 'Quarter 1 1967', '1967');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1968', '01', 'Jan', 'Quarter 1 1968', '1968');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1968', '04', 'Apr', 'Quarter 2 1968', '1968');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1969', '01', 'Jan', 'Quarter 1 1969', '1969');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1970', '01', 'Jan', 'Quarter 1 1970', '1970');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1970', '10', 'Oct', 'Quarter 4 1970', '1970');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1971', '08', 'Aug', 'Quarter 3 1971', '1971');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1972', '03', 'Mar', 'Quarter 1 1972', '1972');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1972', '09', 'Sep', 'Quarter 3 1972', '1972');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1972', '11', 'Nov', 'Quarter 4 1972', '1972');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1973', '02', 'Feb', 'Quarter 1 1973', '1973');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1973', '08', 'Aug', 'Quarter 3 1973', '1973');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1974', '10', 'Oct', 'Quarter 4 1974', '1974');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1977', '07', 'Jul', 'Quarter 3 1977', '1977');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1977', '08', 'Aug', 'Quarter 3 1977', '1977');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1979', '09', 'Sep', 'Quarter 3 1979', '1979');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1980', '10', 'Oct', 'Quarter 4 1980', '1980');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1981', '07', 'Jul', 'Quarter 3 1981', '1981');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1981', '10', 'Oct', 'Quarter 4 1981', '1981');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1983', '06', 'Jun', 'Quarter 2 1983', '1983');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1983', '08', 'Aug', 'Quarter 3 1983', '1983');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1984', '06', 'Jun', 'Quarter 2 1984', '1984');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1984', '09', 'Sep', 'Quarter 3 1984', '1984');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1984', '11', 'Nov', 'Quarter 4 1984', '1984');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1985', '10', 'Oct', 'Quarter 4 1985', '1985');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1986', '09', 'Sep', 'Quarter 3 1986', '1986');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1987', '11', 'Nov', 'Quarter 4 1987', '1987');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1989', '04', 'Apr', 'Quarter 2 1989', '1989');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1990', '05', 'May', 'Quarter 2 1990', '1990');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1990', '06', 'Jun', 'Quarter 2 1990', '1990');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1992', '12', 'Dec', 'Quarter 4 1992', '1992');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1993', '03', 'Mar', 'Quarter 1 1993', '1993');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1994', '01', 'Jan', 'Quarter 1 1994', '1994');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1994', '03', 'Mar', 'Quarter 1 1994', '1994');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1994', '12', 'Dec', 'Quarter 4 1994', '1994');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1996', '07', 'Jul', 'Quarter 3 1996', '1996');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1998', '12', 'Dec', 'Quarter 4 1998', '1998');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2000', '02', 'Feb', 'Quarter 1 2000', '2000');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2001', '02', 'Feb', 'Quarter 1 2001', '2001');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2002', '12', 'Dec', 'Quarter 4 2002', '2002');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2003', '02', 'Feb', 'Quarter 1 2003', '2003');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2003', '05', 'May', 'Quarter 2 2003', '2003');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2004', '10', 'Oct', 'Quarter 4 2004', '2004');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2005', '06', 'Jun', 'Quarter 2 2005', '2005');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2005', '10', 'Oct', 'Quarter 4 2005', '2005');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2005', '12', 'Dec', 'Quarter 4 2005', '2005');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2006', '01', 'Jan', 'Quarter 1 2006', '2006');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2006', '08', 'Aug', 'Quarter 3 2006', '2006');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2006', '09', 'Sep', 'Quarter 3 2006', '2006');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2007', '01', 'Jan', 'Quarter 1 2007', '2007');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2007', '04', 'Apr', 'Quarter 2 2007', '2007');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2007', '05', 'May', 'Quarter 2 2007', '2007');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2007', '06', 'Jun', 'Quarter 2 2007', '2007');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2007', '09', 'Sep', 'Quarter 3 2007', '2007');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2007', '11', 'Nov', 'Quarter 4 2007', '2007');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2008', '03', 'Mar', 'Quarter 1 2008', '2008');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2008', '11', 'Nov', 'Quarter 4 2008', '2008');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2009', '08', 'Aug', 'Quarter 3 2009', '2009');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2009', '10', 'Oct', 'Quarter 4 2009', '2009');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2010', '03', 'Mar', 'Quarter 1 2010', '2010');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2011', '05', 'May', 'Quarter 2 2011', '2011');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2011', '07', 'Jul', 'Quarter 3 2011', '2011');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2011', '09', 'Sep', 'Quarter 3 2011', '2011');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2011', '11', 'Nov', 'Quarter 4 2011', '2011');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2012', '02', 'Feb', 'Quarter 1 2012', '2012');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2012', '04', 'Apr', 'Quarter 2 2012', '2012');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2012', '08', 'Aug', 'Quarter 3 2012', '2012');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2014', '07', 'Jul', 'Quarter 3 2014', '2014');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2016', '05', 'May', 'Quarter 2 2016', '2016');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2016', '06', 'Jun', 'Quarter 2 2016', '2016');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2017', '05', 'May', 'Quarter 2 2017', '2017');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2017', '06', 'Jun', 'Quarter 2 2017', '2017');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2019', '01', 'Jan', 'Quarter 1 2019', '2019');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2020', '08', 'Aug', 'Quarter 3 2020', '2020');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2020', '09', 'Sep', 'Quarter 3 2020', '2020');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1900', '01', 'Jan', 'Quarter 1 1900', '1900');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1950', '05', 'May', 'Quarter 2 1950', '1950');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1950', '10', 'Oct', 'Quarter 4 1950', '1950');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1951', '01', 'Jan', 'Quarter 1 1951', '1951');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1951', '10', 'Oct', 'Quarter 4 1951', '1951');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1952', '08', 'Aug', 'Quarter 3 1952', '1952');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1953', '04', 'Apr', 'Quarter 2 1953', '1953');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1953', '06', 'Jun', 'Quarter 2 1953', '1953');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1955', '05', 'May', 'Quarter 2 1955', '1955');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1955', '10', 'Oct', 'Quarter 4 1955', '1955');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1959', '10', 'Oct', 'Quarter 4 1959', '1959');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1960', '01', 'Jan', 'Quarter 1 1960', '1960');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1960', '08', 'Aug', 'Quarter 3 1960', '1960');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1961', '06', 'Jun', 'Quarter 2 1961', '1961');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1961', '11', 'Nov', 'Quarter 4 1961', '1961');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1962', '09', 'Sep', 'Quarter 3 1962', '1962');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1962', '11', 'Nov', 'Quarter 4 1962', '1962');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1963', '10', 'Oct', 'Quarter 4 1963', '1963');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1964', '01', 'Jan', 'Quarter 1 1964', '1964');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1964', '08', 'Aug', 'Quarter 3 1964', '1964');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1968', '07', 'Jul', 'Quarter 3 1968', '1968');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1968', '08', 'Aug', 'Quarter 3 1968', '1968');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1968', '09', 'Sep', 'Quarter 3 1968', '1968');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1969', '11', 'Nov', 'Quarter 4 1969', '1969');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1970', '05', 'May', 'Quarter 2 1970', '1970');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1971', '03', 'Mar', 'Quarter 1 1971', '1971');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1972', '12', 'Dec', 'Quarter 4 1972', '1972');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1974', '09', 'Sep', 'Quarter 3 1974', '1974');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1975', '02', 'Feb', 'Quarter 1 1975', '1975');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1975', '11', 'Nov', 'Quarter 4 1975', '1975');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1976', '09', 'Sep', 'Quarter 3 1976', '1976');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1976', '11', 'Nov', 'Quarter 4 1976', '1976');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1976', '12', 'Dec', 'Quarter 4 1976', '1976');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1977', '03', 'Mar', 'Quarter 1 1977', '1977');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1977', '09', 'Sep', 'Quarter 3 1977', '1977');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1978', '09', 'Sep', 'Quarter 3 1978', '1978');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1979', '10', 'Oct', 'Quarter 4 1979', '1979');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1980', '02', 'Feb', 'Quarter 1 1980', '1980');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1980', '11', 'Nov', 'Quarter 4 1980', '1980');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1981', '01', 'Jan', 'Quarter 1 1981', '1981');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1984', '01', 'Jan', 'Quarter 1 1984', '1984');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1984', '05', 'May', 'Quarter 2 1984', '1984');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1984', '08', 'Aug', 'Quarter 3 1984', '1984');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1986', '03', 'Mar', 'Quarter 1 1986', '1986');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1986', '08', 'Aug', 'Quarter 3 1986', '1986');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1986', '11', 'Nov', 'Quarter 4 1986', '1986');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1987', '10', 'Oct', 'Quarter 4 1987', '1987');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1988', '01', 'Jan', 'Quarter 1 1988', '1988');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1988', '02', 'Feb', 'Quarter 1 1988', '1988');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1988', '05', 'May', 'Quarter 2 1988', '1988');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1988', '12', 'Dec', 'Quarter 4 1988', '1988');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1990', '03', 'Mar', 'Quarter 1 1990', '1990');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1990', '11', 'Nov', 'Quarter 4 1990', '1990');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1991', '06', 'Jun', 'Quarter 2 1991', '1991');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1991', '09', 'Sep', 'Quarter 3 1991', '1991');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1992', '01', 'Jan', 'Quarter 1 1992', '1992');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1993', '08', 'Aug', 'Quarter 3 1993', '1993');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1993', '11', 'Nov', 'Quarter 4 1993', '1993');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1993', '12', 'Dec', 'Quarter 4 1993', '1993');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1994', '02', 'Feb', 'Quarter 1 1994', '1994');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1994', '06', 'Jun', 'Quarter 2 1994', '1994');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1994', '11', 'Nov', 'Quarter 4 1994', '1994');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1995', '01', 'Jan', 'Quarter 1 1995', '1995');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1995', '06', 'Jun', 'Quarter 2 1995', '1995');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1996', '01', 'Jan', 'Quarter 1 1996', '1996');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1997', '04', 'Apr', 'Quarter 2 1997', '1997');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1997', '06', 'Jun', 'Quarter 2 1997', '1997');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1998', '06', 'Jun', 'Quarter 2 1998', '1998');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1999', '12', 'Dec', 'Quarter 4 1999', '1999');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2000', '10', 'Oct', 'Quarter 4 2000', '2000');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2000', '12', 'Dec', 'Quarter 4 2000', '2000');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2002', '08', 'Aug', 'Quarter 3 2002', '2002');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2003', '11', 'Nov', 'Quarter 4 2003', '2003');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2004', '06', 'Jun', 'Quarter 2 2004', '2004');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2005', '09', 'Sep', 'Quarter 3 2005', '2005');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2006', '10', 'Oct', 'Quarter 4 2006', '2006');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2006', '11', 'Nov', 'Quarter 4 2006', '2006');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2008', '08', 'Aug', 'Quarter 3 2008', '2008');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2008', '09', 'Sep', 'Quarter 3 2008', '2008');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2008', '10', 'Oct', 'Quarter 4 2008', '2008');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2008', '12', 'Dec', 'Quarter 4 2008', '2008');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2010', '02', 'Feb', 'Quarter 1 2010', '2010');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2010', '10', 'Oct', 'Quarter 4 2010', '2010');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2010', '11', 'Nov', 'Quarter 4 2010', '2010');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2012', '01', 'Jan', 'Quarter 1 2012', '2012');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2013', '02', 'Feb', 'Quarter 1 2013', '2013');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2013', '11', 'Nov', 'Quarter 4 2013', '2013');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2014', '05', 'May', 'Quarter 2 2014', '2014');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2016', '02', 'Feb', 'Quarter 1 2016', '2016');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2016', '11', 'Nov', 'Quarter 4 2016', '2016');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2017', '01', 'Jan', 'Quarter 1 2017', '2017');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2017', '12', 'Dec', 'Quarter 4 2017', '2017');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2018', '06', 'Jun', 'Quarter 2 2018', '2018');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2020', '06', 'Jun', 'Quarter 2 2020', '2020');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1950', '01', 'Jan', 'Quarter 1 1950', '1950');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1950', '02', 'Feb', 'Quarter 1 1950', '1950');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1951', '04', 'Apr', 'Quarter 2 1951', '1951');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1951', '11', 'Nov', 'Quarter 4 1951', '1951');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1952', '03', 'Mar', 'Quarter 1 1952', '1952');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1953', '10', 'Oct', 'Quarter 4 1953', '1953');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1956', '01', 'Jan', 'Quarter 1 1956', '1956');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1956', '04', 'Apr', 'Quarter 2 1956', '1956');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1956', '10', 'Oct', 'Quarter 4 1956', '1956');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1957', '01', 'Jan', 'Quarter 1 1957', '1957');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1957', '02', 'Feb', 'Quarter 1 1957', '1957');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1957', '04', 'Apr', 'Quarter 2 1957', '1957');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1957', '09', 'Sep', 'Quarter 3 1957', '1957');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1957', '12', 'Dec', 'Quarter 4 1957', '1957');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1958', '07', 'Jul', 'Quarter 3 1958', '1958');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1959', '03', 'Mar', 'Quarter 1 1959', '1959');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1959', '05', 'May', 'Quarter 2 1959', '1959');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1959', '12', 'Dec', 'Quarter 4 1959', '1959');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1961', '08', 'Aug', 'Quarter 3 1961', '1961');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1962', '08', 'Aug', 'Quarter 3 1962', '1962');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1962', '10', 'Oct', 'Quarter 4 1962', '1962');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1962', '12', 'Dec', 'Quarter 4 1962', '1962');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1963', '01', 'Jan', 'Quarter 1 1963', '1963');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1963', '06', 'Jun', 'Quarter 2 1963', '1963');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1963', '08', 'Aug', 'Quarter 3 1963', '1963');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1964', '02', 'Feb', 'Quarter 1 1964', '1964');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1964', '06', 'Jun', 'Quarter 2 1964', '1964');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1964', '07', 'Jul', 'Quarter 3 1964', '1964');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1964', '09', 'Sep', 'Quarter 3 1964', '1964');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1965', '03', 'Mar', 'Quarter 1 1965', '1965');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1965', '05', 'May', 'Quarter 2 1965', '1965');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1966', '07', 'Jul', 'Quarter 3 1966', '1966');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1967', '10', 'Oct', 'Quarter 4 1967', '1967');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1970', '03', 'Mar', 'Quarter 1 1970', '1970');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1971', '07', 'Jul', 'Quarter 3 1971', '1971');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1971', '12', 'Dec', 'Quarter 4 1971', '1971');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1972', '01', 'Jan', 'Quarter 1 1972', '1972');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1972', '02', 'Feb', 'Quarter 1 1972', '1972');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1972', '04', 'Apr', 'Quarter 2 1972', '1972');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1972', '10', 'Oct', 'Quarter 4 1972', '1972');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1973', '03', 'Mar', 'Quarter 1 1973', '1973');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1973', '12', 'Dec', 'Quarter 4 1973', '1973');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1974', '06', 'Jun', 'Quarter 2 1974', '1974');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1975', '04', 'Apr', 'Quarter 2 1975', '1975');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1975', '12', 'Dec', 'Quarter 4 1975', '1975');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1976', '08', 'Aug', 'Quarter 3 1976', '1976');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1977', '04', 'Apr', 'Quarter 2 1977', '1977');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1977', '05', 'May', 'Quarter 2 1977', '1977');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1977', '06', 'Jun', 'Quarter 2 1977', '1977');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1977', '10', 'Oct', 'Quarter 4 1977', '1977');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1978', '01', 'Jan', 'Quarter 1 1978', '1978');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1978', '08', 'Aug', 'Quarter 3 1978', '1978');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1978', '10', 'Oct', 'Quarter 4 1978', '1978');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1978', '11', 'Nov', 'Quarter 4 1978', '1978');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1979', '03', 'Mar', 'Quarter 1 1979', '1979');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1979', '08', 'Aug', 'Quarter 3 1979', '1979');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1980', '01', 'Jan', 'Quarter 1 1980', '1980');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1980', '04', 'Apr', 'Quarter 2 1980', '1980');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1980', '08', 'Aug', 'Quarter 3 1980', '1980');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1981', '03', 'Mar', 'Quarter 1 1981', '1981');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1981', '04', 'Apr', 'Quarter 2 1981', '1981');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1981', '11', 'Nov', 'Quarter 4 1981', '1981');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1982', '05', 'May', 'Quarter 2 1982', '1982');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1982', '11', 'Nov', 'Quarter 4 1982', '1982');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1983', '07', 'Jul', 'Quarter 3 1983', '1983');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1983', '10', 'Oct', 'Quarter 4 1983', '1983');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1985', '06', 'Jun', 'Quarter 2 1985', '1985');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1985', '08', 'Aug', 'Quarter 3 1985', '1985');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1987', '05', 'May', 'Quarter 2 1987', '1987');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1988', '03', 'Mar', 'Quarter 1 1988', '1988');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1988', '06', 'Jun', 'Quarter 2 1988', '1988');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1988', '09', 'Sep', 'Quarter 3 1988', '1988');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1989', '05', 'May', 'Quarter 2 1989', '1989');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1989', '09', 'Sep', 'Quarter 3 1989', '1989');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1992', '03', 'Mar', 'Quarter 1 1992', '1992');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1992', '08', 'Aug', 'Quarter 3 1992', '1992');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1993', '01', 'Jan', 'Quarter 1 1993', '1993');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1993', '02', 'Feb', 'Quarter 1 1993', '1993');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1995', '03', 'Mar', 'Quarter 1 1995', '1995');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1995', '07', 'Jul', 'Quarter 3 1995', '1995');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1995', '11', 'Nov', 'Quarter 4 1995', '1995');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1997', '12', 'Dec', 'Quarter 4 1997', '1997');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1998', '10', 'Oct', 'Quarter 4 1998', '1998');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1999', '02', 'Feb', 'Quarter 1 1999', '1999');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2001', '03', 'Mar', 'Quarter 1 2001', '2001');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2001', '12', 'Dec', 'Quarter 4 2001', '2001');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2002', '01', 'Jan', 'Quarter 1 2002', '2002');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2002', '09', 'Sep', 'Quarter 3 2002', '2002');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2002', '11', 'Nov', 'Quarter 4 2002', '2002');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2003', '01', 'Jan', 'Quarter 1 2003', '2003');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2005', '02', 'Feb', 'Quarter 1 2005', '2005');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2005', '03', 'Mar', 'Quarter 1 2005', '2005');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2006', '05', 'May', 'Quarter 2 2006', '2006');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2006', '07', 'Jul', 'Quarter 3 2006', '2006');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2006', '12', 'Dec', 'Quarter 4 2006', '2006');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2007', '02', 'Feb', 'Quarter 1 2007', '2007');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2009', '06', 'Jun', 'Quarter 2 2009', '2009');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2010', '04', 'Apr', 'Quarter 2 2010', '2010');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2011', '04', 'Apr', 'Quarter 2 2011', '2011');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2012', '06', 'Jun', 'Quarter 2 2012', '2012');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2013', '05', 'May', 'Quarter 2 2013', '2013');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2014', '02', 'Feb', 'Quarter 1 2014', '2014');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2014', '03', 'Mar', 'Quarter 1 2014', '2014');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2014', '06', 'Jun', 'Quarter 2 2014', '2014');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2014', '10', 'Oct', 'Quarter 4 2014', '2014');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2016', '01', 'Jan', 'Quarter 1 2016', '2016');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2017', '08', 'Aug', 'Quarter 3 2017', '2017');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2019', '04', 'Apr', 'Quarter 2 2019', '2019');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2019', '05', 'May', 'Quarter 2 2019', '2019');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-2019', '10', 'Oct', 'Quarter 4 2019', '2019');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2020', '02', 'Feb', 'Quarter 1 2020', '2020');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2020', '07', 'Jul', 'Quarter 3 2020', '2020');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1950', '06', 'Jun', 'Quarter 2 1950', '1950');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1950', '09', 'Sep', 'Quarter 3 1950', '1950');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1951', '03', 'Mar', 'Quarter 1 1951', '1951');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1951', '08', 'Aug', 'Quarter 3 1951', '1951');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1952', '02', 'Feb', 'Quarter 1 1952', '1952');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1952', '05', 'May', 'Quarter 2 1952', '1952');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1953', '05', 'May', 'Quarter 2 1953', '1953');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1954', '04', 'Apr', 'Quarter 2 1954', '1954');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1955', '09', 'Sep', 'Quarter 3 1955', '1955');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1957', '06', 'Jun', 'Quarter 2 1957', '1957');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1957', '10', 'Oct', 'Quarter 4 1957', '1957');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1957', '11', 'Nov', 'Quarter 4 1957', '1957');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1958', '06', 'Jun', 'Quarter 2 1958', '1958');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1958', '08', 'Aug', 'Quarter 3 1958', '1958');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1958', '12', 'Dec', 'Quarter 4 1958', '1958');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1959', '02', 'Feb', 'Quarter 1 1959', '1959');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1959', '04', 'Apr', 'Quarter 2 1959', '1959');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1960', '02', 'Feb', 'Quarter 1 1960', '1960');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1960', '03', 'Mar', 'Quarter 1 1960', '1960');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1960', '09', 'Sep', 'Quarter 3 1960', '1960');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1960', '10', 'Oct', 'Quarter 4 1960', '1960');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1961', '03', 'Mar', 'Quarter 1 1961', '1961');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1961', '07', 'Jul', 'Quarter 3 1961', '1961');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1961', '09', 'Sep', 'Quarter 3 1961', '1961');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1962', '04', 'Apr', 'Quarter 2 1962', '1962');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1963', '03', 'Mar', 'Quarter 1 1963', '1963');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1963', '04', 'Apr', 'Quarter 2 1963', '1963');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1964', '05', 'May', 'Quarter 2 1964', '1964');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1965', '11', 'Nov', 'Quarter 4 1965', '1965');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1966', '08', 'Aug', 'Quarter 3 1966', '1966');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1967', '07', 'Jul', 'Quarter 3 1967', '1967');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1967', '08', 'Aug', 'Quarter 3 1967', '1967');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1968', '05', 'May', 'Quarter 2 1968', '1968');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1968', '10', 'Oct', 'Quarter 4 1968', '1968');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1970', '02', 'Feb', 'Quarter 1 1970', '1970');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1970', '06', 'Jun', 'Quarter 2 1970', '1970');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1970', '08', 'Aug', 'Quarter 3 1970', '1970');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1970', '09', 'Sep', 'Quarter 3 1970', '1970');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1971', '02', 'Feb', 'Quarter 1 1971', '1971');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1971', '10', 'Oct', 'Quarter 4 1971', '1971');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1973', '04', 'Apr', 'Quarter 2 1973', '1973');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1973', '06', 'Jun', 'Quarter 2 1973', '1973');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1974', '01', 'Jan', 'Quarter 1 1974', '1974');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1974', '03', 'Mar', 'Quarter 1 1974', '1974');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1975', '07', 'Jul', 'Quarter 3 1975', '1975');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1976', '04', 'Apr', 'Quarter 2 1976', '1976');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1978', '06', 'Jun', 'Quarter 2 1978', '1978');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1979', '01', 'Jan', 'Quarter 1 1979', '1979');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1980', '06', 'Jun', 'Quarter 2 1980', '1980');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1980', '07', 'Jul', 'Quarter 3 1980', '1980');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1981', '05', 'May', 'Quarter 2 1981', '1981');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1982', '09', 'Sep', 'Quarter 3 1982', '1982');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1982', '12', 'Dec', 'Quarter 4 1982', '1982');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1983', '01', 'Jan', 'Quarter 1 1983', '1983');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1983', '02', 'Feb', 'Quarter 1 1983', '1983');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1983', '04', 'Apr', 'Quarter 2 1983', '1983');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1984', '03', 'Mar', 'Quarter 1 1984', '1984');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1985', '05', 'May', 'Quarter 2 1985', '1985');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1985', '09', 'Sep', 'Quarter 3 1985', '1985');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1986', '12', 'Dec', 'Quarter 4 1986', '1986');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1987', '02', 'Feb', 'Quarter 1 1987', '1987');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1988', '10', 'Oct', 'Quarter 4 1988', '1988');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1990', '01', 'Jan', 'Quarter 1 1990', '1990');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1990', '04', 'Apr', 'Quarter 2 1990', '1990');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1990', '08', 'Aug', 'Quarter 3 1990', '1990');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1990', '09', 'Sep', 'Quarter 3 1990', '1990');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1991', '03', 'Mar', 'Quarter 1 1991', '1991');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1991', '04', 'Apr', 'Quarter 2 1991', '1991');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1991', '11', 'Nov', 'Quarter 4 1991', '1991');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1992', '06', 'Jun', 'Quarter 2 1992', '1992');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1992', '10', 'Oct', 'Quarter 4 1992', '1992');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1994', '05', 'May', 'Quarter 2 1994', '1994');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1996', '09', 'Sep', 'Quarter 3 1996', '1996');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1997', '01', 'Jan', 'Quarter 1 1997', '1997');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1997', '05', 'May', 'Quarter 2 1997', '1997');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1997', '07', 'Jul', 'Quarter 3 1997', '1997');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1998', '01', 'Jan', 'Quarter 1 1998', '1998');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1998', '07', 'Jul', 'Quarter 3 1998', '1998');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1998', '09', 'Sep', 'Quarter 3 1998', '1998');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1999', '06', 'Jun', 'Quarter 2 1999', '1999');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2000', '01', 'Jan', 'Quarter 1 2000', '2000');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2000', '04', 'Apr', 'Quarter 2 2000', '2000');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2000', '05', 'May', 'Quarter 2 2000', '2000');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2000', '11', 'Nov', 'Quarter 4 2000', '2000');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2001', '09', 'Sep', 'Quarter 3 2001', '2001');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2003', '09', 'Sep', 'Quarter 3 2003', '2003');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2004', '12', 'Dec', 'Quarter 4 2004', '2004');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2005', '07', 'Jul', 'Quarter 3 2005', '2005');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2007', '12', 'Dec', 'Quarter 4 2007', '2007');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2008', '01', 'Jan', 'Quarter 1 2008', '2008');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2008', '07', 'Jul', 'Quarter 3 2008', '2008');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2009', '05', 'May', 'Quarter 2 2009', '2009');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2010', '01', 'Jan', 'Quarter 1 2010', '2010');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2010', '05', 'May', 'Quarter 2 2010', '2010');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2010', '09', 'Sep', 'Quarter 3 2010', '2010');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2013', '01', 'Jan', 'Quarter 1 2013', '2013');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2013', '06', 'Jun', 'Quarter 2 2013', '2013');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2014', '09', 'Sep', 'Quarter 3 2014', '2014');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2014', '11', 'Nov', 'Quarter 4 2014', '2014');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2015', '05', 'May', 'Quarter 2 2015', '2015');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-2015', '11', 'Nov', 'Quarter 4 2015', '2015');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2016', '03', 'Mar', 'Quarter 1 2016', '2016');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2016', '08', 'Aug', 'Quarter 3 2016', '2016');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2016', '12', 'Dec', 'Quarter 4 2016', '2016');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2017', '02', 'Feb', 'Quarter 1 2017', '2017');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2017', '04', 'Apr', 'Quarter 2 2017', '2017');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2019', '03', 'Mar', 'Quarter 1 2019', '2019');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2019', '08', 'Aug', 'Quarter 3 2019', '2019');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-9999', '12', 'Dec', 'Quarter 4 9999', '9999');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1950', '03', 'Mar', 'Quarter 1 1950', '1950');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1951', '05', 'May', 'Quarter 2 1951', '1951');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1952', '04', 'Apr', 'Quarter 2 1952', '1952');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1952', '07', 'Jul', 'Quarter 3 1952', '1952');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1953', '01', 'Jan', 'Quarter 1 1953', '1953');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1954', '09', 'Sep', 'Quarter 3 1954', '1954');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1954', '11', 'Nov', 'Quarter 4 1954', '1954');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1955', '01', 'Jan', 'Quarter 1 1955', '1955');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1955', '02', 'Feb', 'Quarter 1 1955', '1955');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1955', '11', 'Nov', 'Quarter 4 1955', '1955');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1956', '02', 'Feb', 'Quarter 1 1956', '1956');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1956', '11', 'Nov', 'Quarter 4 1956', '1956');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1959', '08', 'Aug', 'Quarter 3 1959', '1959');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1960', '06', 'Jun', 'Quarter 2 1960', '1960');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1961', '05', 'May', 'Quarter 2 1961', '1961');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1962', '03', 'Mar', 'Quarter 1 1962', '1962');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1962', '07', 'Jul', 'Quarter 3 1962', '1962');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1963', '05', 'May', 'Quarter 2 1963', '1963');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1963', '12', 'Dec', 'Quarter 4 1963', '1963');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1964', '03', 'Mar', 'Quarter 1 1964', '1964');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1964', '04', 'Apr', 'Quarter 2 1964', '1964');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1965', '02', 'Feb', 'Quarter 1 1965', '1965');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1966', '05', 'May', 'Quarter 2 1966', '1966');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1966', '09', 'Sep', 'Quarter 3 1966', '1966');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1968', '02', 'Feb', 'Quarter 1 1968', '1968');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1968', '03', 'Mar', 'Quarter 1 1968', '1968');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1968', '11', 'Nov', 'Quarter 4 1968', '1968');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1971', '01', 'Jan', 'Quarter 1 1971', '1971');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1973', '05', 'May', 'Quarter 2 1973', '1973');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1973', '07', 'Jul', 'Quarter 3 1973', '1973');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1975', '09', 'Sep', 'Quarter 3 1975', '1975');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1976', '01', 'Jan', 'Quarter 1 1976', '1976');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1976', '03', 'Mar', 'Quarter 1 1976', '1976');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1977', '01', 'Jan', 'Quarter 1 1977', '1977');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1978', '12', 'Dec', 'Quarter 4 1978', '1978');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1979', '04', 'Apr', 'Quarter 2 1979', '1979');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1980', '12', 'Dec', 'Quarter 4 1980', '1980');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1981', '02', 'Feb', 'Quarter 1 1981', '1981');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1982', '02', 'Feb', 'Quarter 1 1982', '1982');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1982', '03', 'Mar', 'Quarter 1 1982', '1982');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1983', '12', 'Dec', 'Quarter 4 1983', '1983');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1984', '07', 'Jul', 'Quarter 3 1984', '1984');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1985', '04', 'Apr', 'Quarter 2 1985', '1985');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1985', '07', 'Jul', 'Quarter 3 1985', '1985');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1987', '08', 'Aug', 'Quarter 3 1987', '1987');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1987', '09', 'Sep', 'Quarter 3 1987', '1987');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1989', '01', 'Jan', 'Quarter 1 1989', '1989');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1989', '08', 'Aug', 'Quarter 3 1989', '1989');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1990', '07', 'Jul', 'Quarter 3 1990', '1990');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1990', '10', 'Oct', 'Quarter 4 1990', '1990');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-1991', '01', 'Jan', 'Quarter 1 1991', '1991');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1991', '02', 'Feb', 'Quarter 1 1991', '1991');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1992', '09', 'Sep', 'Quarter 3 1992', '1992');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-1994', '07', 'Jul', 'Quarter 3 1994', '1994');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-1994', '08', 'Aug', 'Quarter 3 1994', '1994');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1995', '04', 'Apr', 'Quarter 2 1995', '1995');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1995', '05', 'May', 'Quarter 2 1995', '1995');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1995', '09', 'Sep', 'Quarter 3 1995', '1995');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1995', '10', 'Oct', 'Quarter 4 1995', '1995');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1996', '03', 'Mar', 'Quarter 1 1996', '1996');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-1996', '05', 'May', 'Quarter 2 1996', '1996');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-1996', '06', 'Jun', 'Quarter 2 1996', '1996');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Oct-1996', '10', 'Oct', 'Quarter 4 1996', '1996');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-1996', '12', 'Dec', 'Quarter 4 1996', '1996');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-1998', '02', 'Feb', 'Quarter 1 1998', '1998');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-1998', '04', 'Apr', 'Quarter 2 1998', '1998');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-1999', '03', 'Mar', 'Quarter 1 1999', '1999');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-1999', '09', 'Sep', 'Quarter 3 1999', '1999');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Nov-1999', '11', 'Nov', 'Quarter 4 1999', '1999');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2000', '06', 'Jun', 'Quarter 2 2000', '2000');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2000', '08', 'Aug', 'Quarter 3 2000', '2000');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2001', '08', 'Aug', 'Quarter 3 2001', '2001');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2002', '04', 'Apr', 'Quarter 2 2002', '2002');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2003', '06', 'Jun', 'Quarter 2 2003', '2003');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2004', '02', 'Feb', 'Quarter 1 2004', '2004');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2004', '07', 'Jul', 'Quarter 3 2004', '2004');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2006', '02', 'Feb', 'Quarter 1 2006', '2006');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2006', '03', 'Mar', 'Quarter 1 2006', '2006');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2006', '04', 'Apr', 'Quarter 2 2006', '2006');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2008', '02', 'Feb', 'Quarter 1 2008', '2008');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2008', '06', 'Jun', 'Quarter 2 2008', '2008');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2009', '02', 'Feb', 'Quarter 1 2009', '2009');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2010', '12', 'Dec', 'Quarter 4 2010', '2010');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2011', '01', 'Jan', 'Quarter 1 2011', '2011');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2011', '03', 'Mar', 'Quarter 1 2011', '2011');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2011', '06', 'Jun', 'Quarter 2 2011', '2011');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jul-2013', '07', 'Jul', 'Quarter 3 2013', '2013');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Feb-2015', '02', 'Feb', 'Quarter 1 2015', '2015');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Apr-2015', '04', 'Apr', 'Quarter 2 2015', '2015');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jun-2015', '06', 'Jun', 'Quarter 2 2015', '2015');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Aug-2015', '08', 'Aug', 'Quarter 3 2015', '2015');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2015', '12', 'Dec', 'Quarter 4 2015', '2015');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2016', '09', 'Sep', 'Quarter 3 2016', '2016');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Jan-2018', '01', 'Jan', 'Quarter 1 2018', '2018');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Mar-2018', '03', 'Mar', 'Quarter 1 2018', '2018');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2018', '05', 'May', 'Quarter 2 2018', '2018');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Sep-2018', '09', 'Sep', 'Quarter 3 2018', '2018');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('Dec-2018', '12', 'Dec', 'Quarter 4 2018', '2018');
Insert into DIM_MONTH
   (MNTH_DESC, MNTH_ID, MNTH_NM, QUARTER_DESC, YEAR_ID)
 Values
   ('May-2020', '05', 'May', 'Quarter 2 2020', '2020');
COMMIT;
