update DGM_DOCUMENT_GENERATION_MASTER dgm set DGM.FETCH_QUERY = 'INSERT INTO IS_CONC_TC_CHILD (
INTERNAL_INVOICE_REF_NO,
TC_AMOUNT,
ELEMENT_NAME,
ELEMENT_ID,
AMOUNT_UNIT,
SUB_LOT_NO,
GMR_REF_NO,
ASSAY_DETAIL,
DRY_QUANTITY,
QUANTITY_UNIT_NAME,
STOCK_REF_NO,
NET_TC,
INTERNAL_DOC_REF_NO
)
select 
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
sum(INTC.TCHARGES_AMOUNT) as TC_AMOUNT,
AML.ATTRIBUTE_NAME as ELEMENT_NAME,
AML.ATTRIBUTE_ID as ELEMENT_ID,
CM.CUR_CODE as AMOUNT_UNIT,
INTC.SUB_LOT_NO as SUB_LOT_NO,
GMR.GMR_REF_NO as GMR_REF_NO,
PQCA.TYPICAL||'' ''||RM.RATIO_NAME as ASSAY_DETAIL,
INTC.LOT_QTY as DRY_QUANTITY,
QUM.QTY_UNIT as QUANTITY_UNIT_NAME,
GRD.INTERNAL_STOCK_REF_NO as STOCK_REF_NO,
INTC.TCHARGES_PRICE||'' ''||PUM.PRICE_UNIT_NAME as NET_TC,
?
from
IS_INVOICE_SUMMARY invs,
INTC_INV_TREATMENT_CHARGES intc,
AML_ATTRIBUTE_MASTER_LIST aml,
CM_CURRENCY_MASTER cm,
PCM_PHYSICAL_CONTRACT_MAIN pcm,
GRD_GOODS_RECORD_DETAIL grd,
GMR_GOODS_MOVEMENT_RECORD gmr,
IAM_INVOICE_ASSAY_MAPPING iam,
ASH_ASSAY_HEADER ash,
ASM_ASSAY_SUBLOT_MAPPING asm,
PQCA_PQ_CHEMICAL_ATTRIBUTES pqca,
QUM_QUANTITY_UNIT_MASTER qum,
RM_RATIO_MASTER rm,
PPU_PRODUCT_PRICE_UNITS ppu,
PUM_PRICE_UNIT_MASTER pum
where
INVS.INTERNAL_INVOICE_REF_NO = INTC.INTERNAL_INVOICE_REF_NO(+)
and INTC.ELEMENT_ID = AML.ATTRIBUTE_ID(+)
and PCM.INVOICE_CURRENCY_ID = CM.CUR_ID(+)
and INVS.INTERNAL_CONTRACT_REF_NO = PCM.INTERNAL_CONTRACT_REF_NO(+)
and INTC.GRD_ID = GRD.INTERNAL_GRD_REF_NO
and GRD.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO
and INVS.INTERNAL_INVOICE_REF_NO = IAM.INTERNAL_INVOICE_REF_NO
and INTC.GRD_ID = ASH.INTERNAL_GRD_REF_NO
and INTC.ELEMENT_ID = PQCA.ELEMENT_ID
and IAM.ASH_ID = ASH.ASH_ID
and ASH.ASH_ID = ASM.ASH_ID
and ASM.ASM_ID = PQCA.ASM_ID
and GRD.QTY_UNIT_ID = QUM.QTY_UNIT_ID
and PQCA.UNIT_OF_MEASURE = RM.RATIO_ID
and INTC.TCHARGES_PRICE_UNIT_ID = PPU.INTERNAL_PRICE_UNIT_ID
and PPU.PRICE_UNIT_ID = PUM.PRICE_UNIT_ID
and INVS.INTERNAL_INVOICE_REF_NO = ?
group by
INVS.INTERNAL_INVOICE_REF_NO,
AML.ATTRIBUTE_NAME,
AML.ATTRIBUTE_ID,
CM.CUR_CODE,
INTC.SUB_LOT_NO,
GRD.INTERNAL_STOCK_REF_NO,
GMR.GMR_REF_NO,
INTC.LOT_QTY,
PQCA.TYPICAL,
QUM.QTY_UNIT,
RM.RATIO_NAME,
INTC.TCHARGES_PRICE,
PUM.PRICE_UNIT_NAME'
where
DGM.DOC_ID = 'CREATE_DFI'
and DGM.DGM_ID='DGM-DFIC-C2';

update DGM_DOCUMENT_GENERATION_MASTER dgm set DGM.FETCH_QUERY = 'INSERT INTO IS_CONC_TC_CHILD (
INTERNAL_INVOICE_REF_NO,
TC_AMOUNT,
ELEMENT_NAME,
ELEMENT_ID,
AMOUNT_UNIT,
SUB_LOT_NO,
GMR_REF_NO,
ASSAY_DETAIL,
DRY_QUANTITY,
QUANTITY_UNIT_NAME,
STOCK_REF_NO,
NET_TC,
INTERNAL_DOC_REF_NO
)
select 
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
sum(INTC.TCHARGES_AMOUNT) as TC_AMOUNT,
AML.ATTRIBUTE_NAME as ELEMENT_NAME,
AML.ATTRIBUTE_ID as ELEMENT_ID,
CM.CUR_CODE as AMOUNT_UNIT,
INTC.SUB_LOT_NO as SUB_LOT_NO,
GMR.GMR_REF_NO as GMR_REF_NO,
PQCA.TYPICAL||'' ''||RM.RATIO_NAME as ASSAY_DETAIL,
INTC.LOT_QTY as DRY_QUANTITY,
QUM.QTY_UNIT as QUANTITY_UNIT_NAME,
GRD.INTERNAL_STOCK_REF_NO as STOCK_REF_NO,
INTC.TCHARGES_PRICE||'' ''||PUM.PRICE_UNIT_NAME as NET_TC,
?
from
IS_INVOICE_SUMMARY invs,
INTC_INV_TREATMENT_CHARGES intc,
AML_ATTRIBUTE_MASTER_LIST aml,
CM_CURRENCY_MASTER cm,
PCM_PHYSICAL_CONTRACT_MAIN pcm,
GRD_GOODS_RECORD_DETAIL grd,
GMR_GOODS_MOVEMENT_RECORD gmr,
IAM_INVOICE_ASSAY_MAPPING iam,
ASH_ASSAY_HEADER ash,
ASM_ASSAY_SUBLOT_MAPPING asm,
PQCA_PQ_CHEMICAL_ATTRIBUTES pqca,
QUM_QUANTITY_UNIT_MASTER qum,
RM_RATIO_MASTER rm,
PPU_PRODUCT_PRICE_UNITS ppu,
PUM_PRICE_UNIT_MASTER pum
where
INVS.INTERNAL_INVOICE_REF_NO = INTC.INTERNAL_INVOICE_REF_NO(+)
and INTC.ELEMENT_ID = AML.ATTRIBUTE_ID(+)
and PCM.INVOICE_CURRENCY_ID = CM.CUR_ID(+)
and INVS.INTERNAL_CONTRACT_REF_NO = PCM.INTERNAL_CONTRACT_REF_NO(+)
and INTC.GRD_ID = GRD.INTERNAL_GRD_REF_NO
and GRD.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO
and INVS.INTERNAL_INVOICE_REF_NO = IAM.INTERNAL_INVOICE_REF_NO
and INTC.GRD_ID = ASH.INTERNAL_GRD_REF_NO
and INTC.ELEMENT_ID = PQCA.ELEMENT_ID
and IAM.ASH_ID = ASH.ASH_ID
and ASH.ASH_ID = ASM.ASH_ID
and ASM.ASM_ID = PQCA.ASM_ID
and GRD.QTY_UNIT_ID = QUM.QTY_UNIT_ID
and PQCA.UNIT_OF_MEASURE = RM.RATIO_ID
and INTC.TCHARGES_PRICE_UNIT_ID = PPU.INTERNAL_PRICE_UNIT_ID
and PPU.PRICE_UNIT_ID = PUM.PRICE_UNIT_ID
and INVS.INTERNAL_INVOICE_REF_NO = ?
group by
INVS.INTERNAL_INVOICE_REF_NO,
AML.ATTRIBUTE_NAME,
AML.ATTRIBUTE_ID,
CM.CUR_CODE,
INTC.SUB_LOT_NO,
GRD.INTERNAL_STOCK_REF_NO,
GMR.GMR_REF_NO,
INTC.LOT_QTY,
PQCA.TYPICAL,
QUM.QTY_UNIT,
RM.RATIO_NAME,
INTC.TCHARGES_PRICE,
PUM.PRICE_UNIT_NAME'
where
DGM.DOC_ID = 'CREATE_FI'
and DGM.DGM_ID='DGM-FIC-C2';

update DGM_DOCUMENT_GENERATION_MASTER dgm set DGM.FETCH_QUERY = 'INSERT INTO IS_CONC_TC_CHILD (
INTERNAL_INVOICE_REF_NO,
TC_AMOUNT,
ELEMENT_NAME,
ELEMENT_ID,
AMOUNT_UNIT,
SUB_LOT_NO,
GMR_REF_NO,
ASSAY_DETAIL,
DRY_QUANTITY,
QUANTITY_UNIT_NAME,
STOCK_REF_NO,
NET_TC,
INTERNAL_DOC_REF_NO
)
select 
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
sum(INTC.TCHARGES_AMOUNT) as TC_AMOUNT,
AML.ATTRIBUTE_NAME as ELEMENT_NAME,
AML.ATTRIBUTE_ID as ELEMENT_ID,
CM.CUR_CODE as AMOUNT_UNIT,
INTC.SUB_LOT_NO as SUB_LOT_NO,
GMR.GMR_REF_NO as GMR_REF_NO,
PQCA.TYPICAL||'' ''||RM.RATIO_NAME as ASSAY_DETAIL,
INTC.LOT_QTY as DRY_QUANTITY,
QUM.QTY_UNIT as QUANTITY_UNIT_NAME,
GRD.INTERNAL_STOCK_REF_NO as STOCK_REF_NO,
INTC.TCHARGES_PRICE||'' ''||PUM.PRICE_UNIT_NAME as NET_TC,
?
from
IS_INVOICE_SUMMARY invs,
INTC_INV_TREATMENT_CHARGES intc,
AML_ATTRIBUTE_MASTER_LIST aml,
CM_CURRENCY_MASTER cm,
PCM_PHYSICAL_CONTRACT_MAIN pcm,
GRD_GOODS_RECORD_DETAIL grd,
GMR_GOODS_MOVEMENT_RECORD gmr,
IAM_INVOICE_ASSAY_MAPPING iam,
ASH_ASSAY_HEADER ash,
ASM_ASSAY_SUBLOT_MAPPING asm,
PQCA_PQ_CHEMICAL_ATTRIBUTES pqca,
QUM_QUANTITY_UNIT_MASTER qum,
RM_RATIO_MASTER rm,
PPU_PRODUCT_PRICE_UNITS ppu,
PUM_PRICE_UNIT_MASTER pum
where
INVS.INTERNAL_INVOICE_REF_NO = INTC.INTERNAL_INVOICE_REF_NO(+)
and INTC.ELEMENT_ID = AML.ATTRIBUTE_ID(+)
and PCM.INVOICE_CURRENCY_ID = CM.CUR_ID(+)
and INVS.INTERNAL_CONTRACT_REF_NO = PCM.INTERNAL_CONTRACT_REF_NO(+)
and INTC.GRD_ID = GRD.INTERNAL_GRD_REF_NO
and GRD.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO
and INVS.INTERNAL_INVOICE_REF_NO = IAM.INTERNAL_INVOICE_REF_NO
and INTC.GRD_ID = ASH.INTERNAL_GRD_REF_NO
and INTC.ELEMENT_ID = PQCA.ELEMENT_ID
and IAM.ASH_ID = ASH.ASH_ID
and ASH.ASH_ID = ASM.ASH_ID
and ASM.ASM_ID = PQCA.ASM_ID
and GRD.QTY_UNIT_ID = QUM.QTY_UNIT_ID
and PQCA.UNIT_OF_MEASURE = RM.RATIO_ID
and INTC.TCHARGES_PRICE_UNIT_ID = PPU.INTERNAL_PRICE_UNIT_ID
and PPU.PRICE_UNIT_ID = PUM.PRICE_UNIT_ID
and INVS.INTERNAL_INVOICE_REF_NO = ?
group by
INVS.INTERNAL_INVOICE_REF_NO,
AML.ATTRIBUTE_NAME,
AML.ATTRIBUTE_ID,
CM.CUR_CODE,
INTC.SUB_LOT_NO,
GRD.INTERNAL_STOCK_REF_NO,
GMR.GMR_REF_NO,
INTC.LOT_QTY,
PQCA.TYPICAL,
QUM.QTY_UNIT,
RM.RATIO_NAME,
INTC.TCHARGES_PRICE,
PUM.PRICE_UNIT_NAME'
where
DGM.DOC_ID = 'CREATE_PI'
and DGM.DGM_ID='DGM-PIC-C2';

--FOR RC CHARGES
update DGM_DOCUMENT_GENERATION_MASTER dgm set DGM.FETCH_QUERY = 'INSERT INTO IS_CONC_RC_CHILD(
INTERNAL_INVOICE_REF_NO,
RC_AMOUNT,
ELEMENT_NAME,
ELEMENT_ID,
AMOUNT_UNIT,
SUB_LOT_NO,
GMR_REF_NO,
STOCK_REF_NO,
DRY_QUANTITY,
QUANTITY_UNIT_NAME,
ASSAY_CONTENT,
PAYABLE_CONTENT_PER,
DEDUCTION,
NET_PAYABLE_CONTENT,
NET_RC,
INTERNAL_DOC_REF_NO
)
select 
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
INRC.RCHARGES_AMOUNT as RC_AMOUNT,
AML.ATTRIBUTE_NAME as ELEMENT_NAME,
AML.ATTRIBUTE_ID as ELEMENT_ID,
CM.CUR_CODE as AMOUNT_UNIT,
INRC.SUB_LOT_NO as SUB_LOT_NO,
GMR.GMR_REF_NO as GMR_REF_NO,
GRD.INTERNAL_STOCK_REF_NO as STOCK_REF_NO,
INRC.LOT_QTY as DRY_QUANTITY,
QUM.QTY_UNIT as QUANTITY_UNIT_NAME,
PQCA.TYPICAL ||'' ''|| RM.RATIO_NAME as ASSAY_CONTENT,
PCEPC.PAYABLE_CONTENT_VALUE as PAYABLE_CONTENT_PER,
PCEPC.ASSAY_DEDUCTION ||'' '' || RM_DEC.RATIO_NAME as DEDUCTION,
PQCAPD.PAYABLE_PERCENTAGE||'' ''|| RM.RATIO_NAME as NET_PAYABLE_CONTENT,
INRC.RCHARGES_PRICE ||'' ''|| PUM.PRICE_UNIT_NAME as NET_RC,
?
from
IS_INVOICE_SUMMARY invs,
INRC_INV_REFINING_CHARGES inrc,
AML_ATTRIBUTE_MASTER_LIST aml,
CM_CURRENCY_MASTER cm,
PCM_PHYSICAL_CONTRACT_MAIN pcm,
GRD_GOODS_RECORD_DETAIL grd,
GMR_GOODS_MOVEMENT_RECORD gmr,
QUM_QUANTITY_UNIT_MASTER qum,
ASM_ASSAY_SUBLOT_MAPPING asm,
IAM_INVOICE_ASSAY_MAPPING iam,
ASH_ASSAY_HEADER ash,
PQCA_PQ_CHEMICAL_ATTRIBUTES pqca,
RM_RATIO_MASTER rm,
PCPCH_PC_PAYBLE_CONTENT_HEADER pcpch,
PCEPC_PC_ELEM_PAYABLE_CONTENT pcepc,
RM_RATIO_MASTER rm_dec,
PQCAPD_PRD_QLTY_CATTR_PAY_DTLS pqcapd,
PPU_PRODUCT_PRICE_UNITS ppu,
PUM_PRICE_UNIT_MASTER pum
where
INVS.INTERNAL_INVOICE_REF_NO = INRC.INTERNAL_INVOICE_REF_NO(+)
and INRC.ELEMENT_ID = AML.ATTRIBUTE_ID(+)
and PCM.INVOICE_CURRENCY_ID = CM.CUR_ID(+)
and INVS.INTERNAL_CONTRACT_REF_NO = PCM.INTERNAL_CONTRACT_REF_NO(+)
and INRC.GRD_ID = GRD.INTERNAL_GRD_REF_NO
and GRD.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO
and GRD.QTY_UNIT_ID = QUM.QTY_UNIT_ID 
and INVS.INTERNAL_INVOICE_REF_NO = IAM.INTERNAL_INVOICE_REF_NO
and GRD.INTERNAL_GRD_REF_NO = ASH.INTERNAL_GRD_REF_NO
and IAM.ASH_ID = ASH.ASH_ID
and ASH.ASH_ID = ASM.ASH_ID
and ASM.ASM_ID = PQCA.ASM_ID
and INRC.ELEMENT_ID = PQCA.ELEMENT_ID
and INRC.SUB_LOT_NO = ASM.SUB_LOT_NO
and PQCA.UNIT_OF_MEASURE = RM.RATIO_ID
and INVS.INTERNAL_CONTRACT_REF_NO = PCPCH.INTERNAL_CONTRACT_REF_NO
and PCPCH.PCPCH_ID = PCEPC.PCPCH_ID
and PCPCH.ELEMENT_ID = INRC.ELEMENT_ID
and PCEPC.ASSAY_DEDUCTION_UNIT_ID = rm_dec.RATIO_ID
and PQCA.PQCA_ID = PQCAPD.PQCA_ID
and INRC.RCHARGES_PRICE_UNIT_ID = PPU.INTERNAL_PRICE_UNIT_ID
and PPU.PRICE_UNIT_ID = PUM.PRICE_UNIT_ID
and INVS.INTERNAL_INVOICE_REF_NO = ?'
where
DGM.DOC_ID = 'CREATE_PI'
and DGM.DGM_ID='DGM-PIC-C3';

update DGM_DOCUMENT_GENERATION_MASTER dgm set DGM.FETCH_QUERY = 'INSERT INTO IS_CONC_RC_CHILD(
INTERNAL_INVOICE_REF_NO,
RC_AMOUNT,
ELEMENT_NAME,
ELEMENT_ID,
AMOUNT_UNIT,
SUB_LOT_NO,
GMR_REF_NO,
STOCK_REF_NO,
DRY_QUANTITY,
QUANTITY_UNIT_NAME,
ASSAY_CONTENT,
PAYABLE_CONTENT_PER,
DEDUCTION,
NET_PAYABLE_CONTENT,
NET_RC,
INTERNAL_DOC_REF_NO
)
select 
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
INRC.RCHARGES_AMOUNT as RC_AMOUNT,
AML.ATTRIBUTE_NAME as ELEMENT_NAME,
AML.ATTRIBUTE_ID as ELEMENT_ID,
CM.CUR_CODE as AMOUNT_UNIT,
INRC.SUB_LOT_NO as SUB_LOT_NO,
GMR.GMR_REF_NO as GMR_REF_NO,
GRD.INTERNAL_STOCK_REF_NO as STOCK_REF_NO,
INRC.LOT_QTY as DRY_QUANTITY,
QUM.QTY_UNIT as QUANTITY_UNIT_NAME,
PQCA.TYPICAL ||'' ''|| RM.RATIO_NAME as ASSAY_CONTENT,
PCEPC.PAYABLE_CONTENT_VALUE as PAYABLE_CONTENT_PER,
PCEPC.ASSAY_DEDUCTION ||'' '' || RM_DEC.RATIO_NAME as DEDUCTION,
PQCAPD.PAYABLE_PERCENTAGE||'' ''|| RM.RATIO_NAME as NET_PAYABLE_CONTENT,
INRC.RCHARGES_PRICE ||'' ''|| PUM.PRICE_UNIT_NAME as NET_RC,
?
from
IS_INVOICE_SUMMARY invs,
INRC_INV_REFINING_CHARGES inrc,
AML_ATTRIBUTE_MASTER_LIST aml,
CM_CURRENCY_MASTER cm,
PCM_PHYSICAL_CONTRACT_MAIN pcm,
GRD_GOODS_RECORD_DETAIL grd,
GMR_GOODS_MOVEMENT_RECORD gmr,
QUM_QUANTITY_UNIT_MASTER qum,
ASM_ASSAY_SUBLOT_MAPPING asm,
IAM_INVOICE_ASSAY_MAPPING iam,
ASH_ASSAY_HEADER ash,
PQCA_PQ_CHEMICAL_ATTRIBUTES pqca,
RM_RATIO_MASTER rm,
PCPCH_PC_PAYBLE_CONTENT_HEADER pcpch,
PCEPC_PC_ELEM_PAYABLE_CONTENT pcepc,
RM_RATIO_MASTER rm_dec,
PQCAPD_PRD_QLTY_CATTR_PAY_DTLS pqcapd,
PPU_PRODUCT_PRICE_UNITS ppu,
PUM_PRICE_UNIT_MASTER pum
where
INVS.INTERNAL_INVOICE_REF_NO = INRC.INTERNAL_INVOICE_REF_NO(+)
and INRC.ELEMENT_ID = AML.ATTRIBUTE_ID(+)
and PCM.INVOICE_CURRENCY_ID = CM.CUR_ID(+)
and INVS.INTERNAL_CONTRACT_REF_NO = PCM.INTERNAL_CONTRACT_REF_NO(+)
and INRC.GRD_ID = GRD.INTERNAL_GRD_REF_NO
and GRD.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO
and GRD.QTY_UNIT_ID = QUM.QTY_UNIT_ID 
and INVS.INTERNAL_INVOICE_REF_NO = IAM.INTERNAL_INVOICE_REF_NO
and GRD.INTERNAL_GRD_REF_NO = ASH.INTERNAL_GRD_REF_NO
and IAM.ASH_ID = ASH.ASH_ID
and ASH.ASH_ID = ASM.ASH_ID
and ASM.ASM_ID = PQCA.ASM_ID
and INRC.ELEMENT_ID = PQCA.ELEMENT_ID
and INRC.SUB_LOT_NO = ASM.SUB_LOT_NO
and PQCA.UNIT_OF_MEASURE = RM.RATIO_ID
and INVS.INTERNAL_CONTRACT_REF_NO = PCPCH.INTERNAL_CONTRACT_REF_NO
and PCPCH.PCPCH_ID = PCEPC.PCPCH_ID
and PCPCH.ELEMENT_ID = INRC.ELEMENT_ID
and PCEPC.ASSAY_DEDUCTION_UNIT_ID = rm_dec.RATIO_ID
and PQCA.PQCA_ID = PQCAPD.PQCA_ID
and INRC.RCHARGES_PRICE_UNIT_ID = PPU.INTERNAL_PRICE_UNIT_ID
and PPU.PRICE_UNIT_ID = PUM.PRICE_UNIT_ID
and INVS.INTERNAL_INVOICE_REF_NO = ?'
where
DGM.DOC_ID = 'CREATE_FI'
and DGM.DGM_ID='DGM-FIC-C3';

update DGM_DOCUMENT_GENERATION_MASTER dgm set DGM.FETCH_QUERY = 'INSERT INTO IS_CONC_RC_CHILD(
INTERNAL_INVOICE_REF_NO,
RC_AMOUNT,
ELEMENT_NAME,
ELEMENT_ID,
AMOUNT_UNIT,
SUB_LOT_NO,
GMR_REF_NO,
STOCK_REF_NO,
DRY_QUANTITY,
QUANTITY_UNIT_NAME,
ASSAY_CONTENT,
PAYABLE_CONTENT_PER,
DEDUCTION,
NET_PAYABLE_CONTENT,
NET_RC,
INTERNAL_DOC_REF_NO
)
select 
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
INRC.RCHARGES_AMOUNT as RC_AMOUNT,
AML.ATTRIBUTE_NAME as ELEMENT_NAME,
AML.ATTRIBUTE_ID as ELEMENT_ID,
CM.CUR_CODE as AMOUNT_UNIT,
INRC.SUB_LOT_NO as SUB_LOT_NO,
GMR.GMR_REF_NO as GMR_REF_NO,
GRD.INTERNAL_STOCK_REF_NO as STOCK_REF_NO,
INRC.LOT_QTY as DRY_QUANTITY,
QUM.QTY_UNIT as QUANTITY_UNIT_NAME,
PQCA.TYPICAL ||'' ''|| RM.RATIO_NAME as ASSAY_CONTENT,
PCEPC.PAYABLE_CONTENT_VALUE as PAYABLE_CONTENT_PER,
PCEPC.ASSAY_DEDUCTION ||'' '' || RM_DEC.RATIO_NAME as DEDUCTION,
PQCAPD.PAYABLE_PERCENTAGE||'' ''|| RM.RATIO_NAME as NET_PAYABLE_CONTENT,
INRC.RCHARGES_PRICE ||'' ''|| PUM.PRICE_UNIT_NAME as NET_RC,
?
from
IS_INVOICE_SUMMARY invs,
INRC_INV_REFINING_CHARGES inrc,
AML_ATTRIBUTE_MASTER_LIST aml,
CM_CURRENCY_MASTER cm,
PCM_PHYSICAL_CONTRACT_MAIN pcm,
GRD_GOODS_RECORD_DETAIL grd,
GMR_GOODS_MOVEMENT_RECORD gmr,
QUM_QUANTITY_UNIT_MASTER qum,
ASM_ASSAY_SUBLOT_MAPPING asm,
IAM_INVOICE_ASSAY_MAPPING iam,
ASH_ASSAY_HEADER ash,
PQCA_PQ_CHEMICAL_ATTRIBUTES pqca,
RM_RATIO_MASTER rm,
PCPCH_PC_PAYBLE_CONTENT_HEADER pcpch,
PCEPC_PC_ELEM_PAYABLE_CONTENT pcepc,
RM_RATIO_MASTER rm_dec,
PQCAPD_PRD_QLTY_CATTR_PAY_DTLS pqcapd,
PPU_PRODUCT_PRICE_UNITS ppu,
PUM_PRICE_UNIT_MASTER pum
where
INVS.INTERNAL_INVOICE_REF_NO = INRC.INTERNAL_INVOICE_REF_NO(+)
and INRC.ELEMENT_ID = AML.ATTRIBUTE_ID(+)
and PCM.INVOICE_CURRENCY_ID = CM.CUR_ID(+)
and INVS.INTERNAL_CONTRACT_REF_NO = PCM.INTERNAL_CONTRACT_REF_NO(+)
and INRC.GRD_ID = GRD.INTERNAL_GRD_REF_NO
and GRD.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO
and GRD.QTY_UNIT_ID = QUM.QTY_UNIT_ID 
and INVS.INTERNAL_INVOICE_REF_NO = IAM.INTERNAL_INVOICE_REF_NO
and GRD.INTERNAL_GRD_REF_NO = ASH.INTERNAL_GRD_REF_NO
and IAM.ASH_ID = ASH.ASH_ID
and ASH.ASH_ID = ASM.ASH_ID
and ASM.ASM_ID = PQCA.ASM_ID
and INRC.ELEMENT_ID = PQCA.ELEMENT_ID
and INRC.SUB_LOT_NO = ASM.SUB_LOT_NO
and PQCA.UNIT_OF_MEASURE = RM.RATIO_ID
and INVS.INTERNAL_CONTRACT_REF_NO = PCPCH.INTERNAL_CONTRACT_REF_NO
and PCPCH.PCPCH_ID = PCEPC.PCPCH_ID
and PCPCH.ELEMENT_ID = INRC.ELEMENT_ID
and PCEPC.ASSAY_DEDUCTION_UNIT_ID = rm_dec.RATIO_ID
and PQCA.PQCA_ID = PQCAPD.PQCA_ID
and INRC.RCHARGES_PRICE_UNIT_ID = PPU.INTERNAL_PRICE_UNIT_ID
and PPU.PRICE_UNIT_ID = PUM.PRICE_UNIT_ID
and INVS.INTERNAL_INVOICE_REF_NO = ?'
where
DGM.DOC_ID = 'CREATE_DFI'
and DGM.DGM_ID='DGM-DFIC-C3';

--FOR PENALTY CHARGES
update DGM_DOCUMENT_GENERATION_MASTER dgm set DGM.FETCH_QUERY = 'INSERT INTO IS_CONC_PENALTY_CHILD(
INTERNAL_INVOICE_REF_NO,
PENALTY_AMOUNT,
ELEMENT_NAME,
ELEMENT_ID,
AMOUNT_UNIT,
STOCK_REF_NO,
GMR_REF_NO,
DRY_QUANTITY,
ASSAY_CONTENT,
NET_PENALTY,
INTERNAL_DOC_REF_NO
)
select 
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
IEPD.ELEMENT_PENALTY_AMOUNT as PENALTY_AMOUNT,
AML.ATTRIBUTE_NAME as ELEMENT_NAME,
AML.ATTRIBUTE_ID as ELEMENT_ID,
CM.CUR_CODE as AMOUNT_UNIT,
GRD.INTERNAL_STOCK_REF_NO as STOCK_REF_NO,
GMR.GMR_REF_NO as GMR_REF_NO,
IEPD.ELEMENT_QTY ||'' '' || QUM.QTY_UNIT as DRY_QUANTITY,
PQCA.TYPICAL ||'' '' || RM.RATIO_NAME as ASSAY_CONTENT,
IEPD.ELEMENT_PENALTY_PRICE ||'' '' || PUM.PRICE_UNIT_NAME as NET_PENALTY,
?
from
IS_INVOICE_SUMMARY invs,
IEPD_INV_EPENALTY_DETAILS iepd,
AML_ATTRIBUTE_MASTER_LIST aml,
CM_CURRENCY_MASTER cm,
GRD_GOODS_RECORD_DETAIL grd,
GMR_GOODS_MOVEMENT_RECORD gmr,
QUM_QUANTITY_UNIT_MASTER qum,
ASH_ASSAY_HEADER ash,
IAM_INVOICE_ASSAY_MAPPING iam,
ASM_ASSAY_SUBLOT_MAPPING asm,
PQCA_PQ_CHEMICAL_ATTRIBUTES pqca,
RM_RATIO_MASTER rm,
PPU_PRODUCT_PRICE_UNITS ppu,
PUM_PRICE_UNIT_MASTER pum
where
INVS.INTERNAL_INVOICE_REF_NO = IEPD.INTERNAL_INVOICE_REF_NO(+)
and IEPD.ELEMENT_ID = AML.ATTRIBUTE_ID(+)
and INVS.INVOICE_CUR_ID = CM.CUR_ID
and IEPD.STOCK_ID = GRD.INTERNAL_GRD_REF_NO
and GRD.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO
and GRD.QTY_UNIT_ID = QUM.QTY_UNIT_ID
and INVS.INTERNAL_INVOICE_REF_NO = IAM.INTERNAL_INVOICE_REF_NO
and IAM.ASH_ID = ASH.ASH_ID
and ASH.ASH_ID = ASM.ASH_ID
and ASM.ASM_ID = PQCA.ASM_ID
and PQCA.ELEMENT_ID = IEPD.ELEMENT_ID
and PQCA.UNIT_OF_MEASURE = RM.RATIO_ID
and ASM.SUB_LOT_NO = IEPD.SUB_LOT_NO
and IEPD.ELEMENT_PRICE_UNIT_ID = PPU.INTERNAL_PRICE_UNIT_ID
and PPU.PRICE_UNIT_ID = PUM.PRICE_UNIT_ID
and INVS.INTERNAL_INVOICE_REF_NO = ?'
where
DGM.DOC_ID = 'CREATE_DFI'
and DGM.DGM_ID='DGM-DFIC-C4 ';

update DGM_DOCUMENT_GENERATION_MASTER dgm set DGM.FETCH_QUERY = 'INSERT INTO IS_CONC_PENALTY_CHILD(
INTERNAL_INVOICE_REF_NO,
PENALTY_AMOUNT,
ELEMENT_NAME,
ELEMENT_ID,
AMOUNT_UNIT,
STOCK_REF_NO,
GMR_REF_NO,
DRY_QUANTITY,
ASSAY_CONTENT,
NET_PENALTY,
INTERNAL_DOC_REF_NO
)
select 
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
IEPD.ELEMENT_PENALTY_AMOUNT as PENALTY_AMOUNT,
AML.ATTRIBUTE_NAME as ELEMENT_NAME,
AML.ATTRIBUTE_ID as ELEMENT_ID,
CM.CUR_CODE as AMOUNT_UNIT,
GRD.INTERNAL_STOCK_REF_NO as STOCK_REF_NO,
GMR.GMR_REF_NO as GMR_REF_NO,
IEPD.ELEMENT_QTY ||'' '' || QUM.QTY_UNIT as DRY_QUANTITY,
PQCA.TYPICAL ||'' '' || RM.RATIO_NAME as ASSAY_CONTENT,
IEPD.ELEMENT_PENALTY_PRICE ||'' '' || PUM.PRICE_UNIT_NAME as NET_PENALTY,
?
from
IS_INVOICE_SUMMARY invs,
IEPD_INV_EPENALTY_DETAILS iepd,
AML_ATTRIBUTE_MASTER_LIST aml,
CM_CURRENCY_MASTER cm,
GRD_GOODS_RECORD_DETAIL grd,
GMR_GOODS_MOVEMENT_RECORD gmr,
QUM_QUANTITY_UNIT_MASTER qum,
ASH_ASSAY_HEADER ash,
IAM_INVOICE_ASSAY_MAPPING iam,
ASM_ASSAY_SUBLOT_MAPPING asm,
PQCA_PQ_CHEMICAL_ATTRIBUTES pqca,
RM_RATIO_MASTER rm,
PPU_PRODUCT_PRICE_UNITS ppu,
PUM_PRICE_UNIT_MASTER pum
where
INVS.INTERNAL_INVOICE_REF_NO = IEPD.INTERNAL_INVOICE_REF_NO(+)
and IEPD.ELEMENT_ID = AML.ATTRIBUTE_ID(+)
and INVS.INVOICE_CUR_ID = CM.CUR_ID
and IEPD.STOCK_ID = GRD.INTERNAL_GRD_REF_NO
and GRD.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO
and GRD.QTY_UNIT_ID = QUM.QTY_UNIT_ID
and INVS.INTERNAL_INVOICE_REF_NO = IAM.INTERNAL_INVOICE_REF_NO
and IAM.ASH_ID = ASH.ASH_ID
and ASH.ASH_ID = ASM.ASH_ID
and ASM.ASM_ID = PQCA.ASM_ID
and PQCA.ELEMENT_ID = IEPD.ELEMENT_ID
and PQCA.UNIT_OF_MEASURE = RM.RATIO_ID
and ASM.SUB_LOT_NO = IEPD.SUB_LOT_NO
and IEPD.ELEMENT_PRICE_UNIT_ID = PPU.INTERNAL_PRICE_UNIT_ID
and PPU.PRICE_UNIT_ID = PUM.PRICE_UNIT_ID
and INVS.INTERNAL_INVOICE_REF_NO = ?'
where
DGM.DOC_ID = 'CREATE_FI'
and DGM.DGM_ID='DGM-FIC-C4 ';


update DGM_DOCUMENT_GENERATION_MASTER dgm set DGM.FETCH_QUERY = 'INSERT INTO IS_CONC_PENALTY_CHILD(
INTERNAL_INVOICE_REF_NO,
PENALTY_AMOUNT,
ELEMENT_NAME,
ELEMENT_ID,
AMOUNT_UNIT,
STOCK_REF_NO,
GMR_REF_NO,
DRY_QUANTITY,
ASSAY_CONTENT,
NET_PENALTY,
INTERNAL_DOC_REF_NO
)
select 
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
IEPD.ELEMENT_PENALTY_AMOUNT as PENALTY_AMOUNT,
AML.ATTRIBUTE_NAME as ELEMENT_NAME,
AML.ATTRIBUTE_ID as ELEMENT_ID,
CM.CUR_CODE as AMOUNT_UNIT,
GRD.INTERNAL_STOCK_REF_NO as STOCK_REF_NO,
GMR.GMR_REF_NO as GMR_REF_NO,
IEPD.ELEMENT_QTY ||'' '' || QUM.QTY_UNIT as DRY_QUANTITY,
PQCA.TYPICAL ||'' '' || RM.RATIO_NAME as ASSAY_CONTENT,
IEPD.ELEMENT_PENALTY_PRICE ||'' '' || PUM.PRICE_UNIT_NAME as NET_PENALTY,
?
from
IS_INVOICE_SUMMARY invs,
IEPD_INV_EPENALTY_DETAILS iepd,
AML_ATTRIBUTE_MASTER_LIST aml,
CM_CURRENCY_MASTER cm,
GRD_GOODS_RECORD_DETAIL grd,
GMR_GOODS_MOVEMENT_RECORD gmr,
QUM_QUANTITY_UNIT_MASTER qum,
ASH_ASSAY_HEADER ash,
IAM_INVOICE_ASSAY_MAPPING iam,
ASM_ASSAY_SUBLOT_MAPPING asm,
PQCA_PQ_CHEMICAL_ATTRIBUTES pqca,
RM_RATIO_MASTER rm,
PPU_PRODUCT_PRICE_UNITS ppu,
PUM_PRICE_UNIT_MASTER pum
where
INVS.INTERNAL_INVOICE_REF_NO = IEPD.INTERNAL_INVOICE_REF_NO(+)
and IEPD.ELEMENT_ID = AML.ATTRIBUTE_ID(+)
and INVS.INVOICE_CUR_ID = CM.CUR_ID
and IEPD.STOCK_ID = GRD.INTERNAL_GRD_REF_NO
and GRD.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO
and GRD.QTY_UNIT_ID = QUM.QTY_UNIT_ID
and INVS.INTERNAL_INVOICE_REF_NO = IAM.INTERNAL_INVOICE_REF_NO
and IAM.ASH_ID = ASH.ASH_ID
and ASH.ASH_ID = ASM.ASH_ID
and ASM.ASM_ID = PQCA.ASM_ID
and PQCA.ELEMENT_ID = IEPD.ELEMENT_ID
and PQCA.UNIT_OF_MEASURE = RM.RATIO_ID
and ASM.SUB_LOT_NO = IEPD.SUB_LOT_NO
and IEPD.ELEMENT_PRICE_UNIT_ID = PPU.INTERNAL_PRICE_UNIT_ID
and PPU.PRICE_UNIT_ID = PUM.PRICE_UNIT_ID
and INVS.INTERNAL_INVOICE_REF_NO = ?'
where
DGM.DOC_ID = 'CREATE_PI'
and DGM.DGM_ID='DGM-PIC-C4 ';