
--- LOCI
DECLARE
   fetchqry1   CLOB
      := '[{"dataIndex":"","fixed":true,"header":"<div class=\"x-grid3-hd-checker\">&#160;</div>","hideable":false,"id":"checker","sortable":false,"width":20},
            {"dataIndex":"contractNo","header":"Contract Ref. No","id":1,"sortable":true,"width":150},
            {"dataIndex":"contractType","header":"Contract Type","id":2,"sortable":true,"width":150},
            {"dataIndex":"counterParty","header":"CP Name","id":3,"sortable":true,"width":150},
            {"dataIndex":"partnershipType","header":"Execution Type","id":4,"sortable":true,"width":150},
            {"dataIndex":"tradeType","header":"Product Group Type","id":5,"sortable":true,"width":150},
            {"dataIndex":"itemStatus","header":"Item Status","id":6,"sortable":true,"width":150},
            {"dataIndex":"deliveryRefNo","header":"Delivery Ref. No.","id":7,"sortable":true,"width":150},
            {"dataIndex":"itemRefNo","header":"Item Ref. No.","id":8,"sortable":true,"width":150},
            {"dataIndex":"product","header":"Product","id":9,"sortable":true,"width":150},
            {"dataIndex":"quality","header":"Quality","id":10,"sortable":true,"width":150},
            {"dataIndex":"issueDate","header":"Issue Date","id":11,"sortable":true,"width":150},
            {"dataIndex":"quotaMonth","header":"Quota Period","id":12,"sortable":true,"width":150},
            {"dataIndex":"location","header":"Location","id":13,"sortable":true,"width":150},
            {"dataIndex":"traxysOrg","header":"Org","id":14,"sortable":true,"width":150},
            {"dataIndex":"incotermLocation","header":"INCO Term & Location","id":15,"sortable":true,"width":150},
            {"dataIndex":"qty","header":"Item Quantity","id":16,"sortable":true,"width":150},
            {"dataIndex":"openQty","header":"Open Qty.","id":17,"sortable":true,"width":150},
            {"dataIndex":"allocatedQty","header":"Allocated Qty.","id":18,"sortable":true,"width":150},
            {"dataIndex":"incoterm","header":"Incoterm","id":19,"sortable":true,"width":150},
            {"dataIndex":"strategy","header":"Strategy","id":20,"sortable":true,"width":150},
            {"dataIndex":"bookProfitCenter","header":"Book/Profit Center","id":21,"sortable":true,"width":150},
            {"dataIndex":"trader","header":"Trader","id":22,"sortable":true,"width":150},
            {"dataIndex":"pricing","header":"Pricing","id":23,"sortable":true,"width":150},
            {"dataIndex":"executedQty","header":"Executed Quantity","id":24,"sortable":true,"width":150},
            {"dataIndex":"titleTransferQty","header":"Title Transfer Quantity","id":25,"sortable":true,"width":150},
            {"dataIndex":"provInvoicedQty","header":"Prov. Invoiced Quantity","id":26,"sortable":true,"width":150},
            {"dataIndex":"finalInvoicedQty","header":"Final Invoiced Quantity","id":27,"sortable":true,"width":150},
            {"dataIndex":"payInCurrency","header":"Pay-In Currency","id":28,"sortable":true,"width":150},
            {"dataIndex":"payableContent","header":"Payable Content","id":29,"sortable":true,"width":150},
            {"dataIndex":"origin","header":"Origin","id":30,"sortable":true,"width":150},
            {"dataIndex":"dealType","header":"Deal Type","id":30,"sortable":true,"width":150},
            {"dataIndex":"fullfillmentQty","header":"Fulfilled Quantity","id":30,"sortable":true,"width":150}
            ]';
   fetchqry2   CLOB
      := '[ 
                                {name: "contractNo", mapping: "contractNo"}, 
                                {name: "contractType", mapping: "contractType"}, 
                                {name: "counterParty", mapping: "counterParty"},
                                {name: "tradeType", mapping: "tradeType"},
                                {name: "allocationStatus", mapping: "allocationStatus"},
                                {name: "itemStatus", mapping: "itemStatus"},
                                {name: "deliveryRefNo", mapping: "deliveryRefNo"},
                                {name: "itemRefNo", mapping: "itemRefNo"},
                                {name: "internalContractItemRefNo", mapping: "internalContractItemRefNo"},
                                {name: "internalContractRefNo", mapping: "internalContractRefNo"},
                                {name: "product", mapping: "product"},
                                {name: "quality", mapping: "quality"},
                                {name: "attributes", mapping: "attributes"},
                                {name: "issueDate", mapping: "issueDate"},
                                {name: "quotaMonth", mapping: "quotaMonth"},
                                {name: "location", mapping: "location"},
                                {name: "traxysOrg", mapping: "traxysOrg"},
                                {name: "incotermLocation", mapping: "incotermLocation"},
                                {name: "pricing", mapping: "pricing"},
                                {name: "qp", mapping: "qp"},
                                {name: "qty", mapping: "qty"},
                                {name: "openQty", mapping: "openQty"},
                                {name: "qtyBasis", mapping: "qtyBasis"},
                                {name: "allocatedQty", mapping: "allocatedQty"},
                                {name: "partnershipType", mapping: "partnershipType"},
                                {name: "incoterm", mapping: "incoterm"},
                                {name: "pcdiId", mapping: "pcdiId"},
                                {name: "strategy", mapping: "strategy"},
                                {name: "bookProfitCenter", mapping: "bookProfitCenter"},
                                {name: "trader", mapping: "trader"},
                                {name: "pricing", mapping: "pricing"},
                                {name: "executedQty", mapping: "executedQty"},
                                {name: "titleTransferQty", mapping: "titleTransferQty"},
                                {name: "provInvoicedQty", mapping: "provInvoicedQty"},
                                {name: "finalInvoicedQty", mapping: "finalInvoicedQty"},
                                {name: "payInCurrency", mapping: "payInCurrency"},
                                {name: "payableContent", mapping: "payableContent"},
                                {name: "origin", mapping: "origin"},
                                {name: "dealType", mapping: "dealType"},
                                {name: "fullfillmentQty", mapping: "fullfillmentQty"}
                               ]';
BEGIN
   UPDATE gm_grid_master gm
      SET gm.default_column_model_state = fetchqry1,
          gm.default_record_model_state = fetchqry2
    WHERE gm.grid_id = 'LOCI';
END;

---- LODI
DECLARE
   fetchqry1   CLOB
      := '[{"dataIndex":"","fixed":true,"header":"<div class=\"x-grid3-hd-checker\">&#160;</div>","hideable":false,"id":"checker","sortable":false,"width":20},
                                        {"dataIndex":"contractRefNo","header":"Contract No.","id":1,"sortable":true,"width":150},
                                        {"dataIndex":"contractType","header":"Contract Type","id":2,"sortable":true,"width":150},
                                        {"dataIndex":"cpName","header":"CP Name","id":3,"sortable":true,"width":150},
                                        {"dataIndex":"tradeType","header":"Execution Type","id":4,"sortable":true,"width":150},
                                        {"dataIndex":"deliveryItemRefNo","header":"Delivery Ref. No.","id":5,"sortable":true,"width":150},
                                        {"dataIndex":"assetclass","header":"Product","id":6,"sortable":true,"width":150},
                                        {"dataIndex":"qualityName","header":"Quality","id":7,"sortable":true,"width":150},
                                        {"dataIndex":"attributes","header":"Attributes","id":8,"sortable":true,"width":150},
                                        {"dataIndex":"issueDate","header":"Issue Date","id":9,"sortable":true,"width":150},
                                        {"dataIndex":"quotaMonth","header":"Quota Period","id":10,"sortable":true,"width":150},
                                        {"dataIndex":"location","header":"Location","id":11,"sortable":true,"width":150},
                                        {"dataIndex":"traxysOrg","header":"Org","id":12,"sortable":true,"width":150},
                                        {"dataIndex":"incotermLocation","header":"Incoterm & Location","id":13,"sortable":true,"width":150},
                                        {"dataIndex":"quotaQty","header":"Quota Quantity(Min)","id":14,"sortable":true,"width":150},
                                        {"dataIndex":"quotaQtyUnit","header":"Quota Qty. Unit","id":15,"sortable":true,"width":150},
                                        {"dataIndex":"quotaOpenQty","header":"Quota Open Qty.","id":16,"sortable":true,"width":150},
                                        {"dataIndex":"allocatedQty","header":"Allocated Qty.","id":17,"sortable":true,"width":150},
                                        {"dataIndex":"strategy","header":"Strategy","id":18,"sortable":true,"width":150},
                                        {"dataIndex":"bookProfitCenter","header":"Book/Profit Center","id":19,"sortable":true,"width":150},
                                        {"dataIndex":"trader","header":"Trader","id":20,"sortable":true,"width":150},
                                        {"dataIndex":"qpPricingBasis","header":"QP-Pricing Basis","id":21,"sortable":true,"width":150},
                                        {"dataIndex":"qpPricing","header":"QP-Pricing","id":22,"sortable":true,"width":150},
                                        {"dataIndex":"pricing","header":"Pricing","id":23,"sortable":true,"width":150},
                                        {"dataIndex":"quotaQuantityMax","header":"Quota Quantity(Max)","id":24,"sortable":true,"width":150},
                                        {"dataIndex":"quotaQuantityBasis","header":"Quota Quantity Basis","id":25,"sortable":true,"width":150},
                                        {"dataIndex":"toBeCalledOffQty","header":"To be called Off Quantity","id":26,"sortable":true,"width":150},
                                        {"dataIndex":"calledOffQty","header":"Called Off Quantity","id":27,"sortable":true,"width":150},
                                        {"dataIndex":"executedQty","header":"Executed Quantity","id":28,"sortable":true,"width":150},
                                        {"dataIndex":"pricingStatus","header":"Pricing Status","id":29,"sortable":true,"width":150},
                                        {"dataIndex":"fixedPriceQty","header":"Fixed Price Quantity","id":30,"sortable":true,"width":150},
                                        {"dataIndex":"titleTransferQty","header":"Title Transfer Quantity","id":31,"sortable":true,"width":150},
                                        {"dataIndex":"provInvoicedQty","header":"Prov. Invoiced Quantity","id":32,"sortable":true,"width":150},
                                        {"dataIndex":"finalInvoicedQty","header":"Final Invoiced Quantity","id":33,"sortable":true,"width":150},
                                        {"dataIndex":"payInCurrency","header":"Pay-In Currency","id":34,"sortable":true,"width":150},
                                        {"dataIndex":"fullfillmentStatus","header":"Fullfillment Status","id":35,"sortable":true,"width":150},
                                        {"dataIndex":"paymentDueDate","header":"Payment Due Date","id":36,"sortable":true,"width":150},
                                        {"dataIndex":"qpDeclarationDate","header":"QP Declaration Date","id":37,"sortable":true,"width":150},
                                        {"dataIndex":"qtyDeclarationDate","header":"Qty. Declaration Date","id":38,"sortable":true,"width":150},
                                        {"dataIndex":"qualityDeclarationDate","header":"Quality Declaration Date","id":39,"sortable":true,"width":150},
                                        {"dataIndex":"incoLocationDeclarationDate","header":"INCO Location Declaration Date","id":40,"sortable":true,"width":150},
                                        {"dataIndex":"dealType","header":"Deal Type","id":39,"sortable":true,"width":150},
                                        {"dataIndex":"fullfillmentQty","header":"Fulfilled Quantity","id":39,"sortable":true,"width":150}]';
   fetchqry2   CLOB
      := '[{header: "Contract No.", width: 150, sortable: true, dataIndex: "contractRefNo"},
                                  {header: "Contract Type", width: 150, sortable: true, dataIndex: "contractType"},
                                  {header: "Counter Party", width: 150, sortable: true, dataIndex: "cpName"},
                                  {header: "Trade Type", width: 150, sortable: true, dataIndex: "tradeType"},
                                  {header: "Item Status", width: 150, sortable: true, dataIndex: "itemStatus"},
                                  {header: "Delivery Ref. No.", width: 150, sortable: true,renderer:deliveryItemOrderStatus, dataIndex: "deliveryItemRefNo"},
                                  {header: "Product", width: 150, sortable: true, dataIndex: "assetclass"},
                                  {header: "Quality", width: 150, sortable: true, dataIndex: "qualityName"},
                                  {header: "Attributes", width: 150, sortable: true, dataIndex: "attributes"},
                                  {header: "Issue Date", width: 150, sortable: true, dataIndex: "issueDate"},
                                  {header: "Quota Month", width: 150, sortable: true, dataIndex: "quotaMonth"},
                                  {header: "Location", width: 150, sortable: true, dataIndex: "location"},
                                  {header: "Traxys Org", width: 150, sortable: true, dataIndex: "traxysOrg"},
                                  {header: "Incoterm & Location", width: 150, sortable: true, dataIndex: "incotermLocation"},
                                  {header: "Pricing", width: 150, sortable: true, dataIndex: "pricing"},
                                  {header: "QP", width: 150, sortable: true, dataIndex: "qp"},
                                  {header: "Quota Qty.", width: 150, sortable: true, dataIndex: "quotaQty"},
                                  {header: "Quota Qty. Unit", width: 150, sortable: true, dataIndex: "quotaQtyUnit"},
                                  {header: "Quota Qty Basis", width: 150, sortable: true, dataIndex: "quotaQtyBasis"},
                                  {header: "Quota Open Qty.", width: 150, sortable: true, dataIndex: "quotaOpenQty"},
                                  {header: "Quota Call-off Qty.", width: 150, sortable: true, dataIndex: "quotaCalloffQty"},
                                  {header: "Quota Delivered/Received Qty.", width: 150, sortable: true, dataIndex: "quotaDeliveredReceivedQty"},
                                  {header: "Quota Invoiced Qty.", width: 150, sortable: true, dataIndex: "quotaInvoicedQty"},
                                  {header: "Quota Price Fixed Qty.", width: 150, sortable: true, dataIndex: "quotaPriceFixedQty"},
                                  {header: "Allocated Qty.", width: 150, sortable: true, dataIndex: "allocatedQty"},
                                  {header: "Payment Due Date", width: 150, sortable: true, dataIndex: "paymentDueDate"},
                                  {header: "QP Declaration Date", width: 150, sortable: true, dataIndex: "qpDeclarationDate"},
                                  {header: "Qty. Declaration Date", width: 150, sortable: true, dataIndex: "qtyDeclarationDate"},
                                  {header: "Quality Declaration Date", width: 150, sortable: true, dataIndex: "qualityDeclarationDate"},
                                  {header: "INCO Location Declaration Date", width: 150, sortable: true, dataIndex: "incoLocationDeclarationDate"},
                                  {header: "Deal Type", width: 150, sortable: true, dataIndex: "dealType"},
                                  {header: "Fulfilled Quantity", width: 150, sortable: true, dataIndex: "fullfillmentQty"}]';
BEGIN
   UPDATE gm_grid_master gm
      SET gm.default_column_model_state = fetchqry1,
          gm.default_record_model_state = fetchqry2
    WHERE gm.grid_id = 'LODI';
END;

---LOC
DECLARE
   fetchqry1   CLOB
      := '[{"dataIndex":"","fixed":true,"header":"<div class=\"x-grid3-hd-checker\">&#160;</div>","hideable":false,"id":"checker","sortable":false,"width":20},
                                {"dataIndex":"contractRefNo","header":"Contract Ref No.","id":1,"sortable":true,"width":150},
                                {"dataIndex":"issueDate","header":"Issue Date","id":2,"sortable":true,"width":150},
                                {"dataIndex":"cpName","header":"CP Name","id":3,"sortable":true,"width":150},
                                {"dataIndex":"contractType","header":"Contract Type","id":4,"sortable":true,"width":150},
                                {"dataIndex":"intracompany","header":"Intra Company","id":5,"sortable":true,"width":150},
                                {"dataIndex":"assetclass","header":"Product ","id":6,"sortable":true,"width":150},
                                {"dataIndex":"productGroupType","header":"Product Type ","id":7,"sortable":true,"width":150},
                                {"dataIndex":"noOfItems","header":"No. Of. Delivery Items","id":8,"sortable":true,"width":150},
                                {"dataIndex":"contractqty","header":"Contract Quanity","id":9,"sortable":true,"width":150},
                                {"dataIndex":"partnershipType","header":"Execution Type","id":10,"sortable":true,"width":150},
                                {"dataIndex":"jvcpname","header":"JV Party","id":11,"sortable":true,"width":150},
                                {"dataIndex":"contractStatus","header":"Contract Status","id":12,"sortable":true,"width":150},
                                {"dataIndex":"org","header":"Org.","id":13,"sortable":true,"width":150},
                                {"dataIndex":"strategy","header":"Strategy","id":14,"sortable":true,"width":150},
                                {"dataIndex":"trader","header":"Trader","id":15,"sortable":true,"width":150},
                                {"dataIndex":"executedQty","header":"Executed Quantity","id":16,"sortable":true,"width":150},
                                {"dataIndex":"allocatedQty","header":"Allocated Quantity","id":17,"sortable":true,"width":150},
                                {"dataIndex":"titleTransferQty","header":"Title Transfer Quantity","id":18,"sortable":true,"width":150},
                                {"dataIndex":"provInvoiceQty","header":"Prov. Invoice Quantity","id":19,"sortable":true,"width":150},
                                {"dataIndex":"finalInvoiceQty","header":"Final Invoice Quantity","id":20,"sortable":true,"width":150},
                                {"dataIndex":"payInCurrency","header":"Pay-In Currency","id":21,"sortable":true,"width":150},
                                {"dataIndex":"dealType","header":"Deal Type","id":21,"sortable":true,"width":150},
                                {"dataIndex":"fullfillmentQty","header":"Fulfilled Quantity","id":21,"sortable":true,"width":150}]';
   fetchqry2   CLOB
      := '[{header: "Contract Ref No.", width: 150, sortable: true,renderer:contractOrderStatus, dataIndex: "contractRefNo"},
                                 {header: "Issue Date", width: 150, sortable: true, dataIndex: "issueDate"},
                                 {header: "CP Name", width: 150, sortable: true, dataIndex: "cpName"},
                                 {header: "Contract Type", width: 150, sortable: true, dataIndex: "contractType"},
                                 {header: "Intra Company", width: 150, sortable: true, dataIndex: "intracompany"},
                                 {header: "Product ", width: 150, sortable: true, dataIndex: "assetclass"},
                                 {header: "Product Type ", width: 150, sortable: true, dataIndex: "productGroupType"},
                                 {header: "No. Of. Delivery Items", width: 150, sortable: true, dataIndex: "noOfItems"},
                                 {header: "Contract Quanity", width: 150, sortable: true, dataIndex: "contractqty"},
                                 {header: "Partnership Type", width: 150, sortable: true, dataIndex: "partnershipType"},
                                 {header: "JV Party", width: 150, sortable: true, dataIndex: "jvcpname"},
                                 {header: "Contract Status", width: 150, sortable: true, dataIndex: "contractStatus"},
                                 {header: "Org.", width: 150, sortable: true, dataIndex: "org"},
                                 {header: "Strategy", width: 150, sortable: true, dataIndex: "trader"},
                                 {header: "Trader", width: 150, sortable: true, dataIndex: "contractStatus"},
                                 {header: "Executed Quantity", width: 150, sortable: true, dataIndex: "executedQty"},
                                 {header: "Allocated Quantity", width: 150, sortable: true, dataIndex: "allocatedQty"},
                                 {header: "Title Transfer Quantity", width: 150, sortable: true, dataIndex: "titleTransferQty"},
                                 {header: "Prov. Invoice Quantity", width: 150, sortable: true, dataIndex: "provInvoiceQty"},
                                 {header: "Final Invoice Quantity", width: 150, sortable: true, dataIndex: "finalInvoiceQty"},
                                 {header: "Executed Quantity", width: 150, sortable: true, dataIndex: "executedQty"},
                                 {header: "Pay-In Currency", width: 150, sortable: true, dataIndex: "payInCurrency"},
                                 {header: "Allocated Quantity", width: 150, sortable: true, dataIndex: "allocatedQty"},
                                 {header: "Deal Type", width: 150, sortable: true, dataIndex: "dealType"},
                                 {header: "Fulfilled Quantity", width: 150, sortable: true, dataIndex: "fullfillmentQty"}]';
BEGIN
   UPDATE gm_grid_master gm
      SET gm.default_column_model_state = fetchqry1,
          gm.default_record_model_state = fetchqry2
    WHERE gm.grid_id = 'PHY_LOC';
END;