update DGM_DOCUMENT_GENERATION_MASTER dgm set DGM.FETCH_QUERY = 'INSERT INTO IS_CONC_TC_CHILD (
INTERNAL_INVOICE_REF_NO,
TC_AMOUNT,
ELEMENT_NAME,
ELEMENT_ID,
AMOUNT_UNIT,
SUB_LOT_NO,
INTERNAL_DOC_REF_NO
)
select 
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
INTC.TCHARGES_AMOUNT as TC_AMOUNT,
AML.ATTRIBUTE_NAME as ELEMENT_NAME,
AML.ATTRIBUTE_ID as ELEMENT_ID,
CM.CUR_CODE as AMOUNT_UNIT,
INTC.SUB_LOT_NO as SUB_LOT_NO,
?
from
IS_INVOICE_SUMMARY invs,
INTC_INV_TREATMENT_CHARGES intc,
AML_ATTRIBUTE_MASTER_LIST aml,
CM_CURRENCY_MASTER cm,
PCM_PHYSICAL_CONTRACT_MAIN pcm
where
INVS.INTERNAL_INVOICE_REF_NO = INTC.INTERNAL_INVOICE_REF_NO(+)
and INTC.ELEMENT_ID = AML.ATTRIBUTE_ID(+)
and PCM.INVOICE_CURRENCY_ID = CM.CUR_ID(+)
and INVS.INTERNAL_CONTRACT_REF_NO = PCM.INTERNAL_CONTRACT_REF_NO(+)
and INVS.INTERNAL_INVOICE_REF_NO = ?'
where
DGM.DOC_ID = 'CREATE_PI'
and DGM.DGM_ID='DGM-PIC-C2';


update DGM_DOCUMENT_GENERATION_MASTER dgm set DGM.FETCH_QUERY = 'INSERT INTO IS_CONC_TC_CHILD (
INTERNAL_INVOICE_REF_NO,
TC_AMOUNT,
ELEMENT_NAME,
ELEMENT_ID,
AMOUNT_UNIT,
SUB_LOT_NO,
INTERNAL_DOC_REF_NO
)
select 
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
INTC.TCHARGES_AMOUNT as TC_AMOUNT,
AML.ATTRIBUTE_NAME as ELEMENT_NAME,
AML.ATTRIBUTE_ID as ELEMENT_ID,
CM.CUR_CODE as AMOUNT_UNIT,
INTC.SUB_LOT_NO as SUB_LOT_NO,
?
from
IS_INVOICE_SUMMARY invs,
INTC_INV_TREATMENT_CHARGES intc,
AML_ATTRIBUTE_MASTER_LIST aml,
CM_CURRENCY_MASTER cm,
PCM_PHYSICAL_CONTRACT_MAIN pcm
where
INVS.INTERNAL_INVOICE_REF_NO = INTC.INTERNAL_INVOICE_REF_NO(+)
and INTC.ELEMENT_ID = AML.ATTRIBUTE_ID(+)
and PCM.INVOICE_CURRENCY_ID = CM.CUR_ID(+)
and INVS.INTERNAL_CONTRACT_REF_NO = PCM.INTERNAL_CONTRACT_REF_NO(+)
and INVS.INTERNAL_INVOICE_REF_NO = ?'
where
DGM.DOC_ID = 'CREATE_FI'
and DGM.DGM_ID='DGM-FIC-C2';


update DGM_DOCUMENT_GENERATION_MASTER dgm set DGM.FETCH_QUERY = 'INSERT INTO IS_CONC_RC_CHILD (
INTERNAL_INVOICE_REF_NO,
RC_AMOUNT,
ELEMENT_NAME,
ELEMENT_ID,
AMOUNT_UNIT,
SUB_LOT_NO,
INTERNAL_DOC_REF_NO
)
select 
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
INRC.RCHARGES_AMOUNT as RC_AMOUNT,
AML.ATTRIBUTE_NAME as ELEMENT_NAME,
AML.ATTRIBUTE_ID as ELEMENT_ID,
CM.CUR_CODE as AMOUNT_UNIT,
INRC.SUB_LOT_NO as SUB_LOT_NO,
?
from
IS_INVOICE_SUMMARY invs,
INRC_INV_REFINING_CHARGES inrc,
AML_ATTRIBUTE_MASTER_LIST aml,
CM_CURRENCY_MASTER cm,
PCM_PHYSICAL_CONTRACT_MAIN pcm
where
INVS.INTERNAL_INVOICE_REF_NO = INRC.INTERNAL_INVOICE_REF_NO(+)
and INRC.ELEMENT_ID = AML.ATTRIBUTE_ID(+)
and PCM.INVOICE_CURRENCY_ID = CM.CUR_ID(+)
and INVS.INTERNAL_CONTRACT_REF_NO = PCM.INTERNAL_CONTRACT_REF_NO(+)
and INVS.INTERNAL_INVOICE_REF_NO = ?'
where
DGM.DOC_ID = 'CREATE_FI'
and DGM.DGM_ID='DGM-FIC-C3';


update DGM_DOCUMENT_GENERATION_MASTER dgm set DGM.FETCH_QUERY = 'INSERT INTO IS_CONC_RC_CHILD (
INTERNAL_INVOICE_REF_NO,
RC_AMOUNT,
ELEMENT_NAME,
ELEMENT_ID,
AMOUNT_UNIT,
SUB_LOT_NO,
INTERNAL_DOC_REF_NO
)
select 
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
INRC.RCHARGES_AMOUNT as RC_AMOUNT,
AML.ATTRIBUTE_NAME as ELEMENT_NAME,
AML.ATTRIBUTE_ID as ELEMENT_ID,
CM.CUR_CODE as AMOUNT_UNIT,
INRC.SUB_LOT_NO as SUB_LOT_NO,
?
from
IS_INVOICE_SUMMARY invs,
INRC_INV_REFINING_CHARGES inrc,
AML_ATTRIBUTE_MASTER_LIST aml,
CM_CURRENCY_MASTER cm,
PCM_PHYSICAL_CONTRACT_MAIN pcm
where
INVS.INTERNAL_INVOICE_REF_NO = INRC.INTERNAL_INVOICE_REF_NO(+)
and INRC.ELEMENT_ID = AML.ATTRIBUTE_ID(+)
and PCM.INVOICE_CURRENCY_ID = CM.CUR_ID(+)
and INVS.INTERNAL_CONTRACT_REF_NO = PCM.INTERNAL_CONTRACT_REF_NO(+)
and INVS.INTERNAL_INVOICE_REF_NO = ?'
where
DGM.DOC_ID = 'CREATE_PI'
and DGM.DGM_ID='DGM-PIC-C3';
