declare 
fetchQueryISChildForSI CLOB :=
'INSERT INTO IS_CHILD_SI_D(
INTERNAL_INVOICE_REF_NO,
GMR_REF_NO,
COST_COMPONENT_NAME,
INVOICE_AMOUNT,
INVOICE_AMOUNT_UNIT,
INV_AMT_IN_INV_CUR,
INVOICE_CURRENCY,
INV_TO_ACCRUAL_FX_RATE,
INTERNAL_DOC_REF_NO
)
select
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
GMR.GMR_REF_NO as GMR_REF_NO,
SCM.COST_COMPONENT_NAME as COST_COMPONENT_NAME,
CS.TRANSACTION_AMT as INVOICE_AMOUNT,
CM1.CUR_CODE as INVOICE_AMOUNT_UNIT,
CS.INV_AMT_IN_INV_CUR as INV_AMT_IN_INV_CUR,
CM2.CUR_CODE as INVOICE_CURRENCY,
CS.INV_TO_ACCRUAL_CURR_FX as INV_TO_ACCRUAL_FX_RATE,?
from
IS_INVOICE_SUMMARY invs,
IAM_INVOICE_ACTION_MAPPING iam,
CS_COST_STORE cs,
CIGC_CONTRACT_ITEM_GMR_COST cigc,
GMR_GOODS_MOVEMENT_RECORD gmr,
SCM_SERVICE_CHARGE_MASTER scm,
CM_CURRENCY_MASTER cm1,
CM_CURRENCY_MASTER cm2
where
INVS.INTERNAL_INVOICE_REF_NO = IAM.INTERNAL_INVOICE_REF_NO
and IAM.INVOICE_ACTION_REF_NO = CS.INTERNAL_ACTION_REF_NO
and CS.COG_REF_NO = CIGC.COG_REF_NO
and CIGC.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO
and CS.COST_COMPONENT_ID = SCM.COST_ID
and CM1.CUR_ID(+) = CS.TRANSACTION_AMT_CUR_ID
AND CM2.CUR_ID(+) =  CS.INVOICE_CURRENCY
and INVS.INVOICE_TYPE = ''Service''
and INVS.INTERNAL_INVOICE_REF_NO = ?';

begin
    UPDATE DGM_DOCUMENT_GENERATION_MASTER dgm set DGM.FETCH_QUERY = fetchQueryISChildForSI where DGM.DOC_ID IN ('CREATE_SI') and DGM.DGM_ID IN ('DGM-SI-1','DGM-SIC-1') and DGM.SEQUENCE_ORDER = 2 and DGM.IS_CONCENTRATE IN ('Y','N');
commit;
end;