
Insert into GMC_GRID_MENU_CONFIGURATION
   (MENU_ID, GRID_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, 
    FEATURE_ID, LINK_CALLED, ICON_CLASS, MENU_PARENT_ID, ACL_ID)
 Values
   ('MIN_1_7', 'MIN_LOC', 'Mark As Closed', 7, 2, 
    'APP-PFL-N-220', 'function(){markAsClosed();}', NULL, 'MIN_1', 'APP-ACL-N1379');


Insert into GMC_GRID_MENU_CONFIGURATION
   (MENU_ID, GRID_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, 
    FEATURE_ID, LINK_CALLED, ICON_CLASS, MENU_PARENT_ID, ACL_ID)
 Values
   ('LOC_1_9', 'PHY_LOC', 'Mark As Closed', 13, 2, 
    'APP-PFL-N-191', 'function(){markAsClosed();}', NULL, 'LOC_1', 'APP-ACL-N1131');
  

Insert into AXM_ACTION_MASTER
   (ACTION_ID, ENTITY_ID, ACTION_NAME, IS_NEW_GMR_APPLICABLE, ACTION_DESC, 
    IS_GENERATE_DOC_APPLICABLE, IS_REF_NO_GEN_APPLICABLE, IS_EVENT_PUBLISH_APPLICABLE, IS_CONTINUOUS_MIDDLE_NO_REQ, IS_REQUIRED_FOR_EODEOM, 
    IS_ACTIVITY_LOG_APPLICABLE, IS_RECENT_RECORD_APPLICABLE, NAVIGATION_URL, SEQ_NAME)
 Values
   ('CLOSE_CONTRACT', 'Contract', 'Close Contract', 'N', 'Contract closed', 
    'N', NULL, 'N', 'N', 'Y', 
    'Y', 'Y', NULL, 'GEN_AXM_SEQ');
    
Insert into AKM_ACTION_REF_KEY_MASTER
   (ACTION_KEY_ID, ACTION_KEY_DESC, VALIDATION_QUERY)
 Values
   ('CloseContract', 'CC Ref No', 'SELECT COUNT(*) FROM   AXS_ACTION_SUMMARY axs WHERE  axs.action_ref_no = :pc_action_ref_no AND    axs.corporate_id = :pc_corporate_id');

Insert into AXM_ACTION_MASTER
   (ACTION_ID, ENTITY_ID, ACTION_NAME, IS_NEW_GMR_APPLICABLE, ACTION_DESC, 
    IS_GENERATE_DOC_APPLICABLE, IS_REF_NO_GEN_APPLICABLE, IS_EVENT_PUBLISH_APPLICABLE, IS_CONTINUOUS_MIDDLE_NO_REQ, IS_REQUIRED_FOR_EODEOM, 
    IS_ACTIVITY_LOG_APPLICABLE, IS_RECENT_RECORD_APPLICABLE, NAVIGATION_URL, SEQ_NAME)
 Values
   ('CLOSE_TOLLING_CONTRACT', 'Contract', 'Close Tolling Contract', 'N', 'Tolling Contract closed', 
    'N', NULL, 'N', 'N', 'Y', 
    'Y', 'Y', NULL, 'GEN_AXM_SEQ');
    
    Insert into AKM_ACTION_REF_KEY_MASTER
   (ACTION_KEY_ID, ACTION_KEY_DESC, VALIDATION_QUERY)
 Values
   ('CloseTC', 'CTC Ref No', 'SELECT COUNT(*) FROM   AXS_ACTION_SUMMARY axs WHERE  axs.action_ref_no = :pc_action_ref_no AND    axs.corporate_id = :pc_corporate_id');