Insert into GMC_GRID_MENU_CONFIGURATION
   (MENU_ID, GRID_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, 
    FEATURE_ID, LINK_CALLED, ICON_CLASS, MENU_PARENT_ID, ACL_ID)
 Values
   ('113', 'LOG', 'GMR Details', 12, 2, 
    'APP-PFL-N-182', 'function(){loadConsolidatedSummary();}', NULL, '102', 'APP-ACL-N1062');