
Insert into GMC_GRID_MENU_CONFIGURATION
   (MENU_ID, GRID_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, 
    FEATURE_ID, LINK_CALLED, ICON_CLASS, MENU_PARENT_ID, ACL_ID)
 Values
   ('LOS-QualityCertificate', 'LOS', 'Record Quality Certificate', 4, 2, 
    NULL, 'function(){RecordQualityCertificate();}', NULL, 'LOB-OP', NULL);


Insert into SCM_SERVICE_CHARGE_MASTER
   (COST_ID, GROUP_ID, COST_COMPONENT_NAME, COST_DISPLAY_NAME, QUOTATION_TYPE_ID, 
    QUOTATION_SUB_TYPE_ID, COST_TYPE, COST_GROUP_ID, IS_AUTO_ACCRUAL, IS_CONTRACT_ACCRUAL_POSSIBLE, 
    IS_GENERAL_ACCRUAL_POSSIBLE, REVERSAL_TYPE, ACC_DIRECT_ACTUAL, ACC_ORIGINAL_ACCRUAL, ACC_UNDER_ACCRUAL, 
    ACC_OVER_ACCRUAL, ALLOW_ACCRUAL_ON_SALES, ALLOW_ACCRUAL_ON_PURCHASES, INC_EXP, INTEREST_CAL_REQ, 
    DISPLAY_ORDER, VERSION, IS_ACTIVE, IS_DELETED, SERVICE_CHARGE_SUB_TYPE_ID)
 Values
   ('SCM-26', 'GCD-1', 'SamplingCharge', 'Sampling Charge', NULL, 
    NULL, 'OTHER_CHARGES', 'CGM-7', 'N', 'N', 
    'Y', 'CONTRACT', 'N', 'Y', 'N', 
    'N', 'Y', 'Y', 'Expense', 'N', 
    25, NULL, 'Y', 'N', 'OTHER_CHARGES');
    
alter table PCMAC_PCM_ADDN_CHARGES add is_automatic_charge char(1) default 'N';    

