delete from DGM_DOCUMENT_GENERATION_MASTER dgm where DGM.DGM_ID = 'DGM-VAT-2';
SET DEFINE OFF;

Insert into DGM_DOCUMENT_GENERATION_MASTER
   (DGM_ID, DOC_ID, DOC_NAME, ACTIVITY_ID, SEQUENCE_ORDER, 
    FETCH_QUERY, IS_CONCENTRATE)
 Values
   ('DGM-VAT-2', 'CREATE_VAT', 'VAT Invoice', 'CREATE_VAT', 2, 
    'INSERT INTO VAT_CHILD_D (
INTERNAL_INVOICE_REF_NO,
VAT_NO,
CP_VAT_NO,
VAT_CODE,
VAT_RATE,
VAT_AMOUNT,
VAT_AMOUNT_CUR,
INTERNAL_DOC_REF_NO
)
select
IVD.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
IVD.OUR_VAT_NO as VAT_NO,
IVD.CP_VAT_NO as CP_VAT_NO,
TM.TAX_CODE as VAT_CODE,
IVD.VAT_RATE as VAT_RATE,
IVD.VAT_AMOUNT_IN_INV_CUR as VAT_AMOUNT,
CM.CUR_CODE as VAT_AMOUNT_CUR,
?
from
IVD_INVOICE_VAT_DETAILS ivd,
IS_INVOICE_SUMMARY invs,
CM_CURRENCY_MASTER cm,
TM_TAX_MASTER tm
where
INVS.INTERNAL_INVOICE_REF_NO = IVD.INTERNAL_INVOICE_REF_NO
and IVD.VAT_REMIT_CUR_ID = CM.CUR_ID
and IVD.VAT_CODE = TM.TAX_ID
and INVS.INTERNAL_INVOICE_REF_NO = ?', 'N');


Insert into DGM_DOCUMENT_GENERATION_MASTER
   (DGM_ID, DOC_ID, DOC_NAME, ACTIVITY_ID, SEQUENCE_ORDER, 
    FETCH_QUERY, IS_CONCENTRATE)
 Values
   ('DGM-VAT-2-CONC', 'CREATE_VAT', 'VAT Invoice Concentrate', 'CREATE_VAT', 2, 
    'INSERT INTO VAT_CHILD_D (
INTERNAL_INVOICE_REF_NO,
VAT_NO,
CP_VAT_NO,
VAT_CODE,
VAT_RATE,
VAT_AMOUNT,
VAT_AMOUNT_CUR,
INTERNAL_DOC_REF_NO
)
select
IVD.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
IVD.OUR_VAT_NO as VAT_NO,
IVD.CP_VAT_NO as CP_VAT_NO,
TM.TAX_CODE as VAT_CODE,
IVD.VAT_RATE as VAT_RATE,
IVD.VAT_AMOUNT_IN_INV_CUR as VAT_AMOUNT,
CM.CUR_CODE as VAT_AMOUNT_CUR,
?
from
IVD_INVOICE_VAT_DETAILS ivd,
IS_INVOICE_SUMMARY invs,
CM_CURRENCY_MASTER cm,
TM_TAX_MASTER tm
where
INVS.INTERNAL_INVOICE_REF_NO = IVD.INTERNAL_INVOICE_REF_NO
and IVD.VAT_REMIT_CUR_ID = CM.CUR_ID
and IVD.VAT_CODE = TM.TAX_ID
and INVS.INTERNAL_INVOICE_REF_NO = ?', 'Y');

Insert into DGM_DOCUMENT_GENERATION_MASTER
   (DGM_ID, DOC_ID, DOC_NAME, ACTIVITY_ID, SEQUENCE_ORDER, 
    FETCH_QUERY, IS_CONCENTRATE)
 Values
   ('DGM-VAT-1-CONC', 'CREATE_VAT', 'VAT Invoice Concentrate', 'CREATE_VAT', 1, 
    'INSERT INTO VAT_D (
INTERNAL_INVOICE_REF_NO,
CONTRACT_REF_NO,
CP_CONTRACT_REF_NO,
INCO_TERM_LOCATION,
CONTRACT_DATE,
CP_NAME,
SELLER,
CONTRACT_QUANTITY,
CONTRACT_TOLERANCE,
PRODUCT,
QUALITY,
NOTIFY_PARTY,
INVOICE_CREATION_DATE,
INVOICE_REF_NO,
CONTRACT_TYPE,
INVOICE_STATUS,
SALES_PURCHASE,
INTERNAL_DOC_REF_NO,
VAT_PARENT_REF_NO
)
select
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
PCM.CONTRACT_REF_NO as CONTRACT_REF_NO,
PCM.CP_CONTRACT_REF_NO as CP_CONTRACT_REF_NO,
PCI.TERMS as INCO_TERM_LOCATION,
TO_CHAR(PCM.ISSUE_DATE, ''dd-Mon-yyyy'') as CONTRACT_DATE,
PHD.COMPANYNAME as CP_NAME,
'''' as SELLER,
'''' as CONTRACT_QUANTITY,
'''' as CONTRACT_TOLERANCE,
PDM.PRODUCT_DESC as PRODUCT,
QAT.QUALITY_NAME as QUALITY,
'''' as NOTIFY_PARTY,
TO_CHAR(INVS.INVOICE_CREATED_DATE, ''dd-Mon-yyyy'') as INVOICE_CREATION_DATE,
INVS.INVOICE_REF_NO as INVOICE_REF_NO,
PCM.CONTRACT_TYPE as CONTRACT_TYPE,
INVS.INVOICE_STATUS as INVOICE_STATUS,
PCM.PURCHASE_SALES as SALES_PURCHASE,
?,
INVS.VAT_PARENT_REF_NO as VAT_PARENT_REF_NO
from
IS_INVOICE_SUMMARY invs,
IVD_INVOICE_VAT_DETAILS ivd,
PCM_PHYSICAL_CONTRACT_MAIN pcm,
v_pci pci,
PHD_PROFILEHEADERDETAILS phd,
PDM_PRODUCTMASTER pdm,
QAT_QUALITY_ATTRIBUTES qat,
PCPD_PC_PRODUCT_DEFINITION pcpd
where
INVS.INTERNAL_INVOICE_REF_NO = IVD.INTERNAL_INVOICE_REF_NO
and INVS.INTERNAL_CONTRACT_REF_NO = PCM.INTERNAL_CONTRACT_REF_NO
and PCPD.INTERNAL_CONTRACT_REF_NO = PCM.INTERNAL_CONTRACT_REF_NO
and PCPD.PRODUCT_ID = PDM.PRODUCT_ID
and PCI.INTERNAL_CONTRACT_REF_NO = PCM.INTERNAL_CONTRACT_REF_NO
and PCI.QUALITY_ID = QAT.QUALITY_ID
AND PCM.CP_ID = PHD.PROFILEID(+)
and INVS.INTERNAL_INVOICE_REF_NO = ?
group by 
INVS.INTERNAL_INVOICE_REF_NO,
PCM.CONTRACT_REF_NO,
PCM.CP_CONTRACT_REF_NO,
PCI.TERMS,
PCM.ISSUE_DATE,
PHD.COMPANYNAME,
PDM.PRODUCT_DESC,
QAT.QUALITY_NAME,
INVS.INVOICE_CREATED_DATE,
INVS.INVOICE_REF_NO,
PCM.CONTRACT_TYPE,
INVS.INVOICE_STATUS,
PCM.PURCHASE_SALES,
INVS.VAT_PARENT_REF_NO', 'Y');
