
UPDATE AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO=DISPLAY_SEQ_NO +1 WHERE DISPLAY_SEQ_NO > 10 and MENU_LEVEL_NO=1;
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO=11 WHERE MENU_ID='TOL-M';   

Insert into ATM_APP_TAB_MASTER (TAB_ID, TAB_NAME, IS_DEFAULT, IS_ACTIVE)
 Values    ('Inventory', 'Inventory', 'N', 'Y');
 
 UPDATE AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO=DISPLAY_SEQ_NO +1 WHERE DISPLAY_SEQ_NO > 15 and MENU_LEVEL_NO=1;

 Insert into AMC_APP_MENU_CONFIGURATION
   (MENU_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, LINK_CALLED, 
    ICON_CLASS, MENU_PARENT_ID, ACL_ID, TAB_ID, FEATURE_ID)
 Values
   ('INV1', 'Inventory', 16, 1, NULL, NULL, NULL, NULL, 'Inventory', NULL);



Insert into AMC_APP_MENU_CONFIGURATION
   (MENU_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, LINK_CALLED, 
    ICON_CLASS, MENU_PARENT_ID, ACL_ID, TAB_ID, FEATURE_ID)
 Values
   ('TOL-M1.1', 'Discrete Tolling', 10, 2, NULL, 
    NULL, 'TOL-M', NULL, 'Tolling', NULL);
 
 Insert into AMC_APP_MENU_CONFIGURATION
   (MENU_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, LINK_CALLED, 
    ICON_CLASS, MENU_PARENT_ID, ACL_ID, TAB_ID, FEATURE_ID)
 Values
   ('TOL-M1.2', 'Continuous Tolling', 20, 2, NULL, 
    NULL, 'TOL-M', NULL, 'Tolling', NULL);

 Insert into AMC_APP_MENU_CONFIGURATION
   (MENU_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, LINK_CALLED, 
    ICON_CLASS, MENU_PARENT_ID, ACL_ID, TAB_ID, FEATURE_ID)
 Values
   ('TOL-M1.2.1', 'In Process Stock', 17, 3, NULL, 
    NULL, 'TOL-M1.2', NULL, 'Tolling', NULL);

  Insert into AMC_APP_MENU_CONFIGURATION
   (MENU_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, LINK_CALLED, 
    ICON_CLASS, MENU_PARENT_ID, ACL_ID, TAB_ID, FEATURE_ID)
 Values
   ('TOL-M1.2.2', 'Smelter', 19, 3, NULL, 
    NULL, 'TOL-M1.2', NULL, 'Tolling', NULL);

  Insert into AMC_APP_MENU_CONFIGURATION
   (MENU_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, LINK_CALLED, 
    ICON_CLASS, MENU_PARENT_ID, ACL_ID, TAB_ID, FEATURE_ID)
 Values
   ('TOL-M1.2.3', 'Metal Accounts', 16, 3, NULL, 
    NULL, 'TOL-M1.2', NULL, 'Tolling', NULL);

  Insert into AMC_APP_MENU_CONFIGURATION
   (MENU_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, LINK_CALLED, 
    ICON_CLASS, MENU_PARENT_ID, ACL_ID, TAB_ID, FEATURE_ID)
 Values
   ('TOL-M1.1.1', 'Tolling Contract', 11, 3, NULL, 
    NULL, 'TOL-M1.1', NULL, 'Tolling', NULL);

    delete from AMC_APP_MENU_CONFIGURATION where MENU_ID= 'MINING_TOL-M4';


    --Changes in the existing menu
    Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =13,MENU_PARENT_ID= 'TOL-M1.1',MENU_LEVEL_NO =3,MENU_DISPLAY_NAME='In Process Stock'  WHERE MENU_ID='TOL-M1';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =14,MENU_PARENT_ID= 'TOL-M1.1',MENU_LEVEL_NO =3,MENU_DISPLAY_NAME='Tolling Input/Output'  WHERE MENU_ID='TOL-M2';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =15,MENU_PARENT_ID= 'TOL-M1.1.1',MENU_LEVEL_NO =4,MENU_DISPLAY_NAME='List All'  WHERE MENU_ID='TOL-M3';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =12,MENU_PARENT_ID= 'TOL-M1.1',MENU_LEVEL_NO =3,MENU_DISPLAY_NAME='Contract Item'  WHERE MENU_ID='TOL-M4';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =11,MENU_PARENT_ID= 'TOL-M1.1.1',MENU_LEVEL_NO =4,MENU_DISPLAY_NAME='New Tolling Contract'  WHERE MENU_ID='TOL-M5';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =11,MENU_PARENT_ID= 'TOL-M1.2',MENU_LEVEL_NO =3,MENU_DISPLAY_NAME='Tolling Contract'  WHERE MENU_ID='TOL-M6';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =11,MENU_PARENT_ID= 'INV1',MENU_LEVEL_NO =2,MENU_DISPLAY_NAME='Conversion/Processing Activity'  WHERE MENU_ID='TOL-P7';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =12,MENU_PARENT_ID= 'TOL-M1.2',MENU_LEVEL_NO =3,MENU_DISPLAY_NAME='Delivery Item'  WHERE MENU_ID='TOL-M7';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =14,MENU_PARENT_ID= 'TOL-M1.2',MENU_LEVEL_NO =3,MENU_DISPLAY_NAME='Contract Item'  WHERE MENU_ID='TOL-M9';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =15,MENU_PARENT_ID= 'TOL-M1.2',MENU_LEVEL_NO =3,MENU_DISPLAY_NAME='Position by Element'  WHERE MENU_ID='TOL-M12';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =18,MENU_PARENT_ID= 'TOL-M1.2',MENU_LEVEL_NO =3,MENU_DISPLAY_NAME='Tolling Input/Output'  WHERE MENU_ID='TOL-M13';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =14,MENU_PARENT_ID= 'TOL-M1.2.1',MENU_LEVEL_NO =4,MENU_DISPLAY_NAME='Summary'  WHERE MENU_ID='MINING_SMELT';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =16,MENU_PARENT_ID= 'TOL-M1.2.2',MENU_LEVEL_NO =4,MENU_DISPLAY_NAME='Receive Materials'  WHERE MENU_ID='MINING_RM';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =15,MENU_PARENT_ID= 'TOL-M1.2.1',MENU_LEVEL_NO =4,MENU_DISPLAY_NAME='Details'  WHERE MENU_ID='TOL-MFT_IN';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =11,MENU_PARENT_ID= 'TOL-M1.2.3',MENU_LEVEL_NO =4,MENU_DISPLAY_NAME='Summary'  WHERE MENU_ID='TOL-MACC';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =13,MENU_PARENT_ID= 'TOL-M1.2',MENU_LEVEL_NO =3,MENU_DISPLAY_NAME='Call-Offs'  WHERE MENU_ID='TOL-M14';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =12,MENU_PARENT_ID= 'TOL-M1.2.3',MENU_LEVEL_NO =4,MENU_DISPLAY_NAME='Return Material'  WHERE MENU_ID='MINING_RMA';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =13,MENU_PARENT_ID= 'TOL-M1.2.3',MENU_LEVEL_NO =4,MENU_DISPLAY_NAME='Details'  WHERE MENU_ID='TOL-MACCT';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =3,MENU_PARENT_ID= 'PE1',MENU_LEVEL_NO =2,MENU_DISPLAY_NAME='Price Fixation'  WHERE MENU_ID='MINING_PF';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =14,MENU_PARENT_ID= 'TOL-M1.2.3',MENU_LEVEL_NO =4,MENU_DISPLAY_NAME='Financial Settlements'  WHERE MENU_ID='TOL-FS';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =4,MENU_PARENT_ID= 'PE1',MENU_LEVEL_NO =2,MENU_DISPLAY_NAME='Allocations'  WHERE MENU_ID='MINING_DDA';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =16,MENU_PARENT_ID= 'TOL-M1.2.3',MENU_LEVEL_NO =4,MENU_DISPLAY_NAME='Metal Transfers'  WHERE MENU_ID='TOL-MBT';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =15,MENU_PARENT_ID= 'TOL-M1.2.3',MENU_LEVEL_NO =4,MENU_DISPLAY_NAME='Pledges'  WHERE MENU_ID='L6';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =2,MENU_PARENT_ID= 'TOL-M6',MENU_LEVEL_NO =4,MENU_DISPLAY_NAME='SellTollingService'  WHERE MENU_ID='TOL-M6_M2';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =3,MENU_PARENT_ID= 'TOL-M6',MENU_LEVEL_NO =4,MENU_DISPLAY_NAME='List all'  WHERE MENU_ID='TOL-M6_M3';
Update AMC_APP_MENU_CONFIGURATION SET DISPLAY_SEQ_NO =1,MENU_PARENT_ID= 'TOL-M6',MENU_LEVEL_NO =4,MENU_DISPLAY_NAME='BuyTollingService'  WHERE MENU_ID='TOL-M6_M1';


delete from LCM_LINK_CONFIG_MASTER  Where LINK_ID='MAIN_APP_HELP';
Insert into LCM_LINK_CONFIG_MASTER
   (LINK_ID, LINK_URL)
 Values
   ('MAIN_APP_HELP', '/metals/Metals_Help/Mining/Online_Help.htm');

