ALTER TABLE TEMP_FCR ADD

(PRODUCT_BASE_QTY_UNIT_ID VARCHAR2(15),

PRODUCT_BASE_QTY_UNIT VARCHAR2(15));

ALTER TABLE FCR_FEED_CONSUMPTION_REPORT ADD

(PRODUCT_BASE_QTY_UNIT_ID VARCHAR2(15),

PRODUCT_BASE_QTY_UNIT VARCHAR2(15));

