delete from SLS_STATIC_LIST_SETUP where VALUE_ID IN ('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec');
delete from SLV_STATIC_LIST_VALUE where VALUE_ID IN ('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec');
commit;
SET DEFINE OFF;
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Jan', 'Jan');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Feb', 'Feb');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Mar', 'Mar');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Apr', 'Apr');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('May', 'May');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Jun', 'Jun');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Jul', 'Jul');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Aug', 'Aug');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Sep', 'Sep');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Oct', 'Oct');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Nov', 'Nov');
Insert into SLV_STATIC_LIST_VALUE(VALUE_ID, VALUE_TEXT)Values('Dec', 'Dec');
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Jan', 'N', 1);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Feb', 'N', 2);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Mar', 'N', 3);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Apr', 'N', 4);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'May', 'N', 5);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Jun', 'N', 6);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Jul', 'N', 7);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Aug', 'N', 8);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Sep', 'N', 9);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Oct', 'N', 10);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Nov', 'N', 11);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)Values('MonthList', 'Dec', 'N', 12);
COMMIT;

delete from SLS_STATIC_LIST_SETUP where VALUE_ID IN ('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec');
delete from SLV_STATIC_LIST_VALUE where VALUE_ID IN ('Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec');
delete from SLS_STATIC_LIST_SETUP where VALUE_ID IN ('2009','2010','2011','2012','2013','2014','2015');
delete from SLV_STATIC_LIST_VALUE where VALUE_ID IN ('2009','2010','2011','2012','2013','2014','2015');
commit;
SET DEFINE OFF;

insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('2009', '2009');
insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('2010', '2010');
insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('2011', '2011');
insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('2012', '2012');
insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('2013', '2013');
insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('2014', '2014');
insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('2015', '2015');
insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('Jan', 'Jan');
insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('Feb', 'Feb');
insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('Mar', 'Mar');
insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('Apr', 'Apr');
insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('May', 'May');
insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('Jun', 'Jun');
insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('Jul', 'Jul');
insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('Aug', 'Aug');
insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('Sep', 'Sep');
insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('Oct', 'Oct');
insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('Nov', 'Nov');
insert into slv_static_list_value (VALUE_ID, VALUE_TEXT) values ('Dec', 'Dec');

Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('MonthList', 'Jan', 'N', 1);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('MonthList', 'Feb', 'N', 2);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('MonthList', 'Mar', 'N', 3);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('MonthList', 'Apr', 'N', 4);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('MonthList', 'May', 'N', 5);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('MonthList', 'Jun', 'N', 6);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('MonthList', 'Jul', 'N', 7);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('MonthList', 'Aug', 'N', 8);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('MonthList', 'Sep', 'N', 9);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('MonthList', 'Oct', 'N', 10);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('MonthList', 'Nov', 'N', 11);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('MonthList', 'Dec', 'N', 12);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('yearList', '2009', 'N', 1);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('yearList', '2010', 'N', 2);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('yearList', '2011', 'N', 3);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('yearList', '2012', 'N', 4);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('yearList', '2013', 'N', 5);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('yearList', '2014', 'N', 6);
Insert into SLS_STATIC_LIST_SETUP(LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER) Values('yearList', '2015', 'N', 7);
COMMIT;
