Insert into DGM_DOCUMENT_GENERATION_MASTER
   (DGM_ID, DOC_ID, DOC_NAME, ACTIVITY_ID, SEQUENCE_ORDER, 
    FETCH_QUERY)
 Values
   ('DGM-PI-C1', 'CREATE_PI', 'Provisional Invoice', 'CREATE_PI', 2, 
    'INSERT INTO IS_CHILD_D(
INTERNAL_INVOICE_REF_NO,
GMR_REF_NO,
GMR_QUANTITY,
GMR_QUALITY,
PRICE_AS_PER_DEFIND_UOM,
TOTAL_PRICE_QTY,
GMR_QTY_UNIT,
INVOICED_QTY_UNIT,
INVOICED_PRICE_UNIT,
INTERNAL_DOC_REF_NO
)

select
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
GMR.GMR_REF_NO as GMR_REF_NO,
GMR.QTY as GMR_QUANTITY,
'' as GMR_QUALITY,
IID.NEW_INVOICE_PRICE as PRICE_AS_PER_DEFIND_UOM,
IID.INVOICED_QTY as TOTAL_PRICE_QTY,
QUM.QTY_UNIT as GMR_QTY_UNIT,
QUMINV.QTY_UNIT as INVOICED_QTY_UNIT,
PUM.PRICE_UNIT_NAME as INVOICED_PRICE_UNIT,
?
from
IS_INVOICE_SUMMARY invs,
IID_INVOICABLE_ITEM_DETAILS iid,
GMR_GOODS_MOVEMENT_RECORD gmr,
QUM_QUANTITY_UNIT_MASTER qum,
QUM_QUANTITY_UNIT_MASTER quminv,
PPU_PRODUCT_PRICE_UNITS ppu,
PUM_PRICE_UNIT_MASTER pum
where
INVS.INTERNAL_INVOICE_REF_NO = IID.INTERNAL_INVOICE_REF_NO(+)
and IID.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO(+)
and GMR.QTY_UNIT_ID = QUM.QTY_UNIT_ID(+)
and IID.INVOICED_QTY_UNIT_ID = QUMINV.QTY_UNIT_ID(+)
and IID.NEW_INVOICE_PRICE_UNIT_ID = PPU.INTERNAL_PRICE_UNIT_ID(+)
and PPU.PRICE_UNIT_ID = PUM.PRICE_UNIT_ID(+)
and IID.INTERNAL_INVOICE_REF_NO = ?');



Insert into DGM_DOCUMENT_GENERATION_MASTER
   (DGM_ID, DOC_ID, DOC_NAME, ACTIVITY_ID, SEQUENCE_ORDER, 
    FETCH_QUERY)
 Values
   ('DGM-FI-C1', 'CREATE_FI', 'Provisional Invoice', 'CREATE_FI', 2, 
    'INSERT INTO IS_CHILD_D(
INTERNAL_INVOICE_REF_NO,
GMR_REF_NO,
GMR_QUANTITY,
GMR_QUALITY,
PRICE_AS_PER_DEFIND_UOM,
TOTAL_PRICE_QTY,
GMR_QTY_UNIT,
INVOICED_QTY_UNIT,
INVOICED_PRICE_UNIT,
INTERNAL_DOC_REF_NO
)

select
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
GMR.GMR_REF_NO as GMR_REF_NO,
GMR.QTY as GMR_QUANTITY,
'' as GMR_QUALITY,
IID.NEW_INVOICE_PRICE as PRICE_AS_PER_DEFIND_UOM,
IID.INVOICED_QTY as TOTAL_PRICE_QTY,
QUM.QTY_UNIT as GMR_QTY_UNIT,
QUMINV.QTY_UNIT as INVOICED_QTY_UNIT,
PUM.PRICE_UNIT_NAME as INVOICED_PRICE_UNIT,
?
from
IS_INVOICE_SUMMARY invs,
IID_INVOICABLE_ITEM_DETAILS iid,
GMR_GOODS_MOVEMENT_RECORD gmr,
QUM_QUANTITY_UNIT_MASTER qum,
QUM_QUANTITY_UNIT_MASTER quminv,
PPU_PRODUCT_PRICE_UNITS ppu,
PUM_PRICE_UNIT_MASTER pum
where
INVS.INTERNAL_INVOICE_REF_NO = IID.INTERNAL_INVOICE_REF_NO(+)
and IID.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO(+)
and GMR.QTY_UNIT_ID = QUM.QTY_UNIT_ID(+)
and IID.INVOICED_QTY_UNIT_ID = QUMINV.QTY_UNIT_ID(+)
and IID.NEW_INVOICE_PRICE_UNIT_ID = PPU.INTERNAL_PRICE_UNIT_ID(+)
and PPU.PRICE_UNIT_ID = PUM.PRICE_UNIT_ID(+)
and IID.INTERNAL_INVOICE_REF_NO = ?');


Insert into DGM_DOCUMENT_GENERATION_MASTER
   (DGM_ID, DOC_ID, DOC_NAME, ACTIVITY_ID, SEQUENCE_ORDER, 
    FETCH_QUERY)
 Values
   ('DGM-DFI-C1', 'CREATE_DFI', 'Provisional Invoice', 'CREATE_DFI', 2, 
    'INSERT INTO IS_CHILD_D(
INTERNAL_INVOICE_REF_NO,
GMR_REF_NO,
GMR_QUANTITY,
GMR_QUALITY,
PRICE_AS_PER_DEFIND_UOM,
TOTAL_PRICE_QTY,
GMR_QTY_UNIT,
INVOICED_QTY_UNIT,
INVOICED_PRICE_UNIT,
INTERNAL_DOC_REF_NO
)

select
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
GMR.GMR_REF_NO as GMR_REF_NO,
GMR.QTY as GMR_QUANTITY,
'' as GMR_QUALITY,
IID.NEW_INVOICE_PRICE as PRICE_AS_PER_DEFIND_UOM,
IID.INVOICED_QTY as TOTAL_PRICE_QTY,
QUM.QTY_UNIT as GMR_QTY_UNIT,
QUMINV.QTY_UNIT as INVOICED_QTY_UNIT,
PUM.PRICE_UNIT_NAME as INVOICED_PRICE_UNIT,
?
from
IS_INVOICE_SUMMARY invs,
IID_INVOICABLE_ITEM_DETAILS iid,
GMR_GOODS_MOVEMENT_RECORD gmr,
QUM_QUANTITY_UNIT_MASTER qum,
QUM_QUANTITY_UNIT_MASTER quminv,
PPU_PRODUCT_PRICE_UNITS ppu,
PUM_PRICE_UNIT_MASTER pum
where
INVS.INTERNAL_INVOICE_REF_NO = IID.INTERNAL_INVOICE_REF_NO(+)
and IID.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO(+)
and GMR.QTY_UNIT_ID = QUM.QTY_UNIT_ID(+)
and IID.INVOICED_QTY_UNIT_ID = QUMINV.QTY_UNIT_ID(+)
and IID.NEW_INVOICE_PRICE_UNIT_ID = PPU.INTERNAL_PRICE_UNIT_ID(+)
and PPU.PRICE_UNIT_ID = PUM.PRICE_UNIT_ID(+)
and IID.INTERNAL_INVOICE_REF_NO = ?');