

Insert into AXM_ACTION_MASTER
   (ACTION_ID, ENTITY_ID, ACTION_NAME, IS_NEW_GMR_APPLICABLE, ACTION_DESC, 
    IS_GENERATE_DOC_APPLICABLE, IS_REF_NO_GEN_APPLICABLE, IS_EVENT_PUBLISH_APPLICABLE, IS_CONTINUOUS_MIDDLE_NO_REQ, IS_REQUIRED_FOR_EODEOM, 
    IS_ACTIVITY_LOG_APPLICABLE, IS_RECENT_RECORD_APPLICABLE, NAVIGATION_URL)
 Values
   ('CREATE_DFT_PFI', 'Draft Invoice', 'Create Draft Profoma Invoice', 'N', 'Draft Profoma Invoice Created', 
    'N', NULL, 'N', 'N', 'Y', 
    'Y', 'Y', NULL);



Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED, SEQ_NAME)
 Values
   ('ARF-4075', 'DFTPFIRefNo', 'BLD', 'DFT-PFI-', 1, 
    0, '-BLD', NULL, 'N', 'SEQAXM_DFTPFI_BLD');
    
Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED, SEQ_NAME)
 Values
   ('ARF-DFT-PFI-LDE', 'DFTPFIRefNo', 'LDE', 'DFT-PFI-', 1, 
    0, '-LDE', 1, 'N', 'SEQAXM_DFTPFI_LDE');
    
Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED, SEQ_NAME)
 Values
   ('ARF-4076', 'DFTPFIRefNo', 'BAM', 'DFT-PFI-', 1, 
    0, '-BAM', NULL, 'N', 'SEQAXM_DFTPFI_BAM');
    
Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED, SEQ_NAME)
 Values
   ('ARF-4077', 'DFTPFIRefNo', 'BAT', 'DFT-PFI-', 1, 
    0, '-BAT', NULL, 'N', 'SEQAXM_DFTPFI_BAT');


Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-6121', 'BLD', 'CREATE_DFT_PFI', 'DFTPFIRefNo', 'N');
   
Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-DFT-PFI-LDE', 'LDE', 'CREATE_DFT_PFI', 'DFTPFIRefNo', 'N');
   
Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-6122', 'BAM', 'CREATE_DFT_PFI', 'DFTPFIRefNo', 'N');
   
Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-6123', 'BAT', 'CREATE_DFT_PFI', 'DFTPFIRefNo', 'N');



Insert into AKM_ACTION_REF_KEY_MASTER
   (ACTION_KEY_ID, ACTION_KEY_DESC, VALIDATION_QUERY)
 Values
   ('DFTPFIRefNo', 'DFT PFI Ref No', 'SELECT COUNT(*) FROM   AXS_ACTION_SUMMARY axs WHERE  axs.action_ref_no 

= :pc_action_ref_no AND    axs.corporate_id = :pc_corporate_id');



Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX, 
    IS_CONTINUOUS_MIDDLE_NO_REQ, SEQ_NAME)
 Values
   ('BLD', 'CREATE_DFT_PFI', 'DFT-PFI-', 0, '-BLD', 
    'N', 'SEQERC_DFTPFI_BLD');
    
Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX, 
    IS_CONTINUOUS_MIDDLE_NO_REQ, SEQ_NAME)
 Values
   ('LDE', 'CREATE_DFT_PFI', 'DFT-PFI-', 0, '-LDE', 
    'N', 'SEQERC_DFTPFI_LDE');
    
Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX, 
    IS_CONTINUOUS_MIDDLE_NO_REQ, SEQ_NAME)
 Values
   ('BAM', 'CREATE_DFT_PFI', 'DFT-PFI-', 0, '-BAM', 
    'N', 'SEQERC_DFTPFI_BAM');
    
Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX, 
    IS_CONTINUOUS_MIDDLE_NO_REQ, SEQ_NAME)
 Values
   ('BAT', 'CREATE_DFT_PFI', 'DFT-PFI-', 0, '-BAT', 
    'N', 'SEQERC_DFTPFI_BAT');