Insert into SLS_STATIC_LIST_SETUP
   (LIST_TYPE, VALUE_ID, IS_DEFAULT, DISPLAY_ORDER)
 Values
   ('otherChargeUnit', 'Lot', 'N', 1);

alter table PCIUL_PHY_CONTRACT_ITEM_UL add SPE_SETTLEMENT_STATUS VARCHAR2 (15 Char);
alter table PCIUL_PHY_CONTRACT_ITEM_UL add ITEM_STATUS VARCHAR2 (15 Char);



update GMC_GRID_MENU_CONFIGURATION
set GMC_GRID_MENU_CONFIGURATION.LINK_CALLED='function(){loadMFTGmrDataforPriceAllocation();}'
where GMC_GRID_MENU_CONFIGURATION.MENU_ID='MTGMR_LIST_5';

