update SCM_SERVICE_CHARGE_MASTER scm set SCM.IS_ACTIVE = 'N' ,SCM.IS_DELETED = 'Y'
where SCM.COST_COMPONENT_NAME = 'Bank Fees'

update SCM_SERVICE_CHARGE_MASTER scm set SCM.ACC_ORIGINAL_ACCRUAL = 'Y' ,SCM.ACC_UNDER_ACCRUAL = 'Y'
where SCM.COST_COMPONENT_NAME = 'Material Cost'

update SCM_SERVICE_CHARGE_MASTER scm set SCM.ACC_ORIGINAL_ACCRUAL = 'Y' ,SCM.ACC_UNDER_ACCRUAL = 'Y'
where SCM.COST_COMPONENT_NAME = 'Location Premium'

update SCM_SERVICE_CHARGE_MASTER scm set SCM.ACC_ORIGINAL_ACCRUAL = 'Y' ,SCM.ACC_UNDER_ACCRUAL = 'Y'
where SCM.COST_COMPONENT_NAME = 'Quality Premium'

update SCM_SERVICE_CHARGE_MASTER scm set SCM.ACC_ORIGINAL_ACCRUAL = 'Y' ,SCM.ACC_UNDER_ACCRUAL = 'Y'
where SCM.COST_COMPONENT_NAME = 'Treatment Charges'

update SCM_SERVICE_CHARGE_MASTER scm set SCM.ACC_ORIGINAL_ACCRUAL = 'Y' ,SCM.ACC_UNDER_ACCRUAL = 'Y'
where SCM.COST_COMPONENT_NAME = 'Refining Charges'

update SCM_SERVICE_CHARGE_MASTER scm set SCM.ACC_ORIGINAL_ACCRUAL = 'Y' ,SCM.ACC_UNDER_ACCRUAL = 'Y'
where SCM.COST_COMPONENT_NAME = 'Penalties'