update DGM_DOCUMENT_GENERATION_MASTER DGM set DGM.FETCH_QUERY = 'INSERT INTO IS_DC_CHILD_D(
INTERNAL_INVOICE_REF_NO,
DESCRIPTION,
INVOICED_WEIGHT,
NEW_INVOICED_WEIGHT,
INVOICE_PRICE,
NEW_INVOICE_PRICE,
AMOUNT,
NEW_AMOUNT,
OLD_INVOICE_AMOUNT,
NEW_INVOICE_AMOUNT,
NET_ADJUSTMENT,
OLD_PRICE_UNIT_NAME,
NEW_PRICE_UNIT_NAME,
OLD_INVOICE_CUR_UNIT,
NEW_INVOICE_CUR_UNIT,
INVOICE_CUR_UNIT,
INVOICE_QTY_UNIT_NAME,
INTERNAL_DOC_REF_NO
)
select
IID.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
GMR.GMR_REF_NO as DESCRIPTION,
IID.INVOICED_QTY as INVOICED_WEIGHT,
IID.NEW_INVOICED_QTY as NEW_INVOICED_WEIGHT,
IID.INVOICED_PRICE as INVOICE_PRICE,
IID.NEW_INVOICE_PRICE as NEW_INVOICE_PRICE,
IID.ITEM_AMOUNT as AMOUNT,
IID.INVOICE_ITEM_AMOUNT as NEW_AMOUNT,
IID.ITEM_AMOUNT as OLD_INVOICE_AMOUNT,
(IID.NEW_INVOICED_QTY * IID.NEW_INVOICE_PRICE) as NEW_INVOICE_AMOUNT,
(IID.INVOICE_ITEM_AMOUNT - IID.ITEM_AMOUNT) as NET_ADJUSTMENT,
PUM.PRICE_UNIT_NAME as OLD_PRICE_UNIT_NAME,
PUM.PRICE_UNIT_NAME as NEW_PRICE_UNIT_NAME,
CM.CUR_CODE as OLD_INVOICE_CUR_UNIT,
CM.CUR_CODE as NEW_INVOICE_CUR_UNIT,
CM.CUR_CODE as INVOICE_CUR_UNIT,
QUM.QTY_UNIT as INVOICE_QTY_UNIT_NAME,
?
from
IS_INVOICE_SUMMARY invs,
IID_INVOICABLE_ITEM_DETAILS iid,
QUM_QUANTITY_UNIT_MASTER qum,
CM_CURRENCY_MASTER cm,
PPU_PRODUCT_PRICE_UNITS ppu,
PUM_PRICE_UNIT_MASTER pum,
GMR_GOODS_MOVEMENT_RECORD gmr
where
INVS.INTERNAL_INVOICE_REF_NO = IID.INTERNAL_INVOICE_REF_NO
and IID.INVOICE_CURRENCY_ID = CM.CUR_ID
and IID.INVOICED_PRICE_UNIT_ID = PPU.INTERNAL_PRICE_UNIT_ID
and PPU.PRICE_UNIT_ID = PUM.PRICE_UNIT_ID
and IID.INVOICED_QTY_UNIT_ID = QUM.QTY_UNIT_ID
and IID.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO
and INVS.INTERNAL_INVOICE_REF_NO = ?' where DGM.DOC_ID = 'CREATE_DC' AND DGM.DGM_ID = 'DGM-DC-C1';