update DGM_DOCUMENT_GENERATION_MASTER dgm set DGM.FETCH_QUERY = 
'INSERT INTO IS_CHILD_SI_D(
INTERNAL_INVOICE_REF_NO,
GMR_REF_NO,
COST_COMPONENT_NAME,
INVOICE_AMOUNT,
INVOICE_AMOUNT_UNIT,
INTERNAL_DOC_REF_NO
)
select
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
GMR.GMR_REF_NO as GMR_REF_NO,
SCM.COST_COMPONENT_NAME as COST_COMPONENT_NAME,
CS.TRANSACTION_AMT as INVOICE_AMOUNT,
CM.CUR_CODE as INVOICE_AMOUNT_UNIT,
?
from
IS_INVOICE_SUMMARY invs,
IAM_INVOICE_ACTION_MAPPING iam,
CS_COST_STORE cs,
CIGC_CONTRACT_ITEM_GMR_COST cigc,
GMR_GOODS_MOVEMENT_RECORD gmr,
SCM_SERVICE_CHARGE_MASTER scm,
CM_CURRENCY_MASTER cm
where
INVS.INTERNAL_INVOICE_REF_NO = IAM.INTERNAL_INVOICE_REF_NO
and IAM.INVOICE_ACTION_REF_NO = CS.INTERNAL_ACTION_REF_NO
and CS.COG_REF_NO = CIGC.COG_REF_NO
and CIGC.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO
and CS.COST_COMPONENT_ID = SCM.COST_ID
and CS.TRANSACTION_AMT_CUR_ID = CM.CUR_ID
and INVS.INVOICE_TYPE = ''Service''
and INVS.INTERNAL_INVOICE_REF_NO = ?'
where
DGM.DOC_ID = 'CREATE_SI' and DGM.DGM_ID = 'DGM-SIC-1' and DGM.SEQUENCE_ORDER = 2;


update DGM_DOCUMENT_GENERATION_MASTER dgm set DGM.FETCH_QUERY = 
'INSERT INTO IS_CHILD_SI_D(
INTERNAL_INVOICE_REF_NO,
GMR_REF_NO,
COST_COMPONENT_NAME,
INVOICE_AMOUNT,
INVOICE_AMOUNT_UNIT,
INTERNAL_DOC_REF_NO
)
select
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
GMR.GMR_REF_NO as GMR_REF_NO,
SCM.COST_COMPONENT_NAME as COST_COMPONENT_NAME,
CS.TRANSACTION_AMT as INVOICE_AMOUNT,
CM.CUR_CODE as INVOICE_AMOUNT_UNIT,
?
from
IS_INVOICE_SUMMARY invs,
IAM_INVOICE_ACTION_MAPPING iam,
CS_COST_STORE cs,
CIGC_CONTRACT_ITEM_GMR_COST cigc,
GMR_GOODS_MOVEMENT_RECORD gmr,
SCM_SERVICE_CHARGE_MASTER scm,
CM_CURRENCY_MASTER cm
where
INVS.INTERNAL_INVOICE_REF_NO = IAM.INTERNAL_INVOICE_REF_NO
and IAM.INVOICE_ACTION_REF_NO = CS.INTERNAL_ACTION_REF_NO
and CS.COG_REF_NO = CIGC.COG_REF_NO
and CIGC.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO
and CS.COST_COMPONENT_ID = SCM.COST_ID
and CS.TRANSACTION_AMT_CUR_ID = CM.CUR_ID
and INVS.INVOICE_TYPE = ''Service''
and INVS.INTERNAL_INVOICE_REF_NO = ?'
where
DGM.DOC_ID = 'CREATE_SI' and DGM.DGM_ID = 'DGM-SI-1' and DGM.SEQUENCE_ORDER = 2;

update DGM_DOCUMENT_GENERATION_MASTER dgm set DGM.FETCH_QUERY = 
'INSERT INTO ITD_D (
INTERNAL_INVOICE_REF_NO,
OTHER_CHARGE_COST_NAME,
TAX_RATE,
INVOICE_CURRENCY,
FX_RATE,
AMOUNT,
TAX_CURRENCY,
INVOICE_AMOUNT,
INTERNAL_DOC_REF_NO
)
select
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
TM.TAX_CODE as OTHER_CHARGE_COST_NAME,
ITD.TAX_RATE as TAX_RATE,
CM.CUR_CODE as INVOICE_CURRENCY,
ITD.FX_RATE as FX_RATE,
ITD.TAX_AMOUNT as AMOUNT,
CM_TAX.CUR_CODE as TAX_CURRENCY,
ITD.TAX_AMOUNT_IN_INV_CUR as INVOICE_AMOUNT,
?
from
IS_INVOICE_SUMMARY invs,
ITD_INVOICE_TAX_DETAILS itd,
TM_TAX_MASTER tm,
CM_CURRENCY_MASTER cm,
CM_CURRENCY_MASTER cm_tax
where
INVS.INTERNAL_INVOICE_REF_NO = ITD.INTERNAL_INVOICE_REF_NO
and ITD.TAX_CODE_ID = TM.TAX_ID
and ITD.INVOICE_CUR_ID = CM.CUR_ID
and ITD.TAX_AMOUNT_CUR_ID = CM_TAX.CUR_ID
and ITD.INTERNAL_INVOICE_REF_NO = ?'
where
DGM.DOC_ID = 'CREATE_SI' and DGM.DGM_ID = 'DGM-ITD_BM' and DGM.SEQUENCE_ORDER = 3;