Insert into SCM_SERVICE_CHARGE_MASTER
   (COST_ID, GROUP_ID, COST_COMPONENT_NAME, COST_DISPLAY_NAME, QUOTATION_TYPE_ID, 
    QUOTATION_SUB_TYPE_ID, COST_TYPE, COST_GROUP_ID, IS_AUTO_ACCRUAL, IS_CONTRACT_ACCRUAL_POSSIBLE, 
    IS_GENERAL_ACCRUAL_POSSIBLE, REVERSAL_TYPE, ACC_DIRECT_ACTUAL, ACC_ORIGINAL_ACCRUAL, ACC_UNDER_ACCRUAL, 
    ACC_OVER_ACCRUAL, ALLOW_ACCRUAL_ON_SALES, ALLOW_ACCRUAL_ON_PURCHASES, INC_EXP, INTEREST_CAL_REQ, 
    DISPLAY_ORDER, VERSION, IS_ACTIVE, IS_DELETED, SERVICE_CHARGE_SUB_TYPE_ID)
 Values
   ('SCM-11', 'GCD-1', 'Handling Charge', 'Handling Charge', NULL, 
    NULL, 'OTHER_CHARGES', 'CGM-7', 'N', 'N', 
    'Y', 'CONTRACT', 'N', 'Y', 'N', 
    'N', 'Y', 'Y', 'Expense', 'N', 
    12, NULL, 'Y', 'N', 'OTHER_CHARGES');

Insert into SCM_SERVICE_CHARGE_MASTER
   (COST_ID, GROUP_ID, COST_COMPONENT_NAME, COST_DISPLAY_NAME, QUOTATION_TYPE_ID, 
    QUOTATION_SUB_TYPE_ID, COST_TYPE, COST_GROUP_ID, IS_AUTO_ACCRUAL, IS_CONTRACT_ACCRUAL_POSSIBLE, 
    IS_GENERAL_ACCRUAL_POSSIBLE, REVERSAL_TYPE, ACC_DIRECT_ACTUAL, ACC_ORIGINAL_ACCRUAL, ACC_UNDER_ACCRUAL, 
    ACC_OVER_ACCRUAL, ALLOW_ACCRUAL_ON_SALES, ALLOW_ACCRUAL_ON_PURCHASES, INC_EXP, INTEREST_CAL_REQ, 
    DISPLAY_ORDER, VERSION, IS_ACTIVE, IS_DELETED, SERVICE_CHARGE_SUB_TYPE_ID)
 Values
   ('SCM-12', 'GCD-1', 'Freight Allowance', 'Freight Allowance', NULL, 
    NULL, 'OTHER_CHARGES', 'CGM-7', 'N', 'N', 
    'Y', 'CONTRACT', 'N', 'Y', 'N', 
    'N', 'Y', 'Y', 'Expense', 'N', 
    13, NULL, 'Y', 'N', 'OTHER_CHARGES');
    
    
Insert into SCM_SERVICE_CHARGE_MASTER
   (COST_ID, GROUP_ID, COST_COMPONENT_NAME, COST_DISPLAY_NAME, QUOTATION_TYPE_ID, 
    QUOTATION_SUB_TYPE_ID, COST_TYPE, COST_GROUP_ID, IS_AUTO_ACCRUAL, IS_CONTRACT_ACCRUAL_POSSIBLE, 
    IS_GENERAL_ACCRUAL_POSSIBLE, REVERSAL_TYPE, ACC_DIRECT_ACTUAL, ACC_ORIGINAL_ACCRUAL, ACC_UNDER_ACCRUAL, 
    ACC_OVER_ACCRUAL, ALLOW_ACCRUAL_ON_SALES, ALLOW_ACCRUAL_ON_PURCHASES, INC_EXP, INTEREST_CAL_REQ, 
    DISPLAY_ORDER, VERSION, IS_ACTIVE, IS_DELETED, SERVICE_CHARGE_SUB_TYPE_ID)
 Values
   ('SCM-13', 'GCD-1', 'Location Value', 'Location Value', NULL, 
    NULL, 'OTHER_CHARGES', 'CGM-7', 'N', 'N', 
    'Y', 'CONTRACT', 'N', 'Y', 'N', 
    'N', 'Y', 'Y', 'Expense', 'N', 
    14, NULL, 'Y', 'N', 'OTHER_CHARGES');
    
    Insert into SCM_SERVICE_CHARGE_MASTER
   (COST_ID, GROUP_ID, COST_COMPONENT_NAME, COST_DISPLAY_NAME, QUOTATION_TYPE_ID, 
    QUOTATION_SUB_TYPE_ID, COST_TYPE, COST_GROUP_ID, IS_AUTO_ACCRUAL, IS_CONTRACT_ACCRUAL_POSSIBLE, 
    IS_GENERAL_ACCRUAL_POSSIBLE, REVERSAL_TYPE, ACC_DIRECT_ACTUAL, ACC_ORIGINAL_ACCRUAL, ACC_UNDER_ACCRUAL, 
    ACC_OVER_ACCRUAL, ALLOW_ACCRUAL_ON_SALES, ALLOW_ACCRUAL_ON_PURCHASES, INC_EXP, INTEREST_CAL_REQ, 
    DISPLAY_ORDER, VERSION, IS_ACTIVE, IS_DELETED, SERVICE_CHARGE_SUB_TYPE_ID)
 Values
   ('SCM-14', 'GCD-1', 'Commercial Fees', 'Commercial Fees', NULL, 
    NULL, 'OTHER_CHARGES', 'CGM-7', 'N', 'N', 
    'Y', 'CONTRACT', 'N', 'Y', 'N', 
    'N', 'Y', 'Y', 'Expense', 'N', 
    15, NULL, 'Y', 'N', 'OTHER_CHARGES');
        
    Insert into SCM_SERVICE_CHARGE_MASTER
   (COST_ID, GROUP_ID, COST_COMPONENT_NAME, COST_DISPLAY_NAME, QUOTATION_TYPE_ID, 
    QUOTATION_SUB_TYPE_ID, COST_TYPE, COST_GROUP_ID, IS_AUTO_ACCRUAL, IS_CONTRACT_ACCRUAL_POSSIBLE, 
    IS_GENERAL_ACCRUAL_POSSIBLE, REVERSAL_TYPE, ACC_DIRECT_ACTUAL, ACC_ORIGINAL_ACCRUAL, ACC_UNDER_ACCRUAL, 
    ACC_OVER_ACCRUAL, ALLOW_ACCRUAL_ON_SALES, ALLOW_ACCRUAL_ON_PURCHASES, INC_EXP, INTEREST_CAL_REQ, 
    DISPLAY_ORDER, VERSION, IS_ACTIVE, IS_DELETED, SERVICE_CHARGE_SUB_TYPE_ID)
 Values
   ('SCM-15', 'GCD-1', 'Premium', 'Premium', NULL, 
    NULL, 'OTHER_CHARGES', 'CGM-7', 'N', 'N', 
    'Y', 'CONTRACT', 'N', 'Y', 'N', 
    'N', 'Y', 'Y', 'Expense', 'N', 
    16, NULL, 'Y', 'N', 'OTHER_CHARGES');
            
    Insert into SCM_SERVICE_CHARGE_MASTER
   (COST_ID, GROUP_ID, COST_COMPONENT_NAME, COST_DISPLAY_NAME, QUOTATION_TYPE_ID, 
    QUOTATION_SUB_TYPE_ID, COST_TYPE, COST_GROUP_ID, IS_AUTO_ACCRUAL, IS_CONTRACT_ACCRUAL_POSSIBLE, 
    IS_GENERAL_ACCRUAL_POSSIBLE, REVERSAL_TYPE, ACC_DIRECT_ACTUAL, ACC_ORIGINAL_ACCRUAL, ACC_UNDER_ACCRUAL, 
    ACC_OVER_ACCRUAL, ALLOW_ACCRUAL_ON_SALES, ALLOW_ACCRUAL_ON_PURCHASES, INC_EXP, INTEREST_CAL_REQ, 
    DISPLAY_ORDER, VERSION, IS_ACTIVE, IS_DELETED, SERVICE_CHARGE_SUB_TYPE_ID)
 Values
   ('SCM-16', 'GCD-1', 'Shredding Charges', 'Shredding Charges', NULL, 
    NULL, 'OTHER_CHARGES', 'CGM-7', 'N', 'N', 
    'Y', 'CONTRACT', 'N', 'Y', 'N', 
    'N', 'Y', 'Y', 'Expense', 'N', 
    17, NULL, 'Y', 'N', 'OTHER_CHARGES');
            
    Insert into SCM_SERVICE_CHARGE_MASTER
   (COST_ID, GROUP_ID, COST_COMPONENT_NAME, COST_DISPLAY_NAME, QUOTATION_TYPE_ID, 
    QUOTATION_SUB_TYPE_ID, COST_TYPE, COST_GROUP_ID, IS_AUTO_ACCRUAL, IS_CONTRACT_ACCRUAL_POSSIBLE, 
    IS_GENERAL_ACCRUAL_POSSIBLE, REVERSAL_TYPE, ACC_DIRECT_ACTUAL, ACC_ORIGINAL_ACCRUAL, ACC_UNDER_ACCRUAL, 
    ACC_OVER_ACCRUAL, ALLOW_ACCRUAL_ON_SALES, ALLOW_ACCRUAL_ON_PURCHASES, INC_EXP, INTEREST_CAL_REQ, 
    DISPLAY_ORDER, VERSION, IS_ACTIVE, IS_DELETED, SERVICE_CHARGE_SUB_TYPE_ID)
 Values
   ('SCM-17', 'GCD-1', 'Sieving Charges', 'Sieving Charges', NULL, 
    NULL, 'OTHER_CHARGES', 'CGM-7', 'N', 'N', 
    'Y', 'CONTRACT', 'N', 'Y', 'N', 
    'N', 'Y', 'Y', 'Expense', 'N', 
    18, NULL, 'Y', 'N', 'OTHER_CHARGES');
            
    Insert into SCM_SERVICE_CHARGE_MASTER
   (COST_ID, GROUP_ID, COST_COMPONENT_NAME, COST_DISPLAY_NAME, QUOTATION_TYPE_ID, 
    QUOTATION_SUB_TYPE_ID, COST_TYPE, COST_GROUP_ID, IS_AUTO_ACCRUAL, IS_CONTRACT_ACCRUAL_POSSIBLE, 
    IS_GENERAL_ACCRUAL_POSSIBLE, REVERSAL_TYPE, ACC_DIRECT_ACTUAL, ACC_ORIGINAL_ACCRUAL, ACC_UNDER_ACCRUAL, 
    ACC_OVER_ACCRUAL, ALLOW_ACCRUAL_ON_SALES, ALLOW_ACCRUAL_ON_PURCHASES, INC_EXP, INTEREST_CAL_REQ, 
    DISPLAY_ORDER, VERSION, IS_ACTIVE, IS_DELETED, SERVICE_CHARGE_SUB_TYPE_ID)
 Values
   ('SCM-18', 'GCD-1', 'Cutting Charges', 'Cutting Charges', NULL, 
    NULL, 'OTHER_CHARGES', 'CGM-7', 'N', 'N', 
    'Y', 'CONTRACT', 'N', 'Y', 'N', 
    'N', 'Y', 'Y', 'Expense', 'N', 
    19, NULL, 'Y', 'N', 'OTHER_CHARGES');
            
    Insert into SCM_SERVICE_CHARGE_MASTER
   (COST_ID, GROUP_ID, COST_COMPONENT_NAME, COST_DISPLAY_NAME, QUOTATION_TYPE_ID, 
    QUOTATION_SUB_TYPE_ID, COST_TYPE, COST_GROUP_ID, IS_AUTO_ACCRUAL, IS_CONTRACT_ACCRUAL_POSSIBLE, 
    IS_GENERAL_ACCRUAL_POSSIBLE, REVERSAL_TYPE, ACC_DIRECT_ACTUAL, ACC_ORIGINAL_ACCRUAL, ACC_UNDER_ACCRUAL, 
    ACC_OVER_ACCRUAL, ALLOW_ACCRUAL_ON_SALES, ALLOW_ACCRUAL_ON_PURCHASES, INC_EXP, INTEREST_CAL_REQ, 
    DISPLAY_ORDER, VERSION, IS_ACTIVE, IS_DELETED, SERVICE_CHARGE_SUB_TYPE_ID)
 Values
   ('SCM-19', 'GCD-1', 'Charge to Unadvised Material', 'Charge to Unadvised Material', NULL, 
    NULL, 'OTHER_CHARGES', 'CGM-7', 'N', 'N', 
    'Y', 'CONTRACT', 'N', 'Y', 'N', 
    'N', 'Y', 'Y', 'Expense', 'N', 
    20, NULL, 'Y', 'N', 'OTHER_CHARGES');
            
    Insert into SCM_SERVICE_CHARGE_MASTER
   (COST_ID, GROUP_ID, COST_COMPONENT_NAME, COST_DISPLAY_NAME, QUOTATION_TYPE_ID, 
    QUOTATION_SUB_TYPE_ID, COST_TYPE, COST_GROUP_ID, IS_AUTO_ACCRUAL, IS_CONTRACT_ACCRUAL_POSSIBLE, 
    IS_GENERAL_ACCRUAL_POSSIBLE, REVERSAL_TYPE, ACC_DIRECT_ACTUAL, ACC_ORIGINAL_ACCRUAL, ACC_UNDER_ACCRUAL, 
    ACC_OVER_ACCRUAL, ALLOW_ACCRUAL_ON_SALES, ALLOW_ACCRUAL_ON_PURCHASES, INC_EXP, INTEREST_CAL_REQ, 
    DISPLAY_ORDER, VERSION, IS_ACTIVE, IS_DELETED, SERVICE_CHARGE_SUB_TYPE_ID)
 Values
   ('SCM-20', 'GCD-1', 'Other "Free Text Charge"', 'Other "Free Text Charge"', NULL, 
    NULL, 'OTHER_CHARGES', 'CGM-7', 'N', 'N', 
    'Y', 'CONTRACT', 'N', 'Y', 'N', 
    'N', 'Y', 'Y', 'Expense', 'N', 
    21, NULL, 'Y', 'N', 'OTHER_CHARGES');
            
    Insert into SCM_SERVICE_CHARGE_MASTER
   (COST_ID, GROUP_ID, COST_COMPONENT_NAME, COST_DISPLAY_NAME, QUOTATION_TYPE_ID, 
    QUOTATION_SUB_TYPE_ID, COST_TYPE, COST_GROUP_ID, IS_AUTO_ACCRUAL, IS_CONTRACT_ACCRUAL_POSSIBLE, 
    IS_GENERAL_ACCRUAL_POSSIBLE, REVERSAL_TYPE, ACC_DIRECT_ACTUAL, ACC_ORIGINAL_ACCRUAL, ACC_UNDER_ACCRUAL, 
    ACC_OVER_ACCRUAL, ALLOW_ACCRUAL_ON_SALES, ALLOW_ACCRUAL_ON_PURCHASES, INC_EXP, INTEREST_CAL_REQ, 
    DISPLAY_ORDER, VERSION, IS_ACTIVE, IS_DELETED, SERVICE_CHARGE_SUB_TYPE_ID)
 Values
   ('SCM-21', 'GCD-1', 'Laytime Demurrage/Despatch Amounts', 'Laytime Demurrage/Despatch Amounts', NULL, 
    NULL, 'OTHER_CHARGES', 'CGM-7', 'N', 'N', 
    'Y', 'CONTRACT', 'N', 'Y', 'N', 
    'N', 'Y', 'Y', 'Expense', 'N', 
    22, NULL, 'Y', 'N', 'OTHER_CHARGES');
            
    Insert into SCM_SERVICE_CHARGE_MASTER
   (COST_ID, GROUP_ID, COST_COMPONENT_NAME, COST_DISPLAY_NAME, QUOTATION_TYPE_ID, 
    QUOTATION_SUB_TYPE_ID, COST_TYPE, COST_GROUP_ID, IS_AUTO_ACCRUAL, IS_CONTRACT_ACCRUAL_POSSIBLE, 
    IS_GENERAL_ACCRUAL_POSSIBLE, REVERSAL_TYPE, ACC_DIRECT_ACTUAL, ACC_ORIGINAL_ACCRUAL, ACC_UNDER_ACCRUAL, 
    ACC_OVER_ACCRUAL, ALLOW_ACCRUAL_ON_SALES, ALLOW_ACCRUAL_ON_PURCHASES, INC_EXP, INTEREST_CAL_REQ, 
    DISPLAY_ORDER, VERSION, IS_ACTIVE, IS_DELETED, SERVICE_CHARGE_SUB_TYPE_ID)
 Values
   ('SCM-22', 'GCD-1', 'Ocular Inspection Charge', 'Ocular Inspection Charge', NULL, 
    NULL, 'OTHER_CHARGES', 'CGM-7', 'N', 'N', 
    'Y', 'CONTRACT', 'N', 'Y', 'N', 
    'N', 'Y', 'Y', 'Expense', 'N', 
    23, NULL, 'Y', 'N', 'OTHER_CHARGES');
            
    Insert into SCM_SERVICE_CHARGE_MASTER
   (COST_ID, GROUP_ID, COST_COMPONENT_NAME, COST_DISPLAY_NAME, QUOTATION_TYPE_ID, 
    QUOTATION_SUB_TYPE_ID, COST_TYPE, COST_GROUP_ID, IS_AUTO_ACCRUAL, IS_CONTRACT_ACCRUAL_POSSIBLE, 
    IS_GENERAL_ACCRUAL_POSSIBLE, REVERSAL_TYPE, ACC_DIRECT_ACTUAL, ACC_ORIGINAL_ACCRUAL, ACC_UNDER_ACCRUAL, 
    ACC_OVER_ACCRUAL, ALLOW_ACCRUAL_ON_SALES, ALLOW_ACCRUAL_ON_PURCHASES, INC_EXP, INTEREST_CAL_REQ, 
    DISPLAY_ORDER, VERSION, IS_ACTIVE, IS_DELETED, SERVICE_CHARGE_SUB_TYPE_ID)
 Values
   ('SCM-23', 'GCD-1', 'Crushing (Fragmentation) Charge', 'Crushing (Fragmentation) Charge', NULL, 
    NULL, 'OTHER_CHARGES', 'CGM-7', 'N', 'N', 
    'Y', 'CONTRACT', 'N', 'Y', 'N', 
    'N', 'Y', 'Y', 'Expense', 'N', 
    24, NULL, 'Y', 'N', 'OTHER_CHARGES');
            
    Insert into SCM_SERVICE_CHARGE_MASTER
   (COST_ID, GROUP_ID, COST_COMPONENT_NAME, COST_DISPLAY_NAME, QUOTATION_TYPE_ID, 
    QUOTATION_SUB_TYPE_ID, COST_TYPE, COST_GROUP_ID, IS_AUTO_ACCRUAL, IS_CONTRACT_ACCRUAL_POSSIBLE, 
    IS_GENERAL_ACCRUAL_POSSIBLE, REVERSAL_TYPE, ACC_DIRECT_ACTUAL, ACC_ORIGINAL_ACCRUAL, ACC_UNDER_ACCRUAL, 
    ACC_OVER_ACCRUAL, ALLOW_ACCRUAL_ON_SALES, ALLOW_ACCRUAL_ON_PURCHASES, INC_EXP, INTEREST_CAL_REQ, 
    DISPLAY_ORDER, VERSION, IS_ACTIVE, IS_DELETED, SERVICE_CHARGE_SUB_TYPE_ID)
 Values
   ('SCM-24', 'GCD-1', 'AssayCharge', 'Assay Charge', NULL, 
    NULL, 'OTHER_CHARGES', 'CGM-7', 'N', 'N', 
    'Y', 'CONTRACT', 'N', 'Y', 'N', 
    'N', 'Y', 'Y', 'Expense', 'N', 
    25, NULL, 'Y', 'N', 'OTHER_CHARGES');