SET DEFINE OFF;
Insert into GM_GRID_MASTER
   (GRID_ID, GRID_NAME, DEFAULT_COLUMN_MODEL_STATE, TAB_ID, URL, 
    DEFAULT_RECORD_MODEL_STATE, OTHER_URL, SCREEN_SPECIFIC_JSP, SCREEN_SPECIFIC_JS)
 Values
   ('MLOCI', 'List Of Mining Contracts Items', '[{"dataIndex":"","fixed":true,"header":"<div class=\"x-grid3-hd-checker\">&#160;</div>","hideable":false,"id":"checker","sortable":false,"width":20},{"dataIndex":"contractNo","header":"Contract Ref. No","id":1,"sortable":true,"width":150},{"dataIndex":"contractType","header":"Contract Type","id":2,"sortable":true,"width":150},{"dataIndex":"counterParty","header":"CP Name","id":3,"sortable":true,"width":150},{"dataIndex":"partnershipType","header":"Execution Type","id":4,"sortable":true,"width":150},{"dataIndex":"tradeType","header":"Product Group Type","id":5,"sortable":true,"width":150},{"dataIndex":"itemStatus","header":"Item Status","id":6,"sortable":true,"width":150},{"dataIndex":"deliveryRefNo","header":"Delivery Ref. No.","id":7,"sortable":true,"width":150},{"dataIndex":"itemRefNo","header":"Item Ref. No.","id":8,"sortable":true,"width":150},{"dataIndex":"product","header":"Product","id":9,"sortable":true,"width":150},{"dataIndex":"quality","header":"Quality","id":10,"sortable":true,"width":150},{"dataIndex":"issueDate","header":"Issue Date","id":11,"sortable":true,"width":150},{"dataIndex":"quotaMonth","header":"Quota Period","id":12,"sortable":true,"width":150},{"dataIndex":"location","header":"Location","id":13,"sortable":true,"width":150},{"dataIndex":"traxysOrg","header":"Org","id":14,"sortable":true,"width":150},{"dataIndex":"incotermLocation","header":"INCO Term & Location","id":15,"sortable":true,"width":150},{"dataIndex":"qty","header":"Item Quantity","id":16,"sortable":true,"width":150},{"dataIndex":"openQty","header":"Open Qty.","id":17,"sortable":true,"width":150},{"dataIndex":"allocatedQty","header":"Allocated Qty.","id":18,"sortable":true,"width":150},{"dataIndex":"incoterm","header":"Incoterm","id":19,"sortable":true,"width":150},{"dataIndex":"strategy","header":"Strategy","id":20,"sortable":true,"width":150},{"dataIndex":"bookProfitCenter","header":"Book/Profit Center","id":21,"sortable":true,"width":150},{"dataIndex":"trader","header":"Trader","id":22,"sortable":true,"width":150},{"dataIndex":"pricing","header":"Pricing","id":23,"sortable":true,"width":150},{"dataIndex":"executedQty","header":"Executed Quantity","id":24,"sortable":true,"width":150},{"dataIndex":"titleTransferQty","header":"Title Transfer Quantity","id":25,"sortable":true,"width":150},{"dataIndex":"provInvoicedQty","header":"Prov. Invoiced Quantity","id":26,"sortable":true,"width":150},{"dataIndex":"finalInvoicedQty","header":"Final Invoiced Quantity","id":27,"sortable":true,"width":150},{"dataIndex":"payInCurrency","header":"Pay-In Currency","id":28,"sortable":true,"width":150},{"dataIndex":"payableContent","header":"Payable Content","id":29,"sortable":true,"width":150},{"dataIndex":"origin","header":"Origin","id":30,"sortable":true,"width":150}]', NULL, '/metals/loadListOfMiningContracts.action', 
    '[ 
                                {name: "contractNo", mapping: "contractNo"}, 
                                {name: "contractType", mapping: "contractType"}, 
                                {name: "counterParty", mapping: "counterParty"},
                                {name: "tradeType", mapping: "tradeType"},
                                {name: "allocationStatus", mapping: "allocationStatus"},
                                {name: "itemStatus", mapping: "itemStatus"},
                                {name: "deliveryRefNo", mapping: "deliveryRefNo"},
                                {name: "itemRefNo", mapping: "itemRefNo"},
                                {name: "internalContractItemRefNo", mapping: "internalContractItemRefNo"},
                                {name: "internalContractRefNo", mapping: "internalContractRefNo"},
                                {name: "product", mapping: "product"},
                                {name: "quality", mapping: "quality"},
                                {name: "attributes", mapping: "attributes"},
                                {name: "issueDate", mapping: "issueDate"},
                                {name: "quotaMonth", mapping: "quotaMonth"},
                                {name: "location", mapping: "location"},
                                {name: "traxysOrg", mapping: "traxysOrg"},
                                {name: "incotermLocation", mapping: "incotermLocation"},
                                {name: "pricing", mapping: "pricing"},
                                {name: "qp", mapping: "qp"},
                                {name: "qty", mapping: "qty"},
                                {name: "openQty", mapping: "openQty"},
                                {name: "qtyBasis", mapping: "qtyBasis"},
                                {name: "allocatedQty", mapping: "allocatedQty"},
                                {name: "partnershipType", mapping: "partnershipType"},
                                {name: "incoterm", mapping: "incoterm"},
                                {name: "pcdiId", mapping: "pcdiId"},
                                {name: "strategy", mapping: "strategy"},
                                {name: "bookProfitCenter", mapping: "bookProfitCenter"},
                                {name: "trader", mapping: "trader"},
                                {name: "pricing", mapping: "pricing"},
                                {name: "executedQty", mapping: "executedQty"},
                                {name: "titleTransferQty", mapping: "titleTransferQty"},
                                {name: "provInvoicedQty", mapping: "provInvoicedQty"},
                                {name: "finalInvoicedQty", mapping: "finalInvoicedQty"},
                                {name: "payInCurrency", mapping: "payInCurrency"},
                                {name: "payableContent", mapping: "payableContent"},
                                {name: "origin", mapping: "origin"}
                               ]', NULL, 'mining/physical/listing/ListOfMiningContractItems.jsp', '/private/js/mining/physical/listing/listOfMiningContractItems.js');
COMMIT;