
Insert into AXM_ACTION_MASTER
   (ACTION_ID, ENTITY_ID, ACTION_NAME, IS_NEW_GMR_APPLICABLE, ACTION_DESC, 
    IS_GENERATE_DOC_APPLICABLE, IS_REF_NO_GEN_APPLICABLE)
 Values
   ('CANCEL_SPL_SETTLEMENT', 'GMR', 'Cancel Special Settlement', 'Y', 'Cancel Special Settlement GMR', 
    'N', NULL);


Insert into CAC_CORPORATE_ACTION_CONFIG
   (ACTION_ID, IS_ACCRUAL_POSSIBLE, IS_ESTIMATE_POSSIBLE, EFF_DATE_FIELD, IS_DOC_APPLICABLE, 
    GMR_STATUS_ID, SHIPMENT_STATUS, IS_AFLOAT, IS_INV_POSTING_REQD)
 Values
   ('CANCEL_SPL_SETTLEMENT', 'N', 'N', 'activityDate', 'N', 
    NULL, NULL, 'N', 'N');


alter table PQCA_PQ_CHEMICAL_ATTRIBUTES add IS_ELMNT_PART_OF_CTRCT_ASSAY char(1) default 'N';

Insert into GMC_GRID_MENU_CONFIGURATION
   (MENU_ID, GRID_ID, MENU_DISPLAY_NAME, DISPLAY_SEQ_NO, MENU_LEVEL_NO, 
    FEATURE_ID, LINK_CALLED, ICON_CLASS, MENU_PARENT_ID, ACL_ID)
 Values
   ('MTGMR_LIST_5', 'MTGMR_LIST', 'Price Allocation And Finalization', 5, 2, 
    NULL, 'function(){loadMFTGmrDataforSpeedPricing();}', NULL, 'MTGMR_LIST_1', NULL);