update DGM_DOCUMENT_GENERATION_MASTER dgm set DGM.FETCH_QUERY = 'INSERT INTO IS_CHILD_D(
INTERNAL_INVOICE_REF_NO,
GMR_REF_NO,
GMR_QUANTITY,
GMR_QUALITY,
PRICE_AS_PER_DEFIND_UOM,
TOTAL_PRICE_QTY,
GMR_QTY_UNIT,
INVOICED_QTY_UNIT,
INVOICED_PRICE_UNIT,
STOCK_REF_NO,
STOCK_QTY,
FX_RATE,
ITEM_AMOUNT_IN_INV_CUR,
INTERNAL_DOC_REF_NO
)
select
INVS.INTERNAL_INVOICE_REF_NO as INTERNAL_INVOICE_REF_NO,
GMR.GMR_REF_NO as GMR_REF_NO,
GMR.QTY as GMR_QUANTITY,
nvl(QAT.QUALITY_NAME, QAT1.QUALITY_NAME) as GMR_QUALITY,
IID.NEW_INVOICE_PRICE as PRICE_AS_PER_DEFIND_UOM,
IID.INVOICED_QTY as TOTAL_PRICE_QTY,
QUM.QTY_UNIT as GMR_QTY_UNIT,
QUMINV.QTY_UNIT as INVOICED_QTY_UNIT,
PUM.PRICE_UNIT_NAME as INVOICED_PRICE_UNIT,
nvl(GRD.INTERNAL_STOCK_REF_NO, DGRD.INTERNAL_STOCK_REF_NO) as STOCK_REF_NO,
IID.INVOICED_QTY as STOCK_QTY,
IID.FX_RATE as FX_RATE,
IID.INVOICE_ITEM_AMOUNT as ITEM_AMOUNT_IN_INV_CUR,
?
from
IS_INVOICE_SUMMARY invs,
IID_INVOICABLE_ITEM_DETAILS iid,
GMR_GOODS_MOVEMENT_RECORD gmr,
QUM_QUANTITY_UNIT_MASTER qum,
QUM_QUANTITY_UNIT_MASTER quminv,
PPU_PRODUCT_PRICE_UNITS ppu,
PUM_PRICE_UNIT_MASTER pum,
GRD_GOODS_RECORD_DETAIL grd,
DGRD_DELIVERED_GRD dgrd,
QAT_QUALITY_ATTRIBUTES qat,
QAT_QUALITY_ATTRIBUTES qat1
where
INVS.INTERNAL_INVOICE_REF_NO = IID.INTERNAL_INVOICE_REF_NO(+)
and IID.INTERNAL_GMR_REF_NO = GMR.INTERNAL_GMR_REF_NO(+)
and GMR.QTY_UNIT_ID = QUM.QTY_UNIT_ID(+)
and IID.INVOICED_QTY_UNIT_ID = QUMINV.QTY_UNIT_ID(+)
and IID.NEW_INVOICE_PRICE_UNIT_ID = PPU.INTERNAL_PRICE_UNIT_ID(+)
and PPU.PRICE_UNIT_ID = PUM.PRICE_UNIT_ID(+)
and IID.STOCK_ID = GRD.INTERNAL_GRD_REF_NO(+)
and IID.STOCK_ID = DGRD.INTERNAL_DGRD_REF_NO(+)
and GRD.QUALITY_ID = QAT.QUALITY_ID(+)
and DGRD.QUALITY_ID = QAT1.QUALITY_ID(+)
and IID.INTERNAL_INVOICE_REF_NO = ?'
where
DGM.DOC_ID = 'CREATE_PI'
and DGM.DGM_ID='DGM-PI-C1';