Insert into SCST_SERVICE_CHARGE_SUB_TYPE
   (SERVICE_CHARGE_SUB_TYPE_ID, SERVICE_CHARGE_SUB_TYPE, DISPLAY_ORDER, VERSION, IS_ACTIVE, 
    IS_DELETED)
 Values
   ('OTHER_CHARGES', 'Other Charges', 6, NULL, 'Y', 
    'N');