ALTER TABLE PQDT_PAYABLE_EXT_TOLLING
RENAME COLUMN PQD_ID TO PCPCH_ID;

ALTER TABLE PQDT_PAYABLE_EXT_TOLLING DROP CONSTRAINT FK_PQDT_PQD_ID;

ALTER TABLE PQDT_PAYABLE_EXT_TOLLING ADD (
  CONSTRAINT FK_PQDT_PQD_ID 
 FOREIGN KEY (PCPCH_ID) 
 REFERENCES PCPCH_PC_PAYBLE_CONTENT_HEADER (PCPCH_ID));

UPDATE GMC_GRID_MENU_CONFIGURATION GMC SET GMC.LINK_CALLED='function(){modifyContract();}' WHERE GMC.MENU_ID='MIN_1_2';