CREATE TABLE PCBPH_PC_BASE_PRICE_HEADER
(
  PCBPH_ID                  VARCHAR2(15 BYTE)   NOT NULL,
  OPTIONALITY_DESC          VARCHAR2(4000 BYTE),
  VERSION                   NUMBER(10)          NOT NULL,
  IS_ACTIVE                 CHAR(1 BYTE)        DEFAULT 'Y'                   NOT NULL,
  INTERNAL_CONTRACT_REF_NO  VARCHAR2(15 BYTE)   NOT NULL
);


CREATE UNIQUE INDEX PK_PCBPH_ID ON PCBPH_PC_BASE_PRICE_HEADER
(PCBPH_ID);


ALTER TABLE PCBPH_PC_BASE_PRICE_HEADER ADD (
  CONSTRAINT PK_PCBPH_ID
 PRIMARY KEY
 (PCBPH_ID));

ALTER TABLE PCBPH_PC_BASE_PRICE_HEADER ADD (
  CONSTRAINT FK_PCBPH_PCM_ID 
 FOREIGN KEY (INTERNAL_CONTRACT_REF_NO) 
 REFERENCES PCM_PHYSICAL_CONTRACT_MAIN (INTERNAL_CONTRACT_REF_NO));


ALTER TABLE PFQPP_PHY_FORMULA_QP_PRICING
 ADD (EVENT_ID  VARCHAR2(15 BYTE));



ALTER TABLE PCBPD_PC_BASE_PRICE_DETAIL
 ADD (QTY_TO_BE_PRICED  NUMBER(10,4));



ALTER TABLE PCBPD_PC_BASE_PRICE_DETAIL ADD(PCBPH_ID VARCHAR(15 BYTE)); 

ALTER TABLE PCBPD_PC_BASE_PRICE_DETAIL
 ADD CONSTRAINT FK_PCBPD_PCBPH_ID 
 FOREIGN KEY (PCBPH_ID) REFERENCES PCBPH_PC_BASE_PRICE_HEADER(PCBPH_ID);  

ALTER TABLE PCBPD_PC_BASE_PRICE_DETAIL
 ADD (DESCRIPTION  VARCHAR2(4000 BYTE));



CREATE SEQUENCE SEQ_PCBPH
  START WITH 1
  MAXVALUE 1000000000000000000000000000
  MINVALUE 1
  NOCYCLE
  CACHE 20
  NOORDER;




alter table PCI_PHYSICAL_CONTRACT_ITEM
 modify DEL_DISTRIBUTION_ITEM_NO NUMBER(10,5);


drop table PCDIPE_DI_PRICING_ELEMENTS;

CREATE TABLE PCDIPE_DI_PRICING_ELEMENTS
(
  PCDIPE_ID  VARCHAR2(15 BYTE)                  NOT NULL,
  PCDI_ID    VARCHAR2(15 BYTE)                  NOT NULL,
  PCBPH_ID   VARCHAR2(15 BYTE)                  NOT NULL,  
  VERSION    NUMBER(10)                         NOT NULL,
  IS_ACTIVE  CHAR(1 BYTE)                       DEFAULT 'Y'                   NOT NULL
);


COMMENT ON COLUMN PCDIPE_DI_PRICING_ELEMENTS.PCBPH_ID IS 'Base Price elements';

CREATE UNIQUE INDEX PK_PCDIPE ON PCDIPE_DI_PRICING_ELEMENTS
(PCDIPE_ID);

ALTER TABLE PCDIPE_DI_PRICING_ELEMENTS ADD (
  CONSTRAINT PK_PCDIPE
 PRIMARY KEY
 (PCDIPE_ID));

ALTER TABLE PCDIPE_DI_PRICING_ELEMENTS ADD (
  CONSTRAINT FK_PCDIPE_PCDI_ID 
 FOREIGN KEY (PCDI_ID) 
 REFERENCES PCDI_PC_DELIVERY_ITEM (PCDI_ID));

 
 ALTER TABLE PCDIPE_DI_PRICING_ELEMENTS ADD (
  CONSTRAINT FK_PCDIPE_PCBPH_ID 
 FOREIGN KEY (PCBPH_ID) 
 REFERENCES PCBPH_PC_BASE_PRICE_HEADER (PCBPH_ID));


DROP TABLE PCIPF_PCI_PRICING_FORMULA ;

CREATE TABLE PCIPF_PCI_PRICING_FORMULA
(
  PCIPF_ID                       VARCHAR2(15 BYTE) NOT NULL,
  INTERNAL_CONTRACT_ITEM_REF_NO  VARCHAR2(15 BYTE) NOT NULL,
  PCBPH_ID                       VARCHAR2(15 BYTE) NOT NULL,
  VERSION                        NUMBER(10)     NOT NULL,
  IS_ACTIVE                      CHAR(1 BYTE)   DEFAULT 'Y'                   NOT NULL
);



CREATE UNIQUE INDEX PK_PCIPF_ID ON PCIPF_PCI_PRICING_FORMULA
(PCIPF_ID);

ALTER TABLE PCIPF_PCI_PRICING_FORMULA ADD (
  CONSTRAINT PK_PCIPF_ID
 PRIMARY KEY
 (PCIPF_ID));
 
 ALTER TABLE PCIPF_PCI_PRICING_FORMULA ADD (
  CONSTRAINT FK_PCIPF_PCBPH_ID 
 FOREIGN KEY (PCBPH_ID) 
 REFERENCES PCBPH_PC_BASE_PRICE_HEADER (PCBPH_ID),
  CONSTRAINT FK_PCIPF_PCI_ID 
 FOREIGN KEY (INTERNAL_CONTRACT_ITEM_REF_NO) 
 REFERENCES PCI_PHYSICAL_CONTRACT_ITEM (INTERNAL_CONTRACT_ITEM_REF_NO));

 alter table PCBPD_PC_BASE_PRICE_DETAIL drop column INTERNAL_CONTRACT_REF_NO ;


