Insert into CDC_CORPORATE_DOC_CONFIG
   (DOC_TEMPLATE_ID, CORPORATE_ID, DOC_ID, DOC_TEMPLATE_NAME, DOC_TEMPLATE_NAME_DE, 
    DOC_TEMPLATE_NAME_ES, DOC_PRINT_NAME, DOC_PRINT_NAME_DE, DOC_PRINT_NAME_ES, DOC_RPT_FILE_NAME, 
    IS_ACTIVE, DOC_AUTO_GENERATE)
 Values
   ('CDC-GEPD-3', 'BLD', 'pledgeTransfer', 'Pledge Letter', NULL, 
    NULL, NULL, NULL, NULL, 'PledgeLetterFormat.rpt', 
    'Y', 'Y');
    
Insert into DRF_DOC_REF_NUMBER_FORMAT
   (DOC_REF_NUMBER_FORMAT_ID, DOC_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('DRF-GEPD-3', 'GEPD_KEY_3', 'BLD', 'GEPD-', 0, 
    0, '-BLD', 1, 'N');
      
Insert into DRFM_DOC_REF_NO_MAPPING
   (DOC_REF_NO_MAPPING_ID, CORPORATE_ID, DOC_ID, DOC_KEY_ID, IS_DELETED)
 Values
   ('DRFM-GEPD-3', 'BLD', 'pledgeTransfer', 'GEPD_KEY_3', 'N');
       