Insert into DRF_DOC_REF_NUMBER_FORMAT
   (DOC_REF_NUMBER_FORMAT_ID, DOC_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('DRF-PFI-1', 'PFI_KEY_1', 'LDE', 'PFI-', 0, 
    0, '-LDE', 1, 'N');
    
Insert into DRF_DOC_REF_NUMBER_FORMAT
   (DOC_REF_NUMBER_FORMAT_ID, DOC_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('DRF-PFI-2', 'PFI_KEY_2', 'EKA', 'PFI-', 0, 
    0, '-EKA', 1, 'N');
      
Insert into DRFM_DOC_REF_NO_MAPPING
   (DOC_REF_NO_MAPPING_ID, CORPORATE_ID, DOC_ID, DOC_KEY_ID, IS_DELETED)
 Values
   ('DRFM-PFI-1', 'LDE', 'CREATE_PFI', 'PFI_KEY_1', 'N');
   
Insert into DRFM_DOC_REF_NO_MAPPING
   (DOC_REF_NO_MAPPING_ID, CORPORATE_ID, DOC_ID, DOC_KEY_ID, IS_DELETED)
 Values
   ('DRFM-PFI-2', 'EKA', 'CREATE_PFI', 'PFI_KEY_2', 'N');
   
Insert into CDC_CORPORATE_DOC_CONFIG
   (DOC_TEMPLATE_ID, CORPORATE_ID, DOC_ID, DOC_TEMPLATE_NAME, DOC_TEMPLATE_NAME_DE, 
    DOC_TEMPLATE_NAME_ES, DOC_PRINT_NAME, DOC_PRINT_NAME_DE, DOC_PRINT_NAME_ES, DOC_RPT_FILE_NAME, 
    IS_ACTIVE, DOC_AUTO_GENERATE)
 Values
   ('CDC-PFI-1', 'LDE', 'CREATE_PFI', 'Profoma', NULL, 
    NULL, NULL, NULL, NULL, 'ProfomaDocument.rpt', 
    'Y', 'Y');
    
Insert into CDC_CORPORATE_DOC_CONFIG
   (DOC_TEMPLATE_ID, CORPORATE_ID, DOC_ID, DOC_TEMPLATE_NAME, DOC_TEMPLATE_NAME_DE, 
    DOC_TEMPLATE_NAME_ES, DOC_PRINT_NAME, DOC_PRINT_NAME_DE, DOC_PRINT_NAME_ES, DOC_RPT_FILE_NAME, 
    IS_ACTIVE, DOC_AUTO_GENERATE)
 Values
   ('CDC-PFI-2', 'EKA', 'CREATE_PFI', 'Profoma', NULL, 
    NULL, NULL, NULL, NULL, 'ProfomaDocument.rpt', 
    'Y', 'Y');


Insert into DC_DOCUMENT_CONFIGURATION
   (ACTIVITY_ID, CORPORATE_ID, IS_GENERATE_DOC_REQD, IS_UPLOAD_DOC_REQD, DOC_VALIDATION_QUERY, 
    NAVIGATION)
 Values
   ('CREATE_PFI', 'LDE', 'Y', 'Y', 'select count(*) as countRow
from PFI_D isd
where isd.INTERNAL_DOC_REF_NO = ?', 
    '/metals/loadListOfInvoice.action?gridId=LOII_TEST');


Insert into DC_DOCUMENT_CONFIGURATION
   (ACTIVITY_ID, CORPORATE_ID, IS_GENERATE_DOC_REQD, IS_UPLOAD_DOC_REQD, DOC_VALIDATION_QUERY, 
    NAVIGATION)
 Values
   ('CREATE_PFI', 'EKA', 'Y', 'Y', 'select count(*) as countRow
from PFI_D isd
where isd.INTERNAL_DOC_REF_NO = ?', 
    '/metals/loadListOfInvoice.action?gridId=LOII_TEST');