Insert into CDC_CORPORATE_DOC_CONFIG
   (DOC_TEMPLATE_ID, CORPORATE_ID, DOC_ID, DOC_TEMPLATE_NAME, DOC_TEMPLATE_NAME_DE, 
    DOC_TEMPLATE_NAME_ES, DOC_PRINT_NAME, DOC_PRINT_NAME_DE, DOC_PRINT_NAME_ES, DOC_RPT_FILE_NAME, 
    IS_ACTIVE, DOC_AUTO_GENERATE)
 Values
   ('CDC-DFT-PI-1', '&corpId', 'CREATE_DFT_PI', 'Draft Provisional', NULL, 
    NULL, NULL, NULL, NULL, 'InvoiceDocument.rpt', 
    'Y', 'Y');


Insert into CDC_CORPORATE_DOC_CONFIG
   (DOC_TEMPLATE_ID, CORPORATE_ID, DOC_ID, DOC_TEMPLATE_NAME, DOC_TEMPLATE_NAME_DE, 
    DOC_TEMPLATE_NAME_ES, DOC_PRINT_NAME, DOC_PRINT_NAME_DE, DOC_PRINT_NAME_ES, DOC_RPT_FILE_NAME, 
    IS_ACTIVE, DOC_AUTO_GENERATE)
 Values
   ('CDC-DFT-FI-1', '&corpId', 'CREATE_DFT_FI', 'Draft Final', NULL, 
    NULL, NULL, NULL, NULL, 'InvoiceDocument.rpt', 
    'Y', 'Y');

Insert into CDC_CORPORATE_DOC_CONFIG
   (DOC_TEMPLATE_ID, CORPORATE_ID, DOC_ID, DOC_TEMPLATE_NAME, DOC_TEMPLATE_NAME_DE, 
    DOC_TEMPLATE_NAME_ES, DOC_PRINT_NAME, DOC_PRINT_NAME_DE, DOC_PRINT_NAME_ES, DOC_RPT_FILE_NAME, 
    IS_ACTIVE, DOC_AUTO_GENERATE)
 Values
   ('CDC-DFT-DFI-1', '&corpId', 'CREATE_DFT_DFI', 'Draft Test8', NULL, 
    NULL, NULL, NULL, NULL, 'InvoiceDocument.rpt', 
    'Y', 'Y');


Insert into CDC_CORPORATE_DOC_CONFIG
   (DOC_TEMPLATE_ID, CORPORATE_ID, DOC_ID, DOC_TEMPLATE_NAME, DOC_TEMPLATE_NAME_DE, 
    DOC_TEMPLATE_NAME_ES, DOC_PRINT_NAME, DOC_PRINT_NAME_DE, DOC_PRINT_NAME_ES, DOC_RPT_FILE_NAME, 
    IS_ACTIVE, DOC_AUTO_GENERATE)
 Values
   ('CDC-DFT-API-1', '&corpId', 'CREATE_DFT_API', 'Draft Advance', NULL, 
    NULL, NULL, NULL, NULL, 'AdvancePaymentDocument.rpt', 
    'Y', 'Y');


Insert into CDC_CORPORATE_DOC_CONFIG
   (DOC_TEMPLATE_ID, CORPORATE_ID, DOC_ID, DOC_TEMPLATE_NAME, DOC_TEMPLATE_NAME_DE, 
    DOC_TEMPLATE_NAME_ES, DOC_PRINT_NAME, DOC_PRINT_NAME_DE, DOC_PRINT_NAME_ES, DOC_RPT_FILE_NAME, 
    IS_ACTIVE, DOC_AUTO_GENERATE)
 Values
   ('CDC-DFT-VAT-1', '&corpId', 'CREATE_DFT_VAT', 'Draft Vat', NULL, 
    NULL, NULL, NULL, NULL, 'VatDocument.rpt', 
    'Y', 'Y');

Insert into DRFM_DOC_REF_NO_MAPPING
   (DOC_REF_NO_MAPPING_ID, CORPORATE_ID, DOC_ID, DOC_KEY_ID, IS_DELETED)
 Values
   ('DRFM-DFT-DC-&corpId', '&corpId', 'CREATE_DFT_DC', 'DFT-DC', 'N');

Insert into DRF_DOC_REF_NUMBER_FORMAT
   (DOC_REF_NUMBER_FORMAT_ID, DOC_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('DRF-DFT-DC-&corpId', 'DFT-DC', '&corpId', 'DFT-DC-', 0, 
    0, '-&corpId', 1, 'N');
    
    Insert into CDC_CORPORATE_DOC_CONFIG
   (DOC_TEMPLATE_ID, CORPORATE_ID, DOC_ID, DOC_TEMPLATE_NAME, DOC_TEMPLATE_NAME_DE, 
    DOC_TEMPLATE_NAME_ES, DOC_PRINT_NAME, DOC_PRINT_NAME_DE, DOC_PRINT_NAME_ES, DOC_RPT_FILE_NAME, 
    IS_ACTIVE, DOC_AUTO_GENERATE)
 Values
   ('CDC-DFT-DC-1', '&corpId', 'CREATE_DFT_DC', 'Draft Debit Credit Note', NULL, 
    NULL, NULL, NULL, NULL, 'PurchaseCreditNote.rpt', 
    'Y', 'Y');

Insert into DRFM_DOC_REF_NO_MAPPING
   (DOC_REF_NO_MAPPING_ID, CORPORATE_ID, DOC_ID, DOC_KEY_ID, IS_DELETED)
 Values
   ('DRFM-DFT-SI-&corpId', '&corpId', 'CREATE_DFT_SI', 'DFT-SI', 'N');

Insert into DRF_DOC_REF_NUMBER_FORMAT
   (DOC_REF_NUMBER_FORMAT_ID, DOC_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('DRF-DFT-SI-&corpId', 'DFT-SI', '&corpId', 'DFT-SI-', 0, 
    0, '-&corpId', 1, 'N');
    
    Insert into CDC_CORPORATE_DOC_CONFIG
   (DOC_TEMPLATE_ID, CORPORATE_ID, DOC_ID, DOC_TEMPLATE_NAME, DOC_TEMPLATE_NAME_DE, 
    DOC_TEMPLATE_NAME_ES, DOC_PRINT_NAME, DOC_PRINT_NAME_DE, DOC_PRINT_NAME_ES, DOC_RPT_FILE_NAME, 
    IS_ACTIVE, DOC_AUTO_GENERATE)
 Values
   ('CDC-DFT-SI-1', '&corpId', 'CREATE_DFT_SI', 'Draft Service Invoice', NULL, 
    NULL, NULL, NULL, NULL, 'ServiceInvoice.rpt', 
    'Y', 'Y');


delete from DC_DOCUMENT_CONFIGURATION where ACTIVITY_ID='DGM-DFT-FI';

Insert into DC_DOCUMENT_CONFIGURATION
   (ACTIVITY_ID, CORPORATE_ID, IS_GENERATE_DOC_REQD, IS_UPLOAD_DOC_REQD, DOC_VALIDATION_QUERY, 
    NAVIGATION)
 Values
   ('CREATE_DFT_FI', '&corpId', 'Y', 'Y', 'select count(*) as countRow
from IS_D isd
where isd.INTERNAL_DOC_REF_NO = ?', 
    '/metals/loadListOfInvoiceDraft.action?gridId=LOID');

