delete from RPC_RF_PARAMETER_CONFIG where report_id in('54','59','58');
delete from RFC_REPORT_FILTER_CONFIG where report_id in('54','59','58');
delete from RPC_RF_PARAMETER_CONFIG where report_id in('103','104');
delete from RFC_REPORT_FILTER_CONFIG where report_id in('103','104');
delete from RPC_RF_PARAMETER_CONFIG where report_id in('52');
delete from RFC_REPORT_FILTER_CONFIG where report_id in('52');
delete from RPC_RF_PARAMETER_CONFIG where report_id in('53');
delete from RFC_REPORT_FILTER_CONFIG where report_id in('53');
commit;

SET DEFINE OFF;
--daily derivative report 
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '54', 'RFC-CDC-541', 1, 1,'Created Date', 'GFF021', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '54', 'RFC-CDC-542', 1, 2,'Profit Center', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '54', 'RFC-CDC-543', 1, 3,'Exchange ', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '54', 'RFC-CDC-545', 1, 4,'Strategy', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '54', 'RFC-CDC-546', 1, 5,'Trade Type', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '54', 'RFC-CDC-547', 1, 6,'Purpose', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '54', 'RFC-CDC-548', 1, 7,'Nominee', 'GFF1011', 1, 'N');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-541', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-541', 'RFP0026', 'AsOfDate');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-542', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-542', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-542', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-542', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-542', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-542', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-542', 'RFP1051', 'multiple');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-543', 'RFP1045', 'exchangelist');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-543', 'RFP1046', 'Exchange');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-543', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-543', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-543', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-543', 'RFP1050', '1');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-545', 'RFP1045', 'strategyDefinition');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-545', 'RFP1046', 'Strategy');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-545', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-545', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-545', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '54', 'RFC-CDC-545', 'RFP1050', '1');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '54', 'RFC-CDC-546', 'RFP1045', 'tradeTypeByMasterContract');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '54', 'RFC-CDC-546', 'RFP1046', 'TradeType');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-546', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-546', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '54', 'RFC-CDC-546', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '54', 'RFC-CDC-546', 'RFP1050', '1');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '54', 'RFC-CDC-547', 'RFP1045', 'setupDerivativeTradePurpose');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '54', 'RFC-CDC-547', 'RFP1046', 'Purpose');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '54', 'RFC-CDC-547', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '54', 'RFC-CDC-547', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '54', 'RFC-CDC-547', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-547', 'RFP1050', '1');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '54', 'RFC-CDC-548', 'RFP1045', 'corporatebusinesspartner');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '54', 'RFC-CDC-548', 'RFP1046', 'Nominee');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '54', 'RFC-CDC-548', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '54', 'RFC-CDC-548', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '54', 'RFC-CDC-548', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '54', 'RFC-CDC-548', 'RFP1050', '1');
--COMMIT;

---Daily Derivative unrealized pnl reports

Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '59', 'RFC-CDC-591', 1, 1,'EOD Date', 'GFF021', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '59', 'RFC-CDC-592', 1, 2,'Profit Center', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '59', 'RFC-CDC-593', 1, 3,'Exchange ', 'GFF1011', 1, 'N');
 
--
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '59', 'RFC-CDC-591', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '59', 'RFC-CDC-591', 'RFP0026', 'AsOfDate');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '59', 'RFC-CDC-592', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '59', 'RFC-CDC-592', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '59', 'RFC-CDC-592', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '59', 'RFC-CDC-592', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '59', 'RFC-CDC-592', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '59', 'RFC-CDC-592', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '59', 'RFC-CDC-592', 'RFP1051', 'multiple');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '59', 'RFC-CDC-593', 'RFP1045', 'exchangelist');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '59', 'RFC-CDC-593', 'RFP1046', 'Exchange');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '59', 'RFC-CDC-593', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '59', 'RFC-CDC-593', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '59', 'RFC-CDC-593', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '59', 'RFC-CDC-593', 'RFP1050', '1');
---

---Daily Derivative Realized pnl reports

Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '58', 'RFC-CDC-581', 1, 1,'EOD Date', 'GFF021', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '58', 'RFC-CDC-582', 1, 2,'Profit Center', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '58', 'RFC-CDC-583', 1, 3,'Exchange ', 'GFF1011', 1, 'N');
 
--
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '58', 'RFC-CDC-581', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '58', 'RFC-CDC-581', 'RFP0026', 'AsOfDate');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '58', 'RFC-CDC-582', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '58', 'RFC-CDC-582', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '58', 'RFC-CDC-582', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '58', 'RFC-CDC-582', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '58', 'RFC-CDC-582', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '58', 'RFC-CDC-582', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '58', 'RFC-CDC-582', 'RFP1051', 'multiple');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '58', 'RFC-CDC-583', 'RFP1045', 'exchangelist');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '58', 'RFC-CDC-583', 'RFP1046', 'Exchange');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '58', 'RFC-CDC-583', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '58', 'RFC-CDC-583', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '58', 'RFC-CDC-583', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '58', 'RFC-CDC-583', 'RFP1050', '1');
---

--DerivativePNLAttributionReport.rpt
--Report ID: 103
--AsOfDate

Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '103', 'RFC-CDC-1031', 1, 1,'EOD Date', 'GFF021', 1, 'Y');
 
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '103', 'RFC-CDC-1031', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '103', 'RFC-CDC-1031', 'RFP0026', 'AsOfDate');
--
--DailyClearerSummaryReport Report ID: 104 Parameter List:
-- AsOfDate  -- ClearerName

Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '104', 'RFC-CDC-1041', 1, 1,'EOD Date', 'GFF021', 1, 'Y');
 
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '104', 'RFC-CDC-1041', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '104', 'RFC-CDC-1041', 'RFP0026', 'AsOfDate');

--FutureOptionSummaryPositionReport Report ID:52
--Parameter: AsOfDate Book	Exchange	Purpose.

Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '52', 'RFC-CDC-521', 1, 1,'EOD Date', 'GFF021', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '52', 'RFC-CDC-522', 1, 2,'Profit Center', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '52', 'RFC-CDC-523', 1, 3,'Exchange ', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '52', 'RFC-CDC-524', 1, 4,'Purpose', 'GFF1011', 1, 'N');


Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '52', 'RFC-CDC-521', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '52', 'RFC-CDC-521', 'RFP0026', 'AsOfDate');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '52', 'RFC-CDC-522', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '52', 'RFC-CDC-522', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '52', 'RFC-CDC-522', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '52', 'RFC-CDC-522', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '52', 'RFC-CDC-522', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '52', 'RFC-CDC-522', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '52', 'RFC-CDC-522', 'RFP1051', 'multiple');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '52', 'RFC-CDC-523', 'RFP1045', 'exchangelist');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '52', 'RFC-CDC-523', 'RFP1046', 'Exchange');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '52', 'RFC-CDC-523', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '52', 'RFC-CDC-523', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '52', 'RFC-CDC-523', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '52', 'RFC-CDC-523', 'RFP1050', '1');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '52', 'RFC-CDC-524', 'RFP1045', 'setupDerivativeTradePurpose');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '52', 'RFC-CDC-524', 'RFP1046', 'Purpose');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '52', 'RFC-CDC-524', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '52', 'RFC-CDC-524', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '52', 'RFC-CDC-524', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '52', 'RFC-CDC-524', 'RFP1050', '1');
--
--Margin Report: Report ID : 53
--Parameter: AsOfDate  CorporateID  Book Exchange
--
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '53', 'RFC-CDC-531', 1, 1,'EOD Date', 'GFF021', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '53', 'RFC-CDC-532', 1, 2,'Profit Center', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('LDE', '53', 'RFC-CDC-533', 1, 3,'Exchange ', 'GFF1011', 1, 'N');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '53', 'RFC-CDC-531', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '53', 'RFC-CDC-531', 'RFP0026', 'AsOfDate');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '53', 'RFC-CDC-532', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '53', 'RFC-CDC-532', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '53', 'RFC-CDC-532', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '53', 'RFC-CDC-532', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '53', 'RFC-CDC-532', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '53', 'RFC-CDC-532', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '53', 'RFC-CDC-532', 'RFP1051', 'multiple');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '53', 'RFC-CDC-533', 'RFP1045', 'exchangelist');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '53', 'RFC-CDC-533', 'RFP1046', 'Exchange');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '53', 'RFC-CDC-533', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '53', 'RFC-CDC-533', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '53', 'RFC-CDC-533', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('LDE', '53', 'RFC-CDC-533', 'RFP1050', '1');

---SCRIPT FOR EKA CORPORATE
---******************************
--daily derivative report 
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '54', 'RFC-CDC-541', 1, 1,'Created Date', 'GFF021', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '54', 'RFC-CDC-542', 1, 2,'Profit Center', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '54', 'RFC-CDC-543', 1, 3,'Exchange ', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '54', 'RFC-CDC-545', 1, 4,'Strategy', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '54', 'RFC-CDC-546', 1, 5,'Trade Type', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '54', 'RFC-CDC-547', 1, 6,'Purpose', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '54', 'RFC-CDC-548', 1, 7,'Nominee', 'GFF1011', 1, 'N');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-541', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-541', 'RFP0026', 'AsOfDate');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-542', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-542', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-542', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-542', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-542', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-542', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-542', 'RFP1051', 'multiple');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-543', 'RFP1045', 'exchangelist');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-543', 'RFP1046', 'Exchange');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-543', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-543', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-543', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-543', 'RFP1050', '1');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-545', 'RFP1045', 'strategyDefinition');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-545', 'RFP1046', 'Strategy');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-545', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-545', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-545', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '54', 'RFC-CDC-545', 'RFP1050', '1');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '54', 'RFC-CDC-546', 'RFP1045', 'tradeTypeByMasterContract');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '54', 'RFC-CDC-546', 'RFP1046', 'TradeType');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-546', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-546', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '54', 'RFC-CDC-546', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '54', 'RFC-CDC-546', 'RFP1050', '1');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '54', 'RFC-CDC-547', 'RFP1045', 'setupDerivativeTradePurpose');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '54', 'RFC-CDC-547', 'RFP1046', 'Purpose');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '54', 'RFC-CDC-547', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '54', 'RFC-CDC-547', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '54', 'RFC-CDC-547', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-547', 'RFP1050', '1');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '54', 'RFC-CDC-548', 'RFP1045', 'corporatebusinesspartner');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '54', 'RFC-CDC-548', 'RFP1046', 'Nominee');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '54', 'RFC-CDC-548', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '54', 'RFC-CDC-548', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '54', 'RFC-CDC-548', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '54', 'RFC-CDC-548', 'RFP1050', '1');
--COMMIT;

---Daily Derivative unrealized pnl reports

Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '59', 'RFC-CDC-591', 1, 1,'EOD Date', 'GFF021', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '59', 'RFC-CDC-592', 1, 2,'Profit Center', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '59', 'RFC-CDC-593', 1, 3,'Exchange ', 'GFF1011', 1, 'N');
 
--
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '59', 'RFC-CDC-591', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '59', 'RFC-CDC-591', 'RFP0026', 'AsOfDate');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '59', 'RFC-CDC-592', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '59', 'RFC-CDC-592', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '59', 'RFC-CDC-592', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '59', 'RFC-CDC-592', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '59', 'RFC-CDC-592', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '59', 'RFC-CDC-592', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '59', 'RFC-CDC-592', 'RFP1051', 'multiple');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '59', 'RFC-CDC-593', 'RFP1045', 'exchangelist');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '59', 'RFC-CDC-593', 'RFP1046', 'Exchange');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '59', 'RFC-CDC-593', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '59', 'RFC-CDC-593', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '59', 'RFC-CDC-593', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '59', 'RFC-CDC-593', 'RFP1050', '1');
---

---Daily Derivative Realized pnl reports

Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '58', 'RFC-CDC-581', 1, 1,'EOD Date', 'GFF021', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '58', 'RFC-CDC-582', 1, 2,'Profit Center', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '58', 'RFC-CDC-583', 1, 3,'Exchange ', 'GFF1011', 1, 'N');
 
--
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '58', 'RFC-CDC-581', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '58', 'RFC-CDC-581', 'RFP0026', 'AsOfDate');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '58', 'RFC-CDC-582', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '58', 'RFC-CDC-582', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '58', 'RFC-CDC-582', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '58', 'RFC-CDC-582', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '58', 'RFC-CDC-582', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '58', 'RFC-CDC-582', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '58', 'RFC-CDC-582', 'RFP1051', 'multiple');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '58', 'RFC-CDC-583', 'RFP1045', 'exchangelist');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '58', 'RFC-CDC-583', 'RFP1046', 'Exchange');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '58', 'RFC-CDC-583', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '58', 'RFC-CDC-583', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '58', 'RFC-CDC-583', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '58', 'RFC-CDC-583', 'RFP1050', '1');
---

--DerivativePNLAttributionReport.rpt
--Report ID: 103
--AsOfDate

Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '103', 'RFC-CDC-1031', 1, 1,'EOD Date', 'GFF021', 1, 'Y');
 
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '103', 'RFC-CDC-1031', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '103', 'RFC-CDC-1031', 'RFP0026', 'AsOfDate');
--
--DailyClearerSummaryReport Report ID: 104 Parameter List:
-- AsOfDate  -- ClearerName

Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '104', 'RFC-CDC-1041', 1, 1,'EOD Date', 'GFF021', 1, 'Y');
 
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '104', 'RFC-CDC-1041', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '104', 'RFC-CDC-1041', 'RFP0026', 'AsOfDate');

--FutureOptionSummaryPositionReport Report ID:52
--Parameter: AsOfDate Book	Exchange	Purpose.

Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '52', 'RFC-CDC-521', 1, 1,'EOD Date', 'GFF021', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '52', 'RFC-CDC-522', 1, 2,'Profit Center', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '52', 'RFC-CDC-523', 1, 3,'Exchange ', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '52', 'RFC-CDC-524', 1, 4,'Purpose', 'GFF1011', 1, 'N');


Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '52', 'RFC-CDC-521', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '52', 'RFC-CDC-521', 'RFP0026', 'AsOfDate');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '52', 'RFC-CDC-522', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '52', 'RFC-CDC-522', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '52', 'RFC-CDC-522', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '52', 'RFC-CDC-522', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '52', 'RFC-CDC-522', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '52', 'RFC-CDC-522', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '52', 'RFC-CDC-522', 'RFP1051', 'multiple');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '52', 'RFC-CDC-523', 'RFP1045', 'exchangelist');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '52', 'RFC-CDC-523', 'RFP1046', 'Exchange');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '52', 'RFC-CDC-523', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '52', 'RFC-CDC-523', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '52', 'RFC-CDC-523', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '52', 'RFC-CDC-523', 'RFP1050', '1');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '52', 'RFC-CDC-524', 'RFP1045', 'setupDerivativeTradePurpose');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '52', 'RFC-CDC-524', 'RFP1046', 'Purpose');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '52', 'RFC-CDC-524', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '52', 'RFC-CDC-524', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '52', 'RFC-CDC-524', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '52', 'RFC-CDC-524', 'RFP1050', '1');
--
--Margin Report: Report ID : 53
--Parameter: AsOfDate  CorporateID  Book Exchange
--
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '53', 'RFC-CDC-531', 1, 1,'EOD Date', 'GFF021', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '53', 'RFC-CDC-532', 1, 2,'Profit Center', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values('EKA', '53', 'RFC-CDC-533', 1, 3,'Exchange ', 'GFF1011', 1, 'N');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '53', 'RFC-CDC-531', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '53', 'RFC-CDC-531', 'RFP0026', 'AsOfDate');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '53', 'RFC-CDC-532', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '53', 'RFC-CDC-532', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '53', 'RFC-CDC-532', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '53', 'RFC-CDC-532', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '53', 'RFC-CDC-532', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '53', 'RFC-CDC-532', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '53', 'RFC-CDC-532', 'RFP1051', 'multiple');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '53', 'RFC-CDC-533', 'RFP1045', 'exchangelist');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '53', 'RFC-CDC-533', 'RFP1046', 'Exchange');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '53', 'RFC-CDC-533', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '53', 'RFC-CDC-533', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '53', 'RFC-CDC-533', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values('EKA', '53', 'RFC-CDC-533', 'RFP1050', '1');