SET DEFINE OFF;

delete from RPC_RF_PARAMETER_CONFIG where report_id in('66','213','212','211','68','216');
delete from RFC_REPORT_FILTER_CONFIG where report_id in('66','213','212','211','68','216');
delete from RPC_RF_PARAMETER_CONFIG where report_id in('56','75');
delete from RFC_REPORT_FILTER_CONFIG where report_id in('56','75');
commit;

--213- open conc
--66 - open phy
--68 -- inv phy
--216 - inv conc
/*insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('LDE','211','RFC211PHY01','1','1','As Of Date','GFF021',1,'Y');
insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('LDE','211','RFC211PHY02','1','2','Profit Center','GFF1011',1,'N');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '211', 'RFC211PHY01', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '211', 'RFC211PHY01', 'RFP0026', 'AsOfDate');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '211', 'RFC211PHY02', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '211', 'RFC211PHY02', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '211', 'RFC211PHY02', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '211', 'RFC211PHY02', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '211', 'RFC211PHY02', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '211', 'RFC211PHY02', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '211', 'RFC211PHY02', 'RFP1051', 'multiple');*/

/*
insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('LDE','212','RFC212PHY01','1','1','Profit Center','GFF1011',1,'N');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '212', 'RFC212PHY01', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '212', 'RFC212PHY01', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '212', 'RFC212PHY01', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '212', 'RFC212PHY01', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '212', 'RFC212PHY01', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '212', 'RFC212PHY01', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '212', 'RFC212PHY01', 'RFP1051', 'multiple');*/

--------
insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('LDE','213','RFC213PHY01','1','1','EOD Date','GFF021',1,'Y');
insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('LDE','213','RFC213PHY02','1','2','Profit Center','GFF1011',1,'');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '213', 'RFC213PHY01', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '213', 'RFC213PHY01', 'RFP0026', 'AsOfDate');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '213', 'RFC213PHY02', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '213', 'RFC213PHY02', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '213', 'RFC213PHY02', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '213', 'RFC213PHY02', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '213', 'RFC213PHY02', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '213', 'RFC213PHY02', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '213', 'RFC213PHY02', 'RFP1051', 'multiple');

insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('LDE','66','RFC66PHY01','1','1','EOD Date','GFF021',1,'Y');
insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('LDE','66','RFC66PHY02','1','2','Profit Center','GFF1011',1,'');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '66', 'RFC66PHY01', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '66', 'RFC66PHY01', 'RFP0026', 'AsOfDate');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '66', 'RFC66PHY02', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '66', 'RFC66PHY02', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '66', 'RFC66PHY02', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '66', 'RFC66PHY02', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '66', 'RFC66PHY02', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '66', 'RFC66PHY02', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '66', 'RFC66PHY02', 'RFP1051', 'multiple');
--68 -- inv phy
--216 - inv conc
--
insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('LDE','216','RFC216PHY01','1','1','EOD Date','GFF021',1,'Y');
insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('LDE','216','RFC216PHY02','1','2','Profit Center','GFF1011',1,'');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '216', 'RFC216PHY01', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '216', 'RFC216PHY01', 'RFP0026', 'AsOfDate');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '216', 'RFC216PHY02', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '216', 'RFC216PHY02', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '216', 'RFC216PHY02', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '216', 'RFC216PHY02', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '216', 'RFC216PHY02', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '216', 'RFC216PHY02', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '216', 'RFC216PHY02', 'RFP1051', 'multiple');

insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('LDE','68','RFC68PHY01','1','1','EOD Date','GFF021',1,'Y');
insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('LDE','68','RFC68PHY02','1','2','Profit Center','GFF1011',1,'');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '68', 'RFC68PHY01', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '68', 'RFC68PHY01', 'RFP0026', 'AsOfDate');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '68', 'RFC68PHY02', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '68', 'RFC68PHY02', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '68', 'RFC68PHY02', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '68', 'RFC68PHY02', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '68', 'RFC68PHY02', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '68', 'RFC68PHY02', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '68', 'RFC68PHY02', 'RFP1051', 'multiple');

insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('LDE','56','RFC56PHY01','1','1','EOD Date','GFF021',1,'Y');
insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('LDE','56','RFC56PHY02','1','2','Profit Center','GFF1011',1,'');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '56', 'RFC56PHY01', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '56', 'RFC56PHY01', 'RFP0026', 'AsOfDate');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '56', 'RFC56PHY02', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '56', 'RFC56PHY02', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '56', 'RFC56PHY02', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '56', 'RFC56PHY02', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '56', 'RFC56PHY02', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '56', 'RFC56PHY02', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '56', 'RFC56PHY02', 'RFP1051', 'multiple');

insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('LDE','75','RFC75PHY01','1','1','EOD Date','GFF021',1,'Y');
insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('LDE','75','RFC75PHY02','1','2','Profit Center','GFF1011',1,'');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '75', 'RFC75PHY01', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '75', 'RFC75PHY01', 'RFP0026', 'AsOfDate');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '75', 'RFC75PHY02', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '75', 'RFC75PHY02', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '75', 'RFC75PHY02', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '75', 'RFC75PHY02', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '75', 'RFC75PHY02', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '75', 'RFC75PHY02', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('LDE', '75', 'RFC75PHY02', 'RFP1051', 'multiple');

 ---data for eka corporate
-------
insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('EKA','213','RFC213PHY01','1','1','EOD Date','GFF021',1,'Y');
insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('EKA','213','RFC213PHY02','1','2','Profit Center','GFF1011',1,'');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '213', 'RFC213PHY01', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '213', 'RFC213PHY01', 'RFP0026', 'AsOfDate');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '213', 'RFC213PHY02', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '213', 'RFC213PHY02', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '213', 'RFC213PHY02', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '213', 'RFC213PHY02', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '213', 'RFC213PHY02', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '213', 'RFC213PHY02', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '213', 'RFC213PHY02', 'RFP1051', 'multiple');

insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('EKA','66','RFC66PHY01','1','1','EOD Date','GFF021',1,'Y');
insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('EKA','66','RFC66PHY02','1','2','Profit Center','GFF1011',1,'');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '66', 'RFC66PHY01', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '66', 'RFC66PHY01', 'RFP0026', 'AsOfDate');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '66', 'RFC66PHY02', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '66', 'RFC66PHY02', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '66', 'RFC66PHY02', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '66', 'RFC66PHY02', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '66', 'RFC66PHY02', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '66', 'RFC66PHY02', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '66', 'RFC66PHY02', 'RFP1051', 'multiple');
--68 -- inv phy
--216 - inv conc
--
insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('EKA','216','RFC216PHY01','1','1','EOD Date','GFF021',1,'Y');
insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('EKA','216','RFC216PHY02','1','2','Profit Center','GFF1011',1,'');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '216', 'RFC216PHY01', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '216', 'RFC216PHY01', 'RFP0026', 'AsOfDate');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '216', 'RFC216PHY02', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '216', 'RFC216PHY02', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '216', 'RFC216PHY02', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '216', 'RFC216PHY02', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '216', 'RFC216PHY02', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '216', 'RFC216PHY02', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '216', 'RFC216PHY02', 'RFP1051', 'multiple');

insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('EKA','68','RFC68PHY01','1','1','EOD Date','GFF021',1,'Y');
insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('EKA','68','RFC68PHY02','1','2','Profit Center','GFF1011',1,'');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '68', 'RFC68PHY01', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '68', 'RFC68PHY01', 'RFP0026', 'AsOfDate');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '68', 'RFC68PHY02', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '68', 'RFC68PHY02', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '68', 'RFC68PHY02', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '68', 'RFC68PHY02', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '68', 'RFC68PHY02', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '68', 'RFC68PHY02', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '68', 'RFC68PHY02', 'RFP1051', 'multiple');

insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('EKA','56','RFC56PHY01','1','1','EOD Date','GFF021',1,'Y');
insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('EKA','56','RFC56PHY02','1','2','Profit Center','GFF1011',1,'');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '56', 'RFC56PHY01', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '56', 'RFC56PHY01', 'RFP0026', 'AsOfDate');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '56', 'RFC56PHY02', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '56', 'RFC56PHY02', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '56', 'RFC56PHY02', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '56', 'RFC56PHY02', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '56', 'RFC56PHY02', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '56', 'RFC56PHY02', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '56', 'RFC56PHY02', 'RFP1051', 'multiple');

insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('EKA','75','RFC75PHY01','1','1','EOD Date','GFF021',1,'Y');
insert into rfc_report_filter_config (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
values ('EKA','75','RFC75PHY02','1','2','Profit Center','GFF1011',1,'');

Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '75', 'RFC75PHY01', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '75', 'RFC75PHY01', 'RFP0026', 'AsOfDate');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '75', 'RFC75PHY02', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '75', 'RFC75PHY02', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '75', 'RFC75PHY02', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '75', 'RFC75PHY02', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '75', 'RFC75PHY02', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '75', 'RFC75PHY02', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values ('EKA', '75', 'RFC75PHY02', 'RFP1051', 'multiple');