Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('CAN-RET-&corpId', 'CancelRetMat', '&corpId', 'CAN-RET-', 1, 
    0,  '-&corpId', 1, 'N');
    

Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('CAN-FM-&corpId', 'CancelFreMat', '-&corpId', 'CAN-FM-', 1, 
    0, '-&corpId', 1, 'N');

    
 
    
    Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('CAN-RET-&corpId', '&corpId', 'RETURN_MATERIAL_CANCEL', 'CancelRetMat', 'N');
   
   
  
Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('CAN-FM-&corpId', '&corpId', 'FREE_MATERIAL_CANCEL', 'CancelFreMat', 'N');


 
 
 Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX)
 Values
   ('&corpId', 'RETURN_MATERIAL_CANCEL', 'CAN-RET-', 0, '-&corpId');


Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX)
 Values
   ('&corpId', 'FREE_MATERIAL_CANCEL', 'CAN-FM-', 0, '-&corpId');