Insert into DRF_DOC_REF_NUMBER_FORMAT
   (DOC_REF_NUMBER_FORMAT_ID, DOC_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('DRF-VAT-1', 'VAT_KEY_1', 'LDE', 'VAT-', 0, 
    0, '-LDE', 1, 'N');
    
Insert into DRF_DOC_REF_NUMBER_FORMAT
   (DOC_REF_NUMBER_FORMAT_ID, DOC_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('DRF-VAT-2', 'VAT_KEY_2', 'EKA', 'VAT-', 0, 
    0, '-EKA', 1, 'N');
      
Insert into DRFM_DOC_REF_NO_MAPPING
   (DOC_REF_NO_MAPPING_ID, CORPORATE_ID, DOC_ID, DOC_KEY_ID, IS_DELETED)
 Values
   ('DRFM-VAT-1', 'LDE', 'CREATE_VAT', 'VAT_KEY_1', 'N');
   
Insert into DRFM_DOC_REF_NO_MAPPING
   (DOC_REF_NO_MAPPING_ID, CORPORATE_ID, DOC_ID, DOC_KEY_ID, IS_DELETED)
 Values
   ('DRFM-VAT-2', 'EKA', 'CREATE_VAT', 'VAT_KEY_2', 'N');
   
Insert into CDC_CORPORATE_DOC_CONFIG
   (DOC_TEMPLATE_ID, CORPORATE_ID, DOC_ID, DOC_TEMPLATE_NAME, DOC_TEMPLATE_NAME_DE, 
    DOC_TEMPLATE_NAME_ES, DOC_PRINT_NAME, DOC_PRINT_NAME_DE, DOC_PRINT_NAME_ES, DOC_RPT_FILE_NAME, 
    IS_ACTIVE, DOC_AUTO_GENERATE)
 Values
   ('CDC-VAT-1', 'LDE', 'CREATE_VAT', 'Vat', NULL, 
    NULL, NULL, NULL, NULL, 'VatDocument.rpt', 
    'Y', 'Y');
    
Insert into CDC_CORPORATE_DOC_CONFIG
   (DOC_TEMPLATE_ID, CORPORATE_ID, DOC_ID, DOC_TEMPLATE_NAME, DOC_TEMPLATE_NAME_DE, 
    DOC_TEMPLATE_NAME_ES, DOC_PRINT_NAME, DOC_PRINT_NAME_DE, DOC_PRINT_NAME_ES, DOC_RPT_FILE_NAME, 
    IS_ACTIVE, DOC_AUTO_GENERATE)
 Values
   ('CDC-VAT-2', 'EKA', 'CREATE_VAT', 'Vat', NULL, 
    NULL, NULL, NULL, NULL, 'VatDocument.rpt', 
    'Y', 'Y');
    
Insert into DC_DOCUMENT_CONFIGURATION
   (ACTIVITY_ID, CORPORATE_ID, IS_GENERATE_DOC_REQD, IS_UPLOAD_DOC_REQD, DOC_VALIDATION_QUERY, 
    NAVIGATION)
 Values
   ('CREATE_VAT', 'LDE', 'Y', 'Y', 'select count(*) as countRow
from VAT_D isd
where isd.INTERNAL_DOC_REF_NO = ?', 
    '/metals/loadListOfInvoice.action?gridId=LOII_TEST');
    
Insert into DC_DOCUMENT_CONFIGURATION
   (ACTIVITY_ID, CORPORATE_ID, IS_GENERATE_DOC_REQD, IS_UPLOAD_DOC_REQD, DOC_VALIDATION_QUERY, 
    NAVIGATION)
 Values
   ('CREATE_VAT', 'EKA', 'Y', 'Y', 'select count(*) as countRow
from VAT_D isd
where isd.INTERNAL_DOC_REF_NO = ?', 
    '/metals/loadListOfInvoice.action?gridId=LOII_TEST');

