
Insert into CDC_CORPORATE_DOC_CONFIG
   (DOC_TEMPLATE_ID, CORPORATE_ID, DOC_ID, DOC_TEMPLATE_NAME, DOC_TEMPLATE_NAME_DE, 
    DOC_TEMPLATE_NAME_ES, DOC_PRINT_NAME, DOC_PRINT_NAME_DE, DOC_PRINT_NAME_ES, DOC_RPT_FILE_NAME, 
    IS_ACTIVE, DOC_AUTO_GENERATE)
 Values
   ('CDC-APPROVED', '&corpId', 'CONTRACT_APPROVED', 'Contract Approved', NULL, 
    NULL, NULL, NULL, NULL, 'ContractPreview.rpt', 
    'Y', 'Y');

Insert into DRF_DOC_REF_NUMBER_FORMAT
   (DOC_REF_NUMBER_FORMAT_ID, DOC_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('DRF-APPR-&corpId', 'APPROVED_KEY_1', '&corpId', 'APPR-', 0, 
    1, '-&corpId', NULL, 'N');

Insert into DRFM_DOC_REF_NO_MAPPING
   (DOC_REF_NO_MAPPING_ID, CORPORATE_ID, DOC_ID, DOC_KEY_ID, IS_DELETED)
 Values
   ('DRFM-APPR-&corpId', '&corpId', 'CONTRACT_APPROVED', 'APPROVED_KEY_1', 'N');

Insert into DC_DOCUMENT_CONFIGURATION
   (ACTIVITY_ID, CORPORATE_ID, IS_GENERATE_DOC_REQD, IS_UPLOAD_DOC_REQD, DOC_VALIDATION_QUERY, 
    NAVIGATION)
 Values
   ('CONTRACT_APPROVED', '&corpId', 'Y', 'Y', 'select count(*) as countRow
from COS_CONTRACT_OUTPUT_SUMMARY cos
where COS.INTERNAL_DOC_REF_NO = ?', 
    '/metals/loadListOfContracts.action?gridId=PHY_LOC');
    
Insert into CDC_CORPORATE_DOC_CONFIG
   (DOC_TEMPLATE_ID, CORPORATE_ID, DOC_ID, DOC_TEMPLATE_NAME, DOC_TEMPLATE_NAME_DE, 
    DOC_TEMPLATE_NAME_ES, DOC_PRINT_NAME, DOC_PRINT_NAME_DE, DOC_PRINT_NAME_ES, DOC_RPT_FILE_NAME, 
    IS_ACTIVE, DOC_AUTO_GENERATE)
 Values
   ('CDC-AMEND-PC', '&corpId', 'AMEND_PC', 'Purchase Contract Amendment', NULL, 
    NULL, NULL, NULL, NULL, 'ContractPreview.rpt', 
    'Y', 'Y');

Insert into DRF_DOC_REF_NUMBER_FORMAT
   (DOC_REF_NUMBER_FORMAT_ID, DOC_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('DRF-AMDPC-&corpId', 'AMEND_PC_KEY', '&corpId', 'AMEND-', 0, 
    1, '-&corpId', NULL, 'N');

Insert into DRFM_DOC_REF_NO_MAPPING
   (DOC_REF_NO_MAPPING_ID, CORPORATE_ID, DOC_ID, DOC_KEY_ID, IS_DELETED)
 Values
   ('DRFM-AMDPC-&corpId', '&corpId', 'AMEND_PC', 'AMEND_PC_KEY', 'N');

Insert into DC_DOCUMENT_CONFIGURATION
   (ACTIVITY_ID, CORPORATE_ID, IS_GENERATE_DOC_REQD, IS_UPLOAD_DOC_REQD, DOC_VALIDATION_QUERY, 
    NAVIGATION)
 Values
   ('AMEND_PC', '&corpId', 'Y', 'Y', 'select count(*) as countRow
from COS_CONTRACT_OUTPUT_SUMMARY cos
where COS.INTERNAL_DOC_REF_NO = ?', 
    '/metals/loadListOfContracts.action?gridId=PHY_LOC');

Insert into CDC_CORPORATE_DOC_CONFIG
   (DOC_TEMPLATE_ID, CORPORATE_ID, DOC_ID, DOC_TEMPLATE_NAME, DOC_TEMPLATE_NAME_DE, 
    DOC_TEMPLATE_NAME_ES, DOC_PRINT_NAME, DOC_PRINT_NAME_DE, DOC_PRINT_NAME_ES, DOC_RPT_FILE_NAME, 
    IS_ACTIVE, DOC_AUTO_GENERATE)
 Values
   ('CDC-AMEND-&corpId', 'EKA', 'AMEND_SC', 'Sales Contract Amendment', NULL, 
    NULL, NULL, NULL, NULL, 'ContractPreview.rpt', 
    'Y', 'Y');

Insert into DRF_DOC_REF_NUMBER_FORMAT
   (DOC_REF_NUMBER_FORMAT_ID, DOC_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('DRF-AMDSC-&corpId', 'AMEND_SC_KEY', '&corpId', 'AMEND-', 0, 
    1, '-&corpId', NULL, 'N');

Insert into DRFM_DOC_REF_NO_MAPPING
   (DOC_REF_NO_MAPPING_ID, CORPORATE_ID, DOC_ID, DOC_KEY_ID, IS_DELETED)
 Values
   ('DRFM-AMDSC-&corpId', '&corpId', 'AMEND_SC', 'AMEND_SC_KEY', 'N');

Insert into DC_DOCUMENT_CONFIGURATION
   (ACTIVITY_ID, CORPORATE_ID, IS_GENERATE_DOC_REQD, IS_UPLOAD_DOC_REQD, DOC_VALIDATION_QUERY, 
    NAVIGATION)
 Values
   ('AMEND_SC', '&corpId', 'Y', 'Y', 'select count(*) as countRow
from COS_CONTRACT_OUTPUT_SUMMARY cos
where COS.INTERNAL_DOC_REF_NO = ?', 
    '/metals/loadListOfContracts.action?gridId=PHY_LOC');
   
   
