SET DEFINE OFF;
declare
begin
 for cc in (select *
               from ak_corporate akc
              where akc.is_internal_corporate = 'N')
  loop
    dbms_output.put_line(cc.corporate_id);

Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '229', 'RFC-CDC-2291', 1, 1, 'EOM Month', 'GFF1012', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '229', 'RFC-CDC-2292', 1, 2, 'EOM Year', 'GFF1012', 1, 'Y');

Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '221', 'RFC-CDC-2211', 1, 1, 'EOM Month', 'GFF1012', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER,LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '221', 'RFC-CDC-2212', 1, 2, 'EOM Year', 'GFF1012', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '221', 'RFC-CDC-2213', 1, 3, 'Profit Center', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '221', 'RFC-CDC-2214', 1, 4, 'Exchange ', 'GFF1011', 1, 'N');

Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '222', 'RFC-CDC-2221', 1, 1, 'EOM Month', 'GFF1012', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '222', 'RFC-CDC-2222', 1, 2, 'EOM Year', 'GFF1012', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '222', 'RFC-CDC-2223', 1, 3, 'Profit Center', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '222', 'RFC-CDC-2224', 1, 4, 'Exchange ', 'GFF1011', 1, 'N');

Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '230', 'RFC-CDC-2301', 1, 1, 'EOM Month', 'GFF1012', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '230', 'RFC-CDC-2302', 1, 2, 'EOM Year', 'GFF1012', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '230', 'RFC-CDC-2303', 1, 3, 'Profit Center', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '230', 'RFC-CDC-2304', 1, 4, 'Exchange ', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '230', 'RFC-CDC-2305', 1, 5, 'Purpose', 'GFF1011', 1, 'N');


Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '231', 'RFC231CDC02', 1, 2, 'EOM Year', 'GFF1012', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '231', 'RFC231CDC01', 1, 1, 'EOM Date', 'GFF1012', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '231', 'RFC231CDC03', 1, 3, 'Future Contract ', 'GFF1001', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '231', 'RFC231CDC04', 1, 4, 'Clearer', 'GFF1001', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '231', 'RFC231CDC05', 1, 5, 'Section', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '231', 'RFC231CDC06', 1, 6, 'Trade Date', 'GFF021', 1, 'N');


Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '232', 'RFC-CDC-2322', 1, 2, 'EOM Year', 'GFF1012', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '232', 'RFC-CDC-2321', 1, 1, 'EOM Month', 'GFF1012', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '232', 'RFC-CDC-2323', 1, 3, 'Profit Center', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '232', 'RFC-CDC-2324', 1, 4, 'Exchange ', 'GFF1011', 1, 'N');


Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '233', 'RFC233CDC02', 1, 2, 'EOM Year', 'GFF1012', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '233', 'RFC233CDC01', 1, 1, 'EOM Month', 'GFF1012', 1, 'Y');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '233', 'RFC233CDC03', 1, 3, 'Clearer', 'GFF1001', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '233', 'RFC233CDC04', 1, 4, 'Exchange', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '233', 'RFC233CDC05', 1, 5, 'Instrument Type', 'GFF1011', 1, 'N');
Insert into RFC_REPORT_FILTER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
Values(cc.corporate_id, '233', 'RFC233CDC06', 1, 6, 'Trade Date', 'GFF021', 1, 'N');

Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2305', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2305', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC03', 'RFP1001', 'setupUnderlyingInstrument');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC03', 'RFP1002', 'FutureContract');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC03', 'RFP1003', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC03', 'RFP1004', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC03', 'RFP1005', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC03', 'RFP1006', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC03', 'RFP1007', 'multiple');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC04', 'RFP1001', 'businesspartner');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC04', 'RFP1002', 'ClearerName');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC04', 'RFP1003', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC04', 'RFP1004', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC04', 'RFP1005', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC04', 'RFP1006', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC04', 'RFP1008', 'EXCHANGECLEARER,FUTURESBROKER');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC05', 'RFP1046', 'InstrumentType');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC05', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC05', 'RFP1045', 'setupInstrumentType');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC05', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC05', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC05', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC05', 'RFP1231', 'multiple');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC06', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC06', 'RFP0026', 'TradeDate');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2323', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2323', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2323', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2323', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2323', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2323', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2323', 'RFP1051', 'multiple');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2324', 'RFP1045', 'exchangelist');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2324', 'RFP1046', 'Exchange');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2324', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2324', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2324', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2324', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC01', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC01', 'RFP0026', 'AsOfDate');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC03', 'RFP1001', 'businesspartner');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC03', 'RFP1002', 'ClearerName');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC03', 'RFP1003', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC03', 'RFP1004', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC03', 'RFP1005', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC03', 'RFP1006', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC03', 'RFP1008', 'EXCHANGECLEARER,FUTURESBROKER');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC04', 'RFP1045', 'exchangelist');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC04', 'RFP1046', 'Exchange');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC04', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC04', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC04', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC04', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC05', 'RFP1046', 'InstrumentType');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC05', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC05', 'RFP1045', 'setupInstrumentType');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC05', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC05', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC05', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC05', 'RFP1051', 'multiple');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC06', 'RFP0026', 'TradeDate');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC06', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2211', 'RFP1063', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2211', 'RFP1064', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2211', 'RFP1065', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2211', 'RFP1066', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2212', 'RFP1060', 'yearList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2212', 'RFP1062', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2211', 'RFP1062', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2212', 'RFP1063', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2212', 'RFP1064', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2212', 'RFP1065', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2212', 'RFP1066', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2212', 'RFP1061', 'Year');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2221', 'RFP1061', 'Month');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2221', 'RFP1060', 'MonthList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2221', 'RFP1062', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2221', 'RFP1063', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2221', 'RFP1064', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2221', 'RFP1065', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2221', 'RFP1066', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2222', 'RFP1060', 'yearList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2222', 'RFP1062', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2222', 'RFP1063', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2222', 'RFP1064', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2222', 'RFP1065', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2222', 'RFP1066', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2222', 'RFP1061', 'Year');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '229', 'RFC-CDC-2291', 'RFP1061', 'Month');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '229', 'RFC-CDC-2291', 'RFP1060', 'MonthList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '229', 'RFC-CDC-2291', 'RFP1062', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '229', 'RFC-CDC-2291', 'RFP1063', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '229', 'RFC-CDC-2291', 'RFP1064', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '229', 'RFC-CDC-2291', 'RFP1065', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '229', 'RFC-CDC-2291', 'RFP1066', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '229', 'RFC-CDC-2292', 'RFP1060', 'yearList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '229', 'RFC-CDC-2292', 'RFP1062', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '229', 'RFC-CDC-2292', 'RFP1063', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '229', 'RFC-CDC-2292', 'RFP1064', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '229', 'RFC-CDC-2292', 'RFP1065', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2301', 'RFP1060', 'MonthList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2301', 'RFP1062', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2301', 'RFP1063', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2301', 'RFP1064', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2301', 'RFP1065', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2301', 'RFP1066', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2302', 'RFP1060', 'yearList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '229', 'RFC-CDC-2292', 'RFP1066', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '229', 'RFC-CDC-2292', 'RFP1061', 'Year');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2301', 'RFP1061', 'Month');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2302', 'RFP1062', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2211', 'RFP1061', 'Month');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2211', 'RFP1060', 'MonthList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2213', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2213', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2213', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2213', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2213', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2213', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2213', 'RFP1051', 'multiple');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2214', 'RFP1045', 'exchangelist');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2214', 'RFP1046', 'Exchange');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2214', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2214', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2214', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '221', 'RFC-CDC-2214', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2223', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2223', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2223', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2223', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2223', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2223', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2223', 'RFP1051', 'multiple');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2224', 'RFP1045', 'exchangelist');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2224', 'RFP1046', 'Exchange');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2224', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2224', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2224', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '222', 'RFC-CDC-2224', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2301', 'RFP0104', 'SYSTEM');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2301', 'RFP0026', 'AsOfDate');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2303', 'RFP1045', 'reportProfitcenterList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2303', 'RFP1046', 'Book');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2303', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2303', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2303', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2303', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2303', 'RFP1051', 'multiple');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2304', 'RFP1045', 'exchangelist');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2304', 'RFP1046', 'Exchange');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2304', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2304', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2304', 'RFP1049', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2304', 'RFP1050', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2305', 'RFP1045', 'setupDerivativeTradePurpose');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2305', 'RFP1046', 'Purpose');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2305', 'RFP1047', 'No');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2305', 'RFP1048', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC01', 'RFP1061', 'Month');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC01', 'RFP1060', 'MonthList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC01', 'RFP1062', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC01', 'RFP1063', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC01', 'RFP1064', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC01', 'RFP1065', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC01', 'RFP1066', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC02', 'RFP1060', 'yearList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC02', 'RFP1062', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC02', 'RFP1063', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC02', 'RFP1064', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC02', 'RFP1065', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC02', 'RFP1066', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '231', 'RFC231CDC02', 'RFP1061', 'Year');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC01', 'RFP1061', 'Month');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC01', 'RFP1060', 'MonthList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC01', 'RFP1062', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC01', 'RFP1063', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC01', 'RFP1064', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC01', 'RFP1065', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC01', 'RFP1066', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC02', 'RFP1060', 'yearList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC02', 'RFP1062', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC02', 'RFP1063', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC02', 'RFP1064', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC02', 'RFP1065', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC02', 'RFP1066', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '233', 'RFC233CDC02', 'RFP1061', 'Year');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2321', 'RFP1061', 'Month');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2321', 'RFP1060', 'MonthList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2321', 'RFP1062', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2321', 'RFP1063', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2321', 'RFP1064', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2321', 'RFP1065', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2321', 'RFP1066', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2322', 'RFP1060', 'yearList');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2322', 'RFP1062', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2322', 'RFP1063', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2322', 'RFP1064', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2322', 'RFP1065', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2322', 'RFP1066', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '232', 'RFC-CDC-2322', 'RFP1061', 'Year');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2302', 'RFP1063', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2302', 'RFP1064', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2302', 'RFP1065', '1');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2302', 'RFP1066', 'Yes');
Insert into RPC_RF_PARAMETER_CONFIG(CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
Values(cc.corporate_id, '230', 'RFC-CDC-2302', 'RFP1061', 'Year');
COMMIT;
  end loop;
commit;
end;