delete from RFC_REPORT_FILTER_CONFIG rfc where RFC.LABEL_ID='RFC237PHY07' and RFC.REPORT_ID=237;
delete from RPC_RF_PARAMETER_CONFIG rpc where rpc.LABEL_ID='RFC237PHY07' and rpc.REPORT_ID=237;
commit;

update RFC_REPORT_FILTER_CONFIG rfc set RFC.LABEL_ID='RFC366PHY03' where RFC.LABEL_ID='RFC255PHY03' and RFC.REPORT_ID=366;
update RPC_RF_PARAMETER_CONFIG rpc set RPC.LABEL_ID='RFC366PHY03' where RPC.LABEL_ID='RFC255PHY03' and RPC.REPORT_ID=366;
commit;

update RFC_REPORT_FILTER_CONFIG rfc set RFC.LABEL='Counterparty' where RFC.LABEL_ID='RFC366PHY03' and RFC.REPORT_ID=366;
update RPC_RF_PARAMETER_CONFIG rpc set RPC.REPORT_PARAMETER_NAME='BUYER,SELLER' where RPC.LABEL_ID='RFC366PHY03' and rpc.REPORT_ID=366 and RPC.PARAMETER_ID='RFP1008';
commit;

begin
for cc in (select * from AK_CORPORATE akc where AKC.IS_ACTIVE = 'Y' and AKC.IS_INTERNAL_CORPORATE = 'N')
loop
Insert into RFC_REPORT_FILTER_CONFIG
   (CORPORATE_ID, REPORT_ID, LABEL_ID, LABEL_COLUMN_NUMBER, LABEL_ROW_NUMBER, 
    LABEL, FIELD_ID, COLSPAN, IS_MANDATORY)
 Values
   (cc.CORPORATE_ID, '237', 'RFC237PHY10', 1, 10, 
    'Smelter', 'GFF1001', 1, 'N');
Insert into RPC_RF_PARAMETER_CONFIG
   (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values
   (cc.CORPORATE_ID, '237', 'RFC237PHY10', 'RFP1001', 'businesspartner');
Insert into RPC_RF_PARAMETER_CONFIG
   (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values
   (cc.CORPORATE_ID, '237', 'RFC237PHY10', 'RFP1002', 'Smelter');
Insert into RPC_RF_PARAMETER_CONFIG
   (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values
   (cc.CORPORATE_ID, '237', 'RFC237PHY10', 'RFP1003', 'No');
Insert into RPC_RF_PARAMETER_CONFIG
   (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values
   (cc.CORPORATE_ID, '237', 'RFC237PHY10', 'RFP1004', 'Filter');
Insert into RPC_RF_PARAMETER_CONFIG
   (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values
   (cc.CORPORATE_ID, '237', 'RFC237PHY10', 'RFP1005', 'reportForm');
Insert into RPC_RF_PARAMETER_CONFIG
   (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values
   (cc.CORPORATE_ID, '237', 'RFC237PHY10', 'RFP1006', '1');
Insert into RPC_RF_PARAMETER_CONFIG
   (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values
   (cc.CORPORATE_ID, '237', 'RFC237PHY10', 'RFP1008', 'WAREHOUSING');

Insert into RPC_RF_PARAMETER_CONFIG
   (CORPORATE_ID, REPORT_ID, LABEL_ID, PARAMETER_ID, REPORT_PARAMETER_NAME)
 Values
   (cc.CORPORATE_ID, '366', 'RFC366PHY03', 'RFP1007', 'multiple');  
   
COMMIT;
end loop;
end;




