BEGIN
for cc in (select AKC.CORPORATE_ID from AK_CORPORATE akc where AKC.IS_ACTIVE='Y' and AKC.IS_INTERNAL_CORPORATE='N') 
loop

Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('ARF-CPA-&'||CC.CORPORATE_ID, 'createPARefNo', CC.CORPORATE_ID, 'PA-', 1, 
    0, '-'||CC.CORPORATE_ID, 1, 'N');

 Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-CPA-'||CC.CORPORATE_ID, CC.CORPORATE_ID, 'CREATE_PROVISIONAL_ASSAY', 'createPARefNo', 'N');

 Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX)
 Values
   (CC.CORPORATE_ID, 'CREATE_PROVISIONAL_ASSAY', 'PA-', 0, '-'||CC.CORPORATE_ID);


   Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('ARF-CSA-'||CC.CORPORATE_ID, 'createSARefNo', CC.CORPORATE_ID, 'SA-', 1, 0, '-'||CC.CORPORATE_ID, 1, 'N');

 Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-CSA-'||CC.CORPORATE_ID, CC.CORPORATE_ID, 'CREATE_SELF_ASSAY', 'createSARefNo', 'N');

 Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX)
 Values
   (CC.CORPORATE_ID, 'CREATE_SELF_ASSAY', 'SA-', 0, '-'||CC.CORPORATE_ID);

   Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('ARF-CCPA-'||CC.CORPORATE_ID, 'createCPRefNo', CC.CORPORATE_ID, 'CCPA-', 1, 0, '-'||CC.CORPORATE_ID, 1, 'N');

 Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-CCPA-'||CC.CORPORATE_ID, CC.CORPORATE_ID, 'CREATE_CP_ASSAY', 'createCPRefNo', 'N');

 Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX)
 Values
   (CC.CORPORATE_ID, 'CREATE_CP_ASSAY', 'CCPA-', 0, '-'||CC.CORPORATE_ID);


   Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('ARF-CUA-'||CC.CORPORATE_ID, 'createUARefNo', CC.CORPORATE_ID, 'CUA-', 1, 0, '-'||CC.CORPORATE_ID, 1, 'N');

 Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-CUA-'||CC.CORPORATE_ID, CC.CORPORATE_ID, 'CREATE_UMPIRE_ASSAY', 'createUARefNo', 'N');

 Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX)
 Values
   (CC.CORPORATE_ID, 'CREATE_UMPIRE_ASSAY', 'CUA-', 0, '-'||CC.CORPORATE_ID);

   Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('ARF-CFA-'||CC.CORPORATE_ID, 'createFARefNo', CC.CORPORATE_ID, 'CFA-', 1, 0, '-'||CC.CORPORATE_ID, 1, 'N');

 Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-CFA-'||CC.CORPORATE_ID, CC.CORPORATE_ID, 'CREATE_FINAL_ASSAY', 'createFARefNo', 'N');

 Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX)
 Values
   (CC.CORPORATE_ID, 'CREATE_FINAL_ASSAY', 'CFA-', 0, '-'||CC.CORPORATE_ID);
   
   
  Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('ARF-DPA-'||CC.CORPORATE_ID, 'cancelPARefNo', CC.CORPORATE_ID, 'DPA-', 1, 0, '-'||CC.CORPORATE_ID, 1, 'N');

 Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-DPA-'||CC.CORPORATE_ID, CC.CORPORATE_ID, 'CANCEL_PROVISIONAL_ASSAY', 'cancelPARefNo', 'N');

 Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX)
 Values
   (CC.CORPORATE_ID, 'CANCEL_PROVISIONAL_ASSAY', 'DPA-', 0, '-'||CC.CORPORATE_ID);

  
  Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('ARF-DSA-'||CC.CORPORATE_ID, 'cancelSARefNo', CC.CORPORATE_ID, 'DSA-', 1, 0, '-'||CC.CORPORATE_ID, 1, 'N');

 Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-DSA-'||CC.CORPORATE_ID, CC.CORPORATE_ID, 'CANCEL_SELF_ASSAY', 'cancelSARefNo', 'N');

 Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX)
 Values
   (CC.CORPORATE_ID, 'CANCEL_SELF_ASSAY', 'DSA-', 0, '-'||CC.CORPORATE_ID);


Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('ARF-DCPA-'||CC.CORPORATE_ID, 'cancelCPRefNo', CC.CORPORATE_ID, 'DCPA-', 1, 0, '-'||CC.CORPORATE_ID, 1, 'N');

 Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-DCPA-'||CC.CORPORATE_ID, CC.CORPORATE_ID, 'CANCEL_CP_ASSAY', 'cancelCPRefNo', 'N');

 Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX)
 Values
   (CC.CORPORATE_ID, 'CANCEL_CP_ASSAY', 'DCPA-', 0, '-'||CC.CORPORATE_ID);
   
  
Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('ARF-DUA-'||CC.CORPORATE_ID, 'cancelUARefNo', CC.CORPORATE_ID, 'DUA-', 1, 0, '-'||CC.CORPORATE_ID, 1, 'N');

 Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-DUA-'||CC.CORPORATE_ID, CC.CORPORATE_ID, 'CANCEL_UMPIRE_ASSAY', 'cancelUARefNo', 'N');

 Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX)
 Values
   (CC.CORPORATE_ID, 'CANCEL_UMPIRE_ASSAY', 'DUA-', 0, '-'||CC.CORPORATE_ID);
   
   
 Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('ARF-DFA-'||CC.CORPORATE_ID, 'cancelFARefNo', CC.CORPORATE_ID, 'DFA-', 1, 0, '-'||CC.CORPORATE_ID, 1, 'N');

 Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-DFA-'||CC.CORPORATE_ID, CC.CORPORATE_ID, 'CANCEL_FINAL_ASSAY', 'cancelFARefNo', 'N');

 Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX)
 Values
   (CC.CORPORATE_ID, 'CANCEL_FINAL_ASSAY', 'DFA-', 0, '-'||CC.CORPORATE_ID);
   
 
 Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('ARF-MPA-'||CC.CORPORATE_ID, 'modifyPARefNo', CC.CORPORATE_ID, 'MPA-', 1, 0, '-'||CC.CORPORATE_ID, 1, 'N');

 Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-MPA-'||CC.CORPORATE_ID, CC.CORPORATE_ID, 'MODIFY_PROVISIONAL_ASSAY', 'modifyPARefNo', 'N');

 Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX)
 Values
   (CC.CORPORATE_ID, 'MODIFY_PROVISIONAL_ASSAY', 'MPA-', 0, '-'||CC.CORPORATE_ID);
   
   
 Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('ARF-MSA-'||CC.CORPORATE_ID, 'modifySARefNo', CC.CORPORATE_ID, 'MSA-', 1, 0, '-'||CC.CORPORATE_ID, 1, 'N');

 Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-MSA-'||CC.CORPORATE_ID, CC.CORPORATE_ID, 'MODIFY_SELF_ASSAY', 'modifySARefNo', 'N');

 Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX)
 Values
   (CC.CORPORATE_ID, 'MODIFY_SELF_ASSAY', 'MSA-', 0, '-'||CC.CORPORATE_ID);
   
   
Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('ARF-MCPA-'||CC.CORPORATE_ID, 'modifyCPARefNo', CC.CORPORATE_ID, 'MCPA-', 1, 0, '-'||CC.CORPORATE_ID, 1, 'N');

 Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-MCPA-'||CC.CORPORATE_ID, CC.CORPORATE_ID, 'MODIFY_CP_ASSAY', 'modifyCPARefNo', 'N');

 Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX)
 Values
   (CC.CORPORATE_ID, 'MODIFY_CP_ASSAY', 'MCPA-', 0, '-'||CC.CORPORATE_ID);
   
   
   
Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('ARF-MUA-'||CC.CORPORATE_ID, 'modifyUARefNo', CC.CORPORATE_ID, 'MUA-', 1, 0, '-'||CC.CORPORATE_ID, 1, 'N');

 Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-MUA-'||CC.CORPORATE_ID, CC.CORPORATE_ID, 'MODIFY_UMPIRE_ASSAY', 'modifyUARefNo', 'N');

 Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX)
 Values
   (CC.CORPORATE_ID, 'MODIFY_UMPIRE_ASSAY', 'MUA-', 0, '-'||CC.CORPORATE_ID);
   
      
Insert into ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 Values
   ('ARF-MFA-'||CC.CORPORATE_ID, 'modifyFARefNo', CC.CORPORATE_ID, 'MFA-', 1, 0, '-'||CC.CORPORATE_ID, 1, 'N');

 Insert into ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 Values
   ('ARFM-MFA-'||CC.CORPORATE_ID, CC.CORPORATE_ID, 'MODIFY_FINAL_ASSAY', 'modifyFARefNo', 'N');

 Insert into ERC_EXTERNAL_REF_NO_CONFIG
   (CORPORATE_ID, EXTERNAL_REF_NO_KEY, PREFIX, MIDDLE_NO_LAST_USED_VALUE, SUFFIX)
 Values
   (CC.CORPORATE_ID, 'MODIFY_FINAL_ASSAY', 'MFA-', 0, '-'||CC.CORPORATE_ID);
   
    end loop;
end;
/