INSERT INTO ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 VALUES
   ('ARF-PT-&corpId', 'PTRefNo', '&corpId', 'PT-', 1, 
    1, '-&corpId', 1, 'N');
       
INSERT INTO ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 VALUES
   ('ARFM-PT-&corpId', '&corpId', 'pledgeTransfer', 'PTRefNo', 'N');

INSERT INTO ARF_ACTION_REF_NUMBER_FORMAT
   (ACTION_REF_NUMBER_FORMAT_ID, ACTION_KEY_ID, CORPORATE_ID, PREFIX, MIDDLE_NO_START_VALUE, 
    MIDDLE_NO_LAST_USED_VALUE, SUFFIX, VERSION, IS_DELETED)
 VALUES
   ('ARF-MBT-&corpId', 'MBTRefNo', '&corpId', 'MBT-', 1, 
    1, '-&corpId', 1, 'N');
       
INSERT INTO ARFM_ACTION_REF_NO_MAPPING
   (ACTION_REF_NO_MAPPING_ID, CORPORATE_ID, ACTION_ID, ACTION_KEY_ID, IS_DELETED)
 VALUES
   ('ARFM-MBT-&corpId', '&corpId', 'metalBalanceTransfer', 'MBTRefNo', 'N');