
CREATE OR REPLACE PROCEDURE f_RemoveAppLink( menuId varchar2) as
ACLID VARCHAR2 (100) :='';
begin

select  AMC.ACL_ID into ACLID from AMC_APP_MENU_CONFIGURATION AMC WHERE AMC.MENU_ID = menuId;

delete from RAD_ROLE_ACCESS_DETAILS Where ACL_ID = ACLID;

delete from AMC_APP_MENU_CONFIGURATION AMC WHERE AMC.MENU_ID =menuId;

delete from ACL_ACCESS_CONTROL_LIST WHERE ACL_ID =ACLID;
end;
/



create or replace  PROCEDURE f_RemoveReportLink( reportId varchar2,  menuId varchar2) as
ACLID VARCHAR2 (100) :='';
begin

select  AMC.ACL_ID into ACLID from AMC_APP_MENU_CONFIGURATION AMC WHERE AMC.MENU_ID = menuId;
delete from RFC_REPORT_FILTER_CONFIG  WHERE REPORT_ID = reportId;
delete from REF_REPORTEXPORTFORMAT  Where REPORT_ID  = reportId;
delete from RML_REPORT_MASTER_LIST  Where REPORT_ID  = reportId;

delete from RAD_ROLE_ACCESS_DETAILS Where ACL_ID =ACLID;

delete from AMC_APP_MENU_CONFIGURATION AMC WHERE AMC.MENU_ID =menuId;

delete from ACL_ACCESS_CONTROL_LIST WHERE ACL_ID =ACLID;
end;

/
BEGIN 

	F_REMOVEREPORTLINK ( '215','RPT-D218'); 
	F_REMOVEREPORTLINK ('84','RPT-D226');
	F_REMOVEREPORTLINK ('86','RPT-D228');
	F_REMOVEREPORTLINK ('65','RPT-D229');
	F_REMOVEREPORTLINK ('67','RPT-D330');
	F_REMOVEREPORTLINK ('225','RPT-D231');
	F_REMOVEREPORTLINK ('227','RPT-D233');
	F_REMOVEREPORTLINK ('210','RPT-D412');
	F_REMOVEREPORTLINK ('52','RPT-D426');
	F_REMOVEREPORTLINK ('53','RPT-D428');
	F_REMOVEREPORTLINK ('101','RPT-D429');
	F_REMOVEREPORTLINK ('75','RPT-D522');
	F_REMOVEREPORTLINK ('224','RPT-D532');

	-- Deal Creation
	F_REMOVEAPPLINK ( 'P80' );
	F_REMOVEAPPLINK ( 'P79' );
	F_REMOVEAPPLINK ( 'P78' );

	--Discrete Tolling Link start
	F_REMOVEAPPLINK ( 'TOL-M5' );
	F_REMOVEAPPLINK ( 'TOL-M3' );
	F_REMOVEAPPLINK ( 'TOL-M1.1.1' );
	F_REMOVEAPPLINK ( 'TOL-M1' );
	F_REMOVEAPPLINK ( 'TOL-M4' );
	F_REMOVEAPPLINK ( 'TOL-M2' );
	F_REMOVEAPPLINK ( 'TOL-M1.1' );    
	--Discrete Tolling Link end
	--Transport Booking
	F_REMOVEAPPLINK ( 'L3' );
	--Remove Weighing Sampling
	delete from GMC_GRID_MENU_CONFIGURATION GMC WHERE GMC.MENU_ID ='LOGA-3';
	delete from RAD_ROLE_ACCESS_DETAILS Where ACL_ID In ('APP-ACL-N1061');
	delete from ACL_ACCESS_CONTROL_LIST WHERE ACL_ID In ('APP-ACL-N1061');
	--Special Settlement
	delete from GMC_GRID_MENU_CONFIGURATION GMC WHERE GMC.MENU_ID ='LOSS_1';
	delete from RAD_ROLE_ACCESS_DETAILS Where ACL_ID In ('APP-ACL-N1079');
	delete from ACL_ACCESS_CONTROL_LIST WHERE ACL_ID In ('APP-ACL-N1079');
	delete from GMC_GRID_MENU_CONFIGURATION GMC WHERE GMC.MENU_ID ='LOSS';
	F_REMOVEAPPLINK ( 'LOSS' );
	delete from GMC_GRID_MENU_CONFIGURATION GMC WHERE GMC.MENU_ID ='LOII_4';
	delete from RAD_ROLE_ACCESS_DETAILS Where ACL_ID In ('APP-ACL-N1097');
	delete from ACL_ACCESS_CONTROL_LIST WHERE ACL_ID In ('APP-ACL-N1097');  

	--Inventory Items
	delete from GMC_GRID_MENU_CONFIGURATION GMC WHERE GMC.MENU_ID ='TPA-2';
	delete from RAD_ROLE_ACCESS_DETAILS Where ACL_ID In ('APP-ACL-N1043');
	delete from ACL_ACCESS_CONTROL_LIST WHERE ACL_ID In ('APP-ACL-N1043');
	delete from GMC_GRID_MENU_CONFIGURATION GMC WHERE GMC.MENU_ID ='TPA_1';

	F_REMOVEAPPLINK ( 'TOL-P1' );
	F_REMOVEAPPLINK ( 'TOL-P2' );
	F_REMOVEAPPLINK ( 'TOL-P7' );
 	commit;
  
END; 