alter table POUE_PHY_OPEN_UNREAL_ELEMENT add VALUATION_AGAINST_UNDERLYING char(1);
alter table POUED_ELEMENT_DETAILS  add  VALUATION_AGAINST_UNDERLYING char(1);
alter table PSUE_ELEMENT_DETAILS add VALUATION_AGAINST_UNDERLYING char(1);
alter table PSUE_PHY_STOCK_UNREALIZED_ELE add VALUATION_AGAINST_UNDERLYING char(1);
alter table PSUE_PHY_STOCK_UNREALIZED_ELE add net_m2m_amount number(25,5);
alter table PSUE_PHY_STOCK_UNREALIZED_ELE add prev_net_m2m_amount number(25,5);