alter table CIPD_CONTRACT_ITEM_PRICE_DAILY MODIFY PRICE_DESCRIPTION VARCHAR2(4000);
alter table CIPDE_CIPD_ELEMENT_PRICE MODIFY PRICE_DESCRIPTION VARCHAR2(4000);
alter table POUD_PHY_OPEN_UNREAL_DAILY MODIFY PRICE_STRING VARCHAR2(4000);
alter table POUED_ELEMENT_DETAILS MODIFY PRICING_DETAILS VARCHAR2(4000);
alter table PSUE_ELEMENT_DETAILS MODIFY PRICING_DETAILS VARCHAR2(4000);