alter table GPD_GMR_CONC_PRICE_DAILY add PRICE_BASIS VARCHAR2(30);
alter table GPD_GMR_CONC_PRICE_DAILY add PRICE_FIXATION_DETAILS varchar2(1000);
alter table GPD_GMR_CONC_PRICE_DAILY add PRICE_DESCRIPTION varchar2(4000);