ALTER TABLE CIPD_CONTRACT_ITEM_PRICE_DAILY ADD(
EXCH_RATE_STRING                           VARCHAR2(300),
PRICE_IN_BASE_PRICE_UNIT_ID                NUMBER(25,5));

ALTER TABLE GPD_GMR_PRICE_DAILY ADD(
CONTRACT_BASE_PRICE_UNIT_ID                 VARCHAR2(15),
EXCH_RATE_STRING                            VARCHAR2(300),
PRICE_IN_BASE_PRICE_UNIT_ID                 NUMBER(25,5));

ALTER TABLE GRD_GOODS_RECORD_DETAIL ADD
(PAYMENT_DUE_DATE DATE);

ALTER TABLE DGRD_DELIVERED_GRD ADD
(PAYMENT_DUE_DATE DATE);

ALTER TABLE INVM_INVENTORY_MASTER ADD(
PRODUCT_PREMIUM                    NUMBER(25,5),
QUALITY_PREMIUM                    NUMBER(25,5),
PRICE_UNIT_ID                   VARCHAR2(15),
PRICE_UNIT_CUR_ID               VARCHAR2(15),
PRICE_UNIT_CUR_CODE             VARCHAR2(15),
PRICE_UNIT_WEIGHT_UNIT_ID       VARCHAR2(15),
PRICE_UNIT_WEIGHT_UNIT          VARCHAR2(15),
PRICE_UNIT_WEIGHT               NUMBER(7,2),
MATERIAL_COST_PER_UNIT          NUMBER(20,8),
SECONDARY_COST_PER_UNIT         NUMBER(20,8),
PRODUCT_PREMIUM_PER_UNIT        NUMBER(20,8),
QUALITY_PREMIUM_PER_UNIT        NUMBER(20,8));

ALTER TABLE PSU_PHY_STOCK_UNREALIZED ADD
(M_PNL_IN_BASE_CUR                      NUMBER(25,5),
M_PNL_IN_VAL_CUR                        NUMBER(25,5),
M_PREV_DAY_PNL_IN_BASE_CUR              NUMBER(25,5),
M_PREV_DAY_PNL_IN_VAL_CUR               NUMBER(25,5),
M_TRADE_DAY_PNL_IN_BASE_CUR             NUMBER(25,5),
M_TRADE_DAY_PNL_IN_VAL_CUR              NUMBER(25,5),
M_PNL_IN_EXCH_PRICE_UNIT                NUMBER(25,5),
M_PREV_PNL_IN_EXCH_PRICE_UNIT           NUMBER(25,5),
M_DAY_PNL_IN_EXCH_PRICE_UNIT            NUMBER(25,5),
M_TRADE_DAY_PNL_PER_BASE_UNIT           NUMBER(25,5),
M_PNL_IN_BASE_PER_UNIT                  NUMBER(25,5),
M_PNL_IN_VAL_CUR_PER_UNIT               NUMBER(25,5));

CREATE TABLE GSCS_GMR_SEC_COST_SUMMARY
(
  INTERNAL_GMR_REF_NO            VARCHAR2(15 CHAR),
  AVG_COST                       NUMBER(25,5),
  PROCESS_ID                     VARCHAR2(20 CHAR)
);

CREATE TABLE PRD_PHYSICAL_REALIZED_DAILY(
PROCESS_ID                          VARCHAR2(15),
TRADE_DATE                          DATE,
CORPORATE_ID                        VARCHAR2(15),
CORPORATE_NAME                      VARCHAR2(100),
INTERNAL_CONTRACT_REF_NO            VARCHAR2(15),
CONTRACT_REF_NO                     VARCHAR2(30),
INTERNAL_CONTRACT_ITEM_REF_NO       VARCHAR2(15),
DEL_DISTRIBUTION_ITEM_NO            NUMBER(10,5),
CONTRACT_ISSUE_DATE                 DATE,
CONTRACT_TYPE                       VARCHAR2(10),
CONTRACT_STATUS                     VARCHAR2(20),
INT_ALLOC_GROUP_ID                  VARCHAR2(15),
ALLOC_GROUP_NAME                    VARCHAR2(100),
INTERNAL_GMR_REF_NO                     VARCHAR2(15),
GMR_REF_NO                              VARCHAR2(30),
INTERNAL_GRD_REF_NO                 VARCHAR2(15),
INTERNAL_STOCK_REF_NO               VARCHAR2(15),
PRODUCT_ID                          VARCHAR2(15),
PRODUCT_NAME                        VARCHAR2(100),
ORIGIN_ID                           VARCHAR2(15),
ORIGIN_NAME                         VARCHAR2(100),
QUALITY_ID                          VARCHAR2(15),    
QUALITY_NAME                        VARCHAR2(100),
PROFIT_CENTER_ID                    VARCHAR2(15),
PROFIT_CENTER_NAME                  VARCHAR2(30),
PROFIT_CENTER_SHORT_NAME            VARCHAR2(15),
CP_PROFILE_ID                       VARCHAR2(15),
CP_NAME                             VARCHAR2(100),
TRADE_USER_ID                       VARCHAR2(15),
TRADE_USER_NAME                     VARCHAR2(100),
PRICE_TYPE_ID                       VARCHAR2(15),
PRICE_TYPE_NAME                     VARCHAR2(15),
INCOTERM_ID                         VARCHAR2(15),
INCOTERM                            VARCHAR2(100),
PAYMENT_TERM_ID                     VARCHAR2(15),    
PAYMENT_TERM                        VARCHAR2(50),
PRICE_FIXATION_DETAILS              VARCHAR2(1000),
PRICE_FIXATION_STATUS               VARCHAR2(100),
REALIZED_TYPE                       VARCHAR2(50),
REALIZED_DATE                       DATE,    
CONTAINER_NO                        VARCHAR2(50),    
ITEM_QTY                            NUMBER(25,5),
QTY_UNIT_ID                         VARCHAR2(15),
QTY_UNIT                            VARCHAR2(15),
CONTRACT_PRICE                      NUMBER(25,5),
PRICE_UNIT_ID                       VARCHAR2(15),
PRICE_UNIT_CUR_ID                   VARCHAR2(15),
PRICE_UNIT_CUR_CODE                 VARCHAR2(15),
PRICE_UNIT_WEIGHT_UNIT_ID           VARCHAR2(15),
PRICE_UNIT_WEIGHT_UNIT              VARCHAR2(15),
PRICE_UNIT_WEIGHT                   NUMBER(7,2),
CONTRACT_VALUE_IN_PRICE_CUR         NUMBER(25,5),        
CONTRACT_PRICE_CUR_ID               VARCHAR2(15),
CONTRACT_PRICE_CUR_CODE             VARCHAR2(15),
CONTRACT_INVOICE_VALUE              NUMBER(25,5),        
SECONDARY_COST_PER_UNIT                  NUMBER(25,5),        
PRODUCT_PREMIUM_PER_UNIT                     NUMBER(25,5),
PRODUCT_PREMIUM                     NUMBER(25,5),
QUALITY_PREMIUM_PER_UNIT                     NUMBER(25,5),
QUALITY_PREMIUM                     NUMBER(25,5),
SECONDARY_COST_VALUE                NUMBER(25,5),        
COG_NET_SALE_VALUE                  NUMBER(25,5),        
REALIZED_PNL                        NUMBER(25,5),        
PREV_REAL_PRICE                     NUMBER(25,5),        
PREV_REAL_PRICE_ID                  VARCHAR2(15),
PREV_REAL_PRICE_CUR_ID              VARCHAR2(15),
PREV_REAL_PRICE_CUR_CODE            VARCHAR2(15),
PREV_REAL_PRICE_WEIGHT_UNIT_ID      VARCHAR2(15),
PREV_REAL_PRICE_WEIGHT_UNIT         VARCHAR2(15),
PREV_REAL_PRICE_WEIGHT              NUMBER(7,2),    
PREV_REAL_QTY                       NUMBER(25,5),        
PREV_REAL_QTY_ID                    VARCHAR2(15),
PREV_REAL_QTY_UNIT                  VARCHAR2(15),
PREV_CONT_VALUE_IN_PRICE_CUR        NUMBER(25,5),        
PREV_CONTRACT_PRICE_CUR_ID          VARCHAR2(15),
PREV_CONTRACT_PRICE_CUR_CODE        VARCHAR2(15),
PREV_REAL_CONTRACT_VALUE            NUMBER(25,5),        
PREV_REAL_SECONDARY_COST            NUMBER(25,5),        
PREV_REAL_COG_NET_SALE_VALUE        NUMBER(25,5),        
PREV_REAL_PNL                       NUMBER(25,5),        
PREV_PRODUCT_PREMIUM_PER_UNIT       NUMBER(25,5),
PREV_PRODUCT_PREMIUM                NUMBER(25,5),
PREV_QUALITY_PREMIUM_PER_UNIT       NUMBER(25,5),
PREV_QUALITY_PREMIUM                NUMBER(25,5),
PREV_SECONDARY_COST_PER_UNIT        NUMBER(25,5),        
CHANGE_IN_PNL                       NUMBER(25,5),        
CFX_PRICE_CUR_TO_BASE_CUR           NUMBER(15,8),        
WAREHOUSE_ID                        VARCHAR2(15),
WAREHOUSE_NAME                      VARCHAR2(100),
SHED_ID                             VARCHAR2(15),
SHED_NAME                           VARCHAR2(100),
GROUP_ID                            VARCHAR2(15),
GROUP_NAME                          VARCHAR2(45),
GROUP_CUR_ID                        VARCHAR2(15),
GROUP_CUR_CODE                      VARCHAR2(15),    
GROUP_QTY_UNIT_ID                   VARCHAR2(15),
GROUP_QTY_UNIT                      VARCHAR2(15),
ITEM_QTY_IN_BASE_QTY_UNIT           NUMBER(25,5),        
BASE_QTY_UNIT_ID                    VARCHAR2(15),
BASE_QTY_UNIT                       VARCHAR2(15),
BASE_CUR_ID                         VARCHAR2(15),    
BASE_CUR_CODE                       VARCHAR2(15),    
BASE_PRICE_UNIT_ID                  VARCHAR2(15),        
BASE_PRICE_UNIT_NAME                VARCHAR2(50),    
SALES_PROFIT_CENTER_ID              VARCHAR2(15),
SALES_PROFIT_CENTER_NAME            VARCHAR2(30),
SALES_PROFIT_CENTER_SHORT_NAME      VARCHAR2(15),
SALES_STRATEGY_ID                   VARCHAR2(15),
SALES_STRATEGY_NAME                 VARCHAR2(30),
SALES_BUSINESS_LINE_ID               VARCHAR2(15),
SALES_BUSINESS_LINE_NAME               VARCHAR2(15),
SALES_INTERNAL_GMR_REF_NO           VARCHAR2(15),
SALES_CONTRACT_REF_NO               VARCHAR2(15),
ORIGINATION_CITY_ID                 VARCHAR2(15),
ORIGINATION_CITY_NAME               VARCHAR2(100),
ORIGINATION_COUNTRY_ID              VARCHAR2(15),
ORIGINATION_COUNTRY_NAME            VARCHAR2(100),    
DESTINATION_CITY_ID                 VARCHAR2(15),
DESTINATION_CITY_NAME               VARCHAR2(100),
DESTINATION_COUNTRY_ID              VARCHAR2(15),
DESTINATION_COUNTRY_NAME            VARCHAR2(100),
POOL_ID                             VARCHAR2(15),
STRATEGY_ID                         VARCHAR2(15),
STRATEGY_NAME                       VARCHAR2(100),
BUSINESS_LINE_ID                    VARCHAR2(15),
BUSINESS_LINE_NAME                  VARCHAR2(100),
BL_NUMBER                           VARCHAR2(15),
BL_DATE                             DATE,
SEAL_NO                             VARCHAR2(50),
MARK_NO                             VARCHAR2(50),
WAREHOUSE_REF_NO                    VARCHAR2(50),    
WAREHOUSE_RECEIPT_NO                VARCHAR2(50),
WAREHOUSE_RECEIPT_DATE              DATE,
IS_WARRANT                          VARCHAR2(1),
WARRANT_NO                          VARCHAR2(15),
PCDI_ID                             VARCHAR2(15),
SUPP_CONTRACT_ITEM_REF_NO           VARCHAR2(15),
SUPPLIER_PCDI_ID                    VARCHAR2(50),
PAYABLE_RETURNABLE_TYPE             VARCHAR2(10));

CREATE TABLE RGMR_REALIZED_GMR
(PROCESS_ID VARCHAR2(15),
INT_ALLOC_GROUP_ID VARCHAR2(15),
INTERNAL_GMR_REF_NO VARCHAR2(15),
REALIZED_STATUS     VARCHAR2(30),
REALIZED_PROCESS_ID VARCHAR2(15),
REALIZED_PROCESS_DATE DATE);


CREATE INDEX IDX_PRD1 ON PRD_PHYSICAL_REALIZED_DAILY(PROCESS_ID,REALIZED_TYPE);

CREATE INDEX IDX_RGMR1 ON RGMR_REALIZED_GMR(PROCESS_ID,REALIZED_STATUS);


ALTER TABLE GRD_GOODS_RECORD_DETAIL ADD(
PROFIT_CENTER_ID                VARCHAR2(15),
STRATEGY_ID                     VARCHAR2(15),
IS_WARRANT                      CHAR(1 CHAR),
WARRANT_NO                      VARCHAR2(15),
PCDI_ID                         VARCHAR2(15),
SUPP_CONTRACT_ITEM_REF_NO       VARCHAR2(15),
SUPPLIER_PCDI_ID                VARCHAR2(15),
PAYABLE_RETURNABLE_TYPE         VARCHAR2(10));

ALTER TABLE PSU_PHY_STOCK_UNREALIZED DROP (CGC_ID,CGC,CROP_YEAR,GROWTH_CODE_ID,GROWTH_CODE_NAME);

ALTER TABLE PSU_PHY_STOCK_UNREALIZED DROP (CMA_PURCHASE_CP_NO,CMA_PURCHASE_ITEM_REF_NO,CMA_PURCHASE_REF_NO,CMA_STOCK);        

ALTER TABLE PSU_PHY_STOCK_UNREALIZED DROP (M_PNL_IN_EXCH_PRICE_UNIT,M_PREV_PNL_IN_EXCH_PRICE_UNIT,M_DAY_PNL_IN_EXCH_PRICE_UNIT);

CREATE TABLE PC_PRICE_CONVERSION
(CORPORATE_ID        VARCHAR2(15),                    
FROM_PRICE_UNIT_ID  VARCHAR2(15),                    
TO_PRICE_UNIT_ID    VARCHAR2(15),                    
CONV_FACTOR         NUMBER);        

CREATE TABLE SPD_STOCK_PRICE_DAILY
(PROCESS_ID                VARCHAR2(15),
INTERNAL_DRG_DGRD_REF_NO   VARCHAR2(15),
STOCK_PRICE               NUMBER(25,10),
PRICE_UNIT_ID             VARCHAR2(15),
PRICE_UNIT_CUR_ID         VARCHAR2(15),
PRICE_UNIT_CUR_CODE		  VARCHAR2 (15),			
PRICE_UNIT_WEIGHT		  NUMBER (7,2),
PRICE_UNIT_WEIGHT_UNIT_ID VARCHAR2 (15),	
PRICE_UNIT_WEIGHT_UNIT	  VARCHAR2 (15 ));

CREATE INDEX IDX_SPD1 ON SPD_STOCK_PRICE_DAILY(PROCESS_ID,INTERNAL_DRG_DGRD_REF_NO);

ALTER TABLE CIPD_CONTRACT_ITEM_PRICE_DAILY DROP COLUMN PRICE_IN_BASE_PRICE_UNIT_ID;
ALTER TABLE CIPD_CONTRACT_ITEM_PRICE_DAILY ADD PRICE_IN_BASE_PRICE_UNIT_ID NUMBER(25,10);

ALTER TABLE PSU_PHY_STOCK_UNREALIZED ADD IS_MARKED_FOR_CONSIGNMENT VARCHAR2(15);

ALTER TABLE PRD_PHYSICAL_REALIZED_DAILY ADD PRICE_DESCRIPTION VARCHAR2(4000);

ALTER TABLE PCI_PHYSICAL_CONTRACT_ITEM ADD (
PCBPH_ID VARCHAR2(15),
PRICE_DESCRIPTION VARCHAR2(4000));



CREATE TABLE CDL_COST_DELTA_LOG
(
  CDL_ID                  VARCHAR2(15),
  INTERNAL_ACTION_REF_NO  VARCHAR2(15),
  COST_REF_NO             VARCHAR2(15),
  DELTA_COST              NUMBER(25,10),
  VERSION                 NUMBER(10),
  DBD_ID                  VARCHAR2(15),
  PROCESS_ID              VARCHAR2(15));

ALTER TABLE DGRDUL_DELIVERED_GRD_UL ADD (PROCESS_ID VARCHAR2(15));

CREATE TABLE RGMRD_REALIZED_GMR_DETAIL
(
  PROCESS_ID                     VARCHAR2(15 CHAR),
  REALIZED_INTERNAL_GMR_REF_NO   VARCHAR2(15 CHAR),
  PURCHASE_INTERNAL_GMR_REF_NO   VARCHAR2(15 CHAR),
  INTERNAL_CONTRACT_ITEM_REF_NO  VARCHAR2(15 CHAR),
  PRICE_TYPE_ID                  VARCHAR2(30 CHAR),
  CONTRACT_TYPE                  VARCHAR2(1 CHAR),
  PRICE_FIXATION_STATUS          VARCHAR2(50 CHAR),
  IS_INVOICED              CHAR(1 CHAR)   DEFAULT 'N',
  CORPORATE_ID                   VARCHAR2(15 CHAR)
);

CREATE TABLE IS_INVOICE_SUMMARY
(
  INTERNAL_INVOICE_REF_NO        VARCHAR2(15),
  INVOICE_TYPE                   VARCHAR2(25),
  INVOICE_TYPE_NAME              VARCHAR2(25),
  TOTAL_INVOICE_ITEM_AMOUNT      NUMBER(38,18),
  TOTAL_TAX_AMOUNT               NUMBER(38,18),
  TOTAL_ITEM_AMOUNT_CUR_ID       VARCHAR2(15),
  TAX_AMOUNT_CUR_ID              VARCHAR2(15),
  TOTAL_OTHER_CHARGE_AMOUNT      NUMBER(38,18),
  OTHER_CHARGE_AMOUNT_CUR_ID     VARCHAR2(15),
  PAYMENT_DUE_DATE               DATE,
  INVOICE_ISSUE_DATE             DATE,
  CP_REF_NO                      VARCHAR2(50),
  RECIEVED_RAISED_TYPE           VARCHAR2(25),
  INVOICE_CREATED_DATE           DATE,
  PROFIT_CENTER_ID               VARCHAR2(15),
  TOTAL_AMOUNT_TO_PAY            NUMBER(38,18),
  POSTING_STATUS                 VARCHAR2(25),
  AMOUNT_PAID                    NUMBER(38,18),
  INVOICE_STATUS                 VARCHAR2(25),
  IS_DC_CREATED_ONCANCEL         VARCHAR2(2),
  CANCEL_INVOICE_REF_NO          VARCHAR2(15),
  CANCELLED_DEBIT_CREDIT_REF_NO  VARCHAR2(15),
  CREATED_FROM                   VARCHAR2(25),
  INVOICED_QTY                   NUMBER(38,18),
  APPROVAL_STATUS                CHAR(1),
  INTERNAL_CONTRACT_REF_NO       VARCHAR2(15),
  IS_ACTIVE                      CHAR(1)   DEFAULT 'Y',
  INVOICE_REF_NO                 VARCHAR2(30),
  API_ADJUSTED_AMOUNT            NUMBER(38,18),
  IS_CONSIDERED_FOR_FINAL        CHAR(1)   DEFAULT 'N',
  AMOUNT_TO_PAY_BEFORE_ADJ       NUMBER(38,18),
  NEW_FX_RATE                    NUMBER(38,18),
  INVOICED_PRICE_UNIT_ID         VARCHAR2(15),
  INVOICED_PRICE                 NUMBER(38,18),
  NEW_INVOICED_QTY_UNIT_ID       VARCHAR2(15),
  NEW_INVOICED_QTY               NUMBER(38,18),
  CORPORATE_ID                   VARCHAR2(15),
  INTERNAL_COMMENTS              VARCHAR2(300),
  BILL_TO_ADDRESS                VARCHAR2(300),
  CP_ID                          VARCHAR2(30),
  FX_TO_BASE                     NUMBER(38,18),
  BILL_TO_CP_ID                  VARCHAR2(30),
  REASON_FOR_MODIFICATION        VARCHAR2(300),
  IS_DC_CREATED                  CHAR(1)   DEFAULT 'N',
  CREDIT_TERM                    VARCHAR2(30),
  PROVISIONAL_PYMT_PCTG          NUMBER(10,4),
  INVOICE_CUR_ID                 VARCHAR2(15),
  IS_PROV_CREATED                CHAR(1)   DEFAULT 'N',
  CANCELLED_INVOICE_INT_REF_NO   VARCHAR2(15),
  VAT_PARENT_REF_NO              VARCHAR2(30),
  IS_FREE_METAL                  CHAR(1)   DEFAULT 'N',
  IS_INV_DRAFT                   CHAR(1)   DEFAULT 'N',
  DBD_ID                         VARCHAR2(15),
  PROCESS_ID                     VARCHAR2(15),
  IS_CANCELLED_TODAY             VARCHAR2(1));

CREATE TABLE TRGMR_TEMP_RGMR
(
  CORPORATE_ID             VARCHAR2(15),
  INT_ALLOC_GROUP_ID     VARCHAR2(15),
  INTERNAL_GMR_REF_NO    VARCHAR2(15),
  REALIZED_STATUS        VARCHAR2(30),
  REALIZED_PROCESS_ID    VARCHAR2(15),
  REALIZED_PROCESS_DATE  DATE,
  SECTION_NAME      VARCHAR2(30));

CREATE TABLE INVS_INVENTORY_SALES
(
  INTERNAL_INV_ID                VARCHAR2(15 ),
  INV_REF_NO                     VARCHAR2(30 ),
  INTERNAL_GMR_REF_NO            VARCHAR2(15 ),
  SALES_INTERNAL_GMR_REF_NO      VARCHAR2(15 ),
  INTERNAL_GRD_REF_NO            VARCHAR2(15 ),
  INTERNAL_CONTRACT_ITEM_REF_NO  VARCHAR2(15 ),
  INV_IN_ACTION_REF_NO           VARCHAR2(15 ),
  INV_STATUS                     VARCHAR2(30 ),
  ORIGINAL_INV_QTY               NUMBER(25,10) ,
  CURRENT_INV_QTY                NUMBER(25,10) ,
  INV_QTY_ID                     VARCHAR2(15 ),
  IS_ACTIVE                      CHAR(1 ) ,
  PRODUCT_PREMIUM                NUMBER(25,5),
  QUALITY_PREMIUM                NUMBER(25,5),
  PRICE_UNIT_ID                  VARCHAR2(15 BYTE),
  PRICE_UNIT_CUR_ID              VARCHAR2(15 BYTE),
  PRICE_UNIT_CUR_CODE            VARCHAR2(15 BYTE),
  PRICE_UNIT_WEIGHT_UNIT_ID      VARCHAR2(15 BYTE),
  PRICE_UNIT_WEIGHT_UNIT         VARCHAR2(15 BYTE),
  PRICE_UNIT_WEIGHT              NUMBER(7,2),
  MATERIAL_COST_PER_UNIT         NUMBER(20,8),
  SECONDARY_COST_PER_UNIT        NUMBER(20,8),
  PRODUCT_PREMIUM_PER_UNIT       NUMBER(20,8),
  QUALITY_PREMIUM_PER_UNIT       NUMBER(20,8),
  DBD_ID                       VARCHAR2(15 ),
  PROCESS_ID                     VARCHAR2(15 ));

CREATE TABLE PPS_PHYSICAL_PNL_SUMMARY
(
  CORPORATE_ID              VARCHAR2(15),
  CORPORATE_NAME            VARCHAR2(100),
  PROCESS_ID                VARCHAR2(15),
  PROFIT_CENTER_ID          VARCHAR2(15),
  PROFIT_CENTER_NAME        VARCHAR2(50),
  PROFIT_CENTER_SHORT_NAME  VARCHAR2(15),
  MAIN_SECTION              VARCHAR2(100),
  SUB_SECTION               VARCHAR2(500),
  ENTITY                    VARCHAR2(100),
  PNL                       NUMBER(25,5),
  PNL_CUR_ID                VARCHAR2(15),
  PNL_CUR_CODE              VARCHAR2(15),
  APPROVAL_STATUS           VARCHAR2(1));

CREATE TABLE TPP_TRADE_PNL_PARAMETERS
(
  PROCESS_ID       VARCHAR2(100 ),
  PREV_PROCESS_ID  VARCHAR2(100 ),
  PREV_EOD_DATE    DATE,
  PREV_EOM_REF_NO  VARCHAR2(100 ),
  PREV_EOM_DATE    DATE,
  ACC_START_DATE   DATE);

CREATE MATERIALIZED VIEW  II_INVOICABLE_ITEM  REFRESH FAST ON DEMAND WITH PRIMARY KEY AS  SELECT * FROM  II_INVOICABLE_ITEM@eka_appdb;
CREATE MATERIALIZED VIEW  IID_INVOICABLE_ITEM_DETAILS  REFRESH FAST ON DEMAND WITH PRIMARY KEY AS  SELECT * FROM  IID_INVOICABLE_ITEM_DETAILS@eka_appdb;
CREATE MATERIALIZED VIEW  SCM_STOCK_COST_MAPPING  REFRESH FAST ON DEMAND WITH PRIMARY KEY AS  SELECT * FROM  SCM_STOCK_COST_MAPPING@eka_appdb;