DROP MATERIALIZED VIEW PCMTE_PCM_TOLLING_EXT;
DROP MATERIALIZED VIEW PQDT_PAYABLE_EXT_TOLLING;
DROP MATERIALIZED VIEW PQCAPD_PRD_QLTY_CATTR_PAY_DTLS;
DROP MATERIALIZED VIEW SAM_STOCK_ASSAY_MAPPING;

DROP TABLE PCMTE_PCM_TOLLING_EXT;
DROP TABLE PQDT_PAYABLE_EXT_TOLLING;
DROP TABLE PQCAPD_PRD_QLTY_CATTR_PAY_DTLS;
DROP TABLE SAM_STOCK_ASSAY_MAPPING;

CREATE MATERIALIZED VIEW  PCMTE_PCM_TOLLING_EXT  REFRESH FAST ON DEMAND WITH PRIMARY KEY AS  SELECT * FROM  PCMTE_PCM_TOLLING_EXT@eka_appdb;
CREATE MATERIALIZED VIEW  PQDT_PAYABLE_EXT_TOLLING  REFRESH FAST ON DEMAND WITH PRIMARY KEY AS  SELECT * FROM  PQDT_PAYABLE_EXT_TOLLING@eka_appdb;
CREATE MATERIALIZED VIEW  PQCAPD_PRD_QLTY_CATTR_PAY_DTLS  REFRESH FAST ON DEMAND WITH PRIMARY KEY AS  SELECT * FROM  PQCAPD_PRD_QLTY_CATTR_PAY_DTLS@eka_appdb;
CREATE MATERIALIZED VIEW  SAM_STOCK_ASSAY_MAPPING  REFRESH FAST ON DEMAND WITH PRIMARY KEY AS  SELECT * FROM  SAM_STOCK_ASSAY_MAPPING@eka_appdb;