DROP MATERIALIZED VIEW SAM_STOCK_ASSAY_MAPPING;
DROP TABLE SAM_STOCK_ASSAY_MAPPING;
CREATE MATERIALIZED VIEW  SAM_STOCK_ASSAY_MAPPING  REFRESH FAST ON DEMAND WITH PRIMARY KEY AS  SELECT * FROM  SAM_STOCK_ASSAY_MAPPING@eka_appdb;

ALTER TABLE PCBPH_PC_BASE_PRICE_HEADER ADD VALUATION_PRICE_PERCENTAGE NUMBER(25,10);
ALTER TABLE PCBPHUL_PC_BASE_PRC_HEADER_UL ADD VALUATION_PRICE_PERCENTAGE VARCHAR2(30);
