ALTER TABLE AREO_AR_ELEMENT_ORIGINAL ADD
(ELEMENT_BASE_QTY_UNIT_ID             VARCHAR2(15),
ELEMENT_BASE_QTY_UNIT                VARCHAR2(15));
ALTER TABLE ARE_ARRIVAL_REPORT_ELEMENT ADD(
ELEMENT_BASE_QTY_UNIT_ID             VARCHAR2(15),
ELEMENT_BASE_QTY_UNIT                VARCHAR2(15));