ALTER TABLE GRD_GOODS_RECORD_DETAIL ADD(
POOL_ID                             VARCHAR2(15),
POOL_NAME                           VARCHAR2(50));

ALTER TABLE PA_PURCHASE_ACCURAL_GMR ADD (PLEDGED_GMR_REF_NOS VARCHAR2(500));

CREATE INDEX IDX_PSR1 ON PSR_POOL_STOCK_REGISTER(INTERNAL_GRD_REF_NO,POOL_ID);

ALTER TABLE CBR_CLOSING_BALANCE_REPORT DROP (CONTRACT_PRICE,PRICE_UNIT_ID);

CREATE TABLE CBT_CB_TEMP 
(GMR_REF_NO                    VARCHAR2(15),
INTERNAL_GMR_REF_NO            VARCHAR2(15),
INTERNAL_GRD_REF_NO            VARCHAR2(15),
INTERNAL_STOCK_REF_NO        VARCHAR2(30),
PARENT_INTERNAL_GRD_REF_NO    VARCHAR2(15),
PARENT_INTERNAL_GMR_REF_NO    VARCHAR2(15),
IS_INTERNAL_MOVEMENT        VARCHAR2(1),
CORPORATE_ID                VARCHAR2(15),
CORPORATE_NAME                VARCHAR2(100),
WAREHOUSE_PROFILE_ID        VARCHAR2(15),
WAREHOUSE_NAME                VARCHAR2(100),
SHED_ID                        VARCHAR2(15),
SHED_NAME                    VARCHAR2(50),
PRODUCT_ID                    VARCHAR2(15),
PRODUCT_DESC                VARCHAR2(100),
QUALITY_ID                    VARCHAR2(15),
QUALITY_NAME                VARCHAR2(100),
WET_QTY                        NUMBER(25,10),
DRY_QTY                        NUMBER(25,10),
QTY_UNIT_ID                    VARCHAR2(15),        
QTY_UNIT                    VARCHAR2(15),
ELEMENT_ID                    VARCHAR2(15),
ELEMENT_NAME                VARCHAR2(30),
UNDERLYING_PRODUCT_ID        VARCHAR2(15),
UNDERLYING_PRODUCT_NAME        VARCHAR2(100),
UNDERLYING_BASE_QTY_UNIT_ID    VARCHAR2(15),
UNDERLYING_BASE_QTY_UNIT    VARCHAR2(15),    
ASSAY_QTY                    NUMBER(25,10),                
ASSAY_QTY_UNIT_ID                VARCHAR2(15),    
ASSAY_QTY_UNIT                VARCHAR2(15),    
PAYABLE_QTY                    NUMBER(25,10),
PAYABLE_QTY_UNIT_ID            VARCHAR2(15),
PAYABLE_QTY_UNIT            VARCHAR2(15),
POOL_NAME                    VARCHAR2(50),
ASH_ID                        VARCHAR2(15),
PCDI_ID                        VARCHAR2(15),    
PAY_CUR_ID                    VARCHAR2(15),
PAY_CUR_CODE                VARCHAR2(15),    
PAY_CUR_DECIMAL                NUMBER(2),
QTY_TYPE                    VARCHAR2(15),
CONC_BASE_QTY_UNIT_ID        VARCHAR2(15),    
CONC_BASE_QTY_UNIT            VARCHAR2(15),
GMR_REF_NO_FOR_PRICE        VARCHAR2(15),
GRD_TO_GMR_QTY_FACTOR NUMBER,
SECTION_NAME  VARCHAR2(11));

ALTER TABLE CBR_CLOSING_BALANCE_REPORT ADD(
PARENT_INTERNAL_GRD_REF_NO             VARCHAR2(15),
PAY_CUR_DECIMAL                        NUMBER(2),
GRD_TO_GMR_QTY_FACTOR                  NUMBER,
GMR_QTY                                NUMBER(25,10),
OTHER_CHARGES_AMT                      NUMBER(38,18));

ALTER TABLE CBRE_CLOSING_BAL_REPORT_ELE ADD(
BASE_TC_CHARGES_AMT                     NUMBER(38,18),        
ESC_DESC_TC_CHARGES_AMT                 NUMBER(38,18),        
PAYABLE_AMT_PAY_CCY                     NUMBER(38,18),
PAYABLE_AMT_PRICE_CCY                   NUMBER(38,18),
FX_RATE_PRICE_TO_PAY                    NUMBER(38,18));
