ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD(
IS_NEW_MTD_AR VARCHAR2(1) DEFAULT 'N',
IS_NEW_YTD_AR VARCHAR2(1) DEFAULT 'N',
IS_ASSAY_UPDATED_MTD_AR VARCHAR2(1) DEFAULT 'N',		
IS_ASSAY_UPDATED_YTD_AR VARCHAR2(1) DEFAULT 'N');		
