ALTER TABLE ISR_INTRASTAT_GRD ADD INVOICE_DATE_TEMP DATE;
UPDATE ISR_INTRASTAT_GRD SET INVOICE_DATE_TEMP = INVOICE_DATE;
UPDATE ISR_INTRASTAT_GRD SET INVOICE_DATE = NULL;
ALTER TABLE ISR_INTRASTAT_GRD MODIFY INVOICE_DATE DATE;
UPDATE ISR_INTRASTAT_GRD SET INVOICE_DATE = INVOICE_DATE_TEMP;
ALTER TABLE ISR_INTRASTAT_GRD DROP COLUMN INVOICE_DATE_TEMP;
