DROP INDEX IDX_PCDI1;
CREATE INDEX IDX_PCDI1 ON PCDI_PC_DELIVERY_ITEM (DBD_ID,IS_ACTIVE);

DROP INDEX IDX_PCPQ1;
CREATE INDEX IDX_PCPQ1 ON PCPQ_PC_PRODUCT_QUALITY (DBD_ID,IS_ACTIVE);

DROP INDEX IDX_PCPD1;
CREATE INDEX IDX_PCPD1 ON PCPD_PC_PRODUCT_DEFINITION(DBD_ID, IS_ACTIVE, INPUT_OUTPUT);
