CREATE TABLE GAD_GMR_ALOC_DATA(
CORPORATE_ID                VARCHAR2(15),
INTERNAL_GMR_REF_NO         VARCHAR2(15),
ELEMENT_ID                  VARCHAR2(15),
PCBPD_ID                    VARCHAR2(15),
QTY_TO_BE_PRICED            NUMBER(25,10),
PRICE_BASIS                 VARCHAR2(20),
PRODUCT_ID                  VARCHAR2(15),
BASE_QTY_UNIT_ID            VARCHAR2(15),
GPAH_ID                     VARCHAR2(15),
FINAL_PRICE                 NUMBER(25,10),
FINALIZE_DATE               DATE,
FINAL_PRICE_UNIT_ID         VARCHAR2(15),
VALUATION_PRICE_PERCENTAGE  NUMBER(25,10));

CREATE INDEX IDX_GAD1 ON GAD_GMR_ALOC_DATA(CORPORATE_ID);
CREATE INDEX IDX_GAD2 ON GAD_GMR_ALOC_DATA(INTERNAL_GMR_REF_NO,ELEMENT_ID);

CREATE TABLE DD_DUPLICATE_DATA(ID NUMBER);
INSERT INTO DD_DUPLICATE_DATA VALUES(1);
INSERT INTO DD_DUPLICATE_DATA VALUES(2);
INSERT INTO DD_DUPLICATE_DATA VALUES(3);
INSERT INTO DD_DUPLICATE_DATA VALUES(4);
INSERT INTO DD_DUPLICATE_DATA VALUES(5);
INSERT INTO DD_DUPLICATE_DATA VALUES(6);
INSERT INTO DD_DUPLICATE_DATA VALUES(7);
INSERT INTO DD_DUPLICATE_DATA VALUES(8);
COMMIT;

