DELETE from DD_DUPLICATE_DATA;
INSERT INTO DD_DUPLICATE_DATA VALUES(1);
INSERT INTO DD_DUPLICATE_DATA VALUES(2);
INSERT INTO DD_DUPLICATE_DATA VALUES(3);
INSERT INTO DD_DUPLICATE_DATA VALUES(4);
INSERT INTO DD_DUPLICATE_DATA VALUES(5);
INSERT INTO DD_DUPLICATE_DATA VALUES(6);
INSERT INTO DD_DUPLICATE_DATA VALUES(7);
INSERT INTO DD_DUPLICATE_DATA VALUES(8);
COMMIT;
CREATE UNIQUE INDEX IDX_DD ON DD_DUPLICATE_DATA(ID);       

