ALTER TABLE CCCP_CONC_CONTRACT_COG_PRICE ADD(
IS_FINAL_PRICED               VARCHAR2(1),
PAY_IN_PRICE_UNIT_ID          VARCHAR2(15),
PAY_IN_CUR_ID                 VARCHAR2(15),
PAY_IN_CUR_CODE               VARCHAR2(15),
PAY_IN_PRICE_UNIT_WEIGHT      NUMBER(7,2),
PAY_IN_PRICE_UNIT_WT_UNIT_ID  VARCHAR2(15),
PAY_IN_PRICE_UNIT_WEIGHT_UNIT VARCHAR2(15),
FX_PRICE_TO_PAY               NUMBER,
CONTRACT_PRICE_IN_PAY_IN      NUMBER(25,5));

ALTER TABLE CGCP_CONC_GMR_COG_PRICE ADD(
IS_FINAL_PRICED                VARCHAR2(1),
PAY_IN_PRICE_UNIT_ID      VARCHAR2(15),
PAY_IN_CUR_ID                 VARCHAR2(15),
PAY_IN_CUR_CODE               VARCHAR2(15),
PAY_IN_PRICE_UNIT_WEIGHT        NUMBER(7,2),
PAY_IN_PRICE_UNIT_WT_UNIT_ID    VARCHAR2(15),
PAY_IN_PRICE_UNIT_WEIGHT_UNIT    VARCHAR2(15),
FX_PRICE_TO_PAY               NUMBER,
CONTRACT_PRICE_IN_PAY_IN      NUMBER(25,5));

ALTER TABLE BCCP_BASE_CONTRACT_COG_PRICE ADD(
IS_FINAL_PRICED                VARCHAR2(1),
PAY_IN_PRICE_UNIT_ID      VARCHAR2(15),
PAY_IN_CUR_ID                 VARCHAR2(15),
PAY_IN_CUR_CODE               VARCHAR2(15),
PAY_IN_PRICE_UNIT_WEIGHT        NUMBER(7,2),
PAY_IN_PRICE_UNIT_WT_UNIT_ID    VARCHAR2(15),
PAY_IN_PRICE_UNIT_WEIGHT_UNIT    VARCHAR2(15),
FX_PRICE_TO_PAY               NUMBER,
CONTRACT_PRICE_IN_PAY_IN      NUMBER(25,5));

ALTER TABLE BGCP_BASE_GMR_COG_PRICE ADD(
IS_FINAL_PRICED                VARCHAR2(1),
PAY_IN_PRICE_UNIT_ID      VARCHAR2(15),
PAY_IN_CUR_ID                 VARCHAR2(15),
PAY_IN_CUR_CODE               VARCHAR2(15),
PAY_IN_PRICE_UNIT_WEIGHT        NUMBER(7,2),
PAY_IN_PRICE_UNIT_WT_UNIT_ID    VARCHAR2(15),
PAY_IN_PRICE_UNIT_WEIGHT_UNIT    VARCHAR2(15),
FX_PRICE_TO_PAY               NUMBER,
CONTRACT_PRICE_IN_PAY_IN      NUMBER(25,5));

ALTER TABLE AREO_AR_ELEMENT_ORIGINAL ADD(
PRICE_IN_PAY_IN                      NUMBER(25,5));

ALTER TABLE ARE_ARRIVAL_REPORT_ELEMENT ADD(
PRICE_IN_PAY_IN                      NUMBER(25,5));

ALTER TABLE FCEO_FEED_CON_ELEMENT_ORIGINAL ADD(
PRICE_IN_PAY_IN                      NUMBER(25,5));

ALTER TABLE FCE_FEED_CONSUMPTION_ELEMENT ADD(
PRICE_IN_PAY_IN                      NUMBER(25,5));

CREATE TABLE ARG_ARRIVAL_REPORT_GMR(
PROCESS_ID           VARCHAR2(15),
INTERNAL_GMR_REF_NO  VARCHAR2(15),
MTD_YTD              VARCHAR2(3),
PREV_PROCESS_ID      VARCHAR2(15));

CREATE TABLE CPT1_CONC_PRICE_TEMP1
(CORPORATE_ID                            VARCHAR2(15),
PCDI_ID                            VARCHAR2(15),
INTERNAL_CONTRACT_REF_NO        VARCHAR2(15),
ELEMENT_ID                        VARCHAR2(15),
PAYABLE_QTY                        NUMBER(25,10),
PAYABLE_QTY_UNIT_ID                VARCHAR2(15),
CONTRACT_REF_NO                    VARCHAR2(30),
PRODUCT_ID                        VARCHAR2(15),
INSTRUMENT_ID                    VARCHAR2(15),    
INSTRUMENT_NAME                    VARCHAR2(50),
PRICE_SOURCE_ID                    VARCHAR2(15),
PRICE_SOURCE_NAME                VARCHAR2(30),
AVAILABLE_PRICE_ID                VARCHAR2(15),
AVAILABLE_PRICE_NAME            VARCHAR2(15),        
PRICE_UNIT_NAME                    VARCHAR2(50),
PRICE_UNIT_ID                    VARCHAR2(15),
DELIVERY_CALENDER_ID            VARCHAR2(15),
IS_DAILY_CAL_APPLICABLE            VARCHAR2(1),
IS_MONTHLY_CAL_APPLICABLE        VARCHAR2(1),
PRICE_OPTION_CALL_OFF_STATUS    VARCHAR2(20));


CREATE TABLE CPT2_CONC_PRICE_TEMP2(
CORPORATE_ID                            VARCHAR2(15),
PCDI_ID                                 VARCHAR2(15),
ELEMENT_ID                              VARCHAR2(15),
POCH_ID                                 VARCHAR2(15),
POFH_ID                                 VARCHAR2(15),
PCBPD_ID                                VARCHAR2(15),
PRICE_BASIS                             VARCHAR2(30),
PRICE_VALUE                             NUMBER(25,5),
PRICE_UNIT_ID                           VARCHAR2(15),
QTY_TO_BE_PRICED                        NUMBER(25,10),
FINAL_PRICE                             NUMBER(25,5),
FINALIZE_DATE                           DATE,
FINAL_PRICE_UNIT_ID                     VARCHAR2(15),
VALUATION_PRICE_PERCENTAGE              NUMBER(25,5),
PAY_IN_PRICE_UNIT_ID                    VARCHAR2(15),
FINAL_PRICE_IN_PAY_IN_CUR               NUMBER(25,5),
PAY_IN_CUR_ID                           VARCHAR2(15),
PAY_IN_CUR_CODE                         VARCHAR2(15),
PAY_IN_PRICE_UNIT_WEIGHT                NUMBER(7,2),
PAY_IN_PRICE_UNIT_WT_UNIT_ID            VARCHAR2(15),
PAY_IN_PRICE_UNIT_WEIGHT_UNIT           VARCHAR2(15),
FX_PRICE_TO_PAY_IN                      NUMBER);


DROP TABLE GAD_GMR_ALOC_DATA;

CREATE TABLE GAD_GMR_ALOC_DATA(
CORPORATE_ID                VARCHAR2(15),
INTERNAL_GMR_REF_NO         VARCHAR2(15),
ELEMENT_ID                  VARCHAR2(15),
PCBPD_ID                    VARCHAR2(15),
QTY_TO_BE_PRICED            NUMBER(25,10),
PRICE_BASIS                 VARCHAR2(20),
PRODUCT_ID                  VARCHAR2(15),
BASE_QTY_UNIT_ID            VARCHAR2(15),
GPAH_ID                     VARCHAR2(15),
FINAL_PRICE                 NUMBER(25,10),
FINALIZE_DATE               DATE,
FINAL_PRICE_UNIT_ID         VARCHAR2(15),
VALUATION_PRICE_PERCENTAGE  NUMBER(25,10),
PAY_IN_PRICE_UNIT_ID        VARCHAR2(30),
FINAL_PRICE_IN_PAY_IN_CUR   NUMBER(25,5),
PAY_IN_CUR_ID               VARCHAR2(15),
PAY_IN_CUR_CODE               VARCHAR2(15),
PAY_IN_PRICE_UNIT_WEIGHT        NUMBER(7,2),
PAY_IN_PRICE_UNIT_WT_UNIT_ID    VARCHAR2(15),
PAY_IN_PRICE_UNIT_WEIGHT_UNIT    VARCHAR2(15),
FX_PRICE_TO_PAY_IN               NUMBER);


CREATE INDEX IDX_CPT1_1 ON CPT1_CONC_PRICE_TEMP1(CORPORATE_ID);
CREATE INDEX IDX_CPT2_1 ON CPT2_CONC_PRICE_TEMP2(CORPORATE_ID);
CREATE INDEX IDX_CPT21_2 ON CPT2_CONC_PRICE_TEMP2(PCDI_ID,ELEMENT_ID);

ALTER TABLE GMR_GOODS_MOVEMENT_RECORD DROP COLUMN NO_OF_SUBLOTS;

ALTER TABLE PA_PURCHASE_ACCURAL ADD(
CONTRACT_PRICE_IN_PAY_IN        NUMBER(25,5),
PAY_IN_PRICE_UNIT_ID            VARCHAR2(15),
PAY_IN_PRICE_UNIT_NAME          VARCHAR2(50));

ALTER TABLE PA_PURCHASE_ACCURAL_GMR ADD(
CONTRACT_PRICE_IN_PAY_IN        NUMBER(25,5),
PAY_IN_PRICE_UNIT_ID            VARCHAR2(15),
PAY_IN_PRICE_UNIT_NAME          VARCHAR2(50));

ALTER TABLE PATD_PA_TEMP_DATA ADD(
GMR_PRICE_UNIT_WEIGHT         NUMBER(7,2),      
PAY_IN_PRICE_UNIT_WEIGHT      NUMBER(7,2),
PAY_IN_PRICE_UNIT_ID          VARCHAR2 (15),        
PAY_IN_PRICE_UNIT_WT_UNIT_ID  VARCHAR2 (15),        
PAY_IN_PRICE_UNIT_WEIGHT_UNIT VARCHAR2 (15),        
GMR_PRICE_IN_PAY_IN           NUMBER(25,5),
FX_PRICE_TO_PAY               NUMBER,
PAY_IN_PRICE_UNIT_NAME        VARCHAR2(50));