CREATE TABLE ART_ARRIVAL_REPORT_TEMP(
GMR_REF_NO                  VARCHAR2(30),
INTERNAL_GMR_REF_NO         VARCHAR2(15),
INTERNAL_GRD_REF_NO         VARCHAR2(15),
INTERNAL_STOCK_REF_NO       VARCHAR2(30),
CORPORATE_ID                VARCHAR2(15),
WAREHOUSE_PROFILE_ID        VARCHAR2(15),
WAREHOUSE_NAME              VARCHAR2(100),
SHED_ID                     VARCHAR2(15),
STORAGE_LOCATION_NAME       VARCHAR2(50),
PRODUCT_ID                  VARCHAR2(15),
PRODUCT_NAME                VARCHAR2(200),
QUALITY_ID                  VARCHAR2(15),
QUALITY_NAME                VARCHAR2(200),
WET_QTY                     NUMBER(25,5),
DRY_QTY                     NUMBER(25,5),
QTY_UNIT_ID                 VARCHAR2(15),
QTY_UNIT           VARCHAR2(15),
ELEMENT_ID                  VARCHAR2(15),
ATTRIBUTE_NAME              VARCHAR2(30),
UNDERLYING_PRODUCT_ID       VARCHAR2(15),
UNDERLYING_PRODUCT_NAME     VARCHAR2(200),
BASE_QUANTITY_UNIT_ID       VARCHAR2(15),
BASE_QUANTITY_UNIT          VARCHAR2(15),
ASSAY_CONTENT               NUMBER(25,5),
ASSAY_QTY_UNIT_ID           VARCHAR2(15),
ASSAY_QTY_UNIT     VARCHAR2(15),
PAYABLE_QTY                 NUMBER(25,5),
PAYABLE_QTY_UNIT_ID         VARCHAR2(15),
PAYABLE_QTY_UNIT            VARCHAR2(15),
ARRIVAL_STATUS              VARCHAR2(50),
CONC_BASE_QTY_UNIT_ID       VARCHAR2(15),
CONC_BASE_QTY_UNIT          VARCHAR2(15),
GRD_BASE_QTY_CONV_FACTOR    NUMBER,
PCDI_ID                     VARCHAR2(15),
PAY_CUR_ID                  VARCHAR2(15),
PAY_CUR_CODE                VARCHAR2(15),
PAY_CUR_DECIMALS            NUMBER(2),
SECTION_NAME                VARCHAR2(15),
GRD_TO_GMR_QTY_FACTOR       NUMBER,
QTY_TYPE                    VARCHAR2(20),
GMR_WET_QTY                 NUMBER(25,5),
ARRIVAL_OR_DELIVERY         VARCHAR2(15));     


ALTER TABLE DGRD_DELIVERED_GRD ADD(
DGRD_TO_GMR_QTY_FACTOR           NUMBER,
BASE_QTY_CONV_FACTOR             NUMBER,
NET_WEIGHT_UNIT                  VARCHAR2(15),
DRY_QTY                          NUMBER(35,10));

ALTER TABLE ARO_AR_ORIGINAL ADD ARRIVAL_OR_DELIVERY VARCHAR2(15);
ALTER TABLE AR_ARRIVAL_REPORT ADD ARRIVAL_OR_DELIVERY VARCHAR2(15);

CREATE INDEX IDX_ART1 ON ART_ARRIVAL_REPORT_TEMP(CORPORATE_ID);

UPDATE AR_ARRIVAL_REPORT AR
SET AR.ARRIVAL_OR_DELIVERY ='Arrival';
UPDATE ARO_AR_ORIGINAL ARO
SET ARO.ARRIVAL_OR_DELIVERY ='Arrival';
COMMIT;