ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD PCDI_ID VARCHAR2(15);
ALTER TABLE BGCP_BASE_GMR_COG_PRICE ADD PCDI_ID VARCHAR2(15);
ALTER TABLE CGCP_CONC_GMR_COG_PRICE ADD PCDI_ID VARCHAR2(15);

CREATE TABLE TIP_TEMP_INSTRUMENT_PRICE(
CORPORATE_ID            VARCHAR2(15),
INSTRUMENT_ID           VARCHAR2(15),
PRICE                    NUMBER(25,5),
PRICE_UNIT_ID            VARCHAR2(15),
DATA_MISSING_FOR        VARCHAR2(500));
