DROP MATERIALIZED VIEW FMUH_FREE_METAL_UTILITY_HEADER;
DROP TABLE FMUH_FREE_METAL_UTILITY_HEADER;
CREATE MATERIALIZED VIEW  FMUH_FREE_METAL_UTILITY_HEADER  REFRESH FAST ON DEMAND WITH PRIMARY KEY AS  SELECT * FROM  FMUH_FREE_METAL_UTILITY_HEADER@eka_appdb;

DROP MATERIALIZED VIEW FMED_FREE_METAL_ELEMT_DETAILS;
DROP TABLE FMED_FREE_METAL_ELEMT_DETAILS;
CREATE MATERIALIZED VIEW  FMED_FREE_METAL_ELEMT_DETAILS  REFRESH FAST ON DEMAND WITH PRIMARY KEY AS  SELECT * FROM  FMED_FREE_METAL_ELEMT_DETAILS@eka_appdb;

DROP MATERIALIZED VIEW FMPFH_PRICE_FIXATION_HEADER;
DROP TABLE FMPFH_PRICE_FIXATION_HEADER;
CREATE MATERIALIZED VIEW  FMPFH_PRICE_FIXATION_HEADER  REFRESH FAST ON DEMAND WITH PRIMARY KEY AS  SELECT * FROM  FMPFH_PRICE_FIXATION_HEADER@eka_appdb;




CREATE TABLE CSFM_CONT_STATUS_FREE_METAL
(PROCESS_ID                VARCHAR2 (15),
 CORPORATE_ID              VARCHAR2 (15),
 CORPORATE_NAME            VARCHAR2 (100),
 EOD_TRADE_DATE            DATE,
 UTILITY_REF_NO            VARCHAR2 (15),
 ELEMENT_ID                VARCHAR2 (15), 
 ELEMENT_NAME              VARCHAR2 (15), 
 PAYABLE_QTY               NUMBER(25,10),
 PAYABLE_QTY_UNIT_ID       VARCHAR2 (15), 
 PAYABLE_QTY_UNIT          VARCHAR2 (15), 
 PRICED_QTY                NUMBER(25,10),
 UNPRICED_QTY              NUMBER(25,10),
 ELEMENT_DESC              VARCHAR2(200),
 SMELTER_ID                VARCHAR2(15),
 SMELTER_NAME              VARCHAR2(200)
 );

CREATE INDEX IDX_CSFM on CSFM_CONT_STATUS_FREE_METAL(PROCESS_ID);
CREATE INDEX IDX_CSFM1 on CSFM_CONT_STATUS_FREE_METAL(CORPORATE_ID);

