CREATE TABLE IIDS_IID_SUMMARY (
PROCESS_ID                    VARCHAR2(15),
INTERNAL_INVOICE_REF_NO       VARCHAR2(15),
INTERNAL_GMR_REF_NO           VARCHAR2(15),
GMR_INVOICED_QTY              NUMBER(25,10),
TOTAL_INVOICED_QTY            NUMBER(25,10),
INVOICED_QTY_UNIT_ID          VARCHAR2(15),
INVOICE_CUR_ID                VARCHAR2(15),
CONTRACT_TYPE                 VARCHAR2(20));

CREATE TABLE IOCD_IOC_DETAILS (
PROCESS_ID                      VARCHAR2(15),
INTERNAL_INVOICE_REF_NO         VARCHAR2(15),
INTERNAL_GMR_REF_NO             VARCHAR2(15),
GMR_INVOICED_QTY                NUMBER(25,10),
TOTAL_INVOICED_QTY              NUMBER(25,10),
INVOICE_CUR_ID                  VARCHAR2(15),
INVOICED_QTY_UNIT_ID            VARCHAR2(15),
OTHER_CHARGE_COST_ID            VARCHAR2(15),   
COST_COMPONENT_NAME             VARCHAR2(100),
AMOUNT_IN_INV_CUR               NUMBER(25,10),
IS_CONTAINER_FREIGHT_CHARGE     VARCHAR2(1),
IS_CONTAINER_CHARGE             VARCHAR2(1),
IS_FREIGHT_CHARGE               VARCHAR2(1),
CHARGE_RATE                     NUMBER,
CONTRACT_TYPE                   VARCHAR2(20));

CREATE INDEX IDX_IIDS1 ON IIDS_IID_SUMMARY (PROCESS_ID,CONTRACT_TYPE);
CREATE INDEX IDX_IOCS1 ON IOCD_IOC_DETAILS (PROCESS_ID,CONTRACT_TYPE);

ALTER TABLE ARO_AR_ORIGINAL ADD FREIGHT_CONTAINER_CHARGE_AMT NUMBER(25,10);
ALTER TABLE AR_ARRIVAL_REPORT ADD FREIGHT_CONTAINER_CHARGE_AMT NUMBER(25,10);

ALTER TABLE FCO_FEED_CONSUMPTION_ORIGINAL ADD FREIGHT_CONTAINER_CHARGE_AMT NUMBER(25,10);
ALTER TABLE FC_FEED_CONSUMPTION ADD FREIGHT_CONTAINER_CHARGE_AMT NUMBER(25,10);

ALTER TABLE CBR_CLOSING_BALANCE_REPORT ADD FREIGHT_CONTAINER_CHARGE_AMT NUMBER(25,10);

ALTER TABLE FCOT_FCO_TEMP ADD FREIGHT_CONTAINER_CHARGE_AMT NUMBER(25,10);

