ALTER TABLE PFRD_PRICE_FIX_REPORT_DETAIL ADD FIXED_QTY_UNIT_ID VARCHAR2(15);

ALTER TABLE PFRH_PRICE_FIX_REPORT_HEADER ADD(
WAP_PURCHASE_PRICE_FIXTION_NEW NUMBER(25,5),
WAP_SALES_PRICE_FIXTION_NEW NUMBER(25,5));
