ALTER TABLE PFRD_PRICE_FIX_REPORT_DETAIL ADD PROD_BASE_TO_PRICE_WT_FACTOR NUMBER;
ALTER TABLE MBV_ALLOCATION_REPORT MODIFY PF_REF_NO VARCHAR2(30);
ALTER TABLE PFRD_PRICE_FIX_REPORT_DETAIL ADD IS_ACTIVE VARCHAR2(1);
ALTER TABLE MBV_ALLOCATION_REPORT ADD IS_ACTIVE VARCHAR2(1);
