ALTER TABLE MBV_PHY_POSTION_DIFF_REPORT ADD(
PRODUCT_BASE_QTY_FACTOR              NUMBER,       
PRODUCT_BASE_QTY_UNIT_ID             VARCHAR2(15),
PRODUCT_BASE_QTY_UNIT                VARCHAR2(15));
