drop table CPBU_CORP_PENALITY_BASE_UNIT;
create table CPBU_CORP_PENALITY_BASE_UNIT
(
CORPORATE_ID            VARCHAR2 (15 Char),
ELEMENT_ID              VARCHAR2 (15 Char),
ELEMENT_NAME            VARCHAR2 (50 Char),
BASE_QTY_UNIT_ID        VARCHAR2 (15 Char),
BASE_QTY_UNIT           VARCHAR2 (15 Char)
);

CREATE Unique index idx_cpbu1 on CPBU_CORP_PENALITY_BASE_UNIT(CORPORATE_ID,ELEMENT_ID);

alter table GEPC_GMR_ELEMENT_PC_CHARGES add ASSAY_QTY NUMBER (25,5);
alter table GEPC_GMR_ELEMENT_PC_CHARGES  add TYPICAL NUMBER (25,10);
alter table GEPC_GMR_ELEMENT_PC_CHARGES  add UNIT_OF_MEASURE VARCHAR2 (15 Char);
alter table GEPC_GMR_ELEMENT_PC_CHARGES  add RATIO_NAME  VARCHAR2 (50 Char);

alter table ART_ARRIVAL_REPORT_TEMP  add TYPICAL NUMBER (25,10);
alter table ART_ARRIVAL_REPORT_TEMP  add UNIT_OF_MEASURE VARCHAR2 (15 Char);
alter table ART_ARRIVAL_REPORT_TEMP  add RATIO_NAME  VARCHAR2 (50 Char);

alter table AREO_AR_ELEMENT_ORIGINAL  add TYPICAL NUMBER (25,10);
alter table AREO_AR_ELEMENT_ORIGINAL  add UNIT_OF_MEASURE VARCHAR2 (15 Char);
alter table AREO_AR_ELEMENT_ORIGINAL  add RATIO_NAME  VARCHAR2 (50 Char);

alter table ARE_ARRIVAL_REPORT_ELEMENT  add TYPICAL NUMBER (25,10);
alter table ARE_ARRIVAL_REPORT_ELEMENT  add UNIT_OF_MEASURE VARCHAR2 (15 Char);
alter table ARE_ARRIVAL_REPORT_ELEMENT  add RATIO_NAME  VARCHAR2 (50 Char);


alter table ART_ARRIVAL_REPORT_TEMP add CONTRACT_REF_NO VARCHAR2 (50 Char);
alter table ART_ARRIVAL_REPORT_TEMP add INTERNAL_CONTRACT_REF_NO VARCHAR2 (15 Char);
alter table ART_ARRIVAL_REPORT_TEMP add CP_ID VARCHAR2 (20 Char);
alter table ART_ARRIVAL_REPORT_TEMP add CP_NAME VARCHAR2 (65 Char); 

 
alter table ART1_ARRIVAL_REPORT_TEMP1 add CONTRACT_REF_NO VARCHAR2 (50 Char);
alter table ART1_ARRIVAL_REPORT_TEMP1 add INTERNAL_CONTRACT_REF_NO VARCHAR2 (15 Char);
alter table ART1_ARRIVAL_REPORT_TEMP1 add CP_ID VARCHAR2 (20 Char);
alter table ART1_ARRIVAL_REPORT_TEMP1 add CP_NAME VARCHAR2 (65 Char); 

 
alter table ARO_AR_ORIGINAL add CONTRACT_REF_NO VARCHAR2 (50 Char);
alter table ARO_AR_ORIGINAL add INTERNAL_CONTRACT_REF_NO VARCHAR2 (15 Char);
alter table ARO_AR_ORIGINAL add CP_ID VARCHAR2 (20 Char);
alter table ARO_AR_ORIGINAL add CP_NAME VARCHAR2 (65 Char); 

 
alter table AR_ARRIVAL_REPORT add CONTRACT_REF_NO VARCHAR2 (50 Char);
alter table AR_ARRIVAL_REPORT add INTERNAL_CONTRACT_REF_NO VARCHAR2 (15 Char);
alter table AR_ARRIVAL_REPORT add CP_ID VARCHAR2 (20 Char);
alter table AR_ARRIVAL_REPORT add CP_NAME VARCHAR2 (65 Char);


alter table FCT_FC_TEMP add TYPICAL NUMBER (25,10);
alter table FCT_FC_TEMP  add UNIT_OF_MEASURE VARCHAR2 (15 Char);
alter table FCT_FC_TEMP  add RATIO_NAME  VARCHAR2 (50 Char);

alter table FCE_FEED_CONSUMPTION_ELEMENT add TYPICAL NUMBER (25,10);
alter table FCE_FEED_CONSUMPTION_ELEMENT  add UNIT_OF_MEASURE VARCHAR2 (15 Char);
alter table FCE_FEED_CONSUMPTION_ELEMENT  add RATIO_NAME  VARCHAR2 (50 Char);
 
alter table FCEO_FEED_CON_ELEMENT_ORIGINAL add TYPICAL NUMBER (25,10);
alter table FCEO_FEED_CON_ELEMENT_ORIGINAL  add UNIT_OF_MEASURE VARCHAR2 (15 Char);
alter table FCEO_FEED_CON_ELEMENT_ORIGINAL  add RATIO_NAME  VARCHAR2 (50 Char);

alter table FCEOT_FCEO_TEMP add TYPICAL NUMBER (25,10);
alter table FCEOT_FCEO_TEMP  add UNIT_OF_MEASURE VARCHAR2 (15 Char);
alter table FCEOT_FCEO_TEMP  add RATIO_NAME  VARCHAR2 (50 Char);

alter table FCT_FC_TEMP add CONTRACT_REF_NO VARCHAR2 (50 Char);
alter table FCT_FC_TEMP add INTERNAL_CONTRACT_REF_NO VARCHAR2 (15 Char);
alter table FCT_FC_TEMP add CP_ID VARCHAR2 (20 Char);
alter table FCT_FC_TEMP add CP_NAME VARCHAR2 (65 Char);


alter table FCT1_FC_TEMP1 add CONTRACT_REF_NO VARCHAR2 (50 Char);
alter table FCT1_FC_TEMP1 add INTERNAL_CONTRACT_REF_NO VARCHAR2 (15 Char);
alter table FCT1_FC_TEMP1 add CP_ID VARCHAR2 (20 Char);
alter table FCT1_FC_TEMP1 add CP_NAME VARCHAR2 (65 Char);  


alter table FCO_FEED_CONSUMPTION_ORIGINAL add CONTRACT_REF_NO VARCHAR2 (50 Char);
alter table FCO_FEED_CONSUMPTION_ORIGINAL add INTERNAL_CONTRACT_REF_NO VARCHAR2 (15 Char);
alter table FCO_FEED_CONSUMPTION_ORIGINAL add CP_ID VARCHAR2 (20 Char);
alter table FCO_FEED_CONSUMPTION_ORIGINAL add CP_NAME VARCHAR2 (65 Char);  

alter table FC_FEED_CONSUMPTION add CONTRACT_REF_NO VARCHAR2 (50 Char);
alter table FC_FEED_CONSUMPTION add INTERNAL_CONTRACT_REF_NO VARCHAR2 (15 Char);
alter table FC_FEED_CONSUMPTION add CP_ID VARCHAR2 (20 Char);
alter table FC_FEED_CONSUMPTION add CP_NAME VARCHAR2 (65 Char);  

alter table FCOT_FCO_TEMP add CONTRACT_REF_NO VARCHAR2 (50 Char);
alter table FCOT_FCO_TEMP add INTERNAL_CONTRACT_REF_NO VARCHAR2 (15 Char);
alter table FCOT_FCO_TEMP add CP_ID VARCHAR2 (20 Char);
alter table FCOT_FCO_TEMP add CP_NAME VARCHAR2 (65 Char); 

DROP TABLE PED_PENALTY_ELEMENT_DETAILS;
CREATE TABLE PED_PENALTY_ELEMENT_DETAILS (
PROCESS_ID                        VARCHAR2(15 Char),
INTERNAL_GMR_REF_NO               VARCHAR2(15 Char),
INTERNAL_GRD_REF_NO               VARCHAR2(15 Char),
ELEMENT_ID                        VARCHAR2(15 Char),
ELEMENT_NAME                      VARCHAR2(30 Char),
WEG_AVG_PRICING_ASSAY_ID          VARCHAR2(15 Char),
ASSAY_QTY                         NUMBER(25,10),            
ASSAY_QTY_UNIT_ID                 VARCHAR2(15 Char),
GRD_WET_QTY                       NUMBER(25,10),
GRD_DRY_QTY                       NUMBER(25,10),
GRD_QTY_UNIT_ID                   VARCHAR2(15 Char),
PARENT_STOCK_REF_NO               VARCHAR2(15Char),
TYPICAL                           NUMBER (25,10),
UNIT_OF_MEASURE                   VARCHAR2 (15 Char),
RATIO_NAME                        VARCHAR2 (50 Char)
);


CREATE INDEX IDX_PED1 ON PED_PENALTY_ELEMENT_DETAILS(PROCESS_ID);


begin
delete from CPBU_CORP_PENALITY_BASE_UNIT;
 for cc in (select akc.corporate_id from ak_corporate@eka_appdb akc where akc.is_active = 'Y' and akc.is_deleted = 'N' and akc.is_internal_corporate = 'N' )
        loop
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-323', 'Al2O3', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-324', 'As', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-326', 'Ba', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-327', 'BaO', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-328', 'Be', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-329', 'Bi', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-331', 'C', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-332', 'CaO', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-333', 'Cd', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-334', 'Cl', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-335', 'Co', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-336', 'Cr', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-338', 'F', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-339', 'Fe', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-341', 'Ga', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-342', 'Ge', 'QUM-70','Kg');

Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-346', 'Hg', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-347', 'In', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-348', 'Ir', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-349', 'K', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-350', 'K2O', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-351', 'La', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-352', 'Li', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-353', 'Mg', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-354', 'MgO', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-355', 'Mn', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-356', 'MnO', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-357', 'Mo', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-358', 'Na', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-359', 'Na2O', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-360', 'NaO', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-361', 'Ni', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-362', 'P', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-363', 'P2O5', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-369', 'S', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-370', 'Sb', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-372', 'Si', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-373', 'SiO2', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-374', 'Sn', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-375', 'Sr', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-377', 'Ti', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-378', 'TiO2', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-379', 'Tl', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-380', 'V', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-381', 'Y', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-322', 'Al', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-383', 'Zr', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-401', 'H2O', 'QUM-70','Kg');


Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-581', 'Br', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-421', 'FeO', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-502', 'CIN', 'QUM-70','Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID , BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-521', 'U', 'QUM-70','Kg');
 
 --------------------
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID, BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-325', 'Au', 'QUM-70', 'Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID, BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-337', 'Cu', 'QUM-68', 'MT');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID, BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-364', 'Pb', 'QUM-68', 'MT');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID, BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-365', 'Pd', 'QUM-70', 'Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID, BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-366', 'Pt', 'QUM-70', 'Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID, BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-367', 'Rh', 'QUM-70', 'Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID, BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-368', 'Ru', 'QUM-68', 'MT');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID, BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-371', 'Se', 'QUM-70', 'Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID, BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-376', 'Te', 'QUM-70', 'Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID, BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-321', 'Ag', 'QUM-70', 'Kg');
Insert into CPBU_CORP_PENALITY_BASE_UNIT
   (CORPORATE_ID, ELEMENT_ID, ELEMENT_NAME, BASE_QTY_UNIT_ID, BASE_QTY_UNIT)
 Values
   (cc.CORPORATE_ID, 'AML-382', 'Zn', 'QUM-68', 'MT');
 
end loop;
COMMIT;
end;