DROP MATERIALIZED VIEW  IID_INVOICABLE_ITEM_DETAILS;
CREATE MATERIALIZED VIEW  IID_INVOICABLE_ITEM_DETAILS  REFRESH FAST ON DEMAND WITH PRIMARY KEY AS  SELECT * FROM  IID_INVOICABLE_ITEM_DETAILS@eka_appdb;


ALTER TABLE TGI_TEMP_GMR_INVOICE
MODIFY(INVOICE_ITEM_AMOUNT NUMBER(35,10));

ALTER TABLE ISR2_ISR_INVOICE
MODIFY(INVOICE_AMT NUMBER(35,10));