alter table GMR_GOODS_MOVEMENT_RECORD add PRODUCT_NAME 	    VARCHAR2 (200 Char);
alter table PROCESS_GMR add PRODUCT_NAME 		    VARCHAR2 (200 Char);
alter table GMR_GOODS_MOVEMENT_RECORD add QUALITY_ID 	    VARCHAR2 (15 Char);
alter table PROCESS_GMR add QUALITY_ID 			    VARCHAR2 (15 Char);
alter table TGC_TEMP_GMR_CHARGES add PRODUCT_ID	            VARCHAR2 (15 Char);	
alter table TGC_TEMP_GMR_CHARGES add PRODUCT_NAME	    VARCHAR2 (200 Char);
alter table TGC_TEMP_GMR_CHARGES add QUALITY_ID	            VARCHAR2 (15 Char);
alter table TGC_TEMP_GMR_CHARGES add QUALITY_NAME           VARCHAR2 (200 Char);
alter table TGC_TEMP_GMR_CHARGES add WAREHOUSE_ID	    VARCHAR2 (50 Char);
alter table TGC_TEMP_GMR_CHARGES add WAREHOUSE_NAME	    VARCHAR2 (100 Char);
alter table TGC_TEMP_GMR_CHARGES add GMR_REF_NO	            VARCHAR2 (30 Char);
alter table TGC_TEMP_GMR_CHARGES add CORPORATE_NAME	    VARCHAR2 (100 Char);
alter table TGC_TEMP_GMR_CHARGES add EOD_TRADE_DATE	    DATE;	
alter table TGC_TEMP_GMR_CHARGES add ELEMENT_NAME	    VARCHAR2 (30 Char);	
alter table TGC_TEMP_GMR_CHARGES add PROCESS_ID	            VARCHAR2 (15 Char);
alter table TGC_TEMP_GMR_CHARGES add TOLLING_STOCK_TYPE	    VARCHAR2 (30 Char);
alter table TGC_TEMP_GMR_CHARGES add IS_FINAL_INVOICED      VARCHAR2 (1 Char);
alter table TGC_TEMP_GMR_CHARGES add PAY_CUR_CODE	    VARCHAR2 (15 Char);
alter table TGC_TEMP_GMR_CHARGES add OTHER_CHARGES_AMT	    NUMBER (38,18);



alter table PA_PURCHASE_ACCURAL_GMR add BASE_QTY_UNIT_ID   VARCHAR2 (15 Char);      
alter table PA_PURCHASE_ACCURAL_GMR add BASE_QTY_UNIT      VARCHAR2 (15 Char);
alter table PA_PURCHASE_ACCURAL_GMR add ASSAY_QTY_BASE     NUMBER (25,5);
alter table PA_PURCHASE_ACCURAL_GMR add PAYABLE_QTY_BASE   NUMBER (25,5);

alter table TGC_TEMP_GMR_CHARGES add QTY_TYPE           VARCHAR2(30 Char);
alter table TGC_TEMP_GMR_CHARGES add BASE_QTY_UNIT_ID   VARCHAR2 (15 Char);      
alter table TGC_TEMP_GMR_CHARGES add BASE_QTY_UNIT      VARCHAR2 (15 Char);
alter table TGC_TEMP_GMR_CHARGES add ASSAY_QTY_BASE     NUMBER (25,5);
alter table TGC_TEMP_GMR_CHARGES add PAYABLE_QTY_BASE   NUMBER (25,5);

CREATE TABLE ARO_AR_ORIGINAL_REPORT
(
  PROCESS_ID                    VARCHAR2(15 CHAR),
  EOD_TRADE_DATE                DATE,
  CORPORATE_ID                  VARCHAR2(15 CHAR),
  CORPORATE_NAME                VARCHAR2(100 CHAR),
  GMR_REF_NO                    VARCHAR2(30 CHAR),
  INTERNAL_GMR_REF_NO           VARCHAR2(15 CHAR),
  PRODUCT_ID                    VARCHAR2(15 CHAR),
  PRODUCT_NAME                  VARCHAR2(200 CHAR),
  QUALITY_ID                    VARCHAR2(15 CHAR),
  QUALITY_NAME                  VARCHAR2(200 CHAR),
  ARRIVAL_STATUS                VARCHAR2(100 CHAR),
  WAREHOUSE_ID                  VARCHAR2(50 CHAR),
  WAREHOUSE_NAME                VARCHAR2(100 CHAR),
  SHED_ID                       VARCHAR2(15 CHAR),
  SHED_NAME                     VARCHAR2(50 CHAR),  
  CONC_BASE_QTY_UNIT_ID         VARCHAR2(15 CHAR),
  CONC_BASE_QTY_UNIT            VARCHAR2(15 CHAR),
  OTHER_CHARGES_AMT             NUMBER(38,18),
  PAY_CUR_ID                    VARCHAR2(15 CHAR),
  PAY_CUR_CODE                  VARCHAR2(15 CHAR),
  PAY_CUR_DECIMAL               NUMBER(10), 
  ARRIVAL_OR_DELIVERY           VARCHAR2(15 CHAR),
  FREIGHT_CONTAINER_CHARGE_AMT  NUMBER(25,10),
  CONTRACT_REF_NO               VARCHAR2(50 CHAR),
  INTERNAL_CONTRACT_REF_NO      VARCHAR2(15 CHAR),
  CP_ID                         VARCHAR2(20 CHAR),
  CP_NAME                       VARCHAR2(65 CHAR)
);

CREATE TABLE AREOR_AR_ELE_ORIGINAL_REPORT
(
  PROCESS_ID                VARCHAR2(15 CHAR),
  INTERNAL_GMR_REF_NO       VARCHAR2(15 CHAR), 
  ELEMENT_ID                VARCHAR2(15 CHAR),
  ELEMENT_NAME              VARCHAR2(30 CHAR),
  ASSAY_QTY                 NUMBER(25,5), 
  PAYABLE_QTY               NUMBER(25,5), 
  SECTION_NAME              VARCHAR2(15 CHAR),  
  PAYABLE_AMT_PRICE_CCY     NUMBER(38,18),
  PAYABLE_AMT_PAY_CCY       NUMBER(38,18),  
  BASE_TC_CHARGES_AMT       NUMBER(38,18),
  ESC_DESC_TC_CHARGES_AMT   NUMBER(38,18),
  RC_CHARGES_AMT            NUMBER(38,18),
  PC_CHARGES_AMT            NUMBER(38,18),
  ELEMENT_BASE_QTY_UNIT_ID  VARCHAR2(15 CHAR),
  ELEMENT_BASE_QTY_UNIT     VARCHAR2(15 CHAR)  
);




CREATE TABLE FOR_FEED_ORIGINAL_REPORT
(
  PROCESS_ID                    VARCHAR2(15 CHAR),
  EOD_TRADE_DATE                DATE,
  CORPORATE_ID                  VARCHAR2(15 CHAR),
  CORPORATE_NAME                VARCHAR2(100 CHAR),   
  PRODUCT_ID                    VARCHAR2(15 CHAR),
  PRODUCT_NAME                  VARCHAR2(200 CHAR),
  QUALITY_ID                    VARCHAR2(15 CHAR),
  QUALITY_NAME                  VARCHAR2(200 CHAR),  
  PARENT_GMR_REF_NO             VARCHAR2(30 CHAR),
  WAREHOUSE_ID                  VARCHAR2(50 CHAR),
  WAREHOUSE_NAME                VARCHAR2(100 CHAR),  
  CONC_BASE_QTY_UNIT_ID         VARCHAR2(15 CHAR),
  CONC_BASE_QTY_UNIT            VARCHAR2(15 CHAR), 
  PAY_CUR_ID                    VARCHAR2(15 CHAR),
  PAY_CUR_CODE                  VARCHAR2(15 CHAR),
  PAY_CUR_DECIMAL               NUMBER(2),
  PARENT_INTERNAL_GMR_REF_NO    VARCHAR2(15 CHAR),  
  OTHER_CHARGES_AMT             NUMBER(38,18)
);

CREATE TABLE FEOR_FEED_ELE_ORIGINAL_REPORT
(
  PROCESS_ID                    VARCHAR2(15 CHAR), 
  ELEMENT_ID                    VARCHAR2(15 CHAR),
  ELEMENT_NAME                  VARCHAR2(30 CHAR),
  ASSAY_QTY                     NUMBER(25,5), 
  PAYABLE_QTY                   NUMBER(25,5),   
  PAYABLE_RETURNABLE_TYPE       VARCHAR2(30 CHAR), 
  PARENT_INTERNAL_GMR_REF_NO    VARCHAR2(15 CHAR), 
  SECTION_NAME                  VARCHAR2(15 CHAR),
  QTY_TYPE                      VARCHAR2(10 CHAR),  
  PAYABLE_AMT_PRICE_CCY         NUMBER(38,18),
  PAYABLE_AMT_PAY_CCY           NUMBER(38,18), 
  BASE_TC_CHARGES_AMT           NUMBER(38,18),
  ESC_DESC_TC_CHARGES_AMT       NUMBER(38,18),
  RC_CHARGES_AMT                NUMBER(38,18),
  PC_CHARGES_AMT                NUMBER(38,18),
  ELEMENT_BASE_QTY_UNIT_ID      VARCHAR2(15 CHAR),
  ELEMENT_BASE_QTY_UNIT         VARCHAR2(15 CHAR) 
);


alter table PROCESS_GMR add  IS_NEW_INVOICE  CHAR(1);
alter table GMR_GOODS_MOVEMENT_RECORD add IS_NEW_INVOICE  CHAR(1);
alter table TGC_TEMP_GMR_CHARGES add IS_NEW_INVOICE  CHAR(1);
alter table TGC_TEMP_GMR_CHARGES add FREIGHT_CONTAINER_CHARGE_AMT NUMBER(25,10);
alter table TGC_TEMP_GMR_CHARGES add PAYABLE_AMOUNT NUMBER(25,10);



    




