drop table gmr_rc_cont;
CREATE TABLE GMR_RC_CONT
(
  CORPORATE_ID                  VARCHAR2(50),
  PROCESS_ID                    VARCHAR2(25),
  INTERNAL_GMR_REF_NO           VARCHAR2(50),
  INTERNAL_GRD_REF_NO           VARCHAR2(50),
  INTERNAL_CONTRACT_REF_NO      VARCHAR2(50),
  INTERNAL_CONTRACT_ITEM_REF_NO VARCHAR2(50),
  TYPICAL                       NUMBER(35,10),
  ELEMENT_ID                    VARCHAR2(25),
  PCPQ_ID                       VARCHAR2(25),
  PCDI_ID                       VARCHAR2(25),
  GMR_REF_NO                    VARCHAR2(50),
  ELEMENT_NAME                  VARCHAR2(50),
  PAYABLE_QTY                   NUMBER(25,10),
  PAYABLE_QTY_UNIT_ID           VARCHAR2(15),
  PAY_CUR_DECIMALS              NUMBER
);

CREATE INDEX IDX_GMR_RC_CONT1 ON GMR_RC_CONT(CORPORATE_ID)
/
DROP TABLE GMR_RC_QAT;
CREATE TABLE GMR_RC_QAT
(
  CORPORATE_ID        VARCHAR2(50),
  INTERNAL_GMR_REF_NO VARCHAR2(50),
  PCPQ_ID             VARCHAR2(25),
  ELEMENT_ID          VARCHAR2(25)
);
CREATE INDEX IDX_GMR_RC_QAT1 ON GMR_RC_QAT(CORPORATE_ID)
/
 alter table FOR_FEED_ORIGINAL_REPORT add  GMR_REF_NO VARCHAR2 (30);
 alter table FOR_FEED_ORIGINAL_REPORT add  INTERNAL_GMR_REF_NO VARCHAR2 (15); 
 alter table FEOR_FEED_ELE_ORIGINAL_REPORT  add INTERNAL_GMR_REF_NO VARCHAR2 (15);

CREATE INDEX IDX_AROAR_1 ON ARO_AR_ORIGINAL_REPORT(PROCESS_ID)
/
CREATE INDEX IDX_AREOAR_1 ON AREOR_AR_ELE_ORIGINAL_REPORT(PROCESS_ID)
/
CREATE INDEX IDX_FOROR_1 ON FOR_FEED_ORIGINAL_REPORT(PROCESS_ID)
/
CREATE INDEX IDX_FEOROR_1 ON FEOR_FEED_ELE_ORIGINAL_REPORT(PROCESS_ID)
/
