alter table IS_INVOICE_SUMMARY add IS_INVOICE_NEW_YTD CHAR(1);
alter table PROCESS_GMR add IS_INVOICE_NEW_YTD CHAR(1);
alter table GMR_GOODS_MOVEMENT_RECORD add IS_INVOICE_NEW_YTD CHAR(1);
alter table TGC_TEMP_GMR_CHARGES add IS_INVOICE_NEW_YTD CHAR(1);
