drop table TEMP_PLEDGE_QTY;
CREATE  TABLE TEMP_PLEDGE_QTY
(CORPORATE_ID         VARCHAR2 (15),
INTERNAL_GRD_REF_NO   VARCHAR2 (15),
ELEMENT_ID            VARCHAR2 (15),
GEPD_ID               VARCHAR2 (15),
PAYABLE_QTY           NUMBER (25,10));


CREATE INDEX IDX_TEMP_PLEDGE_QTY1 ON TEMP_PLEDGE_QTY(CORPORATE_ID)