ALTER TABLE TRGMR_TEMP_RGMR ADD (
IS_MC_CHANGE_FOR_SALES VARCHAR2(1) DEFAULT 'N',
IS_MC_CHANGE_FOR_PURCHASE VARCHAR2(1) DEFAULT 'N');

ALTER TABLE RGMR_REALIZED_GMR ADD (
IS_MC_CHANGE_FOR_SALES VARCHAR2(1) DEFAULT 'N',
IS_MC_CHANGE_FOR_PURCHASE VARCHAR2(1) DEFAULT 'N');

ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD IS_FINAL_INVOICED VARCHAR2(1) DEFAULT 'N';
ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD IS_PROVISIONAL_INVOICED VARCHAR2(1) DEFAULT 'N';

