ALTER TABLE CSUL_COST_STORE_UL ADD IS_ACTUAL_POSTED_IN_COG VARCHAR2(1);
ALTER TABLE CS_COST_STORE ADD IS_ACTUAL_POSTED_IN_COG VARCHAR2(1);

ALTER TABLE TINVP_TEMP_INVM_COG ADD
(TRANSACT_AMT_SIGN NUMBER(1));

ALTER TABLE TINVS_TEMP_INVM_COGS ADD
(TRANSACT_AMT_SIGN NUMBER(1));


