ALTER TABLE PSUE_PHY_STOCK_UNREALIZED_ELE ADD PRICE_DESCRIPTION VARCHAR2(4000);

DROP TABLE GSC_GMR_SEC_COST;

CREATE TABLE TGSC_TEMP_GMR_SEC_COST
(
  CORPORATE_ID                   VARCHAR2(15 BYTE),
  PROCESS_ID                     VARCHAR2(15 BYTE),
  INTERNAL_COST_ID               VARCHAR2(15 BYTE),
  COST_TYPE                      VARCHAR2(25 BYTE),
  INTERNAL_GRD_REF_NO            VARCHAR2(15 BYTE),
  INTERNAL_GMR_REF_NO            VARCHAR2(15 BYTE),
  PRODUCT_ID                     VARCHAR2(15 BYTE),
  BASE_QTY_UNIT_ID               VARCHAR2(15 BYTE),
  BASE_QTY_UNIT                  VARCHAR2(15 BYTE),
  GRD_CURRENT_QTY                NUMBER,
  GRD_QTY_UNIT_ID                VARCHAR2(15 BYTE),
  COST_VALUE                     NUMBER,
  TRANSFORMATION_RATIO           NUMBER,
  TRANSACTION_PRICE_UNIT_ID      VARCHAR2(15 BYTE),
  TRANSACTION_CUR_FACTOR         NUMBER,
  TRANSACTION_AMT_CUR_ID         VARCHAR2(15 BYTE),
  TRANSACTION_AMT_MAIN_CUR_ID    VARCHAR2(15 BYTE),
  BASE_CUR_ID                    VARCHAR2(15 BYTE),
  BASE_CUR_CODE                  VARCHAR2(15 BYTE),
  BASE_PRICE_UNIT_ID             VARCHAR2(15 BYTE),
  BASE_PRICE_UNIT_ID_IN_PPU      VARCHAR2(15 BYTE),
  PRICE_QTY_UNIT_ID              VARCHAR2(15 BYTE),
  PRICE_WEIGHT                   NUMBER,
  PRICE_TO_STOCK_WT_CONVERSION   NUMBER,
  VALUE_IN_TRANSACT_CURRENCY     NUMBER(25,5),
  TRANSACT_TO_BASE_FW_EXCH_RATE  NUMBER,
  TRANS_TO_BASE_FW_EXCH_RATE     VARCHAR2(25 BYTE),
  STOCK_TO_BASE_WT_CONVERSION    NUMBER,
  VALUE_IN_BASE_CURRENCY         NUMBER(25,5),
  AVG_COST                       NUMBER,
  TRANSACT_AMT_SIGN              NUMBER(1),
  PAYMENT_DUE_DATE               DATE);

  ALTER TABLE PSUE_PHY_STOCK_UNREALIZED_ELE
ADD (INCOTERM_ID VARCHAR2(15),
INCOTERM VARCHAR2(15),
CONTRACT_RC_TC_PEN_STRING VARCHAR2(4000));

