UPDATE RML_REPORT_MASTER_LIST set IS_ACTIVE ='N' where REPORT_ID in('213','216');

UPDATE AMC_APP_MENU_CONFIGURATION
SET IS_DELETEd='Y'
WHERE MENU_ID in ('RPT-D224','RPT-D225');

ALTER TABLE DGRD_DELIVERED_GRD ADD TOLLING_STOCK_TYPE VARCHAR2(30);
ALTER TABLE DGRDUL_DELIVERED_GRD_UL ADD TOLLING_STOCK_TYPE VARCHAR2(30);
