alter table PSU_PHY_STOCK_UNREALIZED add (CP_NAME varchar2(100),CP_PROFILE_ID varchar2(30));

CREATE TABLE CRE_CP_RISK_EXPOSURE
(
  PROCESS_ID                VARCHAR2(20 CHAR),
  PROCESS_DATE              DATE,
  PROCESS                   VARCHAR2(5 CHAR),
  CORPORATE_ID              VARCHAR2(15 CHAR),
  GROUP_ID                  VARCHAR2(15 CHAR),
  GROUP_NAME                VARCHAR2(50 CHAR),
  PRODUCT_ID                VARCHAR2(15 CHAR),
  PRODUCT_NAME              VARCHAR2(200 CHAR),
  PROFIT_CENTER_ID          VARCHAR2(15 CHAR),
  PROFIT_CENTER_NAME        VARCHAR2(30 CHAR),
  PROFIT_CENTER_SHORT_NAME  VARCHAR2(30 CHAR),
  CONTRACT_TYPE             VARCHAR2(1 CHAR),
  CP_PROFILE_ID             VARCHAR2(15 CHAR),
  CP_NAME                   VARCHAR2(100 CHAR),
  QTY_EXPOSURE              NUMBER(25,4),
  QTY_EXP_UNIT_ID           VARCHAR2(15 CHAR),
  QTY_EXP_UNIT              VARCHAR2(15 CHAR),
  VALUE_EXPOSURE            NUMBER(25,4),
  VALUE_EXP_CUR_ID          VARCHAR2(15 CHAR),
  VALUE_EXP_CUR_CODE        VARCHAR2(15 CHAR),
  M2M_EXPOSURE              NUMBER(25,4),
  M2M_EXP_CUR_ID            VARCHAR2(15 CHAR),
  M2M_EXP_CUR_CODE          VARCHAR2(15 CHAR),
  CREDIT_EXPOSURE           NUMBER(25,4),
  CREDIT_EXP_CUR_ID         VARCHAR2(15 CHAR),
  CREDIT_EXP_CUR_CODE       VARCHAR2(15 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

CREATE TABLE TRE_TRADER_RISK_EXPOSURE
(
  PROCESS_ID                VARCHAR2(20 CHAR),
  PROCESS_DATE              DATE,
  PROCESS                   VARCHAR2(5 CHAR),
  CORPORATE_ID              VARCHAR2(15 CHAR),
  GROUP_ID                  VARCHAR2(15 CHAR),
  GROUP_NAME                VARCHAR2(50 CHAR),
  PRODUCT_ID                VARCHAR2(15 CHAR),
  PRODUCT_NAME              VARCHAR2(200 CHAR),
  PROFIT_CENTER_ID          VARCHAR2(15 CHAR),
  PROFIT_CENTER_NAME        VARCHAR2(30 CHAR),
  PROFIT_CENTER_SHORT_NAME  VARCHAR2(30 CHAR),
  CONTRACT_TYPE             VARCHAR2(1 CHAR),
  TRADER_USER_ID            VARCHAR2(15 CHAR),
  TRADER_USER_NAME          VARCHAR2(50 CHAR),
  QTY_EXPOSURE              NUMBER(25,4),
  QTY_EXP_UNIT_ID           VARCHAR2(15 CHAR),
  QTY_EXP_UNIT              VARCHAR2(15 CHAR),
  VALUE_EXPOSURE            NUMBER(25,4),
  VALUE_EXP_CUR_ID          VARCHAR2(15 CHAR),
  VALUE_EXP_CUR_CODE        VARCHAR2(15 CHAR),
  M2M_EXPOSURE              NUMBER(25,4),
  M2M_EXP_CUR_ID            VARCHAR2(15 CHAR),
  M2M_EXP_CUR_CODE          VARCHAR2(15 CHAR),
  CREDIT_EXPOSURE           NUMBER(25,4),
  CREDIT_EXP_CUR_ID         VARCHAR2(15 CHAR),
  CREDIT_EXP_CUR_CODE       VARCHAR2(15 CHAR)
)
LOGGING 
NOCOMPRESS 
NOCACHE
NOPARALLEL
MONITORING
/

alter table pps_physical_pnl_summary add(
product_id VARCHAR2(15 CHAR)      ,           
product_name VARCHAR2(100 CHAR)   ) 
/
alter table tpd_trade_pnl_daily add(
INSTRUMENT_ID      VARCHAR2(15 CHAR)      ,           
INSTRUMENT_NAME      VARCHAR2(100 CHAR)   )      
/

