ALTER TABLE spql_stock_payable_qty_log ADD 
(ASSAY_CONTENT NUMBER(25,10), PLEDGE_STOCK_ID VARCHAR2(20), GEPD_ID VARCHAR2(15), 
ASSAY_HEADER_ID VARCHAR2(15), IS_FINAL_ASSAY CHAR(1) DEFAULT 'N',CORPORATE_ID  VARCHAR2(15));


ALTER TABLE SPQ_STOCK_PAYABLE_QTY ADD 
(ASSAY_CONTENT NUMBER(25,10), PLEDGE_STOCK_ID VARCHAR2(20), GEPD_ID VARCHAR2(15), 
ASSAY_HEADER_ID VARCHAR2(15), IS_FINAL_ASSAY CHAR(1) DEFAULT 'N',CORPORATE_ID  VARCHAR2(15));