CREATE TABLE CCCP_CONC_CONTRACT_COG_PRICE(
PROCESS_ID                     VARCHAR2(20 ),
CORPORATE_ID                   VARCHAR2(15 ),
PCDI_ID                        VARCHAR2(15 ),
INTERNAL_CONTRACT_REF_NO       VARCHAR2(15 ),
CONTRACT_REF_NO                VARCHAR2(30 ),
ELEMENT_ID                     VARCHAR2(15 ),
PAYABLE_QTY                    NUMBER(25,5),
PAYABLE_QTY_UNIT_ID            VARCHAR2(15 ),
CONTRACT_PRICE                 NUMBER(25,5),
PRICE_UNIT_ID                  VARCHAR2(15 ),
PRICE_UNIT_CUR_ID              VARCHAR2(15 ),
PRICE_UNIT_CUR_CODE            VARCHAR2(15 ),
PRICE_UNIT_WEIGHT              NUMBER(7,2),
PRICE_UNIT_WEIGHT_UNIT_ID      VARCHAR2(15 ),
PRICE_UNIT_WEIGHT_UNIT         VARCHAR2(15 ),
FIXED_QTY                      NUMBER(15),
UNFIXED_QTY                    NUMBER(15),
PRICE_BASIS                    VARCHAR2(10));

CREATE TABLE CGCP_CONC_GMR_COG_PRICE(
PROCESS_ID                     VARCHAR2(20 ),
CORPORATE_ID                   VARCHAR2(15 ),
INTERNAL_GMR_REF_NO            VARCHAR2(15 ),
GMR_REF_NO                     VARCHAR2(15 ),
ELEMENT_ID                     VARCHAR2(15 ),
PAYABLE_QTY                    NUMBER(25,5),
PAYABLE_QTY_UNIT_ID            VARCHAR2(15 ),
CONTRACT_PRICE                 NUMBER(25,5),
PRICE_UNIT_ID                  VARCHAR2(15 ),
PRICE_UNIT_CUR_ID              VARCHAR2(15 ),
PRICE_UNIT_CUR_CODE            VARCHAR2(15 ),
PRICE_UNIT_WEIGHT              NUMBER(7,2),
PRICE_UNIT_WEIGHT_UNIT_ID      VARCHAR2(15 ),
PRICE_UNIT_WEIGHT_UNIT         VARCHAR2(15 ),
FIXED_QTY                      NUMBER(15),
UNFIXED_QTY                    NUMBER(15),
PRICE_BASIS                    VARCHAR2(10));

CREATE TABLE BCCP_BASE_CONTRACT_COG_PRICE(
PROCESS_ID                     VARCHAR2(20 ),
CORPORATE_ID                   VARCHAR2(15 ),
PCDI_ID                        VARCHAR2(15 ),
INTERNAL_CONTRACT_REF_NO       VARCHAR2(15 ),
CONTRACT_REF_NO                VARCHAR2(30 ),
DELIVERY_QTY                   NUMBER(25,10),
QTY_UNIT_ID                    VARCHAR2(15 ),
CONTRACT_PRICE                 NUMBER(25,10),
PRICE_UNIT_ID                  VARCHAR2(15 ),
PRICE_UNIT_CUR_ID              VARCHAR2(15 ),
PRICE_UNIT_CUR_CODE            VARCHAR2(15 ),
PRICE_UNIT_WEIGHT              NUMBER(7,2),
PRICE_UNIT_WEIGHT_UNIT_ID      VARCHAR2(15 ),
PRICE_UNIT_WEIGHT_UNIT         VARCHAR2(15 ),
FIXED_QTY                      NUMBER(15),
UNFIXED_QTY                    NUMBER(15),
PRICE_BASIS                    VARCHAR2(10));

CREATE TABLE BGCP_BASE_GMR_COG_PRICE(
PROCESS_ID                     VARCHAR2(20 ),
CORPORATE_ID                   VARCHAR2(15 ),
INTERNAL_GMR_REF_NO            VARCHAR2(15 ),
GMR_REF_NO                     VARCHAR2(15 ),
QTY                            NUMBER(25,5),
QTY_UNIT_ID                    VARCHAR2(15 ),
CONTRACT_PRICE                 NUMBER(25,5),
PRICE_UNIT_ID                  VARCHAR2(15 ),
PRICE_UNIT_CUR_ID              VARCHAR2(15 ),
PRICE_UNIT_CUR_CODE            VARCHAR2(15 ),
PRICE_UNIT_WEIGHT              NUMBER(7,2),
PRICE_UNIT_WEIGHT_UNIT_ID      VARCHAR2(15 ),
PRICE_UNIT_WEIGHT_UNIT         VARCHAR2(15 ),
FIXED_QTY                      NUMBER(15),
UNFIXED_QTY                    NUMBER(15),
PRICE_BASIS                    VARCHAR2(10));

CREATE TABLE CR_CUSTOMS_REPORT (
PROCESS_ID                      VARCHAR2(15),
INTERNAL_CONTRACT_REF_NO        VARCHAR2(15),
CONTRACT_REF_NO                 VARCHAR2(30),
DELIVERY_ITEM_NO            VARCHAR2(30),
CORPORATE_ID                    VARCHAR2(15),
CORPORATE_NAME                  VARCHAR2(100),
SMELTER_ID                      VARCHAR2(15),
SMELTER_NAME                    VARCHAR2(100),
SUPPLIER_ID                     VARCHAR2(15),
SUPPLIER_NAME                   VARCHAR2(100),
QUALITY_ID                      VARCHAR2(15),
QUALITY_NAME                    VARCHAR2(100),
INTERNAL_INVOICE_REF_NO         VARCHAR2(15),
INVOICE_REF_NO                  VARCHAR2(15),
INVOICE_DATE                    DATE,
INTERNAL_GMR_REF_NO             VARCHAR2(15),
GMR_REF_NO                      VARCHAR2(30),
PRODUCT_ID                      VARCHAR2(15),
PRODUCT_NAME                    VARCHAR2(100),
SHIPMENT_DATE                   DATE, 
LOADING_COUNTRY_ID              VARCHAR2(15),
LOADING_COUNTRY                 VARCHAR2(100),
LOADING_STATE_ID                VARCHAR2(15),
LOADING_STATE                   VARCHAR2(100),
LOADING_CITY_ID                 VARCHAR2(15),
LOADING_CITY                    VARCHAR2(100),
DISCHARGE_COUNTRY_ID            VARCHAR2(15),
DISCHARGE_COUNTRY               VARCHAR2(100),
DISCHARGE_STATE_ID              VARCHAR2(15),
DISCHARGE_STATE                 VARCHAR2(100),
DISCHARGE_CITY_ID               VARCHAR2(15),
DISCHARGE_CITY                  VARCHAR2(100),
LOADING_NATIONAL_CUR_ID         VARCHAR2(15),
LOADING_NATIONAL_CUR_CODE       VARCHAR2(15),
DISCHARGE_NATIONAL_CUR_ID       VARCHAR2(15),
DISCHARGE_NATIONAL_CUR_CODE     VARCHAR2(15),
NO_OF_CONTAINERS                NUMBER(5),
INCOTERM_ID                     VARCHAR2(15),
INCOTERM                        VARCHAR2(15),
CFX_INVENT_OR_INVOICE_TO_BASE   NUMBER(25,10),
BASE_CUR_ID                     VARCHAR2(15),
BASE_CUR_CODE                   VARCHAR2(15),
CFX_BASE_TO_LOADING_COUNTRY     NUMBER(25,10),
CFX_BASE_TO_DISCHARGE_COUNTRY   NUMBER(25,10),
QTY                             NUMBER(25,10),
QTY_UNIT_ID                     VARCHAR2(15),
QTY_UNIT                        VARCHAR2(15),
INVOICE_EFF_DATE                DATE,
GMR_EFF_DATE                    DATE,
FINAL_INVOICE_DATE              DATE,
INVOICE_VALUE                   NUMBER(25,10),
INVOICE_CUR_ID                  VARCHAR2(15),
INVOICE_CUR_CODE                VARCHAR2(15),
INVENTORY_CUR_ID                VARCHAR2(15),
INVENTORY_CUR_CODE              VARCHAR2(15));

CREATE TABLE MAS_METAL_ACCOUNT_SUMMARY
(
  PROCESS_ID             VARCHAR2 (15 Char),
  EOD_TRADE_DATE         DATE,
  CORPORATE_ID           VARCHAR2(15 Char),
  CORPORATE_NAME         VARCHAR2(50 Char),  
  PRODUCT_ID             VARCHAR2(15 CHAR),
  PRODUCT_DESC           VARCHAR2(200 CHAR),
  POSITION_TYPE          VARCHAR2(50 CHAR),
  STOCK_TYPE             VARCHAR2(50 BYTE),
  SECTION_NAME           VARCHAR2(50 CHAR),
  SECTION_ORDER          VARCHAR2(10 CHAR),
  WAREHOUSE_PROFILE_ID   VARCHAR2(15 CHAR),
  WAREHOUSENAME          VARCHAR2(65 CHAR),
  STOCK_QTY              NUMBER(25,5),
  QTY_UNIT_ID            VARCHAR2(15 CHAR),
  QTY_UNIT               VARCHAR2(15 CHAR)
);



CREATE TABLE MD_METAL_DEBT
(PROCESS_ID     VARCHAR2(15),
 CORPORATE_ID   VARCHAR2(15),
 PRODUCT_ID     VARCHAR2(15),
 PRODUCT_NAME   VARCHAR2(60),
 STOCK_QTY      NUMBER(25,10),
 DEBT_QTY      NUMBER(25,10),
 NET_QTY      NUMBER(25,10),
 QTY_UNIT_ID    VARCHAR2(15),
 QTY_UNIT       VARCHAR2(15));

CREATE MATERIALIZED VIEW  SBS_SMELTER_BASE_STOCK  REFRESH FAST ON DEMAND WITH PRIMARY KEY AS  SELECT * FROM  SBS_SMELTER_BASE_STOCK@eka_appdb;
CREATE MATERIALIZED VIEW  PRRQS_PRR_QTY_STATUS  REFRESH FAST ON DEMAND WITH PRIMARY KEY AS  SELECT * FROM  PRRQS_PRR_QTY_STATUS@eka_appdb;

ALTER TABLE GMRUL_GMR_UL ADD
(MODE_OF_TRANSPORT VARCHAR2 (15),        
ARRIVAL_DATE DATE,        
WNS_STATUS VARCHAR2 (10));		

ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD
(MODE_OF_TRANSPORT VARCHAR2 (15),        
ARRIVAL_DATE DATE,        
WNS_STATUS VARCHAR2 (10));        

ALTER TABLE ISR_INTRASTAT_GRD ADD IS_NEW VARCHAR2(1) DEFAULT 'N';
