ALTER TABLE POUED_ELEMENT_DETAILS ADD(
REAL_CONTRACT_PRICE NUMBER (35,10),
REAL_PRICE_UNIT_ID  VARCHAR2 (15),
REAL_PRICE_UNIT_CUR_ID VARCHAR2(15),        
REAL_PRICE_UNIT_CUR_CODE VARCHAR2 (15),        
REAL_PRICE_UNIT_WEIGHT_UNIT_ID VARCHAR2 (15),        
REAL_PRICE_UNIT_WEIGHT NUMBER (7,2),
REAL_PRICE_UNIT_WEIGHT_UNIT VARCHAR2 (15),
PREV_CONTRACT_VALUE_IN_BASE   NUMBER (35,10));