ALTER TABLE POUE_PHY_OPEN_UNREAL_ELEMENT ADD
(LOCATION_PREMIUM_PER_UNIT NUMBER(25,10),
LOCATION_PREMIUM NUMBER(25,10),
LOCATION_PREMIUM_FW_EXCH_RATE VARCHAR2(50));

ALTER TABLE PSUE_PHY_STOCK_UNREALIZED_ELE ADD
(LOCATION_PREMIUM_PER_UNIT NUMBER(25,10),
LOCATION_PREMIUM NUMBER(25,10),
LOCATION_PREMIUM_FW_EXCH_RATE VARCHAR2(50));

ALTER TABLE PRCH_PHY_REALIZED_CONC_HEADER ADD
(LOCATION_PREMIUM_PER_UNIT NUMBER(25,10),
LOCATION_PREMIUM  NUMBER(25,10),
LOCATION_PREMIUM_FW_EXCH_RATE VARCHAR2(50),
PREV_LOCATION_PREMIUM_PER_UNIT  NUMBER(25,10),
PREV_LOCATION_PREMIUM  NUMBER(25,10),
P_LOC_PREMIUM_FW_EXCH_RATE VARCHAR2(50));

