ALTER TABLE POUED_ELEMENT_DETAILS ADD (PRICE_TO_BASE_FW_EXCH_RATE VARCHAR2(50));
ALTER TABLE INVME_COG_ELEMENT ADD PRICE_TO_BASE_FW_EXCH_RATE VARCHAR2(50);
ALTER TABLE INVME_COGS_ELEMENT ADD PRICE_TO_BASE_FW_EXCH_RATE VARCHAR2(50);