create table TEMP_GMR_INVOICE
(
  PROCESS_ID                varchar2(15 char),
  CORPORATE_ID              VARCHAR2(15 CHAR),
  INTERNAL_INVOICE_REF_NO   VARCHAR2(15 CHAR),
  STOCK_ID                  VARCHAR2(15 CHAR),
  INVOICE_ITEM_AMOUNT       NUMBER(25,10),
  INVOICE_CURRENCY_ID       VARCHAR2(15 CHAR),
  NEW_INVOICE_PRICE         NUMBER(25,10),
  INVOICE_TYPE              VARCHAR2(25 CHAR),
  INVOICE_ISSUE_DATE        DATE,
  NEW_INVOICE_PRICE_UNIT_ID VARCHAR2(15 CHAR)
);