ALTER TABLE stock_monthly_yeild_data MODIFY(YIELD_PCT NUMBER(25,5));
DROP MATERIALIZED VIEW  YPD_YIELD_PCT_DETAIL;
CREATE MATERIALIZED VIEW  YPD_YIELD_PCT_DETAIL  REFRESH FAST ON DEMAND WITH PRIMARY KEY AS  SELECT * FROM  YPD_YIELD_PCT_DETAIL@eka_appdb;