CREATE TABLE FC_FEED_CONSUMPTION
(
  PROCESS_ID           VARCHAR2(15 CHAR),
  EOD_TRADE_DATE       DATE,
  CORPORATE_ID         VARCHAR2(15 CHAR),
  CORPORATE_NAME       VARCHAR2(100 CHAR),
  GMR_REF_NO           VARCHAR2(30 CHAR),
  INTERNAL_GMR_REF_NO  VARCHAR2(15 CHAR),
  INTERNAL_GRD_REF_NO  VARCHAR2(15 CHAR),
  STOCK_REF_NO         VARCHAR2(50 CHAR),
  PRODUCT_ID           VARCHAR2(15 CHAR),
  PRODUCT_NAME         VARCHAR2(200 CHAR),
  QUALITY_ID           VARCHAR2(15 CHAR),
  QUALITY_NAME         VARCHAR2(50 CHAR),
  PILE_NAME            VARCHAR2(50 CHAR),
  PARENT_GMR_REF_NO    VARCHAR2(30 CHAR), 
  WAREHOUSE_ID         VARCHAR2(50),
  WAREHOUSE_NAME       VARCHAR2(100),
  SHED_ID              VARCHAR2(15),
  SHED_NAME            VARCHAR2(50),
  GRD_WET_QTY          NUMBER(25,5),
  GRD_DRY_QTY          NUMBER(25,5),
  GRD_QTY_UNIT_ID      VARCHAR2(15 CHAR),
  GRD_QTY_UNIT         VARCHAR2(15 CHAR)
   );

  CREATE TABLE FCE_FEED_CONSUMPTION_ELEMENT
  (PROCESS_ID           VARCHAR2(15 CHAR),
  INTERNAL_GMR_REF_NO  VARCHAR2(15 CHAR),
  INTERNAL_GRD_REF_NO  VARCHAR2(15 CHAR),
  ELEMENT_ID           VARCHAR2(15 CHAR),
  ELEMENT_NAME         VARCHAR2(15 CHAR),
  ASSAY_QTY            NUMBER(25,5),
  ASAAY_QTY_UNIT_ID    VARCHAR2(15 CHAR),
  ASAAY_QTY_UNIT       VARCHAR2(15 CHAR),
  PAYABLE_QTY          NUMBER(25,5),
  PAYABLE_QTY_UNIT_ID  VARCHAR2(15 CHAR),
  PAYABLE_QTY_UNIT     VARCHAR2(15 CHAR)
  );

alter table GRDL_GOODS_RECORD_DETAIL_LOG add SUPP_INTERNAL_GMR_REF_NO VARCHAR2(15);
alter table GRD_GOODS_RECORD_DETAIL add SUPP_INTERNAL_GMR_REF_NO VARCHAR2(15);


CREATE MATERIALIZED VIEW  PSR_POOL_STOCK_REGISTER  REFRESH FAST ON DEMAND WITH PRIMARY KEY AS  SELECT * FROM  PSR_POOL_STOCK_REGISTER@eka_appdb;
CREATE MATERIALIZED VIEW  PM_POOL_MASTER  REFRESH FAST ON DEMAND WITH PRIMARY KEY AS  SELECT * FROM  PM_POOL_MASTER@eka_appdb;

