ALTER TABLE TINVP_TEMP_INVM_COG ADD (GMR_QTY NUMBER(25,5));
ALTER TABLE TGSC_TEMP_GMR_SEC_COST ADD GMR_GRD_QTY NUMBER (25,5);
ALTER TABLE GMR_GOODS_MOVEMENT_RECORD ADD STOCK_CURRENT_QTY NUMBER(25,5);
ALTER TABLE TINVS_TEMP_INVM_COGS RENAME COLUMN  GRD_CURRENT_QTY  TO ORIGINAL_INV_QTY;
ALTER TABLE TINVS_TEMP_INVM_COGS RENAME COLUMN  GRD_QTY_UNIT_ID  TO INV_QTY_UNIT_ID;





