drop table PA_TEMP;
create table PA_TEMP
(
  INTERNAL_GMR_REF_NO      VARCHAR2(20),
  INTERNAL_GRD_REF_NO      VARCHAR2(20),
  INTERNAL_CONTRACT_REF_NO VARCHAR2(20),
  GMR_REF_NO               VARCHAR2(50),
  CORPORATE_ID             VARCHAR2(20),
  PRODUCT_ID               VARCHAR2(20),
  QUALITY_ID               VARCHAR2(20),
  PROFIT_CENTER_ID         VARCHAR2(20),
  INVOICE_CURRENCY_ID      VARCHAR2(20),
  ELEMENT_ID               VARCHAR2(20),
  CONTRACT_TYPE            VARCHAR2(20),
  ASSAY_QTY                NUMBER(35,5),
  ASSAY_QTY_UNIT           VARCHAR2(20),
  PAYBLE_QTY               NUMBER(35,5),
  PAYABLE_QTY_UNIT         VARCHAR2(20),
  ELEMENT_PAYABLE_AMOUNT   NUMBER(35,5),
  TCHARGES_AMOUNT          NUMBER(35,5),
  RCHARGES_AMOUNT          NUMBER(35,5),
  PENALTY_AMOUNT           NUMBER(35,5)
);

create index IDX_PA_TEMP1 on PA_TEMP (CORPORATE_ID);
create index IDX_PA_TEMP2 on PA_TEMP (CORPORATE_ID,INTERNAL_GMR_REF_NO,INTERNAL_GRD_REF_NO);

CREATE TABLE TEMP_MAS
(
PROCESS_ID            VARCHAR2(15),
CORPORATE_ID          VARCHAR2(15),
CORPORATE_NAME        VARCHAR2(50),
QUERY_SECTION_NAME    VARCHAR2(50),
PRODUCT_ID            VARCHAR2(15),
PRODUCT_DESC          VARCHAR2(200),
POSITION_TYPE         VARCHAR2(50),
STOCK_TYPE            VARCHAR2(50),
SECTION_NAME          VARCHAR2(50),
SECTION_ORDER         VARCHAR2(10),
WAREHOUSE_PROFILE_ID  VARCHAR2(15),
WAREHOUSENAME         VARCHAR2(65),
STOCK_QTY             NUMBER(25,5),
STOCK_QTY_UNIT_ID     VARCHAR2(15),
PRODUCT_BASE_QTY_UNIT_ID VARCHAR2(15),
QTY_UNIT              VARCHAR2(15));

CREATE INDEX IDX_TEMP_MAS1 ON TEMP_MAS(CORPORATE_ID);
