ALTER TABLE TEMP_FCR ADD

(PRODUCT_BASE_QTY_UNIT_ID VARCHAR2(15),

PRODUCT_BASE_QTY_UNIT VARCHAR2(15));

ALTER TABLE FCR_FEED_CONSUMPTION_REPORT ADD

(PRODUCT_BASE_QTY_UNIT_ID VARCHAR2(15),

PRODUCT_BASE_QTY_UNIT VARCHAR2(15));

DROP TABLE DPR_DAILY_POSITION_RECORD CASCADE CONSTRAINTS;

CREATE TABLE DPR_DAILY_POSITION_RECORD
(
  TRADE_DATE        DATE,
  CORPORATE_ID      VARCHAR2(15),
  PRODUCT_ID        VARCHAR2(15),
  PROFIT_CENTER_ID  VARCHAR2(15),
  BUSINESS_LINE_ID  VARCHAR2(15),
  FIXED_QTY         NUMBER(25,10),
  QUOTATIONAL_QTY   NUMBER(25,10),
  PROCESS_ID        VARCHAR2(15)
);

