ALTER TABLE EOD_EOM_PHY_CONTRACT_JOURNAL ADD (attribute_1 VARCHAR2(100));
ALTER TABLE EOD_EOM_PHY_CONTRACT_JOURNAL ADD (attribute_2 VARCHAR2(100));
ALTER TABLE EOD_EOM_PHY_CONTRACT_JOURNAL ADD (attribute_3 VARCHAR2(100));
ALTER TABLE EOD_EOM_PHY_CONTRACT_JOURNAL ADD (attribute_4 VARCHAR2(100));
ALTER TABLE EOD_EOM_PHY_CONTRACT_JOURNAL ADD (attribute_5 VARCHAR2(100));