drop table eod_eom_phy_booking_journal;
create table eod_eom_phy_booking_journal
(section_name     varchar2(15),
corporate_id      varchar2(15),
corporate_name    VARCHAR2(100),
product_id        varchar2(15),
product_desc      varchar2(200),
counter_party_id  varchar2(15),
counter_party_name  varchar2(65),
invoice_quantity    number(35,5),
invoice_quantity_uom  varchar2(15),
fx_base               number(35,5),
profit_center_id      varchar2(15),
profit_center         varchar2(35),
strategy_id           varchar2(15),
strategy_name         varchar2(30),
base_cur_id           varchar2(15),
base_currency         varchar2(25),
invoice_ref_no        varchar2(30),
contract_ref_no       varchar2(50),
internal_contract_ref_no  varchar2(15),
invoice_cur_id        varchar2(15),
pay_in_currency       varchar2(25),
amount_in_base_cur    number(35,5),
invoice_amt           number(35,5),
invoice_date          date,
invoice_due_date      date,
invoice_type          varchar2(25),
bill_to_cp_country    varchar2(300),
delivery_item_ref_no  varchar2(25),
vat_amount            number(35,5),
vat_remit_cur_id      varchar2(15),
vat_remit_currency    varchar2(25),
fx_rate_for_vat       number(35,5),
vat_amount_base_currency  number(35,5),
commission_value          number(20,5),
commission_value_ccy      varchar2(25),
attribute1                varchar2(50),
attribute2                varchar2(50),
attribute3                varchar2(50),
attribute4                varchar2(50),
attribute5                varchar2(50),
process_id                varchar2(5),
process                   varchar2(10),
eod_run_date              date,
eod_date                  date,
process_run_count         varchar2(3)
);

create index eepj_idx on eod_eom_phy_booking_journal (corporate_id,process_id,process);