alter table SPQL_STOCK_PAYABLE_QTY_LOG add WEG_AVG_PRICING_ASSAY_ID varchar2(15);
alter table SPQL_STOCK_PAYABLE_QTY_LOG add WEG_AVG_INVOICE_ASSAY_ID varchar2(15);
alter table SPQ_STOCK_PAYABLE_QTY add WEG_AVG_PRICING_ASSAY_ID varchar2(15);
alter table SPQ_STOCK_PAYABLE_QTY add WEG_AVG_INVOICE_ASSAY_ID varchar2(15);


CREATE TABLE GETC_GMR_ELEMENT_TC_CHARGES
(PROCESS_ID                     VARCHAR2(15),
INTERNAL_GMR_REF_NO             VARCHAR2(15),
INTERNAL_GRD_REF_NO             VARCHAR2(15),
GMR_REF_NO                      VARCHAR2(15),
ELEMENT_ID                      VARCHAR2(15),
ELEMENT_NAME                    VARCHAR2(30),
PRICE                           NUMBER(25,10),
PRICE_UNIT_ID                   VARCHAR2(15),
PRICE_CUR_ID                   VARCHAR2(15),
PRICE_WEIGHT_UNIT_ID            VARCHAR2(15),
TC_VALUE                        NUMBER(25,10),
TC_CUR_ID                       VARCHAR2(15),
TC_WEIGHT_UNIT_ID               VARCHAR2(15));


CREATE TABLE GERC_GMR_ELEMENT_RC_CHARGES
(PROCESS_ID                     VARCHAR2(15),
INTERNAL_GMR_REF_NO             VARCHAR2(15),
INTERNAL_GRD_REF_NO             VARCHAR2(15),
GMR_REF_NO                      VARCHAR2(15),
ELEMENT_ID                      VARCHAR2(15),
ELEMENT_NAME                    VARCHAR2(30),
PRICE                           NUMBER(25,10),
PRICE_UNIT_ID                   VARCHAR2(15),
PRICE_CUR_ID                   VARCHAR2(15),
PRICE_WEIGHT_UNIT_ID            VARCHAR2(15),
RC_VALUE                        NUMBER(25,10),
RC_CUR_ID                       VARCHAR2(15),
RC_WEIGHT_UNIT_ID               VARCHAR2(15));

CREATE TABLE GEPC_GMR_ELEMENT_PC_CHARGES
(PROCESS_ID                     VARCHAR2(15),
INTERNAL_GMR_REF_NO             VARCHAR2(15),
INTERNAL_GRD_REF_NO             VARCHAR2(15),
GMR_REF_NO                      VARCHAR2(15),
ELEMENT_ID                      VARCHAR2(15),
ELEMENT_NAME                    VARCHAR2(30),
PC_VALUE                        NUMBER(25,10),
PC_CUR_ID                       VARCHAR2(15),
PC_WEIGHT_UNIT_ID               VARCHAR2(15));


ALTER TABLE FCE_FEED_CONSUMPTION_ELEMENT ADD(UNDERLYING_PRODUCT_ID  VARCHAR2(15),
					     UNDERLYING_BASE_QTY_UNIT_ID  VARCHAR2(15),
					     ORIGINAL_ASAAY_QTY_UNIT_ID VARCHAR2(15),
					     ORIGINAL_PAYABLE_QTY_UNIT_ID  VARCHAR2(15),
					     PAYABLE_RETURNABLE_TYPE VARCHAR2 (30),        
					     TC_AMOUNT NUMBER (25,10),        
					     RC_AMOUNT NUMBER (25,10),        
					     PENALITY_AMOUNT NUMBER (25,10),
					     ORIGINAL_PAYABLE_QTY NUMBER(25,10),
					     PARENT_INTERNAL_GMR_REF_NO VARCHAR2(15),
					     PARENT_INTERNAL_GRD_REF_NO VARCHAR2(15));


ALTER TABLE FC_FEED_CONSUMPTION ADD (ORIGINAL_GRD_QTY NUMBER (25,10),
				     ORIGINAL_GRD_QTY_UNIT_ID VARCHAR2(15),
			             DRY_WET_QTY_RATIO NUMBER (25,10),
                                     PAY_CUR_ID VARCHAR2(15 ),    
				     PAY_CUR_CODE VARCHAR2 (15),
                                     PARENT_INTERNAL_GMR_REF_NO VARCHAR2(15),
				     PARENT_INTERNAL_GRD_REF_NO VARCHAR2(15));


ALTER TABLE PA_PURCHASE_ACCURAL_GMR ADD(QUALITY_ID   VARCHAR2(15),
					QUALITY_NAME  VARCHAR2(100));

ALTER TABLE PA_PURCHASE_ACCURAL ADD (QUALITY_ID    VARCHAR2(15),
				     QUALITY_NAME  VARCHAR2(100));

ALTER TABLE PA_TEMP ADD (QUALITY_NAME  VARCHAR2(100));

ALTER TABLE PATD_PA_TEMP_DATA ADD(QUALITY_ID    VARCHAR2(15),
				  QUALITY_NAME   VARCHAR2(100));


DROP MATERIALIZED VIEW PFD_PRICE_FIXATION_DETAILS;
DROP TABLE PFD_PRICE_FIXATION_DETAILS;
CREATE MATERIALIZED VIEW  PFD_PRICE_FIXATION_DETAILS  REFRESH FAST ON DEMAND WITH PRIMARY KEY AS  SELECT * FROM  PFD_PRICE_FIXATION_DETAILS@eka_appdb;


