ALTER TABLE CBRE_CLOSING_BAL_REPORT_ELE ADD(
CONTRACT_PRICE NUMBER (25,5), 
PRICE_UNIT_ID VARCHAR2 (15),
PARENT_INTERNAL_GMR_REF_NO VARCHAR2 (15)); 

ALTER TABLE POUD_PHY_OPEN_UNREAL_DAILY ADD REAL_PRICE_TO_BASE_FW_RATE VARCHAR2(50);
