CREATE INDEX IDX_POCD1 ON POCD_PRICE_OPTION_CALLOFF_DTLS(IS_ACTIVE,POCH_ID,PCBPD_ID);
CREATE INDEX IDX_GPAH1 ON GPAH_GMR_PRICE_ALLOC_HEADER(IS_ACTIVE,INTERNAL_GMR_REF_NO,ELEMENT_ID);
CREATE INDEX IDX_GPAD1 ON GPAD_GMR_PRICE_ALLOC_DTLS(IS_ACTIVE,GPAH_ID);
CREATE INDEX IDX_POCH1 ON POCH_PRICE_OPT_CALL_OFF_HEADER(IS_ACTIVE);
CREATE INDEX IDX_PFD1 ON PFD_PRICE_FIXATION_DETAILS(IS_ACTIVE, POFH_ID);
CREATE INDEX IDX_POFH1 ON POFH_PRICE_OPT_FIXATION_HEADER(IS_ACTIVE,POFH_ID,POCD_ID);
DROP INDEX IDX_GRD2;
CREATE INDEX IDX_GRD2 ON GRD_GOODS_RECORD_DETAIL(PROCESS_ID,IS_DELETED,STATUS);