CREATE TABLE TYYTD_TEMP_YIELD_YTD(
INTERNAL_GMR_REF_NO            VARCHAR2(15),
ELEMENT_ID                     VARCHAR2(15),
GMR_REF_NO                     VARCHAR2(35),
CORPORATE_ID                   VARCHAR2(15),
ELEMENT_NAME                  VARCHAR2(30),
ELEMENT_PRODUCT_ID             VARCHAR2(15),
ELEMENT_PRODUCT_NAME           VARCHAR2(100),
YIELD_PCT                      NUMBER(25,5),
CURRENT_QTY                    NUMBER(20,5),
QTY_UNIT_ID                    VARCHAR2(15),
YTD_YEAR                       VARCHAR2(4),
YTD_MONTH                      VARCHAR2(3),
YTD_GROUP_COLUMN               VARCHAR2(10));

CREATE TABLE TYS_TEMP_YIELD_STOCK(
CORPORATE_ID  VARCHAR2(15),
INTERNAL_GMR_REF_NO            VARCHAR2(15),
INTERNAL_GRD_REF_NO            VARCHAR2(15),
ELEMENT_ID                    VARCHAR2(15),
TOTAL_QTY_IN_WET            NUMBER(25,10),
TOTAL_QTY_IN_DRY            NUMBER(25,10),
WTDAVGPOSTION_ASH_ID        VARCHAR2(15),
LATEST_ASSAY_ID                VARCHAR2(15),
UNIT_OF_MEASURE                VARCHAR2(15),
TYPICAL                        NUMBER(25,10),        
FINALIZATION_METHOD            VARCHAR2(50),    
IS_FINAL_ASSAY                VARCHAR2(1),    
ASSAY_WINNER                VARCHAR2(50),
IS_ELEM_FOR_PRICING            VARCHAR2(1),
IS_DEDUCTIBLE                VARCHAR2(1),
IS_RETURNABLE                VARCHAR2(1),
CP_ID                        VARCHAR2(15),
CONC_PRODUCT_ID                VARCHAR2(15),    
CONC_QTY_UNIT_ID            VARCHAR2(15),
CONC_QTY_UNIT                VARCHAR2(15));

CREATE INDEX IDX_TYYTD1 ON TYYTD_TEMP_YIELD_YTD (CORPORATE_ID);
CREATE INDEX IDX_TYS1 ON TYS_TEMP_YIELD_STOCK (CORPORATE_ID);
